### ISSUE TITLE
Incorrect transaction amount reported on pending transactions

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1004]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| v2019-11-07    | Windows & OSX & Linux) | Code |

# Context
 
 

![Screenshot 2019-11-11 at 15 02 03](https://user-images.githubusercontent.com/5680256/68602342-71e2e980-04a6-11ea-900c-13b86a2a4ed3.png)

# Steps to Reproduce

1. Make a transaction
2. Observe the reported amount while pending
3. Compare the amount once not pending anymore

## Expected behavior

- They match

## Actual behavior
 
<A clear and concise description of what you observe instead. If applicable add screenshots to help explain your problem.>

- They are different, amount is bigger when pending

---

# Resolution Plan

- Seems to be a very old bug :grimacing: ... The outputs are completely ignored in the computation of pending tx metadata when signing a transaction. Only the changes are taken into account!

# PR

| Number   | Base      |
| ---      | ---       |
| #1005 | `master` |
| #1010 | `master` |

# QA 

- Added a regression scenario and saw it fails: https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core-integration/src/Test/Integration/Scenario/API/Transactions.hs#L143-L159

- Then, fixed the metadata calculation by also taking our outputs into account instead of only change. Regression test passes and all other tests still do.

**Comment by piotr-iohk** [comment]
lgtm. I have only refactored the test script a bit -> #1010.
