### ISSUE TITLE
Compute metadata for transaction

### ISSUE THREAD

**Issue by akegalj** [cardano-foundation/cardano-wallet#101]
# Context

A real wallet implementation may need to store more information than we have modelled in the specification so far. For instance, users may wish to know when their pending transactions got confirmed in the blockchain (as opposed to merely that they were confirmed), or what the effect was of a particular transaction on their balance (rather than merely being able to see the current balance).

# Decision

Compute and maintain metadata for every transaction tracked by the wallet (transactions send to/from the wallet). 

# Acceptance Criteria

1. Tx metadata _must_ contain `unique identifier` (probably tx id)
2. Tx metadata _must_ contain `depth` (a.k.a "number of confirmations)
3. Tx metadata _must_ contain `status`: pending vs in-ledger vs invalidated
4. Tx metadata _must_ contain `total amount`
5. Tx metadata _must_ contain `direction`: outgoing vs incoming
6. Tx metadata _must_ contain `timestamp` when transaction was created
7. Tx metadata _must_ contain info about `absolute slot & block number the transaction was inserted (from genesis)`

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #114       | `master`  |

# QA

**Comment by KtorZ** [comment]
This was done as part of #137 . This ticket is actually redundant with #90 so closing in favor of the latter.
