### ISSUE TITLE
Chain follower does not backoff on errors

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#1027]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Windows & OSX & Linux) | Code  v Configuration v Environment v Human v Unknown |

# Context
 
 

# Steps to Reproduce

Add `throwIO $ userError "no"` to `monitorStakePools`. The `follow` machinery should catch it. Or be on a revision/configuration that will error anyways.

## Expected behavior

Errors are logged when it retries. The time between retries gets longer and longer. (backoff)

E.g. something like this
```
[iohk.cardano-wallet.stake-pools:Error:ThreadId 33] [2019-11-14 09:58:34.68 UTC] Recoverable error following the chain: Enum.toEnum{Word16}: tag (82756) is outside of bounds (0,65535)
[iohk.cardano-wallet.stake-pools:Error:ThreadId 33] [2019-11-14 09:58:34.68 UTC] Sleeping 2000000
[iohk.cardano-wallet.stake-pools:Error:ThreadId 33] [2019-11-14 09:58:36.69 UTC] Recoverable error following the chain: Enum.toEnum{Word16}: tag (82756) is outside of bounds (0,65535)
[iohk.cardano-wallet.stake-pools:Error:ThreadId 33] [2019-11-14 09:58:36.69 UTC] Sleeping 4000000
[iohk.cardano-wallet.stake-pools:Error:ThreadId 33] [2019-11-14 09:58:40.69 UTC] Recoverable error following the chain: Enum.toEnum{Word16}: tag (82756) is outside of bounds (0,65535)
[iohk.cardano-wallet.stake-pools:Error:ThreadId 33] [2019-11-14 09:58:40.69 UTC] Sleeping 8000000
[iohk.cardano-wallet.stake-pools:Error:ThreadId 33] [2019-11-14 09:58:48.70 UTC] Recoverable error following the chain: Enum.toEnum{Word16}: tag (82756) is outside of bounds (0,65535)
[iohk.cardano-wallet.stake-pools:Error:ThreadId 33] [2019-11-14 09:58:48.70 UTC] Sleeping 16000000
```

## Actual behavior
 
It retries and prints a **lot of** errors continuously without ever increasing the retryDelay.

# Resolution Plan

- The first delay is `0` because we don't actually need it to sleep when we start it.
- Quick fix: let it sleep for `1 s` when we start it.

# PR

| Number   | Base      |
| ---      | ---       |
| #1028         | `master` |
| #1031        | `master` |

# QA 

Test -> #1031

**Comment by piotr-iohk** [comment]
lgtm.
