### ISSUE TITLE
Daedalus IPC working intermittently on windows

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1036]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| v2019-11-12 | Windows | Environment v Code |

# Context
 
 

On some machines, Daedalus remains stuck to the splash screen after starting the wallet backend. From looking at the logs, it seems that it never actually receives a `Started` message from the wallet backend IPC server. 

This is somewhat strange and suggest that it'd take too long for Daedalus to put their listen handler on the process in such a way that they would miss the initial `Started` message now sent very early by the wallet backend.

# Steps to Reproduce

1. Start Daedalus on Windows
2. Wait a few seconds and see if stuck on the splash screen
3. Retry until getting stuck
4. When stucked, look at the wallet backend log and see if Jörmungandr has started

## Expected behavior

1. Daedalus doesn't remain stuck and can advance their initial state-machine to the next step

## Actual behavior

1. It does

---

# Resolution Plan

- ~Retry sending `Started` until we receive a first sign of life for Daedalus (i.e. a `QueryPort` request)~
- Rather than starting the send and receive async tasks together, run the message write and read functions in turn.

# PR

| Number   | Base      |
| ---      | ---       |
| #1037 | |
| #1044       | `master` |

# QA 

1. Get a Windows build of Daedalus Testnet Balance check with this fix.
2. Test in both "cold" and "warm" cases (relating to whether jormungandr has completed the bootstrap phase). The issue seems to happen more often in the "warm" case.
3. Check for presence of "Started" and "ReplyPort" in Daedalus log. This means that the IPC process completed. Alternatively, look for the wallet api port in the connection status screen.

**Comment by rvl** [comment]
Sending IPC messages down the ipc channel on Windows seems to block on sending the 3rd message. From that point on the daedalusIPC function is stuck.

I have added a test case on the [rvl/1036/daedalus-ipc-race](https://github.com/input-output-hk/cardano-wallet/compare/rvl/1036/daedalus-ipc-race) branch.

**Comment by piotr-iohk** [comment]
lgtm.
