### ISSUE TITLE
Byron addresses have derivation indexes that are not only hardened.

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1041]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| v2019-11-14    | Windows & OSX & Linux) | Code  v Human |

# Context
 
 

Addresses in `Byron` uses HD derivation with 3 levels: root, account and addresses.
It was believed that Byron addresses indexes used only hardened derivation, i.e. they would range from `2^31=2147483648` to `2^32=4294967296`. 

However, some addresses and in particular change addresses embed derivation indexes that range from outside of the hardened domain (e.g. `1594290073` was found in a mainnet address). 

This appeared to has been fixed in `cardano-sl` in:

```
commit 4ebc883d4f08ffa13d3bce74e71792a3a54aeb42
Author: Edward Tate <edward.tate@iohk.io>
Date:   Tue Nov 28 12:01:26 2017 -0400

    [CSL-1955] Updated generateUnique to always generate hardened addresses and removed orM.
```

released somewhere between March 2018 and June 2018. So any old wallet before these dates have been using non-hardened indexes for addresses. 

# Steps to Reproduce

1. Not all wallets are affected as they need to have addresses with indexes outside of the hardened domain.
2.  Wallets need to be old enough, when Daedalus was still running on `v0` in cardano-sl@1.2.0, or cardano-sl@1.1.1 or cardano-sl@1.1.0.

## Expected behavior

1. Addresses that belong to a wallet should be discovered!

## Actual behavior
 
<A clear and concise description of what you observe instead. If applicable add screenshots to help explain your problem.>

1. Some addresses are missing.

---

# Resolution Plan

- [x] Use another type of derivation index specially for Byron addresses that can go over the whole range (hardened and non hardened).

 - [x] ~Assess whether this is also true for the account path?~ Confirmed by looking at old versions of Cardano, accounts indexes were used using the same buggy function and are therefore subject to the same rule. We need to reflect this in code.

- [x] Curse Serokell one more time.

# PR

| Number   | Base      |
| ---      | ---       |
| #1042       | `master` |
| #1055       | `master` |

# QA 

- Hard to reproduce since this occurred on old addresses that were carrying a wrong payload. Payloads are however encrypted with a passphrase derived from the root public key. Without this, we can't reliably know whether or not the fix solved issues of users.

- We've however tried out with @Anviking's wallet for which the fix has been successful.

- Additionally, the fixed version shipped to users has solved most user issues but _a few_. From those, it appears that they've been trying again using an old version of Daedalus which didn't include the fix. 

- Added an extra golden test in the address discovery spec for random derivation about an address which carries non-hardened derivation index. This more as a regression test to make sure that this bug isn't re-introduced in the future. (see: https://github.com/input-output-hk/cardano-wallet/pull/1055)

**Comment by piotr-iohk** [comment]
lgtm.
