### ISSUE TITLE
getStakePoolMetadata - fetches data from registry

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#1064]
# Context

Part of [WB-25 Collect stake pool metadata](https://jira.iohk.io/projects/WB/issues/WB-25).

Given that metadata for registered stake pools are available in https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry
And are stored in a "registry" folder as JSON objects matching the JSON meta-schema given in annex below
When I fetch all available metadata using a zip archive https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/archive/master.zip
Then I can associate corresponding metadata to known stake pools.

The registry looks like this: [input-output-hk/testnet-stake-pool-registry/registry](https://github.com/input-output-hk/testnet-stake-pool-registry/tree/master/registry)

The files are in this format:

```json
{
  "title": "Stake-pool Metadata",
  "type": "object",
  "required": [
    "id",
    "ticker",
    "homepage",
    "pledge_address"
  ],
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string",
      "format": "bech32"
    },
    "ticker": {
      "type": "string",
      "minLength": 3,
      "maxLength": 4
    },
    "homepage": {
      "type": "string",
      "format": "uri"
    },
    "pledge_address": {
      "type": "string",
      "format": "bech32"
    }
  }
}
```

# Decision

```haskell
-- | Top-level function to associate a list of stake pool IDs with their
-- metadata (if present), which is downloaded from GitHub.
getStakePoolMeta :: URI -> [PoolId] -> IO (Either FetchError [Maybe StakePoolMeta])

-- | Fetch and extract a zip archive to the given location,
-- which ought to have been created using 'withSystemTempDirectory.
fetchStakePoolMetaZip :: URI -> FilePath -> IO (Either FetchError ())

-- | Given a directory containing the extracted metadata files,
-- try to read and parse the json file for a poolid.
-- Any validation/parse error is unexpected and results in a big fat error,
-- because the data should already be validated.
findStakePoolMeta :: FilePath -> PoolId -> IO (Either FetchError (Maybe StakePoolMeta))

-- | Currently hardcoded.
cardanoFoundationRegistryZip :: URI
cardanoFoundationRegistryZip = "https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/archive/master.zip
"
```

The splitting up of these functions is just a sketch, but it should be
done in a way that is easily testable at the unit level.

The [`Codec.Archive.Zip`](http://hackage.haskell.org/package/zip-1.2.0/docs/Codec-Archive-Zip.html) library looks suitable to me. For downloading, `http-conduit` would be simple. And for parsing, the Aeson instances have already been written.

# Acceptance Criteria

1. The function must download a registry zip and return metadata for the requested pool ids.
2. The zip download URL may be user configurable in the app, but hardcoded is also fine. However the function signature permits a `URI` as config so that integration tests can hit a local URL.
3. Good practice recommends that entire zip files should not be loaded into memory.

---

# Development 

1. It turned out better to download the zip to a temporary file and read entries from it, rather than extracting it to a temporary directory ⇒ PR #1069.
2. The unit tests set up a static web server to serve test case registries.
3. The testing zip files are randomly generated.
 
# QA 

1. Cardano.Pool.RegistrySpec has unit tests with test specs based on the example zip, as well as a property test with valid, invalid, and missing entries.

**Comment by piotr-iohk** [comment]
lgtm.
