### ISSUE TITLE
listStakePools - Include metadata in API responses

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#1065]
# Context

Part of [WB-25 Collect stake pool metadata](https://jira.iohk.io/projects/WB/issues/WB-25).

Extend the response of `listStakePools` with a `metadata` matching those from the registry (minus the `id`).
For known stake pools which aren't present in the registry the metadata entry should be `Nothing` / `null`.

# Decision

Add a function to look up metadata by `PooId`. This will first need to find the pool owners of the known stake pools, then use `getStakePoolMeta` to find metadata from the owners.

Adjust `Cardano.Wallet.Api.Server.listPools` to  augment the response with this information.

### Integration tests

Integration tests ought to be configured with an alternative URL, so that they are self-contained. This testing file can be served up with [`Network.Wai.Application.Static`](http://hackage.haskell.org/package/wai-app-static-3.1.6.3/docs/Network-Wai-Application-Static.html#v:staticApp).

The `master.zip` served by the integration tests should correspond with our stake-pools in test setup, but that also covers following cases:
 - data of the stake pool that does not exist in our integration setup
 - missing data for one of the stake pools that we have in the integration setup (for which stake-pool the metadata returned by the request would be null)

The case that `master.zip` is not available at the location should be covered by integration tests.

# Acceptance Criteria

1. Available metadata about stake pools must be included with the API response.
2. Integration tests should not require downloading from external URLs.
3. Conflicting metadata from multiple owners must result in no metadata being presented by cardano-wallet.

---

# Development 

1. Add the logic described aboce to `StakePoolLayer.listStakePools` to keep the web handler clean.
1. Update/add unit tests of listStakePools to include metadata.
1. Allow environment variable override of stake pool registry URL for integration (and other) testing.
1. Integration test fixtures will need stake pool registrations added, if not already done.
1. Update/add integration tests of listStakePools.
1. Print the registry in use at start-up ==> TODO

# QA 

1. The `CARDANO_WALLET_STAKE_POOL_REGISTRY_URL` environment variable can be set for ad-hoc manual testing of stake pool listing.
2. The URL of the registry in use is logged when the metadata is downloaded.
3. There are unit tests added in `lib/core/test/unit/Cardano/Pool/MetricsSpec.hs`. These test `associateMetadata`, which is the guts of the logic for adding metadata. Regrettably, this is not a proper unit test of `Cardano.Pool.Metrics.listStakePools`, but more like testing of the implementation.
4. Integration tests are updated in `lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/API/StakePools.hs`: `STAKE_POOLS_LIST_01` and `STAKE_POOLS_LIST_04` so that metadata is also checked.

**Comment by piotr-iohk** [comment]
Kind reminder (and ask) to add the way to point to custom registry via ENV variable to aid checking behavior on testnets... :pray: :)

**Comment by piotr-iohk** [comment]
lgtm.

Also checked on nightly testnet with custom registry -> https://github.com/piotr-iohk/incentivized-testnet-stakepool-registry
