### ISSUE TITLE
Implement quitStakePool endpoint

### ISSUE THREAD

**Issue by paweljakubas** [cardano-foundation/cardano-wallet#1074]
# Context

When it comes to certificate delegation we want a way to join (already done) and to quit already joined stake pool. 

# Decision
We implement `quitStakePool` endpoint.
 

# Acceptance Criteria

1. `quitStakePool` sends request to Jormungandr to quit delegation. We can observe it later in the coming block, when accommodated, as (ChimericAccount, Nothing.). Nothing comes from capturing of DlgNone.
2.  `quitStakePool` results in error when WalletDelegation is in NonDelegating state.
3.  Signature of the correponding binary functions should return `(Chimeric Account, Maybe PoolId)` and DB representation is to be changed accordingly. Moreover, we need to store rows : `(SlotId, ChimericAccount, Maybe PoolId)` to support rollbacks.
4. Stake pool integration test should be adjusted.

---

# Development 

| Number   | Base      |
| ---      | ---       |
| #1080         | `master`  |
| #1083          | `master`  |
| #1084            | `master`  |

# QA

**Comment by KtorZ** [comment]
@paweljakubas 

> Signature of the correponding binary functions should return (Chimeric Account, Maybe PoolId) and DB representation is to be changed accordingly. Moreover, we need to store rows : (SlotId, ChimericAccount, Maybe PoolId) to support rollbacks.

minus `ChimericAccount`. This isn't stored in the database (or at least, not in the DelegationCertificate table).

**Comment by piotr-iohk** [comment]
lgtm.
