### ISSUE TITLE
Required adjustments for stake pool metadata

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#1076]
# Context

Part of [WB-25 Collect stake pool metadata](https://jira.iohk.io/projects/WB/issues/WB-25).

There have been changes to the stake pool registry so that metadata are associated with stake pool owners rather than stake pool IDs.

Additionally, more metadata fields need to be added.

The relevant issue is input-output-hk/testnet-stake-pool-registry-validator#2

# Decision

* Stake pool metadata is now associated with a stake pool owner public key rather than `PoolId`.

* A registered stake pool (identified by `PoolId`) may have more than one owner.

* An owner (identified by a public key) may be registered with multiple stake pools.

* If multiple stake pool owners publish metadata for their stake pool, the metadata fields must all be exactly the same (modulo `owner`). Otherwise, cardano-wallet shall produce no metadata at all for that pool.

* If a stake pool owner is associated with multiple pools, the metadata is re-used for all pools he owns, though the previous rule applies.

* When applying blocks, the wallet extracts the owner(s) associated with stake pool registrations and stores them in the database. This is a many-to-many association of PoolId to public key.

* We can still assume validation and authentication of metadata is done by the registry validator and cardano-wallet can trust what is downloaded.

* Add the extra metadata fields and update the tests accordingly.

# Acceptance Criteria

1. The extra metadata fields must be added to the types, JSON codecs, and API spec.

(Other tickets contain more AC.)

---

# Development 

- Update types, swagger schema, and test data ⇒ #1078.
- Add `poolRegistrations :: (PoolId, [PoolOwner])` as a new field of `Block` ⇒ #1090.
- Adjust binary decoders to include pool registrations blocks ⇒ #1089.
- Wait for #1050 to be merged - then add a new result to applyBlocks, which is the pool registrations including `[PoolOwner]` ⇒ #1090.
- Add a new database table for mapping `PooId` ↔ `PoolOwner` ⇒ #1091.
- Add queries to insert, delete, and look up pool owners by pool id ⇒ #1091.
- `getStakePoolMetadata` should take a list of `PoolOwner` rather than `PoolId` ⇒ #1078.
- The function which gets metadata for pools should query the database to get relevant pool owners ⇒ #1065.

# QA 

1. `lib/core/test/unit/Cardano/Pool/MetadataSpec.hs` has been updated to match the new registry format.

**Comment by KtorZ** [comment]
@rvl 

> Stake pool metadata is now associated with a stake pool owner XPub rather than PoolId.

Note that, the `X` in `XPub` stands for `eXtended`, which refers to a public key + a chain code (typically 64 bits in total).  

Here, metadata will be identified by 32-bit public keys.

**Comment by rvl** [comment]
OK corrected. This is starting to look like it should be split into more issues.

**Comment by KtorZ** [comment]
@rvl You may be right. The JSON updates are quite straightforward I think. The indirection however requires additional logic to map owners to  pool correctly and also, to extract the owner from the blocks which we currently don't do. So I'd say at least 3 issues yes.

**Comment by piotr-iohk** [comment]
OK, It was not quite clear to me what is the status of this one because there are quite a few issues linked in the **Development** section, which are still opened. 

If I understand correctly that this particular issue corresponds to pr -> https://github.com/input-output-hk/cardano-wallet/pull/1078 (in terms of work done), and the rest is still in progress.

**Comment by piotr-iohk** [comment]
lgtm. 

Just a few comments/questions but on related issues:
 - https://github.com/input-output-hk/cardano-wallet/issues/1091#issuecomment-562107518
 - https://github.com/input-output-hk/cardano-wallet/issues/1065#issuecomment-562109207
