### ISSUE TITLE
Create `epochCeiling` function.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#1086]
# Context

In order to support the ability for users to query the API about the _next epoch_, we need a function capable of calculating the next epoch _number_ from _any given time_.

# Decision

Create a new function within `Cardano.Wallet.Primitive.Types` with a definition similar to:
```hs
epochCeiling :: SlotParameters -> UTCTime -> EpochNo
epochCeiling sp time =
```

# Acceptance Criteria

1. There _must_ be a `epochCeiling` function in `Wallet.Primitive.Types`.
2. The result of calling `epochCeiling` _must_ be the earliest epoch number whose start time is greater than or equal to the specified time.
---

# Development 

- [x] Add `epochCeiling` function.

# QA 

- [x] Add property tests for the `epochCeiling` function.

# PRs

| Number | Base |
| -- | -- |
| #1114 | `master` |
| #1121 | `master` |

**Comment by paweljakubas** [comment]
Task goals/development plan looking good and clear. Nevertheless, I would give here `2` mainly due to `nextEpochAfter` testing

**Comment by piotr-iohk** [comment]
lgtm!
