### ISSUE TITLE
Create `ApiEpochInfo` type.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#1087]
# Context

In order to support the ability for users to query the API about the _next epoch_, we need to provide an API type that contains this information.

# Decision

Create a new type in `Cardano.Wallet.Api.Types` with a definition similar to:
```hs
data ApiEpochInfo = ApiEpochInfo
    { epochNumber :: !(ApiT EpochNo) 
    , epochStartTime :: !Iso8601Time  
    } deriving (Eq, Generic, Show)
```

# Acceptance Criteria

- [x] There _must_ be an `ApiEpochInfo` type with fields that encode an epoch's _number_ and _start time_.
- [x] There _must_ be roundtrip JSON encoding support for the `ApiEpochInfo` type.

# Development 

- [x] Add `ApiEpochInfo` type.
- [x] Add roundtrip JSON encoding support.

# QA 

- [x] Add roundtrip JSON encoding tests.

**Comment by paweljakubas** [comment]
Task goals/development plan looking good and clear

**Comment by piotr-iohk** [comment]
lgtm!
