### ISSUE TITLE
Implement Jörmungandr binary decoder for stake pool registrations

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#1089]
# Context

We need to decode pool registrations in order to track the mapping from `PoolId` to `PoolOwner`.

# Decision

In relation to [format.abnf](https://github.com/input-output-hk/chain-libs/blob/master/chain-impl-mockchain/doc/format.abnf), implement decoders for fragments:

- 5 `POOL-REGISTRATION`
- ~6 `POOL-RETIREMENT`~

And add them to the Jormungandr block `Fragment` type.

Note that 7 `POOL-UPDATE` in the spec is a `TODO` stub so it can be ignored.

The only information that cardano-wallet requires from pool registrations is:
- Stake pool ID
- owner

# Acceptance Criteria

- Pool registrations must be in the jormungandr Block type.
- ~Pool retirements must be in the jormungandr Block type.~

---

# Development 

0. Move pool retirements out of scope, in to WB-40.
1. Implement binary decoder as specified ⇒ #1093.
2. Use jcli to generate golden test data ⇒ #1093

# QA 

1. The golden tests for fragments with stake pool registration certificates are in `BinarySpec.hs`.

**Comment by piotr-iohk** [comment]
lgtm.
