### ISSUE TITLE
Add a database mapping for registered stake pool owners

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#1091]
# Context

In order to provide stake pool metadata, the wallet must track the mapping from `PoolId` to `PoolOwner`.

# Decision

In `Cardano.Pool.DB` add the following database table:

```
PoolOwner sql=pool_owner
    poolOwnerPoolId     W.PoolId     sql=pool_id
    poolOwnerOwner      W.PoolOwner  sql=pool_owner
    -- poolOwnerSlot        W.SlotId     sql=slot
    -- poolOwnerSlotRetired W.SlotId Maybe sql=slot_retired
    deriving Show Generic
```

This is a many-to-many relation by the way.

Add DBLayer functions:

```haskell
putStakePoolOwner :: DBLayer m -> SlotId -> PoolId -> PoolOwner -> m ()
-- deleteStakePoolOwners :: DBLayer m -> SlotId -> PoolId -> m ()
readStakePoolOwners :: DBLayer m -> PoolId -> m [PoolOwner]
```

Note that reading stake pool owners for a list of stake pools will not be very efficient, but let's ignore that until will start caching stake pool metadata in the database.

~Rollback is handled by recording the slots when an owner was registered/deregistered.~

# Acceptance Criteria

1. The stake pool owner mapping must be stored in the DB and be queryable.

---

# Development 

1. Implement per _Decision_ section.
2. Add stake pool owners to the model DB and state machine tests.

# QA 

1. The `putStakePoolOwner` and `readStakePoolOwners` functions are tested together in `Cardano.Pool.DB.Properties`.

**Comment by rvl** [comment]
For the time being we are not concerned about handling stake pool retirement certificates, nor rollback. The mapping may contain stale entries, but the entries which aren't stale will still be correct. [WB-40](https://jira.iohk.io/projects/WB/issues/WB-40)

**Comment by piotr-iohk** [comment]
This will require db migration, correct?

**Comment by KtorZ** [comment]
Probably _not_ because it's a new table. So it'll be part of the initial migration `CREATE TABLE IF NOT EXISTS` that are ran automatically by persistent.

_I think_

**Comment by piotr-iohk** [comment]
lgtm
