### ISSUE TITLE
Update stake pool registrations in the restore loop

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#1092]
# Context

In order to provide stake pool metadata, the wallet must track the mapping from `PoolId` to `PoolOwner`.

# Decision

Combine the results of #1090 and #1091.

When processing filtered blocks in the stake pool restore loop, update the `pool_owner` table.

# Acceptance Criteria

1. The `pool_owner` table must reflect the stake pool registrations and retirements received in the jormungandr block fragments. (i.e. the wallet must track stake pool registrations and their owners).

---

# Development 

1. As above ⇒ PR #1154.
2. Unit testing is tricky because the logic is locked inside `monitorStakePools`.

# QA 

There is a property test in `lib/core/test/unit/Cardano/Pool/MetricsSpec.hs`.

The integration test will come with #1065.

**Comment by piotr-iohk** [comment]
lgtm
