### ISSUE TITLE
Add API endpoint for delegation fee estimation

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#1096]
# Context

Users of the API would like to know the cost of joining a stake-pool before pulling the trigger.

In this task we implement the API, leveraging the work of #1094. 

# Decision

Add the following endpoint:
```yaml
/wallets/\{walletId\}/delegations/fees: 
    get: 
      operationId: getDelegationFee
      tags: ["Stake Pools"]
      summary: Estimate Fee
      parameters: 
        - *parametersWalletId
      responses: *responsesGetDelegationFee

x-responsesGetDelegationFee: &responsesGetDelegationFee
  <<: *responsesErr403
  <<: *responsesErr404
  <<: *responsesErr405
  <<: *responsesErr406
  200:
    description: Ok
    schema: *ApiFee
```

# Acceptance Criteria

- The endpoint _must_ be implemented
- JSON roundtrip tests for any added Api-types _should_ exist
- The endpoint _should_ be tested with integration tests

---

# Development 

- #1116 

# QA 

- Added integration test scenarios here: https://github.com/input-output-hk/cardano-wallet/blob/decdad3e649ae9278d47815926d729ee56e25941/lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/API/StakePools.hs#L515-L558

**Comment by jonathanknowles** [comment]
We might want to add integration tests to check that:
- The _eventual_ fee paid for joining a stake pool is similar or identical to the _estimated_ delegation fee (similar to `BYRON_MIGRATE_03`).
- The estimated delegation fee for a non-empty wallet is `> 0` (similar to `BYRON_CALCULATE_01`).
- Attempting to calculate a delegation fee for an empty wallet produces an appropriate error (similar to `BYRON_CALCULATE_02`).
- Attempting to calculate a delegation fee for a non-Shelley wallet produces an appropriate error (similar to `BYRON_CALCULATE_03`).
- Attempting to calculate a delegation fee for a non-existing wallet produces an appropriate error (similar to `BYRON_CALCULATE_04`).

**Comment by jonathanknowles** [comment]
@KtorZ I've added a question regarding the original requirement here: https://jira.iohk.io/browse/WB-32?focusedCommentId=11089&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-11089

(The question is aimed at clarifying whether or not this endpoint should really be an HTTP GET operation, or whether the endpoint really does require a user-supplied payload, in which case we will indeed need a POST operation.)

**Comment by piotr-iohk** [comment]
Few more tests would be handy on negative cases side of things. Also there is no assertion check for the `200` http status code for most basic fee request.

**Comment by piotr-iohk** [comment]
Fee estimation also does not show correct amount -> https://github.com/input-output-hk/cardano-wallet/issues/1150 (the amount does not correspond with genesis.yaml parameters -> some more info also here https://input-output-rnd.slack.com/archives/GBT05825V/p1575876039070100)

**Comment by Anviking** [comment]
> Few more tests would be handy on negative cases side of things

@piotr-iohk what kind of negative tests would you like to see? There are already [three](https://github.com/input-output-hk/cardano-wallet/blob/c2ee747de248cfba8ec0345a7a2c96450063ef71/lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/API/StakePools.hs#L558-L585)

**Comment by piotr-iohk** [comment]
> @piotr-iohk what kind of negative tests would you like to see? There are already three

They are good indeed!
Just added 2 more to test against 405 and 406 -> #1170.

**Comment by piotr-iohk** [comment]
ok.
