### ISSUE TITLE
Add Jormungadr client measuring latencies of GET queries within integration test framework 

### ISSUE THREAD

**Issue by paweljakubas** [cardano-foundation/cardano-wallet#1097]
# Context

We want to have a way to query in regular fashion our API (GET endpoints) that informs us of latencies

# Decision

We add dedicated Jormungandr integration test suite (we want to reuse what is already done) that calls GET endpoints and measures the latencies for a given intial state of Jormungandr based wallet.

# Acceptance Criteria

1. We can invoke a client that talks with existing instance of Jormungadr wallet, calls the following endpoint : 
```
https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/listWallets
https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/getWallet
https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/getUTxOsStatistics
https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/listAddresses
https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/listTransactions
https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/postTransactionFee
https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/listStakePools
https://input-output-hk.github.io/cardano-wallet/api/edge/#tag/Network
```
2. The client use reasonable benchmarking technique, criterion, and emits statistics

---

# Development 

# PR

| Number   | Base      |
| ---      | ---       |
| #1105  |  `master`  |

# QA 
In order to test/run the latency benchmark do the following : 
```
$ stack bench cardano-wallet-jormungandr
cardano-wallet-jormungandr> benchmarks  
Running 1 benchmarks...                 
Benchmark latency: RUNNING...           
Latencies for two fixture wallets scenario
    listWallets        - 20.2 ms        
    getWallet          - 11.1 ms        
    getUTxOsStatistics - 1.9 ms         
    listAddresses      - 7.1 ms         
    listTransactions   - 2.5 ms         
    postTransactionFee - 1.7 ms         
    listStakePools     - 1.2 ms         
    getNetworkInfo     - 0.4 ms         
Benchmark latency: FINISH
```

**Comment by piotr-iohk** [comment]
Looks good. 

Although not mentioned in the original AC (cause it was not there yet I suppose), maybe also `delegation fee ep` could be added. It seems that it might be also heavily used, hence kind of critical.
