### ISSUE TITLE
Implement necessary CBOR decoders (block and block header)

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#11]
# Context

The [cardano-http-bridge](https://github.com/input-output-hk/cardano-http-bridge) has a rather basic API where data can be retrieved in a binary format. The format used is a mix between the format used on a cardano-sl (a custom-made encoding / decoding protocol built on top of [CBOR](http://cbor.io/) and some custom [packfile](https://github.com/input-output-hk/rust-cardano/blob/master/storage-units/src/packfile.rs) created by the Rust team.  

See https://github.com/KtorZ/wallet-prototype/blob/master/app/Main.hs#L973 for starter.

# Decision

We want the ability to _at least_ decode those binary data in order to be able to use the `cardano-http-bridge` as an initial middle-man.

- [ ] We _must_ be able to decode our wallet primitive types from CBOR 
- [ ] We _should_ use the [cborg](https://hackage.haskell.org/package/cborg-0.2.1.0) library from hackage (same one used by `cardano-sl`) to minimize the risk with implementation details 
- [ ] We _may_ discard unnecessary information from blocks and only retrieve what we need

---

# Development Plan

- [x] Look at `cardano-chain` repo for inspiration.
- [x] Copy&paste decoders implemented in the prototype.
- [x] Add golden tests for decoders.
- [x] No need to add `ToCBOR`/`FromCBOR` typeclasses yet.
- [x] Implement rust-cardano packfile routines.
- [x] Implement encoders in another issue (e.g. #42) and add roundtrip tests where there are also encoders defined.

# PR

| Number   | Base      |
| ---      | ---       |
| #28       | `master`  |
| #32       | `master`  |
| #48 | `master` |

# QA 

- These are covered by unit tests.
   - `Cardano.Wallet.BinarySpec` - These are golden tests based on blocks and block headers found on mainnet and testnet.
   - `Cardano.Wallet.Binary.PackfileSpec` - These are testing first some error cases with synthetic pack file data, then a golden test using epoch 104 of mainnet.
- Ensure tests pass and coverage is adequate.
- Tests cover empty blocks, blocks with a single transaction, blocks with multiple transactions and invalid blocks.

**Comment by KtorZ** [comment]
@rvl Not sure you'll be able to implement round-trips and full encoders without having full decoders. Also, in practice, we won't be serializing block, so the only encoders we need are the one to encode a transaction. Those can (_ought to_) be done as part of another task in another iteration :+1:

**Comment by KtorZ** [comment]
Also for the `packfile`, make sure to check --> https://github.com/KtorZ/wallet-prototype/blob/master/app/Main.hs#L905 (if not already done :no_mouth:)

**Comment by KtorZ** [comment]
Some required encoders were done as part of #42

**Comment by piotr-iohk** [comment]
As discussed and agreed:
 - need to add negative tests for block decoding (#48 in progress)
 - need to add tests decoding blocks with more than one transaction

For the time being I'll put the task back to `In progress`.

**Comment by piotr-iohk** [comment]
lgtm :+1: (outstanding items addressed in #48)
