### ISSUE TITLE
Random shuffle seeded by wallet id

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1102]
# Context

We want the ability to shuffle elements randomly but, consistently for the same wallet. Considering two functions functions `shuffle` and `seed` 

```hs
seed :: WalletId -> StdGen
shuffle :: Monad m => StdGen -> [a] -> m [a]
```

with the following properties

```
∀(x : WalletId, y : WalletId). 
∃(threshold : Int).
∀(es :: [a]). 

shuffle (seed x) es = shuffle (seed x) es
x ≠ y, length es > threshold ⇒ shuffle (seed x) es ≠ shuffle (seed y) es
```

# Decision

- Provide an implementation for the `seed` function above
- Provide an implementation for the `shuffle` function above

# Acceptance Criteria

1. Both functions _must_ satisfy the above properties (possibly with a lower confidence than the default one)
2. The `shuffle` function from the CoinSelection _may_ be re-used an adjusted for this.

---

# Development 

- [x] Move `shuffle` from the coin selection module to a dedicated module ==> #1110 
- [x] Implement a "mkSeed" function and allow `shuffle` to be seeded ==> #1110 

# QA 

- Implemented the properties above [here](https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Data/Vector/ShuffleSpec.hs#L42-L46)

- See also #1110 comment to see an example output

**Comment by piotr-iohk** [comment]
lgtm
