### ISSUE TITLE
Allow special handling of the first epoch in stake pool metrics

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1103]
# Context

During the first epoch, stake pool performances are somewhat not very meaningful: one stake pool may seem to out-perform others simply because it was elected during the first slots of the epoch and therefore, already had a chance to produce blocks. 

# Decision

We need to adjust how the list of stake pools is returned to users and make sure that pools are arbitrarily ordered during the first epoch. However, this arbitrary order must be consistent across calls for a same wallet (i.e. seeded by the wallet id). 

# Acceptance Criteria

1. During the first epoch, stake pool _must_ be ordered arbitrarily
2. For a same list of a pools and a given wallet, any successive calls _must_ return the list in the same order. 
3. Different wallets _should_ as much as possible, returns list in different orders.

---

# Development 

- #1112
- ~~Would it be possible (and worth it) to test listStakePools's behaviour here by mocking the DBLayer and NetworkLayer in unit tests? ==> TODO~~ Probably too much hassle for what it is. 

# QA 

- Wrote two properties to check that the seeded randomizer does the right thing: https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Data/Vector/ShuffleSpec.hs#L42-L46

- Property checking that we can read the random seed from the database and it's consistent between reads https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Cardano/Pool/DB/Properties.hs#L350-L364 (therefore ensuring the seeded randomization is always seeded from the same seed)

**Comment by piotr-iohk** [comment]
lgtm.
