### ISSUE TITLE
Credentials and address for reward account 

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1119]
# Context

As a stake pool operator,
I want an easy way to retrieve my assigned reward account credentials,
And its associated testnet address,
So that I can move funds to it using the wallet backend
And I can know what private key I should use for signing stake pool registration in jcli. 

# Decision

Given that I have a valid 15-word mnemonic sentence,
When I call `cardano-wallet mnemonic reward-credentials`,
And I provide my 15-word mnemonic sentence,
Then my reward account private key is printed on screen as a bech32 string prefixed with `ed25519_sk` 

# Acceptance Criteria

Given that I have a valid 15-word mnemonic sentence,
When I call `cardano-wallet mnemonic reward-credentials`,
And I provide my 15-word mnemonic sentence,
Then my reward account private key is printed on screen as a bech32 string prefixed with `ed25519_sk` 

---

# Development 

- I have added a command to our CLI to spit out the reward account extended private key from a given mnemonic. ==>  #1127 

# QA 

- Added an integration tests which uses jcli to create an account address from the key obtained from our command-line, comparing this to the same address generated by our core function from a given mnemonic! See  https://github.com/input-output-hk/cardano-wallet/blob/master/lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/CLI/Mnemonics.hs#L46-L56

**Comment by piotr-iohk** [comment]
Looks good. 

I think this is not needed though:
```
(Enter a blank line if you didn't use a second factor.)
Please enter your 9–12 word mnemonic second factor: 
```
but I guess that's because it's part of reused code. Is it possible to remove it easily?

Probably we could add some negative tests too. (I can add those)

**Comment by KtorZ** [comment]
> I think this is not needed though:

Well, it is though. The second factor affects the seed generation. If a wallet has a second factor then it is needed to recover its root private key. And we allow settings those from the API and the command line, so it is indeed necessary.

> Probably we could add some negative tests too. (I can add those)

:heart:

**Comment by piotr-iohk** [comment]
> And we allow settings those from the API and the command line, so it is indeed necessary.

Then we have some inconsistency with our API, cause with the API we allow 1st mnemonics to be  [15 .. 24] words and here we can only provide 15. if we want to have consistent with the API then we should change that. If we aim for consistency with what Daedalus exposes (that was my initial impression) then we should remove the second step.

**Comment by piotr-iohk** [comment]
more tests -> #1142
