### ISSUE TITLE
Create skeleton `selectCoins` endpoint.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#1135]
# Context

In order to support users that wish to use a hardware wallet, we would like to expose our coin selection functionality as a new API function `selectCoins`. This function will take a list of payments as its input, and produce a coin selection as its output.

# Decision

Create a skeleton endpoint that matches the following specification:
```yaml
  /wallets/{walletId}/coin-selections/random: 
    post: 
      operationId: selectCoins
      tags: ["Coin Selections"]
      summary: Random
      description: TO BE COMPLETED
      parameters: 
        - *parametersWalletId
        - <<: *parametersBody
          schema: *ApiSelectCoinsData
      responses: *responsesSelectCoins
```

The server implementation of this endpoint should return HTTP 501 (Not Implemented).

# Acceptance Criteria

- [x] There _must_ be a skeleton API endpoint that matches the specification above.
- [x] The server implementation _must_ return HTTP 501 (Not Implemented).

# Development 

- [x] Add the endpoint to the Servant API definition.
- [x] Add the skeleton implementation that returns HTTP 501.
- [x] Add the corresponding Swagger definitions.

# QA 

- [x] Produce an integration test that demonstrates the endpoint returns HTTP 501 (Not Implemented).

# PRs

| Number | Base |
| -- | -- |
| #1152 | `master` |

**Comment by KtorZ** [comment]
@jonathanknowles it would be nice to point to the actual tests and where to find these (see https://github.com/input-output-hk/cardano-wallet/issues/1090)
