### ISSUE TITLE
Provide implementation of `selectCoins` API function.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#1136]
# Context

In order to support users that wish to use a hardware wallet, we would like to expose our coin selection functionality as a new API function `selectCoins`. This function will take a list of payments as its input, and produce a coin selection as its output.

# Decision

Provide a complete server implementation of the skeleton endpoint created in #1135.

Ensure that the following error codes are handled correctly:

```yaml
x-responsesSelectCoins: &responsesSelectCoins
  <<: *responsesErr400
  <<: *responsesErr403
  <<: *responsesErr404
  <<: *responsesErr405
  <<: *responsesErr406
  <<: *responsesErr415
```

# Acceptance Criteria

- [ ] The endpoint _must_ produce a valid coin selection, when given a valid input.
- [ ] The endpoint _must_ correctly handle all of the error conditions indicated in the Swagger specification.

---

# Development 

# QA

**Comment by KtorZ** [comment]
No QA nor Development section here, but deducing from other tickets, I've found:

https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core-integration/src/Test/Integration/Scenario/API/Wallets.hs#L1483-L1518

We are missing:

- Negative tests for the headers and path parameters
- Swagger file description to "stable", putting back "In Progress"
