### ISSUE TITLE
Why fix the compiler *and* the LTS in the stack.yaml?

### ISSUE THREAD

**Issue by angerman** [cardano-foundation/cardano-wallet#1138]
as lts's are compiler dependent, and hence bring in a compiler and with it all its boot/base packages, why specify the compiler as well as the lts?

**Comment by KtorZ** [comment]
I don't have the answer on this one. Perhaps @rvl does. I always thought it was needed by the nix pipeline at some point...

**Comment by rvl** [comment]
I didn't add it here, but the reason it was needed is due to a limitation of nix-tools. `stack-to-nix` doesn't output the LTS compiler version, unless it's explicitly defined in `stack.yaml`. And you need this if you are setting Haskell.nix module options which depend on the compiler version.
