### ISSUE TITLE
Misleading Mnemonic Sentence Error message

### ISSUE THREAD

**Issue by craigem** [cardano-foundation/cardano-wallet#1153]
# Context
 
 

When running `cardano-wallet-jormungandr` from the CLI, if you submit a valid English word that is not in the the list of valid words, your are greeted with this misleading message:

```
$ cardano-wallet-jormungandr wallet create fruity
Please enter a 15–24 word mnemonic sentence: one two three four five six seven eight nine diary twenty coin regret cry thumb glare tribe slice angle pitch boy ankle resource broken
Found invalid (non-English) word: "four".
Please enter a 15–24 word mnemonic sentence:
```

This also happens at the second factor:

```
$ cardano-wallet-jormungandr wallet create fruity
Please enter a 15–24 word mnemonic sentence: diary twenty coin regret cry thumb glare tribe slice angle pitch boy ankle resource broken
Please enter a 9–12 word mnemonic second factor: one two three four five six seven eight nine
Found invalid (non-English) word: "four".
```

This example goes on for many valid English words.

A more accurate error would instead advise that the the selected words are not on the approved word list and perhaps even suggest using `cardano-wallet-jormungandr mnemonic generate` for a valid list.

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | 2019.12.9 (git revision: 0000000000000000000000000000000000000000) |
| Platform     | Linux |
| Installation | GitHub (via IOHK Nix) |

# Steps to Reproduce

1. As per above examples.

## Expected behavior

An error message that accurately describes the problem

## Actual behavior
 

As per above, a misleading error message

---

# Resolution 

Providing an error that accurately directs the user to correct the issue.

---

# PR

| Number   | Base      |
| ---      | ---       |
| #1212        | `master` |

# QA

**Comment by KtorZ** [comment]
Indeed! It might not be obvious that a mnemonic sentence is an encoding made of a composition of words coming from a known pre-established list and isn't simply free-form. 

We could even point to some documentation like https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt

cc @piotr-iohk
