### ISSUE TITLE
Make old Haskell node network prototype compile again

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#1160]
# Context

> As a wallet backend developer and a cardano-node project manager
I want to identify gaps and outstanding effort required to integrate the wallet backend with the haskell nodes,
So that I can anticipate risks and start planning the integration.

[WB-26](https://jira.iohk.io/projects/WB/issues/WB-26?filter=allopenissues)

A while back, Matthias wrote a [prototype for integrating](https://github.com/input-output-hk/cardano-wallet/blob/cbd921f5cb8348baaf5ca7956ad4a5a3a5d60124/lib/shelley/src/Cardano/Wallet/Shelley/Network.hs) with the Haskell node. It does not compile with current version of the node.

# Decision

Adapt the code such that it compiles and works. Focus on getting something minimal working. We may extend the prototype later to check things that interest us. (This task _might_ or _might not_ cover the second point of the acceptance criteria in the Jira U/S)

# Acceptance Criteria

- We must be able to follow the Haskell node chain and handle rollbacks
- We should be a able to construct a `Cardano.Wallet.Primitive.Types.BlockHeader` for each block

---

# Development 

# QA

**Comment by KtorZ** [comment]
@Anviking note also that this prototype was doing a "conversion" from stateful to stateless which should not be necessary anymore.

**Comment by Anviking** [comment]
I think I can close this. No QA since nothing is merged.

I'll open a separate issue for a potentially more extensive prototype.
