### ISSUE TITLE
Add caching of stake pool metadata registry

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#1164]
# Context

Part of [WB-42](https://jira.iohk.io/browse/WB-42).

The listStakePools endpoint will be polled frequently by clients like Daedalus. It will fetch stake pool metadata from the registry every time. The metadata registry data won't change very often.

Add caching of the stake pool metadata with a TTL of say 1 hour.

# Decision

The best solution would be to load the registry metadata into the database, where it can be joined with the stake pool registration data.

But a quicker interim solution could be to download and cache the registry zip file into the databases directory.

# Acceptance Criteria

1. The stake pool metadata must not be downloaded every single time the API endpoint is called.

---

# Development 

- Cache downloaded archive in a temporary folder and renew it every hours ==> #1166 
- Make sure that the cache can still be downloaded if the temporary cache dir is removed ==> #1174 

# QA 

- Added unit tests using a mock server to serve the archive.
    - 1. Test that the the archive is only fetched once from the server by making two successive calls and monitoring logs for tracing code execution: https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Cardano/Pool/MetadataSpec.hs#L97-L105

   - 2. Another test that make a first call, then forces the cache to expire (by manually changing the directory "modification time" to one second after the cache TTL) and monitoring logs for tracing code execution: https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Cardano/Pool/MetadataSpec.hs#L107-L117 

   - 3. A third test that tries to download the archive, cache it, remove the cache folder and re-download successfully the archive. See #1174

**Comment by piotr-iohk** [comment]
TC that fails:
 - list pools with metadata -> OK
 - remove the `/tmp/stake-pools-xxx` directory
 - list stake pools again -> Metadata is not fetched, in the log there is:
```
[cardano-wallet:Info:2224] [2019-12-13 15:29:09.14 UTC] Downloading https://github.com/piotr-iohk/incentivized-testnet-stakepool-registry/archive/master.zip -> /tmp/stake-pool-metadata-3fd60f4b16799520/registry.zip: Started download
[cardano-wallet:Notice:2224] [2019-12-13 15:29:09.14 UTC] Stake pool metadata is unavailable
```

**Comment by piotr-iohk** [comment]
Putting back to _in progress_ for now until :point_up_2:  addressed (also such case can be added). Otherwise looks good.

**Comment by KtorZ** [comment]
> also such case can be added

I've actually already added it. Now looking into it :thinking:

**Comment by KtorZ** [comment]
Seems to work fine for me at the unit level at least @piotr-iohk 

```
"Started download"
"Completed download of 8152 bytes"
"Extracting file: registry/ed25519_pk1a6mv6x2r0f3y62ddavxvf5lkdsj8ttc8mk3yngdy895j8tn6jqyqesvuk2.json"
"Successfully parsed metadata"
"Extracting file: registry/ed25519_pk1fh2ajuu7rqquuxqrkh6ldfvdktlthkl4wlfhymrath85wzhy7slsr37f87.json"
"Successfully parsed metadata"
"Extracting file: registry/ed25519_pk1wc84pj9h3qw5kknawj2d0mqwr43gxhtsnq5pmuzxg7ssrcpt84ds9sce69.json"
"Successfully parsed metadata"
"Started download"
"Completed download of 8152 bytes"
"Extracting file: registry/ed25519_pk1a6mv6x2r0f3y62ddavxvf5lkdsj8ttc8mk3yngdy895j8tn6jqyqesvuk2.json"
"Successfully parsed metadata"
"Extracting file: registry/ed25519_pk1fh2ajuu7rqquuxqrkh6ldfvdktlthkl4wlfhymrath85wzhy7slsr37f87.json"
"Successfully parsed metadata"
"Extracting file: registry/ed25519_pk1wc84pj9h3qw5kknawj2d0mqwr43gxhtsnq5pmuzxg7ssrcpt84ds9sce69.json"
"Successfully parsed metadata"
    Cache it, removes it, re-download it
```

**Comment by KtorZ** [comment]
Doing it manually however from the command-line doesn't work indeed:

```
[cardano-wallet:Info:161] [2019-12-13 15:55:27.14 UTC] Downloading https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/archive/master.zip -> /tmp/stake-pool-metadata-3ff0cf444fd4899e/registry.zip: Started download
[cardano-wallet:Notice:161] [2019-12-13 15:55:27.14 UTC] Stake pool metadata is unavailable
```
