### ISSUE TITLE
Possible missing db migration between balance-check version and latest one

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1177]
# Context

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | 2019.12.13 (git revision: 11f269891d54b870b8768455292d2345e95b6810)  |
| Platform     | All           |
| Installation | Source             |

# Steps to Reproduce

1. Start a wallet server using v2019-11-18, create a wallet, wait for a few block to sync...
2. Quit
3. Start a wallet on the same state dir using v2019-12-09 or v2019-12-13, wait for a first block to sync.

4. (expected) everything is fine.
4. (actual) :boom:  
```
SQLite3 returned ErrorConstraint while attempting to perform step: NOT NULL constraint failed: seq_state_backup.reward_xpub
[cardano-wallet.worker:Error:29] [2019-12-14 16:11:56.57 UTC] 822329c8: Worker has exited unexpectedly: SQLite3 returned ErrorConstraint while attempting to perform step: NOT NULL constraint failed: seq_state_backup.reward_xpub
```

## Expected behavior

In the case of these 2 versions, a DB migration is actually impossible, because it needs access to the xprv to populate the DB.

In the general case going forward:
- it should automatically migrate the wallet databases when possible.
- the stake pools database can be cleared at startup and restored from scratch because there is no wallet-specific data there. 
- if not possible to migrate, it should fail to start with a good error message.
- (perhaps) if the jormungandr version was updated, `cardano-wallet launch` should delete the `chain` directory.
- only forwards migrations (not backwards) need be supported.

## Actual behavior
 
- As above

---

# Resolution 

1. Implement clearing of stake pools database => #1201.
2. Add automatic tests of DB migrations so that we don't release with a migration error => #1190.

---

# QA 

1. Ability to migrate to newer versions should be tested in CI.

**Comment by piotr-iohk** [comment]
Ok. there are automated migration tests in CI for Windows and Linux now.
Note that I couldn't test manually migration between `v2019-11-18` and latest `v2020-01-14` because supported Jormungandr versions (`0.7.0` and `0.8.6` respectively) are not compatible.

The error is:

```
Jan 20 13:43:48.307 Parsing error on Block0
 |-> Structure invalid: Invalid config parameter tag
INFO[cardano-wallet.network:Error:19] [2020-01-20 12:43:49.59 UTC] Child process jormungandr exited with status 4
[cardano-wallet.application:Alert:19] [2020-01-20 12:43:49.59 UTC] The node exited with status ExitFailure 4
```
