### ISSUE TITLE
Servant API: add `postWallet` and `putWallet` operations.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#118]
# Context

Sub-issue of issue #53 (Translate the Swagger API specification into a Servant API specification).

# Decision

Translate the `postWallet` and `putWallet` operations to the Servant API, along with all associated types.

# Acceptance Criteria

1. The Servant API _must_ support the `postWallet` and `putWallet` operations.

# PR

PR #119

**Comment by KtorZ** [comment]
Closing this. Let's not open issues outside of the iteration planning meeting, especially when they are sub-tasks of already existing tasks. Rather, use comments on Github or, add bullet points to your development plan :+1:
