### ISSUE TITLE
SQLite3 returned ErrorConstraint while attempting to perform step: UNIQUE constraint failed: pool_owner.pool_id, pool_owner.pool_owner

### ISSUE THREAD

**Issue by stakeada** [cardano-foundation/cardano-wallet#1184]
# Context
 
Just run cardano-wallet as follows:

```
# cardano-wallet launch --genesis-block-hash $(cat genesis-hash.txt) -- --config itn_rewards_v1-config.yaml 
```

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | 2019.12.13 (git revision: 0000000000000000000000000000000000000000) |
| Platform     | Nixos          |
| Installation | Source          |

# Steps to Reproduce

Just run cardano-wallet and you'll get the following error in stdout:

```
[cardano-wallet.stake-pools:Error:32] [2019-12-15 18:53:51.59 UTC] Recoverable error following the chain: SQLite3 returned ErrorConstraint while attempting to perform step: UNIQUE constraint failed: pool_owner.pool_id, pool_owner.pool_owner
```

## Expected behavior

No error in stdout.

## Actual behavior

The cardano-node starts jormungandr which continues to work, but that error is continuously printed to stdout.

**Comment by KtorZ** [comment]
Duplicate with #1181 
Please use the latest revision _if you need this fixed_.
