### ISSUE TITLE
Cardano wallet wrong port error

### ISSUE THREAD

**Issue by EdouardLvdl** [cardano-foundation/cardano-wallet#1194]
Steps to reproduce:
- Follow official guide until step 3.2.2 https://github.com/input-output-hk/shelley-testnet/blob/master/docs/stake_pool_operator_how_to.md "For the Incentivized Testnet using Cardano-Wallet CLI"
- Then follow https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/wiki/How-to-Register-Your-Stake-Pool-on-Chain Step 3: Fund your account Option B using cardano-wallet

$ cardano-wallet wallet create MyWallet
Please enter a 15–24 word mnemonic sentence: ***
Please enter a 9–12 word mnemonic second factor: ***
Please enter a passphrase: ***

Throws:

> HttpExceptionRequest Request {
>   host                 = "localhost"
>   port                 = 8090
>   secure               = False
>   requestHeaders       = [("Accept","application/json;charset=utf-8,application/json"),("Content-Type","application/json;charset=utf-8")]
>   path                 = "/v2/wallets"
>   queryString          = ""
>   method               = "POST"
>   proxy                = Nothing
>   rawBody              = False
>   redirectCount        = 10
>   responseTimeout      = ResponseTimeoutDefault
>   requestVersion       = HTTP/1.1
> }
>  (ConnectionFailure Network.Socket.connect: <socket: 11>: does not exist (Connection refused))

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | 2019.12.13 (git revision: f3576be15de4976e753dea212aa5d44c334bd204) |
| Platform     | Linux |
| Installation | From Github release  |

**Comment by KtorZ** [comment]
HI @EdouardLvdl , did you start the wallet backend server & its node (Jörmungandr) before running this command? (As explained in [Step 1](https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/wiki/How-to-Register-Your-Stake-Pool-on-Chain#step-1-start-jormungandr) ?)

**Comment by EdouardLvdl** [comment]
Yes, I started jormungandr and my node is synced

**Comment by rvl** [comment]
If using Step 3 Option B (cardano-wallet), then you need to also run the command in the "Using cardano-wallet" option of Step 1.

**Comment by EdouardLvdl** [comment]
Thanks for your help, it is indeed required to install jormungandr by following this guide https://github.com/input-output-hk/jormungandr versus just running the node.

Would be nice to have such step highlighted in https://github.com/input-output-hk/shelley-testnet/blob/master/docs/stake_pool_operator_how_to.md as well

**Comment by xptodevx** [comment]
lol is that for real still or not?
