### ISSUE TITLE
Increase API Handlers polymorphism

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1207]
# Context

Most of the wallet engine is already very polymorphic and can support multiple types of wallet. In the API, we've instantiated endpoints to work either with `SeqState` or `RndState`, though in practice, any combination of `SeqState`, `RndState` and keys are possible. In particular, for supporting Yoroi, we'll need a combination of `SeqState` and `ByronKey`. 

# Decision

- Remove duplication in the API handlers such that we could potentially re-use most of the wallet endpoints with seq or rnd state. 

# Acceptance Criteria

1. Apart from `postWallet`, wallet and transaction handlers _should_ be polymorphic in any type of wallet. 
2. Other handlers such as the delegation ones _should_ remain shelley-specific

---

# Development 

- House keeping in the API definition and handlers to reflect the swagger file with more fidelity ==> #1199 
- More polymorphic handlers ==> #1206 

# QA 

- All integration tests still pass, and the API golden tests are unchanged.

**Comment by piotr-iohk** [comment]
lgtm
