### ISSUE TITLE
Support and discriminate 12 and 15 words in the byron createWallet endpoint

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1208]
# Context

Byron Daedalus wallets use 12 words, Byron Yoroi wallets use 15.

# Decision

To keep the API simple and user friendly, we'll use the number of words to discriminate between  Yoroi and Daedalus byron wallets and pick a corresponding API layer.

# Acceptance Criteria

1. One _must_ be able to restore a legacy yoroi wallet using a 15 word mnemonic passphrase via the same api endpoint https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/postByronWallet

2. Other endpoint for legacy wallets _must_ be accessible to the wallet yielded
3. Migration of Yoroi legacy wallet _may_ be postponed to another task.

---

# Development 

- Support for 15-word mnemonic in the API ==> #1209 
- Work-around for the initial blockchain scan in the genesis block ==> #1221 

# QA 

- Added a new faucet to integration scenario pointing to Icarus wallets in the genesis integration file. Faucet can be used in an analog way to Byron wallets (i.e. `fixtureIcarusWallet`). See also:
    - https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core-integration/src/Test/Integration/Scenario/API/ByronWallets.hs#L149
    - https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core-integration/src/Test/Integration/Scenario/API/ByronTransactions.hs#L77

- Added unit tests for `IcarusKey` derivations methods: https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Cardano/Wallet/Primitive/AddressDerivation/IcarusSpec.hs#L78-L86

- Resurrected golden tests comparing known Icarus addresses with addresses obtained through implementation: https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Cardano/Wallet/Primitive/AddressDerivation/IcarusSpec.hs#L63-L76

- Made the `SequentialSpec` unit tests more polymorphic so that we could test with both Icarus and Shelley Key, as well as any possible combination of the accounting style: https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Cardano/Wallet/Primitive/AddressDiscovery/SequentialSpec.hs#L134-L146

- Added two properties for `shrinkPool` used to reduce the size of the pool used to the initial blockchain scan: https://github.com/input-output-hk/cardano-wallet/blob/534e1a00b42c5e8162756357f7d6df1b195d52b6/lib/core/test/unit/Cardano/Wallet/Primitive/AddressDiscovery/SequentialSpec.hs#L158-L161

- Extra integration test specific to Icarus wallet with addresses with high indexes (far beyond the initial default pool gap). https://github.com/input-output-hk/cardano-wallet/blob/534e1a00b42c5e8162756357f7d6df1b195d52b6/lib/core-integration/src/Test/Integration/Scenario/API/ByronWallets.hs#L1179-L1200

**Comment by piotr-iohk** [comment]
lgtm.
