### ISSUE TITLE
Migration failing on Windows due to stake-pools.sqlite lock

### ISSUE THREAD

**Issue by alan-mcnicholas** [cardano-foundation/cardano-wallet#1224]
# Context
 

When upgrading from version 2.0.0-ITN1 the client is unable to restart on Windows because the stakepool db migration appears to fail. Manually deleting the `stake-pools.sqlite*` files corrects the issue. This issue appears to be Windows specific; this was not the case on MacOS.

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      |  `2019.12.23`   |
| Platform     |  Windows 10       |
| Installation | https://buildkite.com/input-output-hk/daedalus/builds/10126            |

# Steps to Reproduce

1. Install the production version of Daedalus
https://update-jormungandr-incentivized.iohk.io/daedalus-2.0.0-ITN1-cardano-wallet-2019.12.16-itn_rewards_v1-windows-10012.exe
2. Sync the wallet and allow the main UI to load
3. Close Daedalus and upgrade to a newer build 
(i.e. https://buildkite.com/input-output-hk/daedalus/builds/10126) [direct download link](https://ci-output-sink.s3.amazonaws.com/result/daedalus-2.0.1-ITN1-cardano-wallet-2019.12.23-itn_rewards_v1-windows-10126.exe)

4. Launch Daedalus

## Expected behavior

The upgrade should complete successfully and the main UI should load showing the correct wallet information on relaunch.

## Actual behavior

After upgrading the client is stuck in the "connecting to network" screen indefinitely with the following error message in the logs:

```
[34m[cardano-wallet.jormungandr.3476:Info:16][0m [2019-12-23 21:50:57.22 UTC] Process jormungandr started with pid 3476
[34m[cardano-wallet.daedalus-ipc:Info:15][0m [2019-12-23 21:50:57.22 UTC] Daedalus IPC server starting
Dec 23 21:50:57.285 INFO Starting jormungandr 0.8.5 (HEAD-3db06807, release, windows [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)], task: init
Dec 23 21:50:57.287 WARN Node started without path to the stored secret keys (not a stake pool or a BFT leader), task: init
Dec 23 21:50:57.288 INFO storing blockchain in '"C:\\Users\\admin\\AppData\\Roaming\\Daedalus - Rewards v1\\chain\\blocks.sqlite"', task: init
[34m[cardano-wallet:Info:19][0m [2019-12-23 21:50:57.73 UTC] Waiting for Jörmungandr to be ready on tcp/50718
Dec 23 21:51:32.024 INFO connecting to bootstrap peer 3.125.75.156:3000, peer_addr: 3.125.75.156:3000, task: bootstrap
Dec 23 21:51:32.110 INFO update current branch tip, peer_addr: 3.125.75.156:3000, task: bootstrap
Dec 23 21:51:32.113 INFO initial bootstrap completed, peer_addr: 3.125.75.156:3000, task: bootstrap
Dec 23 21:51:32.123 INFO connecting to peer, node_id: 52762c49a84699d43c96fdfe6de18079fb2512077d6aa5bc, peer_addr: 13.112.181.42:3000, task: network
Dec 23 21:51:32.129 INFO connecting to peer, node_id: 23b3ca09c644fe8098f64c24d75d9f79c8e058642e63a28c, peer_addr: 52.28.91.178:3000, task: network
Dec 23 21:51:32.131 INFO connecting to peer, node_id: 671a9e7a5c739532668511bea823f0f5c5557c99b813456c, peer_addr: 52.9.132.248:3000, task: network
Dec 23 21:51:32.131 INFO connecting to peer, node_id: 7e1020c2e2107a849a8353876d047085f475c9bc646e42e9, peer_addr: 13.114.196.228:3000, task: network
Dec 23 21:51:32.132 INFO connecting to peer, node_id: 99cb10f53185fbef110472d45a36082905ee12df8a049b74, peer_addr: 3.124.116.145:3000, task: network
Dec 23 21:51:32.132 INFO connecting to peer, node_id: 22fb117f9f72f38b21bca5c0f069766c0d4327925d967791, peer_addr: 3.125.75.156:3000, task: network
Dec 23 21:51:32.132 INFO connecting to peer, node_id: 18bf81a75e5b15a49b843a66f61602e14d4261fb5595b5f5, peer_addr: 52.8.15.52:3000, task: network
[34m[cardano-wallet:Info:19][0m [2019-12-23 21:51:32.16 UTC] Jörmungandr is ready.
PersistError "\n\nDatabase migration: manual intervention required.\nThe unsafe actions are prefixed by '***' below:\n\n    CREATE TEMP TABLE \"pool_registration_backup\"(\"pool_id\" VARCHAR NOT NULL,\"slot\" INTEGER NOT NULL,\"margin\" INTEGER NOT NULL,\"cost\" INTEGER NOT NULL, PRIMARY KEY (\"pool_id\"));\n    INSERT INTO \"pool_registration_backup\"(\"pool_id\",\"margin\",\"cost\") SELECT \"pool_id\",\"margin\",\"cost\" FROM \"pool_registration\";\n*** DROP TABLE \"pool_registration\";\n    CREATE TABLE \"pool_registration\"(\"pool_id\" VARCHAR NOT NULL,\"slot\" INTEGER NOT NULL,\"margin\" INTEGER NOT NULL,\"cost\" INTEGER NOT NULL, PRIMARY KEY (\"pool_id\"));\n    INSERT INTO \"pool_registration\" SELECT \"pool_id\",\"slot\",\"margin\",\"cost\" FROM \"pool_registration_backup\";\n    DROP TABLE \"pool_registration_backup\";\n"
[35m[cardano-wallet:Notice:19][0m [2019-12-23 21:51:32.73 UTC] Non backward compatible database found. Removing old database and re-creating it from scratch.
cardano-wallet-jormungandr.exe: C:\Users\admin\AppData\Roaming\Daedalus - Rewards v1\wallets\stake-pools.sqlite: DeleteFile "\\\\?\\C:\\Users\\admin\\AppData\\Roaming\\Daedalus - Rewards v1\\wallets\\stake-pools.sqlite": permission denied (The process cannot access the file because it is being used by another process.)
```

# Resolution 

- [x] Fix database setup code where sqlite connection is not closed before trying to delete the database => PR #1226 .
- [x] Obtain access to a windows installation, reproduce error, test the fix manually.
- [x] Add windows batch files to automated db migration tests => PR #1190.
- [?] Follow up on our request for a Windows 10 EC2 instance for Buildkite.

---

# QA 

1. Retest using the reproduction steps on this issue.
2. Ensure that db migrations are also tested in CI for linux and windows.
3. Automated migrations from previous versions now happen automatically on nightly builds!

**Comment by piotr-iohk** [comment]
> Retest using the reproduction steps on this issue.

OK. Verified `2019-12-16` -> `2020-01-14` on Windows 10 VM.

> Ensure that db migrations are also tested in CI for linux and windows.

That's that if I'm not mistaken.
https://hydra.iohk.io/job/Cardano/cardano-wallet/migration-tests-win64

> Automated migrations from previous versions now happen automatically on nightly builds!

:tada:
