### ISSUE TITLE
Unhandled Data.Binary.Get error observed in node logs

### ISSUE THREAD

**Issue by alan-mcnicholas** [cardano-foundation/cardano-wallet#1228]
# Context
 
When running the latest version of Daedalus (https://buildkite.com/input-output-hk/daedalus/builds/10138) the following error message appears in the node logs.

```
Dec 24 16:05:27.357 INFO fetching block 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676, peer_address: 52.28.91.178:3000, block: 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676, task: init
cardano-wallet-jormungandr.exe: Data.Binary.Get.runGet at position 0: not enough bytes
CallStack (from HasCallStack):
  error, called at libraries/binary/src/Data/Binary/Get.hs:351:5 in binary-0.8.6.0:Data.Binary.Get
```

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | `2019.12.23` |
| Platform     | Windows 10         |
| Installation | https://buildkite.com/input-output-hk/daedalus/builds/10138          |

# Steps to Reproduce

1. Install version of Daedalus from the link above. Note this error does not always appear however it can be forced by closing the Daedalus client.

## Expected behavior

Any errors should be handled correctly.

## Actual behavior

Unhandled error is output in the node logs however this does not appear to have any adverse effect on the application. 

# Resolution 

- Avoid raw usage of `runGet` in places outside of the 'Jormungandr.Binary'  module. In particular:
    - DaedalusIPC on Windows
    - Jormungandr HTTP Client 'MimeUnrender' 

==> #1229 

---

# QA 

[logs-2019-12-24T134635.0659Z.zip](https://github.com/input-output-hk/cardano-wallet/files/3998484/logs-2019-12-24T134635.0659Z.zip)

**Comment by piotr-iohk** [comment]
lgtm
