### ISSUE TITLE
Allow restoring 24-word mnemonic in the Byron API 

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1232]
# Context

We ought to support both Trezor and Ledger mnemonic restoration through the API. They both typically use 24-word mnemonic. 

# Decision

- Allow 24-word mnemonic in the API
- Provide a way to discriminate between Trezor and Ledger via a query parameter

# Acceptance Criteria

1. One _must_ be able to restore a Hardware Ledger 24-word mnemonic via the API
2. One _must_ be able to restore a Hardware Trezor 24-word mnemonic via the API

---

# Development 

- #1236 

# QA 

- Rather exhaustive list of scenarios exercising the legacy restoration endpoints with various sizes and various styles of wallets: https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core-integration/src/Test/Integration/Scenario/API/ByronWallets.hs#L872-L898

- Added a special integration tests restoring a Ledger wallet with funds, since they are a bit special https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core-integration/src/Test/Integration/Scenario/API/ByronWallets.hs#L1258-L1277

- Already existing integration test covering both Icarus and Trezor: https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core-integration/src/Test/Integration/Scenario/API/ByronWallets.hs#L1235-L1256

- All other already existing integration tests, testing Icarus (sequential) and Random (random) wallets.

**Comment by piotr-iohk** [comment]
I think there are some cases that would be worth adding:
 - migration/calcuate migration fee of funds for trezor/ledger to shelley
 - listing of interleaving wallets trezor/ledger/icarus/random (it's there for icarus and random)
 - deletion of trezor/ledger
 - listing transactions for trezor/ledger/icarus (only for random)
 - forgeting transactions for trezor/ledger/icarus (only for random)

Maybe something else? Thoughts?

**Comment by KtorZ** [comment]
Yes. Though, I don't think we should _add_ tests per se, but instead modify the existing scenarios so that they run for each type.
