### ISSUE TITLE
Auxiliary seed generation method for Ledger 

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1233]
# Context

Hardware Ledger devices use a different method than the rest of Cardano to generate root master key from a given mnemonic sentence. After quite some research, it seemed that this boiled down to be done by a firmware primitive named `os_perso_derive_node_bip32_seed_key`. 

After more research, I was able to find a reference implementation in Python https://github.com/LedgerHQ/orakolo from which a Haskell implementation could be derived. 

# Decision

Provide a new method in `Primitive.AddressDerivation.Icarus` called `generateKeyFromHardwareLedger` which implements the mnemonic to root master key generation for Hardware Ledger.

# Acceptance Criteria

- Function above _must_ be implemented
- Addresses generated by a Hardware Ledger device _must_ be the same as those obtained via implementing this method in Haskell.

---

# Development 

- #1234 

# QA 

- Golden tests with mnemonics and addresses coming from an actual device (kindly provided by Darko and Sebastien) https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Cardano/Wallet/Primitive/AddressDerivation/IcarusSpec.hs#L113-L181

**Comment by piotr-iohk** [comment]
lgtm.
