### ISSUE TITLE
Allow logs to be filtered by components

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#1235]
# Context

[User story WB-31](https://jira.iohk.io/browse/WB-31)

As a technical user using the command-line
I want to be able to increase or decrease logging verbosity of specific components of the wallet server
So that I can debug more easily issues with the software

# Decision

# Acceptance Criteria

- When starting the wallet server (using `start` or `launch` command), it must be possible to control the logging severity of various distinct parts of the server.

---

# Development 

1. Move from `Trace m a` to `Tracer m a`
2. Collect top-level traces in a data type, and configure this at startup.
3. Remove cli `--quiet` and `--verbose`
4. Add cli options for enabling/disabling top-level traces, and setting their minimum severity. ⇒ #1241
5. ~Add cli options for altering verbosity of top-level traces (this is distinct from severity).~ ← really only useful with structured logging output.
8. Adjust cli integration tests accordingly ⇒ #1257
9. Update usage documentation on wiki ⇒ [CLI Wiki Page](https://github.com/input-output-hk/cardano-wallet/wiki/Wallet-command-line-interface#logging-options-for-launch--serve)

# QA 

- Added integration tests for new options ⇒ [`.../CLI/Server.hs`](https://github.com/input-output-hk/cardano-wallet/blob/0bd418e3362c8b041c9c211d1f1e93b7e4f718c9/lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/CLI/Server.hs#L115-L178)

**Comment by piotr-iohk** [comment]
@rvl is this done/qa ready?

**Comment by rvl** [comment]
@piotr-iohk sorry I forgot - I have updated the QA section.

**Comment by piotr-iohk** [comment]
lgtm.
