### ISSUE TITLE
Revise expectations in integration tests

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#1238]
# Context

In the course of adding integration tests we have added a lot of different and specific assertions which can be replaced with more powerful combinators reducing the code.

# Decision

Replace the myriad of assertions functions with more powerful combinators. For instance, we have `expectFieldEqual`, `expectFieldBetween`, `expectFieldNotEqual` etc ... which can all be expressed via `expectFieldSatisfy` ... Also, all of the `expectEventually` ... can be replaced by a combination of other expectation and the `eventually` combinator we introduced recently.

# Acceptance Criteria

---

# Development 

In #1317:

1. Removed bunch of assertion functions which where replaced by only:
 - expectField
 - expectListField
 - expectCliField
 - expectCliListField

All of which take as an argument a function that is supposed to verify the condition we want to check `(a -> Expectation)`. For instance:

```
expectField #migrationCost (`shouldBe` Quantity 0)
expectField id (`shouldSatisfy` (not. null))
```
`greaterThan` and `(.>=)` helper functions added to use with expectations.

2. Removed `expectEventually` and repaced with the combination of `eventually_` and other expectations

In #1339, revise names of new functions.

# QA 
All tests are passing after the changes, no tests where removed or added.

**Comment by Anviking** [comment]
lgtm! 🎉
