### ISSUE TITLE
Prototype Wallet Executable supporting Haskell Byron Node

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#1243]
# Context

We'd like to gain a better understanding of what it will take to support the Haskell node(s).

 The prototype of #1160 didn't connect with the wallet functionality. The work so-far in #1161 was very theoretical, and I am not convinced it gives a accurate enough picture on its own.

# Decision

For better understanding, make a quick and incomplete prototype wallet executable that integrates with the Haskell Byron Node.

# Acceptance Criteria

- [ ] We _must_ be able to start a cardano-wallet executable connecting to a Haskell Byron Node.
- [ ] We _must_ be able to restore a mainnet wallet (and see its balance at least)
---

# Development 

# QA

**Comment by Anviking** [comment]
Aborted for WB-26. 

I almost got a wallet restoring. Will quickly mention difficulties I discovered in the inventory of #1161.

**Comment by Anviking** [comment]
> I almost got a wallet restoring.

Actually, the balance did increase (encouraging), I just had to be more patient. Full restoration takes a really long time. (~hour)

**Comment by KtorZ** [comment]
@Anviking keep in mind that you are restoring against MainNet, where the chain is much much larger than current ITN. I recall the performance of the node the guys measured recently were around 500 blocks/seconds. MainNet is currently 3.6M blocks, which means ~2h provided that we can digest blocks at the same pace (which is certainly the case on a basic wallet).

**Comment by Anviking** [comment]
For the record: `anviking/WB-26/prototype-3`
