### ISSUE TITLE
Port pool desirability formulas from delegation design document

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#1250]
# Context

The ranking of pools in the ITN are sub-optimal.

We want to adhere to the ranking described in the [Delegation Design Spec](https://hydra.iohk.io/build/1389333/download/1/delegation_design_spec.pdf), ignoring the differences of:
- Jörmungandr Pool Max Tax Cap (nothing we can do about it, most pools don't have it set anyway)
- Leader stake (always 0 in Jörmungandr)

# Decision

Convert relevant formulas in section 6.5 and 6.6 to well-documented and understandable code, maintaining close correspondence and structure with the specs.

If the usefulness of a formula is not clear to the wallet, we may still consider adding it as code for the sake of completeness, learning, and structure.

# Acceptance Criteria

- Relevant formulas in 6.5 and 6.6 _should_ be ported
- The code _must_ be descriptive and well-documented
- The code _should_ follow the same structure as the spec (to make it easy to compare the two)

---

# Development 

- #1259 

# QA 

- Ported fewer formulas than first anticipated. https://github.com/input-output-hk/cardano-wallet/blob/6f09f4bbc58e837547a6ae5c66575e880f060c07/lib/core/src/Cardano/Pool/Ranking.hs#L68
- Currently unused.
- Fairly strict newtypes making sure that we later on don't pass in invalid values. `unsafeMkRatio`, `unsafeMkPositive`, `unsafeMkNonNegative` will crash otherwise. Fairly extensive property tests: https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Cardano/Pool/RankingSpec.hs#L75-L121

**Comment by piotr-iohk** [comment]
lgtm
