### ISSUE TITLE
Benchmarks are failing

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#1252]
# Context
 
Banchmarks (https://buildkite.com/input-output-hk/cardano-wallet-nightly) have recently been failing, e.g.:

https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/349
:point_down: 
```
error: The option `packages."\$locals".package.identifier.name' is used but not defined.
(use '--show-trace' to show detailed location information)
```

# Test Case

Database and Latency benchmarks, e.g. -> https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/349

# Failure / Counter-example

---

# Resolution 

- Will be fixed by merging #1106 (via input-output-hk/haskell.nix#393).
- Also needs #1258

---

# QA

**Comment by rvl** [comment]
The line I added to fix weeder `ghc-options: {"$locals": -ddump-to-file -ddump-hi}` broke the nix build.

The fix is here: input-output-hk/haskell.nix#393

This would also be the reason why tests are missing from the windows testing bundle.

**Comment by piotr-iohk** [comment]
Benchmarks passing now.
