### ISSUE TITLE
"Something went wrong" when listing stake pools from inside a Docker container

### ISSUE THREAD

**Issue by bourkefloyd** [cardano-foundation/cardano-wallet#1256]
# Context
 
Maybe related to changes here https://github.com/input-output-hk/cardano-wallet/issues/1164

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | 2019.12.23 (git revision: 398565cc1a65553827834520c5a95827a7c48d41) |
| Platform     | Docker FROM ubuntu:18.04    |
| Installation | Source 0.8.5   |

# Steps to Reproduce
Setup jormungandr w/ jci per instructions and run w/ jormungandr cmd line as leader
Setup cardano-wallet per instructions and run w/ serve

NOTE: 8443 is jcli and 8299 is the node
tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN      14/jormungandr      
tcp        0      0 0.0.0.0:8444            0.0.0.0:*               LISTEN      13/cardano-wallet   
tcp        8      0 0.0.0.0:8299            0.0.0.0:*               LISTEN      14/jormungandr 

1. Note the first request to /v2/stake-pools (CLI or rest api) returns the stakepools without the meta data. 
2. All following requests to /v2/stake-pools (CLI or rest api) fail with 'Something went wrong(base)'

If you delete the `/tmp/stake-pool-metadata-90e545fc4b1cdae6/registry.zip` cache that seems to be failing to deserialize, you can start at step 1 again, and the repo steps will start over.

## Expected behavior

stake-pools list WITH metadata on the second request to /v2/stake-pools (not crash/error)
https://input-output-hk.github.io/cardano-wallet/api/edge/#tag/Stake-Pools

## Actual behavior
 
 'Something went wrong(base)'

---

# Resolution 

- Cleanup incomplete metadata archive when failing to download ==> #1272 
- Adds SSL root certificates to the docker image so that metadata registry downloads work. ==> #1256

---

# QA 

- Added unit tests to capture behavior on broken cache files ==> https://github.com/input-output-hk/cardano-wallet/pull/1272/files#diff-926cc24c9fd58a975e70cd61762a5ddbR141-R160

- Added also docker documentation in wiki ==> https://github.com/input-output-hk/cardano-wallet/wiki/Docker

**Comment by bourkefloyd** [comment]
Just tested with cardano-wallet `v2020-01-07` same issue

**Comment by rvl** [comment]
Hi @chbfiv, thanks for reporting.

Would you be able to run `cardano-wallet` again with `--verbose`, and show all log lines containing `Downloading https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/archive/master.zip`?

**Comment by rvl** [comment]
I did some testing locally with ITN and could not reproduce it. Not saying that there isn't a problem, just that we may need to dig further to uncover its cause.

1. Which instructions are you using?
2. Are you connecting to `itn_rewards_v1` ([config links](https://hydra.iohk.io/job/Cardano/iohk-nix/jormungandr-deployment/latest/download/1/index.html)).
3. Are you seeing `stake-pool-monitor ... In sync with the node.` log messages before you call the stake-pools endpoint?
4. Are there any errors or warnings reported in the logs? (e.g. failed downloads, out of disk space, anything)
5. Which jormungandr version are you using?

Here are my results:

1. I run latest master branch like this (for this issue though, the version shouldn't matter too much, but master branch has some new logging options)
   ```
   cardano-wallet-jormungandr launch --log-level debug --trace-stake-pool-layer debug --port 8090 --genesis-block-hash 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676  --state-dir ./state-itn_rewards_v1 --sync-tolerance 300s -- --config itn_rewards_v1-config.yaml
   ```
2. I wait for the node to bootstrap and stake pools to sync (took about 40 minutes today).
3. I run `curl http://localhost:8090/v2/stake-pools` ... multiple times. I get the stake pools listed.

I have also checked that every stake pool in the registry as of today can be deserialized with the code (caching in `/tmp` enabled).

Please let us know, thanks.

**Comment by bourkefloyd** [comment]
I'll work on this tonight (logging/master branch build)

At a high level,

```printf "WARN starting: $(jormungandr --version), $(jcli --version), $(cardano-wallet version), config: ${_CONFIG},node_id: ${_NODE_ID},gbh: ${_GBH},rev: ${_REVISION_ID}\n" 1>&2
cardano-wallet serve --listen-address "0.0.0.0" --port 8444 --node-port 8443 \
  --database "/app/storage/wallet" \
  --verbose \
  --genesis-block-hash ${_GBH} &
jormungandr --config /app/cfg/${_CONFIG} --secret /app/secret-cfg/secret-node-config-${_NODE_ID}.yaml --genesis-block-hash ${_GBH}
```

```# 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676
p2p:
 trusted_peers:
  - address: "/ip4/13.56.0.226/tcp/3000"
    id: 7ddf203c86a012e8863ef19d96aabba23d2445c492d86267
  - address: "/ip4/54.183.149.167/tcp/3000"
    id: df02383863ae5e14fea5d51a092585da34e689a73f704613
  - address: "/ip4/52.9.77.197/tcp/3000"
    id: fcdf302895236d012635052725a0cdfc2e8ee394a1935b63
  - address: "/ip4/18.177.78.96/tcp/3000"
    id: fc89bff08ec4e054b4f03106f5312834abdf2fcb444610e9
  - address: "/ip4/3.115.154.161/tcp/3000"
    id: 35bead7d45b3b8bda5e74aa12126d871069e7617b7f4fe62
  - address: "/ip4/18.182.115.51/tcp/3000"
    id: 8529e334a39a5b6033b698be2040b1089d8f67e0102e2575
  - address: "/ip4/18.184.35.137/tcp/3000"
    id: 06aa98b0ab6589f464d08911717115ef354161f0dc727858
  - address: "/ip4/3.125.31.84/tcp/3000"
    id: 8f9ff09765684199b351d520defac463b1282a63d3cc99ca
  - address: "/ip4/3.125.183.71/tcp/3000"
    id: 9d15a9e2f1336c7acda8ced34e929f697dc24ea0910c3e67
 public_address: "/ip4/35.226.127.60/tcp/8299"
 listen_address: "/ip4/0.0.0.0/tcp/8299"
 topics_of_interest:
   messages: high
   blocks: high
rest:
 listen: "0.0.0.0:8443"
storage: "/app/storage"
mempool:
    pool_max_entries: 10000
    fragment_ttl: 30m
    log_max_entries: 100000
    log_ttl: 1h
    garbage_collection_interval: 15m
```

**Comment by bourkefloyd** [comment]
I noticed you are using `launch` instead of `serve`

**Comment by chbfiv** [comment]
I noticed you are using `launch` instead of `serve`

**Comment by KtorZ** [comment]
@chbfiv `launch` will start a `jormungandr` process for you and connects the server to it automatically. `launch` uses `serve` behind the scene.

**Comment by bourkefloyd** [comment]
I updated my entrypoint to the following (using cardano-wallet  `v2020-01-07` because otherwise I need to setup builds for cardano-wallet which is more work/risks)
```
cardano-wallet launch \
  --listen-address '0.0.0.0' \
  --port 8444 \
  --node-port 8443 \
  --state-dir '/app/storage/' \
  --sync-tolerance 300s \
  --verbose \
  --genesis-block-hash ${_GBH} -- --config /app/cfg/${_CONFIG} --secret /app/secret-cfg/secret-node-config-${_NODE_ID}.yaml
```
So now it's using the bundled `jormungandr`

```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:8443          0.0.0.0:*               LISTEN      18/jormungandr      
tcp        0      0 0.0.0.0:8444            0.0.0.0:*               LISTEN      13/cardano-wallet   
tcp        0      0 0.0.0.0:8299            0.0.0.0:*               LISTEN      18/jormungandr ```
```

I know the epoch is not up to date, but the problem appears to still be the same issue.
```
root@cardano-node-leader-ccb7fc695-t8lmc:/app/bin# cardano-wallet stake-pool list --port 8444
I can't list stake pools yet because I need to scan the blockchain for metrics first. I'm at 15%
root@cardano-node-leader-ccb7fc695-t8lmc:/app/bin# date --iso-8601=seconds
2020-01-11T17:31:39+00:00
```
```
root@cardano-node-leader-ccb7fc695-t8lmc:/app/bin# node_stats
---
blockRecvCnt: 928
lastBlockContentSize: 315
lastBlockDate: "19.322"
lastBlockFees: 800000
lastBlockHash: 72eb3f3e2ce4c662124f6d041194d426e507e15d718a38513bcf6f302c610506
lastBlockHeight: "62160"
lastBlockSum: 104440964434
lastBlockTime: "2020-01-01T19:24:21+00:00"
lastBlockTx: 1
lastReceivedBlockTime: "2020-01-11T17:33:55+00:00"
state: Running
txRecvCnt: 80
uptime: 691
version: jormungandr 0.8.5-3a108c38
```
```   
root@cardano-node-leader-ccb7fc695-t8lmc:/app/bin# cardano-wallet stake-pool list --port 8444
Ok.
[
    {
        "metrics": {
            "controlled_stake": {
                "quantity": 59546704741603,
                "unit": "lovelace"
            },
            "produced_blocks": {
                "quantity": 1,
                "unit": "block"
            }
        },
        "cost": {
            "quantity": 0,
            "unit": "lovelace"
        },
        "margin": {
            "quantity": 2,
            "unit": "percent"
        },
        "apparent_performance": 1,
        "id": "03a01cb9acffb3374c9a86ff39b2b5d85128c9ce3ac3fdba51ceceaca0685f98"
    },
...
 {
        "metrics": {
            "controlled_stake": {
                "quantity": 2573432249642,
                "unit": "lovelace"
            },
            "produced_blocks": {
                "quantity": 0,
                "unit": "block"
            }
        },
        "cost": {
            "quantity": 100000000,
            "unit": "lovelace"
        },
        "margin": {
            "quantity": 25,
            "unit": "percent"
        },
        "apparent_performance": 0,
        "id": "ffe7f3fb4f193fb64a8e39e9c9c45286a6aebeaf7001243bf6f25a1eec81b8e3"
    }
]
```
```
root@cardano-node-leader-ccb7fc695-t8lmc:/app/bin# ls /tmp/
stake-pool-metadata-90224d624d49f39c
root@cardano-node-leader-ccb7fc695-t8lmc:/app/bin# cardano-wallet stake-pool list --port 8444
Something went wrong
```

**Comment by bourkefloyd** [comment]
I put some more time/effort into this. 

So, even with a node in sync I'm getting the same error (see above).

I also downloaded cardano-wallet for mac and tested the same configs (wasn't hard to setup). So both the Docker container (ubuntu:18.04) and the mac have almost identical setups and the same source/release `cardano-wallet v2020-01-07`, just one is for mac and one is for linux.

cardano-wallet on mac worked as expected.

and again, on ubuntu:18.04, it has the `Something went wrong` error and no debug info.

**Comment by piotr-iohk** [comment]
Ok, I managed to reproduce it on my Ubuntu 18.04 using docker image and our integration tests' node. Reproducible every time.


1. Start wallet via docker image:
```
docker run -P \
	-p 127.0.0.1:8082:8082 \
	-p 127.0.0.1:8092:8092 \
	-v /tmp:/tmp \
	-v ~/wb/cardano-wallet/lib/jormungandr/test/data/jormungandr/:/config \
	--rm inputoutput/cardano-wallet:21ee81799ffb815ddba756bd9d94640b789e969b-jormungandr launch \
	--genesis-block /config/block0.bin \
	--node-port 8082 \
	--port 8092 \
	--state-dir ./data_launch \
	--listen-address '0.0.0.0' \
	-- --secret /config/secret.yaml --config /config/config.yaml
```

**Note:** Apparently `--listen-address '0.0.0.0'` is needed. Otherwise one cannot attach to the wallet's host:port from host machine. :man_shrugging: 

2. List stake-pools for the first time -> it works FINE.
```
$ cardano-wallet-jormungandr stake-pool list  --port 8092
Ok.
[
  ... metric are shown...
]
```
 In the log there is:

```
Downloading https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/archive/master.zip -> /tmp/stake-pool-metadata-d960810ee7504951/registry.zip: Started download
[cardano-wallet.stake-pool-layer:Notice:61] [2020-01-13 10:51:57.71 UTC] Stake pool metadata is unavailable
```

3. List stake-pools for the second time (and every subsequent time)

```
$ cardano-wallet-jormungandr stake-pool list  --port 8092
Something went wrong
```

In the log there is:
```
Downloading https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/archive/master.zip -> /tmp/stake-pool-metadata-d960810ee7504951/registry.zip: Using cached file last modified at 2020-01-13 10:51:57.562313246 UTC
Parsing of archive structure failed: 
Cannot locate end of central directory
in "/tmp/stake-pool-metadata-d960810ee7504951/registry.zip"
```

**Comment by KtorZ** [comment]
@piotr-iohk does the file IS actually present on your file-system at the expected location :thinking: ?

**Comment by piotr-iohk** [comment]
@KtorZ, no, as a matter of fact, it isn't here in `/tmp`...

**Comment by KtorZ** [comment]
Okay, so this explains why it can't find it and reduces the question to: why isn't the archive saved where it should be? 
What bothers me is this log line though:

```
Downloading https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/archive/master.zip -> /tmp/stake-pool-metadata-d960810ee7504951/registry.zip: Using cached file last modified at 2020-01-13 10:51:57.562313246 UTC
```

The server clearly detects a file at the given location and even the date at which it was last modified.

**Comment by rvl** [comment]
Probably what is happening is that the download failed for a Docker-container-related reason (e.g. missing ssl certificates, DNS resolution failed), but that exception was not caught by `fetchStakePoolMetaZip`. And then the function that calls `listStakePools` probably swallows the exception. An empty `registry.zip` is left behind, causing failures when it is opened next time.

This is how we can fix it:

1. If there is any exception downloading the registry, ensure that the temporary `registry.zip` is deleted.
2. Identify, handle and log the exception that happens in this case.
3. Adjust the inputoutput/cardano-wallet docker image so that the necessary configuration is present.

**Comment by bourkefloyd** [comment]
Sounds reasonable.

I would add that it's unlikely that it's failing 5/5 to download because of DNS/Network/Cert issues. In anycase if the exception isn't swallowed, it should make it more clear.

**Comment by rvl** [comment]
@chbfiv Do you have the [`ca-certificates`](https://packages.ubuntu.com/bionic/ca-certificates) package installed in your image? I think that (absent package) might be the problem.

**Comment by piotr-iohk** [comment]
Verified on recent master docker:
```
$ docker run --rm inputoutput/cardano-wallet:dev-master-jormungandr version
2020.1.14 (git revision: 81ca8e5c0cab59cdbb02427abdfd9acfab6014a9)
```

Runnig docker on local integration tests node:

```
docker run -P \
	-p 127.0.0.1:8080:8082 \
	-p 127.0.0.1:8090:8092 \
	-v ~/wb/cardano-wallet/lib/jormungandr/test/data/jormungandr/:/config \
	   --env TMPDIR=/config \
	  --env CARDANO_WALLET_STAKE_POOL_REGISTRY_URL=https://github.com/piotr-iohk/incentivized-testnet-stakepool-registry/archive/master.zip \
--rm inputoutput/cardano-wallet:dev-master-jormungandr \
launch \
--genesis-block /config/block0.bin \
--node-port 8082 \
--port 8092 \
--state-dir /config/data_launch \
--listen-address '0.0.0.0' \
-- --secret /config/secret.yaml --config /config/config.yaml
```
Listing stkepools with metadata works fine:

```
$ cardano-wallet-jormungandr stake-pool list
Ok.
[
    {
        "metrics": {
            "controlled_stake": {
                "quantity": 99999999945,
                "unit": "lovelace"
            },
            "produced_blocks": {
                "quantity": 3,
                "unit": "block"
            }
        },
        "cost": {
            "quantity": 0,
            "unit": "lovelace"
        },
        "margin": {
            "quantity": 0,
            "unit": "percent"
        },
        "apparent_performance": 0.750000000005,
        "metadata": {
            "homepage": "https://google.com",
            "owner": "ed25519_pk192m4ytl5k357e2l666yleuwjlurmf0vxjyh4atxzu5m22q6mexlsp88k7x",
            "name": "Integration tests stake pool",
            "ticker": "PIOTR",
            "pledge_address": "addr1skgrexh6vsm5cs9xjqrqypw24afssp9wjy0y7twt6qe269n5px84culdaer",
            "description": "My descroaapskfopsfoaskdfopaksdfpok paskdfp kaspodfk aposkd fpoaskdp ofkaspodfk paoskdf poaksdpof kapsodkf paskdf poakspod fkapsodkf posakdf poaskdpof kaspod kpaskd p okaspd kf"
        },
...
```
