### ISSUE TITLE
OWASP risks - Rate-limiter and others

### ISSUE THREAD

**Issue by paweljakubas** [cardano-foundation/cardano-wallet#1269]
# Context

Here I am working on the following assumption : 
**cardano-wallet API will be run locally, listening on localhost, for use by a trusted application (daedalus).**

**If it is going to be part of public API** the following areas need to be addressed : 
(a) obligatory use of HTTPS
Here, remember about adding response header HSTS, ie.,
`("Strict-Transport-Security", "max-age=31536000")`
(b) multi-level use of rate-limiter (on reverse proxy, gateway, and also attached directly to API as will be covered below) BEFORE next security components
(c) authentication (as a measure against DoS attacks and an input for access control)
Here, huge number of options are available (starting from simple ones)
- basic http authentication
- using secure password storage (Scrypt, Argon2, Bcrypt, ...) - see recent recommendation : https://pages.nist.gov/800-63-3/sp800-63b.html (and here, usage of memory-hard hash functions)
- Bearer auth scheme - OAuth2

(d) audit logging (so extend current logging by adding authorization logs). Consider using DB solution for logging (as a way to have in-house analytics on top of it or just try to use elasticsearch or summologic solutions directly on logs) 
(e) access control - differentiate actions AFTER authorization (401 vs 403). Think about Access Control Lists (ACL) and privilege escalation.

Generally speaking the above security mechanisms (ie., security controls of rate-limiting, encryption, authentication and audit logging), when properly applied, can address STRIDE threat (Spoofing, Tampering, Repudation, Information disclosure, Denial of service, Elevation of privilege).

Given the assumption, though, I think it would be beneficial to introduce rate-limiter solution to cardano-wallet and to have a solution that throttle number of calls possible to API (even trusted application can do it unintentionally). If this happens, then adequate response will be emitted.

# Decision

# Acceptance Criteria

---

# Development 

If we are to use rate-limiter then we should probably try to use https://hackage.haskell.org/package/wai-middleware-throttle
and as a test we should use : 
```
for i in {1..100}; do curl http://localhost:8090/v2/wallets --http1.1 ; done
``` 
and depending on number of request set in a given period for some of them we should end up with response header : `429 Too Many Requests` 

`Conclusions` : consider adding rate limiter as sketched above. If the assumption is not valid anymore then all security mechanisms enumerated above needs to be implemented in order to address STRIDE threat.  

# QA

**Comment by jonathanknowles** [comment]
Hi @paweljakubas 

Thanks for writing this up.

Am I correct in assuming that there is _currently_ no requirement for the wallet backend to be listening on anything other than `localhost`? (Of course, this might change in the future!)

If so, is the correct action to close this ticket (for the moment), but to reopen it if (and when) the requirements change?
