### ISSUE TITLE
Windows tests are failing on hydra

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#1283]
# Context
 
Integration and unit tests are now running in Hydra:

https://github.com/input-output-hk/cardano-wallet/issues/703#issuecomment-572949476

Although all integration and unit tests area passing on Windows when running locally:

https://github.com/input-output-hk/cardano-wallet/issues/1115#issuecomment-574693474

Some jobs are still failing on Hydra:

Unit:
 - [cardano-wallet-launcher.unit](https://hydra.iohk.io/job/Cardano/cardano-wallet/x86_64-pc-mingw32.checks.cardano-wallet-launcher.unit.x86_64-linux)
e.g. https://hydra.iohk.io/build/1585119

 - [cardano-wallet-core](https://hydra.iohk.io/job/Cardano/cardano-wallet/x86_64-pc-mingw32.checks.cardano-wallet-core.unit.x86_64-linux)
e.g. https://hydra.iohk.io/build/1585086

Integration:
 - [cardano-wallet-jormungandr.integration](https://hydra.iohk.io/job/Cardano/cardano-wallet/x86_64-pc-mingw32.checks.cardano-wallet-jormungandr.integration.x86_64-linux)
e.g. https://hydra.iohk.io/build/1585087
```
Finished in 0.3991 seconds
1120 examples, 132 failures, 983 pending
builder for '/nix/store/9w2gv6v9g8gj1q529mr0z08sqz8z884y-cardano-wallet-jormungandr-2020.1.14-test-integration-x86_64-pc-mingw32-check-x86_64-pc-mingw32.drv' failed with exit code 1
```

# Test Case

Unit:
 - [cardano-wallet-launcher.unit](https://hydra.iohk.io/job/Cardano/cardano-wallet/x86_64-pc-mingw32.checks.cardano-wallet-launcher.unit.x86_64-linux)
e.g. https://hydra.iohk.io/build/1585119

 - [cardano-wallet-core](https://hydra.iohk.io/job/Cardano/cardano-wallet/x86_64-pc-mingw32.checks.cardano-wallet-core.unit.x86_64-linux)
e.g. https://hydra.iohk.io/build/1585086

Integration:
 - [cardano-wallet-jormungandr.integration](https://hydra.iohk.io/job/Cardano/cardano-wallet/x86_64-pc-mingw32.checks.cardano-wallet-jormungandr.integration.x86_64-linux)
e.g. https://hydra.iohk.io/build/1585087

# Failure / Counter-example

---

# Resolution 

---

# QA

**Comment by KtorZ** [comment]
Still failing on Hydra:

job                                                                          | status
---                                                                          | ----
musl64.benchmarks.cardano-wallet-byron.latency.x86_64-linux                  | :x:
musl64.benchmarks.cardano-wallet-byron.restore.x86_64-linux                  | :x:
musl64.benchmarks.cardano-wallet-core.db.x86_64-linux                        | :x:
musl64.benchmarks.cardano-wallet-jormungandr.latency.x86_64-linux            | :x:
musl64.cardano-node.x86_64-linux                                             | :x:
musl64.checks.cardano-wallet-byron.integration.x86_64-linux                  | :x:
musl64.checks.cardano-wallet-byron.unit.x86_64-linux                         | :x:
musl64.checks.cardano-wallet-cli.unit.x86_64-linux                           | :x:
musl64.checks.cardano-wallet-core.unit.x86_64-linux                          | :x:
musl64.checks.cardano-wallet-jormungandr.unit.x86_64-linux                   | :x:
musl64.checks.cardano-wallet-launcher.unit.x86_64-linux                      | :x:
musl64.db-converter.x86_64-linux                                             | :x:
musl64.migration-tests.x86_64-linux                                          | :x:
musl64.tests.cardano-wallet-byron.integration.x86_64-linux                   | :x:
musl64.tests.cardano-wallet-byron.unit.x86_64-linux                          | :x:
musl64.tests.cardano-wallet-cli.unit.x86_64-linux                            | :x:
musl64.tests.cardano-wallet-core.unit.x86_64-linux                           | :x:
musl64.tests.cardano-wallet-jormungandr.jormungandr-integration.x86_64-linux | :x:
musl64.tests.cardano-wallet-jormungandr.unit.x86_64-linux                    | :x:
musl64.tests.cardano-wallet-launcher.unit.x86_64-linux                       | :x:
native.stackShell.x86_64-darwin                                              | :x:
stackShell.x86_64-darwin                                                     | :x:
x86_64-w64-mingw32.stackNixRegenerate.x86_64-linux                           | :x:


I don't quite know why do we have all the `musl64.tests` and `musl64.benchmarks` jobs in the first place though. As far as I understood, the musl64 category is for building static binaries on linux ? 

And I also don't know what "stackShell" is for. 

Any idea @rvl ?

**Comment by rvl** [comment]
The Hydra [`required` job](https://hydra.iohk.io/job/Cardano/cardano-wallet/required/latest-finished#tabs-constituents) is passing, and this is what counts for CI status in GitHub and Bors. I put an explanation here:  [Hydra wiki page](https://github.com/input-output-hk/cardano-wallet/wiki/Hydra#required-job).

The `stackShell` attr is not documented where it is defined in [`default.nix`](https://github.com/input-output-hk/cardano-wallet/blob/77400e0a34eba0eca9985c5d90d9293b8e36df11/default.nix#L146-L148), but is documented in the header of [`nix/stack-shell.nix`](https://github.com/input-output-hk/cardano-wallet/blob/77400e0a34eba0eca9985c5d90d9293b8e36df11/nix/stack-shell.nix#L1-L2).

The `musl64` prefix is documented in the [jobset file](https://github.com/input-output-hk/cardano-wallet/blob/77400e0a34eba0eca9985c5d90d9293b8e36df11/release.nix#L13). I didn't concentrate on making these build because if the tests pass on linux then they are quite likely to pass on linux musl.

I have opened a PR to make all failing jobs either green or disabled ⇒ #1566.

**Comment by piotr-iohk** [comment]
LGTM.
