### ISSUE TITLE
[Failing Test Case]: TRANS_CREATE_02

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1284]
# Context
 
 

https://buildkite.com/input-output-hk/cardano-wallet/builds/5328#1d9a54fe-bcb0-4f21-a17b-9a093b868663/6-7580

https://buildkite.com/input-output-hk/cardano-wallet/builds/5337#ec96cd20-ec2d-4b03-b0e7-f32bb995393c/6-7586

https://buildkite.com/input-output-hk/cardano-wallet/builds/5401#763cc2bb-8c24-4fb3-960f-d8c14c15bcfb/6-7557

https://buildkite.com/input-output-hk/cardano-wallet/builds/5447#f8ed8dcf-3f33-4cb1-a758-11b4c1e308f6

# Test Case

https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core-integration/src/Test/Integration/Scenario/API/Transactions.hs#L244-L300

# Failure / Counter-example

```hs
src/Test/Integration/Framework/DSL.hs:351:16:
      1) API Specifications TRANS_CREATE_02 - Multiple Output Tx to single wallet
           expected: Quantity {getQuantity = 800000000000}
            but got: Quantity {getQuantity = 999999999966}
```
---

# Resolution 

---

# QA

**Comment by jonathanknowles** [comment]
It's worth noting that the linked test cases also show another failure:
```hs
      src/Test/Integration/Framework/DSL.hs:351:16:
      2) API Specifications TRANS_DELETE_01 - Shelley: Can forget pending transaction
           expected: Quantity {getQuantity = 900000000000}
            but got: Quantity {getQuantity = 999999999976}
```

I've added this failure case to the description, as well as the seeds that provoked these failures.

**Comment by jonathanknowles** [comment]
I was **unable** to reproduce these failures on `master`, even when using the **exact same seeds**. I used the following commands:

```hs
stack build --fast --test cardano-wallet-jormungandr:test:integration --test-arguments '-m "TRANS_CREATE_02 - Multiple Output Tx to single wallet" --seed 2110751146'
stack build --fast --test cardano-wallet-jormungandr:test:integration --test-arguments '-m "TRANS_CREATE_02 - Multiple Output Tx to single wallet" --seed 1461099880'
stack build --fast --test cardano-wallet-jormungandr:test:integration --test-arguments '-m "TRANS_DELETE_01 - Shelley: Can forget pending transaction" --seed 1461099880'

```
Just for completeness, I tried to reproduce these failures with the same commits that triggered them, but still could not reproduce the errors.

@KtorZ Perhaps we should close this off for now? We can reopen it if we see similar failures later on.

**Comment by paweljakubas** [comment]
@jonathanknowles I confirm your findings - was also looking at the issue yesterday and was not able to reproduce it locally

**Comment by KtorZ** [comment]
One more occurrence of this in buildkite today.

**Comment by Anviking** [comment]
Saw it again multiple times in #1303

**Comment by Anviking** [comment]
https://github.com/input-output-hk/cardano-wallet/pull/1369#issuecomment-591501691
```
Failures:
    
      src/Test/Integration/Scenario/API/Transactions.hs:276:22: 
      1) API Specifications TRANS_CREATE_02 - Multiple Output Tx to single wallet
           expected: Quantity {getQuantity = 800000000000}
            but got: Quantity {getQuantity = 999999999966}
    
      To rerun use: --match "/API Specifications/TRANS_CREATE_02 - Multiple Output Tx to single wallet/"
    
    Randomized with seed 1108137962
    
    Finished in 1303.2039 seconds
    683 examples, 1 failure
```

**Comment by Anviking** [comment]
Is this a race-condition?

It seems like the source wallet is not subtracting the spending from its available balance in time.

However, these two lines should surely be run in order? 🤔 
```haskell
r <- request @(ApiTransaction n) ctx (Link.createTransaction wSrc) Default payload
ra <- request @ApiWallet ctx (Link.getWallet @'Shelley wSrc) Default Empty
```

**Comment by paweljakubas** [comment]
yeah, I do think so also, probably we need to use `eventually` for r and wait for tx to be `Pending`, and then get `ra`.  This is what I planned to do and then invoke bors try 20x ;-)

**Comment by KtorZ** [comment]
@paweljakubas how are we doing regarding this one?

**Comment by paweljakubas** [comment]
I have tried several things until now and still the bug eludes me. My findings:
1. I have tried locally (whole tests suite) many many times and was not able to produce it locally.
2. I thought that maybe that when we have 
```
r <- request @(ApiTransaction n) ctx (Link.createTransaction wSrc) Default payload
ra <- request @ApiWallet ctx (Link.getWallet @'Shelley wSrc) Default Empty
```
then we cannot be sure about call order and we need to enforce it. So I tried 
`deepseq` but it did not help
3. Then I just tried what is done for other test, ie.,
```
        r <- TR.trace("---- TRANS_CREATE_02 A") $ request @(ApiTransaction n) ctx (Link.createTransaction wSrc) Default payload
        TR.trace("---- TRANS_CREATE_02 AA") $ expectResponseCode HTTP.status202 r
        verify r
            [ expectField (#amount . #getQuantity) $
                between (feeMin + (2*amt), feeMax + (2*amt))
            , expectField (#direction . #getApiT) (`shouldBe` Outgoing)
            , expectField (#status . #getApiT) (`shouldBe` Pending)
            ]

        ra <- TR.trace("---- TRANS_CREATE_02 B") $ request @ApiWallet ctx (Link.getWallet @'Shelley wSrc) Default Empty
        TR.trace("---- TRANS_CREATE_02 B") $ expectResponseCode HTTP.status200 ra
        verify ra
            [ expectSuccess
            , expectField (#balance . #getApiT . #total) $
                between
                ( Quantity (faucetAmt - feeMax - (2*amt))
                , Quantity (faucetAmt - feeMin - (2*amt))
                )
            , expectField
                (#balance . #getApiT . #available)
                (`shouldBe` Quantity (faucetAmt - 2 * faucetUtxoAmt))
            ]
```
Still failing quite often ...
What is interesting is that `TRANS_CREATE_02 - Multiple Output Tx to different wallets` does not fail (and it has similar structure)

**Comment by paweljakubas** [comment]
now, will put debugs, also only run Transaction.spec (as logs have 1MB limit) and try to compare failure logs with successful ones.

**Comment by KtorZ** [comment]
Closing this one as it seemed to have resolved itself with the recent CI changes.
