### ISSUE TITLE
Introduce endpoint scaffolding and needed types to service it

### ISSUE THREAD

**Issue by paweljakubas** [cardano-foundation/cardano-wallet#1291]
# Context

U/S

As an API client, 
I can get blockchain parameters for various epochs,
And I can get blockchain parameters for the latest epoch,
So that I can build better interfaces based on these parameters.

# Decision

We are creating : 
```
paths: 
  /network/parameters/{epoch}:
    get: 
      operationId: getNetworkParameters
      tags: ["Network"]
      summary: Parameters
      parameters: 
        - *parametersEpoch
      responses: *responsesGetNetworkParameters
```

# Acceptance Criteria

1. Create endpoint scaffolding and introduce new types (if necessary to service that)

---

# Development 

# QA 

Tests in #1302

**Comment by piotr-iohk** [comment]
lgtm.
