### ISSUE TITLE
cardano-wallet-jormungandr.exe not shutting down correctly after 1h on Windows when not connected

### ISSUE THREAD

**Issue by alan-mcnicholas** [cardano-foundation/cardano-wallet#1293]
# Context
 
When testing with a development build of Daedalus on Windows I was unable to complete the bootstrap phase within 1h which lead to the following error in `node.log`:

`Waited too long for Jörmungandr to become available. Giving up!`

Following this the Daedalus client remains open as does the `cardano-wallet-jormungandr.exe` process; `jormungandr.exe` appears to be terminated however
[node.log](https://github.com/input-output-hk/cardano-wallet/files/4091220/node.log)

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | 2020.1.14 |
| Platform     | Windows 10 |
| Installation | https://buildkite.com/input-output-hk/daedalus/builds/10375  |

# Steps to Reproduce
1. Install the Windows ITN build of Daedalus from the link above
2. Leave client to sync (note with unstable\unreachable peers this did not complete within 1 hour 

## Expected behavior

When the 1 hour mark is reached the client is not correctly synchronized the wallet backend process should give up and terminate relevant processes.

## Actual behavior
 
The jormungandr node appears to be terminated however the cardano-wallet process and daedalus process is still active.

---

# Resolution 

---

# QA 

[node.log](https://github.com/input-output-hk/cardano-wallet/files/4091221/node.log)

**Comment by rvl** [comment]
Thanks @alan-mcnicholas.

This is interesting because literally [the next line after that log message](https://github.com/input-output-hk/cardano-wallet/blob/v2020-01-14/lib/cli/src/Cardano/CLI.hs#L1402-L1403) is an `exitFailure` call to exit cardano-wallet.

Calling exitFailure will cause all the shutdown handlers to run. It appears that the one which should terminate jormungandr.exe has completed. One of the other exit handlers may have locked up.

**Comment by rvl** [comment]
Let's wait for Daedalus to integrate [cardano-launcher](https://github.com/input-output-hk/cardano-launcher) into itn_rewards_v1 then see if this behaviour still occurs.

**Comment by KtorZ** [comment]
Plan has changed and there shouldn't be any more release of Daedalus on the ITN. The new launcher will only serve the Haskell cardano-node. So this issue doesn't apply anymore. Closing.
