### ISSUE TITLE
[Feature Request] GetPool API endpoint

### ISSUE THREAD

**Issue by Fell-x27** [cardano-foundation/cardano-wallet#1300]
There are already more than 900 pools. And more in the future.
Right now there is only an endpoint that fetches the whole pools list. 

Even if we need for only one, we have to fetch 900+ and then find a needle in the cycle...
Yes, I solve it for myself with my own caching system etc, but would be great to see a simple GET endoint, smth like "getPool" which takes a pool id as parameter.

**Comment by KtorZ** [comment]
Good point. And this makes me realize that we have no template for actual feature request :) 
I'll add this to our product backlog and discuss that with the rest of the team.

**Comment by KtorZ** [comment]
Moved to a separate issue tracker (sorry, not public :s) where we keep incoming product requirements. Chances are that this would likely land for the testnet coming with cardano-node, but not on the ITN.
