### ISSUE TITLE
How to connect Cardano-wallet to a remote Cardano node instead of spawning a local node ??

### ISSUE THREAD

**Issue by aqua-regia** [cardano-foundation/cardano-wallet#1311]
I am using this script [https://github.com/TheDevKnight/cardano-sl-wallet/blob/master/connect-to-mainnet](url) to create a wallet. 
The thing is because of some security issues I do not want to start the node in the same machine where I keep the wallet. 
I still want to use the wallet apis (create account, publish transactions) but I don't want to keep it in the same machine.

**Comment by rvl** [comment]
Hi @aqua-regia, this script is for the [old codebase](https://github.com/input-output-hk/cardano-sl) - in that case the node is running in the same _process_ as the wallet. There is no way to separate them. 

We are currently in the process of integrating the [rewritten cardano-node](https://github.com/input-output-hk/cardano-node) for mainnet into the rewritten cardano-wallet codebase (this repo). We will take your use case into consideration for our roadmap.

**Comment by rvl** [comment]
One thing which might help is placing another node in front of your wallet as a relay.

**Comment by aqua-regia** [comment]
In that case I would not my relay node to be connected to be connected to any other node except my node ( which I trust). Is there a provision to do so ??

**Comment by KtorZ** [comment]
I moved this to a separate issue tracker. There's currently no way to connect the wallet server itself to a remote node. As of today, the underlying node and the wallet server have be on the same host machine (though the node itself can connect to a remote peer).
