### ISSUE TITLE
Astronomical block production reported in cardano-wallet 1-27-2020

### ISSUE THREAD

**Issue by JSCSJSCS** [cardano-foundation/cardano-wallet#1323]
I just upgrade from 14 to 27 of cardano-wallet and found that near the end of epoch 49, it reports that 153,994 blocks were produced when counted! There might be an issue. Below is sample output of one pool's data:

I am running Windows 10 home. I have been using a data connection to a spreadsheet for analytics for weeks and after this upgrade was shocked to see the total blocks. A review of a few pools confirmed the results.
jormungandr 0.8.9 (HEAD-30d20d2e, release, windows [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
jcli 0.8.9 (HEAD-30d20d2e, release, windows [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

sample results from http://127.0.0.1:8090/v2/stake-pools - note quantity of blocks 1709 below.

```
{
"saturation": 0.801145582730889,
"metrics": {
"controlled_stake": {
"quantity": 86018857583973,
"unit": "lovelace"
},
"produced_blocks": {
"quantity": 1709,
"unit": "block"
}
},
"cost": {
"quantity": 0,
"unit": "lovelace"
},
"margin": {
"quantity": 1,
"unit": "percent"
},
"apparent_performance": 1.420845289152538,
"metadata": {
"homepage": "https://bluecheesestakehouse.com",
"owner": "ed25519_pk1gy0e8lw4dnlkullq559c79nfmanr6e62d3c3trp6c8jsjkvges6q57672t",
"name": "Blue Cheese Stake House",
"ticker": "BCSH",
"pledge_address": "addr1s4q3lyla64k07mnluzjshrckd80kv0t8ffk8z9vv8tq72z2e3rxrg3s377j"
},
```

Steps to reproduce:
Download latest cardano-wallet windows zip 27-1-2020
Close cardano-wallet serve
replace files with new from zip
Restart cardano-wallet serve
./cardano-wallet.exe serve --node-port 3101 --port 8090 --genesis-block-hash 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676
Allow to rebuild state using currently running jormungandr v 0.8.9
Check status of various pools with http://127.0.0.1:8090/v2/stake-pools

It should be noted that I also tried completely closing the shell and rebuilding it again. Same results.

I rolled back to 1-14-2020 and let it rebuild and it is normal again.

**Comment by JSCSJSCS** [comment]
Upload of start of epoch 50 data.
![Untitled](https://user-images.githubusercontent.com/656601/73597821-2c521d80-44e5-11ea-8a97-c25965a221a8.png)

**Comment by KtorZ** [comment]
Nothing really shocks me here. 49 epochs with an active coefficient of 10% (like on the ITN) means that ~200k blocks should have been produced at the end of epoch 49. 

Note however that since 2037c6049f72b2274f38d91915d310395bc9c690 the API does no longer report the block production of the current epoch but instead, report the TOTAL block production since the existence of a pool. We should make sure the release notes mentions this change (cc @piotr-iohk).

**Comment by JSCSJSCS** [comment]
I did not see the change and had I done so, would have suggested to add the total quantity as data point, not replace the current epoch block count with total block count. What method is there to see the current epoch block performance for all pools now? Why not have the API report both?

**Comment by KtorZ** [comment]
Having the API reports both is a possibility that we considered. As well as simply adding a new field (which would have also been my preferred approach to be fair). Yet, other constraints have pushed us to replace the semantic of the existing field. Getting the current block production from the API is no longer possible. 
If that is something you'd be interested in, then I might re-open this ticket and label it as a "feature request" so we can keep track of it.

**Comment by KtorZ** [comment]
Ok. Just saw this: https://github.com/input-output-hk/cardano-wallet/issues/1324 ^.^

**Comment by KtorZ** [comment]
Note that, what's most likely to happen is the creation of a new endpoint which would reconcile both #1324 and #1300 but this needs proper thinking and adequate design for it needs to fit with the upcoming integration with the Shelley Haskell nodes.

**Comment by JSCSJSCS** [comment]
Thank you for the consideration, in the interim, is there another method to retrieve all the individual pools and their current epoch blocks produced, at one time, not a sum total or 974 individual calls?

**Comment by KtorZ** [comment]
@JSCSJSCS I am afraid there's none.
