### ISSUE TITLE
Feature Request: Add back current epoch block production to cardano-wallet API

### ISSUE THREAD

**Issue by JSCSJSCS** [cardano-foundation/cardano-wallet#1324]
Commit [2037c60](https://github.com/input-output-hk/cardano-wallet/commit/2037c6049f72b2274f38d91915d310395bc9c690) changed a quantity data point from blocks in current epoch to a count of total blocks produced. I was using the current epoch blocks produced data point and I cannot find another API call that will give me the previously supplied data. Could the cardano-wallet API be changed to provide both current epoch block production as well as the new total blocks produced?

Example output:
```
{
"saturation": 0.801145582730889,
"metrics": {
"controlled_stake": {
"quantity": 86018857583973,
"unit": "lovelace"
},
"current_produced_blocks": {
"quantity": 12,
"unit": "block"
}
},
"total_produced_blocks": {
"quantity": 1709,
"unit": "block"
}
},
"cost": {
"quantity": 0,
"unit": "lovelace"
},
"margin": {
"quantity": 1,
"unit": "percent"
},
"apparent_performance": 1.420845289152538,
"metadata": {
"homepage": "https://bluecheesestakehouse.com",
"owner": "ed25519_pk1gy0e8lw4dnlkullq559c79nfmanr6e62d3c3trp6c8jsjkvges6q57672t",
"name": "Blue Cheese Stake House",
"ticker": "BCSH",
"pledge_address": "addr1s4q3lyla64k07mnluzjshrckd80kv0t8ffk8z9vv8tq72z2e3rxrg3s377j"
},
```

Thank you.

**Comment by KtorZ** [comment]
Now tracked in JIRA as part of the backlog :+1: , closing that one.
