### ISSUE TITLE
CLI support for GET blockchain params

### ISSUE THREAD

**Issue by paweljakubas** [cardano-foundation/cardano-wallet#1328]
# Context

U/S

As an API client, 
I can get blockchain parameters for various epochs usisng CLI,
And I can get blockchain parameters for the latest epoch using CLI,
So that I can build better interfaces based on these parameters interacting with CLI.

# Decision

We are adding CLI support for this endpoint

# Acceptance Criteria

1. The CLI must allow fetching blockchain parameters for any given epoch from a new endpoint
2. The keyword "latest" may be used to refer to the latest epoch (from the perspective of the network)

---

# Development 

# QA 

 - Integration tests -> https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core-integration/src/Test/Integration/Scenario/CLI/Network.hs#L53-L87
 - CLI man has been updated as well -> https://github.com/input-output-hk/cardano-wallet/wiki/Wallet-command-line-interface#network-parameters

**Comment by piotr-iohk** [comment]
Lgtm. 
 - Integration tests -> https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core-integration/src/Test/Integration/Scenario/CLI/Network.hs#L53-L87
 - CLI man has been updated as well -> https://github.com/input-output-hk/cardano-wallet/wiki/Wallet-command-line-interface#network-parameters

Also added #1341. (few new cases, and small refactor)
