### ISSUE TITLE
0.5% profit margin of pool is rounded to 0%

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#1331]
# Context

The pool margin/fee is a rational number on-chain.

It is converted to a `Percentage`-type here: https://github.com/input-output-hk/cardano-wallet/blob/fcde98eeb8e895db0a770be7cab17995881b9ed2/lib/jormungandr/src/Cardano/Wallet/Jormungandr/Binary.hs#L1082-L1083

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      |  |
| Platform     |           |
| Installation |             |

# Steps to Reproduce

1. List stake pools via CLI or Daedalus
2. Lookup the margin of the `PNT5` pool.

## Expected behavior

1. It should have a `0.5%` profit margin. (Have not confirmed on chain, but sounds very plausible)

## Actual behavior

1. Profit margin is displayed as `0%`.
 

---

# Resolution 

- #1399 Make `Percentage` type more precise

---

# QA 

- Tested manually with Daedalus that PNT5 has `0.5%` margin, and that migration works.
- Golden `ToText`/`ToJSON` tests https://github.com/input-output-hk/cardano-wallet/blob/7482427ff79946124d7142dc4784909c877023d4/lib/core/test/unit/Data/QuantitySpec.hs#L79-L89

**Comment by piotr-iohk** [comment]
lgtm!
