### ISSUE TITLE
Add polish to Hackage `bech32` library.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#1332]
# Context

The `cardano-wallet` repository is currently using its own copy of the `bech32` library. We'd like to switch to the Hackage version, which is based on the following repository:

https://github.com/input-output-hk/bech32

# Decision

As part of this process, we should make sure that our published library meets standards typically expected by the Haskell community.

# Acceptance Criteria

- [x] The package _must_ be buildable by both `cabal` and `stack`.
- [x] The package _must_ be properly licensed.
- [x] The package _must_ have appropriate copyright messages.
- [x] The package Haddock documentation _must_ build correctly.
- [x] The package _must_ have a working continuous integration system.
- [x] The package documentation _must_ include basic usage instructions.
- [x] The package documentation _should_ include a basic guide for contributors.

# Development 

- [x] Add basic usage instructions to https://github.com/input-output-hk/bech32 and to Haddock documentation.
- [x] Add missing exports to `Codec.Binary.Bech32` (see issue https://github.com/input-output-hk/bech32/issues/3)
- [x] Go through and check the haddock documentation for errors and omissions.
- [x] Release a new minor version `v1.0.1` to Hackage (in accordance with https://pvp.haskell.org/): https://hackage.haskell.org/package/bech32-1.0.1
- [x] Ensure that Hackage has a working version of the Haddock documentation for `v1.0.1`: https://hackage.haskell.org/package/bech32-1.0.1/docs/Codec-Binary-Bech32.html
- [x] Add the package to stackage: https://www.stackage.org/haddock/nightly-2020-02-14/bech32-1.0.1/Codec-Binary-Bech32.html
- [x] Add build status badge to home page.
         [![Build Status](https://travis-ci.org/input-output-hk/bech32.svg?branch=master)](https://travis-ci.org/input-output-hk/bech32)
- [x] Add last release badge to home page.

# QA

- [x] Verify that CI is working correctly:
    - :+1: example of a **successful** build : https://travis-ci.org/input-output-hk/bech32/jobs/649822654
    - :-1: example of a **failing** build: https://travis-ci.org/input-output-hk/bech32/builds/650333453
- [x] Ensure that CI also runs when the `master` branch is updated, and not just on PRs.

**Comment by jonathanknowles** [comment]
https://github.com/input-output-hk/bech32/pull/8

**Comment by jonathanknowles** [comment]
Hi @piotr-iohk!
Are you happy with me closing this issue? I believe that all the items are complete.

**Comment by piotr-iohk** [comment]
@jonathanknowles lgtm.

One question/remark: there are some tests there in the new repo -> https://github.com/input-output-hk/bech32/blob/master/test/Codec/Binary/Bech32Spec.hs, but I suppose they are only executed "manually" ? Maybe it would be worth to set up small CI (Travis?) to have those tests executed?

**Comment by jonathanknowles** [comment]
> @jonathanknowles lgtm.
> 
> One question/remark: there are some tests there in the new repo -> https://github.com/input-output-hk/bech32/blob/master/test/Codec/Binary/Bech32Spec.hs, but I suppose they are only executed "manually" ? Maybe it would be worth to set up small CI (Travis?) to have those tests executed?

Good question!

The repository does have Travis set up on it: https://github.com/input-output-hk/bech32/blob/master/.travis.yml

Here's an example build that passed: https://travis-ci.org/input-output-hk/bech32/jobs/649822654

**Comment by piotr-iohk** [comment]
Oh, cool, then perhaps a badge pointing to last travis build on the README would be handy? Maybe also a last release badge? (Similar to what we have on [cardano-wallet](https://github.com/input-output-hk/cardano-wallet))

**Comment by jonathanknowles** [comment]
> Oh, cool, then perhaps a badge pointing to last travis build on the README would be handy? Maybe also a last release badge? (Similar to what we have on [cardano-wallet](https://github.com/input-output-hk/cardano-wallet))

Good idea! I'll add it. :)

**Comment by KtorZ** [comment]
@jonathanknowles How familiar are you with https://coveralls.io ?

**Comment by jonathanknowles** [comment]
> @jonathanknowles How familiar are you with https://coveralls.io ?

I've occasionally looked at the reports relating to `cardano-wallet`. Are you proposing that we add coveralls support to the `bech32` repo?

**Comment by jonathanknowles** [comment]
@piotr-iohk Latest build status of `master` now reflected on home page:

![bech32-build-passing](https://user-images.githubusercontent.com/206319/74517012-617e5700-4f4c-11ea-88c2-892285c31f17.png)

https://github.com/input-output-hk/bech32
https://travis-ci.org/input-output-hk/bech32

**Comment by KtorZ** [comment]
> Are you proposing that we add coveralls support to the bech32 repo?

Precisely :no_mouth: 
I know it is _possible_ through cabal directly, but I've always computed coverage via stack builds. So maybe it's too much efforts here (as I see that the .travis.yml makes use of cabal builds).

**Comment by KtorZ** [comment]
--> https://github.com/lunaticare/codecov-haskell

This seems fairly "recent" though. It's for https://codecov.io (which IMO is even better than coveralls, in terms of UI and available information, see for instance https://codecov.io/gh/elm-toulouse/cbor). Maybe it's worth giving it a shot.

**Comment by jonathanknowles** [comment]
**Removed code coverage support** from the list of items, in the interests of wrapping up this story.

We can add it to a future story, as and when we need to.

**EDIT:** Added here: https://jira.iohk.io/projects/ADP/issues/ADP-181

**Comment by jonathanknowles** [comment]
Hi @piotr-iohk 

I believe this task is now finished, as we moved the code coverage work to a new story.

Is there anything left outstanding from your point of view?

**Comment by jonathanknowles** [comment]
Closing, after discussion with @piotr-iohk.
