### ISSUE TITLE
Remove local copies of Bech32 libraries.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#1333]
# Context

We'd like to switch to using the Hackage version of the [Bech32 libraries](https://github.com/input-output-hk/bech32) instead of our own copy (in `cardano-wallet/lib/bech32`).

# Decision

After bringing the published libraries and our local copies into parity with one another, we will remove our local copies of the libraries, and depend only on the [published versions](https://github.com/input-output-hk/bech32).

# Acceptance Criteria

- [x] The `cardano-wallet` code base _must_ only depend on the published [Bech32 libraries](https://github.com/input-output-hk/bech32).
- [x] The `cardano-wallet` repository _must not_ include local duplicates of the [Bech32 libraries](https://github.com/input-output-hk/bech32).
- [x] All published libraries _must_ be available on Hackage.
- [x] All published libraries _must_ be available on Stackage.

# Rejected Acceptance Criteria

- [x] ~~The `cardano-wallet` repository _may_ include a reference to the [Bech32 repository](https://github.com/input-output-hk/bech32) via a `git` submodule.~~
    **Reasons for rejection:**
    1. Including the published libraries as extra dependencies in `stack.yaml` is a simple solution that works well enough.
    2. We don't currently have a compelling use case for including a submodule. If such a use case appears in future, we can revisit the idea of adding a submodule.

# Development 

- [x] Remove local copy of `bech32` library, and rely instead of the Hackage version.
- [x] Create a new library `bech32-th` to contain Template-Haskell-specific extensions to the `bech32` library. (See https://github.com/input-output-hk/bech32/pull/15)
- [x] Add the `bech32-th` library to Hackage.
- [x] Remove our local copy of `Codec.Binary.Bech32.TH` and instead depend on the Hackage version of `bech32-th`.
- [x] Add the `bech32-th` library to Stackage. (https://github.com/commercialhaskell/stackage/pull/5196).

# QA 

- [x] Ensure that the `bech32-th` library has a suitable test suite. At the very least, we want to check that compile errors happen when they should. (See https://github.com/input-output-hk/bech32/pull/15)
- [x] Ensure that the `bech32` repository CI script runs all test suites (for both `bech32` and `bech32-th`).  (See https://github.com/input-output-hk/bech32/pull/15)

**Comment by KtorZ** [comment]
@jonathanknowles I think we should really move this to the core bech32 library too: https://github.com/input-output-hk/cardano-wallet/blob/26041904b815f17871bbcc07b85cd14bfbb802bf/lib/core/src/Codec/Binary/Bech32/TH.hs 

Don't you agree?

**Comment by jonathanknowles** [comment]
> @jonathanknowles I think we should really move this to the core bech32 library too: https://github.com/input-output-hk/cardano-wallet/blob/26041904b815f17871bbcc07b85cd14bfbb802bf/lib/core/src/Codec/Binary/Bech32/TH.hs
> 
> Don't you agree?

I agree that it would be nice to move this out of `cardano-wallet`.

Though one thing that may affect our decision is that this module depends on **Template Haskell**. I'm aware that people have strong opinions about (not) depending on TH.

Perhaps a good compromise solution would be to keep `bech32` as it is, but define **`bech32-th`** as an extension library? That way, people can choose whether or not they want to include the TH bits. (It seems this pattern has precedent in the Haskell community. For example: [`web-routes`](https://hackage.haskell.org/package/web-routes) and [`web-routes-th`](https://hackage.haskell.org/package/web-routes-th))

It wouldn't be much difference in the work involved, IMO. We can just replicate the approach we already used for `bech32`.

Link to related discussion: https://input-output-rnd.slack.com/archives/C48HA39RS/p1581914194101600

**Comment by KtorZ** [comment]
> @jonathanknowles said: Perhaps a good compromise solution would be to keep bech32 as it is, but define bech32-th as an extension library? 

This sounds like a nice compromise! I'd however strongly recommend to NOT create another repository for this, but have both package part of the same `bech32` repository to make maintenance a bit easier.

**Comment by jonathanknowles** [comment]
> I'd however strongly recommend to NOT create another repository for this, but have both package part of the same `bech32` repository to make maintenance a bit easier.

Okay, sounds great, I'll do this. :+1:

**Comment by jonathanknowles** [comment]
@KtorZ https://github.com/input-output-hk/bech32/pull/15

**Comment by jonathanknowles** [comment]
Hi @piotr-iohk!

I think all the tasks on this issue are now complete.

Are you okay for me to close the issue?
