### ISSUE TITLE
Complete Local Tx Submission integration

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1346]
# Context

When doing the first bits of integration with the Haskell nodes, we left a placeholder for transaction submission: https://github.com/input-output-hk/cardano-wallet/blob/master/lib/byron/src/Cardano/Wallet/Byron/Network.hs#L559

# Decision

- Complete the integration with the local tx submission protocol
- Test this on a private blockchain, if possible.

# Acceptance Criteria

- The network interface _must_ support sending transaction via the local tx submission
- `cardano-wallet` _must_ be integrated with the most recent release of the cardano-node's stack 

---

# Development 

- Integrate with the tx local submission and completed the postTx handler of the network layer ==> #1348 
- Upgrade cardano-node's dependencies to latest release (1.5.0) ==> #1347  #1358 
- See if we can connect the wallet to a private Haskell blockchain ==> #1414 

# QA 

See #1347

**Comment by piotr-iohk** [comment]
lgtm
