### ISSUE TITLE
Add tx submission to the byron API

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1347]
# Context

We didn't initially add this for Jörmungandr because it is not possible to make transaction to legacy addresses in Jörmungandr (which makes it fairly impractical to construct transactions from legacy wallets which have change addresses that are necessarily legacy addresses). 

Yet, for the Byron integration, we need wallets to support transaction submission in the very same way. So, it'd be nice to get closer to API parity between byron and shelley wallets.

# Decision

- Allow POSTing transaction to `/byron-wallets/.../transactions` similarly to 'standard' wallets.
- On Jörmungandr, this is known to generate invalid transaction.

# Acceptance Criteria

- The API _must_ support creating payment transaction from byron wallets.

---

# Development 

- Implement the API endpoint ==> #1350 

# QA 

- Added integration setup for cardano-node, this does not run in CI _yet_ :
    https://github.com/input-output-hk/cardano-wallet/blob/master/lib/byron/test/integration/Main.hs#L111-L115

- Integration tests cover byron wallet scenarios, byron transaction scenarios, network scenarios as well as transaction scenarios ported from the core-integration scenarios but adjusted to work on the newly introduced transactions endpoint in the Byron API.
   - see: https://github.com/input-output-hk/cardano-wallet/blob/master/lib/byron/test/integration/Test/Integration/Byron/Scenario/API/Transactions.hs#L99-L145

**Comment by piotr-iohk** [comment]
lgtm.

It would be nice then to employ those tests in CI as soon as possible.
