### ISSUE TITLE
Add `key child --path` command for CLI key derivation

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#1353]
# Context

[ADP-81](https://jira.iohk.io/browse/ADP-81)

The groundwork for CLI key derivation is being established in #1316.

# Decision

Implement command for deriving child keys, according to the example:
```bash
  $ key child --path 44'/1815'/0'/0 5bd164a28...1ae275939
  0d0a62eef...6f2aee621
```

# Acceptance Criteria

- We _must_ be able to derive keys using hard derivation.
- We _must_ support soft derivation on relevant paths.

---

# Development 

- [x] Added `key child` command  #1321 

# QA 

- Integration tests: https://github.com/input-output-hk/cardano-wallet/blob/9eb96075f841565bd7494eb815a44c3c01cf4a29/lib/cli/test/unit/Cardano/CLISpec.hs#L669-L702
- We have `ToText`/`FromText` roundtrips, and goldens for many special cases for `DerivationPath` and `DerivationIndex` in `CLISpec`
- Existing property `"scheme == mapKey (fromHex . toHex) scheme"` has been extended to confirm that schemes derive the same child keys when round-tripped.

**Comment by KtorZ** [comment]
> We may (?) support soft derivation.

We must, on relevant paths.

**Comment by Anviking** [comment]
@KtorZ 

How will we know whether to use DerivationScheme1 or DerivationScheme2?

It seems Byron / Random keys are using derivation scheme 1, but Icarus (and Shelley) is using scheme 2.

Do we have to take a `--type KEY-TYPE` cli option?

https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/src/Cardano/Wallet/Primitive/AddressDerivation/Icarus.hs#L325

https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/src/Cardano/Wallet/Primitive/AddressDerivation/Byron.hs#L326

**Comment by KtorZ** [comment]
> It seems Byron / Random keys are using derivation scheme 1, but Icarus (and Shelley) is using scheme 2.

Yes.

> Do we have to take a --type KEY-TYPE cli option?

No, rather a `--byron` flag, if present, use derivation scheme 1, if not, use derivation scheme 2.

**Comment by piotr-iohk** [comment]
lgtm.
