### ISSUE TITLE
Prepare new endpoint for hardware wallet restoring

### ISSUE THREAD

**Issue by paweljakubas** [cardano-foundation/cardano-wallet#1354]
# Context

As a cardano-wallet API client,
I want to be able to restore a sequential wallet from an account public key 
so that I can use cardano-wallet to keep track of my wallet 
And I can keep my private keys in another place (e.g. a hardware device)

AC

Given I have a hardware wallet, 
And I export my public key,
Then I can restore to Cardano Wallet 
with public key from hardware wallet.

# Decision

We add POST endpoint to service that which accepts `public account key` and `wallet name`. 

# Acceptance Criteria

1. Endpoint with needed errors are added.
2. TypesSpec unit testing is updated
3. Swagger is updated

---

# Development 

# QA 

New type `WalletOrAccountPostData` was added. What is important in `swagger.yaml` it uses 3.0 feature `oneOf` and it would be worth double checking if either `AccountPostData` and `WalletPostData` is displayed as an alternative in POST `wallets`. Moreover, tests in `Api.TypesSpec` where added to check several things

**Comment by piotr-iohk** [comment]
lgtm and closing. (Adding some tests in https://github.com/input-output-hk/cardano-wallet/pull/1400, but will keep #1355 in QA for that)
