### ISSUE TITLE
Weird log line regarding delegation status

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1376]
# Context
 
 

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      |  |
| Platform     | All           |
| Installation | Source             |

# Steps to Reproduce

1. Execute:   STAKE_POOLS_JOIN/QUIT - Checking delegation expectations
2. Observe logs

## Expected behavior

A clear and concise log line that recap the wallet metadata

## Actual behavior
 

```
[cardano-wallet.wallet-engine:Info:1032] [2020-02-25 22:40:25.47 UTC] a0ced84f: Faucet Wallet, created at 2020-02-25 22:39:56.579497076 UTC, current wallet delegation: delegating to 345ccb86, awaiting 5293674 which is expected to happen at epoch number not delegating
```

---

# Resolution 

---

# QA

**Comment by piotr-iohk** [comment]
TBH the log now is not very informative and quite confusing...

Ok, clear when delegating or not delegating without any `next` delegations:
```
My Test Wallet, created at 2020-03-09 10:25:39 UTC, delegating to ∅

or

My Test Wallet, created at 2020-03-09 10:26:31 UTC, delegating to 712dd028
```

But when awaiting `next` delegation, we get:

```
My Test Wallet, created at 2020-03-09 10:26:31 UTC, delegating to 712dd028 → 1377409
```
`1377409` is actually an epoch number, and there is no info about where are we going to delegate next (or maybe if we are going to quit)

For instance with two `next` we have:

```
My Test Wallet, created at 2020-03-09 10:26:31 UTC, delegating to 712dd028 → 1377409 → 1377410
```

I think it would be more informative and useful in case, for instance, debugging an issue if we had information about both, epoch ID and stake pool ID. E.g.:

```
My Test Wallet, created at 2020-03-09 10:26:31 UTC, delegating to 712dd028 → delegating to: 712dd028, in epoch: 1377409 → delegating to: ∅, in epoch: 1377410
``` 

@paweljakubas what do you think?

**Comment by paweljakubas** [comment]
@piotr-iohk you are right, I have made a mistake. I will produce correcting PR in several minutes

**Comment by piotr-iohk** [comment]
lgtm!
Log line now reads:
```
My Test Wallet, created at 2020-03-09 12:15:46 UTC, delegating to ∅ → 712dd028 (in epoch: 1377707) → 345ccb86 (in epoch: 1377708)
```
