### ISSUE TITLE
Reflect jormungandr API status for v2/network/information endpoint

### ISSUE THREAD

**Issue by rdlrt** [cardano-foundation/cardano-wallet#1377]
cardano-wallet-jormungandr currently does not make use of the status of jormungandr API (eg: message returned as "Bootstrapping" when bootstrapping hasnt finished) and waits before bootstrap completes before responding to v2/network/information endpoint.

This in effect causes a bad UX for end users using Daedalus, as Daedalus is not able to show an accurate response (causing users to think there is a network issue and needs a restart).

This issue maybe a blocker for input-output-hk/daedalus#1858

**Comment by KtorZ** [comment]
Moved to a separate issue tracker where new product requirements are kept :+1:
