### ISSUE TITLE
Crash on MacOS (< 10.12) with 'lazy symbol binding failed: Symbol not found: _clock_gettime' 

### ISSUE THREAD

**Issue by rdlrt** [cardano-foundation/cardano-wallet#1378]
# Context
 
The latest update of cardano-wallet-jormungandr that ships with Daedalus Rewards 2.2.0 does not work anymore on Mac OS X 10.11.6 (and as per error, it expects user machines to be using atleast 10.12)

| Information  | lazy symbol binding failed: Symbol not found: _clock_gettime |
| ---          | ---                                                   |
| Version      | 2020.2.17                      |
| Platform     | Mac OS X (< 10.12)        |
| Installation | Daedalus Rewards v1/version from github            |

# Steps to Reproduce

1. Download and extract [cardano-wallet](https://github.com/input-output-hk/cardano-wallet/releases/download/v2020-02-17/cardano-wallet-jormungandr-macos64-v2020-02-17.tar.gz) or use Daedalus ITN 2.2.0 (latter used for extract below).
2. Launch cardano-wallet[-jormungandr / Daedalus
3. After jormungandr's step to load bootstrap from storage completes, it would fail with an error similar to below:
```
[35m[cardano-wallet.daedalus-ipc:Notice:19] [0m [2020-02-25 22:31:43.66 UTC] Daedalus IPC finished for this reason: <file descriptor: 3>: hGetLine: end of file
[35m[cardano-wallet.network:Notice:22] [0m [2020-02-25 22:31:43.73 UTC] [jormungandr.426] Terminating child process
[cardano-wallet:Debug:4] [2020-02-25 22:31:43.73 UTC] Logging shutdown.
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Applications/Daedalus - Rewards v1.app/Contents/MacOS/cardano-wallet-jormungandr (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
```
This did not happen with previous releases.

**Comment by KtorZ** [comment]
Thanks for reporting this. We do not support OSX older than 10.12.

More details on system requirements here: https://iohk.zendesk.com/hc/en-us/articles/360010496553-Daedalus-System-Requirements.
