### ISSUE TITLE
Add continuous integration to `cardano-coin-selection` library.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#1379]
# Context

As part of the work to create a separate [**coin selection and fee balancing library**](https://github.com/input-output-hk/cardano-wallet/milestone/58), we'll need a way to automatically test new code that is introduced.

# Decision

Add continuous integration support to the [`cardano-coin-selection`](https://github.com/input-output-hk/cardano-coin-selection) library.

# Acceptance Criteria

- [x] The [`cardano-coin-selection`](https://github.com/input-output-hk/cardano-coin-selection) library _must_ have CI support.
- [x] The CI system _must_ detect and report:
    - [x] compilation failures
    - [x] test failures
    - [x] lint failures (`hlint`)
    - [x] style failures (`stylish-haskell`)
- [x] The CI system _must_ run for every pull request.
- [x] The CI system _must_ run for every merge into master.
- [x] The status of the latest master build _should_ be visible on the home page.

# Development

- [x] Add continuous integration support based on the script used for the [bech32](https://github.com/input-output-hk/bech32) library.
- [x] Add a badge to the home page showing the status of the latest build.

# QA 

Try to cause the CI system to fail, by pushing a branch with the following types of failure:
- [x] Failure to compile:
            https://travis-ci.org/input-output-hk/cardano-coin-selection/builds/657112216
- [x] Failure of the lint check:
            https://travis-ci.org/input-output-hk/cardano-coin-selection/builds/657110157
- [x] Failure of the style check:
            https://travis-ci.org/input-output-hk/cardano-coin-selection/builds/657114386
- [x] Failure of the test suite:
            https://travis-ci.org/input-output-hk/cardano-coin-selection/builds/657115878

**Comment by paweljakubas** [comment]
would be good to have it in such a form (eg., using repo name variables propagated throughout the code ) that it is very quick to reuse it in other repositories we are going to spawn

**Comment by jonathanknowles** [comment]
@paweljakubas wrote:

> would be good to have it in such a form (eg., using repo name variables propagated throughout the code ) that it is very quick to reuse it in other repositories we are going to spawn

Good point!

The CI code is fortunately _very_ simple, for the moment. It doesn't even mention the library name. See:

https://github.com/input-output-hk/cardano-coin-selection/blob/master/.travis.yml

**Comment by jonathanknowles** [comment]
Hi @piotr-iohk!

I've just run a few tests on the CI system, just to check that it does fail as expected. According to my tests, it correctly rejects the following kinds of failure:

- [x] Failure to compile:
        https://travis-ci.org/input-output-hk/cardano-coin-selection/builds/657112216
- [x] Failure of the lint check:
        https://travis-ci.org/input-output-hk/cardano-coin-selection/builds/657110157
- [x] Failure of the style check:
        https://travis-ci.org/input-output-hk/cardano-coin-selection/builds/657114386
- [x] Failure of the test suite:
        https://travis-ci.org/input-output-hk/cardano-coin-selection/builds/657115878

Would you be okay with me closing this issue?

**Comment by piotr-iohk** [comment]
@jonathanknowles - OK for the CI :) One question though:

> Add code coverage based on the script used for the bech32 library.

Is there a code coverage set up? can it the seen somewhere? (a badge for CC would be handy too)

**Comment by jonathanknowles** [comment]
> @jonathanknowles - OK for the CI :) One question though:
> 
> > Add code coverage based on the script used for the bech32 library.
> 
> Is there a code coverage set up? can it the seen somewhere? (a badge for CC would be handy too)

There's a separate issue for that here: https://github.com/input-output-hk/cardano-wallet/issues/1390

**Comment by piotr-iohk** [comment]
Ok, thx. The point _Add code coverage based on the script used for the bech32 library._ is part of the **Developement** section, hence my question. Closing then!

**Comment by jonathanknowles** [comment]
> Ok, thx. The point _Add code coverage based on the script used for the bech32 library._ is part of the **Developement** section, hence my question. Closing then!

Ah, that was a typo! I've corrected it to read:
> Add continuous integration support based on the script used for the bech32 library.
