### ISSUE TITLE
Reorganize module structure of `cardano-coin-selection` repository.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#1380]
# Context

As part of the work to create a separate [**coin selection and fee balancing library**](https://github.com/input-output-hk/cardano-wallet/milestone/58), we created a [repository](https://github.com/input-output-hk/cardano-coin-selection) based on minimal changes to the existing [`cardano-wallet`](https://github.com/input-output-hk/cardano-wallet) library.

# Decision

Simplify the module hierarchy in [`cardano-coin-selection`](https://github.com/input-output-hk/cardano-coin-selection), so that:

- [x] Functions and types that are only used by tests are moved into the test suite.
- [x] Functions and types that are located in "general-purpose" modules are moved into dedicated modules, related to their purpose.

# Acceptance Criteria

- [x] There should be no functions or types defined within `src` that are used only for testing.

# Development 

Move the following modules:
- [x] `Cardano.Unsafe` → `Test.Unsafe`.
- [x] `Data.Vector.Shuffle` → `Test.Vector.Shuffle`.
- [x] `Data.Vector.ShuffleSpec` → `Test.Vector.ShuffleSpec`.

# QA

- [x] Verify that there are no functions or types defined within `src` that are used only for testing.

**Comment by piotr-iohk** [comment]
lgtm.
