### ISSUE TITLE
Translate integration tests for active/next delegation into unit tests.

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#1386]
# Context

When reviewing and testing https://github.com/input-output-hk/cardano-wallet/issues/1342 we have created 12 integration tests (tagged `STAKE_POOL_NEXT`) that fairly comprehensively test the requirement. They have been quite long to execute adding ~9 minutes of execution to the overal integration test suite exec time and as a result made CI to timeout.

The idea here is to translate all or of some of them into unit tests to cut on test execution time and still have reliable tests.

There is an open PR with the integration tests -> https://github.com/input-output-hk/cardano-wallet/pull/1374. It can be used to translate the tests.

# Decision

Translate `STAKE_POOL_NEXT` tests from https://github.com/input-output-hk/cardano-wallet/pull/1374 into unit tests.

# Acceptance Criteria

---

# Development 

https://github.com/input-output-hk/cardano-wallet/pull/1392

# QA 

Unit tests and properties added which let us get rid of 2/3 of lengthy integration tests saving ~6min of CI execution. See also description: https://github.com/input-output-hk/cardano-wallet/pull/1392

**Comment by KtorZ** [comment]
@piotr-iohk @paweljakubas I've factored out the logic responsible for controlling the delegation transitions as `guardJoin` and `guardQuit`. 

From these two pure functions, we can now easily tests various delegation scenarios given some initial `WalletDelegation` state, and control that the outcome is as expected. I didn't think much through it but I believe there also exists some nice properties to try out. 

See: https://github.com/input-output-hk/cardano-wallet/commit/718f931ef53846a325b816a09169adb927b987be on `KtorZ/1386/unit-tests-delegation-transitions`. Feel free to add anything you want on this branch :+1:
