### ISSUE TITLE
Document process used to extract `cardano-coin-selection` repository.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#1391]
# Context

As part of the work to create a separate [**coin selection and fee balancing library**](https://github.com/input-output-hk/cardano-wallet/milestone/58), we created [a repository](https://github.com/input-output-hk/cardano-coin-selection) for this library from a clone of the [`cardano-wallet`](https://github.com/input-output-hk/cardano-wallet/) library.

When creating this clone, we **filtered** the commit history so that only commits relevant to coin selection and fee balancing were retained. However, this process was non-trivial, as the internal structure of `cardano-wallet` has been changed many times during its history. A naive repository extraction would have resulted in history being curtailed for files that have content from multiple ancestor files at different file locations.

Given that we'll need to extract further libraries in the future, it would be beneficial to document the process we used for extracting [`cardano-coin-selection`](https://github.com/input-output-hk/cardano-coin-selection/).

# Decision

Document the process we used for extracting [`cardano-coin-selection`](https://github.com/input-output-hk/cardano-coin-selection/), so that we have a simple set of steps to following when extracting further libraries.

# Acceptance Criteria

- [x] There _must_ be a guide that explains the process of extracting a new repository from an existing one.
- [x] The guide _must_ explain how to retain the full history of all files that are included in the extracted repository.

# QA 

- [ ] Take a clone of the [`cardano-wallet`](https://github.com/input-output-hk/cardano-wallet/) repository, delete an arbitrary subset of files, and then follow the steps in the guide to make a new repository based on the remaining subset of files. Confirm that the extraction has worked, with full history preserved for the subset of files included.

**Comment by piotr-iohk** [comment]
@jonathanknowles, I wonder if better place for this type of document would be here -> https://github.com/input-output-hk/adrestia/wiki#engineering-practices

**Comment by piotr-iohk** [comment]
Linked the article on wiki -> https://github.com/input-output-hk/adrestia/wiki.
LGTM!

**Comment by jonathanknowles** [comment]
> @jonathanknowles, I wonder if better place for this type of document would be here -> https://github.com/input-output-hk/adrestia/wiki#engineering-practices

After a brief internal discussion, we came to the conclusion that we would like to:

1. Keep the [existing article](https://github.com/input-output-hk/cardano-coin-selection/blob/f61417d0a24bb7c6a1ac85d792e07261e203f8a8/information/repository-creation-process.md) within [`cardano-coin-selection`](https://github.com/input-output-hk/cardano-coin-selection) to serve as a **historical record** of how we extracted that repository from `cardano-wallet`.

2. Create a link from the [Adrestia engineering wiki](https://github.com/input-output-hk/adrestia/wikii#engineering-practices) to the above article. If in future we need to create a **general process** that _deviates_ from the process we used to extract [`cardano-coin-selection`](https://github.com/input-output-hk/cardano-coin-selection), we can update the wiki with the updated process.
