### ISSUE TITLE
Extend the Cardano.Mnemonic to support recovery passphrase

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#14]
# Context

The way the master key got generated from a mnemonic sentence has changed between the legacy random address scheme, and the new sequential scheme on Cardano. We do now have the possibility to add an extra `recovery passphrase` during the seed / master key generation which adds an extra protection on the mnemonic (having the mnemonics isn't enough, one would also need to know the recovery passphrase). 

This is supported by `cardano-crypto` through the `generateNew` function as shown here:

https://github.com/input-output-hk/cardano-crypto/blob/3c5db489c71a4d70ee43f5f9b979fcde3c797f2a/src/Cardano/Crypto/Wallet.hs#L124-L129

# Decision

We want to extend our `Cardano.Mnemonic` module to support having a recovery passphrase that may be set by a user via the API.

## Questions

1. What relevance has this to the `Cardano.Mnemonic` module? I thought that the recovery passphrase would be only used when generating the root private key.
2. Will a "spending password" still be used to encrypt the root private key?
3. Will the spending password and recovery passphrase be the same?

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #?       | `master`  |

# QA

**Comment by KtorZ** [comment]
@rvl I've updated the context & decision. Estimates are still to be done in team :+1:

**Comment by KtorZ** [comment]
Some work started as part of #46 (see: https://github.com/input-output-hk/cardano-wallet/pull/46/files#diff-d3f54da283c61e7577ea1c27c7627e7aR218)

**Comment by KtorZ** [comment]
Actually now obsolete. The root key generation is done in the AddressDerivation module and do support having a mnemonic passphrase associated. We do even have corresponding golden tests for that.
