### ISSUE TITLE
CLI support for NTP status

### ISSUE THREAD

**Issue by paweljakubas** [cardano-foundation/cardano-wallet#1427]
# Context

There is NTP status endpoint `network/clock` but missing CLI support

# Decision

Adding CLI support for NTP status
# Acceptance Criteria

---

# Development 

# QA

**Comment by piotr-iohk** [comment]
Updated CLI manual -> https://github.com/input-output-hk/cardano-wallet/wiki/Wallet-command-line-interface#network-clock

**Comment by piotr-iohk** [comment]
Closing :+1: 
 - updated CLI manual
 - somewhat related -> https://github.com/input-output-hk/cardano-wallet/pull/1438

Closing.
(@paweljakubas - pls don't forget to update QA section (for future tasks) ;) )
