### ISSUE TITLE
Define encoders & decoders to and from SQL types

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#143]
# Context

Once we've defined an SQL database schema for our wallet backend, we'll need a way to perform:

1. **Encoding**: the conversion of Haskell values into values that can be stored in the database.
2. **Decoding**: the conversion of database values back into Haskell values.

# Decision

When decoding certain values, such as the Wallet state, we may need to trust that the data held within the database is correct.

# Acceptance Criteria

1. Values subject to the encoding and decoding process **must** be able to survive round trips **without** loss or corruption of data.

# Development Plan

# PR

- #272 

# QA

**Comment by KtorZ** [comment]
Closing in favor or #154 
The initial task split was done "horizontally" which doesn't really suit well the development on this feature. In the end, it's much easier to implement a bit of the layer, the corresponding schemas and the corresponding DB queries and move on to the next bits of the layer and so forth.
