### ISSUE TITLE
Add endpoint and type scaffolding for byron wallet restoration from xpriv+passwd hash

### ISSUE THREAD

**Issue by paweljakubas** [cardano-foundation/cardano-wallet#1435]
# Context

I want Daedalus to be able to automatically restore my existing Byron wallets, 
So that I don't need to re-enter my recovery phrase 
And I can enjoy a smooth migration experience to Byron reboot.

# Decision

We are going to add separate endpoint that enables byron wallet restoration from XPrv

# Acceptance Criteria
1. Separate endpoint is added.
2. Swagger is extended.
3. Types servicing this endpoint are added, TypesSpec is extended accordingly, the change is propagated throughout the code

---

# Development 

# QA 

The below areas are worth checking:
1. Added a number of new types in Api.Types, which are checked in Api.TypesSpec.
2. Updated swagger.yaml

**Comment by piotr-iohk** [comment]
lgtm.
