### ISSUE TITLE
Implement the endpoint for byron restoration from XPrv

### ISSUE THREAD

**Issue by paweljakubas** [cardano-foundation/cardano-wallet#1436]
# Context

I want Daedalus to be able to automatically restore my existing Byron wallets, 
So that I don't need to re-enter my recovery phrase 
And I can enjoy a smooth migration experience to Byron reboot.

# Decision

We have scaffolding present after #1435 , no w we want implementation.

# Acceptance Criteria
1. Implementation of endpoint
2. Add illustrative test that this is correct.

---

# Development 

# QA 

several things were addressed here that should be double-checked and maybe needs further more extensive testing:
1. `swagger.yaml` was corrected in a sense that 64-byte constraint on passphrase hash was lifted. This is because **Scrypt encryption** can be realized with different parameters (for example number of bytes of content) and also salt length. Those factors contribute to different encrypted hash length as shown in golden tests in `AddressDerivationSpec`. What is interesting : using **different** Scrypt encryption parameters and salt combinations give rise to proper `passphraseCheck` and ability to send legal tx that is accepted by cardano-node. So lifting 64-byte restriction we are making our migration capabilities more flexible (in case in different versions of cardano-sl different Scrypt parameters were used).
2. A number of tests mentioned in point 1 were added to AddressDerivationSpec.
3. In integration testing with cardano-node we have demonstrated the following:
(a) we can restore wallet using new endpoint and balance is correct.
(b) we can restore wallet using proper root xprv and wrong encrypted hash and it is expected as recovery depends on root xprv
(c) when restoring with wrong encrypted hash  we can get proper balance but cannot send tx and we get nice error 403 
(d) when restoring wallet with root xprv and proper encrypted hash password we can send tx to cardano-node that is accommodated in block

**Comment by piotr-iohk** [comment]
lgtm, additional test for name update -> https://github.com/input-output-hk/cardano-wallet/pull/1497

Note: Also handy would be a test for updating pass of Xprv restored wallet to add (once pass update is available).
