### ISSUE TITLE
Finalize manipulation of wallet metadata

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#145]
# Context

Before we create a proper SQL DB Store, we'd like to finalize the wallet metadata.

In the our current `MVar` DB layer we're not storing `WalletMetadata`. We'd like to do that.

The current [`WalletId`](https://github.com/input-output-hk/cardano-wallet/blob/c8a276e8711e2683d475f5df2d0c984f0ec7c197/src/Cardano/Wallet/Primitive/Types.hs#L150-L151) is an [`UUID`](http://hackage.haskell.org/package/uuid-1.3.13/docs/Data-UUID.html).

We want the wallet id to be deterministic. We do not want to use (and expose) the root public key _directly_ for security reasons…

# Decision

…instead, compute the wallet id using a base16/hex-encoded hash (e.g. Blake2b 128) of root xpub. And — store `WalletMetadata` in the DB.

# Acceptance Criteria

1. [`WalletMetadata`](https://github.com/input-output-hk/cardano-wallet/blob/c8a276e8711e2683d475f5df2d0c984f0ec7c197/src/Cardano/Wallet/Primitive/Types.hs#L134-L145) _must_ be stored in the [`DBLayer`](https://github.com/input-output-hk/cardano-wallet/blob/c8a276e8711e2683d475f5df2d0c984f0ec7c197/src/Cardano/Wallet/DB.hs#L23-L39)
2. [`WalletId`](https://github.com/input-output-hk/cardano-wallet/blob/c8a276e8711e2683d475f5df2d0c984f0ec7c197/src/Cardano/Wallet/Primitive/Types.hs#L150-L151) _should_ be redefined as a hex-encoded `Blake2b 128`-hash of the root public key.

---

# Development Plan

- [x] Replace construction of the wallet id from UUID to an actual hash of the wallet root public key
- [x] Add a property test to verify that any two wallets with the same mnemonics ends up with the same wallet id
- [x] Make sure metadata are stored alongside the wallet state and can be retrieved

# PR

| Number   | Base      |
| ---      | ---       |
| #156      | `master`  |
| #158      | `master`  |

# QA 

- Wallet metadata are now correctly created in the wallet layer when creating a wallet
- UUID has been replaced with an hex-encoded hash of the root public key for the wallet id (this is reflected in the golden tests) and visible through the type of `WalletId` as well (cf [haddock](https://input-output-hk.github.io/cardano-wallet/haddock/cardano-wallet-2.0.0/Cardano-Wallet-Primitive-Types.html#t:WalletId)
- I've extended properties for the wallet layer as well to check that the wallet id generation is both deterministic and injective (cf: [Cardano.WalletSpec](https://github.com/input-output-hk/cardano-wallet/blob/master/test/unit/Cardano/WalletSpec.hs#L83-L88))
- Wallet Metadata are also now stored in the DB Layer (DB layer has been extended to cover for those cases, see [here](https://input-output-hk.github.io/cardano-wallet/haddock/cardano-wallet-2.0.0/Cardano-Wallet-DB.html#t:DBLayer) `putWalletMeta` and `readWalletMeta`) 
- Also added extra tests for the wallet metadata and actually, tx history too in [Cardano.Wallet.DB.MVarSpec](https://github.com/input-output-hk/cardano-wallet/blob/master/test/unit/Cardano/Wallet/DB/MVarSpec.hs#L92-L141)

**Comment by piotr-iohk** [comment]
lgtm :+1:
