### ISSUE TITLE
cardano-node: Wallet re-syncs from 0% after restarting cardano-wallet-byron

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#1453]
# Context
 
| Information  | -                                                     |
| ---          | ---                                                   |
| Version      |`2020.3.16 (git revision: 52d2cf591a534051c39366825fcfd723f3512e30)`|
| Platform     | Linux, All?         |
| Installation | From github           |

# Steps to Reproduce

1. start cardano-wallet on cardano-node:
```
cardano-wallet-byron serve --node-socket /home/piotr/wb/cardano-node/state-node-mainnet/node.socket --mainnet --database ./mainnet
```
2. Create a wallet and make it sync (not necessarily up to 100%)
```
curl  -vX POST http://localhost:8090/v2/byron-wallets \
  -H "Content-Type: application/json; charset=utf-8" \
  -d '{
"style" : "random",
"name": "Byron1",
"mnemonic_sentence": ["rotate", "machine", "travel", "safe", "expire", "leopard", "wink", "vault", "borrow", "digital", "wisdom", "harsh"],
"passphrase": "Secure Passphrase"
}' --http1.1  |  jq
```
3. Stop and start again `cardano-wallet-byron serve`
4. List wallets
```
curl  -vX GET http://localhost:8090/v2/byron-wallets   |  jq
```

## Expected behavior

Wallet continues to sync starting from the point it left before stopping cardano-wallet-byron.

## Actual behavior
 
Wallet syncs again from 0%.
In the log there is:
```
[cardano-wallet.wallet-engine:Info:20] [2020-03-18 11:14:14.27 UTC] df01a993: Rolled back to 0.0
[cardano-wallet.wallet-engine:Info:23] [2020-03-18 11:14:14.27 UTC] 10e1a38c: Rolled back to 0.0
```

---

# Resolution 

- Order of headers submitted for intersection matters ==> #1481

---

# QA

**Comment by piotr-iohk** [comment]
For this one perhaps we could have an integration test... :thinking:

**Comment by KtorZ** [comment]
We have one that is pending and that we run manually, which is restarting a worker but it doesn't necessarily control anything about the wallet state if I recall correctly.

**Comment by piotr-iohk** [comment]
There is one, but it is for Jormungandr's launch (https://github.com/input-output-hk/cardano-wallet/blob/master/lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/CLI/Launcher.hs#L188). I think we should have one for `serve` too.

**Comment by piotr-iohk** [comment]
I don't see behavior described in the ticket any longer (wallet does not sync from 0% again on restarting cardano-wallet), however I am seeing syncing from 0% in slightly different scenario -> https://github.com/input-output-hk/cardano-wallet/issues/1468#issuecomment-603898720

**Comment by KtorZ** [comment]
Yes, but #1468 is a whole different story here. I have something in preparation for this but this is NOT trivial, especially with EBB in Byron :(
