### ISSUE TITLE
Delegation fee estimation is 0 instead of 0.8 ADA

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#1457]
# Context
 
 

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | 2020.3.11 (git revision: 203184fa6a673bfcd1ef5b2181d02b352ef863c6) |
| Platform     | mac          |
| Installation | Daedalus Public installer 2020.2.17, modified with jorm 0.8.14 and recent wallet |

# Steps to Reproduce

1. Delegate in Daedalus
2. Observe fee estimation before confirming
3. Observe actual fee paid in the tx history

## Expected behavior

Estimation and actual fee paid _should_ match

## Actual behavior

Estimation is 0 ADA, actual fee is 0.8 ADA.
 
<img width="612" alt="Skärmavbild 2020-03-19 kl  12 52 50" src="https://user-images.githubusercontent.com/304423/77065217-2b1b7800-69e1-11ea-8c62-2723400c0e81.png">
<img width="1039" alt="Skärmavbild 2020-03-19 kl  12 53 03" src="https://user-images.githubusercontent.com/304423/77065229-32428600-69e1-11ea-9938-54a34f41f1c3.png">
---

# Resolution 

---

# QA

**Comment by KtorZ** [comment]
> Estimation and actual fee paid should match

This is actually incorrect. cf: 

https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/getDelegationFee

I think we discussed the idea of running many estimation at once and taking the average instead of doing it just once.. Yet, an estimation of 0 seems wrong, regardless of what the fees end up being.

**Comment by KtorZ** [comment]
Nikola confirmed it's a frontend issue. Although, I have opened a JIRA ticket to track the "averaged fee" story. ( https://jira.iohk.io/browse/ADP-283 )
