### ISSUE TITLE
cardano-node: Restarting cardano-node while the wallet is running breaks cardano-wallet

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#1468]
# Context
 
 

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | cardano-wallet-byron: `2020.3.16 (git revision: 87580b7feb7ea3506d0342a6bad6f69b6e640d9e)`, cardano-node: `1.8` |
| Platform     | Linux, probably all         |
| Installation | From source          |

# Steps to Reproduce

0. start cardano-node + wallet on testnet
```
$ nix-build -A scripts.testnet.node -o testnet.node.local && testnet.node.local
$ cardano-wallet-byron serve --node-socket ~/wb/cardano-node/state-node-testnet/node.socket --testnet /nix/store/7106qjwral616j6p5049m7hhi5ih0r33-testnet-genesis.json --database ./testnet
```
1. Create a wallet and wait for it to sync.
```
curl  -vX POST http://localhost:8090/v2/byron-wallets \
  -H "Content-Type: application/json; charset=utf-8" \
  -d '{
"style" : "random",
"name": "Byron1",
"mnemonic_sentence": ["rotate", "machine", "travel", "safe", "expire", "leopard", "wink", "vault", "borrow", "digital", "wisdom", "harsh"],
"passphrase": "Secure Passphrase"
}' --http1.1  |  jq
```
2. restart `cardano-node`

## Expected behavior
`cardano-wallet` should stay operational

## Actual behavior
 
 - wallet disapears (cannot be listed, getting wallet by ID returns `404`)
 - `GET network/information` returns `503` 
 - in the log there is:
```
[cardano-wallet.wallet-engine:Error:14] [2020-03-20 09:50:10.29 UTC] 57638bf1: Recoverable error following the chain: ExceptionInLinkedThread ThreadId 24 (MuxError {errorType = MuxBearerClosed, errorMsg = "<socket: 18> closed when reading data, waiting on next header True", errorStack = []})
[cardano-wallet.wallet-engine:Error:14] [2020-03-20 09:50:10.30 UTC] Worker has exited unexpectedly: ExceptionInLinkedThread ThreadId 36 (MuxError {errorType = MuxBearerClosed, errorMsg = "<socket: 19> closed when reading data, waiting on next header True", errorStack = []})
```

`cardano-wallet` seems to be OK after restarting though. Wallet is back, `network/information` is back too.

---

# Resolution 

- [x] Catch relevant exceptions in the network layer and handle them properly ==> #1485 

- [x] Revise error handling in the follow loop and make sure a new intersection is found when reconnecting with the node. ==> #1485 

---

# QA

**Comment by piotr-iohk** [comment]
Currently `2020.3.16 (git revision: acac18457f3bf7ad6dd811670994d00f5969c1cb)` I see the following behaviour:
 - start `cardano-node` and `cardano-wallet`
 - create a wallet and wait for it to sync
 - restart `cardano-node`

As a result a wallet is syncing again from 0%...
(Observed while retesting #1453)

**Comment by piotr-iohk** [comment]
Looks good.

One question @KtorZ. While cardano-node is down, triggering
```
curl  -vX GET http://localhost:8090/v2/network/information |  jq
```
takes 30seconds before it returns:

```
{
  "code": "network_unreachable",
  "message": "The node backend is unreachable at the moment. Trying again in a bit might work."
}
```
I suppose there is some sort of timeout? Just wondering if it is needed? (I remember that on Jormungandr it responded immediatelly in such a case)

**Comment by KtorZ** [comment]
Indeed, there's a 30s timeout for every message we send to the node; after this. On Jörmungandr, requests were going through HTTP, so in many scenarios, it was easy to know whether we could reach Jörmungandr's server or not. With cardano-node, messages are sent through a local socket, and, we wait for a response...

We do know however if we've lost the connection, but there's no particular logic at the moment to route messages differently if that's the case. This would induce some complexity which I am not sure is really worth in that case :/
