### ISSUE TITLE
Define SQL Schema representing relevant Haskell types

### ISSUE THREAD

**Issue by paweljakubas** [cardano-foundation/cardano-wallet#147]
# Context

SQL like db solution is decided to act as db backend for the wallet. 

# Decision

SQLite is chosen as SQL db solution. Hence, the schemas for all data to be stored has to be defined. Moreover, the corresponding tables has to be created, and checked that they can be inscribed correctly into the running db process (CREATE TABLE). 

# Acceptance Criteria

1 SQL schemas for all types 
 (a) Wallet
 (b) WalletMeta
 (c) Tx (pending)
 (d) The Tx History & corresponding tx meta
 (e) SlotId (network tip)
 (f) UTxO 
 (g) AddressPool
    to be stored must be defined within sql types
2. The corresponding from point 1 tables must be checked if they can be (CREATE TABLE) to the db and then (SELECTed) from db

---

# Development Plan

- [ ] I plan to create SQL schema using `persistent` lib for : Wallet, WalletMeta, Tx (pending), The Tx History & corresponding tx meta and test them  (Ante)
- [ ] I plan to create SQL schema using `persistent` for : SlotId (network tip), UTxO, AddressPool and test them
- [ ] I plan to create a module and write few obvious/dummy db selectors that query db
       - this module will consist update/delete/select and other interactions with db
- [ ] I plan to create a module and setup code for db migrations
       - this module will consist of future migrations plans and code to execute the migrations
       - would be nice if we could have a way to test migrations - but don't know much about this (Ante)
- [ ] I plan to try to create `esqualeto` version of the above and compare approaches (ask Matthias and rest of the team is this vialable)

(Pawel)
Proposed localization of schema : `Cardano.Wallet.DB.Schema`
# PR

| Number   | Base      |
| ---      | ---       |
| #227 | `master`  |
| #247 | |

# QA

**Comment by KtorZ** [comment]
@paweljakubas 
The schema for pending transaction and transaction history should actually be the same. This is still under some discussion with the formal spec team, but we might re-consider the way we approach pending transactions. In the end, pending transactions (from a data perspective) are nothing less than classic transactions. They have a special "status" at a given point in time but, with rollbacks, even some resolved and confirmed transactions might become pending.

**Comment by KtorZ** [comment]
Closing in favor or #154 
The initial task split was done "horizontally" which doesn't really suit well the development on this feature. In the end, it's much easier to implement a bit of the layer, the corresponding schemas and the corresponding DB queries and move on to the next bits of the layer and so forth.
