### ISSUE TITLE
Refactor cardano-cli to re-use commands for both Byron & Shelley endpoints

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1477]
# Context

Commands in cardano-cli currently "suffer" from two issues:

a) They require a type-level network discriminant which must be provided **at compile-time**. As a direct consequence, it is not yet possible to provide a single command-line that works with two different network discriminations.

b) They are hard-wired to call the "Shelley" endpoints of the wallet, which in the Byron setup, all returns "501 Not Implement". However, the underlying APIs are _mostly_ the same (except for wallet creation). 

# Decision

- Refactor the command-line setup to work with both Byron and Shelley endpoint
- Refactor the command-line setup to accept network discriminant to be set at runtime
- Keep cardano-wallet-jormungandr command-line unchanged, as much as possible

# Acceptance Criteria

1. cardano-wallet-byron _should_ offer mostly the same functionality as Jormungandr transactions and wallet commands. 

2. The creation of wallet _should_ however be different and adjusted for byron.

3. cardano-wallet-jormungandr _should_ remain unchanged, from a user-perspective.

---

# Development 

- Refactor command-line ==> #1478
- Implement address endpoints for Byron + address command-line ==> #1493 

# QA 

- Integration tests covering transaction manipulation via CLI --> https://github.com/input-output-hk/cardano-wallet/blob/master/lib/byron/test/integration/Test/Integration/Byron/Scenario/CLI/Transactions.hs
- Superficial manual tests done for address commands here: 

<details>
    <summary>cardano-wallet address create --help</summary>

```
Usage: cardano-wallet-byron address create [--port INT] [--address-index INDEX]
                                           WALLET_ID
  Create a new random address. Only available for random wallets. The address
  index is optional, give none to let the wallet generate a random one.

Available options:
  -h,--help                Show this help text
  --port INT               port used for serving the wallet API. (default: 8090)
  --address-index INDEX    A derivation index for the address
```
</details>

<details>
    <summary>cardano-wallet address list adc78398110d92af3132488546c6977f61dc0c7e</summary>

```
Ok.
[]
```
</details>

<details>
    <summary>cardano-wallet address create adc78398110d92af3132488546c6977f61dc0c7e</summary>

```
Please enter your passphrase: ****
passphrase is too short: expected at least 10 characters

Please enter your passphrase: ****************
The given encryption passphrase doesn't match the one I use to encrypt the root private key of the given wallet: adc78398110d92af3132488546c6977f61dc0c7e
```
</details>

<details>
    <summary>cardano-wallet address create adc78398110d92af3132488546c6977f61dc0c7e</summary>

```
Please enter your passphrase: **********
Ok.
{
    "state": "unused",
    "id": "2w1sdSJu3GVfmTYPMT4ohVs9wHidocUwSjpvaRpBQzBAQerk9fSycpkhvLJ7x2AZets69S7b8SdLD195CJmTmWxM4VWu1PKCbjM"
}
```
</details>

<details>
    <summary>cardano-wallet address list adc78398110d92af3132488546c6977f61dc0c7e</summary>

```
Ok.
[
    {
        "state": "unused",
        "id": "2w1sdSJu3GVfmTYPMT4ohVs9wHidocUwSjpvaRpBQzBAQerk9fSycpkhvLJ7x2AZets69S7b8SdLD195CJmTmWxM4VWu1PKCbjM"
    }
]
```
</details>

**Comment by piotr-iohk** [comment]
LGTM.
