### ISSUE TITLE
Byron wallet CRUD - update-name, update-spending password

### ISSUE THREAD

**Issue by paweljakubas** [cardano-foundation/cardano-wallet#1483]
# Context

Those functionalities are needed for Byron Reboot

# Decision

1. Update-name will be as it was done for Jormungandr
2. get utxo statistics will be as it was done for Jormungandr
3. Update spending password will need to take into consideration below requirements:
(a) no password -> valid password   LEGAL
(b) valid password -> valid password   LEGAL
(c) valid password -> no password  ILLEGAL
Moreover, restoration should be reviewed to accept either no password or current password.

# Acceptance Criteria

1. Byron Api supports update-name, get utxo statistics and update-spending password
2. Byron Api restoring accepts also no password
3. Byron Api of update-spending password supports transitions specified in Decision section

---

# Development 

# QA 

It would be worth checking the changes in : 
1. swagger.yaml
2. check integration tests introduced which can be run via
```
stack test --ta '-m "BYRON_UPDATE_NAME"' cardano-wallet-byron:cardano-node-integration
stack test --ta '-m "BYRON_UTXO"' cardano-wallet-byron:cardano-node-integration
```

**Comment by piotr-iohk** [comment]
lgtm.
