### ISSUE TITLE
Can't fetch pools registry

### ISSUE THREAD

**Issue by Fell-x27** [cardano-foundation/cardano-wallet#1489]
# Context
 
At my server I have a weird error. Just can't download pools registry.
I can download it manually by wget. But cardano-wallet gets an error

`[cardano-wallet.api-server:Warning:14393] [2020-03-26 20:47:19.46 UTC] [RequestId 27] 503 Service Unavailable in 5.149634288s
`

But when I test it on my local machine, everything is fine.

It worked on the server previously, but just accidentally stopped about a week ago. I didn't change anythng on the server and can't realize the reason of the problem. 

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      |8316bffdd05596e8830da9129f3a3907c6fba684 |
| Platform     | Linux x64  |
| Installation | From binaries |

# Steps to Reproduce

1. Try to fetch stake-pools list by CLI or REST

## Expected behavior

List is loading.
## Actual behavior
 
503 error

---

**Comment by Fell-x27** [comment]
It didnt wirk work for a week. It's working now. I don't know how.

**Comment by KtorZ** [comment]
see https://github.com/input-output-hk/cardano-wallet/issues/1442

**Comment by Fell-x27** [comment]
Yes, looks pretty similar.
