### ISSUE TITLE
Implement master key generation & public id calculation for Icarus sequential

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1502]
# Context

As a Daedalus developer,  
I want to be able to associate a mnemonic phrase to its corresponding wallet id,  
So that I can implement recurring mnemonic checks to make sure users haven't forgotten their mnemonic sentences.

# Decision

- Wallet id can be derived from a JavaScript library depending on their type (byron, icarus, ledger).

# Acceptance Criteria

- Wallet id can be derived from a JavaScript library depending on their type (byron, icarus, ledger).
- Wallet id generation is documented

---

# Development 

- https://github.com/input-output-hk/cardano-js/pull/29

# QA 

- Generation method documented as part of [Wallet Cryptography and Encoding](https://github.com/input-output-hk/cardano-wallet/wiki/Wallet-Cryptography-and-Encoding)

- Golden test cases generated using `cardano-wallet`: https://github.com/input-output-hk/cardano-js/blob/dc505f29fba0bbb7a055d184ac3e99c998047b34/src/hd/index.spec.ts#L24-L43

**Comment by piotr-iohk** [comment]
Same as here -> https://github.com/input-output-hk/cardano-wallet/issues/1501#issuecomment-606674042
