### ISSUE TITLE
Enable server-side TLS support & command-line options for TLS configuration

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1503]
# Context

There's a security concern with the way the communication between Daedalus and cardano-wallet current works on an end-user's machine. Since the connection happens on via TCP on localhost, any other process or application which happens to know the right port (which can be looked up pretty easily) can make arbitrary requests to cardano-wallet. While there's no risk for the user's assets, it is still a very plausible source of denial of service, as well as potential hard-to-debug behaviors. 

# Decision

While an API token over Basic authentication would be sufficient to mitigate the problem (we aren't much concerned about local process eaves-dropping on the local TCP request at this stage), we are still going for the TLS sledgehammer, mainly because we are lacking time to implement anything simpler. TLS is a drop-in solution for Deadalus at the moment and still fairly simple to support server-side. 

# Acceptance Criteria

1. cardano-wallet server must support requiring connections established through TLS 1.
2, When enabled, the server must require a valid client certificate with connections (with KeyUsagePurpose = client)
3. When enabled, the server should not try to validate the host name of a particular client
4. New command-line options on the cardano-wallet-byron serve command should be added to provide:
    a. --tls-ca-cert, a path to a PEM-encoded (base64 DER with header & footer) certificate authority
    b. --tls-sv-cert, a path to a PEM-encoded (base64 DER with header & footer) certificate authority
    c. --tls-sv-key, a path to PEM-encoded RSA private key which signed the server certificate.
    If one option is provided, the others must be provided. If none are provided, the server will start an "insecure" connection on localhost as normal.

---

# Development 

- See #1504 

# QA 

- Added [unit tests](https://github.com/input-output-hk/cardano-wallet/blob/f3afbcb933c024027deaa47c4f640a1fbe3d7ac8/lib/core/test/unit/Cardano/Wallet/Api/Server/TlsSpec.hs#L73-L132) covering the server setup when a TLS configuration is provided:
        - Respond to authenticated client if TLS is enabled
        - Deny client with wrong certificate if TLS is enabled
        - Properly deny HTTP connection if TLS is enabled

- New command-line options only tested manually + sanity cURL request

**Comment by piotr-iohk** [comment]
When the server uses TLS, then command line is not available:
```
$ cardano-wallet-byron wallet list
This server only accepts secure HTTPS connections.
```

**Comment by KtorZ** [comment]
Indeed. That's actually a feature. Otherwise, we would need to provide a --ca-cert and --client-cert and --client-key to every command interacting with the API. 

The use case for TLS is really for Daedalus or client applications on a end-user desktop. The command-line is meant for debugging and local use in controlled environments where there's no reason to start the server behind TLS.

**Comment by piotr-iohk** [comment]
right, just saying... :) Anyway, LGTM.
