### ISSUE TITLE
Cannot force resync wallet and cardano-node crash as a result

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#1505]
# Context
 
Observed on testnet and staging-shelley and mainnet...

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | cardano-wallet: `2020.3.16 (git revision: fff00d48db58bc73f3b927955944fbeb0f23d23f)`, cardano-node 1.9.1 |
| Platform     | All        |
| Installation | from source           |

# Steps to Reproduce

0. start cardano-node + wallet on testnet
 - `nix-build -A scripts.testnet.node -o testnet.node.local && testnet.node.local`
 -  `cardano-wallet-byron serve --node-socket ~/wb/cardano-node/state-node-testnet/node.socket --testnet /nix/store/7106qjwral616j6p5049m7hhi5ih0r33-testnet-genesis.json --database ./testnet`

1. Restore a wallet.
```
curl  -vX POST http://localhost:8090/v2/byron-wallets \
  -H "Content-Type: application/json; charset=utf-8" \
  -d '{
"style": "random",
"name": "Byron",
"mnemonic_sentence": ["recycle","august","horse","awesome","shuffle","agent","almost","cheap","fury","speak","duty","enemy"],
"passphrase": "Secure Passphrase"
}' --http1.1  |  jq
```
2. Force resync wallet:
```
curl  -vX PUT http://localhost:8090/v2/byron-wallets/d3358ac0fc699784af021710e7aba2a3e31fbbd1/tip \
  -H "Content-Type: application/json; charset=utf-8" \
  -d '{
"slot_number": 0,
"epoch_number": 0
}' --http1.1  |  jq
```

## Expected behavior

Force resync is successful

## Actual behavior
 
Wallet is not resyncing. (state is 0% syncing)

Rolling messages cardano-wallet log:
```
[cardano-wallet.wallet-engine:Error:17] [2020-03-30 10:34:08.44 UTC] c29a2bfb: Unexpected error following the chain: user error (restoreBlocks: given chain isn't a valid continuation. Wallet is at: 8f860283-[0.0#0] but the given chain continues starting from: 8f860283-[0.0#0])
[cardano-wallet.network:Debug:4492] [2020-03-30 10:34:08.44 UTC] Couldn't connect to node (x1). Retrying in a bit...
[cardano-wallet.network:Info:4492] [2020-03-30 10:34:08.44 UTC] Mux ConnectionId {localAddress = LocalAddress {getFilePath = ""}, remoteAddress = LocalAddress {getFilePath = "state-node-testnet/node.socket"}} Send MsgProposeVersions (fromList [(NodeToClientV_1,TInt 1097911063)])
[cardano-wallet.network:Info:17] [2020-03-30 10:34:08.44 UTC] Looking for an intersection with the node's local chain with: 8f860283-[0.0#0]
[cardano-wallet.network:Info:4492] [2020-03-30 10:34:08.44 UTC] Mux ConnectionId {localAddress = LocalAddress {getFilePath = ""}, remoteAddress = LocalAddress {getFilePath = "state-node-testnet/node.socket"}} Recv MsgAcceptVersion NodeToClientV_1 (TInt 1097911063)
[cardano-wallet.network:Info:17] [2020-03-30 10:34:08.44 UTC] Intersection found: 96fceff9


```
After few seconds cardano-node is crashing with:
```
[piotr-la:cardano.node.LocalErrorPolicy:Error:55] [2020-03-30 10:34:37.91 UTC] {"event":"ErrorPolicyAcceptException Network.Socket.accept: resource exhausted (Too many open files)","kind":"ErrorPolicyTrace","address":"LocalAddress {getFilePath = \"state-node-testnet/node.socket\"}"}
[piotr-la:cardano.node.BlockFetchDecision:Info:47] [2020-03-30 10:34:38.98 UTC] {"peer":"ConnectionId {localAddress = 192.168.1.100:33659, remoteAddress = 3.125.94.58:3001}","kind":"FetchDecision","decision":{"length":"1","kind":"FetchDecision results"}}
[piotr-la:cardano.node.BlockFetchDecision:Info:47] [2020-03-30 10:34:39.07 UTC] {"peer":"ConnectionId {localAddress = 192.168.1.100:33659, remoteAddress = 3.125.94.58:3001}","kind":"FetchDecision","decision":{"kind":"FetchDecision declined","declined":"FetchDeclineAlreadyFetched"}}
[piotr-la:cardano.node.ChainDB:Info:37] [2020-03-30 10:34:39.07 UTC] {"event":{"kind":"TraceAddBlockEvent.AddBlockValidation.ValidCandidate","block":"38e5081@1078243"},"kind":"TraceEvent","tip":"0a6977f@1078242"}
[piotr-la:cardano.node.ChainDB:Notice:37] [2020-03-30 10:34:39.07 UTC] {"event":{"kind":"TraceAddBlockEvent.AddedToCurrentChain","newtip":"38e5081@1078243"},"kind":"TraceEvent","tip":"0a6977f@1078242"}
[piotr-la:cardano.node.BlockFetchDecision:Info:47] [2020-03-30 10:34:39.07 UTC] {"peer":"ConnectionId {localAddress = 192.168.1.100:33659, remoteAddress = 3.125.94.58:3001}","kind":"FetchDecision","decision":{"kind":"FetchDecision declined","declined":"FetchDeclineChainNotPlausible"}}
[piotr-la:cardano.node.LocalErrorPolicy:Error:54] [2020-03-30 10:34:39.07 UTC] {"event":"ErrorPolicyLocalNodeError (ApplicationExceptionTrace (UserError ClosedDBError))","kind":"ErrorPolicyTrace","address":"LocalAddress {getFilePath = \"\"}"}
cardano-node: ExceptionInLinkedThread "ThreadId 47" (UserError ClosedDBError)
[piotr-la:cardano.node.ChainDB:Info:5] [2020-03-30 10:34:39.08 UTC] {"event":{"immtip":{"kind":"Tip","tip":"810adb4@1076082"},"kind":"TraceOpenEvent.ClosedDB","tip":{"kind":"Tip","tip":"38e5081@1078243"}},"kind":"TraceEvent","tip":"38e5081@1078243"}


```

---

# Resolution 

input-output-hk/ouroboros-network#1559 - make sure we convert our tip (`BlockHeader`) correctly to the node's tip type (`Tip ByronBlock`). 

# QA

- Added a roundtrip test that fails without the fix.
- Fixed `toPoint`. Only return `Origin` when the wallet _actually_ is at genesis.

Seeing surprising behaviour when using the endpoint. Opened follow-up bug: input-output-hk/ouroboros-network#1567

**Comment by KtorZ** [comment]
The ... node crashes?

**Comment by piotr-iohk** [comment]
> The ... node crashes?

Yes.

**Comment by mrBliss** [comment]
Somebody showed a more complete log from 1.9.2 today, which contains:
```
[2020-03-31 10:47:35.24 UTC] {"event":"ErrorPolicyLocalNodeError (ApplicationExceptionTrace (VolDbFailure (FileSystemError (FsError {fsErrorType = FsTooManyOpenFiles, ...
```
So it is running out of file descriptors, which matches what you're seeing in the other trace:
```
[piotr-la:cardano.node.LocalErrorPolicy:Error:55] [2020-03-30 10:34:37.91 UTC] {"event":"ErrorPolicyAcceptException Network.Socket.accept: resource exhausted (Too many open files)","kind":"ErrorPolicyTrace","address":"LocalAddress {getFilePath = \"state-node-testnet/node.socket\"}"}
```
So there's not much else the node can do and it is thus doing what we expect it to do. Either raise the open file descriptor limit for the node process or limit the number of clients (https://github.com/input-output-hk/ouroboros-network/pull/1831) so that you don't run out of file descriptors. (Note that we plan to improve this in the future with https://github.com/input-output-hk/ouroboros-consensus/issues/736).

**Comment by piotr-iohk** [comment]
> Either raise the open file descriptor limit 

That won't help, it'll only make node, or wallet crash later. 

The issues is when doing force-resync, it does not progress with syncing (infinitelly shows 0% syncing) and eventually either node or wallet crashes, because it reaches max files open.

cc: @KtorZ

**Comment by KtorZ** [comment]
I have an _idea_ that may help: 

Instead of re-creating a _new_ connection every time we try to reconnect we could try to get a connection from a connection pool. There are many existing libraries which will make this quite easy to implement and, by having a limited pool size, we can somewhat limit the number of total connections that get created. As a downside, this would also limit the number of wallet that run in parallel but even a pool with max 50 connections may improve things greatly and not really impact normal usage of the wallet.

**Comment by Anviking** [comment]
I suspect the open file limit is only an indirect symptom from us crashing and retrying in an infinite loop.

`8f860283-[0.0#0] but the given chain continues starting from: 8f860283-[0.0#0]`

comes from https://github.com/input-output-hk/cardano-wallet/blob/cff0e391985887f60b9076aace207674bef6a2b4/lib/core/src/Cardano/Wallet.hs#L726-L731

Seems alarming to me. The `8f860283-[0.0#0]` (which btw is not genesis!) is the current tip and should not be included in the next-block-results.

GenesisHash: 96fceff972c2c06bd3bb5243c39215333be6d56aaf4823073dca31afe5038471

<img width="527" alt="Skärmavbild 2020-04-08 kl  13 09 21" src="https://user-images.githubusercontent.com/304423/78777777-739fd300-799a-11ea-9a4a-e1f0a8978f59.png">

_looking for an off-by-one error_

**Comment by Anviking** [comment]
https://github.com/input-output-hk/cardano-wallet/blob/cff0e391985887f60b9076aace207674bef6a2b4/lib/byron/src/Cardano/Wallet/Byron/Compatibility.hs#L253

So `SlotId 0 0` should not actually be genesis. Might be it.

**Comment by KtorZ** [comment]
Yes.. I assume that's the EBB following genesis...

**Comment by KtorZ** [comment]
We do nothing special with EBB, they are simply overwritten by the next block coming after (since most of our foreign keys in the database uses also the slot id as the reference). 

The problem is that for genesis, we now basically have 3 blocks at the same slot... ? 

- genesis
- the first EBB
- The first block

**Comment by piotr-iohk** [comment]
lgtm
