### ISSUE TITLE
Add latency benchmarking for byron (integration-like self-node)

### ISSUE THREAD

**Issue by paweljakubas** [cardano-foundation/cardano-wallet#1527]
# Context

We had latency benchmarking for Jormungandr. It would be worth to have the one for Byron

# Decision

Add latency benchmark in `lib/byron/bench`

# Acceptance Criteria

1. We have an interesting situation benchmarking in the context of self-node.
2. The benchmark can be invoked by `stack bench cardano-wallet-byron:latency`
3. The report is well-formatted and easy to read
4. Benchmark is run periodically on nightly build

---

# Development 

# QA 

Please use `stack bench cardano-wallet-byron:latency` to verify

**Comment by piotr-iohk** [comment]
LGTM!

While looking at this (and all benchmarks) I thought that it would be great to have most of those results (like latency or restore) presented in the form of a graph that would show how they change overtime... currently it is quite difficult to spot whenever there is a potential deterioration or improvement...
