### ISSUE TITLE
Icarus wallets are created with Mainnet addresses even if the server is in 'Testnet' mode

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#1535]
# Context
... what the heck...

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | `2020.4.1 (git revision: df83d3f54b96ebe9f516a7a216c0d1cc9f169aa0)` cardano-node 1.9.3 |
| Platform     | linux, all?          |
| Installation | from release          |

# Steps to Reproduce

0. start cardano-node + wallet on testnet
 - `nix-build -A scripts.testnet.node -o testnet.node.local && testnet.node.local`
 -  `cardano-wallet-byron serve --node-socket ~/wb/cardano-node/state-node-testnet/node.socket --testnet /nix/store/7106qjwral616j6p5049m7hhi5ih0r33-testnet-genesis.json --database ./testnet`

1. Restore a wallet.
```
curl  -vX POST http://localhost:8090/v2/byron-wallets \
  -H "Content-Type: application/json; charset=utf-8" \
  -d '{
"style": "icarus",
"name": "Icarus",
"mnemonic_sentence": ["merry", "output", "wrestle", "second", "jealous", "electric", "network", "course", "gravity", "valid", "walnut", "trumpet", "sniff", "behind", "switch"],
"passphrase": "Secure Passphrase"
}' --http1.1  |  jq
```
2. Verify addresses generated for that wallet
```
curl  -vX GET http://localhost:8090/v2/byron-wallets/480fcd62295228616a6b0bdf5b818f40beb688c3/addresses |  jq

```
they are like:
```
Ae2tdPwUPEZMhXT3psnE9aaDJVhFFzE6NHjKyeU1xCN2YFmruAJtpK3BCTk
Ae2tdPwUPEZD7cMRTsUcQsZoa1LnSkYtRGLrBc7yQGw4GJWF22qjhh7s4xG
Ae2tdPwUPEZF5LBV9LPE5VMPLh5WMnQnqqT2noewK7Mp6g9bUPNNf1TifyG
Ae2tdPwUPEZLP3McqvFkiB842jRoVnYCxyofGgdkMSuP4gWguZMoS8tiYWP
Ae2tdPwUPEZJUAWD7JvnqB6iVUEr4hD8sfwswS4G7kuGVktSQ7G7ttuAfYN
Ae2tdPwUPEZJHpbXtmBhsy76AAT3Z5gaarJ78zZnQhFvMBeZeW2cUiqEpLV
Ae2tdPwUPEZKA5C5MHAN662VBu7kYky2QXPGRFDNjDuxSJf9ni2FsRfcy3Q
...
```
2. Try to send a transaction to and address of such a wallet

## Expected behavior

You can send tx.

## Actual behavior
 
Sending tx to an address results with:
```
Code = 400,
Json = {"code":"bad_request","message":"Error in $.payments[0].address: Unable to decode Address: neither Bech32-encoded nor a valid Byron Address."}
```

---

# Resolution 

- #1540 

---

# QA 

- Re-introduce the network discrimination inside of the sequential discovery because it is actually needed for computing the fingerprint of Icarus keys. So, this is now type-checked alongside other discrimination insteadof being hard-coded to 'Mainnet' :| 

- Added some extra sanity golden tests that I couldn't found in any other place of the test suite with typical Byron and Yoroi addresses taken from the live explorers: https://github.com/input-output-hk/cardano-wallet/blob/f73322046afbf77b282a404cc9751d11a2ec0ca3/lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs#L658-L680

**Comment by Anviking** [comment]
@KtorZ should this be moved to QA after your #1540 ?

**Comment by piotr-iohk** [comment]
LGTM.
