### ISSUE TITLE
Unexpected address format generation

### ISSUE THREAD

**Issue by nikolaglumac** [cardano-foundation/cardano-wallet#1546]
# Context
 
In the latest version of Daedalus Flight which is using the following `cardano-wallet` revision: `563c28f05c1f38c9741277f480a8983d37b05a68` we see unexpected address format when generating new addresses in "Selfnode" builds:

```
37btjrVyb4KEZmAVJoprtUcjjjomg81ZGwbxXsFsGZwrwUdKyV6pNSSt6qFWmGcp5qXYEfm76hrcTVA7xEsLaEmmEiC24V5cQnh2EiyTa9azGFH7i5
```

Daedalus Selfnode genesis and config files: [selfnode-config-and-genesis-files.zip](https://github.com/input-output-hk/cardano-wallet/files/4443860/selfnode-config-and-genesis-files.zip)

## Screenshot

![Addresses](https://user-images.githubusercontent.com/376611/78663951-59e78880-78d3-11ea-9ac7-a95f60b4985e.png)

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | 563c28f05c1f38c9741277f480a8983d37b05a68 |
| Platform     | All         |
| Installation | From Source           |

# Steps to Reproduce

1. Install Daedalus Flight Selfnode build: [Windows](https://ci-output-sink.s3.amazonaws.com/result/daedalus-1.0.0-FC2-cardano-wallet-2020.4.1-selfnode-windows-12151.exe), [Linux](https://ci-output-sink.s3.amazonaws.com/csl-daedalus/daedalus-1.0.0-FC2-cardano-wallet-cardano-selfnode-x86_64-linux-12151.bin), [macOS](https://ci-output-sink.s3.amazonaws.com/csl-daedalus/daedalus-1.0.0-FC2-cardano-wallet-2020.4.1-selfnode-macos-12151.pkg)
2. Create or restore Daedalus 12-word wallet using the UI
3. Navigate to "Receive" screen and use the "Generate address" feature to create a new address
4. Check the newly created address format

## Expected behavior

Expected address format:

```
9XQrTpiaBYn8jSfmP9N3WxuFnrCTAY4R4BGeQPToSB1M58fAb8wp56opkjn94gFt5WB1YBWwfuQxFnUW73mMPH4kMSSZ217GFjkU
```

## Actual behavior
 
Actual address format:

```
37btjrVyb4KEZmAVJoprtUcjjjomg81ZGwbxXsFsGZwrwUdKyV6pNSSt6qFWmGcp5qXYEfm76hrcTVA7xEsLaEmmEiC24V5cQnh2EiyTa9azGFH7i5
```

---

# Resolution 

Generated address format should match the expected one.

**Comment by KtorZ** [comment]
So. I just checked and ... both addresses are actually TESTNET addresses. But they have a different magic!

`9XQrTpia...` has `459045235` for magic, which is the magic that is set in the genesis file. 

However, 

`37btjrVyb...` has `1097911063` for magic, which is "default" testnet magic. 

What worries me a lot here is that, I generated the `9XQrTpia...` by hand, and manually specified the magic from the genesis here. But the `37b...` addresses are generated based on the protocol magic inferred from the genesis file we receive as argument. 

Here, we actually use functions from the consensus and ledger to extract the protocol magic from the genesis file, and that values is hard-coded nowhere in the source code of cardano-wallet.. So I am going to investigate this...

**Comment by nikolaglumac** [comment]
Thanks @KtorZ <3

**Comment by KtorZ** [comment]
Sorry. That's my bad... It's actually the opposite of what I just said. The `9XQr` are using the `1097911063` magic :man_facepalming:  ... So, addresses generated are the right ones. But not the one I gave you in the generated genesis file.

**Comment by nikolaglumac** [comment]
No harm done @KtorZ - please send me the updated genesis file. Closing this issue now...
