### ISSUE TITLE
jormungandr and cardano-node release artifacts are broken for MacOS

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#1553]
# Context
 
 

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | `2020-04-07` |
| Platform     | MacOS         |
| Installation | release            |

# Steps to Reproduce

"Backend" release artifacts are broken on MacOS

1. Download release artifacts for MacOS
2. Run `jormungandr` or `cardano-node` 

## Expected behavior

They should work.

## Actual behavior
``` 
$ cardano-node 
dyld: Library not loaded: /nix/store/8yi44skz13mlf5q6byy25m6is2pacscn-ncurses-6.1-20190112/lib/libncursesw.6.dylib
  Referenced from: /usr/local/bin/cardano-node
  Reason: image not found
Abort trap: 6
```

```
$ jormungandr 
-bash: /usr/local/bin/jormungandr: cannot execute binary file
```

Note. Both don't work on MacOS 10.13 for me, however `cardano-node` worked for @Anviking on his Mac. :man_shrugging:  

**Note2:** Workaround would be to use artifacts from the respective releases:
 - https://github.com/input-output-hk/jormungandr/releases/tag/v0.8.15
 - https://github.com/input-output-hk/cardano-node/releases/tag/1.9.3

---

# Resolution 

---

# QA 

1. Download releases:

   * [cardano-wallet-byron-macos64](https://hydra.iohk.io/job/Cardano/cardano-wallet/cardano-wallet-byron-macos64/latest)
   * [cardano-wallet-jormungandr-macos64](https://hydra.iohk.io/job/Cardano/cardano-wallet/cardano-wallet-jormungandr-macos64/latest)

2. Extract to temporary directory.

3. Test using the `file` command that all binaries are "Mach-O" executables.

4. Check that jormungandr is removed from `cardano-wallet-jormungandr-macos64`

5. Check that `cardano-node run --help` works on macos with `cardano-wallet-byron-macos64`.

**Comment by rvl** [comment]
The `jormungandr` binary in the macos release tarball is actually a Linux binary. Perhaps it was due to the overlays changes that @disassembler implemented.

That `cardano-node` needs `rewrite-libs` applied to it ⇒ #1554.

**Comment by piotr-iohk** [comment]
lgtm!
