### ISSUE TITLE
Rollback to EBBs likely not handled correctly

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#1570]
# Context
 

<img width="1025" alt="Skärmavbild 2020-04-15 kl  10 01 22" src="https://user-images.githubusercontent.com/304423/79313055-122eb580-7f00-11ea-86c4-ba84e3aa37f0.png">

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      |  |
| Platform     |           |
| Installation |             |

# Steps to Reproduce

TODO

1. ...

## Actual behavior
 

---

# Resolution 

# QA

**Comment by Anviking** [comment]
A solution that was discussed was to rollback further than required, except for genesis:
- `if genesis then deleteWhere (>= slot) else deleteWhere (> slot)`

I believe make it impossible to switch to rollback to genesis and switch to a new fork right after it.

Pros:
- Simple to implement

Cons:
- Cannot handle rollback to genesis properly (but should never happen?)

An alternative could be to use `blockHeight` after 1) filtering out EBBs and 2) assigning genesis a block height of 0, such that all blocks have a unique block height:

<img width="767" alt="Skärmavbild 2020-04-21 kl  12 31 12" src="https://user-images.githubusercontent.com/304423/79856037-165d4600-83cc-11ea-8ed2-a43de3ce0c53.png">

If we are asked to rollback to the first EBB in the sketch, we would e.g. instead roll back to genesis.

Pros:
- Should handle rollback to genesis

Cons:
- Requires more extensive changes. Perhaps unnecessarily risky.

**Comment by KtorZ** [comment]
We do however already store and have access to the blockheight for both jormungandr and cardano-node, don't we? So option 2 seems by far better / cleaner to me.

Although, I am not sure to the "1) filtering out EBBs". Do EBB also have the same block height as the next block :scream:  ?

**Comment by Anviking** [comment]
Outcome of call:
- Rollback to EBB will never happen
- Let's switch to using `BlockNo` for rollback which gives genesis a unique value of 0

However in the [Pool DB](https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/src/Cardano/Pool/DB/Sqlite.hs#L219-L221) we probably want to keep using `SlotId`.

So we'd either use `rollbackTo :: BlockHeader -> ...` or some kind of polymorphic `rollbackTo :: tip -> ...`

Which both are very similar and should work fine, I think.

**Comment by Anviking** [comment]
For wallet delegations we would have had to either
1.  Continue rolling back based on `SlotId`
2. Add an extra `BlockNo` field to the delegation certificate table

In addition to changing types around a bit everywhere.

All for the benefit of handling rollbacks to genesis which, even on a Shelley-only testnet would be… very unlikely?

Closing for now.
