### ISSUE TITLE
Byron `initCursor` does not seem to cause DB to rollback

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#1571]
# Context
 
 

https://github.com/input-output-hk/cardano-wallet/blob/5333afc469294bfa74e07de3317578545661ea05/lib/byron/src/Cardano/Wallet/Byron/Network.hs#L259-L268

`initCursor` will find the intersection between the node and the wallet tip.

If `intersection /= walletTip` the wallet DB needs to rollback. I don't think we do that.

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      |  |
| Platform     |           |
| Installation |             |

# Steps to Reproduce

Imagined scenario:
1. Sync the chain 
2. Stop the wallet. Wait for the network to fork.
3. Start the wallet again.

```
   +- B2a
  /
B1 
   \
    +- B2b 
```

1. Wallet will send `[B1, B2a]` as known points.
2. Node will select B1.
3. Node will send B2b.

## Expected behavior

Wallet should rollback to B1, such that it can switch to the new chain and apply B2b.

## Actual behavior

(Imagined, not tested ⚠️ )

Wallet will stay at B2a. When trying to apply B2b it will crash because of an invariant.
 

---

# Resolution 

---

# QA

**Comment by KtorZ** [comment]
So, after investigation this scenario doesn't look plausible. Here's why:

1. When the restoration loops start, the wallet initialize a cursor using a list of checkpoints. 
  
  ```hs
  cps <- liftIO $ atomically $ listCheckpoints (PrimaryKey wid)
  [...]
  initCursor nl cps
  ```

2. For initializing the cursor, the list of headers is sent to the node via a `FindIntersect` message and the cursor is initialized **at the intersection point**:

  ```hs
  chainSyncQ `send` CmdFindIntersection points >>= \case
    Right (Just intersection) -> do
        pure $ Cursor intersection chainSyncQ
  ```

3. Then, we _know_ from the protocol specification that the first response to a `RequestNext` after setting an intersection will necessarily be a `RollBackward` to that intersection point. Therefore, if the intersection is found anywhere within the list of headers, we'll first start by rolling back to that point.


4. Each rollback restarts the restoration loops exactly as if the whole process was starting from the beginning, so this bring us back to step 1. Now the question is, how and when do we ever break that loop and continue restoring as normal? This is where the trick is: we do not treat `intersection /= walletTip` as an exceptional case, but we do treat `intersection == walletTip` as one! Any request to roll backward to the wallet's tip is indeed ignored:

    ```hs
    Right (RollBackward cursor') ->
        -- NOTE
        -- In case the node asks us to rollback to the last checkpoints we
        -- gave, we take no action and simply move on to the next query.
        -- This happens typically with the Haskell nodes which always
        -- initiates the protocol by asking clients to rollback to the last
        -- known intersection.
        case (cursorSlotId nl cursor', cps) of
            (sl, _:_) | sl == slotId (last cps) ->
                step delay0 cursor'
            (sl, _) ->
                pure (FollowRollback sl)
    ```

There's one _slight_ limitation / gotcha with this approach. In the step 4, the `cps` refers to the original list of 
checkpoints given to the `follow` function. So we could imagine a scenario where:

  a. The intersection is initially found at the tip. 
  b. A few blocks are added on top
  c. Later, a rollback is requested to where the tip was (but no longer is).

That last rollback requests in c. would just be ignored :/ ... As a consequence, next blocks would fail to apply, but the worker would recover itself by restarting from the start, looking back for a new intersection. So, not as pretty as it could be, but also not a significant problem. I do not think changing anything here would be wise provided we intend to undergo more drastic changes on the network layer approach.
