### ISSUE TITLE
Recovery from chain-following exceptions may cause node to crash

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#1572]
# Context
 
 

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      |  |
| Platform     |           |
| Installation |             |

The chain following code will recover from errors and retry immediately.

It is not throttled, which might lead to a (fast) infinite loop.

Follow-up to  #1505 where it seemed that the node was crashing because of this.

# Steps to Reproduce

Imagined:
- Throw exception in chain-follower

## Expected behavior

- Wallet either 1) crashes or 2) retries at a calm rate
- Node should not crash in the second case

## Actual behavior

- Wallet retries really fast, producing a lot of noisy logs
- Node may crash? (#1505)
 

---

# Resolution 

---

# QA

**Comment by KtorZ** [comment]
That is no longer the case, the wallet now "sleeps" between each retry and only retry "retryable" exceptions. Other will simply lead to crash.
