### ISSUE TITLE
DB.rollbackTo may cause inconsistencies between checkpoints and other data

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#1575]
# Context
 
 

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      |  |
| Platform     |           |
| Installation |             |

# Steps to Reproduce

If our DB stores:
```
Checkpoints: cpA                cpB
TxMeta:          m1
Certs:                     c1
--------------------------------------> Increasing slotId
                              |
                              |
                              + p, rollback to here
```
And we rollback to some point p between c1 and cpB.

## Expected behavior

- We rollback to `cpA`, and make sure all other data is consistent with that checkpoint.

## Actual behavior

We rollback to `cpA`
We don’t remove txMeta1 and cert1 because they are earlier than the _requested_ rollback point _p_.

And our new state is:
```
Checkpoints: cpA            
TxMeta:          m1
Certs:                     c1
--------------------------------------> Increasing slotId
```
The wallet will continue restoring from cpA. `m1` is a txMeta from a different chain, and shouldn't exist.

- [Example test 1](https://github.com/input-output-hk/cardano-wallet/blob/5333afc469294bfa74e07de3317578545661ea05/lib/core/test/unit/Cardano/Wallet/DB/SqliteSpec.hs#L458-L503)
- [Example test 2](https://github.com/input-output-hk/cardano-wallet/pull/1573/files#diff-14a8238703a0aa58c4ac6e0fcda7e6eaR556-R663)
 

---

# Resolution 

- Clear certs, txMeta etc based on the actual rollback point instead of the requested rollback point #1579 

---

# QA 

- Golden test in DB close which is almost a "mockchain" that illustrates problem
- Adjusted both Sqlite DB, and Model DB
- Also had to tweak an existing property test

**Comment by piotr-iohk** [comment]
lgtm.
