### ISSUE TITLE
Next delegation status may not work in epoch 0 of Shelley-only testnet

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#1585]
# Context
 
 

- Wallet displays the current and next delegation status
- At one point there will be a new, fresh Shelley testnet starting from the beginning (no Byron) [[src]](https://input-output-rnd.slack.com/archives/C819S481Y/p1587467659195000?thread_ts=1587467219.194700&cid=C819S481Y)

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      |  |
| Platform     |           |
| Installation |             |

# Steps to Reproduce

1. Publish delegation certificate in epoch 0

(Nothing's stopping this from happening, right?)

## Expected behavior

1. Delegation status changes to `{ active = NotDelegating, next = Delegating }` (pseudocode)

## Actual behavior

Looks like implementation of `readWalletDelegation` returns `NotDelegating []` for epoch 0.
https://github.com/input-output-hk/cardano-wallet/blob/b8ae9821f27eb24a119aa06532519cce2ab11cbc/lib/core/src/Cardano/Wallet/DB/Sqlite.hs#L632

(not tested)

---

# Resolution 

---

# QA

**Comment by KtorZ** [comment]
Of course, if the certificate is published at epoch 0, you can't possibly be delegating at epoch 0. The delegation is only effective in the next epoch.

**Comment by KtorZ** [comment]
Of course, if the certificate is published at epoch 0, you can't possibly be delegating at epoch 0. The delegation is only effective in the next epoch.

**Comment by KtorZ** [comment]
Of course, if the certificate is published at epoch 0, you can't possibly be delegating at epoch 0. The delegation is only effective in the next epoch.

**Comment by Anviking** [comment]
Yes, but it seems like the code disregards the possibility of having a "next" delegation status during epoch 0.

**Comment by rvl** [comment]
Who would you delegate to in the first epoch? There would be no pools registered yet.

**Comment by Anviking** [comment]
Good point.

But there _could_ be pools registered in epoch 0, just that we would currently not show them. [If fixed](https://input-output-rnd.slack.com/archives/C819S481Y/p1593396135437600), I _believe_ delegation to them should be possible.

IIRC it is also possible on jormungandr.

Of course, pretty small problem though.

**Comment by KtorZ** [comment]
Seems like it worked :shrug:
