### ISSUE TITLE
CLI: Support public key derivation

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#1594]
# Context

ADP-190

Last time we didn't have time to properly allow the `key` CLI commands deal with public keys.

Partially-relevant diagram I made back then (of derivation in wallet, CLI utilities gives more freedom):

<img width="465" alt="Skärmavbild 2020-04-24 kl  14 01 23" src="https://user-images.githubusercontent.com/304423/80210775-9dacf280-8634-11ea-93c6-00e98fc352cf.png">

# Decision

Make `CliKeySchema` support dealing with public keys.

# Acceptance Criteria

- `key child` must support _soft_ address derivation with _public_ keys
- `key inspect` must support inspecting _public_ keys
- Previous functionality _must_ be preserved

---

# Development 

# QA 

- Added a golden test https://github.com/input-output-hk/cardano-wallet/pull/1588/commits/f2d933be66273c626fdfc6eeb929118dee299cc5
- Added property comparing with private key derivation https://github.com/input-output-hk/cardano-wallet/pull/1588/commits/779ebe5f3ac8d8169b1d06ff897371b3c2be8035
- (A golden test (using a real executable) is coming with #1599 )

**Comment by piotr-iohk** [comment]
lgtm
