### ISSUE TITLE
Move now jormungandr-specific bits regarding stake pool metadata under 'cardano-wallet-jormungandr'

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1595]
# Context

Metadata are implemented in a slightly different way between Jörmungandr and cardano-node. In particular, both relies on an aggregation "server" but with drastically different interfaces.

# Decision

As a starter, we want to move the current bits of implementation under the cardano-wallet-jormungandr package, to make room for the other implementation in cardano-node. We also know that the resolution of pool performances and ranking will be done in a different fashion, so the performance modules and, the whole stake pool database can be moved under the jormungandr-specific package.

# Acceptance Criteria

1. `cardano-wallet-core` _must_ be freed of any jormungandr-specific bits. 
2. `cardano-wallet-jormungandr` _must_ still work without any visible change. 

---

# Development 

- [x] Code moved as part of #1598  

# QA 

- There's no functional change. The code has just been relocated. Existing tests still pass.

**Comment by piotr-iohk** [comment]
lgtm.
