### ISSUE TITLE
Mock metadata aggregation server

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1596]
# Context

The specification for the new metadata aggregation server is captured in the following swagger document:

https://gist.github.com/KtorZ/4ee1bf8136c91f2d4c36ed850023cab6

# Decision

In order to test the aggregation server, we'll need to setup a mock HTTP server that satisfies this specification. 

# Acceptance Criteria

---

# Development 

- [ ] Create a simple servant application that "mocks" the swagger specification ==> #1614 

# QA 

- The mock server is property tested checking that:
    a) It returns valid responses that satisfy the swagger schema mentioned above
    b) Returns both positive and negative responses (404), but does it deterministically (same pool id, same response always) so that we can use it to test correct behavior.
   
see property here: https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Cardano/Pool/MetadataSpec.hs#L117-L137

The relevant bits of the schema were written directly using the Swagger DSL in Haskell: 

https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Cardano/Pool/MetadataSpec.hs#L262-L290

**Comment by piotr-iohk** [comment]
LGTM.
