### ISSUE TITLE
Module for fetching and caching metadata from the aggregation server

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1597]
# Context

See:

- https://jira.iohk.io/browse/ADP-258
- #1595
- #1596 

# Decision

Write a self-isolated module that can offer a simple interface to fetch and refresh metadata from an aggregation server. We'll likely cache these data in a database or on-disk in a second step.

# Acceptance Criteria

---

# Development 

- Cached client fetching data from an aggregation server ==> #1623 
- ~~Database interface for storing and fetching cached metadata~~ ==> Will actually do when we have more confidence about the final format of the metadata. This should be pretty straightforward but doing it now could force us to have to work on some unfortunate db migration later :| 

# QA 

- The cached client is tested in various scenarios with existing and non existing metadata [here](https://github.com/input-output-hk/cardano-wallet/blob/a218df265f67d2e8c941deb383129c521197a114/lib/core/test/unit/Cardano/Pool/MetadataSpec.hs#L139-L169).

**Comment by Anviking** [comment]
Btw, did you know about [`managerRetryableException`](https://hackage.haskell.org/package/http-client-0.6.1/docs/src/Network.HTTP.Client.Types.html#managerRetryableException)? Maybe it could have been used for cardano-wallet-jormungandr, or can be used here, if we want retrying.

**Comment by KtorZ** [comment]
Nope I didn't! Sounds like indeed something that is pretty handy. I've seen the servant client automatically retry on 500 errors. I wonder if it's manual or using this setting from the manager.

**Comment by piotr-iohk** [comment]
LGTM.
