### ISSUE TITLE
Porting and cleaning up Cardano.Mnemonic module (incl. corresponding tests)

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#16]
# Context

As part of this rewrite of the wallet backend, we do not want to depend on any of the code from `cardano-sl`; Yet, there are a few bits that were made in a fairly isolated manner that are still very relevant to the wallet This is the case of:

https://github.com/input-output-hk/cardano-sl/tree/develop/mnemonic

Minus a few bits that are strictly related to `cardano-sl` like:

- https://github.com/input-output-hk/cardano-sl/blob/develop/mnemonic/src/Cardano/Mnemonic.hs#L155-L186
- https://github.com/input-output-hk/cardano-sl/blob/develop/mnemonic/src/Cardano/Mnemonic.hs#L237-L240
- https://github.com/input-output-hk/cardano-sl/blob/develop/mnemonic/src/Cardano/Mnemonic.hs#L286-L316

# Decision

We do want to port this module onto `cardano-wallet`, review the style to make it consistent with our coding standards, and remove the bits that aren't relevant to this new code. We do want to make this a module of `cardano-wallet` (and not a package as it is now), under `Cardano.Wallet.Mnemonic`. 

Tests should also share the same faith and be ported in their rightful place. 

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #47       | `master`  |
| #58 | `master` | 

# QA 

The PR introduces `Cardano.Wallet.Mnemonics` module which delivers mnemonic creation. From the point of view of testing there are two aspects : 
(a) unit tests that are in located in `Cardano.Wallet,MnemonicsSpec` module.
(b) executable that uses this and generates **Mnemonic 15** mnemonics
```
$ stack build
[pawel@arch cardano-wallet]$ stack exec cardano-generate-mnemonic
["love","dutch","usual","uphold","whale","certain","merry","horror","bulb","injury","school","crane","grass","police","beauty"]
```

**Comment by piotr-iohk** [comment]
lgtm :+1: 
I wanted to ask about `SlottingOrphans.hs` but I see it has been removed by #57.

**Comment by piotr-iohk** [comment]
lgtm :+1: 
(I have added few more tests and adjusted API spec in #58)
