### ISSUE TITLE
Use mnemonics from cardano-addresses

### ISSUE THREAD

**Issue by paweljakubas** [cardano-foundation/cardano-wallet#1601]
# Context

Mnemonics functionality was relocated to `cardano-addresses` and we want to use it inside cardano-wallet

# Decision

We use mnemonics module of cardano-addresses inside cardano-wallet

# Acceptance Criteria

1. We do not have separate mnemonic module and test in cardano-wallet but rely on mnemonic module of cardano-addresses
2. All other stuff that use mnemonics is adjusted

---

# Development 

# QA 

Removed in two PRs all mnemonics code and NatVal from AddressDerivation module and used stuff from Cardano.Mnemonic from cardano-addresses

**Comment by piotr-iohk** [comment]
OK. Since `cardano-addresses` is now one of the `cardano-wallet` dependencies I have added this extra step in [release checklist](https://github.com/input-output-hk/cardano-wallet/wiki/Release-Checklist):

> Make sure cardano-wallet points to correct revisions of dependent low-level libs (verify on target repositories if stack.yaml points to appopriate revisions for persistent, cardano-addresses...)

cc: @KtorZ
