### ISSUE TITLE
Database migration script is failing on nightly

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#1608]
# Context
 
https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/497#98a17e05-2390-4a6f-b0ed-5a42f6ea0887

# Test Case

Database migration is failing on nightly...

# Failure / Counter-example

https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/497#98a17e05-2390-4a6f-b0ed-5a42f6ea0887

---

# Resolution 

---

# QA

**Comment by rvl** [comment]
This should be fixed by #1604.
