### ISSUE TITLE
Broken API doc link for `listByronAddresses`

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1609]
# Context
 
 

https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/listByronAddresses

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      |  |
| Platform     |           |
| Installation |             |

# Steps to Reproduce

1. Both operations are named the same in the swagger doc, and as a consequence, linking to listByronAddresses doesn't work :s

## Actual behavior
 

---

# Resolution 

---

# QA

**Comment by piotr-iohk** [comment]
_Fixed._
