### ISSUE TITLE
Database migration tests is failing

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#1621]
# Context
 
Seems to be failing:

```
*** Migrating from v2019-12-13 ***
*** Migrating from v2019-12-16 ***
```

# Test Case

https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/502#3cee1ff2-e03a-4e1c-abca-3fac2ff3b1d6

# Failure / Counter-example

https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/502#3cee1ff2-e03a-4e1c-abca-3fac2ff3b1d6

---

# Resolution 

---

# QA

**Comment by piotr-iohk** [comment]
BTW -> https://github.com/input-output-hk/cardano-wallet/blob/master/nix/migration-tests.nix#L44-L61

It seems that we are testing against fixed versions, which are quite old now. Not sure what would make sense to support in migration, 3 versions back, 5 versions back? Or maybe we need to support migration from any version that was released?

**Comment by rvl** [comment]
Oh I see. It wants to drop and recreate the checkpoint table when non-nullable columns are removed. That will be an issue for upgrading Daedalus.

Definitely, we should only test migrating from the versions that we care about. And we should be testing cardano-wallet-byron.

**Comment by KtorZ** [comment]
Seems like there's still an issue in the migration tests: https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/505

Unless this nightly was triggered before #1624 was merged somehow.

**Comment by rvl** [comment]
Yes that build was triggered before #1624 got merged.
I kicked off another test where it has passed:
https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/506

**Comment by piotr-iohk** [comment]
Migration tests passed in https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/506
