### ISSUE TITLE
Use address derivation from cardano-addresses

### ISSUE THREAD

**Issue by paweljakubas** [cardano-foundation/cardano-wallet#1637]
# Context

We have separate cardano-addresses repo that contains implementation of mnemonics and address derivation interface along with byron, icarus, jomrungandr and shelley implementations

# Decision

We want to use address-derivation's interfaces and impl inside cardano-wallet, and replace it with current ones

# Acceptance Criteria

1. `HardDerivation`, `SoftDerivation`, `StakingDerivation`, `PaymentAddress` and `DelegationAddress`
2. Use crypto primitives from cardano-addresses 
3. Use `Depth`, `Index`, DerivationType`, `AccountStyle` from cardano-addresses
4. Styles and corresponding unit tests are removed
5. The rest codebase is adjusted

---

# Development 

# QA

**Comment by KtorZ** [comment]
Tracked in JIRA as: https://jira.iohk.io/browse/ADP-438
