### ISSUE TITLE
Does it possible request transaction by id?

### ISSUE THREAD

**Issue by fonov** [cardano-foundation/cardano-wallet#1641]
find only method for receive list of transaction 

https://github.com/input-output-hk/cardano-wallet/wiki/Wallet-Command-Line-Interface-(cardano-wallet-byron)/fc82be65a7bbd0b24f2d0663c12079d2157a7980#transaction-list

older api (v1) have a filter options for get transaction by id

https://docs.cardano.org/technical/wallet/api/v1/?v=1.3.0#tag/Transactions

**Comment by KtorZ** [comment]
This is indeed **not** currently supported by the API.

**Comment by fonov** [comment]
May you suggest any workaround for it?

Thursday, 7 May 2020, 19:21 +0300 from notifications@github.com  <notifications@github.com>:

**Comment by KtorZ** [comment]
A work around would be to filter the list of results you get from https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/listByronTransactions or https://github.com/input-output-hk/cardano-wallet/wiki/Wallet-Command-Line-Interface-(cardano-wallet-byron)/fc82be65a7bbd0b24f2d0663c12079d2157a7980#transaction-list. 

Every resource has an "id" field to filter upon.

**Comment by fonov** [comment]
**Ok, thanks for quick answer**. I also will use `start` query with value (pending_since.time) from create transaction output for reduce transaction list

**Comment by KtorZ** [comment]
This is now tracked in a separate (non public) ticket system as part of our backlog :+1:
