### ISSUE TITLE
Add statistics to fee estimation API endpoint

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#1648]
# Context

Jira user story is ADP-283 Reduce variability in fee estimation

> As an API user,
> I want to be able to rely on a somewhat stable fee estimation,
> so that I can better inform my users about the cost of a transaction.

Fee estimation in its current form can be a little confusing. Because the underlying coin selection is a (non-seeded) random algorithm, it is hard to know which coins will be picked for payment in advance.

The current fee estimation in cardano-wallet is quite naive: it applies the normal coin selection process, balance the selection and returns the fees corresponding to that particular selection. Yet there's no guarantee than upon making the real payment, the same coins will be selected, and therefore, the same fee amount will be paid.

Of course, in practice the variability on small UTxO sets is quite small, but it still exists. So, a better alternative would be to run multiple selections, and returns a more elaborated response to the API client with:

 * max fee
 * 9th decile

so we can provide more reliable statistical answers like "90% of the transactions cost at least X, but not more than Y."

# Decision

1. Add a new interface to the fee estimation function which repeats the process and returns statistics along with the result.
2. Change cardano-wallet-core to use this new function.
3. Adjust API definitions to add more information to the `/wallets/{walletId}/payment-fees` endpoint.

## To be decided

1. How many times to run the estimation. e.g. run it until the statistical distribution is confidently known.
2. Which parts to implement in cardano-coin-selection vs cardano-wallet-core.
3. Check that monte carlo simulation is the best method to get this answer.

# Acceptance Criteria

1. The fee estimation API _must_ provide statistical background information about its result.
2. The following statistics _must_ be returned from the API:
   - max fee
   - 9th decile

---

# Development 

1. Implement in cardano-wallet-core for now.
2. Ensure that the estimation function can be unit tested.
3. Repeat the sampling a fixed number of times - 100 samples.
4. Update swagger spec and notify Daedalus team.

# QA 

1. This adds a property test for the estimation function in `lib/core/test/unit/Cardano/WalletSpec.hs`.
2. Integration tests that deal with transaction estimates are updated to use estimatedMin and estimatedMax.

**Comment by piotr-iohk** [comment]
@rvl two questions:

1. Currently the "fee" response is as follows:
```
{
"estimated_min": {
"quantity": 42000000,
"unit": "lovelace"
},
"estimated_max": {
"quantity": 42000000,
"unit": "lovelace"
}
}
```
The acceptance criteria mentions also `9th centile`, was that not included intentionally, or maybe `9th centile` became `estimated_min`? (I suppose it was but wanted to make sure).

2. The change influences:
`POST /byron-wallets/{walletId}/payment-fees`
`POST /wallets/{walletId}/payment-fees`
`GET /wallets/{walletId}/delegation-fees`

Just want to make sure that Daedalus is aware of all? (I'm sure it is, but again to double check)

**Comment by piotr-iohk** [comment]
Ok, question 2 sorted -> https://github.com/input-output-hk/daedalus/pull/2021. :)

**Comment by rvl** [comment]
1. Yes - 9th centile becomes `estimated_min` and 10th centile becomes `estimated_max`.
2. Thanks @piotr-iohk  - I just mentioned `POST /wallets/{walletId}/payment-fees` and the `swagger.yaml` diff, but we can put all in the release notes as well.

**Comment by piotr-iohk** [comment]
lgtm.
