### ISSUE TITLE
Restoration benchmark on mainnet for 1% and 2% ownership unexpectedly slow

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#1650]
# Context

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | `2020.5.6 (git revision: 655a45952f3bbfa862140d12843e6d87a3577a6e)` |
| Platform     | All?          |
| Installation | From source          |
 
Looking at recent restoration benchmark results after introducing pipelining (https://github.com/input-output-hk/cardano-wallet/pull/1615):

 - TESTNET ([see chart](http://cardano-wallet-benchmarks.herokuapp.com/testnet-restoration)). Last 3 builds show the restoration times being 2 or 3 times faster for all 3 benchmarks :tada: 

![Screenshot from 2020-05-11 13-55-40](https://user-images.githubusercontent.com/42900201/81559140-2c3ca600-938f-11ea-91ef-598099f64e4b.png)

 - MAINNET ([see chart](http://cardano-wallet-benchmarks.herokuapp.com/mainnet-restoration)). Shows improvement for the first benchmark (`restore mainnet seq`), but it shows that restoration for 1% and 2% as being almost two times slower...

![Screenshot from 2020-05-11 13-55-21](https://user-images.githubusercontent.com/42900201/81559151-3068c380-938f-11ea-9ae9-f194f7cfe30e.png)

:wave: :arrow_down: 
Look also at the memory profiles and blockchain height vs. time plot for before and after pipelining, interesing how they differ:

|Before pilelining| After pipelining  |
|--|--|
| [508](http://cardano-wallet-benchmarks.herokuapp.com/nightbuilds/508) |   [511](http://cardano-wallet-benchmarks.herokuapp.com/nightbuilds/511) |

# Steps to Reproduce

Run restoration benchmarks.

## Expected behavior

Expected would be to observe improvement in restoration times on all benchmarks.

## Actual behavior
 
Slower restoration for 1% and 2% ownership for mainnet.

---

# Resolution 

- Avoid creating too many checkpoints near the chain tip and either batch or pipeline there. See #1665

---

# QA

**Comment by KtorZ** [comment]
So I thought about this and have an explanation. The new pipelining approach is actually "not particularly optimized" near the tip of the chain, in the sense that it's making checkpoint for the k last slots, whereas before, it was making only 12 checkpoints (one every 1000 blocks, and the 10 last checkpoints). For the 1% benchmark, we can see that it takes:

- 3255 seconds to go from 0% to 99.94%
- 2300 seconds to go from 99.94% to 100% 

So, most of the time really is spent creating those last 2160 checkpoints, whereas this is not actually useful.

**Comment by piotr-iohk** [comment]
I suppose this is in line with the pattern from the block height / time plot:

![Screenshot from 2020-05-11 15-08-46](https://user-images.githubusercontent.com/42900201/81565251-55faca80-9399-11ea-8fa9-55df2a2818a9.png)

(http://cardano-wallet-benchmarks.herokuapp.com/nightbuilds/511)

**Comment by KtorZ** [comment]
Indeed :no_mouth: When I originally looked at the graph I thought "hey, so we are actually reaching 100% quite fast, but... not quite.

**Comment by piotr-iohk** [comment]
After #1665 :tada:

![Screenshot from 2020-05-19 10-08-13](https://user-images.githubusercontent.com/42900201/82301590-bf419580-99b8-11ea-88e5-54dd6e728561.png)
