### ISSUE TITLE
(ADP-319) Add golden test vectors for Shelley Transactions

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#1674]
# Context

ADP-319

We want to add Shelley transaction support.

There is a `cardano-cli` which should now support creating txs.

3rd part folks also want test vectors.

# Decision

- Add a `yaml` file with transaction test vectors

# Acceptance Criteria

- There must exist a `yaml` file with transaction test vectors
- The wallet must pass these tests

---

# Development 

# QA

**Comment by KtorZ** [comment]
closing, this was done: https://gist.github.com/KtorZ/5a2089df0915f21aca368d12545ab230
