### ISSUE TITLE
Remove `epochId` argument from `getNetworkParameters`.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#1690]
# Context

The presence of the `epochId` path parameter in the `/network/parameters/<epochId>` endpoint might give callers the _impression_ that calling `GET` on the endpoint will retrieve parameters corresponding to a particular epoch.

In reality, however, this endpoint only ever returns parameters corresponding to the _latest_ epoch, _regardless_ of which epoch is specified.

# Decision

Remove the `epochId` argument from this endpoint.

# Acceptance Criteria

- [x] The `epochId` argument _must_ be removed from the `getNetworkParameters` endpoint.
- [x] The `getNetworkParameters` endpoint _must_ always return parameters that correspond to the _latest_ epoch.
- [x] We _must_ provide assistance to projects that consume `cardano-wallet`, to help them transition to the modified endpoint. (See https://input-output-rnd.slack.com/archives/C7PJ29FME/p1590569319044000)

# Development 

Remove the following functions and types:

- [x] `ApiEpochNumber`
- [x] `errMsg404NoEpochNo`
- [x] `getNetworkParamsViaCliExpectingFailure`

In addition:

- [x] Adjust description of CLI `network parameters` command to read "View network parameters for the current epoch".

# QA 

- [x] Adjust existing API and CLI tests. We no longer need to test the `epochId` parameter as it no longer exists, but we should retain basic tests to check that the API function and CLI command both still work.

**Comment by rvl** [comment]
Just noting here that the only parameter in the current ApiNetworkParameters that will ever update in shelley is activeSlotCoeff. The rest come from the genesis block.

**Comment by jonathanknowles** [comment]
@rvl wrote:

> Just noting here that the only parameter in the current ApiNetworkParameters that will ever update in shelley is activeSlotCoeff. The rest come from the genesis block.

That's a great point. Perhaps we could break this type up into two separate types: one for static parameters, and another for parameters that can be updated.

I've started a discussion thread about this here: https://input-output-rnd.slack.com/archives/GBT05825V/p1590642003077400

**Comment by piotr-iohk** [comment]
lgtm.
