### ISSUE TITLE
Add skeletal `decentralizationLevel` field to `ApiNetworkParameters`.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#1692]
# Context

We need to provide a way for API users to query the current level of decentralization in the Cardano network, represented by the `d` network parameter.

# Decision

Add a field `decentralizationLevel` (of type `Quantity "percent" Percentage`) to the `ApiNetworkParameters` record type, and make corresponding adjustments to the swagger API definition.

For _this_ task, we will arrange that the value of this field is always set to **0%**. _Future_ tasks will cause this field to be set to the true value reported by the network.

# Acceptance Criteria

- [x] The `ApiNetworkParameters` type _must_ have a `decentralizationLevel` field, and the swagger API definition _must_ have a corresponding field that matches.
- [x] The `decentralizationLevel` field _should_ have type `Quantity "percent" Percentage` (already defined elsewhere), where **0%** indicates that the network is completely federalized, and **100%** indicates that the network is completely decentralized.
- [x] The `decentralizationLevel` field _may_ be assigned a constant value of **0%**. (Reporting the _true_ network value is _not_ part of the acceptance criteria of this task.)

# Development 

- [x] Add skeletal `decentralizationLevel` field to `ApiNetworkParameters`.

# QA 

- [x] Write an integration test to check that the API really does return a value of 0% for the decentralization level. In future, we can adjust our test to expect the live value.

**Comment by piotr-iohk** [comment]
lgtm.
