### ISSUE TITLE
Report live value of `d` parameter in `decentralizationLevel`.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#1693]
# Context

Task #1692 will have added a skeletal `decentralizationLevel` parameter to the `ApiNetworkParameters` object.

# Decision

Adjust the code so that this parameter reflects the true value of the `d` parameter, as reported by the network.

# Acceptance Criteria

- The `GetNetworkParameters` API endpoint **must** return a decentralization level percentage that reflects the true value of the `d` parameter, as reported by the network.

# Development 

- [x] (https://github.com/input-output-hk/cardano-wallet/pull/1700)
    Introduce `ProtocolParameters` type to hold (a subset of) the protocol parameters defined in [a Formal Specification of the Cardano Ledger](https://hydra.iohk.io/build/2839558/download/1/ledger-spec.pdf).

    ```hs
    data ProtocolParameters = ProtocolParameters  
        { decentralizationLevel
            :: Quantity "percent" Percentage      
        , txParameters
            :: TxParameters       
        }
    ```

- [x] (https://github.com/input-output-hk/cardano-wallet/pull/1700)
    Rewrite the `GenesisBlockParameters` type to include a `ProtocolParameters` value (whose type is defined above):
    ```patch
    - data GenesisBlockParameters = GenesisBlockParameters
    -     { staticParameters :: BlockchainParameters
    -     ,     txParameters ::         TxParameters
    -     }
    + data NetworkParameters = NetworkParameters
    +     {  genesisParameters ::  GenesisParameters
    +     , protocolParameters :: ProtocolParameters
    +     }
    ```
- [x] (https://github.com/input-output-hk/cardano-wallet/pull/1700)
    Change the type of `toApiNetworkParameters` to:

    ```patch
    - toApiNetworkParameters :: BlockchainParameters -> ApiNetworkParameters
    + toApiNetworkParameters ::    NetworkParameters -> ApiNetworkParameters
    ```

- [x] (https://github.com/input-output-hk/cardano-wallet/pull/1715)
    Revise documentation comments for the following types:
    - [x] `NetworkParameters`
    - [x] `GenesisParameters`
    - [x] `ProtocolParameters`<br/><br/>

- [x] (https://github.com/input-output-hk/cardano-wallet/pull/1725)
    Generalize the wallet, network, and database layers to use `ProtocolParameters` instead of `TxParameters`. (`ProtocolParameters` includes `TxParameters`).
 
- [x] (https://github.com/input-output-hk/cardano-wallet/pull/1725)
    Adjust the chain-following code to retrieve the current value of the `d` parameter, in the same way we already do for transaction parameters.

- [x] (https://github.com/input-output-hk/cardano-wallet/pull/1725)
     Introduce a `DecentralizationLevel` type (based on the `Percentage` type).

    _Greater_ values should indicate _greater_ levels of decentralization, as follows:

    | Value | Meaning |
    | --: | :-- |
    | 0% | Network is completely _federalized_ |
    | 100% | Network is completely _decentralized_ |

- [x] (https://github.com/input-output-hk/cardano-wallet/pull/1725)
    Add a function to convert from `d` parameter values to values of type `DecentralizationLevel`, performing the following mapping:

    ```
    {1 → 0%, 0.9 → 10%, 0.8 → 20%, ..., 0 → 100%}
    ```

# QA 

- [x] Create unit and property tests to check that we correctly convert from values of `d` (provided by `cardano-node`) to values of `DecentralizationLevel`.
- [x] Add unit test to `lib/byron/test/unit/Cardano/Wallet/Byron/NetworkSpec.hs` to see that decentralization parameter is updated ⇒ #1736.
- [x] Add integration test ` NETWORK_PARAMS - Able to fetch network parameters` to check that decentralization parameter is correct (this is not checking parameter updates however) ⇒ #1736.

**Comment by piotr-iohk** [comment]
lgtm.
