### ISSUE TITLE
Import address API /{walletId}/addresses/{addressId} returns an error

### ISSUE THREAD

**Issue by ntfreem** [cardano-foundation/cardano-wallet#1705]
Using this release:
 $ ./cardano-wallet-byron version
 2020.5.6 (git revision: cf3d9c91e895d1a01f90e4ab3d10b81e260b3510)
 
Here is the example (random Byron wallet):
 $ curl -X PUT http://localhost:8090/v2/byron-wallets/eb8dcd2ab76316a9d1396265c4a5d962992bf3b8/addresses/37btjrVyb4KERafEBA9ueNVE1nuuP5bLvf81LPf4DEnivffZU4qKKQTR5EujejBW4ifzRsUdUhxciLsK97tf3kfxEx3PsVCZgb8ebebhqQMPETR6gJ

Output:
{"code":"not_found","message":"I couldn't find the requested endpoint. If the endpoint contains path parameters, please ensure they are well-formed, otherwise I won't be able to route them correctly."}

**Comment by KtorZ** [comment]
This endpoint is only available since: c99ec255d736731da0c2efe917a7acb623a54963

So far, this hasn't been released.

**Comment by ntfreem** [comment]
Thank you @KtorZ any idea when this will be released?

**Comment by KtorZ** [comment]
_today_
