### ISSUE TITLE
Implement join/quitStakePool and delegation fee in Shelley

### ISSUE THREAD

**Issue by paweljakubas** [cardano-foundation/cardano-wallet#1709]
# Context

ADP-157

We would like to have an ability to join, and quit stake pool and check delegation fee in cardano-wallet-shelley.

# Decision

We will use `deriveRewardAccount` to get sks and then vsk (public key of sks) and treat it as stake key registration certificate. Then we will try to reuse mkUnsignedTx to make certificate registration and joining pool. We will not expose registrate/deregistrate certificate to the user. In detail, we will have three situations : 
1. User wants to join the pool (and is not registered) - so we register him and join at once.
2. User want to rejoin - here tx will have join component only (or we can in the first approach send both registration and joining as in point 1 - even if it means additional costs)
3. User want to quit - here tx will have deregister component only
 In this task we are interested in point 1 and 2. Point 3 is going to be next task within the milestone.
4. User want to check the cost of delegation

# Acceptance Criteria

1. `joinStakePool` endpoint works
2. `quitStakePool` endpoint works
3. `delegationFee` endpoint works
2. Integration tests illustrating the correctness are added

---

# Development 

# QA 

see endpoint in shelley plus integration tests added in (please notice that at the time of doing listStakePools was not implemented and we hardcoded pool id from cluster associated with integration tests) `lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs`

**Comment by piotr-iohk** [comment]
@paweljakubas I am not able to join stake-pool that is on Shelley testnet. They all seem to give me 404.

To reproduce:
1. start cardano-node + cardano-wallet on testnet.
e.g.:
cardano-node:
```
nix-build -A scripts.ff.node -o ff-node-local && ./ff-node-local
```

cardano-wallet-shelley:
```
cardano-wallet-shelley serve --port 8090 \
	--node-socket /path/to/node.socket  \
	--testnet /nix/store/v8lb35176p73f6ksp7p5rhkqmygi1zj9-ff-genesis.json \
        --database ./testnet-ff
```

2. Query stake pools registered on testnet:
```
CARDANO_NODE_SOCKET_PATH=/path/to/node.socket cardano-cli shelley query stake-distribution --testnet-magic 42
```
:point_down: 
```
                           PoolId                                 Stake frac
------------------------------------------------------------------------------
0087ac2efc783ae2aff9edc9ddb7f4a1d892ecb2041c12d30dc21b6c2971c3c9   3.322e-3
0339178e51ed42556f18d049f22c33dbd9040918deade0a73e93c5473fee693f   1.617e-2
04247e8aa8c81b82122dc181530385e678430d75a8eab9a9e89e6c25e763f84f   1.277e-2
07e84e8b8ca95cf005e7ee9cb1b45ee4ef4cdb5bcd87fdcbae664c46059f8f21   2.923e-4
0882955f4906bc49cb9b384fc99c897a4d87eda857a104c931a4ab854da56e4a   7.726e-3
08c58b891548cbd638d9eed86202e9dff17b807dba699cf7ae27276128e205e1   1.458e-4
...
```
3. Try to join a pool using one of the pool ids:

```
curl  -vX PUT http://localhost:8090/v2/stake-pools/0087ac2efc783ae2aff9edc9ddb7f4a1d892ecb2041c12d30dc21b6c2971c3c9/wallets/780ff96efa32aa3646b442b6c1b0e9a48c3b55c6 \
  -H "Content-Type: application/json; charset=utf-8" \
  -d '{
"passphrase": "Secure Passphrase"
}' --http1.1  |  jq
```
:point_down: 

```
{
  "code": "no_such_pool",
  "message": "I couldn't find any stake pool with the given id: 0087ac2efc783ae2aff9edc9ddb7f4a1d892ecb2041c12d30dc21b6c2971c3c9"
}

```

**Comment by piotr-iohk** [comment]
OK, misunderstood comment `please notice that at the time of doing listStakePools was not implemented and we hardcoded pool id from cluster associated with integration tests)`.  I thought it is only valid in the integration tests "realm". Ok, I understand we need to have list stake pools implemented in order to be able to join/quit actually...

So leaving in QA for the time being to be able to do e2e testing later.

**Comment by KtorZ** [comment]
@piotr-iohk I think this is now visible from integration tests :+1:

**Comment by piotr-iohk** [comment]
LGTM.
