### ISSUE TITLE
List id and stake of pools

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#1718]
# Context
We want to implement this endpoint for (the cardano-node-) Shelley.
https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/listStakePools

There is a `LocalStateQuery` command to [`GetStakeDistribution`](https://github.com/input-output-hk/ouroboros-network/blob/e24f14f837d3ea4ee1942121ecdb4a4169a8df99/ouroboros-consensus-shelley/src/Ouroboros/Consensus/Shelley/Ledger/Ledger.hs#L313-L314). Although this returns the stake as a fraction, not in real ada.

# Decision

- Use `GetStakeDistribution` list stake pools, providing their id and stake, as a first step. Other fields may be omitted or use dummy values.

# Acceptance Criteria

- [ ] API and CLI must be able to list stake pools
- [ ] the `id` field must be correct
- [ ] the `controlled_stake` field must be correct
- [ ] the `saturation` field _may_ be implemented

---

# Development 

- [ ] Can we get the total stake, or would it be acceptable to use the fractional stake we have?

# QA 

- See https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs#L443-L559

**Comment by piotr-iohk** [comment]
lgtm
