### ISSUE TITLE
Margin, cost & pledge for pools

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#1719]
# Context

We want to implement this endpoint for (the cardano-node-) Shelley.
https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/listStakePools

Pool margin and cost cannot be retrieved through the node's local state query.

# Decision

It seems we have to traverse the chain for pool registration certificates, to get this data?

# Acceptance Criteria

- Stake pool `margin` must be available in API (and CLI)
- Stake pool `cost` must be available in API (and CLI)
- Stake pool `pledge` must be available in API (and CLI)

---

# Development 

# QA 

- See https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/listStakePools

- And https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs#L464-L496

**Comment by Anviking** [comment]
Superseded by #1761

**Comment by Anviking** [comment]
That ticket seems more about the writing of it, so re-opening this for the reading-aspect.

**Comment by piotr-iohk** [comment]
lgtm
