### ISSUE TITLE
Recovering a Cardano-SL wallet

### ISSUE THREAD

**Issue by got3nks** [cardano-foundation/cardano-wallet#1730]
We had originally created a wallet in Cardano-SL using a 24 words seed.

```
$postData = json_encode(array(
    'backupPhrase' => explode(" ", $this->walletSeed),
    'assuranceLevel' => 'strict',
    'name' => '.... ',
    'operation' =>  'create'
));
$res = $this->rpc->post('/api/v1/wallets', $postData);
```

When trying to restore the wallet in the new cardano-wallet using:

```
curl -X POST http://127.0.0.1:8090/v2/byron-wallets \
-H "Content-Type: application/json" \
-d '{
"style": "random",
"name": "....",
"passphrase": "....",
"mnemonic_sentence": [....]}'
```

This is the error:
**{"code":"bad_request","message":"Error in $['mnemonic_sentence']: Invalid number of words: 12 words are expected."}**

Trying with the first 12 words only:
**{"code":"bad_request","message":"Error in $['mnemonic_sentence']: Found an unknown word not present in the pre-defined dictionary. The full dictionary is available here: https://github.com/input-output-hk/cardano-wallet/tree/master/specifications/mnemonic/english.txt"}**

**Comment by KtorZ** [comment]
The API currently enforces 12-word indeed, although there's no technical limitation to this. It is more of a convention on Byron / Daedalus wallets. Yet indeed, the V1 API didn't have any limitation in place regarding the length of recovery phrases; We could relax this a bit.

**Comment by got3nks** [comment]
> The API currently enforces 12-word indeed, although there's no technical limitation to this. It is more of a convention on Byron / Daedalus wallets. Yet indeed, the V1 API didn't have any limitation in place regarding the length of recovery phrases; We could relax this a bit.

If we are not able to restore our wallet the only option is to create a new one and move all the funds. But deposit addresses given to customers will cease to work, which is not ideal.

After the hard fork, will we be able to use the old Cardano-SL wallet to move funds to the new wallet generated with Cardano-wallet?

**Comment by KtorZ** [comment]
> After the hard fork, will we be able to use the old Cardano-SL

No.

**Comment by KtorZ** [comment]
@got3nks we've added the item to our backlog. So expect the cardano-wallet v2 API to accept mnemonics from 9 to 24 words in a near future. We have a few items to go through regarding Shelley first, but we'll try to get this done in-between some other tasks as this is pretty straightforward.

**Comment by got3nks** [comment]
I hope it will be possible before the hard fork, so we can gracefully switch to the new version.
Also I seem to get error **Found an unknown word not present in the pre-defined dictionary. The full dictionary is available here**, can this check be disabled and use any word? Because I guess we would have the same issue and be unable to restore our wallet.

**Comment by KtorZ** [comment]
> I hope it will be possible before the hard fork

Definitely yes. 

>  can this check be disabled and use any word?

Nope. The mnemonic sentence are encoding bytes by group of 11 bits, where each group correspond to an index which maps to a specific word in a 1024-word dictionary. So words in a mnemonic sentence are _well-known_.

**Comment by got3nks** [comment]
I see the issue has been closed.
Has this been solved in a recent / upcoming release? Thanks.

**Comment by KtorZ** [comment]
Sorry, I should mentioned: 

- This ticket is now superseded by https://github.com/input-output-hk/cardano-wallet/issues/1803
- PR implementing #1803 is landing into the master branch soon.

**Comment by got3nks** [comment]
I confirm we was able to restore our wallet using latest cardano-wallet Docker image.
