### ISSUE TITLE
cardano-wallet-shelley address CLI has import and create commands which are not supported for shelley wallets

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#1733]
# Context

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | `2020.6.5 (git revision: e37a43303fdbc7d1e7df4de07a1d0b498c1cfbc2)` |
| Platform     | Linux, all          |
| Installation | GH release / source           |

# Steps to Reproduce
```
# cardano-wallet-shelley address
Usage: cardano-wallet-shelley address COMMAND
  Manage addresses.

Available options:
  -h,--help                Show this help text

Available commands:
  list                     List all known addresses of a given wallet.
  create                   Create a new random address. Only available for
                           random wallets. The address index is optional, give
                           none to let the wallet generate a random one.
  import                   Import a random address generated elsewhere. Only
                           available for random wallets. The address must belong
                           to the target wallet.
```

## Expected behavior

cardano-wallet-shelley address should not have `create` and `import` as these are for byron wallets.

## Actual behavior
 `cardano-wallet-shelley address list` points to shelley wallets, so having `create` and `import` which are byron specific is misleading.

Trying to invoke "create" or "import" in cardano-wallet-shelley CLI results in error:
```
cardano-wallet-shelley: user error (feature unavailable.)
```

---

# Resolution 

---

# QA

**Comment by KtorZ** [comment]
Moved to: https://jira.iohk.io/browse/ADP-613
