### ISSUE TITLE
 Tx fee estimation is off when tx amount approaches wallet's balance

### ISSUE THREAD

**Issue by johnalotoski** [cardano-foundation/cardano-wallet#1740]
# Context

1) When calculating a transaction fee, if the amount to pay is set to the same value as the wallet holds (in a single address in this test case) or close to it, the TX fee is about as large as the wallets value.  This likely has no functional impact as it looks like these TXs should fail anyway due to insufficient fee ADA.  But in case it impacts something somewhere else, just FYI.

2) Network discrimination for the send to address is not tested for when calculating fees.  This might be by design and not an issue.  Just FYI

| Information  | -  |
| --- | --- 
| Version      |  2020.6.5 (git revision: 5290acf902da32e1e541b5dc227629c9a300f1be) |
| Platform     | Linux |
| Installation | Nix build |

# Steps to Reproduce

1) Check the wallet balance
```
$ cardano-wallet-shelley wallet get $WALLETID
...
        "total": {
            "quantity": 99627083,
            "unit": "lovelace"
        },
        "available": {
            "quantity": 99627083,
            "unit": "lovelace"
        }
...
```

2) Estimate fees by CLI or API:
```
# Set the payment about ~0.13 ADA lower than the wallet value; get a large estimated fee
#
$ cardano-wallet-shelley transaction fees $WALLETID --payment 99500000@$SEND_TO
Ok.
{
    "estimated_min": {
        "quantity": 99665281,
        "unit": "lovelace"
    },
    "estimated_max": {
        "quantity": 99665281,
        "unit": "lovelace"
    }
}

# Set the payment about ~1.13 ADA lower than the wallet value; get an accurate fee
#
$ cardano-wallet-shelley transaction fees $WALLETID --payment 98500000@$SEND_TO
Ok.
{
    "estimated_min": {
        "quantity": 168141,
        "unit": "lovelace"
    },
    "estimated_max": {
        "quantity": 168141,
        "unit": "lovelace"
    }
}
```

3) Perhaps not an issue, the network discriminator of the send to address doesn't appear to be checked during fee estimates.  Repeat one of the above fee estimates, this time flipping the second digit of the address from a `1` to a `0` or visa-versa.  The command completes the same way, successfully, despite one of those addresses not being valid on the network.
```
$ cardano-wallet-shelley transaction fees $WALLETID \
  --payment 99500000@$SEND_TO_WITH_MODIFIED_SECOND_DIGIT
Ok.
{
    "estimated_min": {
        "quantity": 99665281,
        "unit": "lovelace"
    },
    "estimated_max": {
        "quantity": 99665281,
        "unit": "lovelace"
    }
}
```

## QA

- Moved the logic handling the special edge case down the wallet engine so that it's easier to see what's going on.

- Added a unit test to capture this regression, failed before patch and succeed after the patch: https://github.com/input-output-hk/cardano-wallet/blob/master/lib/shelley/test/unit/Cardano/Wallet/Shelley/TransactionSpec.hs#L125-L142

**Comment by piotr-iohk** [comment]
Indeed, I am able to reproduce it for both: shelley and byron wallet. The boundary value (on Shelley testnet) seems to be `165281` lovelace.

I.e.
Where value is the amount for which you want to estimate fee:
If (value <= wallet_balance - 165281) then :+1: 
if (value > wallet_balance - 165281) then :-1: 

**For instance:**
wallet balance = 5 000 000

1. Estimate fee for 5000000−165281 = 4834719
    result: `165281 lovelace` (estimated_min and estimated_max)

2. Estimate fee for 5000000−16528**0** = 4834720
    result: `5000001 lovelace` (estimated_min and estimated_max)

**Comment by piotr-iohk** [comment]
lgtm
