### ISSUE TITLE
Required wallet DB fields do not get persistently added

### ISSUE THREAD

**Issue by johnalotoski** [cardano-foundation/cardano-wallet#1743]
# Context

After creating a wallet using the `cardano-wallet-shelley create from-mnemonic $NAME` command, each restart of cardano-wallet server shows the following messages in the logs:

```
[cardano-wallet.wallet-db:Info:4] [$DATETIME] Found existing wallet: $WALLETID
[cardano-wallet.wallet-db:Notice:16] [$DATETIME] wallet table does not contain required field 'passphrase_scheme'. Adding this field with a default value of "EncryptWithPBKDF2".
[cardano-wallet.wallet-db:Notice:16] [$DATETIME] rnd_state_address table does not contain required field 'account_ix'. Adding this field with a default value of 2147483648.
```

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | 2020.6.5 (git revision: 5290acf) |
| Platform     | Linux    |
| Installation | Nix build |

# Steps to Reproduce

1. Run the cardano-wallet shelley daemon
2. Create a shelley wallet using `from-mnemonic`.
3. Check the cardano-wallet daemon logs.
4. Restart cardano-wallet daemon.
5. Check the logs for the same wallet id and db messages again.

Wiping the cardano-wallet db and repeating does not resolve.

There appears to be no functional impact to this issue -- at least for what I'm doing.

## Expected behavior

The required table values would persist after the first table addition and respective messages in the log would stop after the first time.

**Comment by KtorZ** [comment]
Moved to: https://jira.iohk.io/browse/ADP-612
