### ISSUE TITLE
Sync percentage seems to be off on Shelley testnet

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#1749]
# Context

Observed when the network block height on Shelley testnet was ~17900 and I have a wallet and node that was syncing from scratch. Here's what it was showing on different levels of height (for both, wallet's sync progress, and sync progress reported on /network/information):
network block height = ~17900.
local block height = 11412, sync progress = 7.83%
local block height = 12688, sync progress = 10.53%
local block height = 15063, sync progress = 19.88%
local block height = 15820, sync progress = 26.16%
local block height = 16855, sync progress = 43.02%
local block height = 17744, sync progress = 80.83%
local block height = 17900, sync progress = 100%

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | 2020.6.5 (git revision: 4cd2ce655fa9e0163d2389759519445bcb52f47b) |
| Platform     | Linux, all?         |
| Installation | From source          |

# Steps to Reproduce

1. start cardano-wallet-shelley and cardano-node connected to shelley testnet
2. Observe syncing from scratch

## Expected behavior

E.g. 11412 / 17900 = ~63%... shows 7.83%

## Actual behavior
 
network block height = ~17900.

local block height = 11412, sync progress = 7.83%
local block height = 12688, sync progress = 10.53%
local block height = 15063, sync progress = 19.88%
local block height = 15820, sync progress = 26.16%
local block height = 16855, sync progress = 43.02%
local block height = 17744, sync progress = 80.83%
local block height = 17900, sync progress = 100%

---

# Resolution 

---

# QA

**Comment by piotr-iohk** [comment]
**Note also:**

Also noticed that `network/information`  is a bit "behind". I had my wallets already showing status "ready" and block height being "up-to-date", say 17900, and `network/information` was still showing lower block height, e.g. 17852 and sync progress ~90%.

**Comment by Anviking** [comment]
FYI @piotr-iohk, #1901 changed the sync percentage calculation

**Comment by piotr-iohk** [comment]
I don't see this behavior on current testnet. Closing.
