### ISSUE TITLE
Get reward account balance

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#1750]
# Context

Jira ticket: [ADP-302](https://jira.iohk.io/browse/ADP-302)

### User Story

> As a user, I want to check the rewards I have currently accumulated
>
> Given my wallet is in sync
>
> And I have the public key
> 
> Or I have the mnemonic 
>
> Then I can check the current delegation certificates

### Overview

The delegation rewards balance is shown as part of the shelley wallet balance in the API.

This task is to implement the function in the shelley network layer which queries the cardano-node backend for the reward account balance.

There is some overlap with [ADP-301 Check current delegation preference](https://jira.iohk.io/browse/ADP-301) because the same cardano-node query method is used.

# Decision

The wallet rewards address is already known. It is passed as the parameter to this network layer method.

```haskell
getAccountBalance
    :: NetworkLayer IO (IO Shelley) ShelleyBlock
    -> ChimericAccount
    -> ExceptT ErrGetAccountBalance m (Quantity "lovelace" Word64)
```

The shelley implementation of this method should use the node local state query protocol to get the stake address info.

A model for this could be the `cardano-cli shelley query stake-address-info` command. Its implementation is in `Cardano.Api.LocalStateQuery.queryDelegationsAndRewardsFromLocalState` (`cardano-node` repo / `cardano-api` package).

The `ChimericAccount` address must be converted to a shelley stake credential.

In the shelley network layer, create a queue of `LocalStateQueryCmd ShelleyBlock GetFilteredDelegationsAndRewardAccounts`

```haskell
-- cardano-wallet-shelley
data LocalStateQueryCmd block state (m :: * -> *)
    = CmdQueryLocalState
        (Point block)
        (Query block state)
        (LocalStateQueryResult state -> m ())

-- ouroboros-consensus-shelley
-- Ouroboros.Consensus.Shelley.Ledger.Ledger
instance TPraosCrypto c => QueryLedger (ShelleyBlock c) where
  data Query (ShelleyBlock c) :: Type -> Type where

    -- ...

    GetFilteredDelegationsAndRewardAccounts
      :: Set (SL.Credential 'SL.Staking c)
      -> Query (ShelleyBlock c) (Delegations c, SL.RewardAccounts c)
```

In `mkWalletClient`, add a local state query protocol which handles the reward account query commands. The block queried is tip of the wallet's chain sync protocol.

# Acceptance Criteria

1. Network layer `getAccountBalance` method _must_ return the rewards balance of the wallet (if it is synced).

---

# Development 

- PR implementing plan above ⇒ #1752

# QA 

1. There is an integration test `STAKE_POOLS_JOIN_04 - Rewards accumulate and stop` to cover:

    - rewards flow once stake is delegated
    - rewards cease after delegation has stopped

    ~However the test case is pending until we have stake pool nodes working in the integration test cluster.~

**Comment by piotr-iohk** [comment]
lgtm. However cannot really see if rewards stop due to "Can't quit pools when reward account is non-empty #1824". Also for that matter I suppose the part of the test `STAKE_POOLS_JOIN_04 - Rewards accumulate and stop` is commented out.( https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs#L304)

**Comment by rvl** [comment]
@piotr-iohk Thanks, yes the STAKE_POOLS_JOIN_04 scenario is testing multiple things. The "rewards accumulate" part applies to this user story ADP-302. The "rewards stop" part is blocked by #1824 - I added a note there.
