### ISSUE TITLE
Extract stake pool registration from on-chain data

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1761]
# Context

As a wallet user I want to Check stakepool metadata so that I can make an informed delegation choice.

Stake pool metadata are registered on chain inside stake pool registrations alongside some interesting data like the margin, cost or pledge amount. These registrations can be parsed and the information inside them extracted as we crawl the chain so that we can access it later.

# Decision

- Parse on-chain data and store stake-pool registration certificates in the stake pool database
- Also parse and store metadata details so that they can be fetched from remote servers in a separate worker (see other task)

# Acceptance Criteria

- Pool registrations present on-chain are captured and stored in a dedicated database
- Pool metadata details are also stored and queued but not yet fetched.

---

# Development 

- #1763 

# QA 

- This is relatively hard to test in _isolation_ because to get proper testing, we need to somehow simulate a blockchain with registration and simulate interesting cases. Ultimately, we'll be able to confirm that this works as intended with e2e tests in the integration scenarios, although we need to finalize stake pools listing first (see #1769)

- The PR piggy-back on existing tables and interfaces developed for the ITN, and tests written at this time still apply:
    - https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Cardano/Pool/DB/Properties.hs#L441-L462
    - https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Cardano/Pool/DB/Properties.hs#L408-L439   
    - https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Cardano/Pool/DB/Properties.hs#L389-L406

**Comment by piotr-iohk** [comment]
lgtm
