### ISSUE TITLE
Collect stake pool metadata from remote servers

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1762]
# Context

While SMASH is being developed, we'll be fetching metadata directly from their remote URL, caching the content in another database.

# Decision

- Fetch metadata from _URL_ and persist the content
- Remove from the queue metadata successfully fetched
- Have a rather short timeout to prevent one server from slowing down the entire service.
- Make fetching the metadata decoupled from the rest, so we can easily swap _how_ metadata are fetched once smash is ready.

# Acceptance Criteria

---

# Development 

- #1776 

# QA 

- As for #1761, combining database information with the LSQ is going to be needed to fully test this e2e. However, this is already visible from the logs:

```
[cardano-wallet.pools-engine:Info:192] [2020-06-18 13:12:14.36 UTC] Taking a little break from fetching metadata, back to it in about 0.2s
[cardano-wallet.pools-engine:Info:190] [2020-06-18 13:12:14.36 UTC] Applying blocks [0.0 ... 0.0]
[cardano-wallet.pools-engine:Info:190] [2020-06-18 13:12:14.36 UTC] Applying blocks [0.12 ... 2.0]
[cardano-wallet.pools-engine:Info:190] [2020-06-18 13:12:14.36 UTC] Discovered stake pool registration: Registration of c7258ccc owned by [ed25519_pk1va7rf7f7p097545q8nplgwz98n7x70zk0qm8vhfx3q2apedlt7fsrttw4c]
[cardano-wallet.pools-engine:Info:190] [2020-06-18 13:12:14.37 UTC] Discovered stake pool registration: Registration of 775af3b2 owned by [ed25519_pk1nl63hryqlfljan9046ztd6ejgfersnzevk6cvy2rlkr2npkmdvcqvezqk6]
[cardano-wallet.pools-engine:Info:190] [2020-06-18 13:12:14.37 UTC] Discovered stake pool registration: Registration of 5a7b67c7 owned by [ed25519_pk1vyvapw37ywgugefz0cl9580272w5399m4u4d74mgrwu7st5dd20qsgg22z]
[cardano-wallet.pools-engine:Info:192] [2020-06-18 13:12:14.56 UTC] Fetching metadata for pool c7258ccc from http://localhost:34159/metadata.json
[cardano-wallet.pools-engine:Info:192] [2020-06-18 13:12:14.56 UTC] Successfully fetched metadata for pool c7258ccc: StakePoolMetadata {ticker = StakePoolTicker {unStakePoolTicker = "GPA"}, name = "Genesis Pool A", description = Nothing, homepage = "https://iohk.io"}
[cardano-wallet.pools-engine:Info:192] [2020-06-18 13:12:14.57 UTC] Fetching metadata for pool 775af3b2 from http://localhost:40195/metadata.json
[cardano-wallet.pools-engine:Info:192] [2020-06-18 13:12:14.57 UTC] Successfully fetched metadata for pool 775af3b2: StakePoolMetadata {ticker = StakePoolTicker {unStakePoolTicker = "GPB"}, name = "Genesis Pool B", description = Nothing, homepage = "https://iohk.io"}
[cardano-wallet.pools-engine:Info:192] [2020-06-18 13:12:14.57 UTC] Fetching metadata for pool 5a7b67c7 from http://localhost:45173/metadata.json
[cardano-wallet.pools-engine:Info:192] [2020-06-18 13:12:14.57 UTC] Successfully fetched metadata for pool 5a7b67c7: StakePoolMetadata {ticker = StakePoolTicker {unStakePoolTicker = "GPC"}, name = "Genesis Pool C", description = Just "Lorem Ipsum Dolor Sit Amet.", homepage = "https://iohk.io"}
```

NOTE: I've adapted the integration test cluster so that each pools in the cluster would register itself with metadata and automatically starts a local web-server to serve the metadata as a JSON object (very much like SMASH would do). So, what these logs are showing are:

a) That the integration setup works as intended; we can see that metadata are fetched from various URL (albeit on localhost). 
b) That the client fetching metadata also works as intended. The client do validate metadata hash and check that metadata are somewhat wellf-formed.
c) The wiring between metadata discovery & fetching works correctly. Nothing's hard-coded here and metadata are indeed fetched based on certificate discovered on-chain

I've also manually tested what happens when a server doesn't reply or when metadata served on a URL are invalid (the client correctly handles that, a warning is logged and so far, the client retry later).

- The worker fetching metadata will automatically retry invalid entries every next _block_ (it uses the active slot coefficient and the slot length to calculate the right delay). 

- I've however testing independent constituents of the PR, in particular the database functions (especially since they use raw SQL queries :grimacing:) https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Cardano/Pool/DB/Properties.hs#L464-L501

**Comment by piotr-iohk** [comment]
lgtm
