### ISSUE TITLE
Error in $.protocolParams: key "minPoolCost" not found

### ISSUE THREAD

**Issue by Fell-x27** [cardano-foundation/cardano-wallet#1770]
# Context
 
 

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      |Last master (17.06.2020) |
| Platform     | Linux        |
| Installation | From Source?       |

# Steps to Reproduce

Just trying to launch with:

`cardano-wallet-shelley serve --listen-address 127.0.0.1 --port 8090 --node-socket /path/to/socket --database ./shelley-wallets --sync-tolerance 300s --testnet /path/to/ff-genesis.json`

## Expected behavior
Connetcting to a node, fetching transactions etc.

## Actual behavior
 
```
[cardano-wallet.main:Error:4] [2020-06-16 22:06:03.28 UTC] Failed to parse genesis configuration. You may want to check the filepath given via --genesis and make sure it points to a valid JSON genesis file. Here's (perhaps) some helpful hint: Error in $.protocolParams: key "minPoolCost" not found
[cardano-wallet.main:Debug:4] [2020-06-16 22:06:03.28 UTC] Logging shutdown.
```

Previously it worked as well. On the master branch from 11.06.2020.
genesis source is https://hydra.iohk.io/build/2883639/download/1/index.html

---

# Resolution 

---

# QA

**Comment by rvl** [comment]
Hi @Fell-x27, cardano-wallet master branch currently requires using the very latest cardano-node code. The ff testnet is running cardano-node 1.13.0. The genesis file on hydra will be updated when the next release of cardano-node is deployed to ff testnet. Even if you add the extra key to `ff-genesis.json` you will probably find that the node can't sync with ff testnet.

**Comment by Fell-x27** [comment]
Ok, Will try to build the latest node, fix genesis.json and try again later!

**Comment by rvl** [comment]
That will probably not be a successful endeavour. As far as I know, the current master branch cardano-node is not compatible with ff testnet. This should be sorted out in the coming week. We are testing cardano-wallet with local nodes for the time being.

**Comment by Fell-x27** [comment]
> the current master branch cardano-node is not compatible with ff testnet.

Yep... will try to build local shelley testnet.
