### ISSUE TITLE
Cannot submit transaction with POST /proxy/transactions

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#1774]
# Context

https://github.com/input-output-hk/cardano-wallet/pull/1766#issuecomment-644825477

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | `2020.6.5 (git revision: 00a46043ad37c0714986d33d08795e83d612c1fc)`|
| Platform     | Linux, all?         |
| Installation | From source          |

# Steps to Reproduce

Trying to re-play the [tutorial](https://github.com/input-output-hk/cardano-transactions/wiki/How-to-submit-transaction-via-cardano-tx-CLI) on Shelley testnet:

1. Source icarus wallet with 10ADA (`fit today convince mixture crumble design identify swim jelly charge vast expect below science stove`). 10 ADA being on "first" address of the wallet.

2. Get signing key:
```
echo "fit today convince mixture crumble design identify swim jelly charge vast expect below science stove" \
	| cardano-address key from-recovery-phrase icarus \
	| cardano-address key child 44H/1815H/0H/0/0 --base16
```
and save key in XPRV env variable:
```
export XPRV=783de8e633c29f81503f3a72053d82ee117d2526bc7486699b7a6ccfef996b5580cabebeb11c44233b3159bcf962ac56db6f5eb68277171c22b88b7f579ab38b1233bbc1f45472837b904b719db5d32d947ec521e7fccd1aec6ad6cf884fc458
```

3. Estimate fee:
```
$ cardano-wallet-byron transaction fees 761ddaf7760aaf9c98cd8956417760c4b7f2c656 --payment 1@2657WMsDfac6ivfhdAt33wmrS9PpYhtKi3jWcBduy7ecMRmE9dkPPMrzKnd9VE6e6
Ok.
{
    "estimated_min": {
        "quantity": 168141,
        "unit": "lovelace"
    },
    "estimated_max": {
        "quantity": 168141,
        "unit": "lovelace"
    }
}

```

4. Calculate change -> 10000000-168141 = **9831859**

5. Construct transaction:
```
cardano-tx empty 42 \
  | cardano-tx add-input 1 91456e12a5944676647e0c3f7d6ed22daedbc4770abc940c9887705528a995be \
  | cardano-tx add-output 1 2657WMsDfac6ivfhdAt33wmrS9PpYhtKi3jWcBduy7ecMRmE9dkPPMrzKnd9VE6e6 \
  | cardano-tx add-output 9831859 2657WMsDfac6U62wnBwfX9oPzcyXxagZSBC7thfJFRJkEMMhBxiPBqMRCAhhnYc8A \
  | cardano-tx lock \
  | cardano-tx sign-with $XPRV \
  | cardano-tx serialize --base16
```

6. Try to send over:
```
BLOB=82839f8200d818582482582091456e12a5944676647e0c3f7d6ed22daedbc4770abc940c9887705528a995be01ff9f8282d818582583581c9ecb495af2827bb6524939484fa63816d28832bbee61d7312d802dbfa10242182a001ab64ed263018282d818582583581c88115f4fc167e3a93f53bca2b6a5ef72df5e904efcef9c415bc439bda10242182a001a211ba8b31a009605b3ffa0818200d8185885825840b8cdd384ec1ef3dffe4db999d6bfce40afaa964543e2e1592c932f552fe9e8301233bbc1f45472837b904b719db5d32d947ec521e7fccd1aec6ad6cf884fc45858407c06b3249cb7d3c226126b4098e0f98b50a4f339bfc0f3b49852bdf5f66632f043b36388e09c68a73b75d511a29c8620c35934d9df8c9413c25fbac8aa2aef07

$ cardano-wallet-shelley transaction submit $BLOB
or
$ cardano-wallet-byron transaction submit $BLOB
```
:point_down: 
```
I couldn't verify that the payload has the correct binary format. Therefore I couldn't send it to the node. Please check the format and try again.
```

## Expected behavior

We should be able to submit transaction.

## Actual behavior
 
```
I couldn't verify that the payload has the correct binary format. Therefore I couldn't send it to the node. Please check the format and try again.
```

---

# Resolution 

---

# QA

**Comment by KtorZ** [comment]
@piotr-iohk the underlying binary format for transaction is different between Shelley and Byron. Unfortunately, cardano-transactions still lives in the _Byron_ era and therefore, produce transactions that can't be comprehended by the _shelley-only_ transaction layer.

**Comment by 1b1og-com** [comment]
any updater ?

**Comment by KtorZ** [comment]
@WEALLOVESRAM https://input-output-hk.github.io/cardano-wallet/api/edge/#tag/Proxy fully supports transactions from the Shelley era.
