### ISSUE TITLE
Final transaction fee - /v2/byron-wallets/transactions

### ISSUE THREAD

**Issue by ntfreem** [cardano-foundation/cardano-wallet#1778]
Please return the actual final fee that was used to send a tx, we can only figure that out by using the explorer API, and not when sending a tx using  cardano-wallet using POST /v2/byron-wallets/transactions

**Comment by KtorZ** [comment]
As mentioned on Slack: I am not 100% sure that this is necessary, since actual fees can be computed as the sum of the inputs amount minus the sum of the outputs amounts (which are both provided as part of the response already).
