### ISSUE TITLE
Get transaction by its id

### ISSUE THREAD

**Issue by paweljakubas** [cardano-foundation/cardano-wallet#1789]
# Context

I want to get information about a transaction based on an ID

# Decision

# Acceptance Criteria

1. the endpoint capable of doing that is added.
2. integration test illustrating transaction info lifecycle from valid id and invalid id behavior is added

---

# Development 

# QA 

A number of things were added in this task that are worth checking : 
1. getTx in DBlayer and corresponding property tests
2. get tx by id endpoint in wallets and byron-wallets family - here integration tests 
3. CLI support - here integration tests
4. swagger was updated

**Comment by piotr-iohk** [comment]
Looking good. I have added additional checks in integration tests for Byron wallets (API & CLI) in #1804. 

Also added tests for "get tx by id" into "nightly shelley testnet tests". (And hopefully fixed them to run -> https://github.com/piotr-iohk/cardano-wallet-rb/actions?query=workflow%3ANightly)

**Comment by piotr-iohk** [comment]
lgtm
