### ISSUE TITLE
cardano-wallet-shelley-linux64

### ISSUE THREAD

**Issue by lijianl** [cardano-foundation/cardano-wallet#1792]
I am using cardano-wallet-shelley-latest-release on Linux for a wallet service. when I start with './cardano-wallet serve'
it hits "Missing: --node-socket FILE --testnet FILE", where could I find these two files of mainnet? ; is it impossible to connect the mainet yet??

**Comment by lijianl** [comment]
i get a mainnet file from "https://hydra.iohk.io/build/3175192/download/1/mainnet-genesis.json";  
and the log shows this file is not JSON valid ??????/

what should I do to run Cardano-wallet on mainnet

**Comment by KtorZ** [comment]
For current mainnet, you'll need `cardano-wallet-byron` unfortunately. The transition to Shelley will happen soon but hasn't happened yet. The genesis file looks indeed correct for the current Mainnet chain. 

For further details, please follow the instructions in the command-line manual: https://github.com/input-output-hk/cardano-wallet/wiki/Wallet-command-line-interface-cardano-node#serve

**Comment by lijianl** [comment]
when I run with file "https://hydra.iohk.io/build/3175192/download/1/mainnet-genesis.json"; 
the log shows 'You may want to check the filepath given via --genesis and make sure it points to a valid JSON genesis file. Here's (perhaps) some helpful hint: Error in $: key "maxMajorPV" not found' 

and indeed for key "maxMajorPV" is not exist in the "mainnet-genesis.json"

**Comment by KtorZ** [comment]
`maxMajorPV` is a parameter required by the **Shelley** node. Please re-read my previous answer, you need `cardano-wallet-byron`, not `cardano-wallet-shelley`.
