### ISSUE TITLE
Wallet on new testnet fails with UNIQUE constraint failed: pool_registration.pool_id

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#1794]
# Context
 
Using:
- `shelley_testnet` https://hydra.iohk.io/job/Cardano/iohk-nix/cardano-deployment/latest/download/1/index.html
- cardano-node 1.14.0

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | a1db69e710d492e4297cdea4c4d8c73b47315495 |
| Platform     |           |
| Installation |             |

# Steps to Reproduce

1. `cardano-node run --database-path db --topology shelley_testnet-topology.json --socket-path socket --config shelley_testnet-config.json --port 7776`

2. `cardano-wallet-shelley serve --node-socket socket --testnet shelley_testnet-genesis.json --database wallet-db`

## Expected behavior

- Stake pool monitoring worker runs smoothly

## Actual behavior

After some second the worker panics:

```
[cardano-wallet.pools-engine:Info:30] [2020-06-24 15:32:16.17 UTC] Discovered stake pool registration: Registration of 3d51d7f3 owned by [ed25519_pk1yeq965dl9fg47us5n7nvts63gg0van60ahpf40qyjfec7xhdv8e]
[cardano-wallet.pools-engine:Info:30] [2020-06-24 15:32:16.18 UTC] Discovered stake pool registration: Registration of 31d6318b owned by [ed25519_pk170dxgh2evajf994s7t2cj4vszrnu7fvsk6xpay4gwt6y70hvgx7]
[cardano-wallet.pools-engine:Info:30] [2020-06-24 15:32:16.18 UTC] Discovered stake pool registration: Registration of 27e33e8d owned by [ed25519_pk178axspgs7ktsxk8d4xmrqh238p95gpthvwk5npd502t5gg5xv3g]
[cardano-wallet.pools-engine:Info:30] [2020-06-24 15:32:16.25 UTC] Applying blocks [0.20360 ... 1.18740]
[cardano-wallet.pools-engine:Info:30] [2020-06-24 15:32:16.25 UTC] Discovered stake pool registration: Registration of afd3cbad owned by [ed25519_pk1epdkas5l7t3nw0ntdhc30gd4hyl5eyz9qsr0ld4ar628gm26jdm]
[cardano-wallet.pools-engine:Info:30] [2020-06-24 15:32:16.25 UTC] Discovered stake pool registration: Registration of a26e7dda owned by [ed25519_pk1kwec9hx9kdc0letk656vzruwnpv5anlv4peg3243zkjzgxjtugq]
[cardano-wallet.pools-engine:Info:30] [2020-06-24 15:32:16.25 UTC] Discovered stake pool registration: Registration of a28777a9 owned by [ed25519_pk1pr54apu5y8tyep9hwkmrjnvaq4nqpg5c53jawqt9u8ez2x99ark]
[cardano-wallet.pools-engine:Info:30] [2020-06-24 15:32:16.25 UTC] Discovered stake pool registration: Registration of 75e8e314 owned by [ed25519_pk1kd5d8uqfeczkt76mhj48fnuwt742tqk9c2mqw6ncd899vycs7f2]
[cardano-wallet.pools-engine:Info:30] [2020-06-24 15:32:16.25 UTC] Discovered stake pool registration: Registration of 0e26f399 owned by [ed25519_pk1p27gndmwhhvsfgwez35277xxmxjc80j6llj9g24j4kyas9px96a]
[cardano-wallet.pools-engine:Info:30] [2020-06-24 15:32:16.26 UTC] Discovered stake pool registration: Registration of b71e0990 owned by [ed25519_pk1gd8kwve0zvkzwh2kx8d392zsxn9d9y98qvanepktn69rwha7n9k]
[cardano-wallet.pools-engine:Info:30] [2020-06-24 15:32:16.26 UTC] Discovered stake pool registration: Registration of 6a5a084f owned by [ed25519_pk1xj60dwz38smunrfmpxynf5lj8xjsklgh2lq9ayvcpvs7wqlt4pv]
[cardano-wallet.pools-engine:Info:30] [2020-06-24 15:32:16.26 UTC] Discovered stake pool registration: Registration of 31d6318b owned by [ed25519_pk170dxgh2evajf994s7t2cj4vszrnu7fvsk6xpay4gwt6y70hvgx7]

[cardano-wallet.pools-engine:Error:30] [2020-06-24 15:06:34.17 UTC] Unexpected error following the chain: SQLite3 returned ErrorConstraint while attempting to perform step: UNIQUE constraint failed: pool_registration.pool_id
```
Notice the duplicate registration of `31d6318b`.
 

---

# Resolution 

- Allow for re-registration by tweaking the primary key for pools registration ==> #1798 

---

# QA 

- Redoing reproduction steps now succeeds and wallet can correctly sync on shelley testnet

**Comment by KtorZ** [comment]
@Anviking a first clue which is something I suspected this morning when you talked about it. 

- The pool monitoring worker uses the last `X` block headers to compute an intersection where `X` is `max k 100` (wrongly copied over from the ITN code...)

- The genesis configuration specifies `securityParam: 108` 

This means that, if a node switches to a chain that has between 100 and 108 blocks difference, the worker won't find any intersection and will resync from genesis, trying to apply a block that it can't apply. I think that might be the source cause of :point_up:

**Comment by Anviking** [comment]
This is a different bug.

>  compute an intersection where X is max k 100

I tried removing the `max 100`, but it didn't work. Besides, I used an empty DB.

I looked at the logs again: and it seems `31d6318b` is registering twice. (edited ticket). I suspect re-registration _is_ allowed after all 🤔

**Comment by KtorZ** [comment]
>  re-registration

It's not allowed for stake key surely. But for stake pools, that is indeed a possibility? Can you find the answer?

**Comment by Anviking** [comment]
Yes, confirmed.

**Comment by piotr-iohk** [comment]
Here's what I see in the log:
```
[cardano-wallet.network:Info:29] [2020-06-24 17:02:55.25 UTC] Intersection found: 01010101
[cardano-wallet.pools-engine:Info:29] [2020-06-24 17:02:55.25 UTC] Applying blocks [0.340 ... 0.340]
[cardano-wallet.pools-engine:Info:29] [2020-06-24 17:02:55.29 UTC] Applying blocks [0.360 ... 0.20340]
[cardano-wallet.pools-engine:Info:29] [2020-06-24 17:02:55.31 UTC] Discovered stake pool registration: Registration of 3d51d7f3 owned by [ed25519_pk1yeq965dl9fg47us5n7nvts63gg0van60ahpf40qyjfec7xhdv8e]
[cardano-wallet.pools-engine:Error:29] [2020-06-24 17:02:55.31 UTC] Unexpected error following the chain: ISRManyKeys: unexpected keyvals result: Couldn't parse field `poolRegistrationPoolId` from table `pool_registration`. not a valid value: Invalid stake pool id: expecting a hex-encoded value that is 32 bytes in length.
CallStack (from HasCallStack):
  error, called at ./Database/Persist/Sql/Orphan/PersistStore.hs:197:48 in persistent-2.10.2-eA1qXZfXzoKTlOKK2a1uS:Database.Persist.Sql.Orphan.PersistStore
[cardano-wallet.network:Notice:29] [2020-06-24 17:02:55.31 UTC] Destroying cursor connection at ThreadId 30
[cardano-wallet.pools-engine:Error:29] [2020-06-24 17:02:55.31 UTC] Chain follower exited with error. Worker will no longer monitor stake pools.
```

**Comment by KtorZ** [comment]
@piotr-iohk you need the 1.14.0 branch to get the correct hash lengths.

**Comment by piotr-iohk** [comment]
I was on cardano-node `1.14.0` and cardano-wallet `anviking/bump-node-1.14.0` - but the latter was not up-to-date. After updating cardano-wallet I get the same error indeed :man_shrugging:

**Comment by piotr-iohk** [comment]
lgtm. I don't see that on shelley testnet any longer.
