### ISSUE TITLE
Conflicting pool production

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#1796]
# Context
 
 

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      |  |
| Platform     |           |
| Installation |             |

# Steps to Reproduce

Haven't managed to reproduce yet. Think I saw it multiple times when tweaking genesis params when running integration tests.

## Actual behavior

Sometimes: 

<img width="764" alt="ska__rmavbild_2020-06-22_kl _14 31 29" src="https://user-images.githubusercontent.com/304423/85590221-83978c80-b644-11ea-86a2-6d76b1f59c51.png">
 

---

# Resolution 

- After investigation (see below), we've identified the root cause of the issue and changed the approach in the chain follower to cope with the issue. See #1808

---

# QA 

- Testing this thoroughly is quite delicate as it would require "manipulating" the chain in such way that this particular edge-case would be met. This however touches the very core of the chain following function, which is used by all three byron, jormungandr and shelley versions -- and integrations tests still pass. 

- I wasn't able to reproduce or re-observe on the shelley testnet after the fix. It is probably best to keep this ticket open a little while until we feel confident about this issue being gone,

**Comment by Anviking** [comment]
I see a lot of these errors on #1783 where activeSlotCoeff is increased, and d decreased.
```
[cardano-wallet.pools-engine:Info:235] [2020-06-26 14:51:21.54 UTC] Applying blocks [3.92 ... 3.92]
[cardano-wallet.pools-engine:Info:235] [2020-06-26 14:51:21.73 UTC] Applying blocks [3.93 ... 3.93]
[cardano-wallet.pools-engine:Info:252] [2020-06-26 14:51:21.76 UTC] Taking a little break from fetching metadata, back to it in about 0.4s
[cardano-wallet.pools-engine:Info:235] [2020-06-26 14:51:21.80 UTC] Applying blocks [3.93 ... 3.93]
[cardano-wallet.pools-engine:Error:235] [2020-06-26 14:51:21.80 UTC] Couldn't store production for given block before it conflicts with another block. Conflicting block header is: 57c080cb<-[7fe787a4-3.93#191]
```
Despite seeing many errors, I see no rollbacks, which is interesting.

**Comment by Anviking** [comment]
When adding a more low-level `ChainSyncLog`:
```
[cardano-wallet.network:Info:239] [2020-06-26 17:08:41.41 UTC] ChainSync roll forward: (slotNo 254, 270dadbe)
[cardano-wallet.pools-engine:Info:231] [2020-06-26 17:08:41.41 UTC] Applying blocks [2.54 ... 2.54]
[cardano-wallet.network:Info:239] [2020-06-26 17:08:41.46 UTC] ChainSync roll backward: (slotNo 253, 0593cf2b)
[cardano-wallet.network:Info:239] [2020-06-26 17:08:41.46 UTC] ChainSync roll forward: (slotNo 254, 162fdb44)
[cardano-wallet.pools-engine:Info:231] [2020-06-26 17:08:41.46 UTC] Applying blocks [2.54 ... 2.54]
[cardano-wallet.pools-engine:Error:231] [2020-06-26 17:08:41.46 UTC] Couldn't store production for given block before it conflicts with another block. Conflicting block header is: 0593cf2b<-[162fdb44-2.54#72]
```
Seems like the abstractions that sit on top of the chain sync doesn't correctly notice the rollback.

**Comment by KtorZ** [comment]
@Anviking do you have the list of blocks given for intersection?

**Comment by Anviking** [comment]
Adding more tracing inside `follow`:
```
[cardano-wallet.network:Info:239] [2020-06-26 17:38:53.69 UTC] ChainSync roll forward: (slotNo 245, 1c5d398e)
[cardano-wallet.pools-engine:Info:231] [2020-06-26 17:38:53.69 UTC] Applying blocks [2.45 ... 2.45]
[cardano-wallet.network:Info:239] [2020-06-26 17:38:53.73 UTC] ChainSync roll backward: (slotNo 243, c9fff680)
[cardano-wallet.pools-engine:Info:231] [2020-06-26 17:38:53.73 UTC] follow: Ignoring rollback to 2.43 because of cps empty
[cardano-wallet.network:Info:239] [2020-06-26 17:38:53.73 UTC] ChainSync roll forward: (slotNo 245, 02556d8a)
[cardano-wallet.pools-engine:Info:231] [2020-06-26 17:38:53.73 UTC] Applying blocks [2.45 ... 2.45]
[cardano-wallet.pools-engine:Error:231] [2020-06-26 17:38:53.73 UTC] Couldn't store production for given block before it conflicts with another block. Conflicting block header is: c9fff680<-[02556d8a-2.45#61]
```
So problem should be here:
https://github.com/input-output-hk/cardano-wallet/blob/0243ac496dc395516ef18764a37d74df1785da46/lib/core/src/Cardano/Wallet/Network.hs#L394-L396

**Comment by Anviking** [comment]
> do you have the list of blocks given for intersection

Ah! `cps` is what was originally used to start the follower. So it seems all rollbacks are ignored in that case 😬

**Comment by KtorZ** [comment]
> So it seems all rollbacks are ignored in that case 

Right :facepalm:

**Comment by KtorZ** [comment]
I imagine we can work-around that by making that `cps` contains the latest block applied, passing it around to `step` and `sleep`.

**Comment by piotr-iohk** [comment]
Haven't observed for a while now. Closing.
