### ISSUE TITLE
Cannot join stake-pool on shelley_testnet

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#1799]
# Context

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | 55ffb6b4abcbc7f7ab15c60d2bc4b1c61208cfff `anviking/fix-pools-for-testnet`|
| Platform     | Linux        |
| Installation | From source           |

# Steps to Reproduce

https://hydra.iohk.io/job/Cardano/iohk-nix/cardano-deployment/latest/download/1/index.html

1. 
```
cardano-node run \
        --config /root/node/$type/*-config.json \
        --database-path /root/node/$type/db \
        --socket-path /root/node/$type/node.socket \
        --topology /root/node/$type/*-topology.json \
        --host-addr 127.0.0.1 \
        --port 3001}
```
```
cardano-wallet-shelley serve --port 8090 \
                --node-socket /root/node/$type/node.socket \
                --testnet /root/node/$type/*-genesis.json \
                --database /root/wallet/$type/db

```

2. Join stake-pool on shelley testnet with wallet having funds: (`fuel gentle purse blood bomb advice hundred vehicle maze special pull category smart control shallow`)

```
PUT http://localhost:8090/v2/stake-pools/1fd1450ad92fc024235e2bf908a9b178a6e13f2e653ff0dec5414c46/wallets/98ae2ce26143a126a19a2d47e60b539a596b4d2b
Body: {"passphrase":"Secure Passphrase"}
```
## Expected behavior

I can join.

## Actual behavior
 
```
Code = 500,
Message = {"code":"created_invalid_transaction","message":"That's embarrassing. It looks like I've created an invalid transaction that could not be parsed by the node. Here's an error message that may help with debugging: ApplyTxError [LedgerFailure (UtxowFailure (UtxoFailure (ValueNotConservedUTxO (Coin 994831859) (Coin 995231859))))]"}
```

---

# Resolution 

- Take stake key deposit into account when delegating and quitting delegation ==> #1806 

---

# QA 

- I've changed the genesis configuration to have a non-null key deposit (https://github.com/input-output-hk/cardano-wallet/blob/78074621d87f5a50c833693a38fc4e6aa1a885e6/lib/shelley/test/data/cardano-node-shelley/genesis.yaml#L34) which, as a result, caused most STAKE_POOLS integration scenarios to fail with a similar error to the above :point_up: 

- Taking key deposit into account fixes the scenarios nicely, with the exception of one scenario which required some extra "tweaking". With the approach used in #1806, it is necessary to have at least one change output in order to quit delegation. Said differently, the wallet will fail with a proper error if one tries to delegate with _just_ the amount necessary to pay to the fees. It'd works however if there's at least one lovelace of change after fee deduction. In practice, this should be fairly rarely encountered. 

- Also, the approach from #1806 is "simple" in the sense that it didn't require a lot of code changes. Yet, it won't survive a protocol update of the key deposit (which is very unlikely to happen _soon_) but, we need to make sure to have a ticket to tackle this with more resilience later (e.g. by looking up the original transaction that was used to make a deposit).

**Comment by KtorZ** [comment]
Seems like we are missing a required deposit needed when registering a stake key. This wasn't caught by our integration tests because the value for key deposit is set to `0` in our cluster genesis!

**Comment by piotr-iohk** [comment]
ok. Able to join/quit on shelley testnet.
