### ISSUE TITLE
Allow for different mnemonics for random/icarus wallets

### ISSUE THREAD

**Issue by paweljakubas** [cardano-foundation/cardano-wallet#1803]
# Context

As a wallet user (Byron random and Icarus wallets)
I want to be able to restore a wallet based on various mnemonic lengths
so that I restore from out of date wallets

# Decision

we will allow for [12,15,18,21,24] mnemonic lengths for random/icarus wallets

# Acceptance Criteria

1. different mnemonic lengths are accepted 
2. the tests illustrating the case are added

---

# Development 

# QA 

So now random and icarus accepts mnemonics of length 12, 15, 18, 21, 24. Two tests were updated for that: 
1. Malfunctions in core unit tests
2. byron integration tests : both API and CLI scenarios

**Comment by piotr-iohk** [comment]
lgtm
