### ISSUE TITLE
metadata hash mismatch for re-registered pools

### ISSUE THREAD

**Issue by disassembler** [cardano-foundation/cardano-wallet#1805]
# Context

When a pool is re-registered with new metadata, the wallet still expects the previous metadata hash.

Logs:
```
[34m[cardano-wallet.pools-engine:Info:32][0m [2020-06-26 11:47:08.59 UTC] Fetching metadata with hash a8f463f9 from https://explorer.shelley-testnet.dev.cardano.org/p/1.json
[33m[cardano-wallet.pools-engine:Warning:32][0m [2020-06-26 11:47:08.61 UTC] Failed to fetch metadata with hash a8f463f9: Metadata hash mismatch. Saw: c9ed70969c964284ff854d61e43c2591b67ceb7e978347cb1b50ba3ed1d3edb4, but expected: a8f463f9ca305e85b832dfbfe384a7dfa9cde69c3f4e632dc9de12ee13aebb27
```

Pool registration certificate submitted to chain:

```
18 b5  # int(181)

8a  # list(10)
   03  # int(3)
   58 1c a2 87 77 a9 9c 49 d5 cf 87 d2 73 f4 16 56 
   44 2a e8 9f 5e c7 67 86 21 19 4c 5e f0 99  # bytes(28)
   58 20 5c d1 73 bd a2 9b fc 41 7a a5 03 f4 12 17 
   db 7a 50 37 69 8f e3 9c e6 b1 e0 b0 d2 76 92 81 
   df 9e  # bytes(32)
   1b 00 00 00 d1 8c 2e 28 00  # int(900000000000)
   1a 05 f5 e1 00  # int(100000000)
   d8 1e  # tag(30)
      82  # list(2)
         1b 00 0c cc cc cc cc cc cd  # int(3602879701896397)
         1b 01 00 00 00 00 00 00 00  # int(72057594037927936)
   58 1d e0 9c 2a da 51 4a df 22 1b 18 85 ce 36 9c 
   93 10 a5 ff a8 2c 91 e4 37 7a 34 e0 30 60 7b  # bytes(29)
   81  # list(1)
      58 1c 08 e9 5e 87 94 21 d6 4c 84 b7 75 b6 39 4d 
      9d 05 66 00 a2 98 a4 65 d7 01 65 e1 f2 25  # bytes(28)
   81  # list(1)
      83  # list(3)
         01  # int(1)
         19 0b b9  # int(3001)
         78 2a 72 65 6c 61 79 73 2d 6e 65 77 2e 73 68 65 
         6c 6c 65 79 2d 74 65 73 74 6e 65 74 2e 64 65 76 
         2e 63 61 72 64 61 6e 6f 2e 6f 72 67  # text("relays-new.shelley-testnet.dev.cardano.org")
   82  # list(2)
      78 39 68 74 74 70 73 3a 2f 2f 65 78 70 6c 6f 72 
      65 72 2e 73 68 65 6c 6c 65 79 2d 74 65 73 74 6e 
      65 74 2e 64 65 76 2e 63 61 72 64 61 6e 6f 2e 6f 
      72 67 2f 70 2f 31 2e 6a 73 6f 6e  # text("https://explorer.shelley-testnet.dev.cardano.org/p/1.json")
      58 20 c9 ed 70 96 9c 96 42 84 ff 85 4d 61 e4 3c 
      25 91 b6 7c eb 7e 97 83 47 cb 1b 50 ba 3e d1 d3 
      ed b4  # bytes(32)
```
 

 

version: bcc0ff009b4695589c107fdf21272a470b2362c0

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      |  |
| Platform     |           |
| Installation |             |

# Steps to Reproduce

1. ...

## Actual behavior
 

---

# Resolution 

- Make sure to "blacklist" (temporarily) urls from which we fail to fetch valid metadata. Only retrying them later on ==> #1801 

---

# QA 

- Extended the database interface for pools to store details about the last time a metadata was fetched. Written a small property showing that a URL recently fetched isn't listed as part of the next batch to fetch ==> https://github.com/input-output-hk/cardano-wallet/blob/8f26e72e5d79125186b629baf173fbba462e697e/lib/core/test/unit/Cardano/Pool/DB/Properties.hs#L506-L528

- Also synced against the shelley testnet and observed no duplicates in URL being fetched, they either succeed or fail (see PR's comments)

**Comment by piotr-iohk** [comment]
I have registered a pool and re-registeted with changed metadata on shelley testnet. No problem observed. New metadata is available. :+1:
