### ISSUE TITLE
Database migration notices on fresh database

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#1812]
# Context
 
The integration tests are showing the following log messages:

```
[cardano-wallet.wallet-db:Notice:980] [2020-06-27 19:58:50.09 UTC] wallet table does not contain required field 'passphrase_scheme'. Adding this field with a default value of "EncryptWithPBKDF2".
[cardano-wallet.wallet-db:Notice:980] [2020-06-27 19:58:50.09 UTC] rnd_state_address table does not contain required field 'account_ix'. Adding this field with a default value of 2147483648.
```

On a fresh database there should be no migrations necessary. These fields should either be added to the persistent models, or removed from the migrations.

# Steps to Reproduce

1. Run byron integration tests.
2. Inspect logs for Notice messages.

## Expected behavior

No database migrations occur.

## Actual behavior

Database migrations occur.

---

# Resolution 

---

# QA

**Comment by KtorZ** [comment]
Duplicate of https://github.com/input-output-hk/cardano-wallet/issues/1743 I believe?

**Comment by rvl** [comment]
So it is!
