### ISSUE TITLE
Extend SQLite DB to store pool retirement data.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#1815]
# Context

As part of the work to track pool retirements, we need a way of storing **pool retirement data** in the database.

This is complicated by the fact that:

1. A _single block_ can contain _multiple_ certificates relating to the same pool.
2. A _single transaction_ can contain _multiple_ certificates relating to the same pool.
3. The _relative order_ of these certificates is _significant_.
4. In _general_, earlier certificates are made obsolete by later certificates, but in particular:
    - a registration certificate will always _supersede_ an earlier retirement certificate (making that earlier retirement certificate obsolete);
    - a retirement certificate will always _augment_ the latest known registration certificate (meaning that data supplied as part of the registration remains relevant until the pool actually retires).

These rules follow from the "pool inference rule", as described in "[A Formal Specification of the Cardano Ledger](https://hydra.iohk.io/build/3202141/download/1/ledger-spec.pdf)".

# Decision

Extend the pool DB schema to make it possible to store:

- [x] retirement certificates.
- [x] the order of publication of certificates _within the same block_, for both registration and retirement certificates.

# Acceptance Criteria

- [x] The pool database _must_ provide a way to record all retirement certificates for any given pool.
- [x] The pool database _must_ provide a way to record the _order of publication_ of registration and retirement certificates within a block.

# Development 

Add a `slot_internal_index` row to the `PoolRegistration` table (and similarly to the `PoolOwners` table):
```patch
PoolRegistration sql=pool_registration
    poolRegistrationPoolId            W.PoolId            sql=pool_id
    poolRegistrationSlot              W.SlotId            sql=slot
+   poolRegistrationSlotInternalIndex W.SlotInternalIndex sql=slot_internal_index        
```
This will allow the database to record the position of each certificate in relation to other certificates in the same block.

Add a table to store pool retirements:

```hs
PoolRetirement sql=pool_retirement                                                                                                                                                    
    poolRetirementPoolId              W.PoolId            sql=pool_id                                                                                                                 
    poolRetirementSlot                W.SlotId            sql=slot                                                                                                                    
    poolRetirementSlotInternalIndex   W.SlotInternalIndex sql=slot_internal_index                                                                                                     
    poolRetirementEpoch               Word64              sql=epoch
```
For any given pool **_p_**:

* the _presence_ of a corresponding row in this table with  slot **_s_**, internal index **_n_**, and epoch _**e**_ indicates that a pool retirement certificate was the **_n_** th pool certificate issued during slot **_s_**, and that the pool retires in epoch **_e_**.
* the _absence_ of a corresponding row in this table indicates that no pool retirement data is available for **_p_**.

# QA 

See the following property tests:

- [x] `prop_poolRetirement` 
- [x] `prop_multiple_putPoolRetirement_single_readPoolRetirement`

**Comment by Anviking** [comment]
You might find the "Pool Inference Rules" figure from the 
[shelley ledger specs](https://hydra.iohk.io/build/3202141/download/1/ledger-spec.pdf) interesting.

<img width="782" alt="Skärmavbild 2020-06-29 kl  12 24 29" src="https://user-images.githubusercontent.com/304423/85999500-798ed880-ba0c-11ea-9b01-27ca13b2d1e9.png">


Simply reading the latest values from the two tables
- PoolRegistration
- PoolRetirement

might not work out as it would seem that:
- A retiring (or retired) pool may re-register
- A retiring pool may re-retire

And the timing would be crucial.

We could imagine a _single tx_ in a _single slot_, containing `[register pool1, retire pool1 e12, retire pool1 e10, re-register pool1]` (silly, but should be possible).

**Comment by jonathanknowles** [comment]
@Anviking wrote:

> We could imagine a single tx in a single slot, containing [register pool1, retire pool1 e12, retire pool1 e10, re-register pool1] (silly, but should be possible).

This is a very good point. Thank-you for raising it.

If multiple pool certificates appear within a _single block_, or even within a _single transaction_, it's my current understanding that we process these certificates _in the order that they appear_. In other words, transactions that appear earlier in a block are processed before transactions that appear later on, and entries that appear earlier in a transaction are processed before entries that appear later on.

In our [plan for extending the pool monitoring code](https://github.com/input-output-hk/cardano-wallet/issues/1817), we originally intended to make the following change:

```patch
forward blocks (_nodeTip, _pparams) = do
    atomically $ forM_ blocks $ \blk -> do
        let (slot, registrations) = fromShelleyBlock' getEpochLength blk
        runExceptT (putPoolProduction (getHeader blk) (getProducer blk)) >>= \case
            Left e   -> liftIO $ traceWith tr $ MsgErrProduction e
            Right () -> pure ()
        forM_ registrations $ \case
            Registration pool -> do
                liftIO $ traceWith tr $ MsgStakePoolRegistration pool
                putPoolRegistration slot pool
            Retirement cert -> do
                liftIO $ traceWith tr $ MsgStakePoolRetirement cert
+               putPoolRetirement slot cert
```
This call to [`putPoolRetirement`](https://github.com/input-output-hk/cardano-wallet/issues/1816) would have the effect of adding an entry to the `PoolRetirement` table for some pool **_p_** and slot **_s_**.

If we encounter a certificate of type `Registration` for pool **_p_** in slot **_s_**, we could arrange that we _also_ remove any entries within `PoolRetirement` for pool **_p_** and slot **_s_**. This would have the effect of _cancelling out_ any prior retirements that may have occurred within the same slot.

In the DB layer, we could support this by adjusting the definition of `putPoolRegistration` to also remove any entry (if one exists) from `PoolRetirement` for the given pool and slot.

Can you see any issues with this approach?

**Comment by jonathanknowles** [comment]
Hi @piotr-iohk!

I believe the work for this ticket is complete. Would you be okay with me closing it?

**Comment by piotr-iohk** [comment]
lgtm.
