### ISSUE TITLE
Extend DB layer to allow reading and writing of pool retirement data.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#1816]
# Context

As part of the work to track pool retirements, we need to provide a way for users of the DB layer to record that a pool will retire at a given epoch, or to query the DB to determine whether such a retirement has already been recorded. 

# Decision

Add the following operations (or equivalent operations) to the DB layer:

```hs
putPoolRetirement
    :: SlotId
    -> SlotInternalIndex
    -> PoolRetirementCertificate
    -> stm ()

readPoolRetirement
    :: PoolId
    -> stm (Maybe (SlotId, SlotInternalIndex, PoolRetirementCertificate))
```

For a discussion of `SlotInternalIndex` see https://github.com/input-output-hk/cardano-wallet/issues/1815.

# Acceptance Criteria

- [x] It **_must_** be possible to use the DB layer to record a pool retirement for a given epoch announced at a given slot and slot internal index.
- [x] It **_must_** be possible to use the DB layer to look up the _latest_ pool retirement certificate for a pool, and if one exists, the slot and slot internal index corresponding to that certificate.

# Development 

- https://github.com/input-output-hk/cardano-wallet/pull/1847

# QA 

See the following property tests:
- [x] `putPoolRetirement`
- [x] `prop_multiple_putPoolRetirement_single_readPoolRetirement`

**Comment by jonathanknowles** [comment]
Hi @piotr-iohk!

I believe the work for this ticket is complete. Would you be okay with me closing it?

**Comment by piotr-iohk** [comment]
lgtm.
