### ISSUE TITLE
Extend pool monitoring code to store retirements in the DB.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#1817]
# Context

As part of the work to track pool retirements, we need to make sure that when the wallet encounters a pool retirement certificate, that the relevant information is recorded in the DB.

# Decision

Extend the pool monitoring code to store pool retirements in the DB. Adjust the `forward` function within `monitorStakePools` to call `putPoolRetirement`, along with the corresponding _slot_ and _slot internal index_.

For a discussion of slot internal indices, see https://github.com/input-output-hk/cardano-wallet/issues/1815.

# Acceptance Criteria

- [x] The pool monitoring code, on encountering a pool retirement certificate, **_must_** ensure that the retirement epoch of that pool is recorded in the DB, along with the slot and slot internal index corresponding to that certificate.

# Development 

- https://github.com/input-output-hk/cardano-wallet/pull/1847

# QA 

Write integration tests to check that:

- [x] retiring a pool eventually results in a correct update to the `retirement` field of `ApiStakePool`, when read through the `ListStakePools` operation. (This field is only written as a consequence of the pool monitoring code writing retirements to the DB.)

**Comment by piotr-iohk** [comment]
lgtm
