### ISSUE TITLE
Add skeleton `retirement` field to `ApiStakePool`.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#1818]
# Context

As part of the work to track pool retirements, we need to provide a way for API users to determine whether a given pool has a retirement certificate associated with it.

# Decision

Add a skeleton `retirement` field to the `ApiStakePool` type:

```patch
data ApiStakePool = ApiStakePool  
    { id :: !(ApiT PoolId)
    , metrics :: !ApiStakePoolMetrics 
    , metadata :: !(Maybe (ApiT StakePoolMetadata))   
    , cost :: !(Maybe (Quantity "lovelace" Natural))  
    , margin :: !(Maybe (Quantity "percent" Percentage))  
    , pledge :: !(Maybe (Quantity "lovelace" Natural))
+   , retirement :: !(Maybe ApiEpochInfo)
    } deriving (Eq, Generic, Show)
```

Values of the above type are returned by the `ListStakePools` endpoint.

# Acceptance Criteria

- [x] The `ApiStakePool` type **_must_** have a `retirement` field that records the (expected) retirement epoch of the given stake pool. 
- [x] The API server **_may_** return a constant value of `Nothing` to begin with.
- [x] The swagger API specification **_must_** have a corresponding `retirement` field.
---

# Development 

- [x] Add field to API type.
- [x] Add field to Swagger definition.
- [x] Configure API server to always return `Nothing` for the `retirement` field.

# QA 

- [x] Update golden tests for `ApiStakePool`.
- [x] Update roundtrip serialization tests for `ApiStakePool`, if necessary. (This turned out to be unnecessary.

**Comment by jonathanknowles** [comment]
Hi @piotr-iohk!

I believe the work for this ticket is complete. Would you be okay with me closing it?

**Comment by piotr-iohk** [comment]
lgtm.
