### ISSUE TITLE
Extend Shelley `listPools` operation to provide real pool retirement data.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#1819]
# Context

As part of the work to track pool retirements, we need to ensure that the API server actually reports real pool retirement data as stored in the database (rather than always returning `Nothing`).

# Decision

Extend the Shelley `listPools` operation to provide real pool retirement data:

- [x] Extend `PoolDBMetrics` to include retirement data.
- [x] Extend `readDBPoolData` to provide pool retirement data.
- [x] Adjust `combineDbAndLsqData` to write retirement data into `ApiStakePool`.

# Acceptance Criteria

- [x] The `ListStakePools` endpoint **_must_** return `ApiStakePool` objects with real `retirement` field values and not skeleton values, reflecting the actual contents of the database.

# Development 

- https://github.com/input-output-hk/cardano-wallet/pull/1847

# QA 

Add integration tests to check that:

- [x] retiring a pool eventually results in a correct update to the `retirement` field of `ApiStakePool`, when read through the `ListStakePools` operation.

# Notes

Note that ideally, we would also test that retiring and then re-registering a pool clears the `retirement` field. However, the static nature of our test pool cluster means that building such a test is currently impractical. See: https://jira.iohk.io/browse/ADP-385

**Comment by piotr-iohk** [comment]
ok
