### ISSUE TITLE
Ensure that pool retirement data is correctly rolled back during a rollback operation.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#1820]
# Context

As part of the work to track pool retirements, we need to record pool retirements in the pool database. However, it will also be necessary to remove such entries in the event of a database rollback.

# Decision

Ensure that the `PoolRetirement` database table entries are correctly rolled back in the context of a DB rollback operation.

# Acceptance Criteria

- [x] `PoolRetirement` database table entries **_must_** be correctly rolled back in the context of a DB rollback operation.

# Development 

- https://github.com/input-output-hk/cardano-wallet/pull/1847

# QA 

- [x] Add property tests to verify that entries from `PoolRetirements` are appropriately removed in the context of a DB rollback operation.

**Comment by jonathanknowles** [comment]
Hi @piotr-iohk!

I believe the work for this ticket is complete. Would you be okay with me closing it?

**Comment by piotr-iohk** [comment]
lgtm.
