### ISSUE TITLE
Tentatively allow having an initial reserve amount for running coin selection.

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1821]
# Context

In the context of Shelley, Coin Selection becomes a bit more complex. There are now "things" that can be on the left side of the balance when making transaction that aren't unspent transaction inputs. In particular, we can now find:

- deposit sent back to wallet
- rewards from a stake address 

# Decision

These special inputs will be treated separately from standard UTxO inputs, but fully part of the fee balancing algorithm to allow interacting with them when building transactions. Both rewards and deposit are a bit special in the sense that they require at least a UTxO in a transaction. 

As a first step, I'll create an extension of the current `CoinSelection` data-type as an `UnsignedTransaction`, allowing it to carry an extra reserve amount that can (and will) be used in priority when paying for fees. 

# Acceptance Criteria

1. Fee balancing can be run with an extra positive "reserve" amount that allows for providing a balance to consume. 
2. The behavior of the fee balancing algorithm remains unchanged when `reserve = 0`

---

# Development 

- Added reserve as two separate fields `reclaim` and `withdrawal`, as well as  a new `deposit` for implicit deposit output. Also took care of all the internal plumbing to handle these correctly, including reviewing the fee balancing algorithm and adding the correct witnesses for withdrawal! ==> #1843 

# QA 

- All existing integration & unit tests pass, except one on Jörmungandr's I had to temporarily disable. I did some rework in fee estimator from the integration tests but we've lost some precision along the way which makes it quite harder to run this scenario again. The main problem being that we use two differents ways of calculating fees in integration scenarios and in the real code! ==> https://github.com/input-output-hk/cardano-wallet/blob/master/lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/API/StakePools.hs#L643-L657

- I've extended the unit test for the fee balancing function, with extra assertions. I've also extended the generators so they would cover more cases and in particular cases which mimic the way we "abuse" the algorithm for the delegation selection. In particular we show that:
  1. If at the end of the balancing, remaining fee are null, then the selection is indeed balanced.
  2. If the selection is balanced, then inputs are necessarily not null (we need at least 1 UTxO input)
  3. If the selection is balanced, then it is _valid_, where valid means that the sum of its inputs (including reclaim and withdrawal) does not exceed the sum of its output (including deposit).
  4. Only change outputs are mutated during the balancing process, a selection remains unchanged by the balancing algorithms with regards to other fields (inputs, deposit, withdrawal, outputs, reclaim).

  ==> https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Cardano/Wallet/Primitive/FeeSpec.hs#L505-L544

- Added a new property test to show that adding a withdrawal to a coin selection has an impact on the fee estimation. This is crucial in order to _measure_ the cost of adding a withdrawal in order to know whether a withdrawal is worth adding or not. ==> https://github.com/input-output-hk/cardano-wallet/blob/master/lib/shelley/test/unit/Cardano/Wallet/Shelley/TransactionSpec.hs#L129-L147

- Added an integration test which shows that:
    1. A wallet can delegate and accumulate rewards
    2. The rewards can be implicitly / automatically _spent_ in a normal transaction
    3. That part of the reward balance is transferred into the wallet UTxO balance (by comparing the total balance - reward balance before a withdrawal, with the total balance - reward balance after a withdrawal. It increases. We can't be much precise here because part of the reward is also used to pay for fee, but we can say for sure that it has to be _bigger_, even if fees were paid for a transaction!)

   ==> https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs#L143-L194

**Comment by piotr-iohk** [comment]
lgtm
