### ISSUE TITLE
Introduce K parameter

### ISSUE THREAD

**Issue by paweljakubas** [cardano-foundation/cardano-wallet#1822]
# Context

As a wallet user
I want to receive the K(optimal pool number) value
so that I can know the maximum amount of ADA I can delegate in one delegation certificate

# Decision

we want to have K parameter available

# Acceptance Criteria

1. Extend protocol parameters and propagate the change throughout codebase
2. Update sqlite tables
3. Add update parameter tests

---

# Development 

# QA 

Desired number of stake pools was added to ApiNetworkParameters. For byron it is set to 0, for shelley it get PParams from ledger, for jormungandr it takes maximum value of pool capping. I checked in integration tests the value for shelley.

**Comment by piotr-iohk** [comment]
lgtm.

I have added tests for Byron and Jormungandr -> https://github.com/input-output-hk/cardano-wallet/pull/1848.

For Shelley I was also thinking about testing the parmeter (in integration test) by comparing the value with the nOpt parameter taken from `cardano-cli shelley query protocol-parameters --testnet-magic 42 --out-file protocol.json` with the desiredPoolNumber reported by the endpoint. After discussion with @paweljakubas I think it might be a bit of overkill.

Anyway looking on shelley testnet the parameter reported by the endpoint matches with the nOpt param reported by cardano-cli.
