### ISSUE TITLE
Can't quit pools when reward account is non-empty 

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1824]
# Context
 
 

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | All  |
| Platform     | All           |
| Installation | Sources             |

# Steps to Reproduce

1. Join a pool
2. Wait until there's some reward in the reward account.
3. Quit the pool

## Expected behavior

To be clarified. The wallet should either return a clear error explaining that the reward account must be emptied first. Or, the reward should be automatically redeemed when quitting. The latter is perhaps a little nicer in terms of user experience (although quite implicit) but also require more work to fix.

## Actual behavior
 

The server returns a `500 Internal Server Error` after getting an error from the ledger.

---

# Resolution 

- Wrap up the work on #1821, so that rewards can be turned into UTxO
- Make the server fail with a proper error "you need to consume your reward before quitting".

---

# QA 

- The server now returns a proper error when trying to quit with a non-null reward balance. This is shown as part of STAKE_POOLS_JOIN_04 here: https://github.com/input-output-hk/cardano-wallet/blob/c2fe8f6f42e5edc31434c5bd56d579564a702c51/lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs#L338-L370

- However, a user can withdraw its reward "manually" and quit after which, would work just fine as shown in this scenario: https://github.com/input-output-hk/cardano-wallet/blob/c2fe8f6f42e5edc31434c5bd56d579564a702c51/lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs#L170-L218

**Comment by rvl** [comment]
Reminder to whoever is working on this - uncomment the second part of the "STAKE_POOLS_JOIN_04 - Rewards accumulate and stop" test scenario once this is fixed.

**Comment by KtorZ** [comment]
@rvl yes and no :s. 
In order to "fix" this, I am going to:

1. Wrap up the work on #1821, so that rewards can be turned into UTxO
2. Make the server fail with a proper error "you need to consume your reward before quitting". 

Then, being able to automatically consume the rewards when quitting will be done as part of a next U/S. Note that we are currently discussing the existence of this "quit" endpoint, which in essence, is _against_ the protocol. Instead, it would probably end-up being merged with the `migration` endpoint, so that quitting only happens behind the scene AND, only when a user is migrating his wallet (because we don't want to de-register stake key under normal circumstances).

**Comment by piotr-iohk** [comment]
When quitting the pool and having rewards earned there is now following error being shown:
```
Code = 403,
Message = {"code":"non_null_rewards","message":"It seems that you're trying to retire from delegation although you've unspoiled rewards in your rewards account! Make sure to withdraw your 33080446 lovelace first."}
```

One is able to join another pool even if he earned rewards :ok_hand: .
