### ISSUE TITLE
There are un-joinable pools on shelley_testnet

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#1833]
# Context

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | node: 1.14.2, cardano-wallet `bcc0ff009b4695589c107fdf21272a470b2362c0` |
| Platform     | Linux, all?         |
| Installation | from source            |

There are some pools that one cannot join on shelley testnet although they are listed by the wallet:

A pool that is listed on `cardano-cli shelley query stake-distribution`, but wallet reports as "retired in epoch 5", still it is listed by wallet and cardano-cli in epoch 6:

```
68657135870b97dc43b06955e62b817a010ae29cbe0987c279a42860
```

Some pools that are listed by the wallet but not listed on `cardano-cli shelley query stake-distribution`:
```
d1ba638f82bb013336f321f6a410f4954ac5bbd6a6f572620fc9bd10
afdac781aac2c6e36dfdf8fb9fc8301afed7450c6b432f00e91a3f96
814c66d7d21c6e4bbe2c94eb6b2c478ad3a8628871d9918b145bbc0f
71ecd0e62138588e3fd8522e42d7685983e0274f1439f4abafa531b2
```

# Steps to Reproduce

1. Join one of the pools above on shelley_testnet

## Expected behavior
All pools listed by wallet should be "joinable"

## Actual behavior
 
For all those pools we get:

```
Code = 500,
Message = {"code":"created_invalid_transaction","message":"That's embarrassing. It looks like I've created an invalid transaction that could not be parsed by the node. 
Here's an error message that may help with debugging: 
ApplyTxError [LedgerFailure (DelegsFailure (DelegateeNotRegisteredDELEG (KeyHash 68657135870b97dc43b06955e62b817a010ae29cbe0987c279a42860)))]"}

```

---

# Resolution 

---

# QA

**Comment by Anviking** [comment]
Summarizing [info from Jared](https://input-output-rnd.slack.com/archives/CCRB7BU8Y/p1593514703374600):
A pool retiring "in" epoch 5 will:
- Disappear from the stake distribution query at the 6/7 epoch boundary
- Be un-joinable at the 5/6 epoch boundary

**Comment by Anviking** [comment]
A solution might be to use the work @jonathanknowles now is starting, and ourselves decide, in the DB, which pools to displays or not.

**Comment by jonathanknowles** [comment]
I suspect this issue is fixed by:
- https://github.com/input-output-hk/cardano-wallet/pull/1913
- https://github.com/input-output-hk/cardano-wallet/pull/1945

@piotr-iohk what do you think?

**Comment by piotr-iohk** [comment]
By brute force test all 268 pools on shelley testnet joinable.
