### ISSUE TITLE
Cannot join pool with ITN rewards wallet on shelley testnet

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#1835]
# Context
 
Cannot join pool from ITN reward wallet.
_(Known but haven't seen that reported, so reporting.)_

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | node 1.14.2, wallet `bcc0ff009b4695589c107fdf21272a470b2362c0`|
| Platform     | All         |
| Installation | From source            |

# Steps to Reproduce

1. Restore ITN rewards wallet on Shelley Testnet. => wallet restored. Rewards account has funds.
2. Get some ADA from faucet onto that wallet.
3. Try to join any stake-pool.

## Expected behavior

Should be able to join.

## Actual behavior
 
```
Code = 500,
Message = {"code":"created_invalid_transaction","message":"That's embarrassing. It looks like I've created an invalid transaction that could not be parsed by the node. 
Here's an error message that may help with debugging: 
ApplyTxError [LedgerFailure (DelegsFailure (DelplFailure (DelegFailure (StakeKeyAlreadyRegisteredDELEG (KeyHashObj (KeyHash 96b3e636fddcfb732335f938209812949b5ce355ac80dffb8d4051b7))))))]"}
```

---

# Resolution 

## A plan:
1. Make it easy to create shelley transactions that only register the key, without delegating
2. Create a failing integration test where we A. register key, B. try to delegate
3. Keep track of key registration and key de-registration certificates in the DB

---

# QA 

- Our integration test cluster are now pre-registering a stake key before starting, so that we can test restoring a wallet with a pre-existing stake key and delegating from it (to simulate the case of an ITN) wallet.
    - see here: https://github.com/input-output-hk/cardano-wallet/blob/5e173ea7b1faa883eb41c472e102155c557be4f4/lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs#L407-L412
    - and here for the actual scenario: https://github.com/input-output-hk/cardano-wallet/blob/5e173ea7b1faa883eb41c472e102155c557be4f4/lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs#L374-L395

**Comment by Anviking** [comment]
Summarizing info from Jared:
A pool retiring "in" epoch 5 will:
- Disappear from the stake distribution query at the 6/7 epoch boundary
- Be un-joinable at the 5/6 epoch boundary

**Comment by rvl** [comment]
I reproduced too, after transferring some "real" testnet ada to my ITN rewards wallet to pay for the transaction.

I think we were working under the assumption that stake key registration was idempotent, so multiple registrations would not be a problem.

**Comment by Anviking** [comment]
> I think we were working under the assumption that stake key registration was idempotent, so multiple registrations would not be a problem.

Don't think we assume it's idempotent. We are checking for the existence of a previous key registration here:
https://github.com/input-output-hk/cardano-wallet/blob/5af4490e7f050dcba21692e7ddb9230b7f9d5b85/lib/shelley/src/Cardano/Wallet/Shelley/Transaction.hs#L190-L202

But that check is probably incomplete in the context of ITN rewards. Sounds like MIR certificates will create a stake key too?

**Comment by KtorZ** [comment]
> Sounds like MIR certificates will create a stake key too?

No. But they come along with a stake key registration certificate which we do not process or store. Right now, we _assume_ the existence of stake key by looking at the wallet's delegation certificate. This is sort of wrong as it's based on implementation details of the wallet (both that, on the one hand, we register a stake key before delegating and, we de-register it when "quitting").   

Yet for ITN wallets, we're hitting a case where the a key has been registered, but not by us, so it does not come with a corresponding pool delegation certificate and it is therefore "invisible" to us. 

Possible fix: we need to watch key registration / de-registration certificates as well, store them, and use also take them into account to determine the wallet's needs for registering a key.

**Comment by piotr-iohk** [comment]
LGTM. Able to join stake pool with ITN rewards wallet on shelley testnet.
