### ISSUE TITLE
Resubmit transactions after expiry

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#1839]
# Context

ADP-93 Transaction scheduler

Transactions which have passed their expiry slot are removed from the pending set and effectively cancelled.
A new transaction with the same payment (but possibly different coin selection) should be signed and submitted.

# Decision

- Any transactions in the database which are marked Expired, but have not been resubmitted, should be resubmitted.
- The payment should be exactly the same, but the coin selection may be different.
- The resubmitted transaction is signed again and will have a different txid.
- Record the new txid on the expired transaction in the database.

# Acceptance Criteria

---

# Development 

# QA

**Comment by jonathanknowles** [comment]
I have a couple of questions:

- Which component of the wallet will be responsible for rescheduling expired transactions, and at what point in the execution flow will the rescheduling be initiated?
- On a practical level, how will the wallet perform the re-signing of the newly created transaction?

**Comment by jonathanknowles** [comment]
What should the TTL of the replacement transaction be? Will it inherit the TTL of the transaction it replaced?

**Comment by KtorZ** [comment]
Friendly reminder that this also exists: https://github.com/input-output-hk/cardano-wallet/blob/master/specifications/wallet/formal-specification-for-a-cardano-wallet.pdf, in particular, chapter 10

**Comment by rvl** [comment]
@KtorZ What about it in particular? I was going by section _10.4 Transactions with TTL_. And the TTL is covered by #1838.

**Comment by KtorZ** [comment]
@rvl Nothing special, I just wanted to make sure it gets acknowledged. There are some good ideas to take inspiration from, but not everything maybe applies to the current wallet's design so I trust you to make a sound decision ^.^

**Comment by rvl** [comment]
We don't need to do resubmission of expired transactions in this way. But even if we wanted, it would be difficult to do in practice, as noted above.
