### ISSUE TITLE
Introduce diverse witnesses in shelley

### ISSUE THREAD

**Issue by paweljakubas** [cardano-foundation/cardano-wallet#1844]
# Context

As a user
I want to move my funds from my Byron wallet to my shelley wallet
so that I manage my funds

# Decision

We want to enable sending txs with Icarus/Byron witnesses within shelley style wallet. This will require introducing `TxWitnessTagFor` typeclass on key parameter, add the constraint in `newTransactionLayer`. This will allow adding dedicated `mkWitness` implementation, also differentiate `postTx`

# Acceptance Criteria
1. `TxWitnessTagFor` typeclass and impl for IrarusKey, ByronKey, and ShelleyKey are introduced.
2. `newTransactionLayer` is constraint with `TxWitnessTagFor`
3. Specialized impl of `mkWitness` for keys are added.
4. Estimated fee is revised (IcarusKey and ByronKey witnesses are more costly)
5. Integration tests illustrating the case are added. 

---

# Development 

# QA 

I have demonstrated that decodeTx for shelley/byron witnesses work -> see TransactionSpec tests in shelley 
Also showed that byron/icarus txs to shelley work! 
It would be good to enable ByronTransactions for shelley integration testing and see byron/icarus -> byron/icarus txs work.
Also, we resigned from mkFeeestimator and use fee estimation endpoint - it would be worth to propagate this change throught code

**Comment by piotr-iohk** [comment]
LGTM, I have enabled additional tests for Byron txs, migrations (and also tests for byron addresses, and hw wallets) in integration tests. Also extracted the newly introduced integration test byron tx -> shelley to separate file not to run it on Jormungandr. (Jorm does not support Byron txs so it failed nightly last night). All in -> #1900.

**Comment by piotr-iohk** [comment]
Closing. This is basically working OK. Still #1900 with additional tests to be merged.
