### ISSUE TITLE
Listing stake-pools while wallet is syncing takes long or returns 503

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#1846]
# Context

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | node 1.14.2, wallet:  `2020.6.5 (git revision: a60c27729ea7915ddc00e6970dbd49b60d0e5c5f)`|
| Platform     | Linux, all          |
| Installation | From source          |

Observation similar to https://github.com/input-output-hk/cardano-wallet/issues/1759.

# Steps to Reproduce
On shelley testnet:
1. Either start from scratch node + wallet or while node is fully synced, start a wallet on top from scratch.
2. While wallet is syncing attempt to list stake pools

## Expected behavior
Pools should be listed.

## Actual behavior
Listing stake pools returns:
```
Code = 503,
Message = {"code":"network_unreachable","message":"The node backend is unreachable at the moment. Trying again in a bit might work."}
```
or pools are listed but after quite longer time than normal (5-7 seconds on Linux).

---

# Resolution 

@rvl hypothesis is that it is related to fetching rewards as in https://github.com/input-output-hk/cardano-wallet/issues/1759.

---

# QA

**Comment by KtorZ** [comment]
I don't think this is a "bug" per se. The software is behavior correctly here. It returns a `503 Temporary Unavailable` which sounds relevant to the situation.

It is perhaps not the best user experience I agree, but I'd rather log this as an improvement in JIRA than as a bug.

**Comment by KtorZ** [comment]
Error message has been improved with: https://github.com/input-output-hk/cardano-wallet/pull/2094
