### ISSUE TITLE
Prevent staking to a retired pool.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#1853]
# Context

As part of tracking stake pool retirements, we need to return an error if a user attempts to stake to a pool that has already retired.

# Decision

- Adjust `joinStakePool` to return `ErrNoSuchPool` if the current epoch is later than or equal to the retirement epoch of the specified pool.

# Acceptance Criteria

- [x] The wallet _must_ produce an error if a user attempts to stake to pool that has already retired.

# Development 

- https://github.com/input-output-hk/cardano-wallet/pull/1913

# QA 

- [x] Add an integration test that performs the following steps:

1. Create a new pool **_p_**.
1. Issue a retirement certificate for epoch **_e_**<sub>retirement</sub>.
1. Wait until epoch **_e_**<sub>current</sub> >= epoch **_e_**<sub>retirement</sub>.
1. Verify that attempting to join pool p **does** result in an `ErrNoSuchPool` error.

# Notes

Note that the above integration test is a compromise.

Ideally, a more complete integration test would verify that staking to a pool is still possible right up to the moment before the pool has actually retired. See: https://jira.iohk.io/browse/ADP-385

**Comment by piotr-iohk** [comment]
Works as expected. Also checked that pool that is about to retire (but not yet retired) is still joinable.
