### ISSUE TITLE
Byron->Shelley migration doesn't work

### ISSUE THREAD

**Issue by Fell-x27** [cardano-foundation/cardano-wallet#1856]
# Context
 
When I try yo migrate funds from Byron wallet to a fresh created Shelley one, got error.

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | 2020.7.6 (git revision: 8078cf054141ea1642bc80679411a1a229f15a31) |
| Platform     | Linux 64bit  |
| Installation | From source  |

# Steps to Reproduce

1. Launch wallet (shelley version) over a2161bac70 cardano-node.
2. Restore a Byron wallet it with any 12 or 15 **unused** mnemonic phrase.
3. Fund it with faucet or by transaction.
4. Create a new one Shelley wallet.
5. Launch migration procedure from Byron wallet to any address from Shelley wallet

## Expected behavior

Successfull transaction.

## Actual behavior
 
Errors like:

`{"code":"created_invalid_transaction","message":"That's embarrassing. It looks like I've created an invalid transaction that could not be parsed by the node. Here's an error message that may help with debugging: ApplyTxError [LedgerFailure (UtxowFailure (MissingVKeyWitnessesUTXOW (WitHashes (fromList [KeyHash 719cdfd98531883710ac6cfb3d067bc8679168747895536d776604a8]))))]"}`

---

# Resolution 

---

# QA

**Comment by piotr-iohk** [comment]
Thanks @Fell-x27, this is currently in the works (https://github.com/input-output-hk/cardano-wallet/issues/1844). The story introduces byron transaction support in shelley wallet which will enable migrations as well.

**Comment by KtorZ** [comment]
I imagine that this issue is now fixed.

**Comment by piotr-iohk** [comment]
It is fixed.

**Comment by cryptohoard-io** [comment]
Hi, I have been getting this error whilst trying to register my stake pool on 1.18.0:

Error while submitting tx: ApplyTxError [LedgerFailure (UtxowFailure (MissingVKeyWitnessesUTXOW (WitHashes (fromList [KeyHash "1acd9a8e248a3b896cee183e776638bb6ba8142274c61f3409d871be"]))))]

Is there a fix or workaround?

**Comment by KtorZ** [comment]
This errors tells you that your transaction is missing a witness / signature. Have a look at the `cardano-cli shelley transaction witness` and `cardano-cli shelley transaction sign-witness`commands. 
For more information, refer to the [tutorials](https://github.com/input-output-hk/cardano-tutorials/)
