### ISSUE TITLE
Include withdrawals one level down, during the coin selection (instead of during fee balancing).

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1861]
# Context

In a first iteration, I added withdrawals as a part of the coin selection data type. The withdrawals were taken into account during fee balancing, such that they could be used to pay for fees. Adding them there was easier in a first step as they required very little change to coin selection and fee balancing logic.

# Decision

Yet, being able to use the reward account _during_ the coin selection would be a big plus and would avoid weird cases where the wallet would fail to pay for a transactions despite having enough funds (indeed, in the current state, the wallet needs to be able to cover the entire requested amount with only UTxO and will only use the reward account during fee balancing. This leads to rather misleading API errors. 

# Acceptance Criteria

1. Withdrawals _must_ be used during the coin selection.
2. Withdrawals _must_ still be usable during fee balancing.

---

# Development 

- #1865 

# QA 

- The previous integration tests consuming the rewards still pass.

- The previous unit tests about fee balancing still pass.

- I've added new unit tests showing how the **random** coin selection behaves in the presence  of withdrawals:
    - https://github.com/input-output-hk/cardano-wallet/blob/368c038107e457bfd2ad5298b396ccdd2dfbb422/lib/core/test/unit/Cardano/Wallet/Primitive/CoinSelection/RandomSpec.hs#L166-L178
    - https://github.com/input-output-hk/cardano-wallet/blob/368c038107e457bfd2ad5298b396ccdd2dfbb422/lib/core/test/unit/Cardano/Wallet/Primitive/CoinSelection/RandomSpec.hs#L180-L192
    - https://github.com/input-output-hk/cardano-wallet/blob/368c038107e457bfd2ad5298b396ccdd2dfbb422/lib/core/test/unit/Cardano/Wallet/Primitive/CoinSelection/RandomSpec.hs#L194-L210
    - https://github.com/input-output-hk/cardano-wallet/blob/368c038107e457bfd2ad5298b396ccdd2dfbb422/lib/core/test/unit/Cardano/Wallet/Primitive/CoinSelection/RandomSpec.hs#L212-L237
    - https://github.com/input-output-hk/cardano-wallet/blob/368c038107e457bfd2ad5298b396ccdd2dfbb422/lib/core/test/unit/Cardano/Wallet/Primitive/CoinSelection/RandomSpec.hs#L239-L251
    - https://github.com/input-output-hk/cardano-wallet/blob/368c038107e457bfd2ad5298b396ccdd2dfbb422/lib/core/test/unit/Cardano/Wallet/Primitive/CoinSelection/RandomSpec.hs#L253-L261
    - https://github.com/input-output-hk/cardano-wallet/blob/368c038107e457bfd2ad5298b396ccdd2dfbb422/lib/core/test/unit/Cardano/Wallet/Primitive/CoinSelection/RandomSpec.hs#L263-L271

- I've added new unit tests showing how the **largest-first** coin selection behaves in the presence  of withdrawals:
    - https://github.com/input-output-hk/cardano-wallet/blob/368c038107e457bfd2ad5298b396ccdd2dfbb422/lib/core/test/unit/Cardano/Wallet/Primitive/CoinSelection/LargestFirstSpec.hs#L121-L133
    - https://github.com/input-output-hk/cardano-wallet/blob/368c038107e457bfd2ad5298b396ccdd2dfbb422/lib/core/test/unit/Cardano/Wallet/Primitive/CoinSelection/LargestFirstSpec.hs#L135-L147
    - https://github.com/input-output-hk/cardano-wallet/blob/368c038107e457bfd2ad5298b396ccdd2dfbb422/lib/core/test/unit/Cardano/Wallet/Primitive/CoinSelection/LargestFirstSpec.hs#L149-L157

   
- I've also fixed [a bug](https://github.com/input-output-hk/cardano-coin-selection/issues/39) in the largest-first algorithm that has been fixed in `cardano-coin-selection` but wasn't backported here. As a result, "ErrInputsDepleted" can no longer be met under normal circumstances, but only when a transaction **with withdrawals** is made on a wallet with no UTxO. Therefore, I did remove several integration scenarios that were testing precisely this as they were now failing (which _proved_ that the bug had been fixed :upside_down_face:).

**Comment by piotr-iohk** [comment]
Testing manually on shelley testnet. So, balance available = 1 ADA, rewards = 5 ADA, you can make successful tx (with withdrawals) for 2 ADA :tada: 

About this:
>As a result, "ErrInputsDepleted" can no longer be met under normal circumstances, but only when a transaction with withdrawals is made on a wallet with no UTxO.

See that. So, total balance = 0 ADA, rewards = 5 ADA, and making any transaction in such case (with or without withdrawals) results in `inputs_depleted` error. 
Actually I think that it would be quite nice to be able to "withdraw" rewards in this case also, especially that we'll be having ITN wallets that will be exactly that. Otherwise users will be forced to add some utxo to such wallet in order to be able to withdraw them... What do you think @KtorZ?

**Comment by KtorZ** [comment]
> Actually I think that it would be quite nice to be able to "withdraw" rewards in this case also,

This is actually a limitation of the ledger (and also why we are doing things in such way here). This is in order to prevent _replay_ attacks. Would the ledger allow such transaction with no UTxO, then it'd be possible for attacker to resubmit the exact same transaction later (including its witnesses). By requiring at least one UTxO (which can't be spent twice), this is prevented. So, I agree with you -- it'd be nice, yet unfortunately impossible :+1:

**Comment by piotr-iohk** [comment]
lgtm
