### ISSUE TITLE
I used to use cardano-sl wallet to generate addresses and receive tokens, but now I want to use cardano-wallet, how do I transfer the tokens from cardano-sl wallet to cardano-wallet?

### ISSUE THREAD

**Issue by liuxh-go** [cardano-foundation/cardano-wallet#1866]

**Comment by KtorZ** [comment]
Have you written down your mnemonic words you used to create your wallet in cardano-sl ?

**Comment by liuxh-go** [comment]
no

**Comment by KtorZ** [comment]
Then there's nothing we can do for you, sorry.

**Comment by liuxh-go** [comment]
I see a data table named privilege_key in the rnd.xxx.sqlite database. Can I restore it by the value of the root field?

**Comment by liuxh-go** [comment]
I tested the following on the test network, this is possible, restore my wallet through the root and hash information in the database.

**Comment by liuxh-go** [comment]
The document in the cardano-rest project is wrong. Can you solve the following? @KtorZ 

explorer-api: https://input-output-hk.github.io/cardano-rest/explorer-api/
submit-api: https://input-output-hk.github.io/cardano-rest/submit-api/

Unable to open the api document page, the following is the error message:

```
Something went wrong...
Error downloading https://raw.githubusercontent.com/input-output-hk/cardano-rest/master/explorer-api/swagger.yaml Failed to fetch
Stack trace
Error: Error downloading https://raw.githubusercontent.com/input-output-hk/cardano-rest/master/explorer-api/swagger.yaml 
Failed to fetch
    at https://cdn.jsdelivr.net/npm/redoc@2.0.0-rc.20/bundles/redoc.standalone.js:49:5419
    at https://cdn.jsdelivr.net/npm/redoc@2.0.0-rc.20/bundles/redoc.standalone.js:108:36105

TypeError: Failed to fetch

ReDoc Version: 2.0.0-rc.20
Commit: fd581261
```

**Comment by KtorZ** [comment]
Hmm. Things are working just fine for me on both Firefox and Chrome. Are you using a stable Internet connection? Are you behind a firewall that would block github?

**Comment by liuxh-go** [comment]
Everything works on my network, it doesn't seem to be a problem with the network
