### ISSUE TITLE
Properly support BlockHeader <-> HF.Point conversions

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#1868]
# Context

We can no longer (correctly) convert `SlotNo` to `SlotId` using the genesis epoch length when
the hard fork arrives. Shelley may use a different epoch length.

To interact with the node we need to provide points which are `(slotNo, headerHash)`.

Rollbacks to EBBs are not a concern as they have already ceased to be produced.

# Decision

- Replace SlotId with SlotNo in DB
- Concider using a special value for genesis (like `NULL`)

# Acceptance Criteria

- Wallet _must_ not break when the hard fork arrives
- The DB/persisted slots _should_ be easy to reason about for developers (i.e. not just work by accident) 
- Don't break cardano-wallet-jormungandr

---

# Development 

- #1887 
- #1890 
- #1901 

# QA 

- Existing tests pass

> Wallet _must_ not break when the hard fork arrives

Bad AC, but we don't need to convert between `SlotNo` and `SlotId` anymore to talk to the node.

- Here are the new golden tests for sync progress calculation: https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Cardano/Wallet/Primitive/SyncProgressSpec.hs#L125-L135

**Comment by Anviking** [comment]
I think it would be neat to even use the _very same_ `SlotNo` definition as other projects https://github.com/input-output-hk/cardano-base/blob/5c6db42be8ed83463f89e6257d8eb94ca4df8ca9/slotting/src/Cardano/Slotting/Slot.hs#L31-L35

**Comment by piotr-iohk** [comment]
lgtm
