### ISSUE TITLE
Remove `GenesisParameters` from wallet checkpoints

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#1872]
# Context

In ADP-356 we are integrating with Hard Fork Combinator.

In each wallet checkpoint we are currently storing:

```
checkpointGenesisHash       BlockId      sql=genesis_hash
checkpointGenesisStart      UTCTime      sql=genesis_start
checkpointFeePolicyUnused   Text         sql=fee_policy
checkpointSlotLength        Word64       sql=slot_length
checkpointEpochLength       Word32       sql=epoch_length
checkpointTxMaxSizeUnused   Word16       sql=tx_max_size
checkpointEpochStability    Word32       sql=epoch_stability
checkpointActiveSlotCoeff   Double       sql=active_slot_coeff
```

Note that
- `epochLength`, `slotLength` may change in the byron-to-shelley transition, but I don't think wallet checkpoints are suitable for keeping track of this.
- `epochStability` (i.e. `k`/ `securityParam`) is completely static
- We store recent `TxParameters` in a separate table
- We verify the `genesisHash` of the stored genesis checkpoint (seems useful)

# Decision

I think we should remove everything but `genesisHash`.

# Acceptance Criteria

- [ ] Redundant and potentially confusing information should be removed from wallet checkpoints

---

# Development 

#1983

# QA

**Comment by Anviking** [comment]
Maybe we should abort this for now because of https://input-output-rnd.slack.com/archives/GBT05825V/p1596197796271100?thread_ts=1596197783.271000&cid=GBT05825V

**Comment by rvl** [comment]
Yes when we have a better db migration system we can revisit this.
