### ISSUE TITLE
After using random(from xprv) to restore the wallet, Migrations reports an error

### ISSUE THREAD

**Issue by liuxh-go** [cardano-foundation/cardano-wallet#1878]
I used random(from xprv) to restore the wallet, and then I want to use Byron Migrations to transfer my assets to the new wallet, but the following error occurred:

```
{"code":"created_invalid_transaction","message":"That's embarrassing. It looks like I've created an invalid transaction that could not be parsed by the node. Here's an error message that may help with debugging: MempoolTxErr (UTxOValidationTxValidationError (TxValidationWitnessWrongKey (VKWitness (VerificationKey {unVerificationKey = XPub {xpubPublicKey = \"\\144x\\236\\136\\228_4\\a\\222\\DLEO\\132W\\DC1\\165)Y\\186\\174\\159\\239\\159\\222\\204!\\SI\\211\\SI\\129&\\164\\ETB\", xpubChaincode = ChainCode \"\\162\\135\\137\\180\\159\\183[8\\ENQ\\197\\NAK\\GS\\237$\\ETX\\154_\\165br\\251D\\247/\\193q\\v\\198\\208\\\"\\r\\149\"}}) (Signature (XSignature {unXSignature = \"\\218H/]Y\\248\\ACK\\242\\249?\\234C\\207\\246\\222\\168\\DELc\\254\\187]B\\\\\\161B\\EOTyRQ\\192\\128\\161\\143\\t\\233y\\179\\157k\\161$\\136\\178\\159\\201\\237\\167\\194f\\149\\223\\203\\183\\179\\tN\\ETBWp\\164\\&15\\239\\NUL\"}))) (Address {addrRoot = 874ecc5c6b9e3f9a89c0899ec83a939519208a500da54180163c4c5c, addrAttributes = Attributes { data: AddrAttributes {aaVKDerivationPath = Just (HDAddressPayload {getHDAddressPayload = \"j\\192\\162V\\170\\190\\176fO.r\\170\\255\\153\\139\\GSrsd*IW\\EM\\ETB\\t\\224i\\230\"}), aaNetworkMagic = NetworkTestnet 1097911063} }, addrType = ATVerKey})))"}
```

Because it is on the test network, so I did not delete the key information in the error message.

How should I transfer my assets?

**Comment by liuxh-go** [comment]
@KtorZ Can you help me?

**Comment by KtorZ** [comment]
You previous messages suggest that you've been fiddling with the database by hand: https://github.com/input-output-hk/cardano-wallet/issues/1866#issuecomment-654681776

If that's the case, I can't (or at least, I am not willing to) help you there. Stick with the publicly exposed API and do not play with the software internals unless you know what you're doing. If you know what you're doing, you won't need any help. 

--- 

Having said that, there's indeed a "work-around" that one can use via the API to restore a cardano-sl wallet. This requires however that you: 

a) remember the encryption passphrase that was used on cardano-sl
b) have somewhat access to the hash of that passphrase

There's an ad-hoc tool that can be used to retrieve known public keys and hash of a passphrase from a cardano-sl installation https://github.com/input-output-hk/cardano-sl/pull/4278#issuecomment-600553878

Good luck.
