### ISSUE TITLE
Add DB function to read the current lifecycle status for a pool.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#1880]
# Context

As part of the work to track pool retirements, we need to be able to **determine the latest lifecycle status for a pool**.

A pool's current lifecycle status is determined by _registration_ and _retirement_ certificates, which are published on the blockchain.

This is complicated by the fact that:

1. A _single block_ can contain _multiple_ certificates relating to the same pool.
2. A _single transaction_ can contain _multiple_ certificates relating to the same pool.
3. The _relative order_ of these certificates is _significant_.
4. In _general_, earlier certificates are made obsolete by later certificates, but in particular:
    - a registration certificate will always _supersede_ an earlier retirement certificate (making that earlier retirement certificate obsolete);
    - a retirement certificate will always _augment_ the latest known registration certificate (meaning that data supplied as part of the registration remains relevant until the pool actually retires).

These rules follow from the "pool inference rule", as described in "[A Formal Specification of the Cardano Ledger](https://hydra.iohk.io/build/3202141/download/1/ledger-spec.pdf)".

# Decision

1. Add a `PoolLifeCycleStatus` type, which represents the current status of a pool:

    ```hs
    data PoolLifeCycleStatus
        = PoolNotRegistered
            -- ^ Indicates that a pool is not registered.
        | PoolRegistered
            PoolRegistrationCertificate
            -- ^ Indicates that a pool is registered BUT NOT marked for retirement.
        | PoolRegisteredAndRetired
            PoolRegistrationCertificate
            PoolRetirementCertificate
            -- ^ Indicates that a pool is registered AND ALSO marked for retirement.
    ```

2. Provide a function to read this status from a given database layer:

    ```hs
    readPoolLifeCycleStatus
        :: DBLayer m
        -> PoolId
        -> m PoolLifeCycleStatus
    ```

# Acceptance Criteria

- [x] It _must_ be possible to unambiguously determine the current lifecycle status for a given pool from the database layer.
- [x] The rules of precedence for registration and retirement certificates _should_ be encapsulated within a single _pure function_ that can be unit tested _in isolation_, _without_ having to construct a mock database layer.

# Development 

- https://github.com/input-output-hk/cardano-wallet/pull/1847

# QA 

- [x] See property tests with the prefix `prop_determinePoolLifeCycleStatus` in https://github.com/input-output-hk/cardano-wallet/pull/1847/files.

**Comment by jonathanknowles** [comment]
Hi @piotr-iohk!

I believe the work for this ticket is complete. Would you be okay with me closing it?

**Comment by piotr-iohk** [comment]
lgtm.
