### ISSUE TITLE
Add withdrawals to core transaction data-type 

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1881]
# Context

In order to correctly report an history of all withdrawals made by a user, we need to be able to filter the transaction history based on whether or not they included withdrawals. 

# Decision

- Add a new database table to store withdrawals alongside input and output
- Wire down everything from the block discovery so that withdrawals are correctly inserted into the database for transactions.

# Acceptance Criteria

1. The API _must_ now return a list of withdrawals with each transactions
2. Withdrawals _should_ be represented as a key:value map of chimeric account mapping to a quantity of lovelace
3. Withdrawals belonging to a wallet must be correctly reported in the API

---

# Development 

- #1892 

# QA 

- Transactions now have a "withdrawals" field documented in the API, reflecting a new field added to the core transaction type. Withdrawals are only present in Shelley, and they are simply defaulted to an empty map for Byron and Jormungandr.

- Withdrawals are made of a stake address (hashed reward account, with network discrimination, bech32 encoded). I've tested the encoding / decoding using a classical roundtrip property:
  https://github.com/input-output-hk/cardano-wallet/blob/26064b21e3dd26fef71913ab8a248ba5ad2f5051/lib/shelley/test/unit/Cardano/Wallet/Shelley/CompatibilitySpec.hs#L127-L136

- There's a new **table** in the database for storing withdrawals. This doesn't require any manual migration since persistent will create the new table automatically. There's one 'gotcha' however, and it is that pre-existing wallet with withdrawals will not "sync back", so it is possible that they have missed withdrawals that have already happened. Restoring the wallet from scratch would solve this. This shouldn't be a problem for end-users since withdrawals haven't yet been introduced to them.

- I made sure to adjust our Arbitrary generators to generate transactions _with_ withdrawals, so that every existing unit tests and state-machine tests for the database functions could be tested. They pass. 
  https://github.com/input-output-hk/cardano-wallet/blob/26064b21e3dd26fef71913ab8a248ba5ad2f5051/lib/core/test/unit/Cardano/Wallet/DB/Arbitrary.hs#L378-L400

**Comment by piotr-iohk** [comment]
lgtm
