### ISSUE TITLE
Allow filtering txs by minimal withdrawal amount in the API

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1882]
# Context

See #1881 

# Decision

- Add a query parameter to the API `minWithdrawal` to filter transactions based on a minimal withdrawal amount (discard any withdrawal that doesn't belong to _us_).

# Acceptance Criteria

1. The API _must_ be able to filter the transaction history based on a minimal withdrawal amount.

---

# Development 

- #1892 

# QA 

- There's a new query parameter available when listing transactions `minWithdrawal`. It is documented as such:

  ![Screenshot from 2020-07-11 00-25-22](https://user-images.githubusercontent.com/5680256/87207793-1e62bd00-c30d-11ea-936e-df83cd898aae.png)

- I've augmented the `readTxHistory` database function with this (optional) parameter, as well as the state-machine command counter-part: 
  
  https://github.com/input-output-hk/cardano-wallet/blob/26064b21e3dd26fef71913ab8a248ba5ad2f5051/lib/core/test/unit/Cardano/Wallet/DB/StateMachine.hs#L298-L302

  this means that we get a lot of testing done "for free" via the state-machine tests. It caught an early bug nicely on the first run.

- I've also extended the now-pretty-big STAKE_POOLS_JOIN_01 scenario so that it'd query the withdrawal history (by using a `minWithdrawals` of 1) before and after making the withdrawal, showing that the withdrawals goes from an empty list of results to a list with 1 result.

  https://github.com/input-output-hk/cardano-wallet/blob/26064b21e3dd26fef71913ab8a248ba5ad2f5051/lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs#L149

  https://github.com/input-output-hk/cardano-wallet/blob/26064b21e3dd26fef71913ab8a248ba5ad2f5051/lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs#L205-L209

  https://github.com/input-output-hk/cardano-wallet/blob/26064b21e3dd26fef71913ab8a248ba5ad2f5051/lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs#L227-L238

**Comment by piotr-iohk** [comment]
That looks good initially. Still not able to fully test on testnet cause there are no rewards yet on any of the wallets I have.

I see one, small corner case:

```
curl http://localhost:8090/v2/wallets/617963656a409b8a6828dc3a09001de22af90400/transactions?minWithdrawal=0  | jq
[]
```

So giving `minWithdrawal=0` I'd expect to list all transactions actually, yet nothing is returned.

**Comment by piotr-iohk** [comment]
Able to confirm working on shelley_testnet also.

**Comment by piotr-iohk** [comment]
Closing this one. Issue for the corner case => https://github.com/input-output-hk/cardano-wallet/issues/1915.
