### ISSUE TITLE
Wallet doesn't support staging and other non-mainnet environments without address discrimination

### ISSUE THREAD

**Issue by disassembler** [cardano-foundation/cardano-wallet#1885]
# Context
 
 

Suggestion is to add a `--staging` flag that takes a genesis file but disables address discrimination. This is required for the mainnet candidate as it is a testnet that can't have network discrimination since we're using a utxo snpashot from mainnet.

Let's go for:
```
--mainnet
--testnet FILEPATH
--staging FILEPATH
```
Where staging supposes no explicit discrimination

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      |  |
| Platform     |           |
| Installation |             |

# Steps to Reproduce

1. ...

## Actual behavior
 

---

# Resolution 

- Extend network discrimination data-type with an extra `Staging` branch which should have an explicit magic, but behaves exactly the same has `Mainnet` ==> #1891 

---

# QA 

- Heavily relying on the type-system here, I've added a `Staging` branch and followed the compiler here. This required adding new instances to several type-classes (`EncodeAddress`, `DecodeAddress` etc ..) which were defined in terms of the `Mainnet` instances:

https://github.com/input-output-hk/cardano-wallet/blob/7f401a2b41a2098ce738a7718b652e64bc55f561/lib/core/src/Cardano/Wallet/Primitive/AddressDerivation.hs#L489-L490

https://github.com/input-output-hk/cardano-wallet/blob/7f401a2b41a2098ce738a7718b652e64bc55f561/lib/core/src/Cardano/Wallet/Primitive/AddressDerivation.hs#L564-L566

https://github.com/input-output-hk/cardano-wallet/blob/7f401a2b41a2098ce738a7718b652e64bc55f561/lib/core/src/Cardano/Wallet/Primitive/AddressDerivation.hs#L592-L594

https://github.com/input-output-hk/cardano-wallet/blob/7f401a2b41a2098ce738a7718b652e64bc55f561/lib/byron/src/Cardano/Wallet/Byron/Transaction/Size.hs#L131-L132

https://github.com/input-output-hk/cardano-wallet/blob/7f401a2b41a2098ce738a7718b652e64bc55f561/lib/byron/src/Cardano/Wallet/Byron/Transaction/Size.hs#L137-L138

https://github.com/input-output-hk/cardano-wallet/blob/7f401a2b41a2098ce738a7718b652e64bc55f561/lib/core/src/Cardano/Wallet/Api/Types.hs#L1408-L1409

https://github.com/input-output-hk/cardano-wallet/blob/7f401a2b41a2098ce738a7718b652e64bc55f561/lib/core/src/Cardano/Wallet/Api/Types.hs#L1416-L1417

The nice thing about this approach is that it works for _any_ target backend without requiring any code change. And since `Mainnet` is already well-tested, `Staging` also is.

- Also extended the `serve` command in Byron and Shelley to allow passing a `--staging` in addition to `--mainnet` or `--testnet`. Like `--testnet`, it requires an explicit genesis file, but it'll then behave like `--mainnet` with a custom genesis. 

> :information_source: Using the current mainnet genesis file, one could connect to the mainnet using `--staging` and the mainnet genesis file.

**Comment by piotr-iohk** [comment]
lgtm
