### ISSUE TITLE
Transaction fee changed

### ISSUE THREAD

**Issue by CONQUISTADORA0101** [cardano-foundation/cardano-wallet#1886]
# Context
 
 

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      |  |
| Platform     |           |
| Installation |             |

# Steps to Reproduce

1. ...

## Actual behavior
 

---

# Resolution 

---

# QA

**Comment by CONQUISTADORA0101** [comment]
standard transaction fee changed from .172629 to .574125 on 1 out of 9 transaction

**Comment by rvl** [comment]
Hello @CONQUISTADORA0101
This is expected.
The transaction fee depends on the transaction size.
The transaction size depends on the number of transaction inputs,
which depends on the coins which were selected to make the payment.
You can check your transactions in Cardano explorer to see.

**Comment by rvl** [comment]
The random-improve coin selection strategy is designed to reduce "dust" and therefore fees on average _over time_. As a consequence, individual transactions may have slightly higher fees than they could have.

**Comment by CONQUISTADORA0101** [comment]
Thank you
