### ISSUE TITLE
Introduce minimum UTxO value

### ISSUE THREAD

**Issue by paweljakubas** [cardano-foundation/cardano-wallet#1893]
# Context

Minimal UTXO size needs to abide by the min utxo value set by the protocol (initially in the genesis file, and via protocol updates). This value is currently set to `0` to not break the current behavior of the system but we are looking into increasing it for mainnet.

# Decision

We add minimumUTxOValue in ProtocolParameters

# Acceptance Criteria

1. `ProtocolParameters` and `ApiNetwrokParameters` are changed. 
2. For shelley the parameter is taken from PParams, for byron and jormungandr it is 0
3. the parameter is used in dustThreshold
4. Handle the migration when adding new column

---

# Development 

# QA 

Please notice that `ApiNetworkParameters` has changed (new field added), also showed the value in shelley integration test. For byron/jormungandr it is `minimumUTxOvalue` is `0`.

**Comment by piotr-iohk** [comment]
Do I understand correctly that this will translate into minimal transaction output value and hence minimal transaction amount that can be sent?

If so It would be nice maybe to set this in out CI's [genesis.yaml](https://github.com/input-output-hk/cardano-wallet/blob/master/lib/shelley/test/data/cardano-node-shelley/genesis.yaml). I have tried to explicitely add there (minUTxOValue: 1), but the cluster failed to start...

I have also wanted to try it on `mainnet_candidate` testnet, where `"minUTxOValue": 1000000`, but wallet fails to sync with that network currently -> https://input-output-rnd.slack.com/archives/GBT05825V/p1594713488004400.

**Comment by paweljakubas** [comment]
@piotr-iohk  the `minUTxOvalue` will set `dustThreshold` in feeOpt -> see comment below https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/src/Cardano/Wallet/Primitive/Fee.hs#L84

**Comment by piotr-iohk** [comment]
I have requested minUtxoValue change on shelley_testnet. It used to be 0 and now is 1ADA. I see that value in `GET /network/parameters` is updated properly.

But when now one tries to send transaction with amt < 1, the wallet returns `500`:

```
Code = 500,
Message = {"code":"created_invalid_transaction","message":"That's embarrassing. It looks like I've created an invalid transaction that could not be parsed by the node. Here's an error message that may help with debugging: ApplyTxError [LedgerFailure (UtxowFailure (UtxoFailure (OutputTooSmallUTxO [TxOut (Addr Testnet (KeyHashObj (KeyHash d988972fff7619482878b5413c38c4981451eac7a27846c4eefd4a0e)) (StakeRefBase (KeyHashObj (KeyHash ff7b5d41fa8cb555b6449601d84967bd9b0245a3c530044d8094ee36)))) (Coin 999999)])))]"}
```

Perhaps, that's not really related with that "story"? If so, I'll close this one and report it elsewhere.

@paweljakubas let me know.

**Comment by piotr-iohk** [comment]
Closing this one. Bug for the issue -> https://github.com/input-output-hk/cardano-wallet/issues/1914.
