### ISSUE TITLE
Shelley activation countdown

### ISSUE THREAD

**Issue by paweljakubas** [cardano-foundation/cardano-wallet#1917]
# Context

We want to have information when the era transition happens

# Decision

we are extending network parameters and account for era transition information which will be powered from consensus layer via local network protocol

# Acceptance Criteria

1. NetworkParameters is extended
2. swagger is updated
3. we support the information about transition from consensus layer via local network protocol
4. test this feature if possible (presumable within hfc node)

---

# Development 

# QA

**Comment by piotr-iohk** [comment]
lgtm
