### ISSUE TITLE
Hard fork integration tests

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#1920]
# Context

ADP-356

With the hard fork combinator, we now have a wallet that must work in both byron and shelley eras.

Therefore we should run our integration tests during both eras.

# Decision

1. Adjust the local cardano cluster setup so that it runs in dual era mode and is able to hard fork.
2. Modify cardano-wallet-shelley:test:integration API specs so that they are run initially in byron mode.
3. Command the cluster to complete a hard fork in the local cluster as a test setup step for...
4. Running the integration API specs again.

# Acceptance Criteria

1. Integration test suide API specs must pass in both byron and shelley era on a local cardano cluster.

---

# Development 

- #1924 test cluster setup, which was merged into #1909 

# QA 

- With #1909, all shelley integration tests are run on Byron;Shelley _after_ the fork.
- We can no longer add faucet funds in the Shelley-genesis. After the fork we manually construct txs from byron faucets to all faucet address defined [here](https://github.com/input-output-hk/cardano-wallet/blob/71c0b8fd10aaf7e09c62c42571780f7676381584/lib/core-integration/src/Test/Integration/Faucet.hs#L1472-L1499) 
- I think Matthias disabled two flaky tests relating to hardware wallet address listing
- Relevant test setup code: https://github.com/input-output-hk/cardano-wallet/blob/71c0b8fd10aaf7e09c62c42571780f7676381584/lib/shelley/test/integration/Main.hs#L221-L242
- We don't run any tests _before_ the fork. We are probably going to release very close to the fork anyway.

**Comment by piotr-iohk** [comment]
lgtm
