### ISSUE TITLE
Minimum utxo value should not influence inputs

### ISSUE THREAD

**Issue by paweljakubas** [cardano-foundation/cardano-wallet#1926]
# Context

We have #1916 dealing with outputs in the context of minimum value utxo. Also in #1894 we make dust determined by it. 
The min value rule in the ledger is simple: new outputs must be bigger than the minimum.
The min value can be changed, and this can lead to existing UTxOs being below the current minimum for new outputs. Those existing UTxOs are still spendable.

# Decision

Revert the dependence of input dusting on minmium UTxO value

# Acceptance Criteria

---

# Development 

# QA

**Comment by piotr-iohk** [comment]
Do I understand correctly that this change will be discarded? @paweljakubas, @KtorZ

**Comment by KtorZ** [comment]
This issue is to be discarded indeed. The dust threshold has no influence on the inputs but operate on the change outputs.

**Comment by piotr-iohk** [comment]
Closing.
