### ISSUE TITLE
Do not list retired pools in the API.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#1937]
# Context

As part of the work to track stake pool retirements, we need to prevent pools that have already retired from being listed in public API operations.

# Decision

- Prevent the `ListStakePools` API operation from listing pools that have already retired.
- If practical, use a database query to filter out retired pools, rather than in-memory filter.

# Acceptance Criteria

- [x] The wallet must not include pools that have already retired in the list of known pools returned by the API `ListStakePools` operation.

# Development 
- https://github.com/input-output-hk/cardano-wallet/pull/1945

# QA 

- [x] Provide an integration test that:

    1. Registers a pool _**p**_
    1. Publishes a retirement certificate for pool _**p**_ with retirement epoch _**e**_.
    1. Verifies that when the current epoch is equal to or later than _**e**_, pool _**p**_ does not appear in the list of stake pools returned by `ListStakePools`.

# Notes

Note that the above integration test is a compromise.

Ideally, a more complete integration test would verify that a pool is still visible right up to the moment before the pool has actually retired. See: https://jira.iohk.io/browse/ADP-385

**Comment by piotr-iohk** [comment]
lgtm
