### ISSUE TITLE
Provide more information on failure to determine current epoch.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#1939]
# Context

As part of the work to track stake pool retirements, we must reject attempts to join stake pools that have already retired.

In order to do this, we must compare the pool's retirement epoch with the _current_ epoch.

However, determining the current epoch is an operation that might fail:

https://github.com/input-output-hk/cardano-wallet/blob/05d377418b02e59e1299a0eaee135802c52735d2/lib/core/src/Cardano/Wallet/Primitive/Slotting.hs#L108-L109

If we encounter this condition, we currently report the following error:

https://github.com/input-output-hk/cardano-wallet/blob/05d377418b02e59e1299a0eaee135802c52735d2/lib/core/src/Cardano/Wallet/Api/Server.hs#L1902-L1906

# Decision

Determine the conditions under which this operation may fail, and if necessary, update the error message to be more informative.

# Acceptance Criteria

- [x] The error message associated with `ErrUnableToDetermineCurrentEpoch` should describe a course of action for the user to take.

# Development 

See https://github.com/input-output-hk/cardano-wallet/pull/1992

# QA 

See https://github.com/input-output-hk/cardano-wallet/pull/1992

**Comment by jonathanknowles** [comment]
@Anviking Do you have any opinion on how we might make this particular error more informative?

**Comment by Anviking** [comment]
It's possible with #1943, with the change from `TimeInterpreter IO` to `TimeInterpreter (ExceptT IO PastHorizonException)` (Sorry, I think I indicated some time that the `Nothing` of `currentEpoch` could "include" `PastHorizonException`, but that is not the case.)

There should be reasons for failure:
- Current time is behind genesis. Action: 🤷‍♂️
- Node is in the Byron era of Byron;Shelley, and the current time is beyond our forecast zone. Action: Wait for the node to sync more

A concrete example of `PastHorizonException` behaviour [here](https://input-output-rnd.slack.com/archives/CFKLUH4R0/p1595511029493900), in case it is useful for context.
