### ISSUE TITLE
Migration of wallets with utxos having <= minUTxOValue

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#1950]
# Context
 
Introducing minUTxO value parameter causes problems migrating such wallets.

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | 2020.7.6 |
| Platform     | all          |
| Installation | from release          |

# Steps to Reproduce

1. Try to migrate wallet (byron or shelley) that have utxos <= minUTxO value

## Expected behavior

Possible to migrate.

## Actual behavior
 
```
Code = 500,
Message = {"code":"created_invalid_transaction","message":"That's embarrassing. It looks like I've created an invalid transaction that could not be parsed by the node. Here's an error message that may help with debugging: HardForkApplyTxErrFromEra S (Z (WrapApplyTxErr {unwrapApplyTxErr = ApplyTxError [LedgerFailure (UtxowFailure (UtxoFailure (OutputTooSmallUTxO [TxOutCompact \"\\SOH>\\141\\169\\183\\139\\STX\\199\\251\\DC2N\\t\\206i\\151\\232.\\147\\148\\167\\ACK\\r\\168\\US\\152\\r\\190M$\\255{]A\\250\\140\\181U\\182D\\150\\SOH\\216Ig\\189\\155\\STXE\\163\\197\\&0\\EOTM\\128\\148\\238\\&6\" 807747])))]}))"}
```

---

# Resolution 

@paweljakubas:
 
>if we have minUTxO=1ada and in the big wallet we have things to migrate < 1 ada we need to coalesce them to have each output >=minUTxO, - if that happens not possible to do 1-to1 migration (edited) 

>so the migration test should be refactored in such a way that :
>1. we get network params and here minUtxovalue
>2. account for this minUtxovalue, in such a way that we coalesce outputs into bigger ones if they happen to be less than minUtxovalue. if all outputs are >= minUtxovalue than we still have 1-to1 mapping. otherwise, not so easy. we need to also account for this in utxo statistics expectations

---

# QA

**Comment by KtorZ** [comment]
see #1947

**Comment by piotr-iohk** [comment]
lgtm
