### ISSUE TITLE
Balance temporarily increases when spending rewards

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#1955]
# Context
 
- When spending rewards, we spend everything
- Restoring a ITN wallet is an easy way to get a wallet with only rewards
- Think Alan created a thread about this in #adrestia-dev some time ago

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      |  |
| Platform     |           |
| Installation |             |

# Steps to Reproduce

1. Have a wallet with a noticeable amount of rewards
2. Send a outgoing tx

## Expected behavior

1. While the balance is pending, the balance should either stay the same or decrease

## Actual behavior

1. The wallet balance doubles when spending ada (for wallet with 99% rewards)
2. Balance goes back to normal when the tx is confirmed
 

---

# Resolution 

- I think a simple tweak to https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/src/Cardano/Wallet/Primitive/Model.hs#L308 would be enough

---

# QA 

- Added a property test showing that for any wallet, for any non empty set of pending transaction: the total balance with pending transaction is strictly smaller than the total balance without any pending. This simple assertion was actually failing without a fix here because the withdrawals would be counted twice when some pending transaction had withdrawals (raw and as part of pending change output). 

https://github.com/input-output-hk/cardano-wallet/blob/905277f370093ab43c9246ee6d7c32df7114fe1d/lib/core/test/unit/Cardano/Wallet/Primitive/ModelSpec.hs#L233-L255

- Other integration and unit test still pass after the fix without any change.

**Comment by piotr-iohk** [comment]
I have tried to test it also on MC4 with earned rewards.
 - while transaction is `pending` there is no increase in total amount
 - for a very brief period upon transaction transition into `in_ledger` I _think_ I saw doubled total amount
 - then it was all OK when it was already `in_ledger`

Is it possible?

**Comment by Anviking** [comment]
That sounds like:

> I'm wondering if there could still be strange behaviour from race-conditions from the fact that the reward-balance and wallet utxo are not guaranteed to be in-sync.

So I think that is currently possible for short periods of time.

**Comment by KtorZ** [comment]
> Is it possible?

It is possible indeed. The reward balance update and the block processing happens concurrently in two separate workers. They're invoked roughly at the same time but possibly with a visible delay. As a result there could be a point in time where there's no more pending withdrawal, but the balance hasn't been updated to `0` yet. 

We could "force" our cached balance to zero after processing a withdrawal (within the same database transaction) to prevent this.

**Comment by piotr-iohk** [comment]
>We could "force" our cached balance to zero after processing a withdrawal (within the same database transaction) to prevent this.

Shall we return it ticket to "in progress"?

**Comment by KtorZ** [comment]
Oui.

**Comment by KtorZ** [comment]
Moved to; https://jira.iohk.io/browse/ADP-611
