### ISSUE TITLE
Concern about signature used in Cardano

### ISSUE THREAD

**Issue by QiFengWHu** [cardano-foundation/cardano-wallet#1956]
Dear developers, I'm wondering about the signature used in Cardano. Is it a general version of Ed25519, or I mean does the message need to be hashed before signing? According to the NIST standard, there are two versions of Ed25519, there are EdDSA and HashEdDSA. Looking forward to hearing from you.

**Comment by rvl** [comment]
Hi, we use the cryptonite [Crypto.PubKey.Ed25519](http://hackage.haskell.org/package/cryptonite-0.25/docs/Crypto-PubKey-Ed25519.html) library for signing transactions. The transaction body is hashed before signing.

**Comment by QiFengWHu** [comment]
I see, thanks a lot.

**Comment by QiFengWHu** [comment]
I see, thanks a lot.

**Comment by rvl** [comment]
Correction @QiFengWHu - there are two payment signing schemes in Cardano Shelley - "normal" and "extended". cardano-wallet only uses "extended" Ed25519. See [BIP32-Ed25519](https://github.com/input-output-hk/adrestia/blob/master/user-guide/static/Ed25519_BIP.pdf) for details and [cardano-crypto](https://github.com/input-output-hk/cardano-crypto/) for the implementation.

**Comment by QiFengWHu** [comment]
The cardano-crypto for the implementation is really helpful. You are so nice to answer me by this resources.
By the way, the Ed25519_BIP.pdf is somehow invalid now, it's kindly unfortunate.
