### ISSUE TITLE
Prepare for shelley hardfork

### ISSUE THREAD

**Issue by lijianl** [cardano-foundation/cardano-wallet#1958]
I have a cardno-wallet service running of Byron-Wallets and waiting for the Shelley hardfork coming soon.

what should I do to prepare for this hardfork, any information, or link to introduce? 

Do I need to change my wallet API from 'byron' to SHELLEY, any else to pay attention to?

**Comment by KtorZ** [comment]
We'll detail what to do in the upcoming release notes. But in brief:

- The API stays the same. The "Byron" sections of the API keeps working identically (modulo disclaimer below). 
- Byron wallets won't have any delegation capability, so if you intend to delegate, you'll have to create new "Shelley" wallets.
- You'd have to use a new binary that can survive the hard-fork (upcoming release)
- On this new binary, until the hard-fork happen, you'll be unable to send transactions (but reading from the chain would work without issue).

**Comment by rvl** [comment]
See the [releases page](https://github.com/input-output-hk/cardano-wallet/releases) for the Shelley wallet.
