### ISSUE TITLE
Sort pools with equal rewards randomly

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#1959]
# Context

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      |  |
| Platform     |           |
| Installation |             |

# Steps to Reproduce

1. List pools

## Expected behavior

1. Having a poolId starting with `0` shouldn't be better than one starting with `f`
2. Pools with equal rewards are sorted randomly
3. The random order is unique to each wallet/user
4. The random order is the consistent for the same wallet/user

## Actual behavior

1. It seems pools are ranked alphabetically on poolId, when they have equal reards
 

---

# Resolution 

- Make sure to sort pools that have identical rewards 

---

# QA 

- Pools are now sorted "twice", a first time based on weight that is randomly attributed to them. The weights are generate from a seed that is common to each wallet of a server (so each wallet gets the same randomization), but different across server instances. Then, that randomized list of pools is sorted again based on their non-myopic rewards. In particular, Haskell's `sortOn` function used for the second sorting has the nice property of _"keeping duplicates in the order they appeared in the input."_, which makes the whole thing work nicely. 

![Screenshot from 2020-07-28 14-49-46](https://user-images.githubusercontent.com/5680256/88667405-9e489f80-d0e1-11ea-9134-74d8282d4f08.png)

https://github.com/input-output-hk/cardano-wallet/blob/aab4ddf15fd727b4ed476fa17f6be6c69e94a6e7/lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs#L227-L248

- Existing integration tests still pass, which means that pools are still ordered by descending non-myopic rewards. Testing however that pools with identical rewards are correctly randomized is tricky.

- Some additional testing was done on the mainnet candidate manually where it appeared "obvious" that new pools were no longer ordered by pool's id.

**Comment by piotr-iohk** [comment]
lgtm. Also looking a bit on mainnet candidate and looks like pools on different wallets are sorted differently.
