### ISSUE TITLE
Stake pool DB worker doesn't save sync progress in Byron

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#1963]
# Context
 

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      |  |
| Platform     |           |
| Installation |             |

# Steps to Reproduce

1. Start a `cardano-node` connected to the byron mainnet
1. `cardano-wallet-shelley serve --node-socket socket --mainnet --database wallet-db`
2. wait 20 s
3. `ctrl-c`
4. `cardano-wallet-shelley serve --node-socket socket --mainnet --database wallet-db`

## Expected behavior

The sync progress from the first launch is saved, and it doesn't have to start from the beginning after quitting.

## Actual behavior

It restarts from genesis the second time.

Syncing through the whole of byron again may take some time. I guess it takes ~10 minutes on my machine, if the node is already synced, so while not optimal, I believe it should be fine for now.
 

---

# Resolution 

---

# QA 

Currently there are no integration tests. All we do is test the `putHeaders` and `listHeaders` DBLayer functions: https://github.com/input-output-hk/cardano-wallet/pull/2138/files#diff-c3e090fb717915e32577d1c7311e8ab5392c830dec9a705e025f0bf84af6b099

This tests the new table `block_headers`.

Testing that the wallet resumes the chain at a certain point is very easy on testnet though. Starting sync process, crtl+c and start wallet again. Then check that it resumes on the previous block height.

**Comment by hasufell** [comment]
Why is this in progress?

**Comment by KtorZ** [comment]
@hasufell good question, why is it not in QA ?

**Comment by hasufell** [comment]
@piotr-iohk added QA section... I believe you already tested this, but we didn't follow the process properly I think

**Comment by piotr-iohk** [comment]
LGTM. I have added manual test for this in https://github.com/input-output-hk/cardano-wallet/pull/2271 / https://github.com/input-output-hk/cardano-wallet/commit/466a43b0fc82c313174f530a0016e1654be5d008.
