### ISSUE TITLE
An error during the sync of existence wallets "Unexpected error following the chain"

### ISSUE THREAD

**Issue by Fell-x27** [cardano-foundation/cardano-wallet#1964]
# Context

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | Current master |
| Platform     | Linux    |
| Installation | From sources          |

# Steps to Reproduce

1. Launch the Node 1.18.
2. Launch the cardano-wallet-byron over old wallets storage (from version for node 1.15)
3. Let it sync..
4. Wait...wait...
5. PROFIT!

## Expected behavior
No errors.

## Actual behavior
 
```
cardano-wallet.wallet-engine:Error:79] [2020-07-27 20:55:25.35 UTC] 4e5b0255: Unexpected error following the chain: syncProgress: (-9205824073709551616) % 1 is out of bounds
CallStack (from HasCallStack):
  error, called at src/Cardano/Wallet/Primitive/SyncProgress.hs:151:27 in cardano-wallet-core-2020.7.6-GqaUpTGB29sHAhnzgdRxMB:Cardano.Wallet.Primitive.SyncProgress
```
One by one.

And errors in the Node logs:

`[34d4:cardano.node.LocalErrorPolicy:Error:42] [2020-07-27 20:55:26.99 UTC] [String "ErrorPolicyUnhandledApplicationException (MuxError MuxBearerClosed \"<socket: 29> closed when reading data, waiting on next header True\")",String "ErrorPolicyTrace",String "LocalAddress {getFilePath = \"\"}"]`

---

# Resolution 

---

# QA 

- Regression test 39c4106fe3d44a7ea175cd2309fbe5b8b3efd6a4 that fails without https://github.com/input-output-hk/cardano-wallet/pull/1943/commits/895472379650ae11606bef70f05a6b4ec51c1970

**Comment by KtorZ** [comment]
There's an overflow in the sync progress calculation indeed. #1943 should make things better here.

**Comment by piotr-iohk** [comment]
ok
