### ISSUE TITLE
Redeem ITN rewards from mainet wallet 

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1965]
# Context

- As a ADA stakeholder who participated in the ITN,
- I want to be able to redeem my rewards from the ITN to my mainnet wallet,
- Without having to send a transaction to my ITN account first.
- So that I can enjoy my ITN rewards. 

# Decision

- Make it possible to redeem rewards of a wallet A from the API using another wallet B. 

# Acceptance Criteria

1. It _must not_ be necessary to restore the ITN wallet in order to redeem its rewards. 

---

# Development 

- Add a new `withdrawal` field to Shelley transactions to replace the `?withdrawReward` and extend its behavior ==> #1967 

# QA 

- See documentation on:
    - [postTransaction](https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/postTransaction)
    - [postTransactionFee](https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/postTransactionFee)

- Added extensive test scenarios to cover for various cases. The test scenarios use newly introduced "rewardWallet" faucets which are wallets which come with pre-existing rewards. 

    - https://github.com/input-output-hk/cardano-wallet/blob/5af6e35a4f70ca8e1cebe413b19a99439e04addb/lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs#L1258-L1287

    - https://github.com/input-output-hk/cardano-wallet/blob/5af6e35a4f70ca8e1cebe413b19a99439e04addb/lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs#L1289-L1324

    - https://github.com/input-output-hk/cardano-wallet/blob/5af6e35a4f70ca8e1cebe413b19a99439e04addb/lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs#L1326-L1357

    - https://github.com/input-output-hk/cardano-wallet/blob/5af6e35a4f70ca8e1cebe413b19a99439e04addb/lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs#L1359-L1378

    - https://github.com/input-output-hk/cardano-wallet/blob/5af6e35a4f70ca8e1cebe413b19a99439e04addb/lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs#L1380-L1398

**Comment by darko-mijic** [comment]
Looking forward to this one. :)

**Comment by piotr-iohk** [comment]
I have tested manually on MC4 and locally on cluster, trying out different cases:

 - Can redeem rewards from self/other sending more than rewards, but utxo should cover
 - Can redeem rewards from self/other  sending more than utxo, rewards should cover
 - Can redeem sending my all utxo, rewards should cover fees
 - Can redeem sending all rewards, utxo should cover fees
 - Can't redeem rewards from other when utxo is 0
 - Can't redeem rewards from self when utxo is 0
 - Not-enough money when redeeming > utxo + rewards
 - Cannot cover fee when redeeming = utxo + rewards

Looking at the transactions it seems everything OK, in terms of amount / input / outputs on the receiver and sender side. (Hopefully I haven't missed anything).

Added PR with some additional cases also -> https://github.com/input-output-hk/cardano-wallet/pull/1987

One thing I was wondering about is that when you withdraw rewards from a foreign wallet, there is no evidence (in terms of transaction history on that foreign wallet, that there was a withdrawal). Transaction is only listed on a wallet from where you were doing transaction only (and a receiver wallet.)

**Comment by KtorZ** [comment]
Scenarios have been a bit reviewed in #1987 to avoid having too many cases taking _a long time_ at the integration level. Many of the original edge-cases in #1987 are actually tested at the unit level via the coin selection algorithm, so only a few end-to-end tests are needed to confirm that the behavior works as intended :+1:
