### ISSUE TITLE
Ability to delegate (and pledge) to multiple pools from a single wallet

### ISSUE THREAD

**Issue by disassembler** [cardano-foundation/cardano-wallet#1986]
# Context

The general idea is that we would like the ability to have multiple stake addresses generated from a single wallet root private key and be able to transparently choose multiple pools to delegate to and the wallet would handle moving balances around to meet those delegations. The primary driver for this feature is to be able to pledge multiple pools from a single ledger device. We'd have to extend the current single address derived to a mutli-address derived setup, or extend it to support multiple accounts where each account has it's own stake address.

# Decision

# Acceptance Criteria

---

# Development 

# QA

**Comment by KtorZ** [comment]
That's one complicated thing.
