### ISSUE TITLE
Lost addresses when restore wallet from cardano-sl to byron

### ISSUE THREAD

**Issue by androzd** [cardano-foundation/cardano-wallet#1989]
# Context
 
Clean inputoutput/cardano-node:1.18.0
Clean any of inputoutput/cardano-wallet:shelley or inputoutput/cardano-wallet:byron

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | inputoutput/cardano-wallet:shelley or inputoutput/cardano-wallet:byron |
| Platform     | Docker |
| Installation | Docker |

# Steps to Reproduce

Run in terminal:
1. curl -X POST http://localhost:8090/v2/byron-wallets -H "Content-Type: application/json" -d '{"style": "random", "name": "root", "passphrase": "$PASSPHRASE", "mnemonic_sentence": [$words]}'

## Expected behavior

All addresses exists on old wallet exists on new wallet

## Actual behavior
 
Old wallet had ~1800 addresses, new one had only ~400 addresses

**Comment by KtorZ** [comment]
Restoring a wallet is a process which uses on-chain data. Change addresses generated locally and never used in chain can't be restored from the chain.

Therefore, you'll have to manually import those pre-generates unused address.

See: https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/importAddresses
