### ISSUE TITLE
cardano-wallet sync error

### ISSUE THREAD

**Issue by lijianl** [cardano-foundation/cardano-wallet#1990]
deplosy cardano-wallet version latest master and running with `nix-build -A cardano-wallet-byron`. 

`[cardano-wallet.wallet-engine:Error:37] [2020-08-01 07:51:14.54 UTC] 5180708f: Unexpected error following the chain: ExceptionInLinkedThread ThreadId 389937 DecoderFailure (ChainSync (ByronBlock) (Tip ByronBlock)) ServerAgency TokNext TokCanAwait) (DeserialiseFailure 1015 "Found unknown tag 2 while decoding Block")`

sync block by error upon? 

what should i do

**Comment by KtorZ** [comment]
Do not use cardano-wallet-byron. This version can no longer sync behind the hard fork. It is currently being removed from the repository

Instead, use cardano-wallet-shelley
