### ISSUE TITLE
Api link can not be reached

### ISSUE THREAD

**Issue by lijianl** [cardano-foundation/cardano-wallet#1991]
https://input-output-hk.github.io/cardano-wallet/api/edge

why this link can not be reached?  any this wrong happened

**Comment by jonathanknowles** [comment]
> https://input-output-hk.github.io/cardano-wallet/api/edge
> 
> why this link can not be reached? any this wrong happened

Hi @lijianl 

I've just tried, and the link works from my location. Could you try again and let us know if it's still not working for you?

Some other things to try:

1. Are you able to reach the `input-output-hk.github.io` with a ping?

    Try the following in a terminal:
    ```sh
    $ ping input-output-hk.github.io
    PING input-output-hk.github.io (185.199.109.153) 56(84) bytes of data.
    64 bytes from 185.199.109.153 (185.199.109.153): icmp_seq=1 ttl=56 time=35.1 ms
    64 bytes from 185.199.109.153 (185.199.109.153): icmp_seq=2 ttl=56 time=36.6 ms
    ...
    ```
2. Are you able to resolve the domain name `input-output-hk.github.io`?

    Try the following in a terminal:

    ```sh
    $ host input-output-hk.github.io
    input-output-hk.github.io has address 185.199.109.153
    input-output-hk.github.io has address 185.199.108.153
    input-output-hk.github.io has address 185.199.111.153
    input-output-hk.github.io has address 185.199.110.153
    ```
```

**Comment by lijianl** [comment]
thanks for reply

**Comment by rvl** [comment]
It works for me too. The web site is hosted by GitHub.
If you still can't access it, use https://github.com/input-output-hk/cardano-wallet/blob/master/specifications/api/swagger.yaml instead.
