### ISSUE TITLE
account syncing error

### ISSUE THREAD

**Issue by lijianl** [cardano-foundation/cardano-wallet#1993]
my account's  syncing  was blocked by error below:

`[cardano-wallet.wallet-engine:Error:5452] [2020-08-03 06:41:30.34 UTC] 5180708f: Unexpected error following the chain: ExceptionInLinkedThread ThreadId 125077 DecoderFailure (ChainSync (ByronBlock) (Tip ByronBlock)) ServerAgency TokNext TokCanAwait) (DeserialiseFailure 1015 "Found unknown tag 2 while decoding Block")`   from cardano-wallet

and cardano-node log error:
`[nuls-nov:cardano.node.LocalErrorPolicy:Error:54] [2020-08-03 06:42:11.18 UTC] [String "ErrorPolicyUnhandledApplicationException (MuxError (MuxIOException writev: resource vanished (Broken pipe)) \"(sendAll errored)\")",String "ErrorPolicyTrace",String "LocalAddress {getFilePath = \"\"}"]`

my byron-wallet syncing was blocked at 99.58 ....?  what are the meanings of error from log.

I build cardano-node from master, 
`git clone https://github.com/input-output-hk/cardano-node.git 
cd cardano-node
nix-build -A scripts.mainnet.node -o mainnet-node-local && ./mainnet-node-local
` and build cardano-wallet from master too:
`git clone https://github.com/input-output-hk/cardano-wallet.git
nix-build -A cardano-wallet-byron
cardano-wallet serve --node-socket ~/cardano-node/state-node-mainnet/node.socket --mainnet --database /tmp/mainnet
`
and restore my wallet with API  below
`POST http://xxx.xxx.xxx.xxx:8091/v2/byron-wallets`. 
then wallet syncing met error. what happened?  and the meaning of the error

**Comment by lijianl** [comment]
I have some ADA in my wallet, and the wallet is not available since syncing blocked.
it  is very urgent for me,  could you guys help me with these error..

**Comment by KtorZ** [comment]
Hi, the mainnet has _forked_  since July 29th to a new Era. Therefore, you need to use a version of the wallet that is compatible with this new era. We're in the process of removing `cardano-wallet-byron`, in the meantime, you ought to use `cardano-wallet-shelley`. 

Cheers.

**Comment by lijianl** [comment]
how to build cardano-wallet from source  to support Shelley ERA?  could you give some link or tips to move wallet from byron to shelley

**Comment by lijianl** [comment]
> Hi, the mainnet has _forked_ since July 29th to a new Era. Therefore, you need to use a version of the wallet that is compatible with this new era. We're in the process of removing `cardano-wallet-byron`, in the meantime, you ought to use `cardano-wallet-shelley`.
> 
> Cheers.

could you give some links to introduce  how to move to new ERA with source code

**Comment by lijianl** [comment]
cardano-wallet only provided byron type `nix-build -A cardano-wallet-byron`, any building way for shelley with source code

**Comment by jonathanknowles** [comment]
> cardano-wallet only provided byron type `nix-build -A cardano-wallet-byron`, any building way for shelley with source code

Have you tried:

`$ nix-build -A cardano-wallet-shelley`

You might want to check that you've pulled the latest changes to the `cardano-wallet` repository, or just clone it again from scratch.

**Comment by lijianl** [comment]
thanks for your replay, I will try it

**Comment by lijianl** [comment]
hello.
I build cardano-wallet with `nix-build -A cardano-wallet-shelley`; 

however it is impossible to retore byron-wallet into shelly, it happened `"message": "Error in $['mnemonic_sentence']: Invalid number of words: 15, 18, 21 or 24 words are expected."`, indeed my byron-wallet has 12 words.

what should I do to retore my byron-wallet and resue my ADA from this wallet

**Comment by lijianl** [comment]
should I build source code with Shelley mode and use API with byron mode? isn't it  wired

**Comment by KtorZ** [comment]
@lijianl, yes. The naming may looks a bit confusing but, the *entire* API is available now because, the chain isn't just Shelley. The chain is the continuation of Byron -> Shelley. So, blocks, addresses, transactions etc.. are present in BOTH format in the chain. Therefore, anything that existed in Byron still exists after the hard fork. Wallets that existed in Byron and new Shelley wallets have different address formats, but so-called Byron wallets are still valid and exist in the Shelley era as well.

**Comment by lijianl** [comment]
thanks for your reply and I have solved my problem;
Here is the summary: 

1. build  Cardano-node from source:  v-1.18.0
`
git clone https://github.com/input-output-hk/cardano-node.git
cd cardano-node
nix-build -A scripts.mainnet.node -o mainnet-node-local
`

2. build Cardano-wallet from source: v-1.18.0:

`
git clone from source
nix-build -A cardano-wallet-shelley
`

3.  retore my wallet and serve the wallet with [byron-api](https://input-output-hk.github.io/cardano-wallet/api/edge/#tag/Byron-Wallets)


Thanks again!

**Comment by jonathanknowles** [comment]
> thanks for your reply and I have solved my problem;
> Here is the summary:
>     1. build  Cardano-node from source:  v-1.18.0
>        `git clone https://github.com/input-output-hk/cardano-node.git cd cardano-node nix-build -A scripts.mainnet.node -o mainnet-node-local`
>     2. build Cardano-wallet from source: v-1.18.0:
> `git clone from source nix-build -A cardano-wallet-shelley`
>     1. retore my wallet and serve the wallet with [byron-api](https://input-output-hk.github.io/cardano-wallet/api/edge/#tag/Byron-Wallets)
> Thanks again!

@lijianl Good to hear that it's now working for you!
