### ISSUE TITLE
Wallets are extremely slow to restore for large wallets (e.g. exchanges).

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#1997]
# Context
 
 

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | edge  |
| Platform     | All           |
| Installation |             |

# Steps to Reproduce

1. Have a big wallet (50k+ pending addresses and UTxO). 
2. Restore a wallet an observe

## Expected behavior

1. The wallet _just work_. 

## Actual behavior
 

1. Things get really slow.

---

# Resolution 

1. Try adding more logs to measure various actions of the restoration process to better pinpoint the problem ==> #1994 
2. ~Try using sequential wallets that are storing _diffs_ instead of entire checkpoints~. Aborted, it seems that the performance gain is pretty minor for this, even for big wallets. 
3. Add logging to benchmarks to see the influence of tracers on benchmarks ==> #2030
4. Fix usage of `filterSeverity` and apply it one level earlier (one the Tracer, and not the Trace itself, filtering needs to happen _before_ the `LogObject` is constructed) ==> #2028 

---

# QA 

- Added read/write of RndState in the database benchmark to also measure db operation for random wallets.

- Enabled a non-null tracer in benchmarks to reproduce the production setup. Benchmarks went 2 to 4 times slower, applying the fix turned them back to time comparable with a `nullTracer` (see comments on https://github.com/input-output-hk/cardano-wallet/pull/2030).

- Our partners that had difficulty restoring confirmed that they were now able to restore their wallets.

**Comment by Anviking** [comment]
This is from a recent benchmark:
<img width="853" alt="Skärmavbild 2020-08-10 kl  12 40 45" src="https://user-images.githubusercontent.com/304423/89775381-f501a080-db07-11ea-899e-fa015cab7704.png">

The _shape_ of 1% seems very peculiar, and I think it used to be [≈50 min](https://cardano-wallet-benchmarks.herokuapp.com/mainnet-restoration) instead of ≈ 1h35 min

**Comment by KtorZ** [comment]
I'd actually somewhat expect this shape for the last k blocks (since checkpoints are much more frequent in this area). but, the behavior seems to drastically change around block #600.000 o.O ... That makes no sense. 

**edit:** The restoration actually failed around 12%: 

![Screenshot from 2020-08-10 13-05-45](https://user-images.githubusercontent.com/5680256/89776474-46129400-db0a-11ea-8f09-647dca3627f7.png)
