### ISSUE TITLE
Add branch protections in GitHub & team permissions 

### ISSUE THREAD

**Issue by akegalj** [cardano-foundation/cardano-wallet#2]
# Context

As part of setting up repo for wallet rewrite.

# Decision

[x] Every part of cardano-wallet team must get merge permission.
[x] Merge permission must be available if:
 * at least one reviewer accpeted the PR
 * our CI is green

NOTE: Reviews will be done mostly in pairs (pair-programming) with dev rotation around the code so that everyone is familiar with bits of the whole system.

---

# Development Plan

Explained in the section above

# PR

None.

# QA 

Done. See: [settings/branches](https://github.com/input-output-hk/cardano-wallet/settings/branches)

(Not sure if one needs admin access to see these settings but, just in case, for what it's worth :joy: :)

![image](https://user-images.githubusercontent.com/5680256/53641724-1df1e680-3c30-11e9-846b-0374bef15610.png)

```
$ git push origin master
Counting objects: 5, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 711.10 KiB | 0 bytes/s, done.
Total 5 (delta 0), reused 0 (delta 0)
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least 1 approving review is required by reviewers with write access.
To git@github.com:input-output-hk/cardano-wallet.git
 ! [remote rejected] HEAD -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:input-output-hk/cardano-wallet.git'
```

**Comment by piotr-iohk** [comment]
lgtm :+1: 
(indeed, one needs admin access to see these settings :)
