### ISSUE TITLE
Define type primitives needed to represent a wallet

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#20]
# Context

As per the [specification](https://github.com/input-output-hk/cardano-wallet/blob/master/specifications/wallet/formal-specification-for-a-cardano-wallet.pdf), there are various types and low-level primitives we may define for the wallet (about UTxO manipulation, block application etc). 

# Decision

- A module _must_ define primitive types to represent a wallet in its very core
- A module _must_ define primitive operations on those types
- We _must_ also implement the various properties and proof available in the wallet specifications

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #25       | `master`  |
| #29 | `master` |
| #34 | `master` |
| #37 | `master` |
| #42 | `master` | 
| #43 | `master` | 

# QA 

- This was a bit longer than initially planed. In the end, two modules were added to the source code:
    - [Cardano.Wallet.Primitive](https://github.com/input-output-hk/cardano-wallet/blob/eb3a993e6b58ce459e4320c6a34ba0d5b2399bf4/src/Cardano/Wallet/Primitive.hs)
    - [Cardano.Wallet](https://github.com/input-output-hk/cardano-wallet/blob/d8b34e832f411441011f04ba042526c8404804f3/src/Cardano/Wallet.hs)

- Both modules have corresponding property tests
    - For `Cardano.Wallet.Primitive`, I have translated to Haskell the various Lemma and properties available on those primitive types in the specification for a Cardano wallet  (cf: https://github.com/input-output-hk/cardano-wallet/blob/eb3a993e6b58ce459e4320c6a34ba0d5b2399bf4/test/unit/Cardano/Wallet/PrimitiveSpec.hs#L58-L86).

    -  For `Cardano.Wallet`, I've implemented in test the `Basic Model` from the specification, and compared the tracking of UTxO between that basic model and our slightly more complex model which includes prefiltering -- making sure they match. As we add features to the wallet code, this may become quite useful to make sure that we aren't breaking the basic capabilities of keeping track of UTxO and a balance. I've also added there another Lemma from specification which makes sure that our basic model implementation from the test code actually matches what the specification expect. cf: https://github.com/input-output-hk/cardano-wallet/blob/master/test/unit/Cardano/WalletSpec.hs#L79-L84

**Comment by piotr-iohk** [comment]
lgtm :+1:
