### ISSUE TITLE
Swagger docs say payments list >= 0

### ISSUE THREAD

**Issue by disassembler** [cardano-foundation/cardano-wallet#2000]
# Context
 
When you try to create a tx with just withdrawals (and no payments) wallet returns:
```
{"code":"bad_request","message":"Error in $.payments: parsing NonEmpty failed, unexpected empty list"}
```

But swagger docs show `payments` is a list `>=` 0. @KtorZ confirmed the behavior is correct but docs are wrong.

# Steps to Reproduce

1. ...

## Actual behavior
 

---

# Resolution 

---

# QA

**Comment by KtorZ** [comment]
:+1:
