### ISSUE TITLE
Add pool DB operation `listRetiredPools`.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#2016]
# Context

As part of the work to perform garbage collection of retired pools from the database, we need to be able to determine _which_ pools have retired.

# Decision

Create a pool database operation `listRetiredPools`:

```hs
listRetiredPools
    :: EpochNo
    -> stm [PoolId]
    -- ^ List all pools with an active retirement epoch that is
    -- earlier than or equal to the specified epoch.
````

## SQLite implementation

The SQLite implementation of this operation can be based on the following **view**, which lists all pools that have active retirement certificates associated with them:

<details><summary>Click to expand</summary>

```sql
CREATE VIEW active_pool_retirements AS
SELECT * FROM (
    SELECT
        pool_id,
        retirement_epoch
    FROM (
        SELECT row_number() OVER w AS r, *
        FROM (
            SELECT
                pool_id, slot, slot_internal_index, NULL as retirement_epoch
                FROM pool_registration
            UNION
            SELECT
                pool_id, slot, slot_internal_index, epoch as retirement_epoch
                FROM pool_retirement
        )
        WINDOW w AS (ORDER BY pool_id, slot desc, slot_internal_index desc)
    )
    GROUP BY pool_id
)
WHERE retirement_epoch IS NOT NULL;
```

</details>

# Acceptance Criteria

- [x] The pool DB _must_ provide a `listRetiredPools` operation.
- [x] The `listRetiredPools` operation _must not_ include pools that have never had retirement certificates associated with them.
- [x] The `listRetiredPools` operation _must not_ include pools that have had their most-recently-published retirement certificates revoked by subsequent re-registration certificates.
- [x] The `listRetiredPools` operation _must not_ include pools with retirement epochs that are later than the specified epoch.

# Development 

# QA 

Create property tests for the **model** and **SQLite** implementations of `listRetiredPools` to:
- [x] check that they return **the same results** given the same inputs and initial conditions.
- [x] check that they **do not** include pools that have never had retirement certificates associated with them.
- [x] check that they **do not** include pools that have had their most-recently-published retirement certificates revoked by subsequent re-registration certificates.
- [x] check that they **do not** include pools with active retirement epochs that are later than the specified epoch.

**Comment by piotr-iohk** [comment]
LGTM.

@jonathanknowles this introduces new DB view `active_pool_retirements`. Do we need to consider any additional migration testing?

**Comment by jonathanknowles** [comment]
> @jonathanknowles this introduces new DB view `active_pool_retirements`. Do we need to consider any additional migration testing?

This is a good question. I think our existing tests should be sufficient at this stage.

The view in question is created with a `CREATE VIEW IF NOT EXISTS` statement: https://github.com/input-output-hk/cardano-wallet/blob/75b583a14faa5bc1875f6dddd2a94a897c47080d/lib/core/src/Cardano/Pool/DB/Sqlite.hs#L489-L495

So it should be idempotent over multiple startups.

In future, if we wish to adjust this view, we can adjust the startup logic to just delete and recreate it, perhaps with a `CREATE OR REPLACE VIEW` statement. IMHO, this is one of the advantages of views: we can create, adjust, and delete them without having to alter existing tables with existing data.

**Comment by piotr-iohk** [comment]
lgtm
