### ISSUE TITLE
Add pool DB operation `removeRetiredPools`

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#2018]
# Context

As part of the work to perform garbage collection of retired pools from the database, we need to be able to conveniently and safely remove _retired_ pools.

# Decision

Create a pool database operation `removeRetiredPools`:

```hs
removeRetiredPools
    :: EpochNo
    -> stm [PoolId]
    -- ^ Remove all pools with an active retirement epoch that is
    -- earlier than or equal to the specified epoch.
```

This operation _reuses_ the existing [`listRetiredPools`](https://github.com/input-output-hk/cardano-wallet/issues/2016) and [`removePools`](https://github.com/input-output-hk/cardano-wallet/issues/2017) operations.

# Acceptance Criteria

- [x] The pool DB _must_ provide a `removeRetiredPools` operation.
- [x] The `removeRetiredPools` operation _must_ remove each pool _atomically_.
- [x] The `removeRetiredPools` operation _must_ write an entry to the log before removing a pool.

# Development 

- #2047 

# QA 

Property test:
- https://github.com/input-output-hk/cardano-wallet/pull/2078

This operation _reuses_ the existing [`listRetiredPools`](https://github.com/input-output-hk/cardano-wallet/issues/2016) and [`removePools`](https://github.com/input-output-hk/cardano-wallet/issues/2017) operations. The tests for these operations are described in the following tasks:
- #2016 
- #2017

**Comment by piotr-iohk** [comment]
lgtm
