### ISSUE TITLE
Nightly Jörmungandr tests are failing 

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#2020]
# Context

https://buildkite.com/input-output-hk/cardano-wallet/builds/9809

# Test Case

- The jormungandr unit test suite is timing out. 
- The jormungandr integration tests are failing.

# Failure / Counter-example

---

# Resolution 

---

# QA

**Comment by rvl** [comment]
It says `jormungandr-integration` failed and `cardano-wallet-jormungandr:test:unit` timed out.
You can find logs in the "Artifacts" tab of the build.
The last thing I see in the cardano-wallet-jormungandr test logs is the Cardano.Wallet.Jormungandr.Binary Decoding tests. But they would not be the cause.

**Comment by rvl** [comment]
Is it possible that the jormungandr integration tests fail because they don't have built-in retrying like the shelley integration tests?

**Comment by KtorZ** [comment]
@rvl we introduced the retrying `it` for the Shelley integration tests because of the frequent rollbacks we had. We never had such issues on Jörmungandr because the self-node doesn't rollback as often (or rollback at all actually...). So my two cents would be: no, it is unlikely.

**Comment by piotr-iohk** [comment]
Tests should be passing now.
