### ISSUE TITLE
Latency benchmark are failing on nightly

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#2021]
# Context
 
 

https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/602#72d838c5-e0b3-4215-abae-1754493a09fc

# Test Case

- Latencies for 2 fixture wallets scenario

# Failure / Counter-example

```
latency: user error (fixtureWallet: waited too long for initial transaction)
```

Could

---

# Resolution 

- It seems that the faucets are not correctly setup for the latency benchmarks. With the Byron;Shelley chain, we now need an extra step after the hard-fork has happened in order to fund faucets. This can be seen from the integration setup right here:

  https://github.com/input-output-hk/cardano-wallet/blob/a7670ed340427f3f86dba192325eb7abf67a4ca9/lib/shelley/test/integration/Main.hs#L226-L229

---

# QA

**Comment by Anviking** [comment]
This was fixed I believe, but they are failing for another reason now:

```
CallStack (from HasCallStack):
--
  | error, called at src/Cardano/Wallet/Primitive/Fee.hs:182:9 in cardano-wallet-core-2020.8.3-K7o5kjXekx0FJgLhc2e6XW:Cardano.Wallet.Primitive.Fee
  | adjustForFee, called at src/Cardano/Wallet.hs:1288:24 in cardano-wallet-core-2020.8.3-K7o5kjXekx0FJgLhc2e6XW:Cardano.Wallet
  | generated a coin selection with an excessively large fee.
  | actual fee: 513100 Lovelace
  | coin selection:
```
https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/630#f25ae394-5bd6-4422-ae66-12bf6700a0b3

**Comment by piotr-iohk** [comment]
I think this is the culprit -> https://github.com/input-output-hk/cardano-wallet/issues/2075#issuecomment-686426508
