### ISSUE TITLE
Nightly restoration benchmark are silently failing for 1% wallets

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#2022]
# Context
 
 

https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/602

There really are two issues here (which could have the same root cause): 

a) The restoration tests are taking a very long time to run.
b) Failures are reported as success.

# Test Case

- 1% wallet

# Failure / Counter-example

- The test runs for about 6h before returning invalid results as "green"
- Both the heap profile and block height over time plots look bizarre. 
- We see an "infinite stream" of `[31m[ci4-benc:cardano.node.LocalErrorPolicy:Error:53][0m [2020-08-10 12:46:26.13 UTC] [String "ErrorPolicyUnhandledApplicationException (MuxError MuxBearerClosed \"<socket: 55> closed when reading data, waiting on next header True\")",String "ErrorPolicyTrace",String "LocalAddress {getFilePath = \"\"}"]`
- Eventually, the restoration worker exits with an exception and the results are collected and plotted as if it terminated normally

```
[INFO] restoring: 16.62%
[INFO] restoring: 16.62%
[INFO] restoring: 16.62%
[INFO] restoring: 16.62%
[INFO] restoring: 16.62%
[INFO] restoring: 16.62%
[INFO] restoring: 16.62%
[INFO] restoring: 16.62%
restore: ExceptionInLinkedThread ThreadId 560863 (MuxError (MuxIOException Network.Socket.recvBuf: resource vanished (Connection reset by peer)) "(recv errored)")
[35m[bench-restore:Notice:14][0m [2020-08-10 12:54:40.93 UTC] [cardano-node.43939] Terminating child process
```

---

# Resolution 

---

# QA

**Comment by rvl** [comment]
This matches my results when I run the 1% test locally.

Reacting to CI benchmark failures is slightly tricky - you don't want to immediately crash on an error, otherwise all the successful results will be lost, there will be no charts, etc.

**Comment by KtorZ** [comment]
> Reacting to CI benchmark failures is slightly tricky - you don't want to immediately crash on an error, otherwise all the successful results will be lost, there will be no charts, etc.

Yes indeed and in the end, we get the right information by looking at the logs. Yet having a green check indicating that everything is okay may be quite misleading. That's pretty minor though, understand what's going on and the restoration is interrupted is a bigger concern.

**Comment by piotr-iohk** [comment]
Currently it fails due to removing of `cardano-wallet-shelley`:

```
error: attribute 'cardano-wallet-shelley' in selection path 'benchmarks.cardano-wallet-shelley.restore' not found
```

https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/610#6c0f5b0c-559f-416a-851f-07cbc8ad4fe5

**Comment by rvl** [comment]
That will be fixed by #2045.

**Comment by Anviking** [comment]
After #2045 it times out after 10 hours instead 🙈 

https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/612#0bb60c55-f9d2-443c-9acd-dd83e1ff6d2e

08:43: node starts syncing
10:33: first wallet bench starts
10:40 second wallet bench starts
10:47: third wallet bench starts
11:44: fourth wallet bench starts

Final logs before timeout are:
```
[ci4-benc:cardano.node.ChainDB:Notice:35] [2020-08-19 12:13:37.06 UTC] Chain extended, new tip: (Point 6272925, "12385134ae3954b0ebd636ba7bd348c54f1bf57b433ae2824afb2caed04c9599")
--
  | [INFO] restoring: 48.42%
  | [INFO] restoring: 48.44%
  | [INFO] restoring: 48.46%
  | [INFO] restoring: 48.48%
  | [INFO] restoring: 48.50%
  | [INFO] restoring: 48.53%
  | [INFO] restoring: 48.55%
  | [INFO] restoring: 48.57%
  | [INFO] restoring: 48.59%
  | [INFO] restoring: 48.61%
  | [INFO] restoring: 48.64%
  | [INFO] restoring: 48.66%
  | [INFO] restoring: 48.68%
  | [INFO] restoring: 48.70%
  | [INFO] restoring: 48.72%
  | [INFO] restoring: 48.74%
```
It shouldn't timeout until 18:43, so that it just went silent at 12:13, maybe… is the same issue as this ticket reports?

**Comment by KtorZ** [comment]
nightly restoration benchmarks are up-and-running :+1:
