### ISSUE TITLE
Wrong user-facing encoding for poold id and reward account

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#2023]
# Context
 
 

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      |  |
| Platform     |           |
| Installation |             |

- [x] Pool id are currently encoded as base16 strings. 
- [x] Reward accounts are currently encoded as bech32 with a "stake_addr" prefix

# Steps to Reproduce

N/A

## Expected behavior

- Both types are encoded as bech32 using prefixes as specified in [CIP-5](https://github.com/cardano-foundation/CIPs/tree/master/CIP5)

## Actual behavior
 

---

# Resolution 

---

# QA

**Comment by hasufell** [comment]
Where in the API can I reproduce this?

----

Edit:

- pool id: https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/listStakePools
- reward account: e.g. https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/listTransactions

Any other endpoints affected?

The offending code spots are these, afais:

https://github.com/input-output-hk/cardano-wallet/blob/d7994e9c83ed00d798cf24f3101e50f0383ddc17/lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs#L921-L931
 
https://github.com/input-output-hk/cardano-wallet/blob/d7994e9c83ed00d798cf24f3101e50f0383ddc17/lib/core/src/Cardano/Wallet/Primitive/Types.hs#L677-L695

**Comment by hasufell** [comment]
Afais this will change various API endpoints, such as: https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/joinStakePool where the pool ID is a parameter

Having the encoding for parameter and json output diverge is probably going to be confusing?

**Comment by piotr-iohk** [comment]
lgtm.

I have adjusted swagger to show that pool id can be hex or bech32 in https://github.com/input-output-hk/cardano-wallet/pull/2093 which should also address #2025.

**Comment by hasufell** [comment]
@rhyslbw what's missing?

**Comment by rhyslbw** [comment]
> Reward accounts are currently encoded as bech32 with a "stake_addr" prefix

**Comment by rhyslbw** [comment]
Done in https://github.com/input-output-hk/cardano-wallet/pull/2055/commits/c36ba7d897b90e3d6bcaaae90b18f0c4cf7b5d68
