### ISSUE TITLE
'minLength' must be lower value than 'maxLength'

### ISSUE THREAD

**Issue by melmccann** [cardano-foundation/cardano-wallet#2025]
https://github.com/input-output-hk/cardano-wallet/blob/e096e3403bdd94a67805ede25e2c3818fc875d7a/specifications/api/swagger.yaml#L1404

**Comment by KtorZ** [comment]
That's an interesting one. These two seem to have been swapped.

**Comment by piotr-iohk** [comment]
Fixed in #2093.
