### ISSUE TITLE
DELETE operations cannot have a requestBody.

### ISSUE THREAD

**Issue by melmccann** [cardano-foundation/cardano-wallet#2026]
https://github.com/input-output-hk/cardano-wallet/blob/e096e3403bdd94a67805ede25e2c3818fc875d7a/specifications/api/swagger.yaml#L2208

**Comment by KtorZ** [comment]
Hmm? What do you mean @melmccann ?

**Comment by melmccann** [comment]
I added this just to keep in line with OpenAPI, so stubs can be generated from swagger.yaml without error.
You can have a requestBody for a DELETE but for some reason OpenApi doesn't allow it. 
https://github.com/OAI/OpenAPI-Specification/issues/1801
You can close this issue if you feel it is their problem not ours @KtorZ

**Comment by KtorZ** [comment]
Well, request bodies on `DELETE` request is actually not forbidden by the [RFC 7231](https://tools.ietf.org/html/rfc7231) which specifies the HTTP/1.1 protocol. The only verb that for which a request body is strictly forbidden is `HEAD`.

It also seems that the OpenAPI specifications eventually changed their own design to allow this: https://github.com/OAI/OpenAPI-Specification/pull/2117
