### ISSUE TITLE
Too many intermediate checkpoints created in one go

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#2035]
# Context
 
 

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | v2020-08-03  |
| Platform     | All           |
| Installation |             |

# Steps to Reproduce

1. Restore a wallet
2. Wait until the wallet cross the hard-fork (or a protocol update)
3. Observe checkpoints in the database (e.g. `SELECT DISTINCT(slot) FROM checkpoints`)

## Expected behavior

- The number of checkpoints is kept small, and the wallet creates them gradually.

## Actual behavior
 

- The number of checkpoints kept in the database depends on the `k` parameter. The larger `k`, the more checkpoints we store. In the Shelley era on Mainnet however, we can still see over 30+ checkpoints. 

- When reaching the area close to the tip of the chain, the wallet may create many checkpoints in a single database transaction. For large wallets, this would mean making the wallet inoperative for a long time. Possibly causing it to require another long time of creation of many small checkpoints.

---

# Resolution 

- Find a better strategy for creating checkpoints ==> #2143 

---

# QA 

- Changed the strategy to compute and maintain checkpoints such that no more than 2 checkpoints (and most of the time, only one) would be created by each restoration step. Some parameters of the `sparseCheckpoint` function have also been made configurable instead of being hard-coded, allowing for tweaking them dynamically. 

- With that, we added two interesting properties:

    1. A property which shows that the size of the `edgeSize` parameter only influence the short-term checkpoints, and that long-term checkpoints are always the same regardless of the value of that parameter. This is useful to show because we now calculate acceptable in two places with _different parameters_: In the wallet restoration loop, where we set the edge size to 0, and in the database pruning function where we set it to 5. We do this to avoid the restoration loop to pause for too long to create the short term checkpoints. Yet, since we always store the _last_ checkpoint of a batch of block, when the wallet reaches the tip, it'll start filling the short-term checkpoints automatically (since they won't be pruned by the database). Eventually, long-term and short-term checkpoints will be stored in the database.

    https://github.com/input-output-hk/cardano-wallet/blob/06b34e48408596ef49b7b183f0674a432c2a317f/lib/core/test/unit/Cardano/Wallet/DB/Properties.hs#L924-L937

    2. A more complicated property which mimics the song-and-dance done between the restoration loop and the database pruning. The property shows that the strategy we employ _works_ and ensures that _at any time_, the wallet won't roll back more than `k + gapSize` blocks, where gapSize is a setting calculated from k and smaller than k. Knowing that k is about 108 in Shelley, and a hundred blocks are pretty must instantaneous to restore for the wallet, this seems like a fair compromise. 

    https://github.com/input-output-hk/cardano-wallet/blob/06b34e48408596ef49b7b183f0674a432c2a317f/lib/core/test/unit/Cardano/Wallet/DB/Properties.hs#L939-L1028

**Comment by Anviking** [comment]
> Remove protocol parameters from checkpoints altogether

I was about to in #1872, but had migration problems.

The security parameter k should be very static across all eras though...?

**Comment by KtorZ** [comment]
@Anviking yes indeed.

**Comment by piotr-iohk** [comment]
lgtm. 

I tested few wallets on testnet against `v2020-09-11` and `master`. There are less checkpoints being created for `master` wallet. 
E.g. 
 - empty wallet on  `v2020-09-11` has 35 checkpoints after restoration.
 - empty wallet  on `master` has 7 checkpoints after restoration.
