### ISSUE TITLE
Cardano-wallet Failed to parse genesis configuration for Testnet 

### ISSUE THREAD

**Issue by gopherine** [cardano-foundation/cardano-wallet#2039]
`docker run inputoutput/cardano-wallet serve --node-socket /ipc/node.socket --database /wallet-db --listen-address 0.0.0.0 --testnet testnet-shelley-genesis.json `

I downloaded the above configuration however it is not able to detect the genesis file I see that using --mainnet works out of the box. I would like to run this without docker compose, I don't see documentation regarding this. Thanks

**Comment by KtorZ** [comment]
Hi, you should use the **Byron** genesis configuration. The chain starts in Byron, Shelley parameters are published later on on-chain so the wallet figure them out alone :+1:

**Comment by gopherine** [comment]
Hey @KtorZ  i also used byron genesis configuration the problem is that it's not detecting the genesis file itself, i tried downloading everyone of them present in the doc ...

```Failed to parse genesis configuration. You may want to check the filepath given via --genesis and make sure it points to a valid JSON genesis file. Here's (perhaps) some helpful hint: GenesisDataIOError testnet-byron-genesis.json: openBinaryFile: does not exist (No such file or directory) ```

**Comment by KtorZ** [comment]
Seems like you've specified an invalid path to the byron genesis file?

**Comment by gopherine** [comment]
@KtorZ  I am pretty sure I didn't mess up the path, since I am trying to run this in the same directory where I downloaded my genesis file. I thought earlier that I don't need to download anything, so I also tried to run it with /config/testnet-byron-genesis.json assuming nix is picking up this path.

However, i get the same error in both cases

**Comment by KtorZ** [comment]
@gopherine if you're running this inside a docker container, you need to make sure that the file is in a volume that is mounted in the container, which is likely not your case here. Check the `--volume` and `--mount` options from docker for more details about this.

**Comment by gopherine** [comment]
@KtorZ  right now I am trying to run this locally just to add more details on my system, I am trying to run this on mac os - catalina - ram -16 GB  2017 model
