### ISSUE TITLE
Error code results often contain `application/octet-stream` content type 

### ISSUE THREAD

**Issue by mcsherrylabs** [cardano-foundation/cardano-wallet#2040]
# Context
 
Exercising the API trying to perform simple value transfers 

| Information  | -                                                     |

Version      
Platform     Ubuntu
Installation  docker

# Steps to Reproduce

1. Exercise the API and generate a 403 Forbidden for example use 

https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/postWallet

create/restore wallet with incorrect mnemonic string.
  

## Expected behavior

Resulting stream should have type `application/json' similar to the happy path results. 

## Actual behavior

Error codes often have type `application/octet-stream`

# Resolution 

---

# QA

**Comment by hasufell** [comment]
What's the exact request you send? I get 400 most of the time.

**Comment by KtorZ** [comment]
@hasufell I think this may occur when Servant is picking up errors instead of our application layer. Under normal circumstances, Servant would just return a raw error with just text as body but we have a wai-middleware catching these and re-wrapping them into JSON to be consistent with other application errors, yet, the middleware does not change the content type of the response which may still be the original one set by Servant. 

So, try to make a request that Servant would fail to comprehend, something like a non-json object on a POST endpoint would probably do.

**Comment by hasufell** [comment]
> So, try to make a request that Servant would fail to comprehend, something like a non-json object on a POST endpoint would probably do.

Without a content type header this results in 415. With a content type header, but non-json input, it results in 400:

```json
{"code":"bad_request","message":"I couldn't understand the content of your message. If your message is intended to be in JSON format, please check that the JSON is valid."}
```

(all of these return `Content-Type: application/json;charset=utf-8`)

**Comment by KtorZ** [comment]
Then I am clueless :man_shrugging: . @mcsherrylabs may we have maybe a bit more context?

**Comment by mcsherrylabs** [comment]
While developing against the API I had some failures which I fixed by adding the second case for Binary. Some error results were returning response with that type. Unfortunately I can't reproduce this now. I feel it was in the area of recreating wallets.   
```
response.entity.contentType match {
        case WithFixedCharset(MediaTypes.`application/json`) =>
          // Load into memory using toStrict
          // a. no responses utilise streaming and
          // b. the Either unmarshaller requires it
          strictEntityF.flatMap(f)

        case Binary(MediaTypes.`application/octet-stream`) =>
          extractErrorResponse[T](strictEntityF)

        case c: ContentType =>
          Future.failed(new RuntimeException(s"Unexpected type ${c.mediaType}, ${c.charsetOption}"))
      }
```
So I'm already dealing with it on my side.

**Comment by mcsherrylabs** [comment]
Barring any objections, closing with 'Could not reproduce'

**Comment by mcsherrylabs** [comment]
I have seen another version of this, if you can create a race condition between deleteWallet getWallet and createWallet you will get a `text/plain` response of "Something went wrong", I'n not reopening as a. I'm not going to create a repeatable test case and b. the behaviour might not even be considered a bug, so just capturing.
