### ISSUE TITLE
Test external tx endpoint

### ISSUE THREAD

**Issue by paweljakubas** [cardano-foundation/cardano-wallet#2041]
# Context

This is counterpart task for https://github.com/input-output-hk/cardano-transactions/issues/16
The idea is to prepare wallet's inputs on integration side, then in cardano-transactions side create blob and use via external tx endpoint, and finally verify expectations. 

# Decision

Add several tests : for one and two inputs, both using shelley and byron witnesses, and use blobs produced using cardano-transactions 

# Acceptance Criteria

1. Test showing correctness of external tx endpoint are added.

---

# Development 

# QA

**Comment by piotr-iohk** [comment]
These are very nice tests. :tada:  
I would like to also add test for Icarus wallet there.

For now I was trying to do `Icarus -> Icarus` transaction manually on testnet constructing tx with `cardano-tx` and trying to submit with cardano-wallet according to https://github.com/input-output-hk/cardano-transactions/wiki/How-to-submit-transaction-via-cardano-tx-CLI but got error in the last step -> https://github.com/input-output-hk/cardano-transactions/issues/16#issuecomment-701433948.

**Comment by piotr-iohk** [comment]
lgtm
