### ISSUE TITLE
Cleanup observed reward accounts

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#2042]
# Context

To fix #2005 a immediate solution is to observe the rewards of a `Set ChimericAccounts` on every tip change.

The not yet merged #2034 is only adding to the `Set`, but never removing.

We suspect this is acceptable for the moment because
1. The `Set` is cleared when the wallet restarted
2. Creating and deleting say 100s of wallets in a single session seem like a extremely rare user behaviour
3. Querying even 100 extra reward accounts are likely completely fine performance-wise (to be confirmed)
4. Getting out a fix for #2005 is more important.

But nonetheless we should make sure to deal with this properly. 

# Decision

Stop fetching the rewards of wallets when they are deleted.

# Acceptance Criteria

- [ ] The reward accounts we fetch on tip-changes must not grow uncontrolled. 

---

# Development 

# QA

**Comment by KtorZ** [comment]
Tracked as: https://jira.iohk.io/browse/ADP-410
