### ISSUE TITLE
BUG: cardano-wallet docker container exits with code 127 - command not found

### ISSUE THREAD

**Issue by philkunz** [cardano-foundation/cardano-wallet#2044]
# Context

I'm in the process of creating a MIT licensed TypeScript client for the the cardano wallet api, that replicates daedalus functionality in TypeScript.

For testing I checked out the repo and started the docker compose file with `NETWORK=mainnet docker-compose up`

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | Docker Images: inputoutput/cardano-node:1.18.0 and inputoutput/cardano-wallet:latest as in docker-compose file |
| Platform     | Latest Ubuntu with latest Docker |
| Installation | Docker Compose from master of this repository  |

## Expected behaviour

Everything runs normal and `curl http://localhost:8090/v2/network/information` gives a status 200 response

## Actual behaviour

cardano-node runs normal, cardano-wallet container exits with code 127, command not found. 

---

# Resolution 

---

# QA

**Comment by rvl** [comment]
@philkunz Your project sounds interesting. Perhaps you could add it to [cardano-launcher](https://github.com/input-output-hk/cardano-launcher)?

**Comment by philkunz** [comment]
@rvl I took a look at cardano-launcher and created a ticket there https://github.com/input-output-hk/cardano-launcher/issues/86

My goal is to make cardano consumable to the average TypeScript dev implementing a website or simple shop by nothing a more than a simple `npm install [packagename]`. I'm more than happy to include this work into iohk later should it find your approval upon completion (it is MIT licensed anyway).

**Comment by Anviking** [comment]
It [seems](https://hub.docker.com/r/inputoutput/cardano-wallet/tags) `latest` is not updated immediately, but after setting this:
```bash
    image: inputoutput/cardano-wallet:dev-master-shelley
```
in `docker-compose.yml`, ` NETWORK=mainnet docker-compose up` starts correctly.

I suppose `latest` will be updated next time we make a wallet release, which might be soon, so no need to PR docker-compose-yml. cc @piotr-iohk @rvl

**Comment by KtorZ** [comment]
@Anviking latest correspond to the latest release. So, on August 3rd at the moment.

**Comment by piotr-iohk** [comment]
works fine in `v2020.9.11`
