### ISSUE TITLE
Can't build: Unsupported tarball from /tmp/with-repo-archive4121/foo.tar

### ISSUE THREAD

**Issue by Fell-x27** [cardano-foundation/cardano-wallet#2060]
| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | master|
| Platform     | Linux |

# Steps to Reproduce

git clone https://github.com/input-output-hk/cardano-wallet.git
cd cardano-wallet
git checkout master
stack build --test --no-run-tests

## Expected behavior

Build completed.

## Actual behavior
 
Cloning 460ee17d22cacb3ac4d90536ebe90500a356a1c9 from https://github.com/input-output-hk/cardano-ledger-specs
Unsupported tarball from /tmp/with-repo-archive4121/foo.tar: Symbolic link dest not found from shelley/chain-and-ledger/cddl-spec to executable-spec/cddl-files/, looking for shelley/chain-and-ledger/executable-spec/cddl-files.
This may indicate that the source is a git archive which uses git-annex.
See https://github.com/commercialhaskell/stack/issues/4579 for further information.

**Comment by KtorZ** [comment]
Yes, the ledger revision from `master` is currently broken. See https://github.com/input-output-hk/cardano-wallet/pull/2056

**Comment by rvl** [comment]
Fixed in fece720cb18d9676c4f1f6b0d3a69a37fab93f1c.
