### ISSUE TITLE
Rewards migration?

### ISSUE THREAD

**Issue by Fell-x27** [cardano-foundation/cardano-wallet#2061]
# Context

When I want to migrate funds, I want to click "send all" ant send then all. Literally. But there is a problem.
 
# Steps to Reproduce

1. Call migration endpoint for a wallet with reward.

## Expected behavior

All funds are migrating, rewards are included.

## Actual behavior
 
UTxO migrate, reward doesn't

---
## Comment
Yep, I can do it with simple transaction, but I think that it make sense if there was a reward migration when you ask wallet for migration, not "simple" transaction.

**Comment by KtorZ** [comment]
The rewards aren't indeed included as part of the migration. The primary goal of the migration was to cover migrating from a legacy wallet (where rewards aren't a thing) to a new Shelley wallet. This has then be (perhaps "abusively") extended to Shelley wallets too. 

I'll ping our product owner about this to see if that's something we are willing to support moving forward :+1:

**Comment by Fell-x27** [comment]
>The primary goal of the migration was to cover migrating from a legacy wallet (where rewards aren't a thing) to a new Shelley wallet.

Ok, but I thought that the primary goal is "This operation attempts to preserve the UTxO "shape" of a wallet as far as possible." :)

>if that's something we are willing to support moving forward
Oh, ok, I'll check changelogs twice to catch if you removed it.

**Comment by KtorZ** [comment]
It is also correct. Yet, note that the rewards are NOT UTxOs. They use a chimeric ethereum-like account model which are turned into UTxO via a special operation called "withdrawal".
