### ISSUE TITLE
Fees are excessively high sometimes

### ISSUE THREAD

**Issue by Fell-x27** [cardano-foundation/cardano-wallet#2062]
# Context
 
Sometimes when you want to estimate fees, you can get weird result;

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      |2020.8.3 (git revision: b5b292b5a9f0ddccc0fc5d9e98bf3bf80f1a9d13) |
| Platform     | Linux        |
| Installation | From Hydra            |

# Steps to Reproduce

1. Try to estimate fees when payments + expected_fees_for_this_payments >= payments amount
2. ...
3. PROFIT!1

## Expected behavior
Fees for this transaction even if there is not enough money for it. I just want to know estimated fees for transaction like this. It works well for migrations, but there is a problem https://github.com/input-output-hk/cardano-wallet/issues/2061, so I can't use migrations instead.
## Actual behavior
 Your fees are about 1.8446744062438E+19

---

## Comment
Yep, I can handle it by myself with some nasty solutions, and I will, but would be nice if I have not to do this.

**Comment by KtorZ** [comment]
Looks like a proper under/over flow in the fee estimation.

**Comment by KtorZ** [comment]
I've been able to reproduce with an integration test scenario by trying to estimate fee for a wallet using the total balance (available UTxO + rewards). This indeed reaches an edge case of the fee estimation where fees are too big and some extra computation is done to calculate the estimated amount.

**Comment by KtorZ** [comment]
### QA

- Added an extra integration test scenario illustrating the problem (fee calculation fallback with withdrawal) (https://github.com/input-output-hk/cardano-wallet/commit/f6e74dca19d77b05a3d3b1838badc538b7d00e93)

- Also added an invariant in-code to make sure that this does not happen by accident. The invariant checks that fee are within an acceptable bound and crashes the server otherwise.

**Comment by piotr-iohk** [comment]
lgtm.
