### ISSUE TITLE
Tx metadata stored in sqlite database

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#2072]
# Context

Part of ADP-307

# Decision

Transaction metadata is stored in the SQLite database indexed by TxId.

The metadata is converted to JSON and encoded, and stored in a STRING column.

Schema:
```
TxMetadata
    txMetadataTxId    TxId          sql=tx_id
    txMetadataValue   Text          sql=value

    Primary txMetadataTxId
    deriving Show Generic
```

Pending transactions' metadata are stored in the same manner as confirmed transactions.

Absence of metadata in a transaction corresponds to absence of a `tx_metadata` table row.

I was considering making one table row per top-level metadata map entry, but that's not really needed, slightly more complicated to implement, and makes it harder to differentiate between no metadata and an empty metadata map (if there is in fact any difference on chain).

# Acceptance Criteria

1. Transaction metadata must be stored in the database with the transaction.
2. When transactions are deleted, metadata must also be deleted.

---

# Development 

# QA

- State machine DB tests cover transaction history operations. `lib/core/test/unit/Cardano/Wallet/DB/StateMachine.hs`
- The Tx generator should include arbitrary generated metadata. This arbitrary metadata only includes valid data because metadata is already validated at the API boundary.

**Comment by piotr-iohk** [comment]
lgtm.
