### ISSUE TITLE
Tx metadata accepted in API for creating a transaction

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#2073]
# Context

ADP-307

When creating a transaction, users should be able to attach their metadata in JSON format.

# Decision

1. Use json conversion functions from `Cardano.Api.MetaData`.

# Acceptance Criteria

1. The API must accept metadata when posting to the shelley create transaction endpoint.
2. The API must accept metadata for the shelley transaction fee estimation endpoint.
3. The metadata field must be optional.
4. The swagger API definitions must be updated accordingly.

---

# Development 

- As above.
- Wrap TxMetadata in ApiTxMetadata so that JSON `null` can also denote absence of metadata.

# QA 

1. Api type serialisation/deserialisation is tested with unit tests.
2. There are unit tests in cardano-node for encoding/decoding metadata - see input-output-hk/cardano-node#1797. So we do not need to test multiple invalid metadata cases. One invalid metadata test is enough.
3. Integration tests in `lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs`
   - TRANS_CREATE_01 is modified to check that metadata is missing.
   - TRANS_CREATE_10  - Transaction with metadata
   - TRANS_CREATE_11 - Transaction with invalid metadata -- this is a metadata parsing error.
   - TRANS_CREATE_12 - Transaction with too much metadata

**Comment by piotr-iohk** [comment]
Perhaps this is still in progress, but just to share few observations.

It seems one can send metadata that is _invalid_ in format, should we have more strict validation?

Examples:
1. one can use the same key multiple times which restuls in silently using only first one... maybe there should be validation and such metadata not allowed?
 Metadata: `{"1": 1, "1": 2, "1":123123}` silently results in `{ "1": 1 }`

2. can successfuly send map which is not map (basically list of lists or more generally list of different types)
 
list of lists
`{"4":[["k1", "v1", 1, 2, 4, 5, 6, 7], ["k2", "v2", "v3"]]}`

list of different types
`{111: [1,2,5,"4","4545", [1,2,4]]}`

3. can successfully send "nested" metadata 
`{ "0": {"cardano":"adasd", "2": {3: 4} } }`

4. too big top levels key is are silently made values that are OK (kind of cool, but maybe that's not OK?)
 
{"22222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222": 1, "222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222223434":123123}

:point_down: 
```
{
    "16397105843297379214": 1,
    "16397105843297380426": 123123
}
```

**Comment by KtorZ** [comment]
@piotr-iohk see: https://github.com/input-output-hk/cardano-node/pull/1797

**Comment by piotr-iohk** [comment]
LGTM.
