### ISSUE TITLE
Tx metadata JSON in API transaction list

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#2074]
# Context

ADP-307

When listing transactions in the API, the user should see metadata attached to transactions - if it exists.

# Decision

1. Include metadata in `ApiTxMetadata` response.
2. JSON `null` denotes missing metadata (our generic defaults for aeson are to omit `Nothing` fields).

# Acceptance Criteria

1. Transaction list must show metadata in JSON format, if it exists.
2. Missing metadata should be `null`, to better illustrate that it's missing.
3. When posting a transaction with metadata, the JSON response must also show the metadata.
4. Swagger spec must be updated accordingly.

---

# Development 

As above.

# QA 

1. There are Api types unit tests for encoding/decoding.
2. Integration test `lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs` ⇒ PR #2096
   - TRANS_CREATE_10 - Transaction with metadata -- this tests the create transaction response, as well as checking the transaction list.

**Comment by piotr-iohk** [comment]
lgtm
