### ISSUE TITLE
Tx metadata extracted from binary blocks

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#2077]
# Context

Metadata must be serialized as CBOR in transactions. However, we should input and output JSON at the system boundary, and convert between JSON/CBOR internally.

### User story ADP-307

> As an API user,
> I want to add metadata to a transaction and view them as JSON,
> So that I can embed custom information within a transaction.

### References

See Appendix E of [Delegation Design Spec](https://hydra.iohk.io/job/Cardano/cardano-ledger-specs/delegationDesignSpec/latest/download-by-type/doc-pdf/delegation_design_spec)

# Decision

There's an existing implementation in cardano-api for doing JSON/CBOR conversions. We can hopefully re-use this. See: https://github.com/input-output-hk/cardano-node/blob/495366939621d4a413d000494ec01a8b0f5edc26/cardano-api/src/Cardano/Api/MetaData.hs

Although it is possible to translate any JSON into CBOR, the reciprocal isn't true. There are therefore arbitrary choices made regarding the transformation JSON/CBOR to make sure it can roundtrip under several assumptions.

# AC

- cardano-wallet must show metadata in transaction that have some (as part of the response object).
- metadata must be shown as JSON format in API responses
- cardano-wallet-jormungandr should default to null values and fail if provided with a metadata object.

---

# Development 

1. Extend `TxMeta` type to include metadata as an aeson `Value`.
2. When getting transactions from a block, use the existing conversion functions to make `Value` from metadata.

# QA 

- I have no actual chain data to use, so there are no golden tests.
- integration test _TRANS_CREATE_10 - Transaction with metadata_ in `lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs` ⇒  #2096.

**Comment by KtorZ** [comment]
> Extend TxMeta type to include metadata as an aeson Value.

@rvl from quickly looking at `cardano-api`, it seems that they provide a `Metadatum` data-type as an intermediate Haskell representation and that transformation are done from this Metadatum type (for JSON & CBOR). Perhaps re-using this data-type is preferable over an opaque aeson Value ? Thoughts?

**Comment by rvl** [comment]
Yes it could be better actually because it helps with validating new transactions.

Also I am thinking it's better to have TxMetadata inside the Tx type rather than TxMeta.

**Comment by piotr-iohk** [comment]
lgtm.
