### ISSUE TITLE
Listing stake pools time grows when there are wallets syncing in background

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#2082]
# Context
 
Not sure how is the relation but the time of listing pools seems to grow when there are more wallets being synced.
I don't see any obvious outstanding query time that would explain 50s... the longest query is `GetNonMyopicMemberRewards` which is a bit longer the more wallets are syncing. (Which applies to other querries too actually).

**0 Wallets syncing:**
List sp = 3s
Query GetNonMyopicMemberRewards took 2.028777786s

**1 wallet syncing:**
List sp = 13s
Query GetNonMyopicMemberRewards took 2.39806037s

**2 wallets syncing**
List sp = 26s
Query GetNonMyopicMemberRewards took 2.452248284s

**3 wallets syncing**
List sp = 31s
Query GetNonMyopicMemberRewards took 2.402175446s

**5 wallets syncing**
List sp = 40s
Query GetNonMyopicMemberRewards took 2.821580222s

**10 wallets syncing**
List sp = 47s
Query GetNonMyopicMemberRewards took 3.001514181s

**15 wallets syncing**
List sp = 1m 03s
Query GetNonMyopicMemberRewards took 3.012593506s

**20 wallets syncing**
List sp = 1m 11s
Query GetNonMyopicMemberRewards took 3.519106839s

Times of other querries is also growing a bit too and also the number of queries is growing when there are more wallets:

With 0 wallets (lp exec time = 4s):
```
Query GetNonMyopicMemberRewards took 2.386650034s
Query GetCurrentPParams took 0.000716248s
Query GetEraStart took 0.00137057s
Query getAccountBalance took 0.001327425s
Query GetCurrentPParams took 0.000513555s
Query GetUpdateInterfaceState took 0.000478
```
With 20 wallets (lp exec time = 1:10m):
```
Query GetEraStart took 0.637137392s
Query getAccountBalance took 0.648792572s
Query GetCurrentPParams took 0.626415965s
Query GetUpdateInterfaceState took 0.753813193s
Query GetStakeDistribution took 0.570119185s
Query GetEraStart took 0.771473205s
Query GetCurrentPParams took 0.650308479s
Query GetUpdateInterfaceState took 0.784389s
Query GetNonMyopicMemberRewards took 3.200318526s
Query getAccountBalance took 3.245384946s
Query GetCurrentPParams took 1.100185536s
Query GetEraStart took 0.842396347s
Query getAccountBalance took 0.854336837s
Query GetCurrentPParams took 0.759815955s
Query GetUpdateInterfaceState took 0.683372427s
Query GetEraStart took 0.841750692s
Query getAccountBalance took 0.886189268s
Query GetCurrentPParams took 0.806262374s
Query GetUpdateInterfaceState took 0.796393044s
Query GetEraStart took 0.898862386s
Query getAccountBalance took 0.962203422s
Query GetCurrentPParams took 0.736154508s
Query GetUpdateInterfaceState took 0.811650964s
Query GetEraStart took 0.695541092s
Query getAccountBalance took 0.730742968s
Query GetCurrentPParams took 0.901877006s
Query GetUpdateInterfaceState took 0.893728
```

**NOTE 1:**
Please note that when 20 wallets are synced listing stake pools takes ~5s, so the performance problem is visible only while some wallets are syncing.

**NOTE 2:**
Also, when we have n wallets syncing on _cardano-wallet 1_ and experiencing perf problems with listing stake-pools on that wallet, at the same time if we have _cardano-wallet 2_ on the same machine, we are able to list stake pools there just fine within 3-4 seconds (considering no wallets are syncing on _cardano-wallet 2_).

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | 2020.8.3 (git revision: 9f93d0a98be7c19035dd603149ebf06ac38d7f2f) / cardano-node 1.19.0 |
| Platform     | Linux        |
| Installation | From source            |

# Steps to Reproduce

1. Have n wallets syncing in parallel
2. List stake pools while wallets are syncing

## Expected behavior

Ideally listing stake pools time is consistent no matter how many wallets are syncing.

## Actual behavior
 
Listing stake pool takes longer while the more wallets are syncing. 

# Resolution 

https://github.com/input-output-hk/cardano-wallet/pull/2111

The above PR:

* changes the implementation of `ListStakePools` to execute a small number of handwritten SQL queries with native joins, rather than issuing multiple queries and joining together the results in memory.

* adds a new operation [`listPoolLifeCycleData`](https://github.com/input-output-hk/cardano-wallet/blob/d00c608e47d2d189a282a02946cc8e46b843375b/lib/core/src/Cardano/Pool/DB.hs#L180). The [SQLite implementation](https://github.com/input-output-hk/cardano-wallet/blob/d00c608e47d2d189a282a02946cc8e46b843375b/lib/core/src/Cardano/Pool/DB/Sqlite.hs#L384) of this operation uses a [single hand-optimized query](https://github.com/input-output-hk/cardano-wallet/blob/d00c608e47d2d189a282a02946cc8e46b843375b/lib/core/src/Cardano/Pool/DB/Sqlite.hs#L595) to return lifecycle data for all pools.

# QA 

### :heavy_check_mark: Properties

The above PR adds a [property test](https://github.com/input-output-hk/cardano-wallet/blob/d00c608e47d2d189a282a02946cc8e46b843375b/lib/core/test/unit/Cardano/Pool/DB/Properties.hs#L987) for `listPoolLifeCycleData`, consisting of the following steps:
1. Add an arbitrary sequence of pool registration and retirement certificates to the database, for multiple pools.
2. Call `listPoolLifeCycleData` once to fetch lifecycle data for all active pools.
3. Call `readPoolLifeCycleStatus` multiple times, once for each known pool, and coalesce the results. 
4. Test that the results returned in steps 2 and 3 are identical.

### :heavy_check_mark: Live Data

Run the following command to get a list of all stake pools sorted by ID:
```sh
cardano-wallet stake-pool list --stake 1000 | jq 'sort_by(.id)' > stake-pool-list
```
The results should be identical for both `master` and the branch from PR #2111.

**Comment by jonathanknowles** [comment]
I wonder if this is simply due to the fact that wallet syncing occupies CPU and disk resources, and having several wallets syncing in parallel might cause so much resource contention that querying the pool database slows down?

One possible factor is that we currently perform at least **(<span>2</span>_n_ + 1)** database queries to construct the list of pools, where **_n_** is the set of known pool identifiers. (See [here](https://github.com/input-output-hk/cardano-wallet/blob/3aa7d52bf645d244720105335f52e0745a36044c/lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs#L432-L454).)

Normally, this wouldn't be an issue, as individual queries are executed very quickly. But if the query latency increases, executing **(<span>2</span>_n_ + 1)** queries becomes a problem.

We have a technical debt task here to examine the use of more efficient queries: https://jira.iohk.io/browse/ADP-383

**Comment by piotr-iohk** [comment]
LGTM!

Results from manual verification on mainnet -> https://github.com/input-output-hk/cardano-wallet/pull/2111#issuecomment-687007013.
