### ISSUE TITLE
Ajust jsonToMetadata and jsonFromMetadata from cardano-api

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#2098]
# Context

These functions are making several implicit conversion when dealing with JSON data which make them very unpractical to use. 

# Decision

a. Encode JSON as CBOR considering only the following "optimizations"
b. Hexadecimal sequences starting with 0x are encoded as CBOR bytestring.
c. JSON keys that are numbers are encoded as CBOR numbers.
d. CBOR is shown as JSON when possible, or as a string representing JSON-encoded data when not (i.e. when map keys aren't numbers or strings).
e. CBOR bytestrings are represented as hexadecimal strings prefixed with 0x

NOTE 1: Roundtripping would only work in one direction, when coming from a JSON value and that's totally fine.
NOTE 2: Complexe metadata using non-string keys in maps will render with funky keys in JSON, that's acceptable.
NOTE 3: Related Slack thread https://input-output-rnd.slack.com/archives/GR599HMFX/p1598966521093500

# Acceptance Criteria

---

# Development 

- See: https://github.com/input-output-hk/cardano-node/pull/1797
- Integrated in: #2131 

# QA 

- Metadata have been added to database property and state machine tests. Metadata are generated from JSON objects, as they would be in the API which guarantees that they roundtrip to JSON and from JSON back. Plus, any arbitrary metadata is guaranteed to be convertible to JSON by the type system. See generators here:

  - https://github.com/input-output-hk/cardano-wallet/blob/9721d5ed729212a4df69d484dfe8f12383800913/lib/core/test/unit/Cardano/Wallet/Gen.hs#L169-L241

- We use a patched version of cardano-node (patched on top of 1.19.1), which adds the fixed json conversions function. These functions are tested in cardano-api directly using a roundtrip property, and some golden tests to make sure we are in the end generating intended CBOR binary data:

  - https://github.com/input-output-hk/cardano-node/blob/eac29083ef25dc619f15854623275fb37e63d2b8/cardano-api/test/Test/Cardano/Api/MetaData.hs#L30-L55

**Comment by rvl** [comment]
I have a slight preference for a JSON representation which can perfectly map one-to-one with the on-chain metadata.

It's not much more burden on API users. There are already several limitations on what metadata they can set. It's definitely not POJO.

**Comment by piotr-iohk** [comment]
lgtm
