### ISSUE TITLE
Port and review the Ed25519 module from cardano-wallet to define derivation primitives needed for BIP-44 addressing

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#21]
# Context

This new wallet implementation will focus on implementing BIP-44's style of addressing and therefore, we can re-use most of the work already done in the legacy implementation and port the following module onto `cardano-wallet`:

- https://github.com/input-output-hk/cardano-wallet-legacy/blob/develop/src/Cardano/Wallet/Kernel/Ed25519Bip44.hs
- https://github.com/input-output-hk/cardano-wallet-legacy/blob/develop/test/unit/Golden/Ed25519Addresses.hs
- https://github.com/input-output-hk/cardano-wallet-legacy/blob/develop/test/unit/Test/Spec/Ed25519Bip44.hs

# Decision

1. We _should_ port the above module to `cardano-wallet` while getting rid of `cardano-sl` code
2. We _should_ adjust module according to our coding standards and guidelines
3. We _may_ adjust some 'raw' types to be more type-safe (key, indexes ... )

---

# Development Plan

- I intend to mostly copy/paste the content of the Ed25519 module form cardano-wallet
- I'll remove the 'EncryptedSecretKey' and get rid of encrypted key in memory altogether (use of 'ScrubbedBytes' from `memory`) 
- I intend to get inspiration from the wallet prototype and define custom types for indexes and keys to make the meaning of them all a bit clearer and more type-safe
- I intend to also port the relevant property-tests and add a few to get maximum code coverage 

# PR

| Number   | Base      |
| ---      | ---       |
| #46    | `master`  |
| #61  | `master` |

# QA 

- This module define a rather type-safe API when it comes to address derivation, leveraging phantom types on things like indexes and keys (that have a similar internal representation, but a different semantic depending at which stage they're used). This allows for preventing programming mistakes where an address public key would be used instead of a root public key, or when a hardened index would be instead of a soft one (and vice-versa). This can be seen / reviewed from the generated haddock documentation [here](https://input-output-hk.github.io/cardano-wallet/haddock/cardano-wallet-2.0.0/Cardano-Wallet-AddressDerivation.html)

- Beside the safety offered by types, we have a few unit tests covering for various things:

    - A set of tests to make sure our hand-written instances are correct [see here](https://github.com/input-output-hk/cardano-wallet/blob/KtorZ/%2321/ed25519-address-derivation/test/unit/Cardano/Wallet/AddressDerivationSpec.hs#L53-L68)

    - A set of tests to verify that our main property for sequential derivation holds (the **public key of** the derived **child private** key on a soft index is the same as the derived **child public** key on a soft index, [see here](https://github.com/input-output-hk/cardano-wallet/blob/KtorZ/%2321/ed25519-address-derivation/test/unit/Cardano/Wallet/AddressDerivationSpec.hs#L70-L74)

    - An extra set of golden tests which verify that the whole "pipeline", from a root private key down to the encoded address corresponding to an address public key matches those obtained from `cardano-cli` / `Icarus`. [see here](https://github.com/input-output-hk/cardano-wallet/blob/KtorZ/%2321/ed25519-address-derivation/test/unit/Cardano/Wallet/AddressDerivationSpec.hs#L76-L105)

**Comment by piotr-iohk** [comment]
lgtm! :+1:
