### ISSUE TITLE
Less verbose integration test output by redirecting wallet+node logs to file

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#2119]
# Context

An overload (~60MB) of log output make CI integration test failures hard to debug.

Right now, the following are printed to stdout:
1. Wallet logs
2. The logs of 4 nodes (node/relay, BFT, pool-0, pool-1, pool-2)
3. hspec output 
4. Other integration test setup logs, like faucet tx submission

# Decision

Redirect the node and wallet logs to a file.

The hspec output should be uninterrupted like this:
<img width="693" alt="Skärmavbild 2020-09-03 kl  16 42 27" src="https://user-images.githubusercontent.com/304423/92458896-4748e680-f1c6-11ea-8c09-d933dd35279c.png">

# Acceptance Criteria

- [ ] Wallet and node logs should be redirected to a file
- [ ] The full wallet and node logs must still be accessible from CI failures
- [ ] The stdout of the integration tests should mostly contain an uninterrupted Hspec tree

---

# Development 

#2123

# QA 

1. Logs from wallet and nodes can be logged to file by setting`TESTS_LOGDIR=/pathtodir` (logs technically also exist in the temporary directory)
2. Buildkite uploads these as [artifacts](https://buildkite.com/input-output-hk/cardano-wallet/builds/10777#6cfe9d4f-acba-482f-a1d2-6ab614b13690). The other CIs don't. We could fix if we find it needed.
3. `stack test cardano-wallet:integration` has much cleaner standard output.

**Comment by piotr-iohk** [comment]
lgtm :tada:
