### ISSUE TITLE
Wallet address pool gap is limited to 232

### ISSUE THREAD

**Issue by nikolaglumac** [cardano-foundation/cardano-wallet#2120]
# Context
 
When trying to restore a wallet with a `address_pool_gap` set to `1000` you end up with a wallet with `address_pool_gap` set to `232`.

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | 3feb1d09a4e37b46dcec92585870d8490b6bdf78 |
| Platform     | All         |
| Installation | Daedalus            |

# Steps to Reproduce

1. Trigger wallet restoration with the `address_pool_gap` set to `1000`:
```
"{"name":"Super wallet","mnemonic_sentence":["little","inch","art","moral","entire","alert","blossom","innocent","judge","flower","load","match","what","bargain","museum","sea","crush","rely","baby","rally","during","keen","borrow","carpet"],"passphrase":"Secret1234","address_pool_gap":1000}"
```

## Expected behavior

Wallet is restored and it's `address_pool_gap` is set to `1000`.

## Actual behavior
 
Wallet is restored and it's `address_pool_gap` is set to `232`:
```
"{"passphrase":{"last_updated_at":"2020-09-08T12:27:35.595262Z"},"address_pool_gap":232,"state":{"status":"syncing","progress":{"quantity":0,"unit":"percent"}},"balance":{"reward":{"quantity":0,"unit":"lovelace"},"total":{"quantity":0,"unit":"lovelace"},"available":{"quantity":0,"unit":"lovelace"}},"name":"Super wallet","delegation":{"next":[],"active":{"status":"not_delegating"}},"id":"82324b69f0c16847ab93977a23f4ae2b2f4dc8cc","tip":{"height":{"quantity":0,"unit":"block"},"epoch_number":0,"slot_number":0}}"
```

---

# Resolution 

- Fix the database internal type used for serializing and deserializing address pool gap ==> #2121

---

# QA 

- Test integration scenarios extended to have extra assertions controlling the value of the gap: 
    https://github.com/input-output-hk/cardano-wallet/blob/8e0c0cf1c3c65e6c5f8dd1f2ead008641cef77b9/lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Wallets.hs#L457-L470

**Comment by KtorZ** [comment]
Note for whoever pick this:

```
instance PersistFieldSql AddressPoolGap where
    sqlType _ = sqlType (Proxy @Word8)
```

and 

```
1000 `mod` 256 = 232
```
