### ISSUE TITLE
Provide slot number (flat slot) in network information

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#2148]
# Context

ADP-418

### User story

As an API user
I want to have access to the flat slot number (and not only the slot within the epoch)
so that I can construct transaction TTL that are relevant

# Decision

Add new fields to the `GET /network/information` API endpoint.

```json
{
  "node_tip": {
    "slot": 4705320
  },
  "network_tip": {
    "slot": 4705323
  }
}
```

# Acceptance Criteria

1. API must show node tip as an absolute slot count from genesis
2. API must show network tip as an absolute slot count from genesis, when known.

---

# Development 

1. Update swagger spec
2. Edit API types
3. Adjust API handler
4. Adjust integration tests for network information.

# QA 

1. API golden json test data updated for new field.
2. Integration tests modified to check presence and value of slot field - `lib/core-integration/src/Test/Integration/Scenario/API/Network.hs`

**Comment by piotr-iohk** [comment]
lgtm.
