### ISSUE TITLE
Update API documentation for saturation and relative stake

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#2155]
# Context

#1980, ADP-431

With cardano-node 1.20.0, the `relative_stake` field is now relative to the total stake, not the active stake. This makes the `saturation` calculation correct (tracked by #1980), but it also provides an opportunity to clarify concepts in the API docs.

1.20.0 also made changes to from which snapshot the `relative_stake` is reported. I believe

| -  | 1.19.0 node + wallet | 1.20.0 node + wallet |
|-| ------------- | ------------- |
| saturation in ranking | active (taken at end of e-2)  | live  |
|  wallet api saturation field | non-sensical  | correct (and live) |
|  `relative_stake` snapshot | active (taken at end of e-2)  | live  |
|  `relative_stake` relative to | "active" (delegated) stake | total stake  |

Relevant upstream PRs:
- https://github.com/input-output-hk/cardano-ledger-specs/pull/1854
- https://github.com/input-output-hk/ouroboros-network/pull/2603

# Decision

Review and revise the API documentation.

# Acceptance Criteria

- [ ] API documentation for `relative_stake`, `saturation`, and `non_myopic_member_rewards` must be correct
- [ ] API documentation for `relative_stake`,  `saturation` and `non_myopic_member_rewards` should be helpful

---

# Development 

#2162

# QA 

Docs updated in #2162 . Some context on the individual changes is provided in that PR.

**Comment by piotr-iohk** [comment]
lgtm
