### ISSUE TITLE
Allow flexible SMASH selection without restarting the wallet

### ISSUE THREAD

**Issue by hasufell** [cardano-foundation/cardano-wallet#2163]
# Context

Currently the wallet needs to be restarted when selecting a SMASH server via cli:

```sh
wallet serve --smash-url URL
```

Daedalus developers would like to have an endpoint to change the smash server while the wallet is running.

# Decision

1 implement the following endpoint: `curl -X PUT --data '{ "settings": { "pool_metadata_source": "my.smash.uri" } }' http://localhost:8090/v2/settings/` ... possible values are `direct`, `none` and an actual url
2. The settings will be stored in the database in a separate table as a single row with one column per setting (as text or json).
3. The sync thread will poll the database for the setting.
4. On PUT, the metadata table will be dropped, forcing it to re-sync automatically with the new setting.
5. When selecting SMASH server on wallet start, compare against database setting and drop the metadata table if they diverge.

## Rationale

1. simple and extendable
2. Alternative would be ephemeral state, but that's more complicated implementation-wise and would require daedalus to have a persistent state about the smash setting.
3. Simplicity of implementation. Otherwise we need a way to restart the sync thread, which also requires mutable ephemeral state.
4. see AC
5. see AC

# Acceptance Criteria

1. The user can select the SMASH server at wallet start
2. The user can select the SMASH server after wallet start without restarting the wallet
3. Changing the SMASH server causes a re-sync of the metadata

---

# Development 

https://github.com/input-output-hk/cardano-wallet/pull/2156

# QA 

1. integration test for Settings change: https://github.com/input-output-hk/cardano-wallet/pull/2214/files#diff-ee9ceec3a14de991a6d049756e4830a4
2. json roundtrip test for SettingsPutData: https://github.com/input-output-hk/cardano-wallet/pull/2214/files#diff-aa8e2781f330251ae7904f42941b1de2
3. updated swagger definition: https://github.com/input-output-hk/cardano-wallet/pull/2214/files#diff-6816a7fbd0d7c7e715b8225b1709c612

**Comment by hasufell** [comment]
@piotr-iohk I updated QA section

**Comment by piotr-iohk** [comment]
LGTM.

Additional integration test added in #2225. (Hopefully can be merged some day...)
