### ISSUE TITLE
Address format in Shelley era (single address)

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#217]
# Context

In the next Cardano era, address format is going to be different from what it is currently.
A specification of this revision is available on [input-output-hk/implementation-decisions](https://github.com/input-output-hk/implementation-decisions/blob/master/text/0001-address.md).

Note that in Shelley, addresses can now hold a staking key when they're involved into 
delegation. 

Another singularity of this new approach is the overall text-encoding of those addresses
which change from `base58` to [bech32](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki).

# Decision

- Implement a new version of the `keyToAddress` interface to support the new address format
  for both single and grouped addresses.

- Make sure that the address text-encoding is tight to the address format we chose (either
  review an existing type-class or create a new one to abstract the text-encoding from the 
  wallet core)

# Acceptance Criteria

1. We _must_ support creating _single address_ from a given public key using the new format

---

# Development Plan

- [x] Make sure address encoding is abstracted over the target backend
- [x] Implement `keyToAddress` for `Jormungandr` backend
- [x] Try to generate golden tests using `jcli` and have them as unit test in `cardano-wallet-jormungandr` ?

# PR

| Number   | Base      |
| ---      | ---       |
| #313       | `master`  |
| #336  | `master` |

# QA 

- PR #336 implements the `EncodeAddress` and `DecodeAddress` interfaces for Jormungandr. Jormungandr is slightly more complex than the `cardano-http-bridge` since it supports two different formats: bech32 (for new standard addresses) and base58 (for legacy addresses).

- In the test-suite, we have two kinds of tests. The first kind does standard round-trip tests to verify that decoding an address that we encoded works as expected. We have made sure to generate both kinds of addresses, being however slightly more biased towards the new format since the old one is already rather well tested in the `http-bridge` package. See: 

    - The [Arbitrary generator](https://github.com/input-output-hk/cardano-wallet/blob/master/lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/CompatibilitySpec.hs#L158-L162)

    - The [roundtrip test](https://github.com/input-output-hk/cardano-wallet/blob/master/lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/CompatibilitySpec.hs#L47-L50)

- Added also a variety of negative tests to test various decoding paths. 

    - Some are network-agnostic like [here](https://github.com/input-output-hk/cardano-wallet/blob/master/lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/CompatibilitySpec.hs#L52-L59)

    - Some actually depends on the target network. So we have them for:
        - [Mainnet](https://github.com/input-output-hk/cardano-wallet/blob/master/lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/CompatibilitySpec.hs#L66-L74)
        - [Testnet](https://github.com/input-output-hk/cardano-wallet/blob/master/lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/CompatibilitySpec.hs#L97-L105)
        - NOTE: there's no "staging" for Jormungandr

- Also generated a few addresses using `jcli` from the rust team, comparing results for both single and grouped addresses and also on both networks:
        - [Mainnet](https://github.com/input-output-hk/cardano-wallet/blob/master/lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/CompatibilitySpec.hs#L75-L94)
        - [Testnet](https://github.com/input-output-hk/cardano-wallet/blob/master/lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/CompatibilitySpec.hs#L106-L125)

- This gives us a 100% coverage on the `EncodeAddress` and `DecodeAddress` instance, with a pretty good confidence that we are able to encode and decode Shelley addresses correctly, might they be new or legacy ones.

**Comment by KtorZ** [comment]
# Current State of Affairs

We currently manipulate and represent addresses as:


```hs
newtype Address = Address ByteString
```

where the address internal representation is the whole address payload on Byron. In other
words, the `ByteString` is a cbor encoding of various consistuent derived from the address
public key.

We represent addresses in a human-friendly way using a `Base58` encoding at the API-level.
This goes though `ToText` and `FromText` instances:

```hs
instance FromText Address where
    fromText x = maybe
        (Left $ TextDecodingError err)
        (pure . Address)
        (decodeBase58 bitcoinAlphabet $ T.encodeUtf8 x)
      where
        err = "Unable to decode Address: expected Base58 encoding"

instance ToText Address where
    toText = T.decodeUtf8 . encodeBase58 bitcoinAlphabet . getAddress
```

We do also _currently_ use this address instance to serialize to and deserialize form the
database.

> `NOTE`:
>
> There's a problem inherent to our current design: using an invalid address (which has
> however a valid base58 encoding, throws hard because we only verify the address payload
> when encoding it). This can be fixed by forcing the payload to be decoded when parsing the address
> from a base58 text string.

## Problem to solve

In Shelley, addresses can be one of these three formats:

- Byron addresses, as described above
- Single addresses, holding only a public spending key
- Group addresses, holding both a spending key and delegation key

In addition to these format, we also have a new user-facing encoding for `Single` and
`Group` addresses: `bech32`.

# New Address Data-Type

One area to explore would be to change `Address` definition with:

```hs
data Address
  = ByronAddress !ByteString
  | SingleAddress !???
  | GroupAddress !??? !???
```

This allows for clearly capturing within the `Address` type itself, what the encoding should be.
Now, what to put in `???`, this requires some thoughts:

- `XPub` seems like the most legitimate choice (since the address is a concatenation of a
  discriminant byte and a public key). However, how do we parse an address then? We would
  need to verify the discriminant byte and therefore, know what is the underlying `network`.
  This is something we don't know within the `core` package because this depends on the
  target backend we select. So the transformation from and to bech32 text has to be done within
  the corresponding backend package.

- `ByteString` is a sensible choice here too despite the lost of expressiveness at the type-level (which isn't necessarily a _bad_ thing, cf below). Storing the whole address payload as a
  raw `ByteString` helps to keep the whole core engine fairly agnostic to _what_ the internals of an address are, leaving them up to the node backend.

## Drawbacks

Although elegant from the design perspective, this approach present one major drawback:

We then have to consider addresses always as a sum type between these three constructors whereas, in most places (except at the edge of the application), addresses are really just treated as an opaque type; a wrapper around a payload so-to-speak. 

The content of that payload is interesting only when we want to display the address in a human-friendly way. For the rest, we do maintain a dictionary of Address ->  Derivation Index in the BIP-44 pools so address can be derived from their account key if necessary (and we do need this anyway to recover the private key from an address!). 

Considering a sum-type means that we would have to consider testing all branches, and their possible interaction with the rest of the codebase, whereas they're all treated in an exact same way. Also, what happened for the code within the bridge, jormungandr or shelley haskell for they use different branches of this sum-type (bridge doesn't have group and single address, shelley haskell has extra "pointer" branches that aren't yet in jormungandr etc ...). 

## Keep it simple

On the contrary, keeping the address definition as simply a wrapper around a raw bytestring presents many advantages. For most of the code, the 'Address' remains quite opaque and is treated as such. We only consider the encoding at the edge of the application, for what is user-facing (i.e. the API) and we defer that decision to the backend package via proper type classes parameterized by the backend parameter.

This also gives us a very easy testing (as we do now) where the payload of an address can pretty much be anything. When it matters (comparing or submitting transactions), then we may shove in a relevant payload that is compatible with the target backend. 

# Parameterizing over the backend type

As we do for `TxId`, it is possible to parameterize our wallet layer over a `target` (or `t`)
type parameter which embeds the address format. This allows for keeping the address encoding
outside of the wallet core logic, decided by the caller / target backend. In particular,
it makes it possible to use different encoding on different backend, and/or, disallow specific
encodings or address constructors.

```hs
class EncodeAddress t where
    encodeAddress :: Proxy t -> Address -> Text

class DecodeAddress t where
    decodeAddress :: Proxy t -> Text -> Either TextDecodingError Address
```

So here, depending on which backend we're dealing with, we may end up rejecting addresses that are encoded in bech32, or those with a wrong network magic. The encoding is also a bit subtle as the instances will have to peek into the address raw bytes to determine what sort of address it is. Still, this is a fair price to pay for simplicity.

**Comment by piotr-iohk** [comment]
lgtm! :+1:
