### ISSUE TITLE
Estimating fees on empty Shelley wallet takes 5-6s

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#2170]
# Context
 
According to [benchmarks](http://cardano-wallet-benchmarks.herokuapp.com/mainnet-restoration?type_of_wallet=all&type_of_measurement=estimating_fees_time) since [nb #636](https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/636) (revision https://github.com/input-output-hk/cardano-wallet/commit/76b3a6d2618d628e4f08d37c92fce8fd1a7eb130) fee estimation time increased from ~1.5s to 5-6s on empty Shelley wallet.

![Screenshot from 2020-09-23 12-44-18](https://user-images.githubusercontent.com/42900201/94002722-8c5e4280-fd9a-11ea-8f7c-393b28ea0f53.png)

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | `2020.9.11 (git revision: ffeca1d9e0f302111588c7890785051b6cc6b0da)` |
| Platform     | Linux, all?          |
| Installation | from source            |

# Steps to Reproduce

1. Trigger fee estimation on empty Shelley wallet

## Expected behavior

Should return `not_enough_money` right away.

## Actual behavior
 
Takes 5-6s on nightly benchmarks.
Note for comparison, it takes ~3-4s for `0.4% seq wallet`.

(On my local machine I got ~3s for empty wallet, and ~1s on small wallet with funds)

---

# Resolution 

---

# QA

**Comment by Anviking** [comment]
Looking at the commit history around  76b3a6d https://github.com/input-output-hk/cardano-wallet/commits/master?after=647632e17f1a4add822ab76aef01ba6772a7b813+244&branch=master,

it seems https://github.com/input-output-hk/cardano-wallet/pull/2112 was merged just before, which seems suspicious

**Comment by piotr-iohk** [comment]
Resolved with #2348.

benchmark results on branch -> https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/743.

E.g.:

1-wallets-to-0.1:
"estimateFeesTime":"8.950 ms"
used to be = 9.975 s


100-wallets-to-0.01:
"estimateFeesTime":"117.2 ms"
used to be = 19.7 s
