### ISSUE TITLE
Explore exposing integration tests cluster for a wider audience

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#2175]
# Context

We use a quite sophisticated setup for our integration tests, with a cluster of pools and pre-registered wallets with funds, rewards etc ... That's useful for testing the wallet, but also for a wider audience looking for testing things with Shelley.

# Decision

# Acceptance Criteria

1. One _must_ be able to start an integration test cluster easily from an executable.
2. The tool _may_ not have a command-line or any sophisticated UX as it is meant for internal use primarily. 

---

# Development 

- Create a standalone executable which can start an integration cluster ==> #2178 

# QA 

- This is for internal use mainly, so I admit doing only very little smoke-testing. The code that spins up the cluster is actually very small and re-use constructors and helpers used for our actual integration tests so I am quite confident that it _just works_ :upside_down_face:

**Comment by piotr-iohk** [comment]
It just works indeed. :tada:
