### ISSUE TITLE
Provide a way to map addresses to their derivation paths.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#2176]
# Context

We need a way to map **wallet-owned addresses** to their **derivation paths**, so that they can be exported through the API using the `ApiAddressDerivationPath` type. (See https://github.com/input-output-hk/cardano-wallet/issues/2174)

# Decision

Extend the `IsOurs` interface to return the derivation path corresponding to an address identified as _ours_ (instead of only a Boolean). 

# Acceptance Criteria

1. `IsOurs` must now return a `Maybe` instead of a raw `Bool`
2. `Just [derivationPath]` must be returned when the address belongs to us. 
3. `Nothing` must be returned when the address does not belong to us. 

(the old behavior can be recovered by composing `isOurs` with `isJust`).

# Development 

- #2219 

# QA 

- Extended `IsOurs` interface, existing database tests and model tests still pass (the old behavior can be recovered by composing `isOurs` with `isJust`). 

- Added an entry for golden tests regarding ToJSON / FromJSON serializations:
  https://github.com/input-output-hk/cardano-wallet/blob/364c48021961ee2bd9df3141bf5dec334e922ec9/lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs#L314

- Reworked some existing "negative tests" regarding extremum values
  https://github.com/input-output-hk/cardano-wallet/blob/364c48021961ee2bd9df3141bf5dec334e922ec9/lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs#L457-L475

- Added two migration tests from an Icarus and Shelley databases (there's now a derivation prefix stored with each `SeqState`, this required doing a manual migration). The test show that (a) a previous database can be migrated and (b) after migration, the right prefix has been stored in the database. 
  https://github.com/input-output-hk/cardano-wallet/blob/364c48021961ee2bd9df3141bf5dec334e922ec9/lib/core/test/unit/Cardano/Wallet/DB/SqliteSpec.hs#L249-L263

- Added roundtrip text instances for the newly introduced `DerivationIndex`
  https://github.com/input-output-hk/cardano-wallet/blob/364c48021961ee2bd9df3141bf5dec334e922ec9/lib/core/test/unit/Cardano/Wallet/Primitive/AddressDiscovery/SequentialSpec.hs#L148-L149

- Added an extensive comment about `DerivationIndex` 
  https://github.com/input-output-hk/cardano-wallet/blob/364c48021961ee2bd9df3141bf5dec334e922ec9/lib/core/src/Cardano/Wallet/Primitive/Types.hs#L1172-L1190

- Extended an existing integration scenario to also assess for the derivation path of the result, checking that the prefix is as expected and that the path contains indeed 5 elements. 
  https://github.com/input-output-hk/cardano-wallet/blob/364c48021961ee2bd9df3141bf5dec334e922ec9/lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Wallets.hs#L918-L940

- Adjusted API documentation and examples to reflect the latest changes (derivation path now stored as a list of indexes as strings):
  https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/selectCoins

**Comment by KtorZ** [comment]
You'll also need a given _state_ to make this possible, like `IsOurs` or `IsOwned` also make use of.

**Comment by piotr-iohk** [comment]
LGTM.
