### ISSUE TITLE
Correct/update wallet backend API version

### ISSUE THREAD

**Issue by tatyanavych** [cardano-foundation/cardano-wallet#2182]
Cardano wallet [API referenced by release 2020.9.22](https://input-output-hk.github.io/cardano-wallet/api/v2020-09-22/)  leads to API 2.0.0 that has been unchanged for some time though there have been changes in the API in the past releases.
Please, update API version according to the chosen versioning scheme and changes for every release where there are changes.

### Expected version

TBD

### Actual version

2.0.0

**Comment by rvl** [comment]
Hi @tatyanavych, what version number do you expect it be?

Should it match the release, e.g. `2020.9.22`? That would be simple to fix.

Or should it use another versioning scheme? Because sometimes the API does not change at all between releases. Additionally, we use a URL path prefix `/v2` to denote that our API implements the second or third major revision of the cardano-wallet API.

**Comment by KtorZ** [comment]
@rvl ideally, the same as the version we release on even if the API does not change so there's consistency. I think we could leave the swagger doc with `unreleased`, `edge` or a git revision so it's clear when looking at the doc from `master` and replace that with a tag when packaging the doc.

**Comment by piotr-iohk** [comment]
How about having the version in swagger updated by https://github.com/input-output-hk/cardano-wallet/blob/master/scripts/make_release.sh script on each new release?

**Comment by tatyanavych** [comment]
For the API I would recommend [semver](https://semver.org/), and increment if there is a change in the API.
As cardano-wallet uses date-based versioning you, then, may want to track (code version, API version) info that could be an extra  maintenance work you may not want.
The simple case to use date-based version for both may reduce maintenance work, but will not tell users when there are changes in the API, when there are no.
I deliberately did not specify expected versioning scheme to allow team to think and to choose the best suitable option.
