### ISSUE TITLE
Will Byron addresses starting with Ae2 be disabled in the future?

### ISSUE THREAD

**Issue by vae520283995** [cardano-foundation/cardano-wallet#2186]
There are many address formats now, and many exchanges still use addresses in the Byron era, starting with Ddz or Ae2. Now the Shelley era starts with addr1, will the address in the Byron era be disabled in the future?
If it is disabled, when is it?

**Comment by rdlrt** [comment]
@vae520283995  They're part of chain history. I would find it very difficult to be getting rid of. But regardless, you *SHOULD* upgrade as features of what you can do with Byron wallets are quite limited.

The exchanges do - however - need to update their backends, and once they've done that, its easier for them to simply use shelley addresses as the default

**Comment by vae520283995** [comment]
> @vae520283995 They're part of chain history. I would find it very difficult to be getting rid of. But regardless, you _SHOULD_ upgrade as features of what you can do with Byron wallets are quite limited.
> 
> The exchanges do - however - need to update their backends, and once they've done that, its easier for them to simply use shelley addresses as the default

Thank you for your answer. Due to time constraints, I cannot update the address to the shelley address. I only support withdrawals to the shelley address

**Comment by KtorZ** [comment]
As @rdlrt pointed out, Byron addresses with all their weirdness (and transactions, and signatures, and.. everything that existed in the Byron chain) are there forever. We can't possibly get rid of those without wiping out the blockchain history. It more of a philosophical question than a technical issue :)

**Comment by rvl** [comment]
For how long will the `/v2/byron-wallets` API be supported?

**Comment by KtorZ** [comment]
There's no short, medium or long-term plan to discontinue it. Most of our partners are still relying on it and the `/v2/wallets` is not a suitable replacement for most exchanges. 
So, until we have a better alternative to offer, it'll be supported.
