### ISSUE TITLE
Jörmungandr REST-API / Network Layer

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#219]
# Context

In a similar fashion to how the cardano-http-bridge works, Jörmungandr offers a
REST API to work with. This API is still in progress / under development but
already offers a few endpoints we can start integrating with in order to communicate
with the node.

A swagger specification for this API is available [here](https://gist.github.com/CodeSandwich/1349fef0d1fd277b018be04e996c6df2/) ([rendered](https://rebilly.github.io/ReDoc/?url=https://gist.githubusercontent.com/CodeSandwich/1349fef0d1fd277b018be04e996c6df2/raw/c25e57e7d99c634cfbc615d2be40f9fc4b489ee1/node_rest_open_api.yml#/paths/~1v0~1tip/get))

# Decision

- Implement a new instance of our `NetworkLayer` for Jörmungandr, using the API provided in Context

# Acceptance Criteria

1. The `getBlocks` from our `NetworkLayer` _must_ be implemented using Jörmungandr REST API
2. The `networkTip` from our `NetworkLayer` _must_ be implemented using Jörmungandr REST API
3. The `postTx` from out `NetworkLayer` _must_ be implemented using Jörmungandr REST API

---

# Development Plan

### General
(@Anviking vvv)
- [x] Define the Servant Api type
- [x] The `Network` module needs to be implemented. Some parts might be non-trivial as it differs from http-bridge.
    - [x] Implement `JormungandrLayer` (excluding `postTx`)
    - [x] Implement NetworkLayer
        - [x] Change the wallet tip to `(SlotId, BlockId)`
        - [x] Should then be able to implement a Jormungandr backed `NetworkLayer` 
        - [x] ~It would be… good… to have more blocks to test `getDescendants`. I haven't managed to get some yet.~ #382 

(@KtorZ vvv)
- [x] Extend `BlockHeader` definition to include the current block hash
- [x] Compute corresponding block header hash for `Jormungandr` implementation
- [x] Review how `initWallet` received its first blockHeader ....  

### `signTx`
Signing might be some substantial amount of work
- [x] See if we can submit transactions to jormungandr using the ~old signing schema~, in a minimum viable way. We'd have to add encoders for transactions and witnesses

### Finalizing
- [x] Review code and add more tests

# PR

| Number   | Base      |
| ---      | ---       |
| #310        | `master`  |
| #321         | `master`  |
| #325          | `master`  |
| #362           | `master`  |
| #366            | (unmerged) | 
| #384         | `master` |
| #400         | `master` |
| #433           | `master` |
| #436          | `master` |
| #437         | `master` |
| #439          | `master` |
| #451         | `master` |
| #452         | `master` |
| #463           | `master` |
| #476          | `master` |
| #487          | `master` |

# QA 

- We have implemented a `NetworkLayer` for Jörmungandr using an underlying `JörmungandrLayer`. We added some integration test cases covering `networkTip`, `nextBlocks` and `postTx`. They are  **not** able to test that transactions get accepted by the node. I believe that is tested by #358 though. https://github.com/input-output-hk/cardano-wallet/blob/master/lib/jormungandr/test/integration/Cardano/Wallet/Jormungandr/NetworkSpec.hs#L91-L225
- We fixed flaws with the `Jörmungandr.Binary` module (verified by working integration tests) and goldens
- We made encoders "safer" by throwing instead of overflowing when converting integers #487. The coin-selection shouldn't create that large txs, so we should never hit those cases, but it's good to be safe.
- We added a `TxId` class and comparing `txId` with `jcli`-generated golden tests: https://github.com/input-output-hk/cardano-wallet/blob/a2f24584b3a1015487ecadff523bd89242024616/lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/CompatibilitySpec.hs#L112-L157
- We implemented the Jörmungandr `TransactionLayer` and have golden tests comparing `jcli` with `mkStdTx`: https://github.com/input-output-hk/cardano-wallet/blob/a2f24584b3a1015487ecadff523bd89242024616/lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/TransactionSpec.hs#L225-L360
- We have added Binary roundtrips for signed transactions and addresses #476 
- We were forced to change the type of the wallet and network tip from `SlotId` to `BlockHeader`.`BlockHeader` contains `slotId` and a `prevBlockHash`. Jörmungandr needs `prevBlockHash` and HttpBridge needs `slotId`. Should be covered by existing Network-tests and DB-related tests.
- Aside from one initially, I believe the integration tests (#358 ) hasn't discovered any problems with this code, giving us some more assurance.

**Comment by KtorZ** [comment]
@Anviking I'd recommend having a look at #242 before looking into that one :pray:

**Comment by Anviking** [comment]
Having hidden limit of 255 ins/outs on `(Tx,[TxWitness])` might be fine for transactions created with our coin-selection.

If we want to serve an endpoint corresponding to [`signTx`](https://github.com/input-output-hk/cardano-wallet/blob/a2f24584b3a1015487ecadff523bd89242024616/lib/core/src/Cardano/Wallet.hs#L610-L642) (not sure if we ever will) it might be nice to check that limit and fail early. Otherwise the user won't notice until submitting the signed transaction.

**Comment by piotr-iohk** [comment]
lgtm :+1:
