### ISSUE TITLE
Tweak `it` for more useful information on failures

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#2192]
# Context

ADP-419

We want to make CI failures easier to understand.

It happens that:
1. CI simply times out on a single test. Identifying _which_ test is non-trivial.
2. Our custom `it` (which automatically retries all tests once on failure), retries something that cannot be retried, and returns an unhelpful error message instead of the first helpful one. (Some tests use hard-coded mnemonics, which can only be spent once.)

# Decision

- Add a long timeout to our custom `it`, as a last resort to turn timeouts into failures. We don't want it interfering with long tests, so 10 minutes should probably work.
- If the retry-attempt also fails, return the _first_ error.

# Acceptance Criteria

- A test that is stuck in a weird place should cause a _test-failure_, not a global _CI timeout_.
- When a test fails, and the retry attempt fails, the original error should be presented.

---

# Development 

#2181 
#2193
#2194

# QA 

> - Add a long timeout to our custom it, as a last resort to turn timeouts into failures. We don't want it interfering with long tests, so 10 minutes should probably work.
> - If the retry-attempt also fails, return the first error.

This is done, and tested by
https://github.com/input-output-hk/cardano-wallet/blob/master/lib/test-utils/test/Test/Hspec/ExtraSpec.hs#L33-L64

**Comment by rvl** [comment]
I was trying to be funny before when suggesting to prefix the function name with `sh`, but there is an element of truth in every joke...

If we persist with using this variation of `it`, we are potentially hiding real bugs in our application - the tricky type which only happen occasionally - and on users' systems not developers'.

So it should be used with caution. I think we should _try to_ put this function away, and only deploy it while we are suffering from test stability issues.

**Comment by Anviking** [comment]
> and only deploy it while we are suffering from test stability issues.

😶 When is that not the case? 😞 

Otherwise I 100% agree.

**Comment by piotr-iohk** [comment]
lgtm
