### ISSUE TITLE
Flaky test - STAKE_POOLS_LIST_01 - List stake pools

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#2196]
# Context

https://github.com/input-output-hk/cardano-wallet/pull/2184#issuecomment-698850257 (build 10764)
https://github.com/input-output-hk/cardano-wallet/pull/2185#issuecomment-699868895
https://github.com/input-output-hk/cardano-wallet/pull/2107#issuecomment-700044743
https://github.com/input-output-hk/cardano-wallet/pull/2193#issuecomment-702491672

https://github.com/input-output-hk/cardano-wallet/pull/2198#issuecomment-702514443
https://github.com/input-output-hk/cardano-wallet/pull/2195#issuecomment-701538552
https://github.com/input-output-hk/cardano-wallet/pull/2198#issuecomment-702628123
 

# Test Case

https://github.com/input-output-hk/cardano-wallet/blob/647632e17f1a4add822ab76aef01ba6772a7b813/lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs#L726-L735

# Failure / Counter-example

`(Reason "predicate failed on: 0")`

---

# Resolution 

---

Stake pool worker is crashing due to a History Interpreter failure. I think, current epoch check used to garbage collect pools.

But
1. Shouldn't the worker restart?
2. How can the stake pool chain follower be one epoch ahead of the tip-sync client updating the `TimeInterpreter`? In theory this should be possible, but it should be extremely rare, not every third CI run...

# QA

**Comment by hasufell** [comment]
Have you tried increasing the eventually-timeout? Afair it's 90s.

**Comment by Anviking** [comment]
> Have you tried increasing the eventually-timeout? Afair it's 90s.

The pools are set up at the beginning of the tests (probably at least 10 minutes earlier). By this time, they really should have produced blocks, and have saturation 🤔

**Comment by Anviking** [comment]
Running locally I now got
```
Failures:

  src/Test/Integration/Scenario/API/Shelley/StakePools.hs:151:9:
  1) API Specifications, SHELLEY_STAKE_POOLS, STAKE_POOLS_JOIN_01 - Cannot join existent stakepool with wrong password
       uncaught exception: IOException of type UserError
       user error (Pattern match failure in do expression at src/Test/Integration/Scenario/API/Shelley/StakePools.hs:151:9-14)

  To rerun use: --match "/API Specifications/SHELLEY_STAKE_POOLS/STAKE_POOLS_JOIN_01 - Cannot join existent stakepool with wrong password/"
```
So seems like `GET /stake-pools` didn't return any pools…

**Comment by Anviking** [comment]
I have seen logs like
```
[cardano-wallet.network:Info:1115] [2020-10-02 08:24:38.88 UTC] Fetched pool data from node tip using LSQ. Got 0 pools in the stake distribution, and 0 pools in the non-myopic member reward map.
```
and when bisecting I get _consistent_ failures, even all the way back to `v2020-09-11`:
```
git bisect start
# bad: [b9bc46beb8528a348b95cbdf38479ff0a71c9929] Merge #2194
git bisect bad b9bc46beb8528a348b95cbdf38479ff0a71c9929
# bad: [fcc5afb12e5e16351193e5f0bd043395848c5965] Merge #2160 #2165
git bisect bad fcc5afb12e5e16351193e5f0bd043395848c5965
# bad: [ffeca1d9e0f302111588c7890785051b6cc6b0da] Merge #2164
git bisect bad ffeca1d9e0f302111588c7890785051b6cc6b0da
# bad: [0525347dc0c1e5a0ed1ba35600a93b509655b2e4] use newer version of node.js in .travis.yml and lower down tls default to 1.2
git bisect bad 0525347dc0c1e5a0ed1ba35600a93b509655b2e4
```
I wonder if the cardano-node or cardano-cli version has anything to do with it.

Weird that it fails consistently locally, but only occasionally in CI... Or at least it occasionally seems to _succeed_ in CI. 

Edit: wait, maybe I had `NO_POOLS` set 😅

**Comment by hasufell** [comment]
```
        MsgRegisteringStakePools 0 -> mconcat
                [ "Not registering any stake pools due to "
                , "NO_POOLS=1. Some tests may fail."
                ]
```

Yeah, I wonder if the tests should be skipped if this env var is set

**Comment by Anviking** [comment]
It seems that since 2020-09-25 15:00:17, there has been a 30% bors failure rate, and all failures have been due to this issue.
[bors-analysis.txt](https://github.com/input-output-hk/cardano-wallet/files/5317451/bors-analysis.txt)

(Before that point there are more failures, but due to timeouts)

src: https://bors-ng.aws.iohkdev.io/repositories/12

**Comment by hasufell** [comment]
The only commit doing changes to the behavior of the handler recently was https://github.com/input-output-hk/cardano-wallet/commit/1b4692c4f8 I think, but that doesn't seem too related.

**Comment by Anviking** [comment]
- I have run `stack test cardano-wallet:integration` locally on b9bc46beb8528a348b95cbdf38479ff0a71c9929 5 times and it only succeeded.
- Looking at the wallet logs of the failures, I see no `Got 0 pools`. Only `Got 3 pools` over LSQ from the node.

I guess the last point suggests that there must be missing or faulty DB data causing this `dropMissing` . Not quite sure how to investigate further yet… https://github.com/input-output-hk/cardano-wallet/blob/b9bc46beb8528a348b95cbdf38479ff0a71c9929/lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs#L298

**Comment by Anviking** [comment]
Ah!

```
[31m[cardano-wallet.pools-engine:Error:1590][0m [2020-09-25 09:21:58.45 UTC] Unexpected error following the chain: PastHorizon {pastHorizonCallStack = [("runQuery",SrcLoc {srcLocPackage = "ouroboros-consensus-0.1.0.0-AioOemZGwIVHvzJr0KBFls", srcLocModule = "Ouroboros.Consensus.HardFork.History.Qry", srcLocFile = "src/Ouroboros/Consensus/HardFork/History/Qry.hs", srcLocStartLine = 425, srcLocStartCol = 44, srcLocEndLine = 425, srcLocEndCol = 64}),("interpretQuery",SrcLoc {srcLocPackage = "cardano-wallet-core-2020.9.22-y3Qxf99XvEGRTIqFVPBVR", srcLocModule = "Cardano.Wallet.Primitive.Slotting", srcLocFile = "src/Cardano/Wallet/Primitive/Slotting.hs", srcLocStartLine = 323, srcLocStartCol = 26, srcLocEndLine = 323, srcLocEndCol = 49}),("runQuery",SrcLoc {srcLocPackage = "cardano-wallet-core-2020.9.22-y3Qxf99XvEGRTIqFVPBVR", srcLocModule = "Cardano.Wallet.Primitive.Slotting", srcLocFile = "src/Cardano/Wallet/Primitive/Slotting.hs", srcLocStartLine = 292, srcLocStartCol = 5, srcLocEndLine = 292, srcLocEndCol = 28}),("mkTimeInterpreter",SrcLoc {srcLocPackage = "cardano-wallet-2020.9.22-3wkxwQkD8C3HARSBAveirp", srcLocModule = "Cardano.Wallet.Shelley.Network", srcLocFile = "src/Cardano/Wallet/Shelley/Network.hs", srcLocStartLine = 481, srcLocStartCol = 14, srcLocEndLine = 481, srcLocEndCol = 69}),("_timeInterpreterQuery",SrcLoc {srcLocPackage = "cardano-wallet-2020.9.22-3wkxwQkD8C3HARSBAveirp", srcLocModule = "Cardano.Wallet.Shelley.Network", srcLocFile = "src/Cardano/Wallet/Shelley/Network.hs", srcLocStartLine = 329, srcLocStartCol = 33, srcLocEndLine = 329, srcLocEndCol = 69}),("timeInterpreter",SrcLoc {srcLocPackage = "cardano-wallet-core-2020.9.22-y3Qxf99XvEGRTIqFVPBVR", srcLocModule = "Cardano.Wallet.Network", srcLocFile = "src/Cardano/Wallet/Network.hs", srcLocStartLine = 153, srcLocStartCol = 7, srcLocEndLine = 153, srcLocEndCol = 22})], pastHorizonExpression = Some (ELet (ELet (ERelSlotToEpoch (EAbsToRelSlot (ELit (SlotNo 80)))) (\x0 -> EPair (ERelToAbsEpoch (EVar x0)) (ESnd (EVar x0)))) (\x0 -> EPair (EVar x0) (EEpochSize (EFst (EVar x0))))), pastHorizonSummary = [EraSummary {eraStart = Bound {boundTime = RelativeTime 0s, boundSlot = SlotNo 0, boundEpoch = EpochNo 0}, eraEnd = EraEnd (Bound {boundTime = RelativeTime 20s, boundSlot = SlotNo 80, boundEpoch = EpochNo 1}), eraParams = EraParams {eraEpochSize = EpochSize 80, eraSlotLength = SlotLength 0.25s, eraSafeZone = StandardSafeZone 16 NoLowerBound}}]}
[35m[cardano-wallet.network:Notice:1590][0m [2020-09-25 09:21:58.45 UTC] Destroying cursor connection at ThreadId 1593
[34m[cardano-wallet.network:Info:1587][0m [2020-09-25 09:21:58.45 UTC] Query getAccountBalance took 0.015226809s
[31m[cardano-wallet.pools-engine:Error:1590][0m [2020-09-25 09:21:58.45 UTC] Chain follower exited with error. Worker will no longer monitor stake pools.
[35m[cardano-wallet.pools-engine:Notice:1590][0m [2020-09-25 09:21:58.45 UTC] Worker has exited: main action is over.
```

**Comment by Anviking** [comment]
Should be fixed. We can investigate closer if we something similar again.
