### ISSUE TITLE
cardano-wallet and cardano-address Shelley bech32 addresses are different

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#2197]
# Context
 
 

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | cardano-wallet: `2020.9.22 (git revision: a5f269ac7e1f12ad3b7a9bf760090f01872d950f)`, cardano-address: `2.1.0 @ e0ab4587266430a08734e1aec1c29d261a9a3b70ss version` |
| Platform     | Linux, all        |
| Installation | From source           |

# Steps to Reproduce

1. Restore wallet on testnet `tooth extend water monkey hub magnet uncover cherry shrug sheriff sugar unique memory nurse solve nature pepper phrase hour stick slight anchor earth cave`

2. Derive address with cardano-address

```
cat shelley_phrase.prv \
> | cardano-address key from-recovery-phrase Shelley \
> | cardano-address key child 1852H/1815H/0H/0/0 \
> | cardano-address key public \
> | cardano-address address payment --network-tag testnet
```

3. Check addresses in wallet.

## Expected behavior

Addresses should look the same.

## Actual behavior
 
cardano-wallet: `addr1qr5egevl9mmukz5ccwlnjl2tsftn0fa7d9gdt7ngpyfes9wkm9rcwh70fpz77wjlprw42gjcrnmdu7uuqefhnjanw4xs2xhds6`
cardano-addresses: `addr_test1vr5egevl9mmukz5ccwlnjl2tsftn0fa7d9gdt7ngpyfes9g434s4t`

**Note:** I was able to send funds to `addr_test1vr5egevl9mmukz5ccwlnjl2tsftn0fa7d9gdt7ngpyfes9g434s4t` and they were discovered on address `addr1qr5egevl9mmukz5ccwlnjl2tsftn0fa7d9gdt7ngpyfes9wkm9rcwh70fpz77wjlprw42gjcrnmdu7uuqefhnjanw4xs2xhds6` on the wallet.

**Note2:** Also on `mainnet` addresses look different. For the same mnemonics addresses on wallet are longer, e.g. first address:
 - `addr1q85egevl9mmukz5ccwlnjl2tsftn0fa7d9gdt7ngpyfes9wkm9rcwh70fpz77wjlprw42gjcrnmdu7uuqefhnjanw4xsms72z8`

Whereas derived via `cardano-address`:
```
cat shelley_phrase.prv \
> | cardano-address key from-recovery-phrase Shelley \
> | cardano-address key child 1852H/1815H/0H/0/0 \
> | cardano-address key public \
> | cardano-address address payment --network-tag mainnet
```
:point_down: 
```
addr1v85egevl9mmukz5ccwlnjl2tsftn0fa7d9gdt7ngpyfes9gwepv6w
```

---

# Resolution 

---

# QA

**Comment by rvl** [comment]
1. In `stack.yaml` we have cardano-address 2.0.0, so I have updated the version (#2198).
2. The addr_test bech32 hrp is not implemented in cardano-wallet yet afaik.
3. cardano-wallet addresses probably include the reward address, which accounts for the difference in length.

**Comment by KtorZ** [comment]
@piotr-iohk shall we close this one?

**Comment by piotr-iohk** [comment]
> The addr_test bech32 hrp is not implemented in cardano-wallet yet afaik.

It would be nice to have consisteny between cardano-address and cardano-wallet. Unless it is tracked elsewhere?

**Comment by KtorZ** [comment]
It is not, but I'd rather have that tracked indeed as a tech debt in JIRA instead of a bug ticket here ^.^

**Comment by piotr-iohk** [comment]
OK -> https://jira.iohk.io/browse/ADP-493.
