### ISSUE TITLE
Port and review the Address discovery (AddressPool + AddressPoolGap modules) from cardano-wallet

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#22]
# Context

Similarly to #21, we do want to port existing logic from `cardano-wallet-legacy` onto `cardano-wallet`, from the following modules:

- https://github.com/input-output-hk/cardano-wallet-legacy/blob/develop/src/Cardano/Wallet/Kernel/AddressPool.hs
- https://github.com/input-output-hk/cardano-wallet-legacy/blob/develop/src/Cardano/Wallet/Kernel/AddressPoolGap.hs
- https://github.com/input-output-hk/cardano-wallet-legacy/blob/develop/test/unit/Test/Spec/AddressPoolGap.hs
- https://github.com/input-output-hk/cardano-wallet-legacy/blob/develop/test/unit/Test/Spec/AddressPool.hs

Also, we did initially embed in `AddressPool` some logic to create new addresses. This could actually be removed in order to make the `AddressPool` a plain data-structure that can be easily serialized / deserialized (much more like done in: https://github.com/KtorZ/wallet-prototype/blob/master/app/Main.hs#L719-L730

We do not need any particular abstraction on _how_ addresses are derived at this stage and we can only consider AddressPool and AddressPoolGap in the context of sequential derivation with BIP-44.

# Decision

- We _must_ port modules described above to `cardano-wallet` and remove any dependency to `cardano-sl` 
- We _should_ merge `AddressPool` and `AddressPoolGap` into one module 
- We _should_ remove unnecessary abstraction over the address derivation (as described above)

---

# Development Plan

- I intend to import and merge together the `AddressPoolGap` and `AddressPool` modules from `cardano-wallet`, alongside with their testing code.
- I plan to align types with primitives and wrappers provided in `AddressDerivation` & `Cardano.Wallet.Primitive`
- I intend to make `AddressPool` a plain data-structure (as it is in the wallet prototype) to be more idiomatic haskell.

# PR

| Number   | Base      |
| ---      | ---       |
| #51       | `KtorZ/#21/ed25519-address-derivation`  |

# QA 

- The module define two main data-structure (cf [haddock]([here](https://input-output-hk.github.io/cardano-wallet/haddock/cardano-wallet-2.0.0/Cardano-Wallet-AddressDiscovery.html))
    - `AddressPoolGap`: to represent the number of consecutive undiscovered addresses
    - `AddressPool`: to keep track of a set of addresses for a given account and change chain

- Properties are define for both structures as follows:
    - [AddressPoolGap](https://github.com/input-output-hk/cardano-wallet/blob/KtorZ/%2321/ed25519-address-derivation/test/unit/Cardano/Wallet/AddressDiscoverySpec.hs#L72-L82)
    - [AddressPool](https://github.com/input-output-hk/cardano-wallet/blob/KtorZ/%2321/ed25519-address-derivation/test/unit/Cardano/Wallet/AddressDiscoverySpec.hs#L84-L92)
   The ones for `AddressPoolGap` are rather straightforward and just make sure that our wrapper type has the correct properties and define correct bounds. Not that, I've removed the `Num`, `Real` and `Integral` instances from the legacy code because this was just giving too much power to the wrapper, and wasn't really needed after all. An `Enum` instance is enough in most cases.

**Comment by piotr-iohk** [comment]
lgtm! :+1:
