### ISSUE TITLE
Flaky Network.Wai.Middleware.Logging, Logging Middleware, GET, 200, no query

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#2217]
# Context
 
 

https://github.com/input-output-hk/cardano-wallet/pull/2156#issuecomment-704040406

# Test Case

https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Network/Wai/Middleware/LoggingSpec.hs#L119-L128

# Failure / Counter-example

```
Failures:

  test/unit/Network/Wai/Middleware/LoggingSpec.hs:119:5:
  1) Network.Wai.Middleware.Logging, Logging Middleware, GET, 200, no query
       uncaught exception: HttpException
       HttpExceptionRequest Request {
         host                 = "localhost"
         port                 = 56698
         secure               = False
         requestHeaders       = []
         path                 = "/get"
         queryString          = ""
         method               = "GET"
         proxy                = Nothing
         rawBody              = False
         redirectCount        = 10
         responseTimeout      = ResponseTimeoutDefault
         requestVersion       = HTTP/1.1
       }
        ConnectionTimeout

  To rerun use: --match "/Network.Wai.Middleware.Logging/Logging Middleware/GET, 200, no query/"
```

---

# Resolution 

---

# QA

**Comment by rvl** [comment]
I saw this failure on a recent master commit 6194a931374d0376b2d24aa2dd8e99b470b46184.

https://hydra.iohk.io/jobset/Cardano/cardano-wallet#tabs-evaluations
https://hydra.iohk.io/job/Cardano/cardano-wallet/native.checks.cardano-wallet-core.unit.x86_64-darwin#tabs-status

Disabling the test is probably a reasonable thing to do for now.

I forgot @KtorZ, are we tracking flakies in github or jira?

**Comment by KtorZ** [comment]
Github @rvl, as per: https://input-output.atlassian.net/wiki/spaces/AD/pages/1824292925/Strategy+to+fix+flaky+CI+test+failures

**Comment by Anviking** [comment]
Seems fixed, closing
