### ISSUE TITLE
Testnet restoration benchmark times out

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#2221]
# Context
 
Recently restoration benchmark on testnet times out a lot:

https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/663 <--- Testnet timeout
https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/662 <--- Testnet timeout
https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/661 <--- Testnet timeout
https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/660 <--- Testnet timeout
https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/659 <--- Testnet timeout
https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/658 <--- Testnet timeout
https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/657 <--- Testnet timeout
https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/656 <--- Heap exhausted
https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/655 <--- Mainnet timeout
https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/654 :heavy_check_mark: 
https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/653 :heavy_check_mark: 
https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/652 :heavy_check_mark: 
https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/651 :heavy_check_mark: 
https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/650 :heavy_check_mark: 
https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/649 <--- Mainnet timeout
https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/648 :heavy_check_mark: 

# Test Case

# Failure / Counter-example

Looks like it times out consistently since https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/656  where this happened:
https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/656#c746be14-60f8-4baf-bf4c-63b0b7bf56a8

```
restore: StatementAlreadyFinalized "BEGIN"
--
  | [bench-restore:Notice:14] [2020-09-29 10:27:25.30 UTC] [cardano-node.21881] Terminating child process
  | restore: Heap exhausted;
  | restore: Current maximum heap size is 8589934592 bytes (8192 MB).
  | restore: Use `+RTS -M<size>' to increase it.
```

---

# Resolution 

---

# QA

**Comment by Anviking** [comment]
Old issue, fixed at some point.
