### ISSUE TITLE
Incorrect mainnet network parameters returned from API

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#2226]
### Jira tickets

ADP-483 - epoch length and slot length
ADP-554 - ActiveSlotCoeff parameter

### Context

Daedalus is showing this information about the current epoch for mainnet.
 
![screen_shot_2020-10-08_at_13 48 35](https://user-images.githubusercontent.com/1019641/95543662-8031e080-0a3c-11eb-94a2-cb5aeeb51b01.png)

Cardano-wallet hardcodes the genesis data, including protocol parameters for mainnet. The code was not updated once the shelley genesis data was finalised.

# Steps to Reproduce

1. Run `cardano-wallet serve --mainnet ...`
2. View the `/v2/network/parameters` API endpoint

## Expected behavior

- Epoch length is 432000 (slots).
- Active Slots Coeff is 5%

## Actual behavior
 
- Epoch length is 21600
- Active slots coeff is 100%

---

# Resolution 

### Attempt 1 - bad idea

Update genesis parameters in code, so that they match the shelley era genesis ([cardano deployments page](https://hydra.iohk.io/job/Cardano/iohk-nix/cardano-deployment/latest/download/1/index.html)) ⇒ #2227

### Attempt 2 

1. Stop using genesis data for parameters which aren't covered by protocol parameter updates, but can change.
2. Get epoch length (slots) and slot length (seconds) from HardFork History Interpreter ⇒ #2246.
3. Get _ActiveSlotCoeff_. This one is a bit tricky. We either need to load the shelley genesis (in addition to byron genesis), or find some way of querying the `Shelley.Spec.Ledger.BaseTypes.Globals` structure ⇒ There will be a ledger change to add querying of shelley genesis data.
 
### Can do this as well

In the network parameters endpoint, consider providing more information:
     - an expected number of blocks per epoch (epoch length × active slots coeff)
     - the current block height _within the epoch_.

### PRs

- #2227 - First atttempt
- #2236 - revert of incorrect fix
- #2246 - fix for epoch and slot length parameters.
- #2343 - test hardcoding of shelley mainnet ActiveSlotCoeff.

---

# QA 

1. I have done manual testing of `/network/parameters` and `/network/information` endpoints.
2. Automated testing - epoch length and slot length parameters added to SHELLEY_NETWORK integration test - `lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Network.hs`

**Comment by rvl** [comment]
@piotr-iohk Do you have any ideas for automated testing of this?

I am thinking of doing a "mainnet acceptance test".
It would work in a similar way to the nightly restore tests - i.e. starts a mainnet node, syncs, and runs `cardano-wallet serve --mainnet`.
Then it will assert that network parameters (or a subset of them) are equal to the golden mainnet network parameters.

**Comment by piotr-iohk** [comment]
@rvl so is this hardcoded for mainnet? 
As far as testing, I initially thought that maybe we could just make sure the "hardcoded" values are as expected, with no need to spinning up e2e for mainnet... but on the other hand "mainnet acceptance test" is very good idea. Perhaps we may add more checks there overtime in such suite.

I see that there is also the same problem for "testnet" or "shelley_qa"...

For **testnet** `/network/parameters` shows:

 - Epoch length is 21600
 - Active slots coeff is 100%

Whereas https://hydra.iohk.io/build/4372602/download/1/testnet-shelley-genesis.json shows:

```
 "epochLength": 432000,
 "activeSlotsCoeff": 0.05,
```

For **shelley_qa** `/network/parameters` shows:

 - Epoch length is 360
 - Active slots coeff is 100%

Whereas https://hydra.iohk.io/build/4372602/download/1/shelley_qa-shelley-genesis.json shows:

```
"epochLength": 7200,
"activeSlotsCoeff": 5.0e-2,
```

So, is it fixable for _testnets_? I suppose we'd need to provide `*-shelley-genesis.json` into `serve` to have it?

**Comment by rvl** [comment]
@piotr-iohk Yes we may need to provide a `serve --shelley-genesis` option so that the _ActiveSlotCoeff_ value is known. Only mainnet can be hardcoded.

I have had another look and actually the best way to get epoch length and slot duration is from the HardFork History Interpreter.

**Comment by KtorZ** [comment]
Tracked as: https://jira.iohk.io/browse/ADP-609
