### ISSUE TITLE
Differentiate change outputs from standard outputs in coin selection

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#2247]
# Context

In order to support hardware wallets, we need the API to provide the derivation paths of change output addresses within generated coin selections.

# Decision

Introduce a new `ApiCoinSelectionChange` type that includes a derivation path:

```hs
data ApiCoinSelectionChange (n :: NetworkDiscriminant) = ApiCoinSelectionChange
    { address :: !(ApiT Address, Proxy n)
    , amount :: !(Quantity "lovelace" Natural)
    , derivationPath :: NonEmpty (ApiT DerivationIndex)
    } deriving (Eq, Generic, Show)
```

Modify the `ApiCoinSelection` type so that ordinary outputs (**_without_** derivation paths) and change outputs (**_with_** derivation paths) are held in separate fields:

```patch

data ApiCoinSelection (n :: NetworkDiscriminant) = ApiCoinSelection
    { inputs :: !(NonEmpty (ApiCoinSelectionInput n))
-   , outputs :: !(NonEmpty (AddressAmount (ApiT Address, Proxy n)))
+   , outputs :: !(NonEmpty (ApiCoinSelectionOutput n))
+   , change :: ![ApiCoinSelectionChange n]
    } deriving (Eq, Generic, Show)

```

# Acceptance Criteria

* It **_must_** be possible to differentiate change outputs from ordinary outputs
* Each change output **_must_** specify the full derivation path of the output address

# Development 

https://github.com/input-output-hk/cardano-wallet/pull/2244

# QA 

Update the following integration tests:

- `BYRON_HW_WALLETS/HW_WALLETS_04`.
- `SHELLEY_HW_WALLETS/HW_WALLETS_04`.
- `WALLETS_COIN_SELECTION_02`.
- `WALLETS_COIN_SELECTION_01`.

See https://github.com/input-output-hk/cardano-wallet/pull/2244.

**Comment by piotr-iohk** [comment]
LGTM.

However I'd like to add some more tests for coin-selection. In particular verifying the change may be empty, for instance when trying to send 1 ADA having 2 UTXOs with 1 ADA each => Change will be empty due to minUTxOValue = 1 ADA, therefore leftovers < 1 ADA would be included as fee.

**Comment by piotr-iohk** [comment]
@jonathanknowles I have added additional cases in https://github.com/input-output-hk/cardano-wallet/pull/2275 (including some missing cases for Byron Icarus wallets).
