### ISSUE TITLE
Mainnet restore bench running out of disk space

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#2248]
# Context
 
 

https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/674#c1933993-5335-4d21-82c6-782cc64f5d92

# Test Case

mainnet restore bench

# Failure / Counter-example

In logs
```
ApiMisuse (ClosedDBError (Just (FsError {fsErrorType = FsDeviceFull, fsErrorPath = /tmp/cw-node-c0e02cc881daa38b/db/volatile/blocks-2607.dat, fsErrorString = "No space left on device", fsErrorNo = Just (Errno 28), fsErrorStack = CallStack (from HasCallStack):
```

---

# Resolution 

---

# QA

**Comment by rvl** [comment]
Interesting. That machine has 175G free on `/`.

From that error message, it says that the node data is being stored in `/tmp`. Has that changed recently?

`/tmp` is a ramfs on this buildkite container (it often is for many distros), so probably doesn't have much space.

So we need to change the storage path or set the `TMPDIR` environment variable to somewhere that's not a ramdisk.

**Comment by Anviking** [comment]
https://github.com/input-output-hk/cardano-wallet/blob/7b19a2f0f10dff07be66327108ed239214c7917a/.buildkite/bench-restore.sh#L17 @rvl shouldn't this have a `export` somehow?

It seems that the haskell bench sees the env var as unset.
https://github.com/input-output-hk/cardano-wallet/blob/7b19a2f0f10dff07be66327108ed239214c7917a/lib/core-integration/src/Cardano/Wallet/BenchShared.hs#L136-L140

But also, shouldn't the socket file and node dir exist in `/tmp`, but the db in `/cache`, since we previously had problems with the socket file not being cleaned up?

**Comment by Anviking** [comment]
(Tried this in https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/677#c008f406-d0da-44b1-a977-0df56e35c485 )

**Comment by Anviking** [comment]
Didn't seem to work (this should be the non-trivial failure: https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/678#e7e62ef1-e56d-4b47-a784-6272fd859680)

🤷‍♂️

**Comment by Anviking** [comment]
Old ticket, must have been solved some time.
