### ISSUE TITLE
Looking for documentation on how to restore byron wallet from private key

### ISSUE THREAD

**Issue by jbax** [cardano-foundation/cardano-wallet#2281]
The documented Byron wallet restore API provides an option to restore the wallet from a private key: `random (from xprv)`:

https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/postByronWallet

The parameters of the request body are defined as

**style** = "random"

**name** = string  [ 1 .. 255 ] characters

**encrypted_root_private_key**   A root private key, encrypted using a given passphrase. The underlying key should contain:  

 * A private key 
 * A chain code 
 * A public key

**passphrase_hash**  A hash of master passphrase. The hash should be an output of a Scrypt function with the following parameters: 

 * logN = 14 
 * r = 8
 * p = 1

Which tools and sequence of steps should be followed to correctly obtain valid values for the `encrypted_root_private_key` and `passphrase_hash` parameters listed above?

Thank you!

**Comment by KtorZ** [comment]
@jbax cardano-wallet does not support restoring any wallet from a private key at the moment. There's a backward-compatible constructor that can be used for random wallet, true, but we do not expect any client to produce such input. This is specifically to offer a migration path from the old [cardano-sl](https://github.com/input-output-hk/cardano-sl) implementation and users that have lost their recovery phrase but, still remember their encryption passphrase. New applications should not venture in these lands :sweat_smile: 

Restoring from a mere private key would be possible although it open up the gate to errors and tricky situation to debug in case clients do something wrong (and there's a lot of room for something to go wrong here unfortunately). I'll bring that topic back again on discussion with the team though.

**Comment by jbax** [comment]
Thanks for the input. May I suggest marking endpoints such as these as
deprecated or something?

That way people will know to not even try to mess with them lol.

**Comment by KtorZ** [comment]
I thought it was already the case. So will do indeed :+1:

**Comment by KtorZ** [comment]
see: https://github.com/input-output-hk/cardano-wallet/pull/2283
