### ISSUE TITLE
Flaky test - various DB properties causing timeout

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#2292]
# Context
 
 

Timeouts due to DB properties started occurring at the same time, and have been pretty frequent since. I now merged similar tickets all into this one.

https://github.com/input-output-hk/cardano-wallet/pull/2225#issuecomment-721630391

# Test Case

Several:

https://github.com/input-output-hk/cardano-wallet/blob/970bebbf10a0a984477e14f48033757f6726ce5b/lib/core/test/unit/Cardano/Wallet/DB/Properties.hs#L608-L636

https://github.com/input-output-hk/cardano-wallet/blob/970bebbf10a0a984477e14f48033757f6726ce5b/lib/core/test/unit/Cardano/Wallet/DB/Properties.hs#L824-L880

```haskell
-- | Trying to remove a same wallet twice should yield an error
prop_removeWalletTwice
    :: DBLayer IO s JormungandrKey
    -> ( PrimaryKey WalletId
       , Wallet s
       , WalletMetadata
       )
    -> Property
prop_removeWalletTwice db@DBLayer{..} (key@(PrimaryKey wid), cp, meta) =
    monadicIO (setup >> prop)
  where
    setup = liftIO $ do
        cleanDB db
        atomically $ unsafeRunExceptT $ initializeWallet key cp meta mempty pp
    prop = liftIO $ do
        let err = ErrNoSuchWallet wid
        atomically (runExceptT $ removeWallet key) `shouldReturn` Right ()
        atomically (runExceptT $ removeWallet key) `shouldReturn` Left err
```

# Failure / Counter-example

E.g. getting stuck on
```
Cardano.Wallet.DB.Sqlite.Types
  Values can be persisted and unpersisted successfully
    can persist and unpersist values of type 'SlotNo'
      +++ OK, passed 100 tests.
Cardano.Wallet.DB.Sqlite
  Sqlite
    Extra Properties about DB initialization
      createWallet . listWallets yields expected results
        +++ OK, passed 100 tests.
      creating same wallet twice yields an error
        +++ OK, passed 100 tests.
      removing 
```

---

# Resolution 

---

# QA

**Comment by Anviking** [comment]
I wondered if this could be related to the parallelisation in some intricate way (by integration tests taking up more resources in CI).

But it seems the first failures occurred 2020-11-04 10:52 (on 7f745e74f), whereas the parallel (in buildkite) PR was merged 18:09 
https://github.com/input-output-hk/cardano-wallet/commit/0bf98c9e65af84702139dacc5ed0165777ff59e7

**Comment by Anviking** [comment]
Some PRs which were merged right before (plus the source PR itself):
- #2225 (not the cause)
- #2284 (not the cause)
- #2291 (not the cause)
- #2285 (did touch DB code, but nothing related to this I think)
- #2282 (not the cause)
- #2258 (not the cause)
- #2283 (not the cause)
- #2167 (did touch DB code)

I don't really see how #2167 could explain a sharp increase in these timeouts, but it seems more likely then the other PRs.

**Comment by Anviking** [comment]
`stack test cardano-wallet-core --ta '--match "removing" --qc-max-success=30000'` passes locally. I also tried some other `--match` combined with `stress --cpu 18 --io 1000 --timeout 600`, but also passed.

` stack test cardano-wallet-core --ta '--match "can\'t put before wallet exists" --qc-max-size=2000 --qc-max-success=10000'` passed as well.

- It could be possible that the first failure, before #2191, was simply bad luck, and that #2191 made the bad luck much more likely

I think I did manage to get the generation to get completely stuck using `--qc-max-size=1000` somehow, maybe this is a lead?

**Comment by Anviking** [comment]
Interestingly, `within` didn't help. https://github.com/input-output-hk/cardano-wallet/pull/2307#issuecomment-724756977

**Comment by Anviking** [comment]
Another peculiar thing is that when we look at the buildkite master builds (https://buildkite.com/input-output-hk/cardano-wallet), there is only _one_ recent unit test failure. There are 13 master builds since 2020-11-04 10:52 (when we saw the first failure), but only 1 failure. I.e. a failure rate of ≈8%

The bors r+ failure rate caused by this issue has recently been something like 30%.

This was why I was curious about whether #2310 (removing parallelisation) would improve things.

**Comment by Anviking** [comment]
I ran the full `stack test cardano-wallet-core` like 3 times, and got stuck on
```
      Checkpoints are eventually stored in a sparse manner
        +++ OK, passed 100 tests; 499 discarded.
  Sqlite State machine tests
2549/100
```
where the number was ticking upward _very_ slowly. Not sure if it coincided with my computer going to sleep though.

Want to try re-running more.

**Comment by rvl** [comment]
I also found it got stuck on `Sqlite State machine tests` on the third try. I was running:
```
repeat 20 stack test cardano-wallet-core:test:unit --ta '--match "/Cardano.Wallet.DB.Sqlite/Sqlite"'
```

I am also trying to make it fail with:
```haskell
sqliteFindBug :: Spec
sqliteFindBug = describe "Repeat til failure, no shrinking" $ do
    it "Find bug" $ do
        r <- smashSeq
        print r
        r `shouldSatisfy` isSuccess

sqliteSeqProp :: IO Property
sqliteSeqProp =
    prop_sequential <$> (newMemoryDBLayer :: IO TestDBSeq)

smashSeq :: IO Result
smashSeq = sqliteSeqProp >>= smashIt (\i -> putStrLn $ "Test " ++ show i) . pure

smashIt :: Testable prop => (Int -> IO ()) -> IO prop -> IO Result
smashIt logIt getProp = run 0
  where
    run = fix $ \loop i -> do
      logIt i
      prop <- getProp
      r <- quickCheckResult (noShrinking prop)
      if isSuccess r
         then loop (i + 1)
          else pure r
```
But no luck yet.

**Comment by rvl** [comment]
I triggered it in ghci after 38 loops, but had forgotten to add noShrinking - OOM - doh!. I suspect it's a bad shrink function somewhere.

**Comment by KtorZ** [comment]
@rvl It's the same crazy shrinker as some weeks ago. Last time, I fixed the failing test but not the shrinker (couldn't find the culprit). So I guess we have a new test failure, but the same crazy shrinker.

**Comment by rvl** [comment]
It seems like it could be a generator. The following test slooowly crawls along until it runs out of memory. The test never fails, and shrinking is disabled anyway.

```
Cardano.Wallet.DB.Sqlite
  Repeat til failure, no shrinking
Test 0
+++ OK, passed 3200 tests:
54.84% UnsuccessfulReadTxHistory
54.81% CreateThenList
51.28% TxUnsortedOutputs
51.22% TxUnsortedInputs
51.12% SuccessfulReadCheckpoint
45.66% CreateWalletTwice
31.25% SuccessfulReadTxHistory
29.12% ReadTxHistoryAfterDelete
27.53% UnsuccessfulReadCheckpoint
25.78% PutCheckpointTwice
24.53% ReadMetaAfterPutCert
20.62% CreateThreeWallets
19.28% RolledBackOnce
13.81% RemovePendingTxTwice
13.16% SuccessfulReadPrivateKey
 8.34% RemoveWalletTwice
Test 1
(374 tests)

unit: Heap exhausted;
unit: Current maximum heap size is 2147483648 bytes (2048 MB).
unit: Use `+RTS -M<size>' to increase it.
```

**Comment by rvl** [comment]
Profiling the stuck test above shows that most time is spent in `instance Arbitrary GenTxHistory (arbitrary)` before it runs out of heap space.
I already disabled the obvious one (TxMetadata), but that is not the cause.

**Comment by Anviking** [comment]
Seems gone now.
