### ISSUE TITLE
[BUG] - autogenerated genesis file can't be parsed by cardano-wallet. Error parsing `activeSlotsCoeff`

### ISSUE THREAD

**Issue by jbax** [cardano-foundation/cardano-wallet#2296]
# Context

Using command `cardano-node shelley genesis create ...` the resulting `genesis.json` file comes out with the following:

```

{
    "activeSlotsCoeff": 5.0e-2,
    "protocolParams": {
        "poolDeposit": 0,
        "protocolVersion": {
            "minor": 0,
            "major": 0
        },
 ...
```

When running the `cardano-wallet` process against that genesis.json file, the following exception is raised:

```
[cardano-wallet.main:Error:4] [2020-11-05 04:16:01.54 UTC] Failed to parse genesis configuration. You may want to check the filepath given via --genesis and make sure it points to a valid JSON genesis file. Here's (perhaps) some helpful hint: GenesisDataParseError "(line 2, column 26):\nunexpected \".\"\nexpecting digit, white space, \",\" or \"}\""
```

It seems like the cardano-wallet is unable to parse this double value `5.0e-2` however the JSON is valid. 

**Expected behavior**
The cardano wallet should not raise any errors parsing the genesis.json file.

**System info :**
| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | 2020.10.13 (git revision: 77e04fc0f0c226f27ea2e293666bb8311ba0daa1)  |
| Platform     | Ubuntu Linux 20.02          |
| Installation | From Github Release            |

**Comment by rvl** [comment]
Hi @jbax, what are you trying to do here?

When running `cardano-wallet serve --testnet`, you need to provide the _Byron-era_ genesis json file for the testnet. Shelley genesis parameters are fetched from the chain.

The byron genesis file doesn't have activeSlotsCoeff, so it probably doesn't matter whether or not we can parse numbers in that format.

**Comment by jbax** [comment]
Yeah I noticed that few minutes ago. Sorry for wasting your time.

Is there any way to start the wallet without a Byron genesis file? I got a
cardano node running locally with shelley genesis only.

**Comment by KtorZ** [comment]
@jbax No. Not anymore.

**Comment by jbax** [comment]
thanks!

**Comment by vkconsult** [comment]
Ran into the same issue. The error message could be more specific in this came imo.
