### ISSUE TITLE
Sketch wallet layer to fetch and create a wallet

### ISSUE THREAD

**Issue by paweljakubas** [cardano-foundation/cardano-wallet#23]
# Context

As we are starting from scratch an want to add new lean wallet functionality there is a need to structure the code and layers properly. Following the path of previous `cardano-wallet` we are going to add kernel and API layers to decouple the concerns handle respective errors.   

# Decision

We are going to add wallet kernel layer that is going to be called from API layer, handle errors, manage persistence and inner workings logic 
- we should have separate layer where inner workings of create wallet reside

---

# Development Plan

- [x] I plan to add types/structure/stubs for the first review
- [x] I intend to fill the aforementioned with implementation and corresponding tests

# PR

| Number   | Base      |
| ---      | ---       |
| #62       | `master`  |
| #82        | `master`  |

# QA 

- We have defined a [`WalletLayer`](https://input-output-hk.github.io/cardano-wallet/haddock/cardano-wallet-2.0.0/Cardano-WalletLayer.html#t:WalletLayer) interface that connects the DBLayer and NetworkLayer together. 

- There are also a few corresponding property tests ensuring that the create and read functions from the layer works as expected (cf: [test/unit/Cardano/WalletLayerSpec.hs](https://github.com/input-output-hk/cardano-wallet/blob/5de62216646e36ca77a22f568b63ea5ca702976b/test/unit/Cardano/WalletLayerSpec.hs)). 

- More integration tests are coming along with #69

**Comment by KtorZ** [comment]
> add kernel and API layers

This isn't exactly true. So here, we are interested in our WalletLayer which sits between the API Layer, the Network Layer and the DB Layer. I'll provide a diagram on slack to make things a bit clearer. But this particular task is NOT about creating the API layer. 

What we need here is really just a few effectful functions that can compose the functions from:

- The wallet business logic (`Cardano.Wallet` -- which is the equivalent of our old Kernel here)
- The network layer
- The db layer (which doesn't exist so far so we'll have to sketch a small module api for that and emulate it with an `MVar`).

**Comment by KtorZ** [comment]
This now sounds like duplicated with #69. I'll close #69 in favor of this one, but move this one in the next milestone :+1:

**Comment by KtorZ** [comment]
Okay, re-reading the decisions, they aren't really the same. This one is about implementing the `create` and `get` part of the wallet layer, while #69 is really about the wallet worker which would apply block and maintain a wallet state. So, they are related and will share a state through the DB layer, but they aren't strictly the same.

**Comment by piotr-iohk** [comment]
@paweljakubas, @KtorZ - looking at https://github.com/input-output-hk/cardano-wallet/blob/master/src/Cardano/WalletLayer.hs#L71-L75

```haskell
data NewWallet = NewWallet
    { mnemonic
        :: !(Mnemonic 15)
    , mnemonic2ndFactor
        :: !(Passphrase "generation")
``` 
this does not to seem to be inline with API spec ->

```

mnemonic_sentence - Array of string <bip-0039-mnemonic-word{english}> [ 15 .. 24 ] items
mnemonic_2nd_factor - Array of string <bip-0039-mnemonic-word{english}> [ 9 .. 12 ] items
```

**Comment by KtorZ** [comment]
@piotr.stachyra indeed, and it doesn't have to be. This is the wallet layer to which the API layer talks to.
The representation of the second factor as a mnemonic sequence is really just a detail of the API.
Actually, we could say the same for the main mnemonic and have the wallet layer receives a seed directly.

**Comment by piotr-iohk** [comment]
lgtm :+1:
