### ISSUE TITLE
Incomplete pool list while trying to retrieve a list of pools using latest cardano-node master via cardano-wallet API

### ISSUE THREAD

**Issue by stakelovelace** [cardano-foundation/cardano-wallet#2333]
I downloaded latest master build of cardano-wallet for Mac and Linux (e.g. https://hydra.iohk.io/build/4676806), then compiled latest cardano-node (master branch) as of 3 Nov.

./cardano-wallet version
2020.10.13 (git revision: c9690481e35c9d8f422c80ea8bc0293a758eb6ac)

~/.cabal/bin/cardano-node version
cardano-node 1.22.1 - linux-x86_64 - ghc-8.6
git rev 964811d

Once cardano-node was started and in sync:

cardano-cli shelley query tip --mainnet
{
"blockNo": 4900702,
"headerHash": "6305240b33aff2452ca0d64ce74105b8b0875ef69139035852ef75efc6d3e4aa",
"slotNo": 12793240
}

and wallet was also in sync:
[cardano-wallet.pools-engine:Info:36] [2020-11-02 23:25:44.14 UTC] Applying blocks [12793253 ... 12793253]

I attempted to get a pool list via wallet API:

curl http://localhost:8090/v2/stake-pools?stake=100000000000

at which point I received the following response:

{"code":"past_horizon","message":"Tried to convert something that is past the horizon (due to uncertainty about the next hard fork). Wait for the node to finish syncing to the hard fork. Depending on the blockchain, this process can take an unknown amount of time."}

More detail is available at the pastebin location:

https://pastebin.pl/view/4ef66d1d

**Comment by piotr-iohk** [comment]
This is most likely because the cardano-node was still syncing through the Byron era at the time of attempting to list pools. In such case this message is expected. Please wait until cardano-node and cardano-wallet are fully synced and then list pools again.

You'll know that cardano-wallet is fully synced when:

```
curl http://localhost:8090/v2/network/information | jq .sync_progress.status

"ready"
```

Also, please note that latest (master) cardano-node may not always be compatible (yet) with the latest cardano-wallet (master). Please check the [compatibility matrix](https://github.com/input-output-hk/cardano-wallet#latest-releases).

**Comment by stakelovelace** [comment]
Thanks piotr - the cardano-node was definitely in sync with the mainnet, as evidenced by the cardano-cli shelley query tip and comparing with the main Shelley explorers. I will try out your network/information command as well as check the matrix - thanks.

**Comment by KtorZ** [comment]
see also: https://github.com/input-output-hk/cardano-node/issues/2067

This is probably because 1.22.1 is 'aware of' Mary and Allegra eras, that are after Shelley. So Shelley no longer is the last era of Cardano and the wallet is mistakenly interpreting errors from the time interpreter as being "past the horizon".

**Comment by KtorZ** [comment]
@stakelovelace stick to 1.21.1 until we're done with: https://github.com/input-output-hk/cardano-wallet/pull/2245

**Comment by stakelovelace** [comment]
Thanks for the heads up, will keep an eye on the referenced issue until that merge is complete.

**Comment by stakelovelace** [comment]
@KtorZ downloaded latest cardano-wallet buid from Hydra, ran it against 1.23 release node, for some reason 757 entries returned even though cardano-wallet standard output said "Fetched pool data from node tip using LSQ. Got 1343 pools in the stake distribution, and 1374 pools in the non-myopic member reward map.". Any ideas?

**Comment by KtorZ** [comment]
Note that the wallet is not integrated with 1.23, though I wouldn't expect any issue in that area. 

Was the stake pool background worker fully synced with the network (you can see this from the logs on the standard output)?

**Comment by stakelovelace** [comment]
curl http://localhost:8090/v2/network/information | jq .sync_progress.status
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   390    0   390    0     0  30000      0 --:--:-- --:--:-- --:--:-- 30000
"ready"


[cardano-wallet.pools-engine:Info:36] [2020-12-03 09:19:17.13 UTC] Applying blocks [15420866 ... 15420866]
[cardano-wallet.network:Info:14] [2020-12-03 09:19:17.13 UTC] Query getAccountBalance took 0.001747298s
[cardano-wallet.network:Info:14] [2020-12-03 09:19:17.13 UTC]   delegations = fromList []
  rewards = fromList []

[cardano-wallet.network:Info:21] [2020-12-03 09:19:17.14 UTC] Query GetEraStart took 0.013913633s
[cardano-wallet.network:Info:21] [2020-12-03 09:19:17.15 UTC] Query GetCurrentPParams took 0.001733702s
[cardano-wallet.network:Info:21] [2020-12-03 09:19:17.15 UTC] Query GetUpdateInterfaceState took 0.001297955s
[cardano-wallet.api-server:Info:67] [2020-12-03 09:19:29.20 UTC] [RequestId 2] [GET] /v2/stake-pools?stake=10000000000000
[cardano-wallet.network:Info:67] [2020-12-03 09:19:31.27 UTC] Query GetStakeDistribution took 2.061688317s
[cardano-wallet.network:Info:67] [2020-12-03 09:19:31.27 UTC] Will query non-myopic rewards using the stake 10000000000000
[cardano-wallet.network:Info:67] [2020-12-03 09:19:40.01 UTC] Query GetNonMyopicMemberRewards took 8.746500684s
[cardano-wallet.network:Info:67] [2020-12-03 09:19:40.02 UTC] Query GetCurrentPParams took 0.007781648s
[cardano-wallet.network:Info:67] [2020-12-03 09:19:40.02 UTC] Fetched pool data from node tip using LSQ. Got 1346 pools in the stake distribution, and 1377 pools in the non-myopic member reward map.
[cardano-wallet.api-server:Info:67] [2020-12-03 09:19:41.17 UTC] [RequestId 2] 200 OK in 11.970102557s

curl http://localhost:8090/v2/stake-pools?stake=10000000000000 > x.out
cat x.out | jq . | grep ticker | wc -l
778

**Comment by KtorZ** [comment]
Well, you're counting the number of pools that have metadata, not the total number of pools!

**Comment by stakelovelace** [comment]
Over 1200 pools that aren't retired have metadata, I am not sure I understand your point... my own pool (AAA) is not being included in the returned data and it clearly has metadata.

**Comment by stakelovelace** [comment]
So the issue seems to be specifically the metadata information is returned for a subset of pools, while the actual number of ids returned seemed okay. I've never used any SMASH-related urls when running wallet locally or when invoking the API call so not sure what's going on there (i.e. how I can end up with half of the pools with tickers and half without)

**Comment by KtorZ** [comment]
@stakelovelace many pools are serving metadata different from what they said to have registered. The wallet does check whether metadata registered on-chain matches the metadata served by pools servers. If the hash does not match, the metadata is considered invalid and is not stored.
