### ISSUE TITLE
nix-shell fails with error relating to XDG_DATA_DIRS

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#2334]
# Context

When running a build command with `nix-shell` within a freshly checked-out `cardano-wallet` repository on an Ubuntu 18.04.5 LTS machine, it fails with an error relating to `XDG_DATA_DIRS`.

# Environment
 
| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | `master` (b3d504ee81c7e196d17ee5b2f3a5b7398d9f06dc) |
| Platform     | Ubuntu 18.04.5 LTS x86-64 |
| Installation | Nix installed according to [these instructions](https://github.com/input-output-hk/cardano-node/blob/468f52e5a6a2f18a2a89218a849d702481819f0b/doc/getting-started/building-the-node-using-nix.md#building-under-nix) |

# Steps to Reproduce

1. Install a fresh Ubuntu 18.04.5 LTS instance. (This might also work with a later LTS, but haven't tested.)
2. Install `nix` and add the IOHK binary cache according to [these instructions](https://github.com/input-output-hk/cardano-node/blob/468f52e5a6a2f18a2a89218a849d702481819f0b/doc/getting-started/building-the-node-using-nix.md#building-under-nix)
3. Run any command with `nix-shell`.

## Expected behaviour

The command succeeds.

## Actual behaviour

The command produces an error relating to `XDG_DATA_DIRS`:
```
jsk@neon:~/projects/input-output-hk/cardano-wallet$ nix-shell --run .buildkite/check-stylish.sh --show-trace
trace: Using IOHK default nixpkgs
trace: gitSource.nix: /nix/store/dvp437wx7bmj4kfpvybifnj0aak27hmc-cardano-node-src does not seem to be a git repository,
assuming it is a clean checkout.
trace: Using index-state: 2020-07-15T00:00:00Z for cardano-node-src
trace: Using index-state: 2020-07-15T00:00:00Z for cardano-node-src
warning: dumping very large path (> 256 MiB); this may run out of memory
error: while evaluating the attribute 'XDG_DATA_DIRS' of the derivation 'cardano-wallet-shell' at /nix/store/p4a2vfvmvqghlh6pmibak5rsjhd8fd8w-haskell.nix-src/builder/shell-for.nix:122:5:
while evaluating anonymous function at /home/jsk/projects/input-output-hk/cardano-wallet/shell.nix:86:10, called from undefined position:
string '/nix/store/bnp1y85ikf7949lsd2ygslvlvcllbydi-cardano-node-exe-cardano-node-1.21.1/share/bash-completion' cannot refer to other paths, at /home/jsk/projects/input-output-hk/cardano-wallet/shell.nix:86:17
```

Contents of the `XDG_DATA_DIRS` variable:
```
$ echo $XDG_DATA_DIRS 
/usr/local/share:/usr/share:/var/lib/snapd/desktop
```

# Workaround

Comment out the following section from `shell.nix`:

```patch
     CARDANO_NODE_CONFIGS = walletPackages.cardano-node.deployments;

-    # If any build input has bash completions, add it to the search                                                                                                                  
-    # path for shell completions.                                                                                                                                                    
-    XDG_DATA_DIRS = concatStringsSep ":" (                                                                                                                                           
-      [(builtins.getEnv "XDG_DATA_DIRS")] ++                                                                                                                                         
-      (filter                                                                                                                                                                        
-        (share: builtins.pathExists (share + "/bash-completion"))                                                                                                                    
-        (map (p: p + "/share") buildInputs))                                                                                                                                         
-    );                                                                                                                                                                               
-                                                                                                                                                                                     
     meta.platforms = platforms.unix;
```

# Resolution 

# QA

**Comment by rvl** [comment]
Hi @jonathanknowles - what OS are you using and what nix version?
I tested it with Ubuntu 20.04.1 and Nix 2.3.8 and did not get any errors.

**Comment by jonathanknowles** [comment]
> Hi @jonathanknowles - what OS are you using and what nix version?
> I tested it with Ubuntu 20.04.1 and Nix 2.3.8 and did not get any errors.

Hi @rvl 

I originally wrote this in the description:

> Ubuntu 18.04.5 LTS

Perhaps it's worth upgrading the instance to 20.04.0.1 LTS.

**Comment by jonathanknowles** [comment]
As for the `nix` version:
> $ nix --version
> nix (Nix) 2.2.1

I'm attempting to upgrade it right now.

**Comment by jonathanknowles** [comment]
Upgraded to nix version 2.3.8, and the problem goes away.

Thanks @rvl for looking at this.
