### ISSUE TITLE
Flaky test: Network.Wai.Middleware.Logging, Logging Middleware, different request ids

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#2368]
# Context
 
This failure was seen in the following overnight test runs of the entire `cardano-wallet-core:test:unit` test suite:

| Test<br>Date<br> | Wallet<br>Version<br> | Run<br>Count<br> | Failure<br>Count<br> | Failure<br> Rate<br> |
| -- | -- | --: | --: | --: | 
| 2020-12-04 | ec22c1ba | 48 | 1 | 2% |

# Test Case

`Network.Wai.Middleware.Logging, Logging Middleware, different request ids`

# Failure / Counter-example

```
test/unit/Network/Wai/Middleware/LoggingSpec.hs:225:13: 
1) Network.Wai.Middleware.Logging, Logging Middleware, different request ids
     Falsifiable (after 81 tests and 8 shrinks):
       NumberOfRequests 1
     expected: 1
      but got: 188

To rerun use: --match "/Network.Wai.Middleware.Logging/Logging Middleware/different request ids/"

Randomized with seed 1576720526
```

# Resolution 

---

# QA

**Comment by Anviking** [comment]
Seen again https://github.com/input-output-hk/cardano-wallet/pull/2506#issuecomment-776931203

**Comment by Anviking** [comment]
Test removed in  #2734
