### ISSUE TITLE
Address format in Shelley era (grouped address)

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#239]
# Context

See #217. In this ticket, we're interested in the _grouped address_, containing a staking key.

# Decision

- Finalize the implementation for the address format, and support the grouped address

# Acceptance Criteria

1. We _must_ support creating _grouped addresses_ from a public address key and a public staking key using the new format

---

# Development Plan

- [x] Actually got tackled as part of #217 (in #336)

# PR

| Number   | Base      |
| ---      | ---       |
| #336        | `master`  |

# QA 

- Grouped addresses implemented and tested as part of #217. See https://github.com/input-output-hk/cardano-wallet/issues/217#issue-440641226

**Comment by piotr-iohk** [comment]
:+1:
