### ISSUE TITLE
Flaky test: Validate generators & shrinkers, Shrinker for CreateWallet

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#2393]
# Context
 

`Validate generators & shrinkers` was added recently in #2354, to catch problems with our shrinkers and generators. Seems the CreateWallet one is now failing.

https://github.com/input-output-hk/cardano-wallet/pull/2357#issuecomment-740124434
https://github.com/input-output-hk/cardano-wallet/pull/2382#issuecomment-742453481

Perhaps this could be the underlying cause for #2394 too.

# Test Case

https://github.com/input-output-hk/cardano-wallet/blob/60aee7da3932a4451f32b0897a27f1dbc31997fe/lib/core/test/unit/Cardano/Wallet/DB/StateMachine.hs#L1281-L1313

# Failure / Counter-example

```
Build failed:

ci/hydra-build:required

 test/unit/Cardano/Wallet/DB/StateMachine.hs:1298:28:
 1) Cardano.Wallet.DB.Sqlite, Validate generators & shrinkers, Shrinker for CreateWallet
 Timed out.

 To rerun use: --match "/Cardano.Wallet.DB.Sqlite/Validate generators & shrinkers/Shrinker for CreateWallet/"

Randomized with seed 809167721
```

---

# Resolution 

---

# QA

**Comment by KtorZ** [comment]
Fixed in #2471
