### ISSUE TITLE
Jörmungandr in CI

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#242]
# Context

In order to start experimenting with Jörmungandr API, we'll need to set it up in the CI and make it available, in a very similar fashion the cardano-http-bridge is available.

Being a full node (and not a proxy like the bridge), Jörmungandr requires some extra configuration and details in order to be set up. A full documentation is available on the repository, and hosted [here](https://input-output-hk.github.io/jormungandr/)

# Decision

- Enable Jörmungandr in CI
- In order to do that, it might be required to split the compilation job in two jobs (as we're tight to 50 minutes builds with Travis)

# Acceptance Criteria

1. Jörmungandr _must_ be available in CI
2. Jörmungandr _must_ be easy to start from upcoming integration tests

---

# Development Plan

- [x] Try building it directly in ci 

# PR

- #284 
- #287 
- #297

# QA 

- `jormungandr` is available in CI
- Some configuration is stored in the repo, and we test that we can launch `jormungandr` here: https://github.com/input-output-hk/cardano-wallet/blob/fb2110589405fd4431fe488b563679c8f404723a/lib/jormungandr/test/integration/Cardano/LauncherSpec.hs#L21-L26
- There are no integration tests yet so we don't know how well it actually works (with current config etc) aside from that it launches, but that will be required in #219 so better handle it then.

**Comment by piotr-iohk** [comment]
:+1:
