### ISSUE TITLE
Flaky: ProcessHasExited "cluster didn't start correctly

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#2427]
# Context
 
 

https://hydra.iohk.io/build/5275648

# Test Case

N/A - error during local test cluster setup before tests.

# Failure / Counter-example

```
       ProcessHasExited "cluster didn't start correctly: 
           [ Left user error (Waited too long for: pool registration)
           , Left user error (Waited too long for: pool registration)
           , Left user error (Waited too long for: pool registration)
           , Left user error (Waited too long for: pool registration)
           ]" (ExitFailure 1)
```

**Comment by rvl** [comment]
It looks as if the pool nodes were running and the `cardano-cli transaction submit` commands succeeded.
But either the registrations didn't work, or checking for stake distribution didn't work.
It's impossible to know without Info level logging. 

I double checked the minor exception handling fix that I recently made to `withCluster`. The changes just ensured that when exiting, the cluster nodes are given a chance to clean up beforehand. Other than that, the only problem seems to be that the `link` calls were never needed.

**Comment by rvl** [comment]
I was repeating a test case locally and found this error on the 68th run.
The log message was:
```
[cardano-wallet.integration:Info:383] [2021-01-07 12:42:47.77 UTC] Query of stake-distribution failed with status 1:
  Shelley command failed: query stake-distribution  Error: A query from a certain era was applied to a ledger from a different era: EraMismatch {ledgerEraName = "Allegra", otherEraName = "Shelley"}
```
So a timing issue.

We will be using InstaFork™ technology once #2400 is merged, so I think it's safe to not bother fixing this.
