### ISSUE TITLE
OpenAPI transaction metadata docs don't warn about PII

### ISSUE THREAD

**Issue by mikestead** [cardano-foundation/cardano-wallet#2433]
# Context

If a developer submits personally identifiable information (PII) to the blockchain there's no way to reverse it and the repercussions could be significant.

## Essential Information

The OpenAPI docs around [transaction creation](https://github.com/input-output-hk/cardano-wallet/blob/master/specifications/api/swagger.yaml#L798), while thorough, don't warn about submitting PII metadata to the blockchain.

I'm wondering if this is something worth adding given the potential impact? Perhaps there are other docs around transaction metadata where this should reside too?

**Comment by rvl** [comment]
Thanks for the suggestion @mikestead. I think we should note the PII issue in the OpenAPI docs. 

ADP-646

**Comment by piotr-iohk** [comment]
Addressed in #2437.

**Comment by mikestead** [comment]
Great thanks for actioning that so quickly
