### ISSUE TITLE
Missing address and amount fields from Tx Inputs

### ISSUE THREAD

**Issue by PegasusPool** [cardano-foundation/cardano-wallet#2434]
# Context

## Essential Information

 - **Version**:      2020.12.21 (git revision: 62df413064605323d59ef1816cb223b13b9ce386)
 - **Platform**:     Ubuntu 20.04
 - **Installation**: Binary from GitHub release page
 - **Network**:      mainnet

```
cardano-wallet transaction list --port PORT WALLET_ID
[
    {
        "inserted_at": {
            "height": {
                "quantity": 5186895,
                "unit": "block"
            },
            "time": "2021-01-09T12:31:06Z",
            "epoch_number": 240,
            "absolute_slot_number": 18629175,
            "slot_number": 312375
        },
        "status": "in_ledger",
        "withdrawals": [],
        "amount": {
            "quantity": 9000000,
            "unit": "lovelace"
        },
        "inputs": [
            {
                "id": "3321d12fd7d7d47b0d32fbdeae4f5a06f5ef563519e77f1dafb996c10537248d",
                "index": 0
            }
        ],
        "direction": "incoming",
        "outputs": [
            {
                "amount": {
                    "quantity": 9000000,
                    "unit": "lovelace"
                },
                "address": "addr1qyhce4688xm050mlqd29x2cq8rqar8jq7wpyxr4aytgdneudf4u6pngyfpszcjk83r5c3mxc99urmg0ew4dac2eee4kq0qn3lj"
            },
            {
                "amount": {
                    "quantity": 43113699,
                    "unit": "lovelace"
                },
                "address": "addr1qx744khz98tjgpvue5jnl36xhknzac0je4egjwgdyffu5dxz6dlxpqhca3freqtejk23yvmn4xcmayjvhd6h2lq388sqrylrqm"
            }
        ],
        "metadata": null,
        "depth": {
            "quantity": 1,
            "unit": "block"
        },
        "id": "9171d8078c10d7d6527debe64d738d97f63caf976aa04e07e7b050ec514c35fb"
    },
  }
]
```

# Steps to Reproduce

1. Generate a 24 words passpharse using cardano-wallet
2. Create a wallet using the generated passphrase
3. Send some ADA from yoroi chrome extension to the newly created wallet
4. Inspect the incoming transaction using `cardano-wallet transaction list --port PORT WALLET_ID`

## Expected behavior

Although the [cardano-wallet API documentation](https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/getTransaction) only marks the `id` and `index` fields as required in the `inputs` array, I would expect the `address` and `amount` information to be populated as well. In fact I've seen others test this and these two fields were populated.

## Actual behavior

`address` and `amount` fields are null in the `inputs` array.

When are the fields `address` and `amount` populated in the transaction inputs? If this is not a reliable way to tell the address from which transactions are sent then what is the way to do this using cardano-wallet?

**Comment by KtorZ** [comment]
Nope, this behavior is correct. We can only populate these fields for **outgoing** transactions (and in some rare cases, for some incoming). The reason being that in order to lookup which address and amount correspond to any arbitrary input, one needs an access to the entire ledger. However, the wallet does not maintain a complete ledger but only a subset narrowed down to the assets belonging to the wallet. (which also explains why inputs on outgoing transactions can be identified, they are fully known).

**Comment by KtorZ** [comment]
I thought the API documentation was already making this clear though.. We might want to revise this a bit.

**Comment by PegasusPool** [comment]
Thank you for the clarification. I thought something like this is the case.
I'm wondering though how it's possible for Daedalus and Yoroi wallets to show the sender on an incoming transaction. What do you suggest for my usecase? Using cardano-db-sync instead to listen blocks with transactions where my address is an output and that way I can tell the input address?

**Comment by KtorZ** [comment]
I'd suggest using an explorer api like cardano-graphql where you can easily lookup this information. A local one or an instance already deployed (though I don't think there are any publicly available instance of cardano-graphql. At least Input Output does not provide one, yet).

**Comment by KtorZ** [comment]
```graphql
{ 
  transactions (where: { hash: { _eq: "<the tx id>" } }) {
    outputs (where: { index: { _eq: "<the tx index>" } }) {
      address, 
      amount 
    }
  } 
} 
```
À query like this should give you what you're looking for.

**Comment by PegasusPool** [comment]
Thank you @KtorZ
