### ISSUE TITLE
Cardano.Wallet.DB.Sqlite.TypesSpec/Coverage checks for generators/TokenQuantity times out

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#2436]
# Context
 
The test-suite `cardano-wallet-core:test:unit` is failing in CI

# Test Case

The tests seem to get stuck at `Cardano.Wallet.DB.Sqlite.TypesSpec - Coverage checks for generators / TokenQuantity`.

# Failure / Counter-example

```
Cardano.Wallet.DB.Sqlite.Types
  Values can be persisted and unpersisted successfully
    can persist and unpersist values of type 'SlotNo'
      +++ OK, passed 100 tests.
building of '/nix/store/gi69gpdzca1ddnp66fkgg9rlxf9q5hrd-cardano-wallet-core-test-unit-2020.12.21-check' timed out after 900 seconds of silence
```

https://hydra.iohk.io/build/5300927

---

# Resolution 

---

# QA

**Comment by jonathanknowles** [comment]
Hi @rvl 

Thanks for reporting this.

I haven't been able to reproduce this locally just yet, even after running the relevant section of the test suite **1000** times:

```hs
time stack build --ghc-options "-j +RTS -A256m -n4m -RTS" --fast --test cardano-wallet-core:test:unit --test-arguments '--match "Cardano.Wallet.DB.Sqlite.Types"
```
As for the `TokenQuantity` coverage check, the lower coverage bounds are actually rather conservative, being set at `2%`:

```hs
prop_checkTokenQuantityCoverage :: TokenQuantity -> Property
prop_checkTokenQuantityCoverage q = checkCoverage
    $ cover 2 (TokenQuantity.isZero q)
        "token quantity is zero"
    $ cover 2 isSmall
        "token quantity is small"
    $ cover 2 isLarge
        "token quantity is large"
    $ cover 2 isMassive
        "token quantity is massive"
    True
  where
    isSmall   = TokenQuantity    0 < q && q <= tokenQuantitySmall
    isLarge   = tokenQuantitySmall < q && q <= tokenQuantityLarge
    isMassive = tokenQuantityLarge < q && q <= tokenQuantityMassive
```

Indeed, when we run the test, we see a much higher coverage:
```
  Coverage checks for generators
    TokenQuantity
      +++ OK, passed 100 tests:
      38% token quantity is large
      26% token quantity is massive
      21% token quantity is zero
      15% token quantity is small
```

I'll do some more testing, to see if I can uncover anything.

**Comment by jonathanknowles** [comment]
@rvl Perhaps the faulty test is elsewhere?

Looking at the log of a _successful_ run, we see that the `SlotNo` roundtrip persistence test is:
- immediately followed by the `NominalDiffTime`/`POSIXTime` roundtrip persistence test;
- shortly afterward, followed by the `Cardano.Wallet.DB.Sqlite / Validate generators & shrinkers` test section.

I'll soak test the `Cardano.Wallet.DB.Sqlite/Validate generators & shrinkers` test suite, to see if it gets stuck.

**Comment by jonathanknowles** [comment]
> I'll soak test the `Cardano.Wallet.DB.Sqlite/Validate generators & shrinkers` test suite, to see if it gets stuck.

I ran this section of the test suite 1000 times locally, and didn't see any failures yet.

**Comment by rvl** [comment]
Perhaps. The source of the loop will be one of the test cases after the last one shown to have passed.
It may not be the ones immediately after, but they are:
```
Cardano.Wallet.DB.Sqlite.Types
  Values can be persisted and unpersisted successfully
    can persist and unpersist values of type 'SlotNo'
    can persist and unpersist values of type 'NominalDiffTime'
    can persist and unpersist values of type 'TokenQuantity'
  Coverage checks for generators
    TokenQuantity
Cardano.Wallet.DB.Sqlite
  Validate generators & shrinkers
   ...
```

**Comment by jonathanknowles** [comment]
> Perhaps. The source of the loop will be one of the test cases after the last one shown to have passed.

@rvl Do you know whether buffering is used when writing to the test log on CI? If so, perhaps we can disable it?

Perhaps this would help with narrowing down the source of the failure, if we see it again.

As for the section mentioned:

> ```
> Cardano.Wallet.DB.Sqlite.Types
>   Values can be persisted and unpersisted successfully
>     can persist and unpersist values of type 'SlotNo'
>     can persist and unpersist values of type 'NominalDiffTime'
>     can persist and unpersist values of type 'TokenQuantity'
>   Coverage checks for generators
>     TokenQuantity
> Cardano.Wallet.DB.Sqlite
>   Validate generators & shrinkers
> ```

I've run this entire section 1000 times locally, but without seeing a single failure (so far).

Perhaps it's sporadic enough that we can de-prioritize it for now, until such time as we see it again on CI.

**Comment by rvl** [comment]
> Do you know whether buffering is used when writing to the test log on CI? If so, perhaps we can disable it?

Fair chance it's defaulted to block buffering, if Haskell thinks that it's outputting to a file.

Here is what I did for the integration tests: https://github.com/input-output-hk/cardano-wallet/blob/a2e8c7b342453695c788437ab8d0a2984dbfb8a9/lib/shelley/test/integration/Main.hs#L205-L207

Same could be done for unit tests.

**Comment by rvl** [comment]
It's possible that this is a re-occurrence of a previous issue - #2394 - but currently the cause is unknown.

**Comment by Anviking** [comment]
Stale. Closing
