### ISSUE TITLE
(ADP-644) Withdraw rewards from hardware wallet reward account

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#2440]
# Context

(public exposure of ADP-644)

##### Story

- As a hardware wallet user
- I want to withdraw my rewards from my rewards accounts 
- So that I can spend my rewards

##### Acceptance Criteria

- Given I have a hardware wallet
- And I have accumulated rewards
- And I have it connected to Daedalus
- Then I can create a transaction, withdrawing my reward from my reward account
- To some payment address

##### Additional Information / Description

In the API, we have the option to provide an extra "withdrawal" parameters when constructing payments. The result allows user to selectively include rewards (if eligible) as part of the transaction. This query parameter does not however exists for the /coin-selections API which is used by hardware wallets. There's therefore no way to include rewards in transactions constructed from hardware devices.

More context here: https://github.com/input-output-hk/daedalus/issues/2274

**Comment by mbrosparky100** [comment]
Bump.

hi guys is this scheduled to be fixed? I can’t withdraw 000s of my rewards on my Nano Ledger X because of this issue

**Comment by seaplanedude** [comment]
I would also like to know about the progress of this fix. I set up a hardware wallet and would like to send the rewards from my previous wallet but I am unable to send from a wallet only containing rewards.

**Comment by KtorZ** [comment]
This is now being addressed by #2528
