### ISSUE TITLE
xpub and phrase restoration have different addresses

### ISSUE THREAD

**Issue by Fell-x27** [cardano-foundation/cardano-wallet#2453]
# Context
 
I just use cardano-wallet to check if I do my own research by the right way.

# Test Case

There is a mnemonic(24): "produce fresh flock very unfold shine moon connect priority path nice galaxy oven stomach script session protect oak inch shiver square tool riot meadow"

It's expub is(hex): "b722fa14be04b0ad476d44a97cae8d1879872af01a01e98abb53732587c27cdcdeab4517d3b8c03ee59ccb2547b3e8836b351e9fd502d91a90d64a96b34e9881"

Test 1: Both restoration ways, xpub and phrase should yeld the same wallet id. PASSED.
Test 2: Both restoration ways, xpub and phrase should yeld the same wallet address set. FAILED.

Is it ok, or there is a cardano-wallet's bug?

Ok, it was wrong using, so I derived an ACCOUNT xpub(hex):"2d06f9aefe16f719f45d77109a93037dd042643e4b069aa99789218b3aa2201c6b1b29e1a0f062d2e225f7aa4035c099dddfcece0e44e230723629f8ee66ff79"

Test 1: Both restoration ways, xpub and phrase should yeld the same wallet id. FAILED.
Test 2: Both restoration ways, xpub and phrase should yeld the same wallet address set. PASSED.

Looks like cardano-wallet uses root_xpub to calculate walletid, so we can restore the same wallet..twice?

**Comment by rvl** [comment]
Hi @Fell-x27, The most likely explanation is that your program is using a different key derivation path to cardano-wallet. What derivation paths are you using for the account and addresses?

**Comment by Fell-x27** [comment]
> Hi @Fell-x27, The most likely explanation is that your program is using a different key derivation path to cardano-wallet. What derivation paths are you using for the account and addresses?

Hi! It's not about my apps and algos. It's about cardano-wallet behaviour only.
It allows to restore the same wallet twice. It uses the root_xpub to calculate walletId instead of account_xpub. Heritage of "random-wallets-obly" time?

**Comment by KtorZ** [comment]
I am not sure I fully understand the above but, some clarifications:

The `walletId` used in the API is generated from the wallet's root public key. If restoring from an account public key, the account public key is used instead. So far, wallets are only ever using the first HD account available thus indeed, at this stage it is possible to restore the same _account_ from two different means and have them co-exist in the server.

**Comment by Fell-x27** [comment]
Yep. But, probably, would be better if cardano-wallet used account_xpub for sequential wallets to prevent duplicating? It derives and stores it separately already, so why not?

**Comment by KtorZ** [comment]
>  It derives and stores it separately already, so why not?

Because wallets aren't not accounts. We are working on enabling multiple accounts within wallets, and using an identifier that is not linked to a particular account makes more sense.

**Comment by Fell-x27** [comment]
I see. Correct me if I wrong, but, technically, it's already possible to use multi-acc wallet if we derive it manually? Not with cardano-wallet yet, but in theory.

I mean H1852/H1815/H(0...N), where N - is wished account number. And then use this key to derive addresses.

**Comment by rvl** [comment]
Yes, that's correct @Fell-x27.
