### ISSUE TITLE
Unable to create address

### ISSUE THREAD

**Issue by PegasusPool** [cardano-foundation/cardano-wallet#2454]
# Context

This is not so much a bug report, but rather a question about how to create a new address for a wallet using the CLI.

<b>Edit:</b>
I also looked at [Construct address](https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/postAnyAddress) using the API but I could not manage to generate an address as I can't get the payload right. It's not clear to be what should be the exact payload if one would like to construct a normal payment address.

## Essential Information

 - **Version**:      2020.12.21 (git revision: 62df413064605323d59ef1816cb223b13b9ce386)
 - **Platform**:     Ubuntu
 - **Installation**: Binary from GitHub release page
 - **Network**:      mainnet

# Steps to Reproduce

- Create an wallet with passphrase using cardano-wallet CLI
- Create address

# Logs

```
cardano-wallet address create --port {PORT} {WALLET_ID}
Please enter your passphrase: **********
cardano-wallet: user error (feature unavailable.)
```

## Expected behavior

Address is created

## Actual behavior

Feature is not implemented

**Comment by PegasusPool** [comment]
Eventually I managed to generate a new address using the API.

I'm just going to leave this here for the record:
I have a previously generated 24 words phrase in the file called `phrase`

```
cat phrase | cardano-wallet key from-recovery-phrase Shelley > root.prv
```

```
cat root.prv \
    | cardano-wallet key child 1852H/1815H/0H \
    | tee acct.prv \
    | cardano-wallet key public --without-chain-code > acct.pub

```

```
cat acct.pub | bech32 addr_vk
```

Final output of the above is `addr_vk1d30aphw9vaac5fmndgdz6azxt4pzga59wxnd85rftexxzcr6nxwqw5qk9w`

Then I `POST`-ed the following on my running cardano-wallet API:

Endpoint: `http://localhost:3102/v2/addresses`
Payload: 
```
{
	"payment": "addr_vk1d30aphw9vaac5fmndgdz6azxt4pzga59wxnd85rftexxzcr6nxwqw5qk9w"
}
```

Response:
```
{
    "address": "addr1vydt4tz2k56qkwxkc6stf64vfwgtuddr5a3jvycjm4ntjgsw3sky9"
}
```


I'd be still interested in when this will be available via the CLI? A single command to generate a new address would be more convenient.

**Comment by PegasusPool** [comment]
Interestingly, I sent 2 ADA to the generated address, which is shown [here](https://explorer.cardano.org/en/address?address=addr1vydt4tz2k56qkwxkc6stf64vfwgtuddr5a3jvycjm4ntjgsw3sky9)

However when I get the wallet summary using `cardano-wallet wallet get --port 3102 WALLET_ID` the balance of the wallet is still 0. I'm very curious to know what I'm missing here. I thought this generated address belongs to the wallet (the keys were generated from the same 24 words phrase).

```
...
"state": {
    "status": "ready"
},
"balance": {
    "reward": {
        "quantity": 0,
        "unit": "lovelace"
    },
    "total": {
        "quantity": 0,
        "unit": "lovelace"
    },
    "available": {
        "quantity": 0,
        "unit": "lovelace"
    }
},
...
```

**Comment by rvl** [comment]
Hi @PegasusPool - once you have the account 0 extended public key, use it to derive address keys.
cardano-wallet searches at the _address level_ of account 0 for funds. So:
1. Use `cardano-address key public --with-chain-code` to get the extended public key.
2. Derive the key for address 0 with:
    ```
   cat acct.pub | cardano-address key child 0/0 > addr0.pub
   ```
   (edited to fix mistake)
3. Use the `cardano-address` program to make an address from the key.
   ```
   cat addr0.pub | cardano-address address payment --network-tag mainnet
   ```

**Comment by PegasusPool** [comment]
Thank you for your rely @rvl .
I tried following your instructions but did not succeed.

1. I reused `root.prv` from above
2. I recreated `acct.pub` with
```
cat root.prv \
     | cardano-wallet key child 1852H/1815H/0H \
     | tee acct.prv \
     | cardano-wallet key public --with-chain-code > acct.pub
```
3. `cat acct.pub | cardano-address key child 0/0` gives me `addr_xvk1r0440sa...`
4. when I pipe the above into `cardano-address key public --with-chain-code` I get this error:
```
user error (Invalid human-readable prefix. Prefix ought to be one of: ["root_xsk","acct_xsk","addr_xsk","stake_xsk","script_xsk"])
```

Did I make a mistake somewhere?

**Comment by rvl** [comment]
Sorry I made a mistake in the message above. The second `cardano-address key public --with-chain-code` pipeline step is not necessary. The address key is already a public key (`addr_xvk` prefix) because it was derived from a public account key.

```
cat root.prv | cardano-wallet key child 1852H/1815H/0H | cardano-wallet key public --with-chain-code | cardano-address key child 0/0 | cardano-address address payment --network-tag mainnet
```

**Comment by PegasusPool** [comment]
That worked @rvl 
Thanks for your help here.

Now the question is how I can send my 2 ADA back to the original address. I cannot do that with cardano-wallet, but I think somehow it should be possible.
I have the files `acct.prv  acct.pub` that were created in the first run before I sent the 2 ADA

**Comment by rvl** [comment]
Yes it should be possible to spend the 2 Ada from the original address, but you'll need to build the transaction manually.

Here are the instructions for doing that using `cardano-cli`: https://docs.cardano.org/projects/cardano-node/en/latest/reference/building-and-signing-tx.html

**Comment by KtorZ** [comment]
@PegasusPool note that we only let users create addresses for random wallets. It is so-to-speak forbidden for sequential wallets because there are rules and pre-conditions which need to be satisfied before creating a new sequential address. This is why the wallet manages that internally and instead, gives you a way to list your unused / available addresses that are safe to use. 

If you derive sequential addresses using an arbitrary index, your funds may not show up in your wallet because the software will fail to discover them. See also: https://input-output-hk.github.io/adrestia/docs/key-concepts/hierarchical-deterministic-wallets/#account-discovery

**Comment by PegasusPool** [comment]
Thank you both. Your help is much appreciated. I'll close this issue for now
