### ISSUE TITLE
produced_blocks is stuck

### ISSUE THREAD

**Issue by PegasusPool** [cardano-foundation/cardano-wallet#2463]
# Context

This behaviour has been observed many times sometimes for days and the only fix is to restart cardano-wallet.

## Essential Information

 - **Version**:      2020.12.21 (git revision: 62df413064605323d59ef1816cb223b13b9ce386)
 - **Platform**:     Ubuntu 20.04
 - **Installation**: Binary from GitHub release page
 - **Network**:      mainnet

# Steps to Reproduce

If I run cardano-wallet for long enough, sooner or later the `produced_blocks` field will stop increasing even though the software is following the network and is in sync.

## Exhibit A:

PoolId: `pool1668w66pcrdjmavz0c7vym7s4d3xm7578jy0fqzhk55677t4etud`

The following commands were executed in sequence:

```
cardano-wallet network information --port 3102
Ok.
{
    "network_tip": {
        "time": "2021-01-24T13:05:00Z",
        "epoch_number": 243,
        "absolute_slot_number": 19927209,
        "slot_number": 314409
    },
    "node_tip": {
        "height": {
            "quantity": 5251350,
            "unit": "block"
        },
        "time": "2021-01-24T13:04:25Z",
        "epoch_number": 243,
        "absolute_slot_number": 19927174,
        "slot_number": 314374
    },
    "sync_progress": {
        "status": "ready"
    },
    "next_epoch": {
        "epoch_start_time": "2021-01-25T21:44:51Z",
        "epoch_number": 244
    }
}
```

```
stake-pool list --port 3102 --stake 1 | grep "pool1668w66pcrdjmavz0c7vym7s4d3xm7578jy0fqzhk55677t4etud" 
    {
        "flags": [],
        "metrics": {
            "saturation": 0.2580665047149284,
            "non_myopic_member_rewards": {
                "quantity": 0,
                "unit": "lovelace"
            },
            "produced_blocks": {
                "quantity": 31,
                "unit": "block"
            },
            "relative_stake": {
                "quantity": 5.0e-2,
                "unit": "percent"
            }
        },
        "cost": {
            "quantity": 340000000,
            "unit": "lovelace"
        },
        "margin": {
            "quantity": 3,
            "unit": "percent"
        },
        "pledge": {
            "quantity": 1260000000000,
            "unit": "lovelace"
        },
        "id": "pool1668w66pcrdjmavz0c7vym7s4d3xm7578jy0fqzhk55677t4etud"
    },
```

Note the value returned by cardano-wallet: `produced_blocks: 31`
The last block created by this pool was 2 hours ago (from "2021-01-24T13:05:00Z")

At the same time other explorers show the total number of blocks produced by this pool as such:
pooltool.io: 32
adastat.net: 32

## Expected behavior

Show the total number of blocks created by the pool

## Actual behavior

The pool's `produced_blocks` field does not increase when a new block is created for hours/days.
In fact the only fix for this is to restart cardano-wallet. Once that's done the software immediately shows the right number of total blocks produced by the pool.

**Comment by rvl** [comment]
Hi @PegasusPool, thanks for reporting this. Are there any error messages in the cardano-wallet log when it happens?

**Comment by PegasusPool** [comment]
Hi @rvl 
I checked the logs for when I was doing this test and I see no errors.

```
Jan 24 12:57:36 [cardano-wallet.api-server:Info:8268] [2021-01-24 12:57:36.59 UTC] [RequestId 1860] [GET] /v2/stake-pools?stake=1
Jan 24 12:57:36 [cardano-wallet.network:Info:8268] [2021-01-24 12:57:36.59 UTC] Will query non-myopic rewards using the stake 1
Jan 24 12:57:36 [cardano-wallet.network:Info:8268] [2021-01-24 12:57:36.59 UTC] Query GetCurrentPParams took 0.00106205s
```

**Comment by Anviking** [comment]
Hi,
Do you have logs further back? It would in particular be interesting to see recent `[cardano-wallet.pools-engine]` logs, because it sounds like it has stopped.

**Comment by PegasusPool** [comment]
@Anviking I think you are onto something. I had to go back quite some time (~17hours) but this is the last message from `[cardano-wallet.pools-engine]` before Jan 24 12:57:36.

```
Jan 23 20:10:55: [cardano-wallet.pools-engine:Error:50] [2021-01-23 20:10:55.69 UTC] Unexpected error following the chain: ExceptionInLinkedThread ThreadId 4170 (MuxError MuxBearerClosed "<socket: 23> closed when reading data, waiting on next header True")
Jan 23 20:10:55: [cardano-wallet.pools-engine:Error:50] [2021-01-23 20:10:55.70 UTC] Chain follower exited with error. Worker will no longer monitor stake pools.
Jan 23 20:10:55: [cardano-wallet.pools-engine:Notice:50] [2021-01-23 20:10:55.70 UTC] Worker has exited: main action is over.
```

**Comment by PegasusPool** [comment]
I have updated to the latest version, but this is still happening, and if anything even more often. I find myself having to restart cardano-wallet on a daily basis because of this. I can see that it's in the list of known issues, hopefully you'll find a fix soon.

**Comment by KtorZ** [comment]
@PegasusPool if the background worker synchronizing pool dies, it certainly leaves a trace in the logs. If you could get that trace, we would be able to pinpoint the issue much faster :pray:

**Comment by KtorZ** [comment]
(From the error above, it seems that the connection is lost with the node at some point, maybe because your system enters in hibernation and forces the connections to terminate..)

**Comment by PegasusPool** [comment]
@KtorZ That's the only log I see at the time the worker dies. Is there another method to get this trace you are referring to? I'm happy to investigate it with guidance.
My system does not go into hibernation so I'd take that out of the equation. 
But even if the connection to the node is lost (maybe it's restarted) is it not reasonable to expect that cardano-wallet reconnects after some time?

**Comment by KtorZ** [comment]
The wallet background worker does, not the one for the stake pool. That's indeed arguably a bad decision :upside_down_face: I do think that in most cases, we do not want to reconnect because that worker is not supposed to exit the first place. However, there are obviously some cases where this would be a desired behavior, like when the connection with the node is lost. 

We'll look into it.

**Comment by HeinrichApfelmus** [comment]
@PegasusPool Does this issue persist?

I'd like to close this issue as outdated, but I have the feeling that the problem is still there, as I do not remember any significant changes to the worker thread code.
