### ISSUE TITLE
cardano-wallet doesn't allow use unspoiled rewards when you join a a stake-pool with the wallet rest api

### ISSUE THREAD

**Issue by santins77** [cardano-foundation/cardano-wallet#2534]
# Context

We are running a Cardano Node in Linux. We use cardano-wallet rest api to communicate with it. When we use cardano-wallet rest api to delegate to external stake pool it works right. But when we receive the rewards for the delegation we can't access them. They never pass to available amount.

## Essential Information

 - **Version**:      2021.2.15 (git revision: a37c9856b4d96286e3f01a95026c63b986ebbba0)
 - **Platform**:     Linux
 - **Installation**: Binary from GitHub release page/
 - **Network**:      mainnet

Output of wallet information from cardano-wallet:

=> {"passphrase"=>{"last_updated_at"=>"2020-09-28T13:45:25.259262628Z"}, "address_pool_gap"=>20, "state"=>{"status"=>"ready"}, "balance"=>{"reward"=>{"quantity"=>**1489690**, "unit"=>"lovelace"}, "total"=>{"quantity"=>**107142408**, "unit"=>"lovelace"}, "available"=>{"quantity"=>**105652718**, "unit"=>"lovelace"}}, "name"=>"stake_wallet", "delegation"=>{"next"=>[], "active"=>{"status"=>"delegating", "target"=>"pool1vx9tzlkgafernd9vpjpxkenutx2gncj4yn88fpq69823qlwcqrt"}}, "id"=>"***", "tip"=>{"height"=>{"quantity"=>5384633, "unit"=>"block"}, "time"=>"2021-02-24T15:23:36Z", "epoch_number"=>249, "absolute_slot_number"=>22613925, "slot_number"=>409125}, "assets"=>{"total"=>[], "available"=>[]}} 

# Steps to Reproduce

curl -X PUT http://localhost:8090/v2/stake-pools/***/wallets/***/ -H "Content-Type: application/json" -d '{"passphrase":"***"}'

After some months receiving rewards they are still not accessible:

curl http://localhost:8090/v2/wallets
[{"passphrase":{"last_updated_at":"2020-09-28T13:45:25.259262628Z"},"address_pool_gap":20,"state":{"status":"ready"},"balance":{"reward":{"quantity":**1489690**,"unit":"lovelace"},"total":{"quantity":**107142408**,"unit":"lovelace"},"available":{"quantity":**105652718**,"unit":"lovelace"}},"name":"stake_wallet","delegation":{"next":[],"active":{"status":"delegating","target":"pool1vx9tzlkgafernd9vpjpxkenutx2gncj4yn88fpq69823qlwcqrt"}},"id":"***","tip":{"height":{"quantity":5384810,"unit":"block"},"time":"2021-02-24T16:21:17Z","epoch_number":249,"absolute_slot_number":22617386,"slot_number":412586},"assets":{"total":[],"available":[]}}]

## Expected behavior

The expected behaviour is that after some time you can retire the unspoiled rewards from the wallet.

## Actual behavior

The rewards are not accesible from cardano-wallet

**Comment by KtorZ** [comment]
Hi, reward withdrawals must be explicitly requested for them to happen. You can do this by specifying a `withdrawal` body parameter when constructing a transaction. 

https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/postTransaction

**Comment by santins77** [comment]
Thanks! This worked perfectly!
