### ISSUE TITLE
Please increase the maxLength of the AssetTicker field

### ISSUE THREAD

**Issue by gitmachtl** [cardano-foundation/cardano-wallet#2541]
This is linked to 

https://github.com/input-output-hk/metadata-server/issues/30

please move it into the right place.

------------------------

Hi,

https://github.com/input-output-hk/metadata-server/blob/master/specifications/wallet/submission-schema.json

specifies a maxLength of only 4 chars for the ticker field of the native token.

please increase this to 8 chars!

why is there such a short limitation needed or suggested? so not even pool-operators can use there native pool tickers to create there own native assets with the same ticker name!?

please explain this to us or please provide us the right contact to discuss this, because is this is not a rational decision imo.

thank you very much!

Martin

**Comment by rvl** [comment]
Hi @gitmachtl, you don't need to use the `ticker` field - it's an optional abbreviation of the asset name. When `ticker`, is not present, user interfaces will display `name` instead. If the name is long, however, the GUI may need to truncate it to fit in the space.

**Comment by rvl** [comment]
We could probably increase the ticker max length to 5 so it matches the stake pool ticker. Longer than this, it starts looking less like an abbreviation, and more like a name.

**Comment by gitmachtl** [comment]
Ok, than please increase it to 5 chars. So we have it set up the same way like a pool ticker. You have 5 chars for pool tickers and a longer Name. So this would be consistent.

Short tickers can be confusing:
GPWR -> GREENPWR, GPWR -> GREATPWR, PWRL -> POWERLESS
BTC, BCH, BSV, BTG, etc... are all very confusing and are all "Bitcoin".

**Comment by rvl** [comment]
This was resolved in [v2021-03-04](https://github.com/input-output-hk/cardano-wallet/releases/tag/v2021-03-04)
