### ISSUE TITLE
[feature] Add "birthday" (aka "block height") option when restoring wallet

### ISSUE THREAD

**Issue by jonathancross** [cardano-foundation/cardano-wallet#2544]
[being moved here from [daedalus#2416](https://github.com/input-output-hk/daedalus/issues/2416)]

When restoring a wallet from seed phrase, the user should have an option to set a so-called "birthday" (block height or date) of the first transaction. The idea is that transactions from older blocks can be ignored unless they have direct bearing on UTXOs owned by this wallet.

The goal is dramatically faster syncing.

I am coming at this from the Bitcoin / Monero space where this feature has been part of the UX for a long time. Perhaps there is something different in Cardano which prevents such a speedup?

### Jira ticket

ADP-106

**Comment by KtorZ** [comment]
@jonathancross Thanks for your feedback here. Note that we have captured this (i.e. the ability to restore a wallet from a given date / slot number) in a user story some times ago already. As for many other UX improvements that we have in the backlog, what we are missing so far is a bit of time to go through them. As you know, Cardano is evolving at a quite crazy pace and so far, we've been busy in catching up with era changes in the ledger / the node. 

We've been discussing internally about making some of our roadmap in the wallet a bit more public to give people visibility about this kind of things. From the Github repository, it may looks like we aren't doing much, but we actually have a quite large backlog of UX items like this one. 

Short story short: I totally agree with you and this would be a nice feature.

**Comment by jonathancross** [comment]
Transparency and open collaboration are good  :-)

**Comment by HeinrichApfelmus** [comment]
We implemented a feature like that, see "Restoration mode / Restoration from block" in the create wallet endpoint.
