### ISSUE TITLE
[FR] Allow separate reward receive address for normal delegators

### ISSUE THREAD

**Issue by Straightpool** [cardano-foundation/cardano-wallet#2556]
Internal / Exernal
External

Describe the feature you'd like
A regular delegator might want to specify a separate reward receive address for these reasons:

Tax purposes (in some juristaction re-staked coins extend the holding period)
Accounting purposes to keep track of rewards
Reward savings account for multiple people to pool rewards into one address to fund e.g. something
...
Currently this is only possible during pool registration for pool ops at the step
${CCLI} shelley stake-pool registration-certificate

Of course this needs to be available in the UI for the average user via Deadalus or Yoroi, but a first step is cardano-cli support.

Describe alternatives you've considered
None

Additional context / screenshots
None

**Comment by Anviking** [comment]
Is the idea that you want _all funds_ in a wallet to be associated with a specified stake key, e.g. a stake key belonging to a different wallet?

**Comment by Straightpool** [comment]
Yes, this is a good summary.

**Comment by hi3rophant** [comment]
Let s hope it goes through!

**Comment by Straightpool** [comment]
There is a CLI hack for this, not yet tested, but I see no reason why this should not work.

Create two wallets, one for the stake, one for the rewards e.g. using two hardware wallets or two seed phrases. Delegate the rewards wallet to the pool of your choice.

Obtain receive addresses for both wallets.

Create a franken-address with the stake wallet payment key + reward wallet stake key.

Go into ccvault settings, set the stake wallet to "nami mode" or use Nami wallet with single address mode and use this franken-address for the single address of this wallet. 
If there is a transaction on the stake wallet, the stake always remains delegated.

Send the stake funds from the stake wallet to the created franken address.

See more here: https://www.youtube.com/watch?v=KULzovfWn-M&t=3s
