### ISSUE TITLE
why am I getting the wallet address type sometimes as test address?

### ISSUE THREAD

**Issue by gitloverr** [cardano-foundation/cardano-wallet#2558]
Hi everyone,

I'm running with Cardano-wallet for mainnet. I started the docker-compose with `NETWORK=mainnet` I created a wallet with mnemonic_sentence then I checked the wallet addresses, (get wall) those addresses  sometimes look like this:"addr_test1qpsfrdk43mm......." (with test tag) and sometimes normally (addr1q9sfrdk43mmxpqtqalv2....like..) -without test prefix-  

why happened this?
Thank you

**Comment by rvl** [comment]
Hi, you need to add `--mainnet` to the RUN arguments of the cardano-wallet container.
