### ISSUE TITLE
When will we be able to create and send assets?

### ISSUE THREAD

**Issue by coconutpool** [cardano-foundation/cardano-wallet#2584]
When will we be able to create and send assets from the wallet-server?

**Comment by rvl** [comment]
cardano-wallet server can send assets but it doesn't yet have a minting function. You can mint assets with cardano-cli.

**Comment by coconutpool** [comment]
Ok great, but it's not documented in the API docs. Could somebody please update that?

Only get asset metadata and list assets are documented. 


https://input-output-hk.github.io/cardano-wallet/api/edge/

**Comment by rvl** [comment]
Perhaps we can make the docs more clear, thanks for pointing that out.
Assets are treated more or less the same as ada, and appear wherever there are ada amounts.
So you can add assets to the `payment` field of [`postTransaction`](https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/postTransaction), and you can see them in the wallet balance..

**Comment by coconutpool** [comment]
Thanks for addressing my concerns. I appreciate your help.
