### ISSUE TITLE
Include CARDANO_WALLET_HOST environment variable when running a cluster

### ISSUE THREAD

**Issue by leobel** [cardano-foundation/cardano-wallet#2591]
Include CARDANO_WALLET_HOST environment variable when running a cluster so you can interact with the cluster outside the local machine. 

Right now the host `127.0.0.1` is hardcoded here https://github.com/input-output-hk/cardano-wallet/blob/master/lib/shelley/exe/local-cluster.hs#L266 and maybe we can change it the same way the other parameters does (e.g. CARDANO_WALLET_PORT) and keep `127.0.0.1` as default.

**Comment by rvl** [comment]
Good idea.
