### ISSUE TITLE
unexpected floating number error

### ISSUE THREAD

**Issue by gitloverr** [cardano-foundation/cardano-wallet#2595]
hi everyone,

I try to send ADA, from an address to another. When I try  this ADA value ( 2.0190109999999994 ADA) for sending to another wallet, I got this error:

`'{"code":"bad_request","message":"Error in $.payments[1].amount.quantity: parsing AddressAmount failed, parsing Natural failed, unexpected floating number 2019010.9999999995"}'`

Why this situation happened? I would like to send all ADA's value to another, If I decrease the this ada value, I guess the sending process will  be success. but tiny ADA value will send to my another address of my wallet or I don't know...

what will I do?

thank you

**Comment by piotr-iohk** [comment]
@gitloverr I assume that you are trying to send your ADA using https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/postTransaction endpoint sending request to `cardano-wallet` directly?

Please note that wallet API operates at `lovelace` level (1ADA = 1 000 000 lovelace) and whole numbers only:
![Screenshot from 2021-04-01 15-57-33](https://user-images.githubusercontent.com/42900201/113305137-04d22d00-9303-11eb-9ee0-0e213a872811.png)

**Comment by gitloverr** [comment]
Hi, @piotr-iohk  thank you your support. Yes, I'm using the Cardano-wallet. 

Actually my scenario is that: 

My wallet total ada balance is : 8.1 ADA

and We assume my ada wallet address is : X 
I would like to send 5.9 ADA to Y address

The network says (Cardano-wallet) this transaction fee will be 0.180989 ADA

Now;

Remaining ADA = **My Wallet Total ADA Amount - Transfer amount to Y Address - Fee**  

Remaining ADA = 2.0190109999999994 ADA

I would like to send this Remaining ADA (2.0190109999999994 ADA) to  the X Address (not random address of  the wallet, exactly selected ADA address. ) Therefore I put the the my X ADA address as the transaction output with this REMAINING ADA BALANCE. 

what should I do?

Thank you

**Comment by KtorZ** [comment]
@gitloverr You **should not** use floating arithmetic when dealing with finance. Floating arithmetic is poorly suited for precise computation over large decimals and can cope well with rounding. For example, in your calculation above, the resulting amount is actually:

```
2.019011 Ada
```

What you should do instead use plain integer at a higher resolution. In Cardano, we use `Lovelace`, 1 Ada is worth 1.000.000 Lovelace. So in your example, 8.1 Ada is 8100000 Lovelace, 5.9 Ada is 5900000 Lovelace and fees are actually: 180989. 

So, your amount end up being:

8100000 - 5900000 - 180989 = 2019011 Lovelace

The wallet API only speaks in Lovelace and expect you to fill all amount in Lovelace to avoid issues coming with floating arithmetic.

**Comment by gitloverr** [comment]
> @gitloverr You **should not** use floating arithmetic when dealing with finance. Floating arithmetic is poorly suited for precise computation over large decimals and can cope well with rounding. For example, in your calculation above, the resulting amount is actually:
> 
> ```
> 2.019011 Ada
> ```
> 
> What you should do instead use plain integer at a higher resolution. In Cardano, we use `Lovelace`, 1 Ada is worth 1.000.000 Lovelace. So in your example, 8.1 Ada is 8100000 Lovelace, 5.9 Ada is 5900000 Lovelace and fees are actually: 180989.
> 
> So, your amount end up being:
> 
> 8100000 - 5900000 - 180989 = 2019011 Lovelace
> 
> The wallet API only speaks in Lovelace and expect you to fill all amount in Lovelace to avoid issues coming with floating arithmetic.

ok, I see @KtorZ, thank you!
