### ISSUE TITLE
Provide some way to get the wallet Id from the recovery phrase or account public key

### ISSUE THREAD

**Issue by leobel** [cardano-foundation/cardano-wallet#2602]
I think that will be useful to get the wallet Id on "restore" or in another dedicated method. If for some reason you lost track of the wallet Id but the wallet is already loaded you'll find a hard time to get the wallet Id and effectively use it again. 

I mean, maybe from an UI point of view is ok to just return an error when the wallet already exist ("This operation would yield a wallet with the following id: {id} However, I already know of a wallet with this id.") since the user will be able to identify it from the wallet's list visually but when it's a program who is interacting with the API the code cannot identify the wallet from the list.

The endpoint create/restore Wallet cover these scenarios:

```
Wallet on Server Instance List | Wallet on Blockchain |   Action
            no                 |           no         |   Create
            no                 |           yes        |   Restore
            yes                |           yes        |   Throw error wallet_already_exist
```

**Comment by rvl** [comment]
Hi @leobel, thanks for the suggestion. We will be implementing this soon to support the "reset password from recovery phrase" feature in Daedalus.

**Comment by gringokiwi** [comment]
Commenting just to say I second this; having the wallet ID get returned as a seperate key in a conflict error could be nice, or better, have a single endpoint to get details on a wallet (via xpub) regardless of whether it exists on the DB. Thanks for raising this (and making cardano-wallet-js) @leobel

**Comment by said1296** [comment]
I got stuck on something similar today, this feature would have been really helpful.

**Comment by piotr-iohk** [comment]
> I got stuck on something similar today, this feature would have been really helpful.

This feature has been added to cardano-addresses actually, See "How to generate a wallet id based on extended root or account keys" in the [README](https://github.com/input-output-hk/cardano-addresses/blob/master/README.md).

(it is currently in cardano-addresses `master` but should be released soon)

**Comment by HeinrichApfelmus** [comment]
Closing as "Done".
