### ISSUE TITLE
Cardano-wallet malformed tx payload on Submit External Transaction endpoint

### ISSUE THREAD

**Issue by leobel** [cardano-foundation/cardano-wallet#2610]
I’m trying to submit an already signed tx from `cardano-cli` using the `cardano-wallet` endpoint: `https://localhost:8090/v2/proxy/transactions`

the signed transaction look like this:

       txBody = {
            "type": "Tx MaryEra",
            "description": "",
            "cborHex": "83a400818258202d7928a59fcba5bf71c40fe6428a301ffda4d2fa681e5357051970436462b89400018282583900c0e88694ab569f42453eb950fb4ec14cb50f4d5d26ac83fdec2c505d818bcebf1df51c84239805b8a330d68fdbc3c047c12bb4c3172cb9391a002b335f825839003d2d9ceb1a47bc1b62b7498ca496b16a7b4bbcc6d97ede81ba8621ebd6d947875fcf4845ef3a5f08dd5522581cf6de7b9c065379cbb3754d1a001e8480021a00029361031a01672b7ea1008182582073dd733cc50d594cb89d3ac67287b02dae00982fc800e9c9c9d1bb282b56122558404d0cb4e4f1cc415ddcf546871f075d0ca6e0c2620cd784b06c21c9b86e4403cb7a115038487576dcb20e7820e9d0dc93ab2a737ed9d0a71a77bc1e12f7c4dd0ef6"
        }

I just don’t know how to pass it to the endpoint using Content-Type `application/octet-stream`. The API doc says the payload should be:

    string <binary>
    Signed transaction message binary blob.

I’m using javascript for this and have tried passing the `cborHex` directly, using `Buffer.from(txBody.cborHex).toString('base64')` and the whole json `Buffer.from(JSON.stringify(txBody)).toString('base64')` but always got the same response:

    {
      "code": "malformed_tx_payload", 
      "message": "I couldn't verify that the payload has the c…node. Please check the format and try again."
    }

Also I’ve noticed from the swagger specification that the endpoint support a JSON payload and taking a look to the `cardano-wallet`'s source code [here][1]:

    newtype PostExternalTransactionData = PostExternalTransactionData
        { payload :: ByteString
        } deriving (Eq, Generic, Show)

I thought the structure should be some like this:

    {
      "payload": ?// some binary blob here that I can't find. I've tried with: 
                  // Buffer.from(txBody.cborHex).toString('base64') and 
                  // Buffer.from(JSON.stringify(txBody)).toString('base64')
    }

Any idea how to construct the payload and pass the signed tx?

  [1]: https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/src/Cardano/Wallet/Api/Types.hs#L780

**Comment by KtorZ** [comment]
That endpoint does not accept JSON, it accepts a raw octet-stream. I don't know what HTTP client you're using, but there's certainly a way to provide a plain Buffer as a request. Following your examples and assuming Node.js, you would construct such a Buffer as:

```
const buffer = Buffer.from(txBody.cborHex, "hex")
```

Now, it's a matter of passing that buffer as THE request payload to your HTTP client.

**Comment by leobel** [comment]
@KtorZ I just tried that way without any luck. I'm using the autogenerated code from swagger, it looks like this:

```
export const ProxyApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * <p align=\"right\">status: <strong>stable</strong></p>  Submits a transaction that was created and signed outside of cardano-wallet. 
         * @summary Submit External Transaction
         * @param {Object} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postExternalTransaction: async (body?: Object, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/proxy/transactions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/octet-stream';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProxyApi - functional programming interface
 * @export
 */
export const ProxyApiFp = function(configuration?: Configuration) {
    return {
        /**
         * <p align=\"right\">status: <strong>stable</strong></p>  Submits a transaction that was created and signed outside of cardano-wallet. 
         * @summary Submit External Transaction
         * @param {Object} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postExternalTransaction(body?: Object, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2022>> {
            const localVarAxiosArgs = await ProxyApiAxiosParamCreator(configuration).postExternalTransaction(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ProxyApi - factory interface
 * @export
 */
export const ProxyApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * <p align=\"right\">status: <strong>stable</strong></p>  Submits a transaction that was created and signed outside of cardano-wallet. 
         * @summary Submit External Transaction
         * @param {Object} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postExternalTransaction(body?: Object, options?: any): AxiosPromise<InlineResponse2022> {
            return ProxyApiFp(configuration).postExternalTransaction(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProxyApi - object-oriented interface
 * @export
 * @class ProxyApi
 * @extends {BaseAPI}
 */
export class ProxyApi extends BaseAPI {
    /**
     * <p align=\"right\">status: <strong>stable</strong></p>  Submits a transaction that was created and signed outside of cardano-wallet. 
     * @summary Submit External Transaction
     * @param {Object} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProxyApi
     */
    public postExternalTransaction(body?: Object, options?: any) {
        return ProxyApiFp(this.configuration).postExternalTransaction(body, options).then((request) => request(this.axios, this.basePath));
    }
}
```

I'm using this way:

```
const buffer = Buffer.from(txBody.cborHex, "hex");
proxyApi.postExternalTransaction(buffer);
```

Could be another problem but the API is just returning this generic error?

**Comment by face0612** [comment]
having a similar issue. I am getting `malformed_tx_payload` error even when sending through octet-stream

**Comment by electic** [comment]
Having the same issue here as well.

**Comment by leobel** [comment]
I solved the issue, the problem on my case was here:
```
postExternalTransaction: async (body?: Object, options: any = {}): Promise<RequestArgs> => {
            ...
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
```

It seems that the swagger code generation here: [https://editor.swagger.io](https://editor.swagger.io) has some issues generating the typescript/axios client since these lines:
```
  const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
  localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");
```
are the problem. Here the `Buffer` is being "stringified" but we need to pass it as THE REQUEST as @KtorZ mentioned above. 

So replacing the 2 above lines for this:
`localVarRequestOptions.data =  body;` 

the buffer will be passed as is
