### ISSUE TITLE
Unable to invoke api calls when using TLS flags

### ISSUE THREAD

**Issue by cheapstaking** [cardano-foundation/cardano-wallet#2625]
# Context

Unable to invoke any remote api calls when using TLS flags - Error "HandshakeFailed Error_EOF" - also cardadno-wallet cli commands that require API fail "This server only accepts secure HTTPS connections."

## Essential Information

 - **Version**:     2021.4.8
 - **Platform**:     Linux
 - **Installation**: Built from source
 - **Network**:      testnet

# Steps to Reproduce
1. Create lets encrypt cert
2. Separate full chain pem file 
2. start cardano-wallet with ssl flags
3.  Invoke get wallets api call from remote host with https. call fails, cardano wallet logs: "HandshakeFailed Error_EOF"

## Expected behavior
Return the wallet similar to http call

**Comment by rvl** [comment]
Hi there - Let's Encrypt certificates are primarily for publicly accessible servers.
You do not want to run the cardano-wallet API in this way.

Furthermore, the cardano-wallet API server requires HTTPS clients to authenticate with a client certificate.
You can create self-signed server and client certificates with `openssl`.

**Comment by cheapstaking** [comment]
> Hi there - Let's Encrypt certificates are primarily for publicly accessible servers.
> You do not want to run the cardano-wallet API in this way.
> 
> Furthermore, the cardano-wallet API server requires HTTPS clients to authenticate with a client certificate.
> You can create self-signed server and client certificates with `openssl`.

Thanks Rodney - im trying to make it accessible but restricted to only a serverless logicApp via https with a firewall rule. (which wouldnt have a client cert)

Sounds like what im trying to do is not possible then

**Comment by rvl** [comment]
You could run the cardano-wallet API behind a reverse proxy (e.g. NGINX) which does your SSL termination.

**Comment by cheapstaking** [comment]
> You could run the cardano-wallet API behind a reverse proxy (e.g. NGINX) which does your SSL termination.

Good call - ill take that route, thanks!
