### ISSUE TITLE
docker compose is not starting the stack

### ISSUE THREAD

**Issue by ggcaponetto** [cardano-foundation/cardano-wallet#2635]
# Context

When executing

```
wget https://raw.githubusercontent.com/input-output-hk/cardano-wallet/master/docker-compose.yml
NETWORK=testnet docker-compose up
```
i expect the starting of all containers.

Currently i get the error: ``ERROR: manifest for inputoutput/cardano-wallet:2021.4.28-shelley not found: manifest unknown: manifest unknown``

**Comment by rvl** [comment]
Hi @ggcaponetto you are best off using configs from a released version, rather than `master`, which is the unstable development branch. So:
```
wget https://raw.githubusercontent.com/input-output-hk/cardano-wallet/v2021-04-08/docker-compose.yml
```

**Comment by ggcaponetto** [comment]
@rvl thanks. I got it to work.

**Comment by rvl** [comment]
Great!
