### ISSUE TITLE
Image cardano-wallet:2021.4.28-shelley does not exists

### ISSUE THREAD

**Issue by dario97** [cardano-foundation/cardano-wallet#2639]
I get the following error when running docker-compose up command:

> ERROR: manifest for inputoutput/cardano-wallet:2021.4.28-shelley not found: manifest unknown: manifest unknown

if I change that image to "inputoutput / cardano-wallet: 2021.4.28", everything works fine.

**Comment by rvl** [comment]
Hi @dario97 - yes, thanks, since the [v2021-04-28](https://github.com/input-output-hk/cardano-wallet/releases/tag/v2021-04-28) release, the image is now tagged as `inputoutput/cardano-wallet:2021.4.28`. Fixed in #2640.
