### ISSUE TITLE
Cardano Wallet Serve Couldn't connect to Node

### ISSUE THREAD

**Issue by varianchu** [cardano-foundation/cardano-wallet#2653]
I am trying to use this command:

 cardano-wallet serve \
  --testnet testnet-byron-genesis.json \
  --node-socket CARDANO_NODE_SOCKET_PATH_OR_PIPE \
  --database ./wallets-testnet

However once executed, I couldn't seem to connect to the node. Any ideas as to why this is happening?
![Screen Shot 2021-05-15 at 10 01 19 AM](https://user-images.githubusercontent.com/2063765/118345094-dcc22480-b564-11eb-85ac-8a704a01dfac.png)

**Comment by rvl** [comment]
Hi there @varianchu, the text `CARDANO_NODE_SOCKET_PATH_OR_PIPE ` is supposed to be replaced with the actual filepath of the socket for a running `cardano-node`. You need to run both `cardano-wallet` and `cardano-node`, and they communicate using this file. Here are [instructions on how to run cardano-node](https://docs.cardano.org/projects/cardano-node/en/latest/).
