### ISSUE TITLE
Flaky test: /tmp/stack-2dfd0bd162f34f1a/test-ghc-env: openBinaryFile: resource busy (file is locked)

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#2657]
# Context

There are rare failures just after the `stack test` run completes. The error message is:
```
/tmp/stack-2dfd0bd162f34f1a/test-ghc-env: openBinaryFile: resource busy (file is locked)
```

It could be a bug in `stack`. See https://github.com/commercialhaskell/stack/issues/5024.

# Test Case

Buildkite stack build & test.

# Failure / Counter-example

https://buildkite.com/input-output-hk/cardano-wallet/builds/14712#f922ddf0-672a-43cc-8414-bd7aad2d49d6

```
...
cardano-wallet             > Finished in 30.6675 seconds
cardano-wallet             > 158 examples, 0 failures
cardano-wallet             > Test suite unit passed
Completed 8 action(s).
/tmp/stack-2dfd0bd162f34f1a/test-ghc-env: openBinaryFile: resource busy (file is locked)
 
/tmp/stack-2dfd0bd162f34f1a/test-ghc-env: openBinaryFile: resource busy (file is locked)
error: Command exited with code 1!
```

---

# Resolution 

We need a workaround for the stack issue which doesn't involve using `-j1`.

---

# QA

**Comment by Anviking** [comment]
Not seen for a while & we're not using stack anymore - closing.
