### ISSUE TITLE
Missing 'Transaction' schema from list transaction and create transaction in API documentation

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#268]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Windows & OSX & Linux) | Configuration |

# Context
 
 

The response schema from `listTransaction` and `createTransaction` in the API shows nothing, or inconsistent values... Something's probably off with the swagger specification.

- https://input-output-hk.github.io/cardano-wallet/api/#operation/listTransactions

![image](https://user-images.githubusercontent.com/5680256/57788882-2a1e1800-7738-11e9-8431-fe8a65535c90.png)

- https://input-output-hk.github.io/cardano-wallet/api/#operation/postTransaction

![image](https://user-images.githubusercontent.com/5680256/57788904-35714380-7738-11e9-8183-f950f5b35fdb.png)

# Steps to Reproduce

N/A

---

# Resolution Plan

 - Investigate the shape of the `swagger.yaml` and see try to understand why ReDoc can't find the schema? I know we've moved some definitions around _recently_ and probably broke some references.

# PR

| Number   | Base      |
| ---      | ---       |
| #269        | `master` |

# QA 

- Latest documentation deployment now correctly displays the schema for transactions. cf: https://input-output-hk.github.io/cardano-wallet/api/#operation/listTransactions

**Comment by piotr-iohk** [comment]
:+1:
