### ISSUE TITLE
Cabal build fails with random-1.2.0

### ISSUE THREAD

**Issue by Mercurial** [cardano-foundation/cardano-wallet#2685]
# Context

When trying to compile `cardano-wallet` using cabal I'm getting the following error:

```
src/Cardano/Wallet/DB/Sqlite/Types.hs:575:24: error:
    • No instance for (Read StdGen)
        arising from a use of ‘fromPersistValueRead’
    • In the expression: fromPersistValueRead
      In an equation for ‘fromPersistValue’:
          fromPersistValue = fromPersistValueRead
      In the instance declaration for ‘PersistField StdGen’
    |
575 |     fromPersistValue = fromPersistValueRead
    |                        ^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build cardano-wallet-core-2021.4.28 (which is required by
exe:local-cluster from cardano-wallet-2021.4.28, test:integration from
cardano-wallet-2021.4.28 and others).
```

tried ghc `8.10.2` and `8.10.4`

## Essential Information

 - **Version**:      `cardano-wallet` release/tag ` v2021-05-26`
 - **Platform**:    Linux (Ubuntu 20.04)
 - **Installation**: from source
 - **Network**:  any

# Steps to Reproduce
1. git clone https://github.com/input-output-hk/cardano-wallet.git
2. git fetch --all --recurse-submodules --tags
3. git checkout tags/v2021-05-26
4. cabal configure --with-compiler=ghc-8.10.4
5. cabal build all

## Expected behavior

I expect it to compile succesfully

## Actual behavior

I get the following error and compilation fails:

```
src/Cardano/Wallet/DB/Sqlite/Types.hs:575:24: error:
    • No instance for (Read StdGen)
        arising from a use of ‘fromPersistValueRead’
    • In the expression: fromPersistValueRead
      In an equation for ‘fromPersistValue’:
          fromPersistValue = fromPersistValueRead
      In the instance declaration for ‘PersistField StdGen’
    |
575 |     fromPersistValue = fromPersistValueRead
    |                        ^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build cardano-wallet-core-2021.4.28 (which is required by
exe:local-cluster from cardano-wallet-2021.4.28, test:integration from
cardano-wallet-2021.4.28 and others).
```

# Jira ticket

ADP-961

**Comment by KtorZ** [comment]
The team mostly use Stack and Nix for building the project. We try to maintain build for Cabal along the way but few things might have broken in the cabal build with the various updates for Alonzo.

This will get addressed eventually, but for now it's better if you stick with stack. It seems that cabal is picking either and old or too recent version of persistent somehow.

Note that It's surprising that the CI automated jobs didn't catch that? cv @rvl

**Comment by KtorZ** [comment]
For any questions about building with stack, please refer to: https://github.com/input-output-hk/cardano-wallet/wiki/Building#stack

Alternatively, you may also get a precompiled binary or a docker image to avoid building yourself from sources (unless this is specifically what you want).

**Comment by Mercurial** [comment]
> For any questions about building with stack, please refer to: https://github.com/input-output-hk/cardano-wallet/wiki/Building#stack
> 
> Alternatively, you may also get a precompiled binary or a docker image to avoid building yourself from sources (unless this is specifically what you want).

Thank you, I am writing a documentation about Cardano Components so I'm trying all the options. But looks like I'll just recomend using `stack` for now when dealing with `cardano-wallet`.

**Comment by Mercurial** [comment]
I also found this related issue: https://github.com/input-output-hk/cardano-wallet/issues/2579

**Comment by rvl** [comment]
It's due to changes in [random-1.2.0](http://hackage.haskell.org/package/random-1.2.0/changelog).

Cabal picks whatever versions are newest according to its local index state, and any package version contraints.
Stack uses curated "LTS snapshot" package sets.
So there are often slight differences between dependency versions, depending on which build tool that you use.

Here is a workaround for Cabal:
```console
$ cabal configure --constraint="random<1.2"
$ cabal build all
```

There is only a `cabal configure` test in CI at them moment. Because the packages are already built once with stack, then again with nix. But we can add a nightly `cabal build` test to pick up these issues.

**Comment by Mercurial** [comment]
Thank you so much for the answer, much appreciated!

> It's due to changes in [random-1.2.0](http://hackage.haskell.org/package/random-1.2.0/changelog).
> 
> 
> 
> Cabal picks whatever versions are newest according to its local index state, and any package version contraints.
> 
> Stack uses curated "LTS snapshot" package sets.
> 
> So there are often slight differences between dependency versions, depending on which build tool that you use.
> 
> 
> 
> Here is a workaround for Cabal:
> 
> ```console
> 
> $ cabal configure --constraint="random<1.2"
> 
> $ cabal build all
> 
> ```
> 
> 
> 
> There is only a `cabal configure` test in CI at them moment. Because the packages are already built once with stack, then again with nix. But we can add a nightly `cabal build` test to pick up these issues.
> 
>
