### ISSUE TITLE
Lists all incoming and outgoing wallet's transactions issue

### ISSUE THREAD

**Issue by rajqumar** [cardano-foundation/cardano-wallet#2689]
https://localhost:8090/v2/wallets/{walletId}/transactions
This API is fetching transactions only within the addresses generated by a single wallet. 
It is not showing transactions from other wallet or if you deposit funds from faucet site.
External Transactions are not included in the response

**Comment by rajqumar** [comment]
I am generating enterprise address, its not showing in list addresses, neither the balance is getting updated.

**Comment by HeinrichApfelmus** [comment]
Transactions from an external wallet should eventually turn up in the history after they have been accepted into the blockchain.

Closing as out of date.

Please feel free to reopen if this issue persists — especially if you can provide a reproducible test case, e.g. a transaction on testnet which does not show up in the wallet history.
