### ISSUE TITLE
Node to client version error

### ISSUE THREAD

**Issue by mikaint** [cardano-foundation/cardano-wallet#2706]
# Context

Keep getting this error when connecting on testnet:
`IP LocalAddress "" ErrorPolicyUnhandledApplicationException (Refused NodeToClientV_8 "version data mismatch: NodeToClientVersionData {networkMagic = NetworkMagic {unNetworkMagic = 1097911063}} /= NodeToClientVersionData {networkMagic = NetworkMagic {unNetworkMagic = 764824073}}")
`

## Essential Information

 - **Version**:      1.25.1
 - **Platform**:     Linux, Mac
 - **Installation**: IOHK Docker image
 - **Network**:      mainnet/testnet

**Comment by KtorZ** [comment]
You are trying to connect to the testnet using a mainnet configuration (the default). This can be changed using the `--testnet` command option. See also: https://github.com/input-output-hk/cardano-wallet/wiki/Wallet-command-line-interface#examples

If you're using the `docker-compose` setup, you can configure the target network using an environment variable as:

```
NETWORK=testnet docker-compose up
```

**Comment by mikaint** [comment]
This is the command for wallet i have:
`
cardano-wallet serve --node-socket /ipc/node.socket --database /wallet-db --listen-address 0.0.0.0 --testnet /genesis/byron.json`

**Comment by rvl** [comment]
Hello @mikaint - please provide some more details about exactly which docker images you are using and how you are starting the wallet and node (e.g. `docker` command lines) so that we can help you.
