### ISSUE TITLE
[feature] Show incoming tx Input address in wallet API

### ISSUE THREAD

**Issue by MrMitch17** [cardano-foundation/cardano-wallet#2710]
I need to get the incoming address of transactions.   I am using cardano-wallet for a service and need to use the incoming address for who sent transactions into the wallet.  The rest API lists what I am looking for and on the testnet I was getting the address, but on mainnet I am not getting the address.   I would like to not have to use another service / API to get this information.

GET /v2/wallets/<walletid>/transactions

"assets and address are always present for outgoing transactions but generally absent for incoming transactions. This information is present on the Cardano explorer, but is not tracked by the wallet."

**Comment by rvl** [comment]
Hi @MrMitch17, thanks for the report.
That feature is on our backlog but it's not a high priority at the moment.
You will need to query an explorer for now.

**Comment by MrMitch17** [comment]
Sure thing, just figured I would make a note for visibility.

**Comment by wout** [comment]
I'd love to see this as well. Recently we launched an NFT mint that was using the wallet API to watch for transactions coming in. We had to close again because we were missing the buyers' addresses. We're now converting the app to use Blockfrost.

**Comment by HeinrichApfelmus** [comment]
Closely related to #2921

**Comment by HeinrichApfelmus** [comment]
The `/wallets/{walletId}/transactions-decode` endpoint provides functionality like this.
