### ISSUE TITLE
Couldn't connect to node

### ISSUE THREAD

**Issue by tmazhuan** [cardano-foundation/cardano-wallet#2759]
Hi all,
i'm trying to run the cardano-wallet against my mainnet node but always get the following message:
`[cardano-wallet.network:Warning:13] [2021-07-12 11:17:02.46 UTC] Couldn't connect to node (x87). Retrying in a bit...`

I use the following comand to start the wallet:
`docker run  inputoutput/cardano-wallet:2021.6.11 serve --node-socket=/home/thomasm/Cardano/cardano-node/node-ipc/mainnet/node.socket --mainnet`

Here are also the first few lines of output after i start the wallet:
`thomasm@pop-os:~/Cardano/wallet$ docker run  inputoutput/cardano-wallet:2021.6.11 serve --node-socket=/home/thomasm/Cardano/cardano-node/node-ipc/mainnet/node.socket --mainnet
[cardano-wallet.main:Info:4] [2021-07-12 11:14:17.30 UTC] Running as v2021-06-11 (git revision: 1532352c75cfe02015873c4c82b0d76eb798dfd8) on x86_64-linux
[cardano-wallet.main:Info:4] [2021-07-12 11:14:17.30 UTC] Command line: /bin/cardano-wallet serve --node-socket=/home/thomasm/Cardano/cardano-node/node-ipc/mainnet/node.socket --mainnet
[cardano-wallet.main:Debug:4] [2021-07-12 11:14:17.30 UTC] ServeArgs {_hostPreference = Host "127.0.0.1", _listen = ListenOnPort 8090, _tlsConfig = Nothing, _nodeSocket = CardanoNodeConn "/home/thomasm/Cardano/cardano-node/node-ipc/mainnet/node.socket", _networkConfiguration = MainnetConfig, _database = Nothing, _syncTolerance = SyncTolerance 300s, _enableShutdownHandler = False, _poolMetadataSourceOpt = Nothing, _tokenMetadataSourceOpt = Nothing, _logging = LoggingOptions {loggingMinSeverity = Debug, loggingTracers = Tracers {applicationTracer = Const (Just Info), apiServerTracer = Const (Just Info), tokenMetadataTracer = Const (Just Info), walletEngineTracer = Const (Just Info), walletDbTracer = Const (Just Info), poolsEngineTracer = Const (Just Info), poolsDbTracer = Const (Just Info), ntpClientTracer = Const (Just Info), networkTracer = Const (Just Info)}, loggingTracersDoc = Nothing}}
[cardano-wallet.application:Info:4] [2021-07-12 11:14:17.30 UTC] Wallet backend server starting. Using /home/thomasm/Cardano/cardano-node/node-ipc/mainnet/node.socket.
[cardano-wallet.application:Info:4] [2021-07-12 11:14:17.30 UTC] Node is Haskell Node on mainnet.
[cardano-wallet.token-metadata:Notice:4] [2021-07-12 11:14:17.30 UTC] No token metadata server is configured.
[cardano-wallet.token-metadata:Notice:4] [2021-07-12 11:14:17.30 UTC] No token metadata server is configured.
[cardano-wallet.token-metadata:Notice:4] [2021-07-12 11:14:17.30 UTC] No token metadata server is configured.
[cardano-wallet.token-metadata:Notice:4] [2021-07-12 11:14:17.30 UTC] No token metadata server is configured.
[cardano-wallet.main:Info:4] [2021-07-12 11:14:17.31 UTC] Wallet backend server listening on http://127.0.0.1:8090/
[cardano-wallet.pools-engine:Info:23] [2021-07-12 11:14:17.31 UTC] Chain following starting. Requesting intersection using 0 checkpoints
[cardano-wallet.network:Notice:13] [2021-07-12 11:14:17.55 UTC] Couldn't connect to node (x2). Retrying in a bit...
[cardano-wallet.network:Notice:15] [2021-07-12 11:14:17.55 UTC] Couldn't connect to node (x2). Retrying in a bit...
[cardano-wallet.network:Notice:26] [2021-07-12 11:14:17.56 UTC] Couldn't connect to node (x2). Retrying in a bit...
[cardano-wallet.network:Warning:13] [2021-07-12 11:14:17.81 UTC] Couldn't connect to node (x3). Retrying in a bit...
`
First i thought that maybe the socket-path is wrong, but i use the same path when starting DB-Sync and there it works without problems. A little confusing is, that even if i put a wrong socket-path i don't get any different output (apart of the path). It would be great that i get a message that no socket-path has been found or something similar.

Is there something else i miss or should do to make this work?
Thanks very much, 
Thomas

**Comment by piotr-iohk** [comment]
Hi, I believe you need to use https://docs.docker.com/storage/bind-mounts/ to access node.socket that is on your local system, e.g.:

```
$ docker run --network host --rm \
-v /path/to/your/node.socket/dir/on/local/system:/ipc \
inputoutput/cardano-wallet:2021.6.11 serve --port 8091 --node-socket /ipc/node.socket --mainnet
```

Have a look at our https://github.com/input-output-hk/cardano-wallet/blob/master/docker-compose.yml which provides cardano-walet and cardano-node docker containers with compatible versions. You can start wallet + node from there on mainnet too:

```
wget https://raw.githubusercontent.com/input-output-hk/cardano-wallet/master/docker-compose.yml
NETWORK=mainnet docker-compose up

```
