### ISSUE TITLE
Restoration benchmark fails (hp2pretty gets killed)

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#2771]
# Context

It seems to be happening since build 1018. All the restoration benchmarks (1018 - 1023) fail for that reason except for 1021 (which passes)
e.g.:

https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/1018#aac6e105-1322-4022-994f-157be5a4508c
https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/1023#0a4f701a-dc86-4782-9f67-647ce3e3573e

# Test Case

# Failure / Counter-example

```
[bench-restore:Notice:15] [2021-07-15 09:31:32.21 UTC] [cardano-node.35362] withBackend action done. Terminating child process
--
  | ./.buildkite/bench-restore.sh: line 42: 35403 Killed                  hp2pretty $artifact_name.hp
```
It seems that `hp2pretty` gets killed as line 42 is:
```
hp2pretty $artifact_name.hp
```

---

# Resolution 

---

# QA

**Comment by rvl** [comment]
It's probably using too much memory because there's so much data in the `.hp`!
