### ISSUE TITLE
Cardano wallet Killed no more information provided?

### ISSUE THREAD

**Issue by xptodevx** [cardano-foundation/cardano-wallet#2773]
# Context

I have a node running on test net using docker, I entered on its bash and wget cardano-wallet for ubuntu 64, extracted to my /usr/local/bin, when I execute cardano-wallet --help it shows only Killed as message, no more information provided.

## Essential Information

 - **Version**:      
 - **Platform**:     Mac OS M1 host dev environment running node 1.27.0 on docker
 - **Installation**:  Latest release downloaded
 - **Network**:      testnet

# Steps to Reproduce

Already explained above

## Expected behavior

Able to run cardano-wallet as documented.

## Actual behavior

Shows the message "Killed" on console.

---

# Resolution

---

# QA

**Comment by piotr-iohk** [comment]
> I have a node running on test net using docker, I entered on its bash and wget cardano-wallet for **ubuntu 64**, extracted to my /usr/local/bin, when I execute cardano-wallet --help it shows only Killed as message, no more information provided.

and

> Platform: Mac OS M1 host dev environment running node 1.27.0 on docker

If I understand correctly from your description you've downloaded cardano-wallet for Linux platform and trying to run it on MacOS platform? If so please try corresponding to your platform cardano-wallet release package i.e. cardano-wallet-v2021-06-11-macos64.tar.gz from latest [release](https://github.com/input-output-hk/cardano-wallet/releases/tag/v2021-06-1).

**Comment by xptodevx** [comment]
Hi, the cardano node is running in a docker container. I'll close this because I could manage to run this on a real server but for anybody else in a dev environment may experience this problem.
