### ISSUE TITLE
Shared Wallet API status

### ISSUE THREAD

**Issue by jordy25519** [cardano-foundation/cardano-wallet#2780]
Hi,

Wondering about the status of the Shared Wallet API.

It's reported in the docs as "unstable": https://input-output-hk.github.io/cardano-wallet/api/edge/#tag/Shared-Wallets
<img width="880" alt="Screen Shot 2021-07-29 at 15 28 37" src="https://user-images.githubusercontent.com/5133901/127427056-5aa96212-a7ad-457a-aee0-3ca45dd1cab5.png">

Is anything expected to change soon etc.

**Comment by rvl** [comment]
Yes @holygits we put shared wallets development on hold temporarily while we complete the work to support plutus application backend. We plan to add the final pieces of shared wallet support after that.
