### ISSUE TITLE
are cardano-node/cardano-cli executables suitable for setting a staking pool?

### ISSUE THREAD

**Issue by monkey-jsun** [cardano-foundation/cardano-wallet#2803]
So far I have been building those 2 binaries from source like [CoinCashew site](https://www.coincashew.com/coins/overview-ada/guide-how-to-build-a-haskell-stakepool-node) suggests.

I just notice that cardano-wallet binary package contain these 2 binaries as well.  I just wonder if they are suitable for setting up the staking pool so that I don't have to build myself.  Are they of any difference as described in CoinCashew site?

**Comment by rvl** [comment]
Hi @monkey-jsun - they should be suitable. The binaries are built with the default GHC optimization level, are fully statically linked, with symbols stripped. These builds are also included with Daedalus.

**Comment by monkey-jsun** [comment]
I went ahead and did a test on testnet.  Everything seems fine.  Let me close the issue.
