### ISSUE TITLE
Could not load module ‘System.Random.Internal’ when building from source using Cabal on MacOS

### ISSUE THREAD

**Issue by atx-barnes** [cardano-foundation/cardano-wallet#2824]
### Version

v2021-07-30

### Platform

macOS Catalina

### Installation method

Built from source

### Network configuration

mainnet

### Context

I've been following the Cardano developer documentation for building the cardano-wallet CLI but every time I try to build from source using cabal it throws this error shown below.

```
src/Cardano/Wallet/DB/Sqlite/Types.hs:122:1: error:
    Could not load module ‘System.Random.Internal’
    It is a member of the hidden package ‘random-1.2.0’.
    Perhaps you need to add ‘random’ to the build-depends in your .cabal file.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
    |
122 | import System.Random.Internal
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
cabal: Failed to build cardano-wallet-core-2021.7.30 (which is required by
exe:local-cluster from cardano-wallet-2021.7.30, test:integration from
cardano-wallet-2021.7.30 and others).
```

I've seen a couple of issues already that sort of relate to this issue but non of the proposed solutions fix the problem.

## Steps to Reproduce

1. Download the latest Cardano node 1.28.0
2. Follow this documentation https://developers.cardano.org/docs/get-started/installing-cardano-wallet on macOS for building the Cardano Wallet from source using cabal.

### Expected behavior

Build from source successfully.

### Actual behavior

Throws Could not load module ‘System.Random.Internal’ when running `cabal build all`

**Comment by rvl** [comment]
Hi @atx-barnes, thanks for reporting.
It seems like those instructions are wrong.

We will get them corrected, but in the mean time, the command to build cardano-wallet with Cabal is simply:
```
cabal build all -frelease
```
If you have previously run `cabal configure` or `cabal build` with the wrong flags, then remove `cabal.project.local` beforehand.

**Comment by torphix** [comment]
@rvl 
Hi I had the same problem once I removed  cabal.project.local and run cabal build all -frelease it returns Cannot find the program 'ghc'. User-specified path 'ghc-8.10.5' 
Thank you

**Comment by Im0** [comment]
@henry8th out of interest, what version of ghc do you have installed? `ghc --version`

**Comment by Im0** [comment]
@rvl after running into the same issue (Ubuntu 20.04) I ran the following:

```
  379  rm cabal.project.local
  380  cabal build all -frelease
  382  cabal configure --with-compiler=ghc-8.10.7 --constraint="random<1.2"
  383  cabal build all -frelease

```

But that also returned:

```
Building library for cardano-wallet-core-2021.9.9..
[59 of 95] Compiling Cardano.Wallet.DB.Sqlite.Types ( src/Cardano/Wallet/DB/Sqlite/Types.hs, /home/cardano/cardano-src/cardano-wallet/dist-newstyle/build/x86_64-linux/ghc-8.10.7/cardano-wallet-core-2021.9.9/build/Cardano/Wallet/DB/Sqlite/Types.o, /home/cardano/cardano-src/cardano-wallet/dist-newstyle/build/x86_64-linux/ghc-8.10.7/cardano-wallet-core-2021.9.9/build/Cardano/Wallet/DB/Sqlite/Types.dyn_o )

src/Cardano/Wallet/DB/Sqlite/Types.hs:122:1: error:
    Could not load module ‘System.Random.Internal’
    It is a member of the hidden package ‘random-1.2.0’.
    Perhaps you need to add ‘random’ to the build-depends in your .cabal file.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
    |
122 | import System.Random.Internal
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
cabal: Failed to build cardano-wallet-core-2021.9.9 (which is required by
exe:local-cluster from cardano-wallet-2021.9.9, test:integration from
cardano-wallet-2021.9.9 and others).

```

Essentially I've ran:
```
  372  git clone https://github.com/input-output-hk/cardano-wallet.git
  373  cd cardano-wallet
  374  git fetch --all --recurse-submodules --tags
  375  git checkout tags/v2021-09-09
  376  cabal configure --with-compiler=ghc-8.10.7 --constraint="random<1.2"
  378  cabal build all -frelease
```

**Comment by torphix** [comment]
Hi thanks for your reply I fixed it by removing --constraint=random<1.2
from cabal configure

**Comment by Im0** [comment]
@henry8th nice one, thank you for that!  Worked a treat for me too.

**Comment by HeinrichApfelmus** [comment]
Closing as this is probably out of date by now. Feel free to reopen if this or a similar issue persists.
