### ISSUE TITLE
[cardano-wallet.network:Warning:15] [  UTC] Couldn't connect to node . Retrying in a bit...

### ISSUE THREAD

**Issue by Yatsei** [cardano-foundation/cardano-wallet#2828]
### Just checking...

- [X] This is a `cardano-wallet` bug.
- [X] I am using the latest `cardano-wallet` release.
- [X] I am using the *correct* `cardano-node` version for that release of `cardano-wallet`.

### Version

2021.8.11

### Platform

Ubuntu

### Installation method

IOHK Docker image

### Network configuration

mainnet

### Context

When I installed cardano-wallet with :
wget https://raw.githubusercontent.com/input-output-hk/cardano-wallet/master/docker-compose.yml
NETWORK=mainnet docker-compose up

At the beginning it installed well and everything was working with the API.
After a while I started getting this message and the server was not responding correctly anymore:
[](url) 
![walle](https://user-images.githubusercontent.com/89045237/129628263-43123ee4-7984-4e32-861f-225350201ef2.png)

The blockchain is downloaded, and everything was working normally until this came.
I get this message when I try to go to wallets/id : 

My associated worker for id.............. is no longer responding. This is not something that is supposed to happen. The worker must have left a trace in the logs of severity Error when it died which might explain the cause. Said differently, this wallet won't be accessible until the server is restarted but there are good chances it'll recover itself upon restart

I am able to see the sync progress on the network page on the browser
Tried a fresh install on a new os Ubuntu, same.
Ubuntu 20, 6gb Ram
Tried to leave it for hours, restart...

### Description

Install all the dependencies, docker
run 
wget https://raw.githubusercontent.com/input-output-hk/cardano-wallet/master/docker-compose.yml
NETWORK=mainnet docker-compose up

**Comment by rvl** [comment]
Hi, thanks for the report. This message usually means that the `cardano-node` process which provides the socket file `/ipc/node.socket` is not running. You should be able to use docker or docker-compose to check the status and logs of the `cardano-node` service.

**Comment by Yatsei** [comment]
> Hi, thanks for the report. This message usually means that the `cardano-node` process which provides the socket file `/ipc/node.socket` is not running. You should be able to use docker or docker-compose to check the status and logs of the `cardano-node` service.

Ok when I check my logs I see :
Named volume "node--db:/data:rw" is used in service "cardano-node" but no declaration was found in the volumes section.

It seems that the node is running but something else is wrong.

**Comment by piotr-iohk** [comment]
```
Named volume "node--db:/data:rw" is used in service "cardano-node" but no declaration was found in the volumes section.
```
This message is from docker, not cardano-wallet or cardano-node. It appears e.g. when you do not set NETWORK env variable when starting docker compose.

Your description and cardano-wallet logs you shared suggest that cardano-node crashed/stopped working at some point and cardano-wallet couldn't connect to it any longer as @rvl mentioned. (hard to tell what happend without the node logs)

Perhaps stopping and restarting docker-compose gracefully might help?
```
NETWORK=mainnet docker-compose down
NETWORK=mainnet docker-compose up
```
or killing some orphaned docker processes you may have running in the background (`docker ps` to check)?

**Comment by Yatsei** [comment]
> ```
> Named volume "node--db:/data:rw" is used in service "cardano-node" but no declaration was found in the volumes section.
> ```
> 
> This message is from docker, not cardano-wallet or cardano-node. It appears e.g. when you do not set NETWORK env variable when starting docker compose.
> 
> Your description and cardano-wallet logs you shared suggest that cardano-node crashed/stopped working at some point and cardano-wallet couldn't connect to it any longer as @rvl mentioned. (hard to tell what happend without the node logs)
> 
> Perhaps stopping and restarting docker-compose gracefully might help?
> 
> ```
> NETWORK=mainnet docker-compose down
> NETWORK=mainnet docker-compose up
> ```
> 
> or killing some orphaned docker processes you may have running in the background (`docker ps` to check)?

Tried to install everything again from scratch, tell me if I did anything wrong:
sudo apt-get update
sudo apt-get install automake build-essential pkg-config libffi-dev libgmp-dev libssl-dev libtinfo-dev libsystemd-dev zlib1g-dev make g++ tmux git jq wget libncursesw5 libtool autoconf -y


sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release

sudo apt-get install build-essential curl libffi-dev libffi7 libgmp-dev libgmp10 libncurses-dev libncurses5 libtinfo5
curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
reboot

ghcup --version

ghcup install ghc 8.10.4
ghcup set ghc 8.10.4

ghc --version
cabal --version
cabal-install version 3.4.0.0

sudo apt-get update
sudo apt install docker.io docker-compose

wget https://raw.githubusercontent.com/input-output-hk/cardano-wallet/master/docker-compose.yml
NETWORK=mainnet docker-compose up


6GB RAM 4 core

**Comment by piotr-iohk** [comment]
For starting our docker-compose only having docker and docker-compose should be enough.

**Comment by Yatsei** [comment]
The problem still not solved even with a new fresh install. Is it may be because I have to make the volume shared or does the script already makes it.

**Comment by piotr-iohk** [comment]
I'm not sure what might be the problem. I suspect the node stopping and now cannot recover somehow. Is it possible that you share logs from cardano-node?

One option to recover might be also to clean-up your docker volumes/images/processes and try starting docker-compose again. (But pls note that you will need to restore the whole blockchain from scratch)

This should clean up all of what you have, but you my want to limit only to cardano-node / cardano-wallet...
```
docker rm -f $(docker ps -a -q)
docker volume rm -f $(docker volume ls -q)
docker image rm -f $(docker image ls -q)

NETWORK=mainnet docker-compose up
```

**Comment by Yatsei** [comment]
> I'm not sure what might be the problem. I suspect the node stopping and now cannot recover somehow. Is it possible that you share logs from cardano-node?
> 
> One option to recover might be also to clean-up your docker volumes/images/processes and try starting docker-compose again. (But pls note that you will need to restore the whole blockchain from scratch)
> 
> This should clean up all of what you have, but you my want to limit only to cardano-node / cardano-wallet...
> 
> ```
> docker rm -f $(docker ps -a -q)
> docker volume rm -f $(docker volume ls -q)
> docker image rm -f $(docker image ls -q)
> 
> NETWORK=mainnet docker-compose up
> ```

This is what I get when I check the logs : 
ERROR: Named volume "node--db:/data:rw" is used in service "cardano-node" but no declaration was found in the volumes section.

The node is running, tried a fresh install and still the same result. Is it built for ubuntu 20.4?

**Comment by piotr-iohk** [comment]
> ERROR: Named volume "node--db:/data:rw" is used in service "cardano-node" but no declaration was found in the volumes section.

This suggests that NETWORK env variable is somehow not picked up by docker :thinking: ...

> Is it built for ubuntu 20.4?

Yes, it works on Ubuntu 20.04 for me.

Can you follow those steps please?

0. `wget https://raw.githubusercontent.com/input-output-hk/cardano-wallet/master/docker-compose.yml`
1. Start `NETWORK=mainnet docker-compose up` (do you see some logs from node and wallet here after starting the command?)
2. Check running containers with `docker ps`, I have something like this:
```
CONTAINER ID        IMAGE                                          COMMAND                  CREATED             STATUS              PORTS                    NAMES
81f13e2cf2e2        inputoutput/cardano-node:alonzo-purple-1.0.1   "entrypoint"             2 minutes ago       Up 2 minutes                                 cardano-wallet_cardano-node_1
cbfbc639e432        inputoutput/cardano-wallet:2021.8.11           "bash -c ' ([[ $NETW…"   2 minutes ago       Up About a minute   0.0.0.0:8090->8090/tcp   cardano-wallet_cardano-wallet_1
```
3. Then look-up logs for cardano-node container, e.g. `docker logs -f  81f13e2cf2e2`
In my case I see cardano-node logs:
```
[8596e314:cardano.node.ChainDB:Notice:34] [2021-08-18 16:35:52.76 UTC] Chain extended, new tip: 744e2e79ed97d34dbdc8e3325bf79cf3ef111cb8ec8ace9faae0bf1edc521cb4 at slot 25297
[8596e314:cardano.node.ChainDB:Notice:34] [2021-08-18 16:35:54.01 UTC] Chain extended, new tip: 95fad99fdf46879aec1f361754e6fd6308ecf3f24792a1c79f80775b92bd608a at slot 27160
...
```

**Comment by piotr-iohk** [comment]
Cannot reproduce.
