### ISSUE TITLE
All transactions through /v2/proxy/transactions are failing

### ISSUE THREAD

**Issue by xdzurman** [cardano-foundation/cardano-wallet#2845]
### Just checking...

- [X] This is a `cardano-wallet` bug.
- [X] I am using the latest `cardano-wallet` release.

### Version

dev-master

### Platform

Ubuntu 20.04

### Installation method

IOHK Docker image

### Network configuration

alonzo-purple

### Context

cardano-node 1.29.0-rc2

## Steps to Reproduce

1. create a valid transaction successfully submittable by cardano-cli (+cardano node)
2. execute `curl --header "Content-Type: application/octet-stream" -X POST --data-binary "@txCborHex" http://localhost:8201/v2/proxy/transactions`
...

### Expected behavior

The transaction is successfully submitted.

### Actual behavior

{"code":"unexpected_error","message":"This endpoint is not supported by the backend currently in use. Please try a different backend."}

**Comment by piotr-iohk** [comment]
Thanks for reporting!

I'm able to reproduce also with cardano-wallet master and cardano-node 1.29.0-rc3.
Jira ticket: https://jira.iohk.io/browse/ADP-1094

**Comment by piotr-iohk** [comment]
Issue should be fixed now in master.
