### ISSUE TITLE
Wallet returns error: "not enough money" after 3 successful txs, when making several txs in immediate succession

### ISSUE THREAD

**Issue by rumourscape** [cardano-foundation/cardano-wallet#2865]
### Just checking...

- [X] This is a `cardano-wallet` bug.
- [X] I am using the latest `cardano-wallet` release.
- [X] I am using the *correct* `cardano-node` version for that release of `cardano-wallet`.

### Version

2021.4.8 (git revision: b0701a9c1a59d766e9f611160235a196b016b336)

### Platform

WSL Linux-Ubuntu 20.04

### Installation method

Binary from GitHub release page

### Network configuration

Testnet

## Steps to Reproduce

1. Send multiple successive txs to http://localhost:8090/v2/wallets/{walletId}/transactions via python script
2. payload has withdrawal: "self"
3. The 4th tx will return "not enough money" error
...

### Expected behavior
Execute all txs

### Actual behavior
4th tx returns error, rest aren't executed

**Comment by piotr-iohk** [comment]
The error "not enough money" indicates that there is not enough available balance on the wallet to create a transaction.

When you submit a transaction, it is first in "pending" status until it is accepted by the node. While tx is in "pending" status all the utxos that are used in this transaction are blocked such that they cannot be used in another transaction at the same time (this is to prevent double spending and is expected). Hence you created 3 transactions one after another and you get error on the 4th, there is a good chance that your previous transactions are simply still in "pending" status and, therefore, blocking the Utxo of the wallet. 
(The status of tx can be monitored via https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/getTransaction)

I believe you need to wait until your previous transactions status is "in_ledger" before creating the next one.

**Comment by rumourscape** [comment]
Understood! Thanks for the help. I guess I should just create more Utxos to avoid this problem.
