### ISSUE TITLE
Flaky test: restoration benchmarks time out on "Fetching tip failed, retrying"

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#2872]
### Please ensure:

- [X] This is actually a flaky test already present in the code and not caused by your PR.

### Context

Nightly benchmark is failing due to:
```
[bench-restore:Warning:15] [2021-09-07 00:31:29.68 UTC] Fetching tip failed, retrying in 15000ms
```
There is 120 min timeout for fetching the tip, but it fails within this timeout.

In `piotr/restoration-benchmark-tip` I have changed timeout to 240 mins but it was still failing. (cd24e3a57ea460e4f406437f66a026c70a42c985)

On the same branch I've changed the home dir (aa2618e057c4c2fa90e8c6234b5b1eb6e3e57fa2) which caused benchmark to work, still it didn't manage to finish withing 10h... (https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/1082)

### Job name

Restore benchmark - cardano mainnet

### Error message

```shell
[bench-restore:Warning:15] [2021-09-07 00:31:29.68 UTC] Fetching tip failed, retrying in 15000ms
[bench-restore:Warning:15] [2021-09-07 00:31:44.68 UTC] Fetching tip failed, retrying in 15000ms
[bench-restore:Warning:15] [2021-09-07 00:31:59.68 UTC] Fetching tip failed, retrying in 15000ms
[bench-restore:Warning:15] [2021-09-07 00:32:14.68 UTC] Fetching tip failed, retrying in 15000ms
[bench-restore:Warning:15] [2021-09-07 00:32:29.69 UTC] Fetching tip failed, retrying in 15000ms
```

### Build link

https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/1083#9908ce84-ad9b-4429-afa2-fd6dcd3f9d65

**Comment by Anviking** [comment]
This should be stale, closing.
