### ISSUE TITLE
Shuffle statistical tests sometimes fail ... 

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#291]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Windows & OSX & Linux) | Code  |

# Context
 
 

We use statistical tests to verify that our shuffle function does a fair job at .. shuffling:

https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Cardano/Wallet/Primitive/CoinSelectionSpec.hs#L77-L83

However, sometimes, quickcheck fails to verify the property and simply give up early trying to shuffle a list that isn't much shuffled. 

# Steps to Reproduce

1. Run the test many times

## Expected behavior

The test should NEVER fail

## Actual behavior
 
<A clear and concise description of what you observe instead. If applicable add screenshots to help explain your problem.>

It fails eventually, once in a while

---

# Resolution Plan

- [ ] ~~Try constraining the length of the list to a minimum. The properties are formulated with "non-trivial" lists in mind, so using it on empty list or singleton doesn't really help our cause here.~~

- [x] Removed the precondition on the list length `length xs > 1 ==> ...`; it appears that quickcheck generates quite a few empty lists which made the `checkCoverage` really hard to satisfy in practice as it will give up after only a few cases. Instead, using a proper generator to generate `NonEmptyList` solved the issue nicely. 

# PR

| Number   | Base      |
| ---      | ---       |
| #295         | `develop` |

# QA 

- Re-run the tests locally a thousand times each without observing any failure (was occurring more than 1 every 50 tests before that). So I believe this is now fixed.

- Also no failure in CI about this since the fix was merged.

**Comment by piotr-iohk** [comment]
:+1:
