### ISSUE TITLE
How to get public key (xpub) for a test wallet address?

### ISSUE THREAD

**Issue by v0d1ch** [cardano-foundation/cardano-wallet#2913]
### The problem that you wish to solve

Have an easy way of obtaining wallet public key suitable for use in cardano-wallet api

### Description

Cardano wallet api docs mention possibility of restoring a wallet using public key (`account_public_key`). 

This feature works nicely if I use the public key found in my Yoroi wallet, however I couldn't find useful resources on how to obtain public key for a test wallet generated with cardano-cli

```
$CARDANO_CLI address build --payment-verification-key-file main.vkey --out-file main.addr --testnet-magic $TESTNET_MAGIC_NUM
```

**Comment by v0d1ch** [comment]
I see there is https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/getAccountKey but I need to have a `walletId` for that to work. It is a bit like a chicken/egg problem where I need to have public key in order to get a `walletId` but if I don't have a public key and want to obtain one I need a `walletId`. Might also easily be I missed something while browsing the docs.

**Comment by HeinrichApfelmus** [comment]
I'm not entirely sure what you are asking:

* Given an `account_public_key`, you can `POST` `/wallets` to create a wallet. Its `walletId` will be returned in the response.
* Given a `walletId`, you can `GET` `/wallets/{walletId}/keys` to retrieve its account public key.

Note that an *address*, e.g. such as the one you've created with `cardano-cli`, is actually the hash of a public key, and cannot be used as an account public key.

Closing as outdated. Feel free to reopen if the question persists.
