### ISSUE TITLE
wallet

### ISSUE THREAD

**Issue by zhangtiantian222** [cardano-foundation/cardano-wallet#294]
Launched a Daedalus purse, but there is no port 8090, how to configure with this portubuntu 18.04 | Launched a Daedalus purse, but there is no port 8090, how to configure with this portubuntu 18.04
-- | --
Launched a Daedalus purse, but there is no port 8090, how to configure with this portubuntu 18.04

**Comment by zhangtiantian222** [comment]
![TIM截图20190521113914](https://user-images.githubusercontent.com/38236278/58080386-b3749500-7be5-11e9-8980-657aa96bc01b.png)

**Comment by KtorZ** [comment]
Hello :) 
I don't think you're in the right place here or, I am missing some context from your issue. 

If you have trouble using Deadalus, please refer to the [support portal](https://iohk.zendesk.com/hc/en-us/categories/360000877653-Daedalus-wallet-mainnet) which contains quite some troubleshooting information. If needed, you can always submit a ticket to the support team to have them help you.

If you are indeed willing to use wallet **backend** API as a service, **note that this repository is still under heavy work and not complete**. Among other things, this project isn't _yet_ integrated with Daedalus. You may still try the API using one of our pre-compiled binaries on the [release page](https://github.com/input-output-hk/cardano-wallet/releases) or try compiling from sources following the instructions on our [README](https://github.com/input-output-hk/cardano-wallet#how-to-build).

Thanks for your interest! 

Edit: I welcome you to open a BUG ticket for any issues you'd experience, if any.
