### ISSUE TITLE
(Instance of #2855) Flaky test: `/CLI Specifications/SHELLEY_CLI_TRANSACTIONS/TRANS_CREATE_06`

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#2980]
### Please ensure:

- [X] This is actually a flaky test already present in the code and not caused by your PR.

### Context

https://github.com/input-output-hk/cardano-wallet/pull/2979#issuecomment-947445721

### Job name

https://buildkite.com/input-output-hk/cardano-wallet/builds/17337#162299be-70ce-4613-a1fb-9f9193c13795

### Test case name(s)

/CLI Specifications/SHELLEY_CLI_TRANSACTIONS/TRANS_CREATE_06

### Error message

```shell
Failures:
 
  src/Test/Integration/Scenario/CLI/Shelley/Transactions.hs:243:59: 
  1) CLI Specifications, SHELLEY_CLI_TRANSACTIONS, TRANS_CREATE_06 - Invalid amount, string with wildcards
       uncaught exception: IOException of type ResourceVanished
       fd:131: hFlush: resource vanished (Broken pipe)
 
  To rerun use: --match "/CLI Specifications/SHELLEY_CLI_TRANSACTIONS/TRANS_CREATE_06 - Invalid amount/string with wildcards/"
 
Randomized with seed 1642389836
 
Finished in 881.4515 seconds, used 943.6028 seconds of CPU time
871 examples, 1 failure, 45 pending
```

### Build link

https://buildkite.com/input-output-hk/cardano-wallet/builds/17337#162299be-70ce-4613-a1fb-9f9193c13795

**Comment by Anviking** [comment]
Thanks. Closing and tracking as #2855.
