### ISSUE TITLE
wallet is not accessible and database Issue after upgrading from v2019-09-09 to v2019-09-29

### ISSUE THREAD

**Issue by wspi** [cardano-foundation/cardano-wallet#2984]
### Just checking...

- [X] This is a `cardano-wallet` bug.
- [X] I am using the latest `cardano-wallet` release.
- [X] I am using the *correct* `cardano-node` version for that release of `cardano-wallet`.

### Version

v2021-09-29 (git revision: 6626489542ce442a8451fb46fb5339346e62b4ee)

### Platform

Linux 4.18.0-147.8.1.el8_1.x86_64 #1 SMP Thu Apr 9 13:49:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Installation method

Binary from GitHub release page

### Network configuration

mainnet

### Context

I was running cardano-wallet v2021-09-09 (git revision: 011a258c1b5ba57ca70f13346109ce3074820032) and upgraded to v2021-09-29 (git revision: 6626489542ce442a8451fb46fb5339346e62b4ee) but one of my wallets was not accessible

When trying to get a transaction of a wallet I got this error:
`{"code":"wallet_not_responding","message":"That's embarrassing. My associated worker for WALLET_ID is no longer responding. This is not something that is supposed to happen. The worker must have left a trace in the logs of severity 'Error' when it died which might explain the cause. Said differently, this wallet won't be accessible until the server is restarted but there are good chances it'll recover itself upon restart."}`

in the logs I've found this:
`cardano-wallet.wallet-engine:Error:85]#033[0m [2021-10-20 18:53:08.54 UTC] Worker has exited: Unhandled exception: user error (Couldn't parse field `localTxSubmissionTx` from table `local_tx_submission`. DecoderErrorDeserialiseFailure "Shelley Tx" (DeserialiseFailure 0 "expected list len or indef"))`

I've tried restarting the node and it didn't solve the issue.

after rolling back to the v2021-09-09 (git revision: 011a258c1b5ba57ca70f13346109ce3074820032) it started to work again

## Steps to Reproduce

1. create more than one shelley wallet using cardano-wallet v2021-09-09 and cardano-node 1.29.0
2. upgrade cardano-node and cardano-wallet
3. try to get a tx from the wallets

### Expected behavior

get a tx from every wallet that has been created

### Actual behavior

one of the wallets is not accessible

**Comment by HeinrichApfelmus** [comment]
The error message from the logs suggests that something is wrong with the `local_tx_submission` table in the database. It seems very likely that the serialization format for transactions changed between wallet versions and the table was not migrated automatically (that's a bug in the wallet). Fortunately, the `local_tx_submission` table stores temporary data only — transactions that have been submitted to the node, but did not yet make it to the blockchain.

Likely solutions:
* You can stop the wallet process, delete the `local_tx_submission` table, and start the process again.
* If you don't feel like fiddling with the database yourself, you can stop the wallet process, delete the `she${WalletId}.sqlite` file entirely (where `WalletId` is the alphanumeric ID of your wallet), and start the wallet process again. However, in this case, you will have to restore the wallet from the mnemonic / passphrase.

**Comment by piotr-iohk** [comment]
Thanks for reporting. Created Jira ticket to track the migration issue -> ADP-1224.
It seems that issue is happening only when there are pending transactions on the wallet. Another workaround then would be to make sure all transactions are in ledger before migrating from `v2021-09-09` to `v2021-09-29`.

**Comment by wspi** [comment]
We've tried to upgrade again now making sure all recent transactions were in ledger, and it went smooth, thanks for the help

**Comment by DreamHackchosenone** [comment]
> We've tried to upgrade again now making sure all recent transactions were in ledger, and it went smooth, thanks for the help

How did you solve it？delete the local_tx_submission table？

**Comment by khelle** [comment]
Can someone describe how can I delete the `local_tx_submission` from `she${WalletId}.sqlite` step-by-step?

When I try to open it using sqlite:
```
sqlite she${WalletId}.sqlite
```

I get response
```
Unable to open database "she${WalletId}.sqlite": file is encrypted or is not a database
```

Of course I did replace the template with the actual file name

**Comment by wspi** [comment]
> > We've tried to upgrade again now making sure all recent transactions were in ledger, and it went smooth, thanks for the help
> 
> How did you solve it？delete the local_tx_submission table？

before upgrading, we've listed the recent transactions of every wallet we have and checked if all were "in ledger" that being true, we've stopped cardano-wallet and cardano-node, upgraded both, and started again

**Comment by DreamHackchosenone** [comment]
> > > We've tried to upgrade again now making sure all recent transactions were in ledger, and it went smooth, thanks for the help
> > 
> > 
> > How did you solve it？delete the local_tx_submission table？
> 
> before upgrading, we've listed the recent transactions of every wallet we have and checked if all were "in ledger" that being true, we've stopped cardano-wallet and cardano-node, upgraded both, and started again

Thanks, i recover wallet from mnemonic

**Comment by LovelaceAdmin** [comment]
> > > > We've tried to upgrade again now making sure all recent transactions were in ledger, and it went smooth, thanks for the help
> 
> > > 
> 
> > > 
> 
> > > How did you solve it？delete the local_tx_submission table？
> 
> > 
> 
> > before upgrading, we've listed the recent transactions of every wallet we have and checked if all were "in ledger" that being true, we've stopped cardano-wallet and cardano-node, upgraded both, and started again
> 
> 
> 
> Thanks, i recover wallet from mnemonic

Hello user
PM and explain your wallet difficulties.
