### ISSUE TITLE
Worker has exited: Unhandled exception

### ISSUE THREAD

**Issue by khelle** [cardano-foundation/cardano-wallet#2994]
### Just checking...

- [X] This is a `cardano-wallet` bug.
- [X] I am using the latest `cardano-wallet` release.
- [X] I am using the *correct* `cardano-node` version for that release of `cardano-wallet`.

### Version

v2021-09-29 (git revision: 6626489542ce442a8451fb46fb5339346e62b4ee)

### Platform

Ubuntu 16.04

### Installation method

Binary from GitHub release page

### Network configuration

mainnet

### Context

The bug only apparead after I upgraded my 1.29 install (which worked fine) to the newest 1.30 one. The update included cardano-node, cardano-db-sync and cardano-wallet

### Description

Hello, I am using:

```
cardano-node 1.30.1
cardano-wallet v2021-09-29 (the one compatible with 1.30.1)
cardano-db-sync-extended 11.0.4
```

cardano-node and cardano-db-sync-extended seems to work correctly, however when I run cardano-wallet I get following error:

```
Oct 29 14:46:17 cardano-wallet[10265]: [cardano-wallet.wallet-engine:Error:30] [2021-10-29 14:46:17.46 UTC] bfbcec28: Processing the pending local tx submission pool: exception: user error (Couldn't parse field `localTxSubmissionTx` from table `local_tx_submission`. DecoderErrorDeserialiseFailure "Shelley Tx" (DeserialiseFailure 0 "expected list len or indef"))
Oct 29 14:46:17 cardano-wallet[10265]: [cardano-wallet.wallet-db:Info:31] [2021-10-29 14:46:17.48 UTC] Closing single database connection (/home/ada/db-wallet/she.bfbcec28fb8c3225bb4c6913652660d36809b922.sqlite)
Oct 29 14:46:17 cardano-wallet[10265]: [cardano-wallet.wallet-db:Info:23] [2021-10-29 14:46:17.65 UTC] Stopping database connection pool /home/ada/db-wallet/she.bfbcec28fb8c3225bb4c6913652660d36809b922.sqlite
Oct 29 14:46:17 cardano-wallet[10265]: [cardano-wallet.wallet-engine:Error:23] [2021-10-29 14:46:17.65 UTC] Worker has exited: Unhandled exception: user error (Couldn't parse field `localTxSubmissionTx` from table `local_tx_submission`. DecoderErrorDeserialiseFailure "Shelley Tx" (DeserialiseFailure 0 "expected list len or indef"))
Oct 29 14:46:40 cardano-wallet[10265]: [cardano-wallet.pools-engine:Notice:45] [2021-10-29 14:46:40.91 UTC] In sync. Applied 38 blocks, 0 rollbacks in the last 30.000948484s. Currently at slot 43952507.
Oct 29 14:51:40 cardano-wallet[10265]: [cardano-wallet.pools-engine:Info:45] [2021-10-29 14:51:40.91 UTC] Still in sync. Applied 20 blocks, 0 rollbacks in the last 300.000706893s. Currently at slot 43952807.
Oct 29 14:56:40 cardano-wallet[10265]: [cardano-wallet.pools-engine:Info:45] [2021-10-29 14:56:40.92 UTC] Still in sync. Applied 13 blocks, 0 rollbacks in the last 300.003721634s. Currently at slot 43953078.
```

As you can see, just after start of the node it throws some connection issues, kills worker and afterwards even though being active, it cannot push any transactions as the worker is dead. The problem started after I migrated everything to newest versions, previously I was running 1.29 and 1.29-compatible wallet and everything was fine.

To run services I am using following commands:

cardano-node
```
/home/ada/cardano-node/cardano-node run --topology /home/ada/config/mainnet-topology.json --database-path /home/ada/db --socket-path /home/ada/db/node.socket --host-addr 0.0.0.0 --port 3001 --config /home/ada/config/mainnet-config.json
```

cardano-db-sync
```
/home/ada/cardano-db-sync/db-sync-node/bin/cardano-db-sync-extended --config /home/ada/cardano-db-sync/config/mainnet-config.yaml --socket-path /home/ada/db/node.socket --state-dir /home/ada/ledger-state/mainnet --schema-dir /home/ada/cardano-db-sync/schema
```

cardano-wallet
```
/home/ada/cardano-wallet/cardano-wallet serve --mainnet --node-socket /home/ada/db/node.socket --database /home/ada/db-wallet --listen-address 0.0.0.0 --port 12018
```

What am I doing wrong? Has something changed in 1.30 release that I missed? How can I solve this problem?

**Comment by piotr-iohk** [comment]
Thanks for reporting! This seems to be the same issue as https://github.com/input-output-hk/cardano-wallet/issues/2984.
Possible workarounds:
 - https://github.com/input-output-hk/cardano-wallet/issues/2984#issuecomment-948383550
 - https://github.com/input-output-hk/cardano-wallet/issues/2984#issuecomment-948413202

**Comment by khelle** [comment]
Thank you @piotr-iohk , I posted my next question in the topic you provided but seems it has been closed so I will repeat my quetion here in regards to that topic as the author:

Can someone describe how can I delete the local_tx_submission from she${WalletId}.sqlite step-by-step?

When I try to open it using sqlite:

sqlite she${WalletId}.sqlite
I get response

Unable to open database "she${WalletId}.sqlite": file is encrypted or is not a database
Of course I did replace the template with the actual file name

**Comment by piotr-iohk** [comment]
@khelle you may use https://sqlitebrowser.org/ to open the db and delete `local_tx_submission` table.

**Comment by khelle** [comment]
Ok, the method with deleting the `local_tx_submission` table worked. Everything seems to work correctly now, thank you.

Just for future reference - on Ubuntu you should use `sqlite3` instead of `sqlite`. That's why I had problems with opening the db file.
