### ISSUE TITLE
Create a cardano-wallet-api package containing servant API and Client

### ISSUE THREAD

**Issue by marijanp** [cardano-foundation/cardano-wallet#3005]
### The problem that you wish to solve

I'm developing a haskell application which I want to interact with the HTTP server of cardano wallet.

Instead of regenerating/ rewriting the servant API definitions using swagger-codegen it would make more sense to use the already existing definitions in [API.hs](https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/src/Cardano/Wallet/Api.hs) and [Client.hs](https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/src/Cardano/Wallet/Api/Client.hs)

### Description

Create a cardano-wallet-client package and additionally make it available on hackage.

### Ticket

ADP-1264

**Comment by rvl** [comment]
Thanks, yes this is a good idea.

I have opened ADP-1264 and added it to our wish list.

**Comment by HeinrichApfelmus** [comment]
@Unisay I think we made some progress in that direction — what is the current status?

**Comment by Unisay** [comment]
> @Unisay I think we made some progress in that direction — what is the current status?

My goal was to generate a Haskell client application from the Wallet's OpenAPI spec. The repo is [here](https://github.com/Unisay/cardano-wallet-client). 

The author of this PR says "it would make more sense to use the already existing [Servant] definitions". We consider Servant API description an implementation detail, while OpenAPI spec is a public contract.

**Comment by marijanp** [comment]
So you expect me to re-generate the exact same servant definitions when I already use servant? It may be a implementation detail that you use servant, but servant api definitions are 1:1 to the OpenAPI spec. So instead of pulling in a dependency which is a versioned source of truth I have to impurely re-generate the definitions and keep track of changes manually.
