### ISSUE TITLE
Create a cardano wallet without showing passphrase.

### ISSUE THREAD

**Issue by bremengnaht** [cardano-foundation/cardano-wallet#3009]
### The problem that you wish to solve

For some reason, i want to create a wallet for one time use only. 

### Description

And i really don't want to CLI give me the passphrase (for security reason).

### Implementation suggestions

Add an option on API to let user can decide to receive passphrase or not

**Comment by piotr-iohk** [comment]
>And i really don't want to CLI give me the passphrase (for security reason).

Can you clarify what that means? CLI doesn't give you the passphrase... you have to provide one when creating a wallet and that's because of security reasons, because you need to provide passphrase to spend from the wallet later.

**Comment by bremengnaht** [comment]
Sorry, that is my misunderstanding. Close Ticket

**Comment by LovelaceAdmin** [comment]
> Sorry, that is my misunderstanding. Close Ticket

Hello user 
PM and explain your difficulties for solutions.
