### ISSUE TITLE
How to convert a 12-digit mnemonic phrase into 15 or more？

### ISSUE THREAD

**Issue by Alteryy** [cardano-foundation/cardano-wallet#3015]
### Just checking...

- [X] This is a `cardano-wallet` bug.
- [X] I am using the latest `cardano-wallet` release.
- [X] I am using the *correct* `cardano-node` version for that release of `cardano-wallet`.

### Version

cardano-wallet-v2021-09-29

### Platform

ubuntu

### Installation method

Binary from GitHub release page

### Description

I only have 12-digit mnemonic words. When I use wallet create from-recovery-phrase to restore the wallet, it prompts that more than 15-digit mnemonics are needed. How can I solve this?

**Comment by piotr-iohk** [comment]
Using cardano-wallet CLI you can only create Shelley type wallet. Shelley wallets can be created with 15, 18, 21 or 24 words mnemonic phrase only. There is no way to convert 12-word recovery phrase to 15-word or more. However you can generate new mnemonic phrase with:

 - cardano-wallet CLI (`$ cardano-wallet recovery-phrase generate --help`)
 - external library implementing [BIP39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#Reference_Implementation)
 - external service like https://iancoleman.io/bip39/

If your 12-word mnemonic phrase belongs to already existing wallet, then it is most probably a Byron wallet. You can restore this wallet using cardano-wallet API -> https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/postByronWallet

**Comment by Alteryy** [comment]
Hi,
I have restored my wallet with postbyronwallet, but this method is deprecated at present. 
What is the risk if I keep 12 mnemonics all the time,Will my 12 bit mnemonics not be restored to my wallet one day and What should I do?

**Comment by LovelaceAdmin** [comment]
Hello user. 
PM me and explain your issues.

**Comment by LovelaceAdmin** [comment]
>  Hi,
> 
> I have restored my wallet with postbyronwallet, but this method is deprecated at present. 
> 
> What is the risk if I keep 12 mnemonics all the time,Will my 12 bit mnemonics not be restored to my wallet one day and What should I do? 
Hello user.
PM me and explain your issues.

**Comment by Alteryy** [comment]
I have restored my wallet with postbyronwallet, but this method is deprecated at present.

will postbyronwallet method always exist? 

I can’t change the mnemonic words with more digits now (more than 12+), what should I do?

**Comment by LovelaceAdmin** [comment]
Hello user. It's a request for a wallet created from a local node. you need to connect your account before it can be fixed.?

What wallet do you hold.?
MetaMask or Trust Wallet.?

**Comment by LovelaceAdmin** [comment]
> I have restored my wallet with postbyronwallet, but this method is deprecated at present.
> 
> 
> 
> will postbyronwallet method always exist? 
> 
> 
> 
> I can’t change the mnemonic words with more digits now (more than 12+), what should I do?

Hello user. It's a request for a wallet created from a local node. you need to connect your account before it can be fixed.?

What wallet do you hold.?
MetaMask or Trust Wallet.?

**Comment by piotr-iohk** [comment]
>I have restored my wallet with postbyronwallet, but this method is deprecated at present.

> will postbyronwallet method always exist?

> I can’t change the mnemonic words with more digits now (more than 12+), what should I do?

There is no intent for dropping support of Byron wallets in the future, however you miss on the Shelley wallets features, like delegation.
One way would be to create new Shelley wallet and transfer all your funds from the old Byron wallet to the new one. 
For better user experience you can use https://daedaluswallet.io/. Daedalus wallet actually uses cardano-wallet in the bg and provides nice UI on top of it.

**Comment by Alteryy** [comment]
Hi, We are an exchange that provides services. We will assign each user an address produced with 12-digit mnemonic words. There are many addresses. If the mnemonic words are upgraded, the cost of redistributing user addresses will be very high. So we are worried that the 12-digit mnemonic will not be used in the future。

**Comment by Alteryy** [comment]
> > I have restored my wallet with postbyronwallet, but this method is deprecated at present.
> 
> > will postbyronwallet method always exist?
> 
> > I can’t change the mnemonic words with more digits now (more than 12+), what should I do?
> 
> There is no intent for dropping support of Byron wallets in the future, however you miss on the Shelley wallets features, like delegation. One way would be to create new Shelley wallet and transfer all your funds from the old Byron wallet to the new one. For better user experience you can use https://daedaluswallet.io/. Daedalus wallet actually uses cardano-wallet in the bg and provides nice UI on top of it.

Hi, We are an exchange that provides services. We will assign each user an address produced with 12-digit mnemonic words. There are many addresses. If the mnemonic words are upgraded, the cost of redistributing user addresses will be very high. So we are worried that the 12-digit mnemonic will not be used in the future。

**Comment by piotr-iohk** [comment]
>Hi,
I have restored my wallet with postbyronwallet, but this method is deprecated at present.
What is the risk if I keep 12 mnemonics all the time,Will my 12 bit mnemonics not be restored to my wallet one day and What should I do?

There are no plans to di

**Comment by Alteryy** [comment]
Is it risky to keep 12 mnemonic words all the time?

**Comment by piotr-iohk** [comment]
There is no intent to drop support for Byron wallets (12-word mnemonic wallets included). However it is recommended to use Shelley wallets for any new applications.

**Comment by ditchtech** [comment]
For all those still trying, I tried every other light wallet, without success.
Finally it worked like a charm with Medusa, https://adawallet.io/.  Used the 12 word seed to restore the entire wallet, then moved it out to Trustwallet.

**Comment by abailly** [comment]
Thanks @ditchtech. While certainly a great tool, Medusa being a light which means you have to trust a remove central server with your data (hopefully not your keys, but still), which might not be acceptable for all users.
Having a way to migrate Byron wallets to Shelley wallets would be nice but is non trivial given the widely diverging address structures. But the "deposit wallet" the team is currently working on could provide a solution.
