### ISSUE TITLE
Technical Debt Week 21

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#302]
# Context

When using `unsafeGenerateKeyFromSeed` or `generateKeyFromSeed` from the `Cardano.Wallet.Primitive.AddressDerivation` module, the length of the seed should be at least 16-bytes (cf: [cardano-crypto@Cardano/Crypto/Wallet.hs#L119-L124](https://github.com/input-output-hk/cardano-crypto/blob/3c5db489c71a4d70ee43f5f9b979fcde3c797f2a/src/Cardano/Crypto/Wallet.hs#L119-L124))

# Decision

It's probably a good idea to add a proper disclaimer in the corresponding function documentation on our side and, to check various generators or method using them and make sure they actually always generate seed of at least 16-bytes.

# Acceptance Criteria

- [ ] Our documentation `must` contain the aforementioned disclaimer
- [ ] Current generators `must` have been checked and fixed if necessary
- [ ] The module API `may` enforce this constraint

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #381        | `master`  |

# QA 

We introduced invariant to `(Passphrase "seed")` requiring min 16 bytes and max 255 bytes. A number of tests failed because of this change. The PR was also to adjust tests (generators, values, golden tests) to comply with this and make it green.  

Moreover, the comment was added https://github.com/input-output-hk/cardano-wallet/pull/381/files#diff-d14c4b850bb3168e6ef09bf8769d120aR506

**Comment by piotr-iohk** [comment]
lgtm :+1:
