### ISSUE TITLE
`listTransactions` endpoint: add assets to the "amount" object

### ISSUE THREAD

**Issue by runeksvendsen** [cardano-foundation/cardano-wallet#3044]
### The problem that you wish to solve

Currently, the [listTransactions](https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/listTransactions) endpoint only returns the amount of ADA sent/received for a transaction inside the `amount`  field.

### Description

Add to the object in this field an `asset` property, which contains the native tokens received/sent by the given transaction.

### Implementation suggestions

1. Make the change backwards-compatible by adding the propery `assets` to the `amount` object (in addition to the already-existing properties `quantity` and `unit`)
2. It looks like cardano-wallet already has the needed data available here https://github.com/input-output-hk/cardano-wallet/blob/a112dc15998cb54c3b7323fe8217316ebabb4fa2/lib/core/src/Cardano/Wallet/Primitive/Model.hs#L599-L604 but throws it away (using `TB.getCoin`)

**Comment by HeinrichApfelmus** [comment]
Closely related to #2710
