### ISSUE TITLE
really slow to on-ramp setup in <docker-compose up>

### ISSUE THREAD

**Issue by btfdip** [cardano-foundation/cardano-wallet#3070]
### The problem that you wish to solve

I spent three days to try to fully sync the cardano-wallet server. Still cannot make it work.

Everyone interested in this repo directly got rejected by setting up the  dev environment.

![image](https://user-images.githubusercontent.com/96004784/147384909-8fcd4755-40ce-4955-97ed-02e154087c31.png)

### Description

RT

**Comment by piotr-iohk** [comment]
[docker-compose.yml](https://github.com/input-output-hk/cardano-wallet/blob/master/docker-compose.yml) works fine for me.
```
NETWORK=testnet docker-compose up
```
Spins up both cardano-node and cardano-wallet and I'm able to use the wallet API fine: 
```
$ docker ps
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS              PORTS                    NAMES
965ae77bd950        inputoutput/cardano-wallet:2021.12.15   "bash -c ' ([[ $NETW…"   9 seconds ago       Up 8 seconds        0.0.0.0:8090->8090/tcp   cardano-wallet_cardano-wallet_1
79606abda9d5        inputoutput/cardano-node:1.32.1         "entrypoint"             9 seconds ago       Up 8 seconds                                 cardano-wallet_cardano-node_1

```
Looking at the logs you shared it seems that probably cardano-node didn't start for some reason :thinking:.
Can you share your `docker ps` output and some cardano-node logs (`docker logs -f <cardano-node-container-id>`)?

**Comment by HeinrichApfelmus** [comment]
Closing as outdated.

Feel free to reopen if the issue persists.
