### ISSUE TITLE
Provide transaction input information in transaction details

### ISSUE THREAD

**Issue by benapetr** [cardano-foundation/cardano-wallet#3082]
### The problem that you wish to solve

Right now one of most crucial information is missing in transaction details - WHO sent it. If I want to know that I have to use external service to lookup tx details and see where the inputs came from, the cardano wallet data only show this:

```
  "inputs": [
    {
      "id": "16717b2ef1f7479f6dcba243122f1f222451bc3a44328f9a7e0e9cc2b96394d7",
      "index": 1
    }
  ],
```

that's useless

### Description

Show information about inputs, this information must be on blockchain, otherwise other tools wouldn't be able to see it. If you can't even see where did the transaction come from, they you don't really see much.

**Comment by HeinrichApfelmus** [comment]
At the time of this writing, the HTTP endpoint `/wallets/{walletId}/transactions` does a partial lookup of transaction inputs when displaying transactions.

However, it can only show information for inputs that belong to the wallet — showing information about other inputs would require keeping track of *all past transactions*. This is expensive for a wallet to do, and the node doesn't quite do it.

**Comment by HeinrichApfelmus** [comment]
Closely related to #2710
