### ISSUE TITLE
Nix-build is broken, `nix build` works

### ISSUE THREAD

**Issue by tomsmalley** [cardano-foundation/cardano-wallet#3107]
### Just checking...

- [X] This is a `cardano-wallet` bug.
- [X] I am using the latest `cardano-wallet` release.
- [X] I am using the *correct* `cardano-node` version for that release of `cardano-wallet`.

### Version

dde627009c98ee85be8fda09d453d5078e6616f7

### Platform

Linux nixos 5.10.88 #1-NixOS SMP Wed Dec 22 08:31:00 UTC 2021 x86_64 GNU/Linux

### Installation method

Nix

### Context

When running `nix-build` in the project root directory, I get:

```
building '/nix/store/4ig2z0ly7yjnzxcfhkl3rwqy739gkm94-source.drv'...

trying https://api.github.com/repos/numtide/flake-utils/tarball/74f7e4319258e287b0f9cb95426c9853b282730b
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  7256  100  7256    0     0  28793      0 --:--:-- --:--:-- --:--:-- 28793
unpacking source archive /build/74f7e4319258e287b0f9cb95426c9853b282730b
do not know how to unpack source archive /build/74f7e4319258e287b0f9cb95426c9853b282730b
error: builder for '/nix/store/4ig2z0ly7yjnzxcfhkl3rwqy739gkm94-source.drv' failed with exit code 1
```

But if I use Nix with flakes and nix-command, I can run `nix flake archive`, and subsequent `nix-build`s will work fine because flake-utils is in the store.

## Steps to Reproduce

1. Clone the repo
2. nix-collect-garbage to ensure you don't have flake-utils in the store
3. nix-build

### Expected behavior

Successful build

### Actual behavior

This error:

```
building '/nix/store/4ig2z0ly7yjnzxcfhkl3rwqy739gkm94-source.drv'...

trying https://api.github.com/repos/numtide/flake-utils/tarball/74f7e4319258e287b0f9cb95426c9853b282730b
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  7256  100  7256    0     0  28793      0 --:--:-- --:--:-- --:--:-- 28793
unpacking source archive /build/74f7e4319258e287b0f9cb95426c9853b282730b
do not know how to unpack source archive /build/74f7e4319258e287b0f9cb95426c9853b282730b
error: builder for '/nix/store/4ig2z0ly7yjnzxcfhkl3rwqy739gkm94-source.drv' failed with exit code 1
```

**Comment by rvl** [comment]
Hi @tomsmalley, The next release of `cardano-wallet` will be using nix flakes for its build.
Could I ask you to please install `nix` version 2.6.0 (or greater) and enable this configuration:
```
# nix.conf
experimental-features = nix-command flakes
```
Then build with the command:
```
nix build
```
More information:
- https://input-output-hk.github.io/cardano-wallet/developers/Building#nix
- https://input-output-hk.github.io/cardano-wallet/user-guide/installation/NixOS

Thanks

**Comment by HeinrichApfelmus** [comment]
Closing — as @rvl said, we no longer support building with plain `nix-build`, but we do support flakes with `nix build`.
