### ISSUE TITLE
Bech32 decoder fails for certain valid Bech32 strings.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#311]
## Overview

When presented with certain **known-valid** Bech32 strings from [BIP 173](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki) (the Bech32 specification), our [Bech32 decoder](https://github.com/input-output-hk/cardano-wallet/blob/501f5157e179d8c62eb082813c45b2a830e26643/lib/bech32/src/Codec/Binary/Bech32/Internal.hs) currently fails:

```hs
> decode "bc1zw508d6qejxtdg4y5r3zarvaryvg6kdaj"
Left (StringToDecodeContainsInvalidChars [])

> decode "bc1pw508d6qejxtdg4y5r3zarvary0c5xw7kw508d6qejxtdg4y5r3zarvary0c5xw7k7grplx"
Left (StringToDecodeContainsInvalidChars [])
```

The reference Haskell implementation, on the other hand, **succeeds** in decoding these strings.

## Analysis

If we examine the [`decode`](https://github.com/input-output-hk/cardano-wallet/blob/501f5157e179d8c62eb082813c45b2a830e26643/lib/bech32/src/Codec/Binary/Bech32/Internal.hs#L193) function, we discover that the final step is to convert the data portion from **base-32** (5-bit words) to **base-256** (8-bit words):

```hs
    dp <- maybeToEither (StringToDecodeContainsInvalidChars []) $
        toBase256 (take (length dcp - checksumLength) dcp)
    return (hrp, BS.pack dp)
```

However, this step is **not** guaranteed to succeed:
```hs
toBase256 :: [Word5] -> Maybe [Word8]
toBase256 dat =
    map fromIntegral <$> convertBits (map fromWord5 dat) 5 8 noPadding
```

In particular, this step will **always** fail if the data part of the string satisfies two conditions:

1. The length (in bits) is **not** divisible by 8.
2. When partitioned into contiguous 8-bit chunks (starting from the most-significant end of the string), the least significant chunk (which will be shorter than 8 bits) contains **any** non-zero bits.

## Root Cause

The problem is caused by our attempt to always convert the [`Word5`] result into a string of `Word8`. In fact, there is no general way to do this, without some knowledge of what we're trying to decode.

The `toBase256` function attempts to do this (by always trimming trailing zeros so that the result has a bit length that is divisible by 8) but this particular convention is **specific** to one particular use case (segwit addresses), and fails in the general case. The reason for this is simple: we don't always know if the trailing zero bits are meant to be part of the data.

## Proposed Solution

Don't try to always convert the result to a string of `Word8`. Instead:

1. Add a type `DataPart`, which wraps `[Word5]`.
2. Change the types of `decode` and `encode` so that they operate on `DataPart` instead of `ByteString`.
3. Ensure that the round trip relationship between `encode` and `decode` is preserved, with QuickCheck property tests.
4. Provide auxilliary functions to convert to (and from) `ByteString` and `DataPart`. These functions will be dependent on the use-case, but we can provide a basic implementation that always pads when going from `ByteString` to `DataPart`, and always trims when going from `DataPart` back to `ByteString`.
5. Provide unit tests to ensure that all reference Bech32 strings mentioned in the standard can be decoded successfully.

## QA

- We now have an improved API with better smart-constructors which disallow construction of illed DataPart, see: [haddock](https://input-output-hk.github.io/cardano-wallet/haddock/edge/bech32-2019.5.8/Codec-Binary-Bech32.html)

**Comment by piotr-iohk** [comment]
nice one :+1:
