### ISSUE TITLE
Provide endpoint that allows user to obtain min UTXO size for potential transaction in machine friendly format

### ISSUE THREAD

**Issue by benapetr** [cardano-foundation/cardano-wallet#3113]
### The problem that you wish to solve

Right now, when you are trying to obtain fees using payment-fees endpoint you get error when UTXO is too small (when sending native assets). That's kind of expected, but you need to understand that user doesn't know what min UTXO is and perhaps need cardano-wallet to calculate it for them.

Right now when I use this endpoint, I get 404 error with machine unfriendly error description that contains data I need somewhere encrypted in the error description (min coin value: 1.413762).

This is the output I get:

```
{
  "code": "utxo_too_small",
  "message": "Some outputs have ada values that are too small. There's a minimum ada value specified by the protocol that each output must satisfy. I'll handle that minimum value myself when you do not explicitly specify an ada value for an output. Otherwise, you must specify enough ada. Here are the problematic outputs:   - Expected min coin value: 1.413762     TxOut:       address: 00064225...d59deacc       coin: 1.400000       tokens:         - policy: 9e87deb6ec1e989f125652b4883728fdd308e4223a0396f45b2023c2           tokens:             - token: 766d3774657374486f736b794361736847726162               quantity: 1 "
}
```

### Description

What I want is to ask cardano-wallet "what is min UTXO size for this kind of transaction, and how much fees it will cost?" and I expect it will give me some JSON data contaning answer to my question like

```
{
  "min_utxo": 1.413762,
  "fee": 200000
}
```

**Comment by JideFasholaADA** [comment]
Have you tried the cardano wallet estimate fees endpoint? https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/postTransactionFee

**Comment by rvl** [comment]
Thanks - this is a good idea because the [getNetworkParameters](https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/getNetworkParameters) endpoint only provides the fixed part of `minimum_utxo_value`.

**Comment by cedcardano** [comment]
For now you can implement this yourself for the current set of network parameters with 

![image](https://user-images.githubusercontent.com/96455322/163409895-12e60936-23a1-4aa1-be9d-950ae9488861.png)

Here your parameters are:

- The number of distinct asset types (ie, a utxo with two types of fungible token with different policy IDs and two NFTs with the same policy ID will have this parameter be four)
- The sum of the lengths of the unique token names in bytes (ie, a utxo with an asset called '123' and an asset called '12' will have this value be 5, regardless of if they have the same policy ID or not)
- The number of distinct policy IDs (ie, two NFTs with the same policy, plus a fungible token with a different policy id will have this value be 2)

**Comment by HeinrichApfelmus** [comment]
@jonathanknowles What is the current status of this issue?

**Comment by HeinrichApfelmus** [comment]
`utxo_too_small` now reports a better error message indicating a good UTxO size.
