### ISSUE TITLE
Unable to send Byron era 

### ISSUE THREAD

**Issue by gitstar2022** [cardano-foundation/cardano-wallet#3142]
Having issues sending Byron era ada which was not moved into shelley with fork. How can this be resolved. Is it possible to get an old version of Daedalus (2.0.0) to attempt to do this here.

**Comment by nikolaglumac** [comment]
Old versions of Daedalus will not help you as they can no longer connect to the network.
Please share more details:
- Do you have access to your Byron wallet in the latest Daedalus version?
- Do you see the correct balance?
- What error do you get when trying to send funds from that wallet?

Logs and screenshots would help us a lot 🙏

**Comment by nikolaglumac** [comment]
@rvl this is the individual who has reached out to us via Twitter. 
Please let us know if there is any progress on this issue 🙏

**Comment by gitstar2022** [comment]
https://github.com/input-output-hk/cardano-wallet/issues/2395 
@rvl @nikolaglumac could anything on the above issue help solve the problem. Secret.key file is not in json version so also unable to drop it into any other wallets

**Comment by courtwebb** [comment]
@rvl if there is a way to manual spend or generate the 12 words so we can try in a different platform i can jump on a call with you - i can have you walk me through the coding on the wallet

**Comment by rvl** [comment]
There are 3 separate bugs from the 2017 code which apply to this.
1. One is that the cardano-sl wallet never generated address indices in the hardened index range.
2. The other is that deriveXPub used the wrong range for hardened indices.
3. The last seems to be an off-by-one error for address indices.
I need to run some tests locally to reproduce it - then we can use a few CLI commands to verify with your wallet, and then we can come up with the procedure to spend the funds.

**Comment by gitstar2022** [comment]
Ok thats great, do you have any kind of timeline for a fix on this issue.

**Comment by courtwebb** [comment]
would we have the same issue if we were able to get the wallet into Yoroi by using memonic if we could retrieve this

**Comment by gitstar2022** [comment]
Also from one Aussie to another - THANK YOU!!

**Comment by fukur0kuju** [comment]
@gitstar2022 

contact me, can help, important

**Comment by gitstar2022** [comment]
> 

No thanks @fukur0kuju - I’m working directly with @rvl and IOHK. I don’t have any desire to be scammed considering you are asking people for money upfront and tagging everyone. Something is a bit fishy. This is not an issue that anyone can fix. I have trust in the Iohk team.

**Comment by HeinrichApfelmus** [comment]
There was a file in circulation with a wrong passphrase and nobody was able to decrypt the private key
