### ISSUE TITLE
Conflicting family instance declarations

### ISSUE THREAD

**Issue by locallycompact** [cardano-foundation/cardano-wallet#3146]
### Just checking...

- [X] This is a `cardano-wallet` bug.
- [X] I am using the latest `cardano-wallet` release.
- [X] I am using the *correct* `cardano-node` version for that release of `cardano-wallet`.

### Version

9684c1cb002ec980f71e7a7c157fa134df1f0f97

### Platform

linux

### Installation method

Built from source

### Description

Hi, I'm using the latest master of all cardano libraries, running into this error

```
src/Demo/Database.hs:159:10: error:
    Conflicting family instance declarations:
      STM (SqlPersistT (NoLoggingT (ResourceT IO))) = WrapSTM
        -- Defined at src/Demo/Database.hs:159:10
      STM
        (Control.Monad.Trans.Reader.ReaderT
           r m) = Control.Monad.Class.MonadSTM.WrappedSTM
                    'Control.Monad.Class.MonadSTM.Reader r m
        -- Defined in module Control.Monad.Class.MonadSTM
    |
159 |     type STM (SqlPersistT (NoLoggingT (ResourceT IO))) = WrapSTM
    |          ^^^

src/Demo/Database.hs:160:10: error:
    Conflicting family instance declarations:
      TVar (SqlPersistT (NoLoggingT (ResourceT IO))) = TVar IO
        -- Defined at src/Demo/Database.hs:160:10
      TVar (Control.Monad.Trans.Reader.ReaderT r m) = TVar m
        -- Defined in module Control.Monad.Class.MonadSTM
    |
160 |     type TVar (SqlPersistT (NoLoggingT (ResourceT IO))) = TVar IO
    |          ^^^^
 ```

**Comment by ghost** [comment]
Please check that `ouroboros-network`'s pinned commit in your cabal.project is the same as in `cardano-wallet`'s `cabal.project`. That should fix this issue.

**Comment by HeinrichApfelmus** [comment]
> That should fix this issue.

Indeed. Closing. Feel free to reopen in case the issue persists.
