### ISSUE TITLE
ApiCoinSelection json instance

### ISSUE THREAD

**Issue by v0d1ch** [cardano-foundation/cardano-wallet#3147]
### Just checking...

- [X] This is a `cardano-wallet` bug.
- [X] I am using the latest `cardano-wallet` release.
- [X] I am using the *correct* `cardano-node` version for that release of `cardano-wallet`.

### Version

6508a5f8939bab5fa6ca8df0e1d056585607c5e6

### Platform

NixOs

### Installation method

Built from source

### Network configuration

testnet

### Context

We have a http call to cardano-wallet api to construct a transaction (https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/constructTransaction) and eventually end up with the correct `ApiConstructTransaction` type. 

I noticed the api broke at this commit `6508a5f8939bab5fa6ca8df0e1d056585607c5e6` and after the described api call I could not decode json to valid `ApiConstructionType`. 

### Description

There are couple of new fields in `ApiCoinSelection` (which is part of the mentioned type `ApiConstructTransaction`) namely `depositsTaken` and `depositsReturned` which somehow don't end up being inside of the returned json (only `deposits` key exists which is part of the old api).

This is the complete response I get for the reference:

```
parsing Cardano.Wallet.Api.Types.ApiCoinSelection(ApiCoinSelection) failed, key "deposits_taken" not found.
JSON: Object (fromList [("coin_selection",Object (fromList [("change",Array [Object (fromList [("address",String "addr_test1qrm2eveexcqal3fx8w79zzf0kklplmp0f7fl8rgty3emj8ydy6ep90qusqgn7zwfa7504rrytflqr9vx9nzgxqp49g2qeevjvd"),("amount",Object (fromList [("quantity",Number 8136181.0),("unit",String "lovelace")])),("assets",Array []),("derivation_path",Array [String "1852H",String "1815H",String "0H",String "1",String "0"])])]),("collateral",Array []),("deposits",Array []),("inputs",Array [Object (fromList [("address",String "addr_test1qqqm73qquru5ta4yllnta3kg8j30yw4x288aldaxmmuhr05dy6ep90qusqgn7zwfa7504rrytflqr9vx9nzgxqp49g2qwekflf"),("amount",Object (fromList [("quantity",Number 1.0e7),("unit",String "lovelace")])),("assets",Array []),("derivation_path",Array [String "1852H",String "1815H",String "0H",String "0",String "0"]),("id",String "a0e5025825b4f86efb174127b6f45a1c1e4508fb1901ae8c229f3932c1bbcb49"),("index",Number 0.0)])]),("outputs",Array [Object (fromList [("address",String "addr_test1qqtfz4ma9cu6ses73wn2tny9gc8zufv9eg3qqt3lqfzlhjvn5t9nzcdv4sxsrz7k6adtp0xjj35gq73lzv8yct6xjgysv9qxfj"),("amount",Object (fromList [("quantity",Number 1694798.0),("unit",String "lovelace")])),("assets",Array [])])]),("withdrawals",Array [])])),("fee",Object (fromList [("quantity",Number 169021.0),("unit",String "lovelace")])),("transaction",String "hKYAgYJYIKDlAlgltPhu+xdBJ7b0WhweRQj7GQGujCKfOTLBu8tJAA2AAYKCWDkAFpFXfS45qGYei6alzIVGDi4lhcoiAC4/AkX7yZOiyzFhrKwNAYvW11qwvNKUaIB6PxMOTC9GkgkaABncToJYOQD2rLM5NgHfxSY7vFEJL7W+H+wvT5PzjQskc7kcjSayErwcgBE/CcnvqPqMZFp+AZWGLMSDADUqFBoAfCX1AhoAApQ9AxoAARpYDoCg9fY=")])

```

I am happy to provide more input or work on fixing this. From taking a glance at the code I didn't see immediately what is exactly off here since json instances are derived using generics, might be something is not correct in the client.

**Comment by HeinrichApfelmus** [comment]
We do not support the coin selection endpoint anymore — please use the Transaction (New) workflow
