### ISSUE TITLE
Couldn't match expected type 'Word32' with actual type 'Word16'

### ISSUE THREAD

**Issue by locallycompact** [cardano-foundation/cardano-wallet#3151]
### Just checking...

- [X] This is a `cardano-wallet` bug.
- [X] I am using the latest `cardano-wallet` release.
- [X] I am using the *correct* `cardano-node` version for that release of `cardano-wallet`.

### Version

d001a56aa3a4bb794094c40c8cba560064b879d5

### Platform

linux

### Installation method

Built from source

### Description

Hi, I am running into this error when trying to build cardano-wallet as a dependency of a contract.

```

src/Cardano/Wallet/Byron/Compatibility.hs:293:17: error:
    • Couldn't match expected type ‘Word32’ with actual type ‘Word16’
    • In the ‘inputIx’ field of a record
      In the expression:
        W.TxIn {inputId = W.Hash $ CC.hashToBytes id_, inputIx = ix}
      In an equation for ‘fromTxIn’:
          fromTxIn (TxInUtxo id_ ix)
            = W.TxIn {inputId = W.Hash $ CC.hashToBytes id_, inputIx = ix}
    |
293 |     , inputIx = ix
    |                 ^^
```
On the df/wallet-bug branch here, with nix-build.

https://gitlab.homotopic.tech/plutus/contracts/gift/-/commits/df/wallet-bug

**Comment by HeinrichApfelmus** [comment]
Closing as this issue is likely resolved — we use `nix build` for our releases, and we couldn't have released if this were still an issue. Chances are that you got a slightly broken `master` version.

But please feel free to reopen if the issue persists!
