### ISSUE TITLE
Invalid boundaries for fee estimation in transaction scenario

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#316]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Windows & OSX & Linux) | Human |

# Context
 
 

It's a bit tricky to know exactly how much fee a transaction will have to leave in the transaction... In practice, it depends on the size of the input indexes. Bigger indexes take few more bytes to encode, smaller one less bytes. So we are checking fees to be within a certain range, and it seems that this range was incorrectly calculated.

# Steps to Reproduce

1. Re-run the integration tests Transactions scenarios a few times until a scenarios picks some some very small or big input index which make the fee out of the expected bounds. 

## Expected behavior

- The test never fail

## Actual behavior
 
<A clear and concise description of what you observe instead. If applicable add screenshots to help explain your problem.>

- We sometimes have a situation where the fees are slightly less than expected resulting in:

```
      test/integration/Test/Integration/Framework/DSL.hs:242:16: 
      1) Transactions API endpoint tests TRANS_CREATE_01 - Single Output Transaction
           predicate failed on: 168610
```

---

# Resolution Plan

- [x] Make the failure better, right now we just use `shouldSatisfy` which gives a poor error message... It'd be better to show the given value and the expected boundaries. 
- [x] Try to reproduce and compute the correct boundaries for fees (thought I did the first time already...)

# PR

| Number   | Base      |
| ---      | ---       |
| #317       | `master` |

# QA 

- Error message from `expectFieldBetween` now gives a better output:

```
(expected 168610 >= 168611)
```

- The initial window for fee was actually made using the total transaction amount. Since the amount sent was 1 lovelace, we ended up being only one lovelace off on the edges. Fixed in #317

**Comment by piotr-iohk** [comment]
:ok_hand:
