### ISSUE TITLE
404 Not found on transactions-submit endpoint

### ISSUE THREAD

**Issue by adetante** [cardano-foundation/cardano-wallet#3181]
### Just checking...

- [X] This is a `cardano-wallet` bug.
- [X] I am using the latest `cardano-wallet` release.
- [X] I am using the *correct* `cardano-node` version for that release of `cardano-wallet`.

### Version

v2022-01-18 (git revision: a5085acbd2670c24251cf8d76a4e83c77a2679ba)

### Platform

MacOS

### Installation method

IOHK Docker image

### Network configuration

testnet

### Context

cardano-wallet synced on the testnet, wallet OK.

cardano-wallet logs:

```
[cardano-wallet.api-server:Info:485] [2022-03-18 10:37:39.19 UTC] [RequestId 74] [POST] /v2/wallets/.../transactions-construct
[cardano-wallet.wallet-engine:Info:485] [2022-03-18 10:37:39.20 UTC] c5cfa657: Selection report (summarized):
SelectionReportSummarized:
  computedFee: 0.169021
  ...
[cardano-wallet.api-server:Info:485] [2022-03-18 10:37:39.20 UTC] [RequestId 74] POST /v2/wallets/.../transactions-construct 202 Accepted in 0.0125638s
[cardano-wallet.api-server:Info:486] [2022-03-18 10:37:39.21 UTC] [RequestId 75] [POST] /v2/wallets/.../transactions-sign
[cardano-wallet.api-server:Info:486] [2022-03-18 10:37:39.33 UTC] [RequestId 75] POST /v2/wallets/.../transactions-sign 202 Accepted in 0.1280354s
[cardano-wallet.api-server:Info:488] [2022-03-18 10:37:39.34 UTC] [RequestId 76] [POST] /v2/wallets/.../transactions-submit
[cardano-wallet.api-server:Info:488] [2022-03-18 10:37:39.34 UTC] [RequestId 76] POST /v2/wallets/.../transactions-submit 404 Not Found in 0.0013394s
```
## Steps to Reproduce

1. Construct a transaction:
```
curl -X POST 'http://localhost:8090/v2/wallets/{wallet_id}/transactions-construct' \
  -H 'Content-Type: application/json' \
  -d '{ "payments": [ {...} ] }'
```
✅ returns a `202 Accepted` with `{ transaction: "xxx" }` in the response

2. Sign the transaction
```
curl -X POST 'http://localhost:8090/v2/wallets/{wallet_id}/transactions-sign' \
  -H 'Content-Type: application/json' \
  -d '{ "transaction": "xxx", "passphrase": "my-passphrase" }'
```
✅ returns a `202 Accepted` with `{ transaction: "zzz" }` in the response

3. Submit the tx

```
curl -X POST 'http://localhost:8090/v2/wallets/{wallet_id}/transactions-submit' \
  -H 'Content-Type: application/json' \
  -d '{ "transaction": "zzz" }'
```
❌ returns a `404 Not Found` with
```
{
    "code": "not_found",
    "message": "I couldn't find the requested endpoint. If the endpoint contains path parameters, please ensure they are well-formed, otherwise I won't be able to route them correctly."
}
```

=> same value is used for `{wallet_id}` in the 3 calls

...

### Expected behavior

`200 OK` on `POST /v2/wallets/{wallet_id}/transactions-submit` with `{ id: "..." }` in the response

**Comment by bhoudebert** [comment]
Hello there,

This is not a bug, you are looking at something that is not in the release you are using. If you have a look at the file describing the new endpoint at the specific sha1 version, you'll see that it does not have it.

**Comment by adetante** [comment]
Thank you. It was not clear in the doc...
But that's ok with the current `dev-master` docker tag.

**Comment by piotr-iohk** [comment]
Indeed, the release `v2022-01-18` was tagged at a5085acbd2670c24251cf8d76a4e83c77a2679ba. It doesn't yet include this endpoint.

**Comment by abrkn** [comment]
When can we expect `transactions-submit` in a Docker image release?

**Comment by b00kdev** [comment]
I just ran into this as well. The `v2022-01-18` release docs do show this endpoint as being included, which adds to the confusion. https://input-output-hk.github.io/cardano-wallet/api/v2022-01-18/#operation/submitTransaction

So while it may not be a bug in the code (as @bhoudebert pointed out) it does seem to be a bug in the docs. Could there be a bugfix release that includes this endpoint or will we need to wait for the next release?

**Comment by bhoudebert** [comment]
As I assume you are on the development timeline you could also just use the `main` latest sha1 and then build & start.

I usually do this kind of thing for the whole cardano/plutus env to avoid waiting for release, unfortunately it is not safe for production to do so but allow you to be unblocked for now.

**Comment by b00kdev** [comment]
@bhoudebert Yeah, that's what I did to unblock for now, but like you mentioned it's not really ideal for going to production (which we're hoping to do soon).
