### ISSUE TITLE
Support Aeson 2

### ISSUE THREAD

**Issue by kk-hainq** [cardano-foundation/cardano-wallet#3187]
### The problem that you wish to solve

We would like to have Aeson 2 support in `cardano-wallet` so we could integrate it into the likes of `plutus-apps` that is on such a move.

### Description

Many packages (`cardano-base`, `plutus`, `cardano-ledeger`, etc.) in the Cardano ecosystem have added Aeson 2 support to bump dependencies together. More and more are following and it would be nice for this repository to do so as well.

We could open a PR if accepted!

**Comment by rvl** [comment]
Yeah we shall need to do this next time we bump the cardano-node version.
@kk-hainq, if you already have a branch, please by all means open a PR.
Thanks.

**Comment by manonthemat** [comment]
The comment on `452975f8afe5b9c5c168e972c4c4993f08f10e7f` from April 2021 mentioned something along those lines.

https://cs-syd.eu/posts/2021-09-11-json-vulnerability further highlights the importance. Looking forward to the next cardano-node release for one more reason.

**Comment by Anviking** [comment]
Done with #3280, which is in latest release
