### ISSUE TITLE
Cardano - cardano-wallet - couldn't be find policy-key endpoint.

### ISSUE THREAD

**Issue by wandyyd** [cardano-foundation/cardano-wallet#3219]
### Just checking...

- [X] This is a `cardano-wallet` bug.
- [X] I am using the latest `cardano-wallet` release.
- [X] I am using the *correct* `cardano-node` version for that release of `cardano-wallet`.

### Version

v2022-01-18 (git revision: a5085acbd2670c24251cf8d76a4e83c77a2679ba)

### Platform

Linux - Ubuntu 18.04.6 LTS

### Installation method

Built from source

### Network configuration

testnet

### Context

Hi, I kinda new on cardano world.

Currently learning about nft / minting based [on this link](https://developers.cardano.org/docs/native-tokens/minting-nfts) on testnet.

The `cardano-node` and `cardano-wallet` working correctly and so far is good. Both `cardano-node` and `cardano-wallet` using latest version

I can see status is ready

```
curl --url http://localhost:8099/v2/network/information | jq

{
  ...
  "sync_progress": {
    "status": "ready"
  },
  ...
}

```

But, when trying on `policy-key` endpoint, [from this reference](https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/postPolicyKey), it's failed and show error. Am I doing it incorrectly?

Below is the command I run / try.

```
curl --request POST \
--url http://localhost:8099/v2/wallets/my_wallet_id/policy-key \
--header 'Content-Type: application/json' \
--data '{
"passphrase": "my_passphrase"
}' | jq


{
  "code": "not_found",
  "message": "I couldn't find the requested endpoint. If the endpoint contains path parameters, please ensure they are well-formed, otherwise I won't be able to route them correctly."
}
```

**ps**
1. Notice, that I use `8099` as the port, instead of default `8090`. Just to test around. I think it's fine, since I can do `curl` well without an issue (except that `policy-key`)

2. For the `policy` command, you can try to copy-paste and change the `my_wallet_id` and `my_passphrase`, to see if I make a typo. But I think, I'm not making typo or else there. 😕 

3. I tried to double-check if the `endpoint` is ready to used, and seems yes, seeing this figure below
![image](https://user-images.githubusercontent.com/30722472/161883468-25ccd397-f433-4644-980a-b577f641ec70.png)

Thanks for your time! :smile: 

## Steps to Reproduce

1. Setup `cardano-node` and `cardano-wallet` to `testnet` network
2. Do `sync` and check its status if ready or not - `curl --url http://localhost:8099/v2/network/information | jq`
3. Create `wallet` and get its `address`
4. Trying `curl` to `policy-key` endpoint
<pre>
curl --request POST \
--url http://localhost:8099/v2/wallets/my_wallet_id/policy-key \
--header 'Content-Type: application/json' \
--data '{
"passphrase": "my_passphrase"
}' | jq
</pre>
...

### Expected behavior

A string response(?) [as per guide](https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/postPolicyKey)

### Actual behavior

Error return, saying that the endpoint isn't there
<pre>
{
  "code": "not_found",
  "message": "I couldn't find the requested endpoint. If the endpoint contains path parameters, please ensure they are well-formed, otherwise I won't be able to route them correctly."
}
</pre>

**Comment by piotr-iohk** [comment]
This endpoint is not yet available in the last release https://github.com/input-output-hk/cardano-wallet/releases/tag/v2022-01-18, and here's the corresponding API doc for the last release -> https://input-output-hk.github.io/cardano-wallet/api/v2022-01-18/. (linked also in the release notes)

The endpoint is available in the current `master` though and the corresponding API doc for `master` is -> https://input-output-hk.github.io/cardano-wallet/api/edge/.

Sorry for the confusion! I believe we'll have a new release fairly soon. :crossed_fingers:

**Comment by wandyyd** [comment]
Hi @piotr-iohk ! Thanks for your detail info!
I didn't realize it's different, since the `master doc` also stated as `v2022-01-18` instead `master` (maybe it will make things clearer or maybe add some notes).

Sorry for false-report this as bug 😅 


*edit - question related to documentation.
Been wonder, if there's mint/burn nft documentation using `cardano-wallet`
I saw this [guide](https://input-output-hk.github.io/cardano-wallet/user-guide/common-use-cases/assets#minting-and-burning-assets), is this still valid?
Means, at the moment, `cardano-wallet` haven't yet able to do mint/burn nft (hopefully soon)
