### ISSUE TITLE
Bech32 `decode` function successfully decodes certain classes of corrupted strings.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#324]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | (Windows & OSX & Linux) | Code |

# Context

For certain Bech32 strings, **deleting** or **inserting** a single character will produce strings that are **still valid** according to our implementation. There appear to be **two** main cases:

1. **Insertion**: if a valid Bech32 string has the suffix `p`, inserting a single `q` character immediately before the `p` will produce **another** valid Bech32 string.

2. **Deletion**: if a valid Bech32 string has the suffix `qp`, deleting the `q` character will produce **another** valid Bech32 string.

These production rules can be applied **repeatedly**, either by deleting many `q` characters, or by inserting many `q` characters, producing a valid Bech32 string after each step.

# Examples

The string `ii2134hk2xmat79tp` is a valid Bech32 string, with:
* human-readable part `ii2`
* data part `34hk2xm`
* checksum `at79tp`

## Insertion

By inserting one or more `q` characters immediately before the final `p` character, we can produce more strings that are valid Bech32 strings:

* `ii2134hk2xmat79tqp`
* `ii2134hk2xmat79tqqp`
* `ii2134hk2xmat79tqqqp`
* `ii2134hk2xmat79tqqqqp`

## Deletion

Conversely, by deleting one or more `q` characters located immediately before a final `p` character, we can go the other way. The following are all valid Bech32 strings:

* `eyg5bsz1l2mrq5ypl40hqqqp`
* `eyg5bsz1l2mrq5ypl40hqqp`
* `eyg5bsz1l2mrq5ypl40hqp`
* `eyg5bsz1l2mrq5ypl40hp`

# Consequences

Unfortunately, this causes our test suite to fail, as we currently assume the following laws:
1. inserting a random character into a valid Bech32 string will create an invalid string.
2. deleting a random character from a valid Bech32 string will create an invalid string.

The above laws unfortunately do not hold, at least with the reference implementations (and consequently our implementation).

# Resolution Plan

We need to account for the fact that there are counterexamples to the above laws.

- [x] Adjust the test suite so that encountering the above class of counterexamples will not cause our test suite to fail.
- [x] Add more debugging information to our test suite to make it easier to analyze any potential further classes of counterexamples.
- [x] Run the test suite on a large number of examples, to determine whether there are other counterexamples to the above laws.
# PR

| Number   | Base      |
| ---      | ---       |
| #327       | `master` |
| #328 | `master` |

# QA 

- Failures now output much better counter examples

```
       index of mutated char: 9
               original char: '1'
            replacement char: 'q'
             original string: "tbx1!w9-j180j4kcx7z64"
            corrupted string: "tbx1!w9-jq80j4kcx7z64"
```

- Particular edge-case is now handled in the test assertions, see [Codec.Binary.Bech32Spec](https://github.com/input-output-hk/cardano-wallet/blob/master/lib/bech32/test/Codec/Binary/Bech32Spec.hs#L202-L209)

- Opened a ticket on the reference implementation to alert / discuss about the issue: [sipa/bech32#51](https://github.com/sipa/bech32/issues/51)

**Comment by jonathanknowles** [comment]
An example with more debugging information:
```hs
  test/Codec/Binary/Bech32Spec.hs:155:22: 
  1) Codec.Binary.Bech32, Decoding a corrupted string should fail, Decoding fails when a character is omitted.
       Falsifiable (after 715 tests):
         ValidBech32String {getValidBech32String = "{gz01t9ylrthxjkw4pwceanudwk9kwrnu8aaqp", humanReadablePart = HumanReadablePart "{gz0", unencodedDataPart = DataPart "t9ylrthxjkw4pwceanudwk9kwrn"}
         omitted char at index: 36
         omitted char:'q'
         
       predicate failed on: Right (HumanReadablePart "{gz0",DataPart "t9ylrthxjkw4pwceanudwk9kwr")

  To rerun use: --match "/Codec.Binary.Bech32/Decoding a corrupted string should fail/Decoding fails when a character is omitted./"

Randomized with seed 932303910

Finished in 0.3923 seconds
47 examples, 1 failure
```

In the above example, the character has been omitted from the **checksum** part.

**Comment by jonathanknowles** [comment]
Every counterexample I've found so far has the same thing in common:

1. The character chosen (to be randomly omitted by the test) is the **second-to-last** character.
2. The character omitted is `q`, which corresponds to a `Word5` value of `0`.

Another example:
```hs
  1) Codec.Binary.Bech32, Decoding a corrupted string should fail, Decoding fails when a character is omitted.
       Falsifiable (after 10218 tests):
         ValidBech32String {getValidBech32String = "uexf>14w03rn5zwc8leqp", humanReadablePart = HumanReadablePart "uexf>", unencodedDataPart = DataPart "4w03rn5zw"}
         omitted char at index: 19
         omitted char:          'q'
         original string:       "uexf>14w03rn5zwc8leqp"
         recombined string:     "uexf>14w03rn5zwc8lep"
         
       predicate failed on: Right (HumanReadablePart "uexf>",DataPart "4w03rn5z")
```

**Comment by jonathanknowles** [comment]
Sometimes the letter `q` can be inserted into a valid string (as the second-to-last character), and it doesn't cause the decoder to fail:
```hs
  test/Codec/Binary/Bech32Spec.hs:182:22: 
  1) Codec.Binary.Bech32, Decoding a corrupted string should fail, Decoding fails when a character is inserted.
       Falsifiable (after 16262 tests):
         ValidBech32String {getValidBech32String = "1vql9kg1fu7npp", humanReadablePart = HumanReadablePart "1vql9kg", unencodedDataPart = DataPart ""}
         DataChar {getDataChar = 'q'}
         inserted char at index: 13
         inserted char:          'q'
         original string:       "1vql9kg1fu7npp"
         recombined string:     "1vql9kg1fu7npqp"
         
       predicate failed on: Right (HumanReadablePart "1vql9kg",DataPart "f")
```

**Comment by jonathanknowles** [comment]
I've raised an issue against the reference implementation, here: https://github.com/sipa/bech32/issues/51

**Comment by piotr-iohk** [comment]
:+1:
