### ISSUE TITLE
Support GHC-9.2.2

### ISSUE THREAD

**Issue by locallycompact** [cardano-foundation/cardano-wallet#3240]
### The problem that you wish to solve

Hi, we're trying to get somewhere with compiling plutus-apps for ghc-9.2. I've had a go at updating cardano-wallet dependencies such as Oddword [here](https://github.com/locallycompact/OddWord). Something seems to have changed such that I get this error:

```
       > src/Data/Text/Class.hs:182:10: error:
       >     • Illegal type synonym family application ‘Data.Word.Odd.BaseWordImpl
       >                                                  (GHC.TypeNats.Internal.CmpNat 31 64)’ in instance:
       >         ToText Word31
       >     • In the instance declaration for ‘ToText Word31’
       >     |
       > 182 | instance ToText Word31 where
       >     |          ^^^^^^^^^^^^^
```

### Description

As above

**Comment by locallycompact** [comment]
Actually, I don't think this is a 9.2 problem. This problem seems to occur even if I just copy this repo into git and put it in an 8.10 build

**Comment by HeinrichApfelmus** [comment]
These days, we compile `cardano-wallet` using GHC 9.6. Closing as no relevant. Feel free to open a new issue if you hit similar problems.
