### ISSUE TITLE
Flaky test: Compare Wallet impl. with Specification

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#3248]
### Please ensure:

- [X] This is actually a flaky test already present in the code and not caused by your PR.

### Context

https://hydra.iohk.io/build/13887987/nixlog/1/tail

Seen on CI for:
https://github.com/input-output-hk/cardano-wallet/pull/3247

### Relevant team discussions

https://element.adrestia.iohkdev.io/#/room/!pVmOFJiBkItJMNTmCR:adrestia.iohkdev.io/$-unJ0isT24cCiJETY75z3G2eWQYSDYEiGXxZb-eRWao?via=adrestia.iohkdev.io

### Job name

https://hydra.iohk.io/build/13887987/nixlog/1/tail

### Test case name(s)

Compare Wallet impl. with Specification

### Error message

```shell
Failures:

  test/unit/Cardano/Wallet/Primitive/ModelSpec.hs:201:9: 
  1) Cardano.Wallet.Primitive.Model, Compare Wallet impl. with Specification, Lemma 3.2 - dom u ⋪ updateUTxO b u = new b
       Insufficient coverage (after 6400 tests):
         71.00% utxo ≠ ∅ 
         
         Only 71.00% utxo ≠ ∅ , but expected 75.00%

  To rerun use: --match "/Cardano.Wallet.Primitive.Model/Compare Wallet impl. with Specification/Lemma 3.2 - dom u \8938 updateUTxO b u = new b/"

Randomized with seed 1367156704
```

### Build link

https://hydra.iohk.io/build/13887987

**Comment by jonathanknowles** [comment]
Relevant team discussion: https://element.adrestia.iohkdev.io/#/room/!pVmOFJiBkItJMNTmCR:adrestia.iohkdev.io/$-unJ0isT24cCiJETY75z3G2eWQYSDYEiGXxZb-eRWao?via=adrestia.iohkdev.io

**Comment by Anviking** [comment]
Link has expired, but I presume this is fixed, or it hasn't been seen again for a while at least
