### ISSUE TITLE
Wallet is bloating address pool unnecessarily

### ISSUE THREAD

**Issue by benapetr** [cardano-foundation/cardano-wallet#3363]
### The problem that you wish to solve

Hello,

Right now due to random fund reshuffling - https://github.com/input-output-hk/cardano-wallet/issues/2614 the wallet is slowly allocating more and more addresses, which may be by design and OK for small users. But for large users (e-shops etc.) this might be a problem.

For example here is this cardano-wallet used as a backend for automated tool - which in result over ~2 months generated almost 20 000 addresses associated with same staking key - https://cardanoscan.io/addresses?stakeKey=cab9c9543b2d6a84a99b54ad67dfe7ef135e87db3fad705d18916198

while only first ~200 addresses are actually active. All other addresses just had randomly funds thrown at by cardano-wallet. That means cardano-wallet need to keep all these addresess in memory and needs to scan the blockchain for all of them in order to calculate proper balance.

This seems to be putting unnecessary load on underlying systems. There should be an option to specify address pool limit (say 1000 addressess) so that wallet can stop auto-throwing funds at last N - address_gap (20 by default) when this limit is reached so that more and more addresses are not allocated indefinitely.

I don't believe that performance of cardano-wallet is going to be very good when you reach a point where you have billions cardano addresses associated with your staking key (I presume some e-shops might be getting at billions of transactions). There is currently about 20 new addresses associated with almost every transaction generated by cardano-wallet.

### Description

Implemented address limit which if reached would stop putting funds at last N addresses to avoid allocating more of them.

**Comment by benapetr** [comment]
over 34 000 addresses now with same staking key, I am wondering when cardano-wallet starts having troubles scanning the chain with so many addresses belonging to single wallet

**Comment by benapetr** [comment]
over 110 000 addresses in single wallet and still increasing... cardano-wallet is now using over 12GB of RAM just to start and load all these addresses. Tracking of all these addresses takes immense CPU. This is a critical issue.

**Comment by benapetr** [comment]
fix for this is trivial - when submitting a TX send change always to first address in address pool, to avoid allocation of 20 more addresses. Right now wallet puts change to the bottom of address pool every time.

**Comment by HeinrichApfelmus** [comment]
This will be tackled in https://github.com/cardano-foundation/cardano-wallet/pull/4129 . We intend the "one-change-address" feature to be part of the next wallet release. Unfortunately, this does not reduce the number of change addresses used by an existing wallet, it only pertains to future address generation — but you can migrate to a new wallet to mitigate this.

**Comment by HeinrichApfelmus** [comment]
> fix for this is trivial - when submitting a TX send change always to first address in address pool, to avoid allocation of 20 more addresses. Right now wallet puts change to the bottom of address pool every time.

This feature is now part of the wallet release

https://github.com/cardano-foundation/cardano-wallet/releases/tag/v2023-12-18

I hope that this concludes the issue, feel free to reopen if you're not entirely happy.
