### ISSUE TITLE
Bech32 mixed-case mutation test fails occasionally.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#339]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Windows & OSX & Linux) | Code |

# Context
 
Occasionally, the Bech32 mixed-case mutation test fails with an error similar to:

```
  test/Codec/Binary/Bech32Spec.hs:271:26:   
  2) Codec.Binary.Bech32, Decoding a corrupted string should fail, Decoding fails for an upper-case string with a lower-case character.
       Falsifiable (after 7782 tests):   
         Bech32String {getBech32String = "]66]106205h", humanReadablePart = HumanReadablePart "]66]", unencodedDataPart = DataPart ""}
         index of mutated char: 10   
               original string: "]66]106205H"
              corrupted string: "]66]106205h"
       expected: Left StringToDecodeHasMixedCase
        but got: Right (HumanReadablePart "]66]",DataPart "")
```

# Cause

The cause of this appears to be obvious: if the generated string only has a single alphabetic character, and if we change the case of just that character, the result will **not** be a mixed-case string, and therefore decoding will not fail as expected.

# Resolution Plan

- [x] Change the precondition for the test, from `corruptedString /= originalString` to `isMixedCase corruptedString`.

# PR

| Number   | Base      |
| ---      | ---       |
| #340        | `master` |

# QA 

I believe this is the end of our trouble with the testing of `bech32`. I've re-run all the mutation tests **a million time each** without catching any problem:

```
  Decoding a corrupted string should fail
    Decoding fails when an adjacent pair of characters is swapped.
      +++ OK, passed 1000000 tests; 28494 discarded.
    Decoding fails when a character is omitted.
      +++ OK, passed 1000000 tests.
    Decoding fails when a character is inserted.
      +++ OK, passed 1000000 tests:
      94.4313% inserted into the middle
       2.7968% inserted after the end
       2.7719% inserted before the start
    Decoding fails when a single character is mutated.
      +++ OK, passed 1000000 tests; 15151 discarded.
    Decoding fails for an upper-case string with a lower-case character.
      +++ OK, passed 1000000 tests; 486352 discarded.
    Decoding fails for a lower-case string with an upper-case character.
      +++ OK, passed 1000000 tests; 486352 discarded.
```

**Comment by jonathanknowles** [comment]
Fix available: #340

**Comment by jonathanknowles** [comment]
> I believe this is the end of our trouble with the testing of bech32. I've re-run all the mutation tests a million time each without catching any problem:

:champagne:

**Comment by piotr-iohk** [comment]
> I've re-run all the mutation tests a million time each

:+1:  (thanks a million! 😁)
