### ISSUE TITLE
Latest docker-compose not compatible with preprod

### ISSUE THREAD

**Issue by melchoir55** [cardano-foundation/cardano-wallet#3465]
### Just checking...

- [X] This is a `cardano-wallet` bug.
- [X] I am using the latest `cardano-wallet` release.
- [X] I am using the *correct* `cardano-node` version for that release of `cardano-wallet`.

### Version

v2022-08-16 (git revision: 0000000000000000000000000000000000000000)

### Platform

linux (as defined by the dockerfile)

### Installation method

IOHK Docker image

### Network configuration

preprod

### Context

The latest `docker-compose` shows compatibility with NETWORK=preprod 

For example, based on the way it is written, it indicates that it will pass the correct NetworkMagic (1) and that a proper config file exists at `/config/preprod/genesis-byron.json`

However, not only does the config file not exist at that location, but the docker image does not recognize the value `preprod` as a valid value for NETWORK. Indeed, the existing docker-compose for `inputoutput/cardano-wallet:2022.8.16` appears to be broken.

## Steps to Reproduce

1. > NETWORK=preprod docker-compose up
2.
3.
...

### Expected behavior

Cardano-Wallet should connect to cardano-node running the preprod configuration.

### Actual behavior

If the preprod parameter is passed to NETWORK the image complains the value is not valid. If `testnet` is passed instead, and the configuration file is manually injected via mounting, the wrong networkmagic value will be used.

**Comment by piotr-iohk** [comment]
`inputoutput/cardano-wallet:2022.8.16` on dockerhub has been updated with the version containing new environments (preview and preprod). Perhaps you already had previous version (also tagged `2022.8.16` but without new environments) on your system and therefore it is using the old one that doesn't have those missing configs?

In that case, in that case you may want to remove old `inputoutput/cardano-wallet:2022.8.16` from your system and start docker-compose again, then new version will be downloaded. Sorry for inconvenience!

**Comment by melchoir55** [comment]
That solved this particular problem.

With respect, it is unusual to release a new image with the same tag as an old image. Most CI flows assume an image is immutable once tagged. Approaching updating your images in this way is going to cause a lot of headache for a lot of people.

**Comment by stefiix92** [comment]
sorry to bother you guys, but I ran into similar issue and I use `--preprod /configs/preprod-byron-genesis.json` command in `inputoutput/cardano-wallet:2022.8.16` docker image, but the log says: "Invalid option `--preprod'"

**Comment by piotr-iohk** [comment]
I believe what you want to use is `--testnet /configs/preprod-byron-genesis.json`.
