### ISSUE TITLE
(Instance of #3461) Flaky test: Waited longer than 90s to resolve action: "waitForNextEpoch"

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#3482]
### Please ensure:

- [X] This is actually a flaky test already present in the code and not caused by your PR.

### Context

https://github.com/input-output-hk/cardano-wallet/pull/3476#issuecomment-1232432181

### Job name

linux.musl.checks.cardano-wallet.integration

### Test case name(s)

SHELLEY_CREATE_MIGRATION_PLAN_06

### Error message

```shell
Failures:

  src/Test/Integration/Framework/DSL.hs:1056:51: 
  1) API Specifications, SHELLEY_MIGRATIONS, SHELLEY_CREATE_MIGRATION_PLAN_06 - Can create a migration plan for a wallet that has rewards.
       not yet
       Waited longer than 90s to resolve action: "waitForNextEpoch: goes to next epoch".

  To rerun use: --match "/API Specifications/SHELLEY_MIGRATIONS/SHELLEY_CREATE_MIGRATION_PLAN_06 - Can create a migration plan for a wallet that has rewards./"
```

### Build link

https://hydra.iohk.io/build/18612398

**Comment by Anviking** [comment]
Tracking as #3461
