### ISSUE TITLE
Set up proper logging

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#350]
# Context

The [iohk-monitoring-framework](https://github.com/input-output-hk/iohk-monitoring-framework) offers a set of tools including logging. We currently don't have any proper logging solution setup in our codebase. We fake it via some `TIO.putStrLn` and `sayErr` but, nothing very meaningful or production-ready. 

A simple logging solution is an event-stream of structured data output by the application on either `stdout` or `stderr`. Then, we leave it to external tools to redirect this output to files or appropriate services to parse and analyze.

# Decision

- Experiment with [iohk-monitoring-framework](https://github.com/input-output-hk/iohk-monitoring-framework) and see how the API for this module works. 
  Here's a bit of documentation regarding logging usage from cardano-shell: [docs/Usage.md](https://github.com/input-output-hk/cardano-shell/blob/develop/docs/Usage.md)

- Prepare foundation for adding logging to the wallet backend application layers (networking, wallet layer, transaction layer, db layer). This is not about adding logging in these layers for this will be part of another tasks. This is about setting up of logging framework and making it available for use within the wallet layer. We could print a single "demo" log line as an example to show how it works. See also #354 

- Logging at the API-level is excluded from the above concern and will go through a dedicated middleware. See also #352 

# Acceptance Criteria

1. It _must_ be possible to log information from within the wallet layer and, various other layer easily
3. Logging level _must_ be configurable at runtime via CLI flag 
4. Logging level _may_ be configurable at runtime via an ENV var
2. Logging _shouldn't_ be used at this stage, kept for a later story
5. On startup, the wallet _should_ write a simple "STARTED" message to the log, along with its version.
6. Although it's not within the scope of this ticket to actually implement logging for the business logic, we _should_ at least attempt to implement logging for one function somewhere deep in the guts of the codebase, so that we can verify the general approach.

# Non-Goals

We may (at some point in the future) decide to implement logging to a file. For this ticket, however, we'll _only_ log to `stdout` and `stderr`.

# Development Plan

- [x] Investigate what support [iohk-monitoring-framework](https://github.com/input-output-hk/iohk-monitoring-framework) provides for different logging levels. 
- [x] Use the logging functionality to implement real logging within functions in the Wallet layer, as a verification of the general approach. 
- [x] Make it possible to configure logging level at runtime via CLI flag
- [x] Review the use of "simple" and "text" in the logger, and use "cardano-wallet". (See https://github.com/input-output-hk/cardano-wallet/pull/412#discussion_r293746189)
- [x] On startup, output a simple message to the log that includes the current version.
- [x] For `cardano-wallet launch`: restrict the output of the wallet API server so that only log entries with severity **greater than or equal to** the specified `--min-log-severity` are written to the log. We can pass through the `--min-log-severity` parameter within the `walletCmd` function.
- [x] For `cardano-wallet launch`: restrict the output of the HTTP bridge so that only log entries with severity **greater than or equal to** the specified `--min-log-severity` are written to the log.

# PR

| Number   | Base      |
| ---      | ---       |
| #390 | `master` |
| #412 | `master` |
| #420 | `master` |
| #421 | `master` |
| #429 | `master` |
| #450 | `master `|
| [#27](https://github.com/input-output-hk/cardano-http-bridge/pull/27) ([`cardano-http-bridge`](https://github.com/input-output-hk/cardano-http-bridge)) | `master` |

# QA

**Comment by jonathanknowles** [comment]
Are there any standard structured log file formats that we could / should use? Using a pre-existing standard might mean that people can use standard tools to examine our logs.

**Comment by KtorZ** [comment]
One of them is obviously JSON, and, some other might exist. I'd suggest to have a look at what other projects are doing and what's suggested by [iohk-monitoring-framework](https://github.com/input-output-hk/iohk-monitoring-framework).

**Comment by jonathanknowles** [comment]
The [`iohk-monitoring-framework`](https://github.com/input-output-hk/iohk-monitoring-framework/) defines a number of [severity levels](https://github.com/input-output-hk/iohk-monitoring-framework/blob/b0ea8317ba5a887d46969e9b3040862a10e6efb3/iohk-monitoring/src/Cardano/BM/Data/Severity.lhs#L33-L44):

| **Severity Level** | **Meaning** |
| -- | -- |
| Debug | detailed information about values and decision flow |
| Info      | general information of events; progressing properly |
| Notice    | needs attention; something not progressing properly |
| Warning   | may continue into an error condition if continued |
| Error     | unexpected set of event or condition occurred |
| Critical  | error condition causing degrade of operation |
| Alert     | a subsystem is no longer operating correctly, likely requires manual intervention |
| Emergency | at this point, the system can never progress without additional intervention |

This design was influenced by the [`syslog` severity level](https://en.wikipedia.org/wiki/Syslog#Severity_level) taxonomy.

**Comment by jonathanknowles** [comment]
Hi @KtorZ 

Just curious if there is a business requirement for this criterion:

> Logging level may be configurable at runtime via an ENV var

If not, then perhaps we can leave this until later, in order to keep things simple. What do you think?

**Comment by KtorZ** [comment]
@jonathanknowles Just seeing your last comment. The criteria is `may`, hence this is optional. A nice-to-have if time allowed. If you'd rather keep it for later, then that's good.

**Comment by jonathanknowles** [comment]
> @jonathanknowles Just seeing your last comment. The criteria is `may`, hence this is optional. A nice-to-have if time allowed. If you'd rather keep it for later, then that's good.

I definitely think it's a good idea to keep this one for later. Users can already exert control over the verbosity through the `--quiet` and `--verbose` flags, which have the benefit of being very explicit.

**Comment by jonathanknowles** [comment]
Moving this to QA, as all the items on the development plan are now completed, and the acceptance criteria should now be satisfied (to the best of my knowledge).

**Comment by KtorZ** [comment]
(@jonathanknowles before moving it to QA, make sure to fill-in the 'QA' section with details about testing and how things are being tested, if they are :wink:)

**Comment by piotr-iohk** [comment]
Hi @jonathanknowles, indeed filled QA section would be helpful (e.g. something like here would be handy -> https://github.com/input-output-hk/cardano-wallet/issues/352).

Anyway, I've looked through PRs and comments and as far as I see (correct me if I'm wrong):
 - In the end for setting log level we can use in CLI for `launch` and `server` commands
   - no param -> log level: info
   - `--quiet` -> log level: error
   - `--verbose` -> log level: debug
 - there should be a message in the log at start of the server containing wallet's version (there is as far as I see)
 - as far as I see log level currently cannot be controlled via `ENV` (it was agreed that it's not going to be implemented now)

Maybe I missed something but actually didn't find any tests for this. (Only a note that it was manually tested that log entires are filtered and some roundtrip tests for severity levels, btw. are they still needed after we went for `--quiet` and `--verbose` https://github.com/input-output-hk/cardano-wallet/blob/master/lib/cli/test/unit/Cardano/CLISpec.hs#L53?)

I think that we could add integration tests for checking log levels (i.e. that when `--verbose` output contains `info` and `debug` entries etc.) and also checking if the version on the start apears in the log.
I can look into that.

Can you please also clarify on the following points (I mean have they been addressed and/or how):

> 4. Logging shouldn't be used at this stage, kept for a later story

> 6. Although it's not within the scope of this ticket to actually implement logging for the business logic, we should at least attempt to implement logging for one function somewhere deep in the guts of the codebase, so that we can verify the general approach.

**Comment by piotr-iohk** [comment]
Ok, I've added some tests under #474. Will add more (for launcher) tomorrow.

**Comment by piotr-iohk** [comment]
> @KtorZ KtorZ closed this 3 days ago

Well, I didn't want to close this one until #474 gets merged...

**Comment by KtorZ** [comment]
@piotr-iohk sorry about that!
On fridays, I sometimes close some of the ticket to get Zenhub updated and do some predictions on what can be the work of next week. Seems like I forgot to re-open them this time :/

I should have reopened the relevant stuff though I am commuting at the moment; I'll have a second look once I get my hand on a laptop.

**Comment by piotr-iohk** [comment]
:+1:
