### ISSUE TITLE
Define and document logging semantics

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#351]
# Context

One of the hardest question to answer when it comes to logging is what NOT to log, and when logging, to which degree? What is an error? What is an info? 

# Decision

- Document as a coding standard the semantics we give to various log levels
- Have a few examples for each level
- Have a few examples of things NOT to log
- Define what is private and shouldn't appear in the log

# Acceptance Criteria

1. We _must_ document our semantics for logging
2. This _should_ be documented in the [Coding Standard](https://github.com/input-output-hk/cardano-wallet/wiki/Coding-Standards)
3. If too verbose, this _may_ be documented in its own wiki page.

---

# Development Plan

1. Put the draft document in a separate wiki page, then move to Coding Standard when finalised.
2. Log level examples should be straightforward.
3. More difficult will be finding examples of private/sensitive/non-private information. Search for examples then ask people on slack where/how they ought to be logged.

# PR/Wiki Page

[Logging Guidelines](https://github.com/input-output-hk/cardano-wallet/wiki/Logging-Guidelines)

# QA 

- Documented reviewed by various peers outside of the wallet backend team.
- The document will likely be an ever-evolving document and updates / refinements will follow.

**Comment by KtorZ** [comment]
Good ideas / people to have discussion with:

- Technical Support Desk
- Daedalus
- Duncan

**Comment by jonathanknowles** [comment]
The [`iohk-monitoring-framework`](https://github.com/input-output-hk/iohk-monitoring-framework/) defines a number of [severity levels](https://github.com/input-output-hk/iohk-monitoring-framework/blob/b0ea8317ba5a887d46969e9b3040862a10e6efb3/iohk-monitoring/src/Cardano/BM/Data/Severity.lhs#L33-L44):

| **Severity Level** | **Meaning** |
| -- | -- |
| Debug | detailed information about values and decision flow |
| Info      | general information of events; progressing properly |
| Notice    | needs attention; something not progressing properly |
| Warning   | may continue into an error condition if continued |
| Error     | unexpected set of event or condition occurred |
| Critical  | error condition causing degrade of operation |
| Alert     | a subsystem is no longer operating correctly, likely requires manual intervention |
| Emergency | at this point, the system can never progress without additional intervention |

This design was influenced by the [`syslog` severity level](https://en.wikipedia.org/wiki/Syslog#Severity_level) taxonomy.

**Comment by rvl** [comment]
Privacy section needs to be updated with our simpler plan, and TSD may yet have some input.

**Comment by KtorZ** [comment]
Closing the ticket since the document exists and has been reviewed by a few already; It will be refined over time and make more precise as we demand it.
