### ISSUE TITLE
Middleware for API logging

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#352]
# Context

Server and API logging are somewhat special. They provide little insights about the internals of the application as they only log the user-visible part. Still, they are very useful to have when debugging in order to trace back what users have been doing and better understand what caused some other application logs.

# Decision

- Create a new Wai middleware to log request and response from the server. Make sure 
  to hide sensitive information such as:
  - passphrases
  - mnemonic words

- The log should include:
   - The full request body (minus sensitive information)
   - The full response body
   - The request URL 
   - The request query parameters if any

- Associate a unique id to request and their corresponding response. This could be done via a specific header `X-Request-Id` added upfront and looked up when the response is sent.

- For each request / response, also log the total processing time, in second or millisecond.

# Acceptance Criteria

1. A new middleware _must_ be define to add logging to the API.
2. Logs _must_ include response time in second or millisecond 
3. In logs, requests and responses _must_ share a unique id to be easily identifiable
4. Sensitive information _mustn't_ be logged. This includes and is limited to:
    - passphrase
    - mnemonic_sentence
    - mnemonic_second_factor
5. Apart from sensitive information, logs _should_ include the full request body and response, in JSON format.

---

# Development Plan

- [x] Define a request logger using [setLogger](https://hackage.haskell.org/package/warp-3.2.27/docs/Network-Wai-Handler-Warp.html#v:setLogger)
- [x] Augments the request with a `X-Request-Id` and a `X-Request-Timestamp` to hold respectively, a unique request ID and a corresponding POSIX timestamp in seconds
- [x] Define a middleware to log response from the API including the request Id and the response time 
- [x] Tweak loggers to not log sensitive details from requests
- [x] Adjust logging details according to the severity:
    - debug = everything
    - info = don't log the request and response bodies
    - alert = log only 500 errors 
- [x] Experiment with testing in this area :thinking: ?
    - [x] Implement a small mock server with dummy endpoints
    - [x] Collect log lines in a "pure" logger (`TVar` target available)
    - [x] Check log lines match expectations
    - [x] Add extra test to control that the request-id 

# PR

| Number   | Base      |
| ---      | ---       |
| #430        | `master` |
| #432        | `master` |
| #438        | `master` |
| #441        | `master` |

# QA 

- Logging middleware tested against a mock server in [Network.Wai.Middleware.LoggingSpec](https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Network/Wai/Middleware/LoggingSpec.hs). The tests checks several things:
    - Check that we indeed log what we expect from various dummy endpoints, for different HTTP verb, with and without query parameter, with and without request and / or response body etc, with invalid payload. We check both the content and the severity.
    - Check that top-level fields flagged as "sensitives" aren't displayed in logs. 
    - Check that every request / response gets assigned a unique id that appears in the log handle's name
    - Check that response time is measured correctly (using an arbitrary "long" endpoint order of magnitudes longer than others).

- Examples of log lines given in PRs:

```
[iohk.cardano-wallet.serve.api.request-0:Info:ThreadId 27]  [2019-06-18 15:28:37.82 UTC] [PUT] /v2/wallets/2512a00e9653fe49a44a5886202e24d77eeb998f
[iohk.cardano-wallet.serve.api.request-0:Debug:ThreadId 27] [2019-06-18 15:28:37.82 UTC] {"name":"patate"}
[iohk.cardano-wallet.serve.api.request-0:Info:ThreadId 27]  [2019-06-18 15:28:37.82 UTC] 404 Not Found in 0.000608631s
[iohk.cardano-wallet.serve.api.request-0:Debug:ThreadId 27] [2019-06-18 15:28:37.82 UTC] {"code":"no_such_wallet","message":"I couldn't find a wallet with the given id: 2512a00e9653fe49a44a5886202e24d77eeb998f"}

[iohk.cardano-wallet.serve.api.request-1:Info:ThreadId 29]  [2019-06-18 15:29:06.23 UTC] [POST] /v2/wallets
[iohk.cardano-wallet.serve.api.request-1:Debug:ThreadId 29] [2019-06-18 15:29:06.23 UTC] {"passphrase":"*****","address_pool_gap":20,"name":"MyWallet","mnemonic_sentence":"*****"}
[iohk.cardano-wallet.serve.api.request-1:Info:ThreadId 29]  [2019-06-18 15:29:06.41 UTC] 202 Accepted in 0.184808431s
[iohk.cardano-wallet.serve.api.request-1:Debug:ThreadId 29] [2019-06-18 15:29:06.41 UTC] {"passphrase":{"last_updated_at":"2019-06-18T15:29:06.348875675Z"},"address_pool_gap":20,"state":{"status":"restoring","progress":{"quantity":0,"unit":"percent"}},"balance":{"total":{"quantity":0,"unit":"lovelace"},"available":{"quantity":0,"unit":"lovelace"}},"name":"MyWallet","delegation":{"status":"not_delegating"},"id":"5f0e194ed385de1c87fb63c74802dd223637440f"}
```

**Comment by piotr-iohk** [comment]
@KtorZ

The unit tests using mock server are very nice. Perhaps we could also have few cases in integration environment in particular for checking if sensitive info is not logged (passphrase, mnemonic, mnemonicsnd). So at least for creating wallet, updating passphrase, posting transaction. What do you think?

Also, probably not related, but I noticed that there is a tone of queries logged in `DEBUG` for practically every operation. Not sure if that's good or bad that there's so many, but they are polluting the log quite heavily. For that matter maybe it would be worth moving request's payload and response data to `INFO`? Not sure, any thoughts?

**Comment by KtorZ** [comment]
> The unit tests using mock server are very nice. Perhaps we could also have few cases in integration environment in particular for checking if sensitive info is not logged (passphrase, mnemonic, mnemonicsnd). So at least for creating wallet, updating passphrase, posting transaction. What do you think?

A bit tricky to setup to be honest :thinking: ... If we turn on logging in the integration tests, they're going to become quite noisy. There's also the option of spinning up another wallet that has logging enabled in a TVar too. Though to be honest, I think it's a bit overkill here since it doesn't buy us much than the `unit` tests (since this is already what the unit tests are testing! So we would just be duplicating code and testing the same things).

I actually had an hesitation on _where_ to put those tests initially since we are already dealing with an actual Wai application and servant server in the tests, they probably belong more to the "integration" side than the unit side to be honest. 

> Also, probably not related, but I noticed that there is a tone of queries logged in DEBUG for practically every operation. Not sure if that's good or bad that there's so many, but they are polluting the log quite heavily. For that matter maybe it would be worth moving request's payload and response data to INFO? Not sure, any thoughts?

Well, that's a bit the point of the `DEBUG` level. We only logs request and response payloads in that mode, so it's not _too_ noisy. But that's indeed not something you would want in production in a standard mode. Likely, this is something users turn on  temporarily to be able to debug what's going on with their server. In the end, per request, it's only two lines, one for the request, one for the response.

**Comment by piotr-iohk** [comment]
Ok, acknowledged that mechanism works and is well tested. I'm just a bit concerned that there is no check that it works in _real_ code... (like, when someone makes some unintentional change in the future and suddently it stops hiding sensitive info... but maybe that's too pesimistic). Maybe, just to be safe, a _stupid_ unit test checking the contents of -> https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/src/Cardano/Wallet/Api/Server.hs#L180-L187 ?

**Comment by KtorZ** [comment]
> suddently it stops hiding sensitive info... but maybe that's too pesimistic

Well, the thing is that the list of things we should hide isn't specific to the logging module. And, we could also hard-code the list of sensitive things and verify in the tests that what we have in the test isn't shown in logs but.. it doesn't really prevent us from making any mistake here since this wouldn't catch:

- parameter that are renamed
- new parameters that are added
- old parameters that are removed

If we _really_ wanted some strong guarantee on these, I'd rather defer that check to the compiler and embed something in the servant API type direction; some sort of meta information that tells what field in the API are sensitive and which ones aren't. With this, we could write some code that automatically guarantees that every parameter from the `API` labelled as "sensitive" is left out, and because there's only a single source of truth (a.k.a the API annotation), we can have test also checking for these without the risk of any discrepancy. 

That's definitely something to imagine. Not sure if the trade-off complexity / gain is worth it :thinking: ... Perhaps, that's one thing to add to the release notes or manual tests: 

- to control that the list of sensitive values is still accurate ?

**Comment by piotr-iohk** [comment]
>Perhaps, that's one thing to add to the release notes or manual tests

That sounds good too (and would make me sleep better...) ;)

**Comment by KtorZ** [comment]
Added an entry in the release checklist :+1: (see https://github.com/input-output-hk/cardano-wallet/wiki/Release-Checklist)
