### ISSUE TITLE
Review and add logging into the application layer

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#354]
# Context

Our application lacks helpful logging that would improve diagnosis of errors or bad behaviours over time. According to the semantics defined in #351 and the logging capability introduced in #350, we should be able to provide insights for various pieces of the wallet back-end, where it makes sense. 

# Decision

- Replace existing "fake" logging attempts like `say` or `putStrLn` by actual logs, with a relevant log-level
- Add logging on the application critical path with relevant information, in particular on failures.

# Acceptance Criteria

1. As developers and maintainers, we _must_ have a total understanding of what is going on within our application when running. 

2. The semantics for the verbosity level _must_ be respected such that logging can be adjusted at will to increase the amount of detail we get from the application.

3. Logging _shouldn't_ impact application performance more than what's reasonable. In other words, it shouldn't be possible to detect that logging is happening when using the wallet's functionality.   

---

# Development Plan

- [x] Review each function from the wallet layer. For each, analyze what's worth logging and at which severity.
    - [x] createWallet
    - [x] readWallet
    - [x] updateWallet
    - [x] updateWalletPassphrase
    - [x] listWallets
    - [x] removeWallet
    - [x] restoreWallet
    - [x] listAddresses
    - [x] createUnsignedTx
    - [x] signTx
    - [x] submitTx
    - [x] attachPrivateKey

# PR

| Number   | Base      |
| ---      | ---       |
| #485        | `master`  |
| #448 | `master` |
| #492 | `master` |

# QA 

- We've reviewed logs within the application layer to make sure we log informations of interested. This is a never-ending process and we'll iterate as we get feedback from users (TSD, Daedalus) but for a start, we are now already getting some nice insights.

- We have also greatly improved logs we get from the database, using various level of severity depending on the type of logs (see: https://github.com/input-output-hk/cardano-wallet/pull/492/files)

**Comment by jonathanknowles** [comment]
@KtorZ Is the [IOHK monitoring framework](https://github.com/input-output-hk/iohk-monitoring-framework) relevant to our needs for this?

**Comment by KtorZ** [comment]
Yes, see #350

**Comment by piotr-iohk** [comment]
>@KtorZ KtorZ closed this 3 days ago

Hm, I don't remember reviewing this, also #492 has been referenced to this item after closing. Should this be still in progress?

**Comment by piotr-iohk** [comment]
lgtm
