### ISSUE TITLE
Improve context and details of existing errors

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#355]
# Context

Many of our application errors are poorly self-documenting. For instance, when the network is unreachable, we get a `ErrNetworkUnreachable Text` where this `Text` is raw network error without any context. 
Another example, when we fail to select coins because there's not enough money, we return a `ErrNotEnoughMoney Word64 Word64` capturing the available UTxO amount and the payment amount.  

In the first example, it could be useful to know what endpoint we were trying to reach, and with which request. Perhaps even, we could parse this `Text` to identify whether in some cases, retrying could help. etc..

In the second example, what's particularly interesting to know in practice is details about the transaction. How many inputs? How many outputs? Their size? What's the UTxO distribution, etc...

These are not details we necessarily want to put in the server response, but, that are useful to have in the logs when debugging and trying to pinpoint an issue. 

# Decision

- Review existing errors and enhance the context and details we give for each
- Introduce new errors when relevant, that are more fine-grained and better described ambiguous situation

# Acceptance Criteria

1. Errors and failures _must_ come with additional context that make debugging easier
2. Context for errors _may_ be printed and scattered across multiple messages, bound together via a common reference or context (e.g. a request id).

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #?       | `master`  |

# QA

**Comment by jonathanknowles** [comment]
@KtorZ I'm guessing the first task here would be to build a complete list of these errors, and for each error, specify the metadata we intend to attach to it. (This could be reviewed separately, before actually attempting to implement the change.)

**Comment by KtorZ** [comment]
Sounds like a good start for a development plan indeed :smile:

**Comment by KtorZ** [comment]
Closed. As discussed, this will be an ongoing work we'll do as part of refining our logging and error types as we ran into issues that aren't sufficiently detailed with context.
