### ISSUE TITLE
Allow filtering by address state when fetching all addresses

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#356]
# Context

In order to test transaction creation and submission, earlier on we had to implement the ability to list known addresses from the API. However, according to the specification, we should be able to filter known addresses by state (used vs unused). 

See: [Api Doc - listAddresses](https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/listAddresses)

# Decision

- Allow filtering by address state when fetching all addresses

# Acceptance Criteria

1. Query parameter `state` _must_ be supported by the API layer
2. The Command line interface _must_ have new option flags `--only-used` and `--only-unused` or an option `--state=used|unused` to filter accordingly.

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #372      | `master`  |
| #395      | `master`  |

# QA 

#395 introduces integration tests against CLI and API for listing addresses with filters (tagged `ADDRESS_LIST_02`):
CLI: https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/integration/Test/Integration/Scenario/CLI/Addresses.hs#L77-L134
API: https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/integration/Test/Integration/Scenario/API/Addresses.hs#L86-L132

**Comment by jonathanknowles** [comment]
@KtorZ Can we rename this task to something like:

> "Allow filtering by address state when fetching all addresses"

(It seems clearer than the current title, which appears to describe a side effect of completing this task.)

**Comment by jonathanknowles** [comment]
Fix available: https://github.com/input-output-hk/cardano-wallet/pull/372

**Comment by piotr-iohk** [comment]
@jonathanknowles it seems to be ready to move to QA? (related integration tests added in #395)

**Comment by jonathanknowles** [comment]
> @jonathanknowles it seems to be ready to move to QA? (related integration tests added in #395)

Yes, I believe this one is finished.

**Comment by KtorZ** [comment]
Then let's fill in the QA section properly and move it to the appropriate section :pray:

**Comment by piotr-iohk** [comment]
Done. Implemented & tested. :+1:
