### ISSUE TITLE
Repo Preparation for MBO

### ISSUE THREAD

**Issue by ThatGuyLLC** [cardano-foundation/cardano-wallet#3569]
### The problem that you wish to solve

This repo has been marked as core tech and is part of initiative of repo preparation, part of this includes adding needed missing documentation.

### Description

This repo in particular needs:
Include the Standard Code of Conduct
Identify the Core Maintainers

### Implementation suggestions

This repo in particular needs:
Include the Standard Code of Conduct
Identify the Core Maintainers

**Comment by HeinrichApfelmus** [comment]
Closing as no longer relevant. The repo has moved to the Cardano Foundation.
