### ISSUE TITLE
Integration tests on Jörmungandr

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#358]
# Context

Our integration test scenarios (see [Test/Integration/Scenario](https://github.com/input-output-hk/cardano-wallet/tree/master/lib/http-bridge/test/integration/Test/Integration/Scenario)) describe interactions with the API or CLI and expectations from these interactions. In practice, most of these scenarios are backend-agnostic and, we should be able to replay most of them for either `cardano-http-bridge` or `jörmungandr`. 

PR #334 already makes a first step in that direction by moving the `Network` environment and backend-specific bits up-to the integration main file, leaving the scenarios really just about the interactions with the API or CLI.

# Decision

- Move the integration framework (DSL & Request) from the `http-bridge` module to `core`.
- Set up integration tests in jörmungandr and replay all scenarios using jörmungandr as a backend target (while still playing all the scenarios for the bridge). 
- We'll probably need to adapt the `Faucet` module as well although a similar approach should be possible with Jörmungandr too. 

# Acceptance Criteria

1. Integration tests scenarios _must_ still run for the http-bridge
2. Integration tests scenarios _must_ run for jörmungandr
3. Some scenarios that are too backend-specific _may_ be disabled and/or duplicated for their corresponding backend.

---

# Development Plan

- [x] I intend to extend the move DSL and Request to the core in order to reuse them both at http-bridge and jormungandr
- [x] I intend to deliver faucet scaffolding for jormungandr that will work with small amount of work when tx API is finalized
- [x]  I intend to make integration tests scenarios passing with jörmungandr
# PR

| Number   | Base      |
| ---      | ---       |
| #396        | `master`  |
| #424        | `master`  |
| #454        | `master`  | 
| #470        | `master`  |
| #471        | `master`  |
| #473        | `master` |
| #475        | `master` |
| #496        | `master` |
| #504        | `master` |
| #506        | `master` |
| #509        | `master` |

# QA 

- Integration tests have been ported, adjusted and are running in CI (https://github.com/input-output-hk/cardano-wallet/blob/master/lib/jormungandr/test/integration/Main.hs#L108-L136)

- We have a similar setup as the bridge, running test against both the API and the CLI. 

- We can probably add more tests that are Jörmungandr-specific, since the CLI is a bit different and, there are now two address encoding formats; this is rather out-of-scope for this ticket though I believe and I'd suggest to tackle that as debts or, in a new story.

**Comment by piotr-iohk** [comment]
lgtm :+1:
