### ISSUE TITLE
testnet Support with cardano-wallet

### ISSUE THREAD

**Issue by mhassan102** [cardano-foundation/cardano-wallet#3586]
### The problem that you wish to solve

Can we have documentation for executing cardano-wallet on `testnet` network ?

### Description

`testnet` config seems to missing in cardano-wallet latest version.

I tried following execute following docker-compose:
```
export NETWORK=testnet
docker-compose up -d
```
and face this error:
```
cardano-wallet_1  | [cardano-wallet.main:Error:4] [2022-10-30 18:42:25.36 UTC] Failed to parse Byron genesis configuration. You may want to check the filepath given via --genesis and make sure it points to a  valid JSON Byron genesis file. The genesis file must be Byron, not Shelley as it used to feed the wallet with the initial blockchain parameters. Here's (perhaps) some helpful hint: GenesisDataIOError /config/testnet/genesis-byron.json: openBinaryFile: does not exist (No such file or directory)
```

Inside container I didn't find `testnet` config
```
bash-5.1# ls config/
mainnet  preprod  preview  shelley_qa  staging
``` 

volumes for `testnet` also missing in docker-compose

**Comment by mgajda** [comment]
It is much safer to test transaction submission on testnet, rather than playing with real Adas.
#migamake

**Comment by piotr-iohk** [comment]
Yes, you can use `cardano-wallet` on preprod and preview testnets.
```
NETWORK=preprod docker-compose up
NETWORK=preview docker-compose up
```
(:warning: `preview` testnet has been forked to cardano-node 1.35.4 with which current cardano-wallet is not yet compatible, but preprod should work fine)

See also: 
 - https://book.world.dev.cardano.org/environments.html
 - https://docs.cardano.org/cardano-testnet/tools/faucet

**Comment by piotr-iohk** [comment]
Note: Configs for old `testnet` have been intentionally removed as it is a legacy network which I believe doesn't work anyway on any node version >= 1.35.3.

**Comment by mgajda** [comment]
Thanks a lot!

Since we want maximum stability of our tests, and `preprod` is long running network, we will use `preprod` for our wallet tests.

**Comment by mhassan102** [comment]
Thanks for the support
