### ISSUE TITLE
Transaction chaining after another transaction or after certain block hash

### ISSUE THREAD

**Issue by mgajda** [cardano-foundation/cardano-wallet#3604]
### The problem that you wish to solve

If we have just received the block or transaction with a specific hash, and we want to make another transaction _only if the previous has been confirmed_.

### Description

We would like to create or submit transaction after a fixed _block number_ **and** _hash_, or after a fixed _transaction id_ and _block number_.

In case of transactions, this is called _transaction chaining_ and may greatly improve performance.
In case of blocks, this enables other blockchain players to react much quicker to certain blockchain events.

In both cases it would greatly improve performance, while allowing _higher_ level of safety than submission of transaction without such dependency.

### Implementation suggestions

This would require additional arguments to `cardano-wallet` CLI that would enable these.

**Comment by HeinrichApfelmus** [comment]
Unfortunately, this feature is out of scope for cardano-wallet. There are various solutions for making multiple transactions, e.g. [DripDropz](https://news.dripdropz.io/).
