### ISSUE TITLE
Transaction with amount 0 on http bridge fails with error HTTP 500 

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#364]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Linux | Code  v Configuration v Environment v Human v Unknown |

# Context
 
The transaction with 0 amount on Byron node should fail more gracefully than HTTP 500. cf https://github.com/input-output-hk/cardano-wallet/pull/335#discussion_r288165883

# Steps to Reproduce

Run transaction with 0 amount from API or CLI.

## Expected behavior

There should be an error (perhaps HTTP 400 or 403 on the API) and a graceful error message about 0 amount transaction not being supported on Byron node.

## Actual behavior
`HTTP 500`
```
That's embarassing. It looks like I've created an invalid transaction that could
not be parsed by the node. Here's an error message that may help with 
debugging: Transaction failed verification: output with no credited value
```
 

---

# Resolution Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #445       | `master` |

# QA 

- Added a new error branch when creating transaction, now triggered from the `http-bridge` and tested via an integration test (see [TRANS_CREATE_09](https://github.com/input-output-hk/cardano-wallet/blob/d18adfb25746e7ecec1fb5a6ac8dde306ab62839/lib/core/test/integration/Test/Integration/Scenario/API/Transactions.hs#L697-L717))

**Comment by paweljakubas** [comment]
I added the test and we have :  
```
  test/integration/Test/Integration/Framework/DSL.hs:243:5: 
  1) Transactions API endpoint tests, TRANS_CREATE_06 - Invalid amount, Quantity = 0
       expected: Status {statusCode = 400, statusMessage = "Bad Request"}
        but got: Status {statusCode = 403, statusMessage = "Forbidden"}
```
So it is probably proper behaviour -> Forbidden = 403

**Comment by paweljakubas** [comment]
tough we have message : 
```
"{\"code\":\"cannot_cover_fee\",\"message\":\"I'm unable to adjust the given transaction to cover the associated fee! In order to do so, I'd have to select one or more additional inputs, but I can't do that without increasing the size of the transaction beyond the acceptable limit. Note that I am only missing 158018 Lovelace.\"}"
```

**Comment by piotr-iohk** [comment]
Looking good. Just added few more scenarios in https://github.com/input-output-hk/cardano-wallet/pull/458
