### ISSUE TITLE
NETWORK=testnet docker-compose up does not work

### ISSUE THREAD

**Issue by dorijan** [cardano-foundation/cardano-wallet#3674]
### Just checking...

- [X] This is a `cardano-wallet` bug.
- [X] I am using the latest `cardano-wallet` release.
- [X] I am using the *correct* `cardano-node` version for that release of `cardano-wallet`.

### Version

2022.12.14

### Platform

ubuntu 22.04

### Installation method

IOHK Docker image

### Network configuration

testnet

### Context

I am trying to start a testnet for cardano-wallet

## Steps to Reproduce

1. NETWORK=testnet docker-compose up
2. got error: ERROR: Named volume "node-testnet-db:/data:rw" is used in service "cardano-node" but no declaration was found in the volumes section.
...

### Expected behavior

cardano wallet and node on testnet should start

### Actual behavior

got error: ERROR: Named volume "node-testnet-db:/data:rw" is used in service "cardano-node" but no declaration was found in the volumes section.

**Comment by piotr-iohk** [comment]
Network `testnet` is deprecated. Please use `preprod` or `preview` testnet networks.
```
NETWORK=preview docker-compose up
NETWORK=preprod docker-compose up
```
More about environments: https://book.world.dev.cardano.org/environments.html.
