### ISSUE TITLE
Building cardano-wallet fails on Windows: 'specifications/api/swagger.yaml' does not match any files.

### ISSUE THREAD

**Issue by Displee** [cardano-foundation/cardano-wallet#3677]
### Just checking...

- [X] This is a `cardano-wallet` bug.
- [X] I am using the latest `cardano-wallet` release.
- [x] I am using the *correct* `cardano-node` version for that release of `cardano-wallet`.

### Version

2022.12.14

### Platform

Windows 10/11

### Installation method

Built from source

### Network configuration

Not configured

### Context

I'm getting the following error:
```
cabal-3.6.2.0.exe: sdist of cardano-wallet-2022.12.14: filepath wildcard
'specifications/api/swagger.yaml' does not match any files.
```

### Description

To reproduce:
1. Get on a Windows 10/11 machine
2. Clone the repo
3. Run `cabal build`

**Comment by Displee** [comment]
I worked around this by installing WSL and running Ubuntu and doing everything in there.

**Comment by HeinrichApfelmus** [comment]
Please use Linux for building. We cross-compile to Windows. 🤓
