### ISSUE TITLE
Wallet takes too long to sync

### ISSUE THREAD

**Issue by karthik947** [cardano-foundation/cardano-wallet#3678]
### Just checking...

- [X] This is a `cardano-wallet` bug.
- [X] I am using the latest `cardano-wallet` release.
- [X] I am using the *correct* `cardano-node` version for that release of `cardano-wallet`.

### Version

v2022-12-14

### Platform

Windows 11

### Installation method

Built from source

### Network configuration

mainnet

### Context

I downloaded the docker-compose.yml and spun up the node on the mainnet network. I then tried to sync a wallet that was created on Yoroi a week ago. The wallet restored successfully but the balance and transactions are not reflected. I waited for the wallet to sync but it takes forever to sync. After about 70% the sync gets frozen and when I leave the laptop aside for a while, it stops and resyncs from the start.

Is there a faster/better way to restore an existing wallet  ?

## Steps to Reproduce

1.Sping up the a container using docker-compose up NETWORK=mainnet
2.Restore a wallet that was created on Yoroi
3.
...

### Expected behavior
The wallet should restore and sync 100%

### Actual behavior
The wallet sync stuck at 70%

**Comment by MatthewDEVi** [comment]
Talk to Cardano Support on the Support :[Cardano Live Support](https://explore-cardano.org/) so that your issue can be looked into.

**Comment by zhp1254** [comment]
Status: syncing, Progress: {Quantity:99.8 Unit:percent}  for a long time too

**Comment by MatthewDEVi** [comment]
have you been able to resolve your issue with the support?

**Comment by hiiamtrong** [comment]
I had a similar situation. Took 2 days just from 50% - > 52%

**Comment by hiiamtrong** [comment]
This issue was resolved after I deleted the unused wallets. It is possible that there are too many synchronized wallets leading to reduced performance

**Comment by learncardano** [comment]
Yes this is a real pain. Creating multiple wallets for different users with Cardano Wallet CLI takes forever to sync. This is not helpful for our use case. Not recommended to use Wallet CLI for building a dApp for hundred thousands of users with individual wallets.

**Comment by HeinrichApfelmus** [comment]
We hope that the Deposit Wallet in progress will fix performance issues like this.
