### ISSUE TITLE
Merge `cardano-wallet-launcher` into `cardano-wallet`

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#368]
# Context

We currently maintain two separate executables as we historically needed to have a separate
process for launching and monitoring both the wallet server and its backend node. It was recently agreed with Daedalus' team that in the long run, Daedalus will be managing both processes itself and would only require the wallet to take care of itself. 

# Decision

- Moving towards this direction, we agreed on making the launcher a command of the `cardano-wallet` CLI instead of a new executable. This will make the support of multiple target backend slightly easier (having to maintain ultimately 3 executables instead of 6, and having the ability to simply remove the `launcher` command once Daedalus takes care of these bits). 

- Friendly reminder to also update the .travis.yml file to make sure we adjust the build artifacts on releases.

# Acceptance Criteria

1. `cardano-wallet` _must_ have a new command `launcher` doing what `cardano-wallet-launcher` currently does
2. `cardano-wallet-launcher` _mustn't_ exist anymore

---

# Development Plan

- [x] Create a new `launch` command in `cardano-wallet`
- [x] Remove everything related to `cardano-wallet-launcher`
- [x] Replace tests to use `cardano-wallet launcher` instead of `cardano-wallet-launcher`
- [x] Review port validation (see #422)

# PR

| Number   | Base      |
| ---      | ---       |
| #414        | `master`  |
| #422  | `master` |

# QA 

- There's no more `cardano-wallet-launcher` but a new `launch` command on `cardano-wallet`. Various tests and documentation bits have been updated to reflect that new setup.

- There was some issues with the `--port` validation also fixed as part of this ticket (with corresponding tests at both the cli-level and the unit level).

**Comment by jonathanknowles** [comment]
@KtorZ 

> cardano-wallet must have a new command launcher doing what cardano-wallet-launcher currently does

If commands are verbs, the perhaps we should call this command `cardano-wallet launch`?

**Comment by piotr-iohk** [comment]
lgtm
