### ISSUE TITLE
CLI is not very helpful when arguments are missing.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#371]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Windows & OSX & Linux) | Code |

# Context

When the user issues a CLI command **but forgets one of the required arguments**, the CLI prints the **entire** help string and then exits.

It would be more helpful to the user if the CLI could instead point out **which** arguments are missing.

# Steps to Reproduce

Consider the following command:
```
$ cardano-wallet address list 2512a00e9653fe49a44a5886202e24d77eeb998f
```
The final positional parameter is the `wallet-id` parameter.

Now suppose we **omit** that parameter, and instead issue the following command:
```
$ cardano-wallet address list
```

## Expected behavior

The CLI gives the user feedback that is **specific** and **relevant**, perhaps similar to:
```
$ cardano-wallet address list

Error: missing parameter <wallet-id>.

Usage: cardano-wallet address list [--port=INT] [--state=STRING] <wallet-id>
```

## Actual behavior
 
The CLI prints out the **entire** help string, with no specific help to identify what went wrong:

<details><summary>See more</summary>
<p>

```
$ cardano-wallet address list

Cardano Wallet CLI.

The CLI is a proxy to the wallet server, which is required for most
commands. Commands are turned into corresponding API calls, and submitted
to an up-and-running server. Some commands do not require an active server
and can be run "offline". (e.g. 'generate mnemonic')

    ⚠️  Options are positional (--a --b is not equivalent to --b --a) ! ⚠️

Usage:
  cardano-wallet server [--network=STRING] [--port=INT] [--bridge-port=INT]
  cardano-wallet mnemonic generate [--size=INT]
  cardano-wallet wallet list [--port=INT]
  cardano-wallet wallet create [--port=INT] <name> [--address-pool-gap=INT]
  cardano-wallet wallet get [--port=INT] <wallet-id>
  cardano-wallet wallet update [--port=INT] <wallet-id> --name=STRING
  cardano-wallet wallet delete [--port=INT] <wallet-id>
  cardano-wallet transaction create [--port=INT] <wallet-id> --payment=PAYMENT...
  cardano-wallet address list [--port=INT] [--state=STRING] <wallet-id>
  cardano-wallet -h | --help
  cardano-wallet --version

Options:
  --port <INT>                port used for serving the wallet API [default: 8090]
  --bridge-port <INT>         port used for communicating with the http-bridge [default: 8080]
  --address-pool-gap <INT>    number of unused consecutive addresses to keep track of [default: 20]
  --size <INT>                number of mnemonic words to generate [default: 15]
  --payment <PAYMENT>         address to send to and amount to send separated by @: '<amount>@<address>'
  --network <STRING>          testnet, staging, or mainnet [default: testnet]
  --state <STRING>            address state: either used or unused

Examples:
  # Create a transaction and send 22 lovelace from wallet-id to specified addres
  cardano-wallet transaction create \
    2512a00e9653fe49a44a5886202e24d77eeb998f \
    --payment 22@Ae2tdPwUPEZ...nRtbfw6EHRv1D
```

</p></details>

# Resolution Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #?       | `develop` |

# QA

**Comment by piotr-iohk** [comment]
I remember there was a similar point about showing CLI help (along with some other minor improvements to the CLI) on https://github.com/input-output-hk/cardano-wallet/wiki/Blackboard and we even discussed it on one of the meetings. I don't see it anymore however, I don't remember if it was supposed to land as a ticket (but I don't see ticket either) (@KtorZ?)

**Comment by KtorZ** [comment]
This is now on our [roadmap](https://github.com/input-output-hk/cardano-wallet/wiki/Roadmap#improvements-to-the-cli). As a consequence, I'll close this ticket and point to that roadmap instead. This is a known issue that we'll eventually tackle :+1:
