### ISSUE TITLE
Preview testnet error for cardano-wallet

### ISSUE THREAD

**Issue by nilaysaha** [cardano-foundation/cardano-wallet#3722]
### Just checking...

- [X] This is a `cardano-wallet` bug.
- [X] I am using the latest `cardano-wallet` release.
- [X] I am using the *correct* `cardano-node` version for that release of `cardano-wallet`.

### Version

v2022-12-14 (git revision: bbf11d4feefd5b770fb36717ec5c4c5c112aca87)

### Platform

Linux nft-srv-1 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Installation method

Binary from GitHub release page

### Network configuration

preview testnet

## Steps to Reproduce

Run the following script:

CARDANO_WALLET="$HOME/<path-to>/cardano-wallet"
CONFIG_FILE="$HOME/<path-to>/preview/byron-genesis.json"
DB_DIR="$HOME/wallets/db"
SOCKET="$HOME/<path-to>/node.socket"

$CARDANO_WALLET serve --port 8090 --testnet $CONFIG_FILE --database $DB_DIR --node-socket $SOCKET

Replace the variables as you need in your local env.

### Expected behavior

Should have run without error.

### Actual behavior

[cardano-wallet.network:Warning:17] [2023-01-30 20:12:30.57 UTC] Delegation Rewards node client: Node connection lost because of the mux error (MuxBearerClosed): <socket: 14> closed when reading data, waiting on next header True
Jan 30 21:12:31 nft-srv-1 start_cw_local_node.sh[2339735]: [cardano-wallet.network:Warning:17] [2023-01-30 20:12:31.08 UTC] Delegation Rewards node client: Couldn't connect to node (x4). Retrying in a bit...

**Comment by HarshitJoshi** [comment]
:eyes:

**Comment by nilaysaha** [comment]
Solved. After running sync for a while this error resolved

**Comment by HarshitJoshi** [comment]
How long though - I've been running it for 3 days now via docker (using the docker-compose.yml [here](https://github.com/input-output-hk/cardano-wallet/blob/master/docker-compose.yml) on the `preview` network):

```
$ docker ps -a
CONTAINER ID   IMAGE                                   COMMAND                  CREATED      STATUS      PORTS                                       NAMES
624087737f8b   inputoutput/cardano-wallet:2022.12.14   "bash -c ' ([[ $NETW…"   3 days ago   Up 3 days   0.0.0.0:8090->8090/tcp, :::8090->8090/tcp   cardano-cardano-wallet-1
143cae978717   inputoutput/cardano-node:1.35.5         "entrypoint"             3 days ago   Up 3 days                                               cardano-cardano-node-1
```
I still am able to see the same error output as you mentioned above:
```
[cardano-wallet.network:Warning:17] [2023-02-06 14:42:38.48 UTC] Delegation Rewards node client: Couldn't connect to node (x51570). Retrying in a bit...
[cardano-wallet.network:Warning:17] [2023-02-06 14:42:41.49 UTC] Delegation Rewards node client: Node connection lost because of the mux error (MuxBearerClosed): <socket: 14> closed when reading data, waiting on next header True
[cardano-wallet.network:Warning:17] [2023-02-06 14:42:43.49 UTC] Delegation Rewards node client: Couldn't connect to node (x51571). Retrying in a bit...
```
```
$ curl http://localhost:8090/v2/network/information | python3 -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   486    0   486    0     0   195k      0 --:--:-- --:--:-- --:--:--  474k
{
    "network_info": {
        "network_id": "testnet",
        "protocol_magic": 2
    },
    "network_tip": {
        "absolute_slot_number": 9038650,
        "epoch_number": 104,
        "slot_number": 53050,
        "time": "2023-02-06T14:44:10Z"
    },
    "next_epoch": {
        "epoch_number": 105,
        "epoch_start_time": "2023-02-07T00:00:00Z"
    },
    "node_era": "babbage",
    "node_tip": {
        "absolute_slot_number": 9038640,
        "epoch_number": 104,
        "height": {
            "quantity": 419291,
            "unit": "block"
        },
        "slot_number": 53040,
        "time": "2023-02-06T14:44:00Z"
    },
    "sync_progress": {
        "status": "ready"
    },
    "wallet_mode": "node"
}
```
Environment details:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```
```
$ uname -a
Linux Cardano-Testnet 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by nilaysaha** [comment]
Hmm … actually if you query it should work and all normal functionality of
wallet is ok … should resolve eventually … I think should not take that
long ..

**Comment by piotr-iohk** [comment]
@HarshitJoshi despite the warnings in the logs your wallet appears to be fully synced and operational:
```
$ curl http://localhost:8090/v2/network/information
...
    "sync_progress": {
        "status": "ready"
    },
```
Note that in case that wallet loses connection to the node (via node socket) it attemps to reconnect. Do you see any other issue with the wallet despite the warnings in the log?

**Comment by HarshitJoshi** [comment]
As you both have mentioned, both the wallet and the node are completely functional. Although, I would still like to understand how to get rid of these warnings altogether for a clean state (without any warning regarding disconnects), perhaps, I'm missing some configuration field or the configuration itself is incorrect? As @nilaysaha mentioned, these warnings eventually go away after a while but there has to be a reason for these, to begin with. Losing connection to the node (via node socket) every 2sec doesn't look right.
*Edit - Happy to share any further configuration details/environment details but as mentioned, I'm running both of these components via docker utilizing the boiler plate `docker-compose.yml` file in the repo.

**Comment by hiiamtrong** [comment]
This issue was resolved after I deleted the unused wallets. It is possible that there are too many synchronized wallets leading to reduced performance
