### ISSUE TITLE
Unable to decode Jörmungandr BFT blocks

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#386]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Windows & OSX & Linux) | Code  v Configuration v Environment v Human v Unknown |

# Context

Jörmungandr decoders had only been tested with the genesis block. Thanks to #382 there are more blocks to test on.

# Steps to Reproduce

```bash
cd lib/jormungandr/test/data/jormungandr
jormungandr --genesis-block block-0.bin --config config.yaml --secret secret.yaml
```

`stack ghci cardano-wallet-jormungandr`

```haskell
import Control.Monad.Trans.Except
import Cardano.Wallet.Jormungandr.Network
m <- newManager defaultManagerSettings
j = mkJormungandrLayer m (BaseUrl Http "localhost" 8081 "")
:m -Cardano.Wallet.Jormungandr.Binary

(Right t) <- runExceptT $ getTipId j
runExceptT $ getBlock j t
```

## Expected behavior

Successfully decodes the block.

## Actual behavior

Throws an exception.

```
runExceptT $ getBlock j t
Right (Just *** Exception: Data.Binary.Get.runGet at position 84: isolate: the decoder consumed 82 bytes which is less than the expected 178 bytes
CallStack (from HasCallStack):
  error, called at libraries/binary/src/Data/Binary/Get.hs:351:5 in binary-0.8.6.0:Data.Binary.Get
```
 
<A clear and concise description of what you observe instead. If applicable add screenshots to help explain your problem.>

---

# Resolution Plan

Probably related to the BFT specific case:

https://github.com/input-output-hk/cardano-wallet/blob/master/lib/jormungandr/src/Cardano/Wallet/Jormungandr/Binary.hs#L115

https://github.com/input-output-hk/rust-cardano/blob/master/chain-impl-mockchain/doc/format.md

With
```haskell
let bft = True
when bft $ do
    _leaderPublicKey <- getByteString 32
    _signature <- getByteString 64
    return ()
```
it works, for non-genesis blocks, but the genesis-block doesn't work (existing unit test fails). We need to handle these cases properly.

- [ ] I will give testing with genesis/praos a shot

# PR

| Number   | Base      |
| ---      | ---       |
| #394       | `master` |

# QA 

This now works:

```haskell
-- NOTE: have to manually export 
    , mkJormungandrLayer
    , JormungandrLayer (..)
-- in Cardano.Wallet.Jormungandr.Network
```

`stack ghci cardano-wallet-jormungandr`
```haskell
import Control.Monad.Trans.Except
import Cardano.Wallet.Jormungandr.Network
m <- newManager defaultManagerSettings
j = mkJormungandrLayer m (BaseUrl Http "localhost" 8081 "/api")
:m -Cardano.Wallet.Jormungandr.Binary

(Right t) <- runExceptT $ getTipId j
runExceptT $ getBlock j t
```

- There is a test decoding a non-genesis BFT block. https://github.com/input-output-hk/cardano-wallet/pull/394/files#diff-243dc78f6db975fd4b83e50a4e045bc1R54
- I have still not tried with Genesis/Praos 😕 , maybe we can close still?

**Comment by Anviking** [comment]
*wasn't sure whether to create a bug or add a point to #359*

**Comment by KtorZ** [comment]
@Anviking Bug is right here since it's about a task that is now "done" and closed.

**Comment by piotr-iohk** [comment]
lgtm :+1: 

>I have still not tried with Genesis/Praos confused , maybe we can close still?

We can as BFT is only in scope for now.
