### ISSUE TITLE
Stake pool monitor exit: Unhandled exception: SQLite3 returned ErrorIO while attempting to perform step: disk I/O error

### ISSUE THREAD

**Issue by liv-io** [cardano-foundation/cardano-wallet#3878]
### Just checking...

- [X] This is a `cardano-wallet` bug.
- [X] I am using the latest `cardano-wallet` release.
- [X] I am using the *correct* `cardano-node` version for that release of `cardano-wallet`.

### Version

v2023-04-14 (git revision: 3f9055373c272a4d7b1f9f6bacc1df3b6dc906af)

### Platform

Ubuntu 22.04 LTS (5.15.0-69-generic)

### Installation method

Own Docker image (please specify)

### Network configuration

mainnet

### Context

I am able to fully synchronize `cardano-wallet`, but see the following error message in the logs:

```
[cardano-wallet.pools-db:Info:53] [2023-04-23 11:15:28.22 UTC] Closing single database connection (/var/local/cardano-wallet/db/stake-pools.sqlite)
[cardano-wallet.pools-engine:Error:35] [2023-04-23 11:15:28.22 UTC] Stake pool monitor exit: Unhandled exception: SQLite3 returned ErrorIO while attempting to perform step: disk I/O error
[cardano-wallet.pools-db:Info:20] [2023-04-23 11:18:27.84 UTC] Closing single database connection (/var/local/cardano-wallet/db/stake-pools.sqlite)
```

**Most likely this isn't a bug, but the error makes me uneasy.** I would be thankful if you could confirm whether I can safely ignore this message.

Thank you.

#### Versions

I tested the following combination, but always get the same error:

|cardano-node|cardano-wallet|
|---                   |---                   |
|1.35.4              |v2022-12-14   |
|1.35.4              |v2023-04-14   |
|1.35.6              |v2022-12-14   |
|1.35.6              |v2023-04-14   |

#### Setup

My setup is a Ubuntu 22.04 with Podman as OCI container runtime.

 - The full `cardano-wallet` command is:

    ```
    /usr/local/bin/cardano-wallet serve --database /var/local/cardano-wallet/db --listen-address 0.0.0.0 --log-level Info --node-socket /var/local/cardano-node/db/node.socket --port 8090 --token-metadata-server https://tokens.cardano.org/ --mainnet
    ```

 - The network information is:

    ```
    curl --silent -H "Content-Type: application/json" http://localhost:8090/v2/network/information

    {"network_info":{"network_id":"mainnet","protocol_magic":764824073},"network_tip":{"absolute_slot_number":90687665,"epoch_number":407,"slot_number":226865,"time":"2023-04-23T12:45:56Z"},"next_epoch":{"epoch_number":408,"epoch_start_time":"2023-04-25T21:44:51Z"},"node_era":"babbage","node_tip":{"absolute_slot_number":90687656,"epoch_number":407,"height":{"quantity":8683811,"unit":"block"},"slot_number":226856,"time":"2023-04-23T12:45:47Z"},"sync_progress":{"status":"ready"},"wallet_mode":"node"}
    ```

## Steps to Reproduce

1. Build Docker image
    ```
    export CARDANO_WALLET_VERSION="v2023-04-14"
    export CARDANO_NODE_SOCKET_PATH="/var/local/cardano-node/db/node.socket"
    export CARDANO_WALLET_DATABASE_PATH="/var/local/cardano-wallet/db"

    apt update
    apt install -y --no-install-recommends ca-certificates curl git tar

    mkdir -p /usr/local/src/cardano-wallet
    mkdir -p /var/local/cardano-wallet/{config,db}
    mkdir -p /var/local/cardano-node/db

    curl --proto '=https' --tlsv1.2 \
        --location https://github.com/input-output-hk/cardano-wallet/releases/download/${CARDANO_WALLET_VERSION}/cardano-wallet-${CARDANO_WALLET_VERSION}-linux64.tar.gz \
        --output /usr/local/src/cardano-wallet/cardano-wallet-${CARDANO_WALLET_VERSION}-linux64.tar.gz

    tar --extract --gzip --file=/usr/local/src/cardano-wallet/cardano-wallet-${CARDANO_WALLET_VERSION}-linux64.tar.gz --directory=/usr/local/src/cardano-wallet
    cp /usr/local/src/cardano-wallet/cardano-wallet-${CARDANO_WALLET_VERSION}-linux64/cardano-wallet /usr/local/src/cardano-wallet/cardano-wallet

    cd /usr/local/src
    git clone --depth=1 --branch master https://github.com/input-output-hk/cardano-configurations.git
    ```

2. Run the `cardano-node` container in version `1.35.4`

3. Run the `cardano-wallet` container in version `v2023-04-14`

    ```
    /usr/local/bin/cardano-wallet serve --database /var/local/cardano-wallet/db --listen-address 0.0.0.0 --log-level Info --node-socket /var/local/cardano-node/db/node.socket --port 8090 --token-metadata-server https://tokens.cardano.org/ --mainnet
    ```

### Expected behavior

Ideally, no error message show up in a working `cardano-wallet` instance.

### Actual behavior

The error message described above is printed to the logs.

**Comment by Unisay** [comment]
This SO answer suggest that the error could be caused by a file system that doesn't support locking:
https://stackoverflow.com/questions/29244788/error-disk-i-o-error-on-a-newly-created-database

**Comment by liv-io** [comment]
@Unisay Many thanks for your input, I will research in this direction.
Very likely this is a bug in either my setup or SQLite3 itself. I am using the ext4 filesystem.

Would you like me to close this issue and report back once I was able to solve the error?

**Comment by liv-io** [comment]
It seems like this issue is related to running SQLite3 in a read-only container/filesystem.

https://stackoverflow.com/questions/75875515/how-to-fix-sqlite3-disk-i-o-error-when-running-inside-docker-container-on-a-serv

I am closing this issue as it isn't a problem in `cardano-wallet` itself.

**Comment by Unisay** [comment]
Btw, thanks for the exemplary bug report! 
Please come back if you find out any additional useful information, we'll consider adding it to the documentation.
Cheers!

**Comment by liv-io** [comment]
I will report back once I fixed my issue :) Many thanks for your help and hint.
