### ISSUE TITLE
Option for user-defined change address

### ISSUE THREAD

**Issue by jbgi** [cardano-foundation/cardano-wallet#39]
# Context

As a wallet user I want an option when sending a transaction to specify the change address. example: I have utxo with 100 Ada. I send 10 Ada to someone. Currently a new address is generated and 90 ADA goes into that address. But I want to be able to specify my-self the address that received the 90 ADA change.

# Decision

# Acceptance Criteria

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #?       | `master`  |

# QA

**Comment by KtorZ** [comment]
Moved to: https://github.com/input-output-hk/cardano-wallet/wiki/Blackboard
