### ISSUE TITLE
Compatibility with `cardano-node` version `8.0.0`

### ISSUE THREAD

**Issue by sourabhxyz** [cardano-foundation/cardano-wallet#3945]
### The problem that you wish to solve

To have `cardano-wallet` compatible with `cardano-node` version `8.0.0`.  

### Description

To update for dependencies and incorporate breaking changes, if any.

**Comment by jonathanknowles** [comment]
Hi @sourabhxyz 

Many thanks for creating this issue.

Compatibility with node version `8.0.0` is almost certainly on our roadmap for the near future.

We'll endeavour to post an update once we have more news.

Thanks again!

**Comment by RdeWilde** [comment]
Any timeline on this yet?

**Comment by jonathanknowles** [comment]
@RdeWilde wrote:

> Any timeline on this yet?

No precise timeline yet, but it's something we're aiming to do very soon. (It's near the top of our list of current work items.)

Will post more as soon as we have some news.

**Comment by Dark345** [comment]
any news on this?

**Comment by michalrus** [comment]
@Dark345 https://github.com/cardano-foundation/cardano-wallet/pull/4003 has already been merged to `master`

**Comment by Dark345** [comment]
> @Dark345 #4003 has already been merged to `master`

do you know when we'll have a tagged/official release?

**Comment by Unisay** [comment]
> do you know when we'll have a tagged/official release?

I don't have a date for you but release is the next top priority, so we'll make it asap.

**Comment by HeinrichApfelmus** [comment]
Status update: We're still working `macOS` support.

**Comment by Dark345** [comment]
> Status update: We're still working `macOS` support.

I can see [v2023-07-18](https://github.com/cardano-foundation/cardano-wallet/releases/tag/v2023-07-18) but it's lacking docs and pre-built binaries

**Comment by HeinrichApfelmus** [comment]
I have just published the release v2023-07-18:

https://github.com/cardano-foundation/cardano-wallet/releases/tag/v2023-07-18

> I can see [v2023-07-18](https://github.com/cardano-foundation/cardano-wallet/releases/tag/v2023-07-18) but it's lacking docs and pre-built binaries

We use Git tags to prepare a release, but the release is not official until we publish it on https://github.com/cardano-foundation/cardano-wallet/releases .

Closing this issue. Feel free to open new issues if you find problems with this release.
