### ISSUE TITLE
CLI unnecessarily asks for password when posting transaction from a non-existing wallet

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#398]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Linux | Code  v Configuration v Environment v Human v Unknown |

# Context
 
When trying to post tx and providing wallet id that is valid 40 char hex encoded string (yet not belonging to existing wallet), the CLI is asking for password, and only after providing the password it shows message that `I couldn't find a wallet with the given id: <walletId>`.
Instead, the CLI should not ask for password but return the message immediatelly.

# Steps to Reproduce

1. Run `cardano-wallet transaction create --port=<port> 1111111111111111111111111111111111111111 --payment 22@2cWKMJemoBahmFD6eqM76PqSVxxbobW4QbnF2ApBbR1c7JcrEhyq8S8YSrweZJPGGBcoY`

## Expected behavior
Error message:
`I couldn't find a wallet with the given id: <walletId>`
Exit code = 1

## Actual behavior
Password prompt appears:
`Please enter a passphrase:`
And error message just after providing a password:
`I couldn't find a wallet with the given id: <walletId>`

---

# Resolution Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #399       | `develop` |

# QA 

On #399 I have also modified CLI integration tests (the ones tagged `TRANS_CREATE_07`) to make sure CLI does not ask for password in case non-existing wallet is provided.

**Comment by KtorZ** [comment]
:+1:
