### ISSUE TITLE
Setup repository structure

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#4]
# Context

We’re starting fresh in a new repo! We need some basic things to work in it.

We should be able to quickly port over things from the old repo.

# Decision

- [ ] We *must* have a `.gitignore`
- [ ] We *must* have a basic `stack` setup, with appropriate folder structure (for instance `src`, `test/unit`, ...) ⇒ #15 
- [ ] We *should* have a config files for hlint and stylish-haskell
- [ ] We *may* have an `.editorconfig` (This is a proposal in the [Coding Standards wiki page](https://github.com/input-output-hk/cardano-wallet/wiki/Coding-Standards))
---

# Development Plan

- [x] I intend to copy the config-files from the old repo
- [x] I might intend to copy the `.cabal` from the prototype
- [x] I intend to add a pdf export of the formal specifications into a 'specifications' folder
- [x] I intend to add a swagger.yaml file specification document describing the API v2

# PR

| Number   | Base      |
| ---      | ---       |
| #15       | `master`  |
| #9       | `master`  |
| #13        | `master`  |
| #10        | `master`  |
| #17       | `master`  |

# QA

**Comment by KtorZ** [comment]
NOTE: We'll need to add a LICENSE file as well :+1:

**Comment by KtorZ** [comment]
I'll also add the specifications documents for both the API and the formal specs to have them versioned.

**Comment by KtorZ** [comment]
@Anviking Do we miss anything for this one :thinking: ?

**Comment by Anviking** [comment]
I don't _think_ so

**Comment by KtorZ** [comment]
Okay :+1: Let's move it into QA then :)

**Comment by piotr-iohk** [comment]
lgtm :+1:
