### ISSUE TITLE
API swagger specification isn't a valid swagger file

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#403]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Windows & OSX & Linux) | Configuration |

# Context
 
 

We have a hand-written swagger API specification [here](https://github.com/input-output-hk/cardano-wallet/blob/master/specifications/api/swagger.yaml). However, this isn't a valid swagger structure for there are some attributes and parameters in the top-level document which swagger does not support.

# Steps to Reproduce

1. Run the spec through a validator tool (e.g. https://github.com/p1c2u/openapi-spec-validator or http://editor.swagger.io/).

## Expected behavior

1. The spec is free of any parsing or semantic errors

## Actual behavior
 
<A clear and concise description of what you observe instead. If applicable add screenshots to help explain your problem.>

1. A lot of unexpected attributes errors are reported

---

# Resolution Plan

- [x] See the feasibility of using an automated validation tool in CI
- [x] Attempt to fix errors by moving attributes under the `definitions` special key

# PR

| Number   | Base      |
| ---      | ---       |
| #408        | `master` |

# QA 

- Specifications have been fixed by prefixing custom attributes with `x-` (which is swagger recommended way of introducing custom attributes).

- Compatibility of our swagger.yaml tested with:
    - editor.swagger.io
    - [openapi-spec-validator](https://github.com/p1c2u/openapi-spec-validator)

- The check with `openapi-spec-validator` has been added to our travis.yml and is now tested on each PR and merge to master (see: https://travis-ci.org/input-output-hk/cardano-wallet/jobs/545220168#L385-L387)

**Comment by piotr-iohk** [comment]
lgtm :+1:
