### ISSUE TITLE
Publish tag 2023-07-18 on Docker hub

### ISSUE THREAD

**Issue by abrkn** [cardano-foundation/cardano-wallet#4055]
### The problem that you wish to solve

The latest tag on Docker hub is 2023.4.14, which does not work with node v8.1.1

### Description

Please publish 2023-07-18 on Docker hub

**Comment by abrkn** [comment]
If anyone is facing this issue, Docker hub `cardanofoundation/cardano-wallet@sha256:436658eb223fb01ac3ab0010f3e985aa4e52343470e2a9d26b66115d25d36a0e` appears to be working

**Comment by HeinrichApfelmus** [comment]
I have just published the release and I have convinced our CI to push the tag `2023.7.18` to https://hub.docker.com/r/cardanofoundation/cardano-wallet/tags .

The `sha256` of the Docker image corresponding to the `2023.7.18` release is

```
0fc97fb1d0429d0d64b67347e581e1c4dc6efc09bb9f95126920835d7c49733f
```

I hope that this solves the issue. Closing.
