### ISSUE TITLE
Invalid link in `CONTRIBUTING.md` file

### ISSUE THREAD

**Issue by coot** [cardano-foundation/cardano-wallet#4064]
### The problem that you wish to solve

The link to contribution guide in `CONTRIBUTING.md` is returning a 404: `https://input-output-hk.github.io/cardano-wallet/contributing`.

**Comment by jonathanknowles** [comment]
Thanks @coot!

I've created a PR to fix this here: https://github.com/cardano-foundation/cardano-wallet/pull/4067.

**Comment by HeinrichApfelmus** [comment]
Should be fixed with Jonathan's PR. Feel free to reopen if the issue persists.
