### ISSUE TITLE
MacOS ARM64 builds

### ISSUE THREAD

**Issue by xanather** [cardano-foundation/cardano-wallet#4095]
### The problem that you wish to solve

Lack of MacOS ARM64 pre-built binaries.

### Description

Currently only Mac intel builds are provided, please provide ARM64 (aarch64) too, its becoming more widespread with M1/M2 chips and will should be supported in the longer term as Apple will deprecate Intel X64.

**Comment by michalrus** [comment]
You can take a look at how we patch `cardano-wallet` in Daedalus to get `aarch64-darwin` executables:

https://github.com/input-output-hk/daedalus/blob/883cbed8b7c149404698a27368e468efadd5bdd9/nix/internal/common.nix#L26-L45

You can run it from our repo having Nix installed:

```
❯ nix run github:input-output-hk/daedalus#internal.aarch64-darwin.common.cardano-wallet -- --help
The CLI is a proxy to the wallet server, which is required for most commands.
```

If you need the latest release (not yet merged into Daedalus, but we have a PR):

```
❯ nix run github:input-output-hk/daedalus/chore/ddw-1220-cardano-node-8.1.1#internal.aarch64-darwin.common.cardano-wallet -- version
v2023-07-18 (git revision: 0000000000000000000000000000000000000000)
```

**Comment by HeinrichApfelmus** [comment]
After merging https://github.com/cardano-foundation/cardano-wallet/pull/4429, `cardano-wallet` now fully supports `aarch64-darwin`.

Starting with the next release, we will officially support the `aarch64-darwin` platform.

**Comment by HeinrichApfelmus** [comment]
`aarch64-darwin` is officially supported starting with release

https://github.com/cardano-foundation/cardano-wallet/releases/tag/v2024-03-01
