### ISSUE TITLE
Expose Wallet Engine Sync Progress API

### ISSUE THREAD

**Issue by xanather** [cardano-foundation/cardano-wallet#4122]
### The problem that you wish to solve

I have several new wallets that I have added to my node, however they are all reporting as state 'ready' via /v2/wallets GET.

The strange thing is that the console says otherwise, cardano-wallet.cardano-engine is still syncing from the cardano node. E.g:
` Syncing (19.37% percent) Applied 8000 blocks, 0 rollbacks in the last 30.043631812s. Current tip is [point 4443f653 at slot 5293353]."`

Now I am aware that my specific wallets may be ready to send/receive transactions, however I am creating a node backup process where it checks that all necessary processing has occurred so I can then save the state into an image for future quick-boot usage. It's currently not possible to determine when cardano-wallet has finished syncing. I have also checked the EKG stats endpoint.

### Description

Expose a way to retrieve the wallet sync progress %.

/v2/wallets and /v2/network/information does not contain this info.

### Implementation suggestions

Include a new field as part of /v2/networking/information

**Comment by HeinrichApfelmus** [comment]
> The strange thing is that the console says otherwise, cardano-wallet.cardano-engine is still syncing from the cardano node. E.g:

That's curious, if `GET` reports `"status": "ready"` on a wallet, then the wallet should be, well, ready. That said, there is a background process that detects stake pools, maybe that is causing the log messages.

Could you include more detailed logs? (Or contact us privately via the Cardano Foundation (Slack) if you don't want to post your logs publicly. Happy to escalate to a contact person if you like.)

**Comment by xanather** [comment]
These are the logs I receive while all my wallets are status ready as well as network/information endpoint is ready/in sync.

```
{"MESSAGE":"\u001b[34m[cardano-wallet.wallet-engine:Info:135]\u001b[0m [2023-09-24 09:53:04.74 UTC] 9e5295f3: Syncing (36.70% percent) Applied 6000 blocks, 0 rollbacks in the last 30.068146537s. Current tip is [point 3c4ac2fb at slot 10602566]."}
```

Running cardano-wallet-v2023-07-18-linux64.tar.gz, this line above appears just before shutdown once the 'in sync' state is determined. It's only at 36% due to the few times the archival node as been rebooted and is able to increment some bit before shutting back down.

Here are also some pool-engine messages around the same time:

```
{"MESSAGE":"\u001b[35m[cardano-wallet.pools-engine:Notice:27]\u001b[0m [2023-09-24 09:49:58.83 UTC] In sync! Applied 2267 blocks, 0 rollbacks in the last 30.013552159s. Current tip is [point 0ef01649 at slot 28892968]."}
```

Noticeably the ready state is available when the pool-engine sync completes before the wallet-engine?

So what is "cardano-wallet.wallet-engine:Info:135" doing?

**Comment by HeinrichApfelmus** [comment]
> These are the logs I receive while all my wallets are status ready as well as network/information endpoint is ready/in sync.
>
> {"MESSAGE":"\u001b[34m[cardano-wallet.wallet-engine:Info:135]\u001b[0m [2023-09-24 09:53:04.74 UTC] 9e5295f3: Syncing (36.70% percent) Applied 6000 blocks, 0 rollbacks in the last 30.068146537s. Current tip is [point 3c4ac2fb at slot 10602566]."}

Hm. 🤔 This log message is created by a wallet whose `walletId` starts with `9e5295f3`. Can you locate this wallet in one of the following listings?

```
GET /wallets
GET /byron-wallets
GET /shared-wallets
```

These listings also include the `"state"` field for each wallet. Could you filter the response and post here the `"id"`, `"state"`, and `"tip"` fields of the JSON object corresponding to the wallet whose `"id"` starts with `9e5295f3`, as well as a recent `Syncing` log message from this wallet?

**Comment by xanather** [comment]
My apologies, I think this was a logic/bug error on my end where there was an edge case where it returned true anyway if the node was fully synced but the wallet wasn't.

Seems to work fine after adjusting my code with latest release, the state is not 'ready' immediately after creating the wallet anymore.

Closing.
