### ISSUE TITLE
Parameters --port and --bridge-port not validated correctly by CLI

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#422]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Linux| Code  v Configuration v Environment v Human v Unknown |

# Context
 
Currently both `serve` and `launch` commands of `cardano-wallet` come with:
 - `--port`
 - `--bridge-port`
e.g.:

```
  cardano-wallet launch [--network=STRING] [(--port=INT | --random-port)] [--bridge-port=INT] [--state-dir=DIR] [--min-log-severity=SEVERITY]
  cardano-wallet serve [--network=STRING] [(--port=INT | --random-port)] [--bridge-port=INT] [--database=FILE] [--min-log-severity=SEVERITY]
```
There are few issues:

1. Provided port for both commands (either for `--port` or `--bridge-port`) is validated as Int and following error message is displayed when providing faulty port, e.g.

```
$ cardano-wallet launch --port r
Int is an integer number between -9223372036854775808 and 9223372036854775807.
```
2. as a consequence one might also provide a negative number which makes `serve` or `launch` fail with unpleasent error:
```
$ cardano-wallet serve --port -1000                   
[iohk.#messagecounters.switchboard:Warning:ThreadId 10] [2019-06-17 10:37:38.63 UTC] time_interval_(s) = 0
cardano-wallet: Network.Socket.getAddrInfo (called with preferred socket type/protocol: AddrInfo {addrFlags = [AI_PASSIVE,AI_ADDRCONFIG], addrFamily = AF_UNSPEC, addrSocketType = Stream, addrProtocol = 0, addrAddress = <assumed to be undefined>, addrCanonName = <assumed to be undefined>}, host name: Just "127.0.0.1", service name: Just "-1000"): does not exist (Servname not supported for ai_socktype)
```

3. Additionally there is small issue with `cardano-wallet serve --port x`, the error message (from `errOut` interwines with `stdOut`), which looks a bit unpleasent e.g.:
```
$ cardano-wallet serve --port x
Int is an integer number bet[iohk.#messagecounters.switchboard:Warning:ThreadId 10] [2019-06-17 10:40:07.80 UTC] time_interval_(s) = 0
ween -9223372036854775808 and 9223372036854775807.
```

# Steps to Reproduce

Examples are for `--port` but it is the same issue with `--bridge-port`

Ex 1. 
 `cardano-wallet launch --port x`

Ex 2.
 `cardano-http-bridge start --port 8080 --template testnet` 
 `cardano-wallet serve --port -1000`
 or
 `cardano-wallet launch --port -1000`

Ex 3. 
 `cardano-wallet serve --port x`

## Expected behavior

1. -> `--- port | --bridge-port - provided port should be in range (xxx, xxx)`
2. -> `--- port | --bridge-port - provided port should be in range (xxx, xxx)`
3. -> `--- port | --bridge-port - provided port should be in range (xxx, xxx)`
^ errMsg does not interwine with stdOut
## Actual behavior
 
1. -> `Int is an integer number between -9223372036854775808 and 9223372036854775807.`
2. ->
```
cardano-wallet: Network.Socket.getAddrInfo (called with preferred socket type/protocol: AddrInfo {addrFlags = [AI_PASSIVE,AI_ADDRCONFIG], addrFamily = AF_UNSPEC, addrSocketType = Stream, addrProtocol = 0, addrAddress = <assumed to be undefined>, addrCanonName = <assumed to be undefined>}, host name: Just "127.0.0.1", service name: Just "-1000"): does not exist (Servname not supported for ai_socktype)
```
3. ->

```
Int is an integer number bet[iohk.#messagecounters.switchboard:Warning:ThreadId 10] [2019-06-17 10:40:07.80 UTC] time_interval_(s) = 0
ween -9223372036854775808 and 9223372036854775807.
```

---

# Resolution Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #?       | `develop` |

# QA

**Comment by KtorZ** [comment]
I'll tackle that as part of #368
