### ISSUE TITLE
  cardano-wallet is not getting synced up

### ISSUE THREAD

**Issue by shanhashcah** [cardano-foundation/cardano-wallet#4248]
### Just checking...

- [x] This is a `cardano-wallet` bug.
- [X] I am using the latest `cardano-wallet` release.
- [X] I am using the *correct* `cardano-node` version for that release of `cardano-wallet`.

### Version

v2023--7-18

### Platform

ubuntu

### Installation method

Binary from GitHub release page

### Network configuration

mainnet

### Context

My cardano node is on 100% synced, cardano version is 8.1.2 and my cardano-wallet version is v2023-07-18 . Now I am  trying  to run cardano-wallet but getting below warnings 

[cardano-wallet.network:Warning:17] [2023-11-20 08:42:24.59 UTC] Connection lost with the node.
[cardano-wallet.network:Warning:17] [2023-11-20 08:42:26.83 UTC] Couldn't connect to node (x340). Retrying in a bit...
[cardano-wallet.network:Warning:17] [2023-11-20 08:42:28.49 UTC] Connection lost with the node.
[cardano-wallet.network:Warning:17] [2023-11-20 08:42:30.67 UTC] Couldn't connect to node (x341). Retrying in a bit...
[cardano-wallet.network:Warning:17] [2023-11-20 08:42:33.16 UTC] Connection lost with the node.
[cardano-wallet.network:Warning:17] [2023-11-20 08:42:35.28 UTC] Couldn't connect to node (x342). Retrying in a bit...
[cardano-wallet.network:Warning:17] [2023-11-20 08:42:36.81 UTC] Connection lost with the node.

Thanks

**Comment by Unisay** [comment]
Please make sure that `cardano-node` socket file exists and is readable. One way of doing it is to use the `cardano-cli` executable that ships with the node, for example:
```
cardano-cli query tip --mainnet --socket-path /your/path/to/the/node.socket
```

**Comment by shanhashcah** [comment]
@Unisay Sir:

Thanks for your reply. I have execute the query  and getting blow response

**cardano-cli query tip --mainnet --socket-path /home/ubuntu/cardano/db/node.socket

{
    "block": 9571129,
    "epoch": 449,
    "era": "Babbage",
    "hash": "c83ea12cc3200a37a7acdb64e8ae28f5244e085e150c85b7ab128a43985028f8",
    "slot": 108911100,
    "slotInEpoch": 306300,
    "slotsToEpochEnd": 125700,
    "syncProgress": "100.00"
}**

**Comment by shanhashcah** [comment]
Any help...

**Comment by Unisay** [comment]
Ok, so the node socket seems to be fine.

I've noticed you're using node `8.1.2` while the [release page](https://github.com/cardano-foundation/cardano-wallet/releases/tag/v2023-07-18) mentions `8.1.1`. I'll ask you to use node 8.1.1 as its the one we've tested the wallet with.

If the problem remains, we'll need to have more information: wallet.log &| node.log, if possible.

**Comment by shanhashcah** [comment]
Thanks @Unisay Sir for your reply.

I have download cardano 8.1.1 binary from release page. It shows different versions  if I check by  two way.

1.  cardano-node --version
       cardano-node 8.1.2 - linux-x86_64 - ghc-8.10

2.   ./cardano-node --version
      cardano-node 8.1.1 - linux-x86_64 - ghc-8.10
      
Sir which one is correct?

**Comment by shanhashcah** [comment]
Ok @Unisay Sir... Let me try & I'll  update you.

Thanks..

**Comment by shanhashcah** [comment]
Hi @Unisay  Sir:

My cardano node 8.1.1 get 100 % synced and I have run cardano-wallet v2023-07-18 . From cardano-wallet server  log I am seeing that sometime it is syncing  and sometime  **syncing progress getting decreased** as I am getting below message


**_[cardano-wallet.wallet-engine:Info:118] [2023-11-23 06:39:43.66 UTC] d12fb9d6: Syncing (94.43% percent) Applied 100 blocks, 0 rollbacks in the last 36.002320268s. Current tip is [point 5b67e7f9 at slot 98322557]_**

Then I am getting below message 

**_[cardano-wallet.wallet-engine:Warning:1654] [2023-11-23 06:39:53.30 UTC] 488a3ac6: Syncing (94.42% percent) Applied 0 blocks, 0 rollbacks in the last 30.739998812s. Current tip is [point 70f9a1b0 at slot 98310820]. (progress decreased)_**

Again I am getting below message 
**_[cardano-wallet.wallet-engine:Info:1670] [2023-11-23 06:42:25.02 UTC] 9e294885: Syncing (94.43% percent) Applied 100 blocks, 0 rollbacks in the last 30.12136007s. Current tip is [point 1ea88c1e at slot 98316709]_**

But in cardano-node log every thing is ok, getting below message

**_[ip-10-0-:cardano.node.ChainDB:Notice:39] [2023-11-23 06:43:25.90 UTC] Chain extended, new tip: a96f3a46c19d25eca9aa0e9690e16e7ab3a2865c7915e685146d21a06d11f290 at slot 109155514_**

Sir is there any issue??? Please guide me.

Many Thanks

**Comment by shanhashcah** [comment]
@Unisay Sir .. Any suggestion...

**Comment by shanhashcah** [comment]
Any Help.....

**Comment by Unisay** [comment]
Judging from the logs you provided above you have several "logical" wallets (based on a particular mnemonic) managed by a single "cardano-wallet" application. (Each logical wallet does its own synchronization.)

Unfortunately its hard to say what's happening without seeing the full picture by which I mean the `wallet.log` file.

It would also help to understand how many wallets you have by querying this endpoint:
https://cardano-foundation.github.io/cardano-wallet/api/edge/#operation/listWallets

Would it be possible for you to send us (developers) required information to hal@cardanofoundation.org for troubleshooting?
(It is supposed to be safe in terms of your private data as we never log mnemonics or passwords).

**Comment by shanhashcah** [comment]
Thanks for your reply.

Sir, Which particular information I need to provide by email?  Is there something am I doing wrong or there is issue in cardano-wallet itself?

**Comment by Unisay** [comment]
> Which particular information I need to provide by email?

It would be helpful for troubleshooting if you can attach your `wallet.log` file which could be obtained by re-directing standard output to a file, for example:

```
cardano-wallet serve --node-socket /path/to/your/node.socket --mainnet  --database /path/to/wallet/db  --log-level DEBUG | tee wallet.log
```

> Is there something am I doing wrong or there is issue in `cardano-wallet` itself?

This is exactly what we're trying to figure out.

**Comment by shanhashcah** [comment]
Hi @Unisay Sir:

Cardano wallet is synced after few days. But sometimes wallet slot be behind  to cardano node.  Then it tries resync and progress decreased and synced.
