### ISSUE TITLE
cabal build all with v2023-07-18 tag not working

### ISSUE THREAD

**Issue by forart82** [cardano-foundation/cardano-wallet#4265]
### Just checking...

- [X] This is a `cardano-wallet` bug.
- [X] I am using the latest `cardano-wallet` release.
- [X] I am using the *correct* `cardano-node` version for that release of `cardano-wallet`.

### Version

on installation

### Platform

window 11 wsl2

### Installation method

Built from source

### Network configuration

testnet

### Context

try to build cardano wallet with this documentaion: https://developers.cardano.org/docs/get-started/installing-cardano-wallet
error when execute the command: cabal build all.
   fatal: reference is not a tree: c30d0de6875d75edd64d1aac2272886528bc492d
found the reference in cabal.project line 92 https://github.com/paolino/openapi3
i do not find a reference when i search in the paolino/openapi3 repo 
workaround with tag 3.2.2 / c5596067ef11618fc2eec74a37a927808e2c9500

### Description

Prerequisites:
fresh installaion of all / os / cardano-node / cardano-cli / etc..

## Steps to Reproduce

1: go to https://developers.cardano.org/docs/get-started/installing-cardano-wallet
2: execute all steps until : cabal build all
3: get error fatal: reference is not a tree: c30d0de6875d75edd64d1aac2272886528bc492d

**Comment by paolino** [comment]
Hi, this is unrecoverable, sadly. I made a mistake by rewriting git history in that clone of the `biocad` original openapi3. The only workaround is to use the `f22c31611c295637a3e72b341cd1c56d1d87b993` commit from my clone.

In cabal.project you can substitute the old source repository package section with

```
source-repository-package
  type: git
  location: https://github.com/paolino/openapi3
  tag: f22c31611c295637a3e72b341cd1c56d1d87b993
  --sha256: 10l7wlaz9rcr3fysi1vwg7qqa826bb7nidkpx9jy1q7ja7ddw47i
  ```

OTOH , in the next few days we are releasing a new version of the wallet with that exact section in the cabal.project
