### ISSUE TITLE
Defer selection improvement in random-improve algorithm

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#461]
# Context

The current coin selection works following a so-called random-improve algorithm (see [Formal Specification For A Cardano Wallet - Chapter 11](https://github.com/input-output-hk/cardano-wallet/blob/master/specifications/wallet/formal-specification-for-a-cardano-wallet.pdf) for all outputs, one output after the other. 

We have identified that for some users, doing the improvement for each output before covering the next one can become problematic. As a matter of fact, if the first input to cover requires many outputs, it will likely consume all remaining available inputs when trying to improve this first selection, leaving no inputs available for the next outputs.

# Decision

Instead, we could perform the **random selection only**, for all outputs, and then, try to improve each output one after the other. This way, we can use our available inputs to cover requested outputs. And, once done, with the remaining available inputs, we try to improve each output one after the other. This should be much more resilient to multi-output transaction while still allowing a best-effort for cleaning up the UTxO as we make transactions.

So basically, given the following selection:

```
  *------ output 1 / selection #1
  |                              
--*------ output 2 / selection #2
  |                              
  *------ output 3 / selection #3
```

Instead of

```
(1) random + improve #1
           |
(2) random + improve #2        
           |
(3) random + improve #3
           |
           |
           v
     final selection
```

We want to do:

```
              *---------*        
              |         |
(1) random #1 | (4) improve #1
       |      |         |
(2) random #2 | (5) improve #2
       |      |         |
(3) random #3 | (6) improve #3
       |      |         |
       *------*         |
                        |
                        v
                  final selection
```

Possibly repeating steps `(4)`, `(5)`, `(6)` as many times as necessary.

# Acceptance Criteria

1. CS algorithm `must` traverse and randomly cover all outputs first before making any improvement.
2. Selection `must` be improved, if possible, from the remaining outputs. Failing to improve doesn't make the random-selection fail. 
3. CS algorithm `must` still fallback to `LargestFirst` if the random selection fails.
4. CS algorithm `shouldn't` stop improving if-and-only-if:
    - there's no more selection to improve
    - or there's no more available inputs
    (this means that, with a multi-outputs transaction, failing to improve on the first one shouldn't prevent the subsequent ones to be improved).
4. High-level module API for coin selection `shouldn't` change.
5. During the improvement phase CS `may` try to split remaining inputs across all outputs, and do several round of improvements (instead of improving the first output, then the next one etc ...). 

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #493        | `master`  |
| #500        | `master`  |

# QA 
A number of things were changed in this ticket that needs checking : 
1. The flow of random algo has changed and this was documented here : https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/src/Cardano/Wallet/Primitive/CoinSelection/Random.hs#L64
2. Additional error was introduced (and illustrative test was added to pinpoint the case) : https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/src/Cardano/Wallet/Primitive/CoinSelection.hs#L67
3. A number of tests were added and some were updated in the light of new random algo flow

**Comment by KtorZ** [comment]
*Add info about existing regression tests

**Comment by KtorZ** [comment]
*Add examples of properties

**Comment by piotr-iohk** [comment]
LGTM, I've only added integration tests producing ErrInputsDepleted in #500.
