### ISSUE TITLE
Implement `listTransactions` endpoint (no filtering)

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#465]
# Context

The following endpoint is still missing but crucial for end-users:

https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/listTransactions

# Decision

The main difficulty on this endpoint lies in the `Range` parameter and the filtering and sorting requirements that goes behind it. This ticket leaves that aside and focus on implementing the endpoint "raw', returning all transactions in a non-paginated format. 

# Acceptance Criteria

1. `GET /api/v2/transactions` _must_ return a list of all known transactions
2. Transactions _must_ be sorted by descending date of insertion

---

# Development Plan

- [x] Make `selectTxHistory` sort by `slotId`
- [x] Add a function to the wallet layer that sorts and returns `[(Tx, TxMeta)]` (add a test)
- [x] Add a function `SlotId -> UTCTime`
- [x] Add a `listTransactions` function in the Api and make sure the endpoint is served. Because we now have `[(Tx, TxMeta)]` and `SlotId -> UTCTime` we can create a `[ApiTransaction]`.
- [x] I believe we should have some integration tests.  https://input-output-rnd.slack.com/archives/GBT05825V/p1564475587002600?thread_ts=1564381927.001200&cid=GBT05825V Aside from that I think we're good here.

# PR

| Number   | Base      |
| ---      | ---       |
| #497        | `master`  |
| #524 | `master` |

# QA 

1. [x] Transaction sorting behaviour is captured in unit test models.
2. [x] There is an integration test that exercises the `/api/v2/transactions` endpoint

**Comment by jonathanknowles** [comment]
@Anviking @KtorZ 

I was just wondering: do we have a **type** for this endpoint yet, or are there more details to work out before we can be sure what the type should be?

If we are already sure what the type should be, then I'm wondering if it would be convenient to  implement a small PR to add a skeleton endpoint, returning just the empty list? (We wouldn't have to merge this immediately.)

If we had that, then this would potentially allow #467 (the CLI part) to proceed in parallel.

Just a thought.

**Comment by KtorZ** [comment]
@jonathan.knowles 

https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/listTransactions ?

Is it what you meant?

**Comment by jonathanknowles** [comment]
> https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/listTransactions ?
> 
> Is it what you meant?

Yup! But practically speaking, to translate this into a `ListTransactions` type in `Cardano.Wallet.Api`.

If we could make a small PR to implement this first (with a dummy implementation that returns `[]`), then that would potentially allow #467 (the CLI part) to proceed in parallel.

**Comment by Anviking** [comment]
_resurrecting an old un-rebased commit doing that_

--> #518
