### ISSUE TITLE
🐞 Bug: HTTP API returns "Internal Server Error" when attempting to encrypt multiple transaction metadata messages.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#4652]
## Version

a2cac93ed8f55512d4e3590a6c8d64f6df5c4f7b

## Bug description

If:
- the user calls the `constructTransaction` HTTP API endpoint
- the `metadata` field is populated with metadata to be encrypted according to [CIP-83](https://cips.cardano.org/cip/CIP-83)

And if:
- the included metadata map includes **_more than one_** message with a `msg` key
- the **_detailed_** JSON schema option `TxMetadataDetailedSchema` is used.

Then the HTTP API will return "Internal Server Error".

## Reproduction steps

See the following PR that demonstrates the issue:
- https://github.com/cardano-foundation/cardano-wallet/pull/4651

With a fresh checkout of the above PR, run:

```sh
$ nix develop
$ just conway-integration-tests-match "encrypt multiple metadata messages"
```

## Example failure links

- https://buildkite.com/cardano-foundation/cardano-wallet/builds/5570#01905814-2e6e-460b-83aa-7cfed4ede245/139-753
- https://buildkite.com/cardano-foundation/cardano-wallet/builds/5570#01905814-2e70-4cc3-b3f8-8f8f3d9eb0f8/139-758

## Example failure log extract
```hs
only one 'msg' field expected
CallStack (from HasCallStack):
  error, called at src/Cardano/Wallet/Api/Http/Shelley/Server.hs:3207:24 in cardano-wallet-api-2024.5.5-AKdt1G4fjDDEhVlTTGjQVf:Cardano.Wallet.Api.Http.Shelley.Server
From the following response: Left
    ( DecodeFailure "Something went wrong" "Unexpected "Something went wrong", expecting JSON value" )
While verifying value:
  ( Status
      { statusCode = 500
      , statusMessage = "Internal Server Error"
      }
  , Left
      ( DecodeFailure "Something went wrong" "Unexpected "Something went wrong", expecting JSON value" )
  )
expected: Status {statusCode = 202, statusMessage = "Accepted"}
 but got: Status {statusCode = 500, statusMessage = "Internal Server Error"}
```

## Expected behaviour

Either:
- The API returns a dedicated error with a corresponding schema definition, indicating that only one message is allowed to be encrypted.

Or:
- The API accepts more than one message for encryption, and encrypts them all of them.

**Comment by jonathanknowles** [comment]
The cause of the internal server error is this section of code:
https://github.com/cardano-foundation/cardano-wallet/blob/a2cac93ed8f55512d4e3590a6c8d64f6df5c4f7b/lib/api/src/Cardano/Wallet/Api/Http/Shelley/Server.hs#L3202-L3207

The `error` branch will only be evaluated if the `TxMetadataDetailedSchema` JSON serialisation option is used in conjunction with a `TxMetaMap` object that contains multiple `msg` keys. 

If instead the `TxMetadataNoSchema` JSON serialisation option is used, then only the last `msg` key-value mapping will be retained, and the `error` branch will not be evaluated.

 See https://github.com/cardano-foundation/cardano-wallet/issues/4647#issuecomment-2193646898 for an explanation of why this happens.

**Comment by paweljakubas** [comment]
addressed and fixed https://github.com/cardano-foundation/cardano-wallet/pull/4651
