### ISSUE TITLE
Implement `wallet passphrase update` command in CLI

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#472]
# Context

The API does support have a dedicated endpoint to update a wallet's passphrase:

https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/putWalletPassphrase

The corresponding command in the CLI is still missing.

# Decision

Implement a `wallet update passphrase` command.

# Acceptance Criteria

1. A `wallet update passphrase` command _must_ be available in the command-line interface.
2. The command _must_ prompt the user for their current and new passphrase, in a secure way (hidden inputs).
3. The new passphrase _must_ be prompted for twice.

---

# Development Plan

- [x] Generalize functions `getPassphrase` and `getPassphraseWithConfirm` to work with different prompts. For example:
     * "Please enter a new passphrase:"
     * "Please enter your current passphrase:".
- [x] Generalize functions `getPassphrase` and `getPassphraseWithConfirm` to return different **types** of passphrase. We need to be able to return:
    * `Passphrase "encryption"`
    * `Passphrase "encryption-old"`
    * `Passphrase "encryption-new"`.
- [x] Adjust the structure of the CLI so that updating a wallet's name and updating a wallet's passphrase fall under the same command group.
- [x] Add a command `cmdWalletUpdatePassphrase` to update a wallet's passphrase, along with an associated data type `WalletUpdatePassphraseArgs`.

# PR

| Number   | Base      |
| ---      | ---       |
| #519        | `master`  |
| #535        | `master`  |

# QA 

- [x] Add integration tests to check that it **is** possible to update a wallet's passphrase through the CLI.
- [x] Add integration tests to check that it's **not** possible to update a wallet's passphrase without supplying the original passphrase.

**Comment by jonathanknowles** [comment]
Hi @KtorZ 

After adding this command, we'd end up with the following:

| Command | Effect |
| -- | -- |
| `cardano-wallet wallet update` | update wallet metadata (currently just the name) |
| `cardano-wallet wallet passphrase update` | update wallet passphrase |

If the user types `cardano-wallet wallet --help` they'll see something similar to:
```
Usage: cardano-wallet wallet COMMAND

Available commands:
  list         List all known wallets.
  create       Create a new wallet using a sequential address scheme.
  get          Fetch wallet with specified id.
  update       Update the metadata for a wallet.
  passphrase   Commands relating to a wallet's passphrase.
  delete       Delete wallet with specified wallet id.
```
In my opinion, this is a bit inconsistent, as it mixes **verbs** (like `list`, `create`, `update` and so on) with **nouns** (like `passphrase`) at the same level.

## Proposal

What if we were to change the above scheme very slightly to:

| Command | Effect |
| -- | -- |
| `cardano-wallet wallet update name` | update wallet name |
| `cardano-wallet wallet update passphrase` | update wallet passphrase |

_OR_

| Command | Effect |
| -- | -- |
| `cardano-wallet wallet update metadata` | update wallet metadata (including name) |
| `cardano-wallet wallet update passphrase` | update wallet passphrase |

## Advantages

1. The list of sub-commands of `wallet` is kept simple. All sub-commands are **verbs**, a list of **things one can do with wallets**:

    ```
    Usage: cardano-wallet wallet COMMAND

    Available commands:
      list         List all known wallets.
      create       Create a new wallet using a sequential address scheme.
      get          Fetch wallet with specified id.
      update       Update wallet with specified id.
      delete       Delete wallet with specified id.
    ```

2. If the user invokes `wallet update --help`, they're presented with a **list of things they can update**:

    ```
    Usage: cardano-wallet wallet update COMMAND

    Available commands:
      name         Update a wallet's name.
      passphrase   Update a wallet's passphrase.
    ```

What do you think?

**Comment by jonathanknowles** [comment]
@KtorZ Another question:

Unix commands like `passwd` notify the user if they attempt an idempotent update. Should we do the same for a passphrase update?

Something like this:

<pre>
$ cardano-wallet wallet passphrase update 4ce7b5440f94054925cead9247e406cb28ea7add
Please enter your current passphrase: **********
Please enter a new passphrase: **********
Please enter your new passphrase a second time: **********
<b>The new passphrase is the same as your current passphrase.</b>
<b>Passphrase unchanged.</b>
</pre>

If so, then should this be implemented in the **API layer** or in the **CLI layer**?

**Comment by KtorZ** [comment]
I think your first proposal makes sense. And I'd be more inclined to have `update name` than `update metadata` at first, and either add a new one or, review the command-line if we ever come to add more metadata :) 

I've more reserved about the second proposal, the main reason being that the API doesn't act this way. So we start having a difference of logic between the CLI and the API which is something we do want to avoid. There's probably a reason why `passwd` doesn't allow updating to an identical passphrase, for us, I see little (no?) particular benefits apart from informing the user he's/she's doing something stupid :sweat_smile:

**Comment by jonathanknowles** [comment]
> I think your first proposal makes sense. And I'd be more inclined to have update name than update metadata at first, and either add a new one or, review the command-line if we ever come to add more metadata :)

Great. Thanks for confirming.

> I've more reserved about the second proposal, the main reason being that the API doesn't act this way. So we start having a difference of logic between the CLI and the API which is something we do want to avoid. 

Fair enough!

> I see little (no?) particular benefits apart from informing the user he's/she's doing something stupid.

If the user is attempting to change the passphrase to the same value, it's possible he/she has made a mental error. As a user, I personally like to be reminded when I've made an error like this. But I guess it boils down to the kind of experience we want to provide.

**Comment by piotr-iohk** [comment]
Looks good :+1: . I'd like to add few more integration tests for it to the suite.

**Comment by piotr-iohk** [comment]
More tests added in #535.
