### ISSUE TITLE
Lost my wallet passphare 

### ISSUE THREAD

**Issue by Shiv15399** [cardano-foundation/cardano-wallet#4745]
### The problem that you wish to solve

Dear sir, I have lost my passphare because of lost my android phone and I have created new wallet but my 627 pi already mainnet in wallet so, please give me solution how to recover my old passphare to transfer the mainnet pi in new wallet..

### Description

Please give the options to forget the passphare to recover the wallet pi

**Comment by ACCmaintenance** [comment]
This issue has been previewed on Pull Request. To Resolve,
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@Shiv15399

**Comment by Shiv15399** [comment]
Still no improvement in my wallet
Sir, pls check and synchronisation my wallet old and new both .

**Comment by HeinrichApfelmus** [comment]
Sorry, but

* `cardano-wallet` is for the Cardano blockchain, not for the Pi chain
* `cardano-wallet` is not supported on mobile phones
* In general, cryptocurrencies require you to remember your passphrase and/or mnemonic — or your funds are lost forever.
