### ISSUE TITLE
`flake.lock` still points to `cardano-node` 9.2.1, not 10.1.2

### ISSUE THREAD

**Issue by michalrus** [cardano-foundation/cardano-wallet#4834]
### Just checking...

- [X] This is a `cardano-wallet` bug.
- [X] I am using the latest `cardano-wallet` release.
- [X] I am using the *correct* `cardano-node` version for that release of `cardano-wallet`.

### Version

9078093ca150d97a6a4ca09895ec123bb76227c0

### Platform

any

### Installation method

Nix

### Network configuration

any

### Context

First found [here](https://github.com/cardano-foundation/cardano-wallet/pull/4830#issuecomment-2462298419).

We can override it ourselves in Daedalus for now, but it would be reasonable to have here.

## Steps to Reproduce

1. Checkout 9078093ca150d97a6a4ca09895ec123bb76227c0 (PR #4830).
2. `nix repl`
3. `:lf .`
4. `inputs.cardano-node-runtime.rev`
5. You will see [`5d3da8ac771ee5ed424d6c78473c11deabb7a1f3`](https://github.com/IntersectMBO/cardano-node/commit/5d3da8ac771ee5ed424d6c78473c11deabb7a1f3)…
6. … which is still 9.2.1.

### Expected behavior

Runtime is `cardano-node` 10.1.2.

### Actual behavior

Runtime is still `cardano-node` 9.2.1.

/cc @paolino @HeinrichApfelmus

**Comment by HeinrichApfelmus** [comment]
Thank you for the report, we noticed this as well. Working on it for the upcoming release.

**Comment by michalrus** [comment]
@HeinrichApfelmus great, thanks. Could you please give us an estimate on when it will be released?

**Comment by HeinrichApfelmus** [comment]
> Could you please give us an estimate on when it will be released?

We hope to release from candidate `v2024-11-07`, but this could be delayed by a couple of days.

**Comment by michalrus** [comment]
Thanks, and good luck!

**Comment by HeinrichApfelmus** [comment]
We have released [v2024-11-18](https://github.com/cardano-foundation/cardano-wallet/releases/tag/v2024-11-18) which is now shipped with `cardano-node` version 10.1.2. This should fix the issue. Feel free to reopen if it doesn't work. 😊

**Comment by michalrus** [comment]
It does, thanks! :bow:
