### ISSUE TITLE
Restoration workers aren't restarted with the wallet

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#484]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Windows & OSX & Linux) | Code |

# Context
 
 

When creating a wallet via the API, we also start a restoration worker in charge of keeping the wallet in sync with the chain. There's one dedicated worker per wallet, and they're fairly resilient to network issues. 
However, when restarting a wallet using an existing database that already contains a wallet, not restoration worker is started. Though, the wallet exist in DB and can't be recreated for instance.

# Steps to Reproduce

1. `$ cardano-wallet launch --state-dir .state`
2. `$ cardano-wallet wallet create ...` 
3. SIGINT or CTRL-C on the launcher
4. `$ cardano-wallet launch --state-dir .state`

## Expected behavior

We should see log activity for a restoration worker keeping the wallet in sync.

## Actual behavior
 
<A clear and concise description of what you observe instead. If applicable add screenshots to help explain your problem.>

Nothing happen, the wallet exists in the DB but no restoration worker in background.

---

# Resolution Plan

- [x] Upon starting, lookup existing wallets.
- [x] Start a worker for each wallet.

# PR

| Number   | Base      |
| ---      | ---       |
| #486        | `master` |

# QA 

- Add an integration tests which does the following steps (see [LauncherSpec](https://github.com/input-output-hk/cardano-wallet/blob/master/lib/http-bridge/test/integration/Cardano/LauncherSpec.hs#L87-L107))
    1. Start a wallet server (on an empty state, with persistence)
    2. Create a new wallet
    3. Immediately kill the wallet server
    4. Re-start a wallet server, using the same database file
    5. Expect the previous wallet to exist and eventually be restored.

- Note that the test is only a best-effort and will sometimes give false positive (but shouldn't give any false negative!). This is because we are running the test on a fresh new blockchain so, depending on _when_ the restoration kicks in, it might have time to restore the wallet before we even kill the server (:rocket:). This happens fairly rarely in practice, and shouldn't give any false alarm anyway.

**Comment by piotr-iohk** [comment]
lgtm
