### ISSUE TITLE
Voting Power Delegation endpoints reject `abstain` and `no_confidance` votes

### ISSUE THREAD

**Issue by szymonmaslowski** [cardano-foundation/cardano-wallet#4870]
### Just checking...

- [X] This is a `cardano-wallet` bug.
- [X] I am using the latest `cardano-wallet` release.
- [X] I am using the *correct* `cardano-node` version for that release of `cardano-wallet`.

### Version

v2024-11-18

### Platform

macOS 14

### Installation method

Nix

### Network configuration

preview

### Context

I am a Daedalus developer. The new version we are about to release will include the voting power delegation feature. We discovered an issue with [constructTransaction](https://cardano-foundation.github.io/cardano-wallet/api/edge/#operation/constructTransaction) and [joinDRep](https://cardano-foundation.github.io/cardano-wallet/api/edge/#operation/joinDRep) endpoints. We use Cardano Wallet v2024-11-28 in combination with Cardano Node v10.1.3. The issue occurs independently of the network and OS.

## Steps to Reproduce

1. Vote `abstain` using the `joinDRep` endpoint.
2. Vote `no_confidence` using the `joinDRep` endpoint.

### Expected behavior

Cardano Wallet creates and submits the TX

### Actual behavior

- Cardano Wallet responds with a `same_vote` error.
- the error occurs when voting on `abstain` or `no_confidence`
- the previous vote doesn't matter, could be also a DRep ID.
- voting on DRep passes successfully
- unfortunately, the circumstances of the error to occur are unknown to us yet. We just noticed it happens after some time / many votes performed for a given wallet.

**Comment by szymonmaslowski** [comment]
Hey @abailly, are there chances of taking this issue as a priority? It impacts users of Daedalus, so we would like to release a new version with the fix as soon as possible.

**Comment by abailly** [comment]
@szymonmaslowski It's at the top of our backlog

**Comment by abailly** [comment]
<img width="1440" alt="Screenshot 2024-12-10 at 14 42 30" src="https://github.com/user-attachments/assets/8b7308fe-bf40-4769-b43c-9827356b34ad">

**Comment by abailly** [comment]
Note that we don't plan to do a release before end of next week anyhow

**Comment by abailly** [comment]
Seems to me that #4871 and #4872 are more or less duplicates of this issue which is the most developed among the 3 issues you submitted last week. If this is the case, could you please consolidate the issue into a single one?

**Comment by abailly** [comment]
I wasn't able to reproduce the issue following the instructions on a wallet running on preprod.
I did:

```
 % curl http://mac-mini:54775/v2/dreps/abstain/wallets/77992dc1b3f46688766c49d7920b0fb9ba33830a/  -X PUT -d '{"passphrase":<REDACTED>}' -H content-type:application/json
 % curl http://mac-mini:54775/v2/dreps/no_confidence/wallets/77992dc1b3f46688766c49d7920b0fb9ba33830a/  -X PUT -d '{"passphrase":<REDACTED>}' -H content-type:application/json
```

and both calls resulted in a transaction being returned and posted (check [faaccab869aa968cb136d797f0682926906852c18b32181652a9df3dfa669ade](https://preprod.cexplorer.io/tx/faaccab869aa968cb136d797f0682926906852c18b32181652a9df3dfa669ade) and [3073c860419d5da64e5a5d51244ea14856c4f0fb521835e26f813b77f6fe1526](https://preprod.cexplorer.io/tx/3073c860419d5da64e5a5d51244ea14856c4f0fb521835e26f813b77f6fe1526))

**Comment by szymonmaslowski** [comment]
> I wasn't able to reproduce the issue

Hey @abailly, as I mentioned in the description the issue occurs after some time / many votes. Could you send maybe 20 requests?

**Comment by abailly** [comment]
Sure, I can try that but: Have you tried reproduce the issue yourself?

**Comment by szymonmaslowski** [comment]
Yes, I experienced this issue with two different wallets. Two other teammates also had it. I will try to reproduce it again.

**Comment by DominikGuzei** [comment]
I can confirm that it reliably happens for me when switching my vote type a few times 👍  The amount of votes required to trigger the bug seems to be random so far.

**Comment by abailly** [comment]
I think I understand the reason, but @paweljakubas or @Anviking @david-a-clark might know better: is it not the case this depends on the observation by the wallet of the actual transactions from a block unchain? The scenario would be the following:

* post `abstain`
* if you wait for the tx to be visible by the wallet, you cannot post `abstain` again but you can post `no_confidence`
* you can keep flip-flopping as much as you want, as long as you wait for the tx to be observable by the wallet
* however, there's nothing preventing you from hitting the same endpoint several times in a row, with the same default vote, and _all_ those calls will succeed and produce a tx on chain, because every time the wallet will take into account the "real" state, ie. the one observed on chain and not the intentional one
*

**Comment by abailly** [comment]
If this diagnostic is correct then this seems to me more like a UI issue: we could imagine putting in place some guard mechanism in the server to prevent multiple submissions but it seems rather simpler to let the client poll for transactions and check the relevant ones have been observed. I might be missing something so waiting for more expert feedback.

**Comment by abailly** [comment]
A client can always query a particular transaction to know its status :

```
% curl http://mac-mini:33458/v2/wallets/2269611a3c10b219b0d38d74b004c298b76d16a9/transactions/47ca5bd13ffd4aac64fcd45fce89a155d9e87dd906774cee645fd4670e2ecd8b | jq .status
```

which can be `in_ledger` or `pending`.

**Comment by szymonmaslowski** [comment]
That might be the reason... Thanks for the investigation! We will try to reproduce it.
Definitely, we can implement the mechanism you described, especially since we have something similar for HWs that use the `POST /proxy/transactions` endpoint.
However, this behaviour is not strictly related to use with Daedalus, and can occur for any user of Cardano Wallet so IMO it still might be worth fixing 😉

**Comment by abailly** [comment]
Users having enough technical know-how to incorporate cardano-wallet as an API should probably be able to understand the difference between `pending` and `in ledger` transactions and might have their own ways to handle this situation. I don't think we want to go the extra hassle of providing a specific mechanism just for this particular endpoint.

**Comment by szymonmaslowski** [comment]
Just one question to confirm my understanding. So far we had an issue with `abstain` and `no_confidence`. Can I also "lock" the vote for a drep id/script? I guess this question is also related to: Do CWB respond with `same_vote` error when voting the second time in a row for the same drep id?

**Comment by abailly** [comment]
That's a good question, I don't have evidence here so will defer to @paweljakubas

**Comment by paweljakubas** [comment]
@szymonmaslowski yes, The same drep voting, which can be abstain, no confidence or drep (keyhash or script hash CIP-0129 compliant) should result in `same_vote` error. The tx is redundant and incur unnecessary fees so we outlaw it.

**Comment by abailly** [comment]
BTW, it seems this `same_vote` error is not documented here: https://cardano-foundation.github.io/cardano-wallet/api/edge/#operation/constructTransaction Am I missing something?

**Comment by paweljakubas** [comment]
Indeed, there should be `errSameVote` (https://github.com/cardano-foundation/cardano-wallet/blob/master/specifications/api/swagger.yaml#L5354) to https://github.com/cardano-foundation/cardano-wallet/blob/master/specifications/api/swagger.yaml#L6240

**Comment by paweljakubas** [comment]
and after that it should be listed in 403 constructTransaction endpoint error upon cllicking

**Comment by abailly** [comment]
Maybe that's _the_ issue we want to work on as a follow up to this discussion :)

**Comment by paweljakubas** [comment]
I will prepare PR - hope swagger will not protest like before

**Comment by DominikGuzei** [comment]
@abailly I'm not sure if that's the issue though - we have a wallet on preprod that stayed forever in this error mode (it's not possible to vote `abstain` nor `no-confidence` again even days after the tx have been submitted)

**Comment by abailly** [comment]
Without more info, it's really hard to tell, the wallet could be stuck for a variety of reasons.
