### ISSUE TITLE
The constructTransaction endpoint doesn't contain certificates in response

### ISSUE THREAD

**Issue by szymonmaslowski** [cardano-foundation/cardano-wallet#4871]
### Just checking...

- [X] This is a `cardano-wallet` bug.
- [X] I am using the latest `cardano-wallet` release.
- [X] I am using the *correct* `cardano-node` version for that release of `cardano-wallet`.

### Version

v2024-11-18

### Platform

macOS 14

### Installation method

Nix

### Network configuration

preview

## Steps to Reproduce

Call the [constructTransaction](https://cardano-foundation.github.io/cardano-wallet/api/edge/#operation/constructTransaction) endpoint with `{ vote: 'abstain' }` payload

### Expected behavior

The response contains a `coin_selection.certificates` with appropriate certificates.

### Actual behavior

 - no `coin_selection.certificates` property.
 - the cbor received under `transaction` property has the proper certificates.

**Comment by abailly** [comment]
Again, the description of the bug quite terse. @szymonmaslowski Could you please elaborate on the circumstances? A minimal reproducible test case on a testnet would be the most useful here.

**Comment by szymonmaslowski** [comment]
@abailly I can reproduce it no matter the circumstances. The `coin_selection.certificates` property is just not present in the response.

**Comment by abailly** [comment]
@paweljakubas your insights would be much appreciated here

**Comment by paweljakubas** [comment]
@abailly it seems we do not have all possibilities here https://github.com/cardano-foundation/cardano-wallet/blob/master/lib/api/src/Cardano/Wallet/Api/Http/Shelley/Server.hs#L4591

As we need only take into consideration this https://github.com/cardano-foundation/cardano-wallet/blob/master/lib/wallet/src/Cardano/Wallet/Transaction.hs#L342

But this should also be included https://github.com/cardano-foundation/cardano-wallet/blob/master/lib/wallet/src/Cardano/Wallet/Transaction.hs#L354

**Comment by paweljakubas** [comment]
we should have it from here https://github.com/cardano-foundation/cardano-wallet/blob/master/lib/wallet/src/Cardano/Wallet/Transaction.hs#L234

**Comment by abailly** [comment]
I see, so what you mean is that we need to take into account _both_ delegation and voting actions when constructing certificates in the coin selection?

**Comment by paweljakubas** [comment]
Plus check the presence of certificates somewhere here :
https://github.com/cardano-foundation/cardano-wallet/blob/master/lib/integration/scenarios/Test/Integration/Scenario/API/Shelley/TransactionsNew.hs#L3696

Please remember that we are expecting the following upon voting:
1. no delegation to stake pool, no voting => both registration and voting certificates
2.  delegating to stake pool, no prior voting=> voting certificate
3.  delegating to stake pool,  voting=> voting certificate

**Comment by paweljakubas** [comment]
it is already taken into account, but we have not expose it in this place, ie. in response of tx when constructing

**Comment by abailly** [comment]
> Plus check the presence of certificates somewhere here : https://github.com/cardano-foundation/cardano-wallet/blob/master/lib/integration/scenarios/Test/Integration/Scenario/API/Shelley/TransactionsNew.hs#L3696
> 
> Please remember that we are expecting the following upon voting:
> 
> 1. no delegation to stake pool, no voting => both registration and voting certificates
> 2. delegating to stake pool, no prior voting=> voting certificate
> 3. delegating to stake pool,  voting=> voting certificate

This looks like a great test to me :)

**Comment by paweljakubas** [comment]
4. Also when quitting you should see stake key deregistration certificate

**Comment by paweljakubas** [comment]
Also see how it is done for decodeTransaction as it is supported there - here is how it is checked : https://github.com/cardano-foundation/cardano-wallet/blob/master/lib/integration/scenarios/Test/Integration/Scenario/API/Voting.hs#L1159C1-L1177C13

**Comment by paweljakubas** [comment]
Plus `Test.Integration.Scenario.API.Voting` might be even better place to put tests imho
