### ISSUE TITLE
ADP-3488 Deposit wallet can sign payments transactions

### ISSUE THREAD

**Issue by david-a-clark** [cardano-foundation/cardano-wallet#4873]
### The problem that you wish to solve

The deposit wallet's payments interface currently lacks the ability to sign transactions because we cannot derive signing keys for all consumed addresses. This capability is essential for completing transactions initiated through this interface.

### Description

We want to be able to sign transactions created through the Payments interface of the deposit wallet

This requires being able to derive all signing keys for all consumed addresses

**Comment by abailly** [comment]
Is this not done? We demoed it in Berlin.

**Comment by david-a-clark** [comment]
Moved to done,
