### ISSUE TITLE
Add building and caching of `cardano-http-bridge` in Travis conf file

### ISSUE THREAD

**Issue by paweljakubas** [cardano-foundation/cardano-wallet#5]
# Context

We want to have CI set up for the new `cardano-wallet` in order to have a means to automatically build the code and run all our tests against the build. At this moment we decided to go with Travis, so we want to get the `.travis.yaml` from the previous `cardano-wallet` review it and remove all unnecessary dependencies to `cardano-sl` from it. Instead, we want to depend on `cardano-http-bridge` as a gate for receiving blocks from the mainnet/testnet. 

# Decision

In order to use this repo with `cardano-http-bridge` we need to add instructions for building and caching Rust http-bridge to .travis.yml

---

# Development Plan

- [ ] I intend to review the build instruction locally 
- [ ] I intend to review travis documentation about Rust to see if there's anything good to know about it
- [ ] I intend to add necessary build instruction of the http bridge in the build steps of the CI, trying to make it a job running in parallel from our compilation
- [ ] I intend to make sure that the `cardano-http-bridge` is within the available `PATH` such that we can refer to it in our various scripts.

# PR

| Number   | Base      |
| ---      | ---       |
| #64       | `master`  |

# QA 

- cf [PR comment](https://github.com/input-output-hk/cardano-wallet/pull/65#issue-261175606)

**Comment by piotr-iohk** [comment]
lgtm :+1:
