### ISSUE TITLE
Use ticking function to get blocks

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#52]
# Context

We have:
- a ticking function (#3)
- a function to get blocks (#12)
- a running `cardano-http-bridge` subprocess (#8 -- in progress)

The ticking function should call the function to get blocks.

# Decision

Add a function to get blocks every tick and log them.

```haskell
startBlockSyncer
    :: MonadChainProducer m
    => NetworkName
    -> Port
    -> m ()
```

This function will be called from `main` and won't normally return. 

# Acceptance Criteria

1. Must be able to catch up with blocks from chain producer.
2. Must process (by logging to stdout) the blocks received.

---

# Development Plan

- [x] Implement `startBlockSyncer`
- [x] Call `startBlockSyncer from `main`
- [ ] ~~Add `iohk-monitoring-framework` and use the basic set up which they have documented. (Maybe not yet -- haven't decided)~~
- [x] Log new blocks at "info" level
- [x] Rely on an externally launched `cardano-http-bridge`
- [ ] ~~Reflect upon design of the receive and process blocks feature, and propose then implement changes.~~

# PR

| Number   | Base      |
| ---      | ---       |
| #54       | `master`  |
| #63       | `master`  |
| #52       | `master`  |
| #71 | `master` |

# QA 

- Okay, we do now connect and receives blocks from the http bridge, pretty much epoch per epoch. Note that this is very very rudimentary for now and we are missing quite a few features coming soon:
    - Ability to persist the progression (ideally, we do want to process blocks as we fetch them, and store the latest tip we've processed).
    - Handling rollbacks and duplicates

- Still, this can be manually tested by starting the current "wallet server" alongside the http bridge. Provided you've installed in cardano-http-bridge (`cargo install https://github.com/input-output-hk/cardano-http-bridge.git`):

```
cardano-http-bridge start --port 1337 & 
stack exec -- cardano-wallet-server --http-bridge-port 1337
```

This should print all blocks received from the http bridge, until the tip block is reached, whereupon a network block should be printed every 20 seconds.

- Also, check what happens if the node backend crashes (or gets killed).

**Comment by KtorZ** [comment]
>  Add iohk-monitoring-framework and use the basic set up which they have documented. (Maybe not yet -- haven't decided)

We need to discuss that further before going to far with this :) 
This is almost a U/S on its own and requires proper thoughts, pros and cons, etc..

**Comment by rvl** [comment]
> This [logging] is almost a U/S on its own and requires proper thoughts, pros and cons, etc..

Sure, agreed.

**Comment by piotr-iohk** [comment]
lgtm :+1: 
I was able to connect and get blocks from `mainnet` and `testnet`:
1.  Mainnet: Run cardano-http-bridge with `cargo run --release -- start --port 1337 --template mainnet` and wallet with `stack exec -- cardano-wallet-server --network mainnet --http-bridge-port 1337`
2. Testnet: Run cardano-http-bridge with `cargo run --release -- start --port 1337 --template testnet` and wallet: `stack exec -- cardano-wallet-server --network testnet --http-bridge-port 1337`

It seems that it is really not a lot of effort to also be able to connect from wallet to staging (as cardano-http-bridge seems to offer that as well): `cargo run --release -- start --port 1337 --template staging`
