### ISSUE TITLE
Maximum number of inputs are applied to each output individually and not globally

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#522]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Windows & OSX & Linux) | Code  |

# Context
 
 

The coin selection selects coins from available UTxO up to a certain limit (which is implicitly fixed by the transaction size). However, it seems that this limit isn't respected as, in some cases, our coin selection would generate transactions with far more inputs than the allowed max size.

# Steps to Reproduce

After some investigation, I've found two unit tests that illustrate rather well what's going on:

(from `CoinSelection/RandomSpec`)
```hs
        coinSelectionUnitTest random "each output requires < maxNumOfInputs"
            (Left $ ErrMaximumInputsReached 9)
            (CoinSelectionFixture
                { maxNumOfInputs = 9
                , utxoInputs = replicate 100 1
                , txOutputs = NE.fromList (replicate 100 1)
                })

        coinSelectionUnitTest random "each output requires more than maxNumInputs"
            (Left $ ErrMaximumInputsReached 9)
            (CoinSelectionFixture
                { maxNumOfInputs = 9
                , utxoInputs = replicate 100 1
                , txOutputs = NE.fromList (replicate 10 10)
                })
```

## Expected behavior

Both tests should pass and yield an error regarding max number of inputs.

## Actual behavior
 
<A clear and concise description of what you observe instead. If applicable add screenshots to help explain your problem.>

The first one doesn't pass and generate an invalid selection with far too many coins selected, while the second does successfully pass:

```
    max=9, UTxO=[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1], Output=[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1] --> Left (ErrMaximumInputsReached 9) (each output requires < maxNumOfInputs) FAILED [1]
    max=9, UTxO=[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1], Output=[10,10,10,10,10,10,10,10,10,10] --> Left (ErrMaximumInputsReached 9) (each output requires more than maxNumInputs)
```
```
  1) Cardano.Wallet.Primitive.CoinSelection.Random, Coin selection : random algorithm unit tests, max=9, UTxO=[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1], Output=[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1] --> Left (ErrMaximumInputsReached 9) (each output requires < maxNumOfInputs)
       expected: Left (ErrMaximumInputsReached 9)
        but got: Right (CoinSelectionResult {rsInputs = [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1], rsChange = [], rsOutputs = [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]})
```

---

# Resolution Plan

- [x] Write unit test to illustrate the issue (for both largest first and random)
- [x] Figure out how to deplete the max number of inputs as we cover a selection
    - [x] Most likely, the options needs to be part of the accumulated result, rather than being a top-level function argument..

# PR

| Number   | Base      |
| ---      | ---       |
| #523      | `master` |

# QA 

- Unit tests added as explained above in:
    - [`CoinSelection/LargestFirstSpec`](https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Cardano/Wallet/Primitive/CoinSelection/LargestFirstSpec.hs#L156-L170)
    - [`CoinSelection/RandomSpec`](https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Cardano/Wallet/Primitive/CoinSelection/RandomSpec.hs#L161-L175)

- Note that, the problem was only present in the "random" part, and not in the "improvement" part as illustrated by the following unit test:
    - [`CoinSelection/RandomSpec`](https://github.com/input-output-hk/cardano-wallet/blob/1d6a19c5eec681564c8b989860cce937679f0a88/lib/core/test/unit/Cardano/Wallet/Primitive/CoinSelection/RandomSpec.hs#L130-L141)

**Comment by piotr-iohk** [comment]
lgtm :+1:
