### ISSUE TITLE
Port the DSL module from the integration framework

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#55]
# Context

In `cardano-wallet-legacy` we had [integration tests](https://github.com/input-output-hk/cardano-wallet-legacy/tree/develop/test/integration/Test/Integration) written in a custom [DSL](https://github.com/input-output-hk/cardano-wallet-legacy/blob/develop/test/integration/Test/Integration/Framework/DSL.hs). We want integration tests in this repo.
# Decision

Port the DSL in preparation of adding integration tests here. The [DSL](https://github.com/input-output-hk/cardano-wallet-legacy/blob/develop/test/integration/Test/Integration/Framework/DSL.hs) is a long file, but we should only need the "core" parts of it.

# Acceptance Criteria

1. We _must_ identify appropriate parts of [DSL.hs](https://github.com/input-output-hk/cardano-wallet-legacy/blob/develop/test/integration/Test/Integration/Framework/DSL.hs)(and potentially related modules) for our new code-base
2. We _must_ port these

---

# Development Plan

- [x] I intend(ed) to get the DSL module compiling
- [x] New plan - #83 already seems like what we need here, so I think it would be enough to add 3cbf665 as a follow up.

# PR

| Number   | Base      |
| ---      | ---       |
| #83        | `master`  |

# QA 

- Verify that `DSL.hs` contains plausible functions for executing test scenarios, given that we don't have an API server in place, nor any code to start a dev cluster (for node backend to connect with).

**Comment by piotr-iohk** [comment]
lgtm :+1:
