### ISSUE TITLE
Parameterize the wallet layer over `Key`

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#557]
# Context

We currently define `Key` as:

```hs
newtype Key (level :: Depth) key = Key { getKey :: key }
    deriving stock (Generic, Show, Eq)
```

However, with the introduction of the random derivation scheme, there's a couple of issues that arise from this model. Random derivation requires more information than just the raw public key in order to derive addresses from Key. This is captured by the `KeyToAddress` class. 

In the case of random derivation, one needs:

- The wallet root public key
- The underlying account derivation index 
- The underlying address derivation index
- The address public key

# Decision

So, in order to allow using different sort of keys in the wallet backend, we'll parameterize the `WalletLayer` over a key parameter, and only instantiate that parameter when defining the various API handlers we define.

The `Key` is only use in two places in the `WalletLayer`: 

```hs
    attachPrivateKey
        :: WalletId
        -> (Key 'RootK XPrv, Passphrase "encryption")
        -> ExceptT ErrNoSuchWallet IO ()
```

and

```hs
    withRootKey
        :: forall e a. ()
        => WalletId
        -> Passphrase "encryption"
        -> (ErrWithRootKey -> e)
        -> (Key 'RootK XPrv -> ExceptT e IO a)
        -> ExceptT e IO a
```

Note however that, in order to serialize the key to the database, we currently rely on 

```hs
serializeXPrv
    :: (Key purpose XPrv, Hash "encryption")
    -> (ByteString, ByteString)

deserializeXPrv
    :: (ByteString, ByteString)
    -> Either String (Key purpose XPrv, Hash "encryption")
```

from the `Cardano.Wallet.Primitive.AddressDerivation` module. These function will likely need to be promoted to type-class' methods and required as a class-constrained in the database layer. Note that we may have to define a rather extensive DSL for key manipulation:

```hs
class WalletKey (key :: * -> * -> *) where
   publicKey :: key level XPrv -> key level XPub
   digest :: HashAlgorithm a => key level XPub -> Digest a 
   changePassphrase :: ...
   keyToAddress :: key 'AddressK XPub -> Address
   etc ...
```

# Acceptance Criteria

1. The `WalletLayer` _must_ work with a parametric key type. 

1. The `WalletLayer` _may_ define type-classes as necessary to bestow necessary powers for key manipulation, serialization and derivation.

1. Current `Key` definitions and related specific functions _should_ be moved into `Cardano.Wallet.Primitive.AddressDerivation.Sequential`.

1. `Key` representation for the sequential scheme _should_ remain unchanged.

1. New definitions for random derivation _should_ be defined in `Cardano.Wallet.Primitive.AddressDerivation.Random`. 

1. It _must_ be possible to derive an `Address` from a `Key` in the random scheme. 

---

# Development Plan

- [x] Work backwards from `rndToAddress`
- [ ] Remove hardcoding of SeqKey as much as possible, to make things more polymorphic.
- [x] Implement `instance KeyToAddress t RndKey`
- [x] Fix type signature of Random.encodeDerivationPath because derivation path is now included in the RndKey.
- [x] Implement `instance PersistKey RndKey` ⇒ #612
- [x] Remove AddressDerivation.Common module (actually maybe we can keep it for common functions used by PersistKey). ⇒ #612

# PR

| Number   | Base      |
| ---      | ---       |
| #557        | `master`  |
| #610        | `master`  |
| #611        | `master`  |
| #612 | `master` |

# QA 

 - This is mostly a refactor so it shouldn't introduce new features that need to be tested.
 - But it does add a function to derive and encode random scheme addresses.
   - The new thing which is added is an encoder for the HD random scheme payload which includes derivation path.
   - The derivation path encoder is tested via a roundtrip test with the derivation path decoder.
   - The derivation path decoder is golden-tested using HD random addresses generated with the old wallet.

**Comment by KtorZ** [comment]
I think this one is mostly done, right ?

**Comment by rvl** [comment]
Yes it's mostly done and meets the AC. The last thing to do is "Remove hardcoding of SeqKey as much as possible, to make things more polymorphic." which I started with #623. But if that PR is blocked on a decision about the API, then we could say this is done now.

**Comment by KtorZ** [comment]
Yes, the API layer isn't to be parameterized yet. We're still deciding on the features and the approach regarding legacy addresses. So, for now, we'll stick with the implementation of the building blocks for the random scheme and wait a bit for the requirements regarding the user facing aspects.

**Comment by piotr-iohk** [comment]
lgtm.

One question, so 

_But it does add a function to derive and encode random scheme addresses._ 

fullfils the requirement -> 

_6. It must be possible to derive an Address from a Key in the random scheme._
, correct?

**Comment by rvl** [comment]
Yes it derives/encodes from key →derivation path →payload → address.
