### ISSUE TITLE
Implement `IsOurs` for random derivation scheme

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#558]
# Context

[Cardano.Wallet.Primitive.AddressDiscovery](https://github.com/input-output-hk/cardano-wallet/blob/e752723b35764d57fe50aa2998a0eece7167709c/lib/core/src/Cardano/Wallet/Primitive/AddressDiscovery.hs#L109-L130)
```hs
-- | This abstraction exists to give us the ability to keep the wallet business
-- logic agnostic to the address derivation and discovery mechanisms.
--
-- This is needed because two different address schemes lives on Cardano:
--
--   - A hierarchical random scheme:
--      rather 'custom' made, with several flaws; this is the original and now
--      legacy address scheme.
--
--   - A hierarchical sequential scheme:
--      a new scheme based on the BIP-0044 specification, which is better suited
--      for our present needs.
--
-- In practice, we will need a wallet that can support both, even if not at the
-- same time, and this little abstraction can buy us this without introducing
-- too much overhead.
class IsOurs s where
    isOurs
        :: Address
        -> s
        -> (Bool, s)
        -- ^ Checks whether an address is ours or not.
```

# Decision

We need to define a new state `RndState` upon which will be defined all the discovery capabilities for defining a wallet.

Address are considered _ours_ in the random derivation when we are able to decode their derivation path. The derivation path is encrypted using the hash of the wallet root public key.
So, this is likely something to be kept in the state `s`

# Acceptance Criteria

1. We _must_ define a new `RndState` type, analogous to `SeqState` which will carry information needed by the random scheme. 

1. `RndState` definition _may_ be extended by future ticket.

1. We _must_ implement `IsOurs` for `RndState`

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #616       | `master`  |

# QA 

1. This should have golden tests (data sourced from cardano-sl) and properties at the unit test level.

**Comment by piotr-iohk** [comment]
lgtm :+1:
