### ISSUE TITLE
Implement `GenChange` for random scheme

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#560]
# Context

[Cardano.Wallet.Primitive.AddressDiscovery](https://github.com/input-output-hk/cardano-wallet/blob/e752723b35764d57fe50aa2998a0eece7167709c/lib/core/src/Cardano/Wallet/Primitive/AddressDiscovery.hs#L151-L161)
```hs
-- | Abstracting over change address generation. In theory, this is only needed
-- for sending transactions on a wallet following a particular scheme. This
-- abstractions allows for defining an heuristic to pick new change address. For
-- instance, in BIP-44, change addresses belong to a particular change chain
-- (also called "Internal Chain").
class GenChange s where
    genChange
        :: s
        -> (Address, s)
        -- ^ Generate a new change address for the given scheme. The rules for
        -- generating a new change address depends on the underlying scheme.
```

# Decision

Ideally, we want to keep track of previously generated change indexes so we don't generate already generated indexes (even if we generate random indexes, clashes are still likely after many generations). Likely this means that we need something analogous to `PendingIxs` in the state, although probably not bounded and, containing the indexes of not only the previously generated change addresses, but of any known addresses that has been randomly generated. 

Note that, because the legacy scheme is currently called "random", it doesn't mean that we actually have to generate random address indexes :upside_down_face:  ... A possible approach to change management here could be to split the address space in two, and consider the upper part to be only change addresses. After restoration, we can have a list of some "blacklisted" elements that happened to be in the upper part and that aren't valid indexes for change addresses. Then, when a new change address is needed, we can simply chose the next in line, skipping blacklisted indexes. This makes sure that we avoid clashes for change addresses in a rather simple way. In the end, it only requires to keep in memory:

- A blacklist of addresses that have already been used 
- A current "cursor" which tells us the index of the next change address

# Acceptance Criteria

1. `GenChange` _must_ be implemented.

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #625      | `master`  |
| #655      | `master`  |

# QA 

1. Property tests to ensure that generated change addresses are valid. This is `prop_changeAddressesBelongToUs` in RandomSpec.hs.
2. It's probably not feasible to dumbly check that addresses aren't re-used, because there are 2<sup>31</sup> address indices (although birthday paradox might help in testing that). So the tests that check for illegal re-use of addresses need to have access to internal RndState variables (i.e. white box testing). This is tested by `prop_forbiddenAddreses` in `RandomSpec.hs`.
3. Database save/restore of RndState should be tested. See `SqliteSpec.hs` for that.

**Comment by rvl** [comment]
If we generate change address indices in a sequential, predictable way, then (I think) this will leak information about the symmetric key used to encrypt the derivation path payload - because the cardanoNonce is fixed. I'm not sure whether that's acceptable or not.

**Comment by rvl** [comment]
The symmetric payload encryption key is derived from the public key anyway. PR #655

**Comment by piotr-iohk** [comment]
lgtm.
