### ISSUE TITLE
Implement `KnownAddresses` for random scheme

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#562]
# Context

[Cardano.Wallet.Primitive.AddressDiscovery](https://github.com/input-output-hk/cardano-wallet/blob/e752723b35764d57fe50aa2998a0eece7167709c/lib/core/src/Cardano/Wallet/Primitive/AddressDiscovery.hs#L186-L194)
```hs
-- | Extract the list of all known addresses.
--
-- NOTE: Change addresses aren't considered "known" until they've been used. The
-- rationale is that, we don't want users or consumers of the wallet to be using
-- change addresses prematurely.
class KnownAddresses s where
    knownAddresses
        :: s
        -> [Address]
```

# Decision

Unlike sequential derivation, we can't derive this information from the index only. We will likely need to store this information in the state too. This overlaps to some extent with the 'blacklist' approach described in #560 regarding generation of change addresses.

# Acceptance Criteria

1. `KnownAddresses` _must_ be implemented for the random scheme

---

# Development Plan

1. Use the discovered addresses list from RndState as, implemented in #560.
2. Pending addresses are not part of the list.

# PR

| Number   | Base      |
| ---      | ---       |
| #625       | `master`  |
| #657 | `master` |

# QA 

The properties of `KnownAddresses` are covered in `AddressDerivation.RandomSpec`.

**Comment by piotr-iohk** [comment]
lgtm.
