### ISSUE TITLE
There is not cardano-wallet command

### ISSUE THREAD

**Issue by Victoryfan** [cardano-foundation/cardano-wallet#571]
After used the stack to build cardano-wallet,  but there is not cardano-wallet command to use.
Is there something wrong?

**Comment by piotr-iohk** [comment]
Hi @Victoryfan,

Currently we have `cardano-wallet-http-bridge` and `cardano-wallet-jormungandr` which are suppose to work with their respective backends - [cardano-http-bridge](https://github.com/input-output-hk/cardano-http-bridge) and [jormungandr](https://github.com/input-output-hk/jormungandr). It is not released yet, but that's how it is in the current `master`.

**Comment by Victoryfan** [comment]
> Hi @Victoryfan,
> 
> Currently we have `cardano-wallet-http-bridge` and `cardano-wallet-jormungandr` which are suppose to work with their respective backends - [cardano-http-bridge](https://github.com/input-output-hk/cardano-http-bridge) and [jormungandr](https://github.com/input-output-hk/jormungandr). It is not released yet, but that's how it is in the current `master`.

Thanks. I mean how can use the following command as picture, or I should use cardano-wallet-jormungandr instead of cardano-wallet. 
I don't know how to build and get the 'cardano-wallet' to do as picture:
![image](https://user-images.githubusercontent.com/25604389/61617457-49d43e00-ac9d-11e9-9e76-d0ac97026442.png)

**Comment by piotr-iohk** [comment]
If you are using recent `master` branch you can use `cardano-wallet-http-bridge` pretty much the same as you used to use `cardano-wallet` (they are using the same backend -> `cardano-http-bridge`). `cardano-wallet-jormungandr` is using different backend, so there will be some differences with its `launch` and `serve` parameters.

Please also note that our wikis (in particular https://github.com/input-output-hk/cardano-wallet/wiki/Wallet-command-line-interface) are up-to-date with our latest release https://github.com/input-output-hk/cardano-wallet/releases/tag/v2019-07-02 and not with `master` branch.

**Comment by Victoryfan** [comment]
> If you are using recent `master` branch you can use `cardano-wallet-http-bridge` pretty much the same as you used to use `cardano-wallet` (they are using the same backend -> `cardano-http-bridge`). `cardano-wallet-jormungandr` is using different backend, so there will be some differences with its `launch` and `serve` parameters.
> 
> Please also note that our wikis (in particular https://github.com/input-output-hk/cardano-wallet/wiki/Wallet-command-line-interface) are up-to-date with our latest release https://github.com/input-output-hk/cardano-wallet/releases/tag/v2019-07-02 and not with `master` branch.

Thanks a lot! And do you know how to build offline wallet for exchange?

**Comment by piotr-iohk** [comment]
Actually to interact with the current Cardano mainnet (Byron) I'd recommend using our front-end wallet -> [Daedalus](https://daedaluswallet.io/). (if you are aiming for having offline wallet it has a _paper wallet_ feature too).

Please note that this source code repository contains the next major version of Cardano Wallet Backend, which has been completely rewritten for the [Shelley](https://cardanoroadmap.com/) phase (which has not been released yet).

**Comment by Victoryfan** [comment]
> Actually to interact with the current Cardano mainnet (Byron) I'd recommend using our front-end wallet -> [Daedalus](https://daedaluswallet.io/). (if you are aiming for having offline wallet it has a _paper wallet_ feature too).
> 
> Please note that this source code repository contains the next major version of Cardano Wallet Backend, which has been completely rewritten for the [Shelley](https://cardanoroadmap.com/) phase (which has not been released yet).
Do you mean the Daedalus is a offline wallet? So the process of creating address has walletid to join in
?

**Comment by KtorZ** [comment]
@Victoryfan 

May I ask you some precisions about what you call an "offline wallet" (to make sure that we can actually speak about the same thing :))

**Comment by Victoryfan** [comment]
> @Victoryfan
> 
> May I ask you some precisions about what you call an "offline wallet" (to make sure that we can actually speak about the same thing :))

I mean i want to realize the aim of creating address by myself not through wallet. But the addresses I created are started with "Ae2tdPw.." they looked like walletid.  So if i want to created address start with"DdzFFz...", it should use walletid, right?

**Comment by KtorZ** [comment]
@Victoryfan okay, you have several options then:

- Use the `cardano-wallet` as a Haskell library. In particular: https://input-output-hk.github.io/cardano-wallet/haddock/edge/cardano-wallet-core-2019.6.24/Cardano-Wallet-Primitive-AddressDerivation.html will be a useful module to write some Haskell code that will perform address derivation from a root private key.

- Use [`cardano-cli`](https://github.com/input-output-hk/cardano-cli) which is as a command-line interface which provides some low-level primitives like address derivation.

**Comment by Victoryfan** [comment]
@KtorZ okay, very thanks!
 And do you know how to traverse blocks. I should get the transactions related to addresses created by myself. Now i can use api only the wallet-api https://cardanodocs.com/technical/wallet/api/v1/#, but i should have walletid to use related interface. Are there some other methods to traverse block?

**Comment by Victoryfan** [comment]
@KtorZ I use http-bridge to send signed transaction,but it returned 'Block protocol error'. Is there someting wrong? 
![image](https://user-images.githubusercontent.com/25604389/61781204-86876d00-ae36-11e9-85be-3c15cfd5a6b9.png)
