### ISSUE TITLE
Resolve address and amount for incoming transaction inputs

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#573]
# Context

When listing transactions, users expect to see the source address and amount used for each input of each transaction.

Currently cardano-wallet is able to show address and amount for inputs of outgoing transaction, but not incoming transactions. For incoming transactions, it can only show a `(TxId, Index)` pair.

# Decision

While restoring the wallet, the `(TxId, Index) -> (Address, Amount)` mapping should be cached so that it's possible to resolve addresses and amounts for incoming transactions.

# Acceptance Criteria

1. The API _must_ return addresses and amounts for each input of a transaction.
2. The API _may_ also return `(TxId, Index)` values as extra information for each input of a transaction.

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #?       | `master`  |

# QA

**Comment by KtorZ** [comment]
re-located as https://github.com/input-output-hk/cardano-wallet/wiki/Roadmap#transaction-history-index
