### ISSUE TITLE
How can i use the wallet backend API 2.0.0?

### ISSUE THREAD

**Issue by Victoryfan** [cardano-foundation/cardano-wallet#585]
I don't know how to use the wallet backed API 2.0.0 and what's the difference between v1 and v2?
And how to start the cardano-wallet?

**Comment by KtorZ** [comment]
Hi @Victoryfan, if you haven't yet looked into the latest release notes (https://github.com/input-output-hk/cardano-wallet/releases/tag/v2019-07-24), I encourage you to do so.

In particular, have a look at the `Installation Instructions` section for `Jörmungandr`.  There are also links to the [command-line interface user-guide](https://github.com/input-output-hk/cardano-wallet/wiki/Wallet-command-line-interface/0782f8b07bdb03fb2db95c7632cfa92137282f96) and, to the new [REST API@v2.0.0](https://input-output-hk.github.io/cardano-wallet/api/v2019-07-24). 

Hope it helps.

**Comment by Victoryfan** [comment]
Thank you @KtorZ, could you give me some suggestions to traverse block and transaction. I created offline addresses, and i want to get these addresses related transactions. Is there api for analyzing block?

**Comment by KtorZ** [comment]
Not currently. The `wallet-backend` is currently more like a all-in-the-box solution that keeps track of a bunch of addresses for you from a mnemonic sentence. 

If you're looking into doing block traversal yourself, you might as well just connect to a node and use whatever networking interface it provides to fetch blocks. 
Alternatively, you could use an explorer (seiza is being developed by Emurgo and a new one will be developed by IOHK soon).

**Comment by Victoryfan** [comment]
Yeah, I builded wallet-connect-mainnet, explorer-connect-mainnet via cardano-sl. But the wallet-mainnet only supports the v1 api, it can't get trasactions related offline addresses. And the explorer-mainnet now syncs process has bug, it crashs very often during syncing.  So I don't know is there other plans for this issue or not.  HuoBi wallet has integrated ADA, do you know how they get transactions related to their offline addresses?

**Comment by Victoryfan** [comment]
And you say use whatever networking interface, can you tell me where is it? Or you say is also a wallet-mainnet?

**Comment by KtorZ** [comment]
Nodes new networking interfaces are currently under development. You can have a look into [Jörmungandr](https://github.com/input-output-hk/jormungandr) or into [ouroboros-network](https://github.com/input-output-hk/ouroboros-network).

Yet, I'd recommend to stick with the current explorer and the tools that currently deployed in production. Have you tried contacting the technical support desk regarding the explorer bugs?

**Comment by Victoryfan** [comment]
Yeah, they are fixing bugs. Thank you.
