### ISSUE TITLE
Rename & Archive 'cardano-wallet' and create a new fresh repostiory

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#6]
# Context

As described in the [roadmap](https://github.com/input-output-hk/cardano-wallet/wiki/Roadmap), we are now creating a new repository and moving away from the legacy code. We have a bunch of things to setup in order to achieve this. 

# Decision

Create a new repository and import relevants bits from the wiki and the github templates. We also need to re-create the Zenhub board and have proper milestones aligned with our roadmap.

---

# Development Plan

- [x] I intend to rename the old repository to `cardano-wallet-legacy`
- [x] I intend to create a new fresh repository `cardano-wallet`
- [x] I intend to import relevant parts of the wiki, and leave out whatever concerns the Byron era
- [x] I intend to import and adjust the github templates (PR, Task, Bug) we've been using
- [x] I intend to setup the Zenhub board to match what's specified in the development process
- [x] I intend to create milestones aligned with our roadmap, give end date to milestones and put corresponding issues in their milestones

# PR

| Number | Base |
|---|---|
| #24 | `master` |

# QA 

- New repository created with same name as before `cardano-wallet`
- Wiki populated, removed stuff from the Byron Era (see [Wiki](https://github.com/input-output-hk/cardano-wallet/wiki))
- Added and updated templates for Tasks, Bugs and PRs (~~removed the "acceptance criteria" section, now conflated with "decisions" and~~, remove the "retrospective" section; we'll do as part of the iteration planning).
- Adjusted Zenhub board
- Created corresponding milestones (see [Milestones](https://github.com/input-output-hk/cardano-wallet/milestones)) and added corresponding tasks to milestones

**Comment by piotr-iohk** [comment]
@KtorZ, I am sligthly hesitant on removing the `Acceptance Criteria`. I acknowledge that in reality it may be  sometimes the same thing, however in my understanding decision is rather to express high level intention of what one wants to do whereas acceptance criteria define set of statements that define when work item is complete and working as expected. Acceptance criteria is really a set of capabilities which can be either passed or failed.

I think I would prefer to call this section `Acceptance Criteria` rather then `Decision` or maybe `Decision \ Acceptance Criteria` or maybe bring back `Acceptance Criteria` after all?

**Comment by KtorZ** [comment]
@piotr-iohk re-introduced the 'Acceptance Criteria' section as part of the template, so this will hold for all new issues we create.

**Comment by stasio33** [comment]
lgtm :+1:

**Comment by piotr-iohk** [comment]
lgtm :+1:
