### ISSUE TITLE
Implement `PersistState` for random scheme

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#621]
# Context

To load/save random AD scheme wallets to the sqlite database, the class members of `PersistState` must be implemented.

# Decision

# Acceptance Criteria

1. The DBLayer can be instantiated with RndState.
2. Loading and saving wallets works for random AD scheme wallets.

---

# Development Plan

- [x] implement `instance PersistState DBLayer`
- [x] Arbitrary instance for RndState
- [x] Make DBLayer property tests polymorphic so that the instance is tested

# PR

| Number   | Base      |
| ---      | ---       |
| #622      | `master`  |
| #654      | `master`  |

# QA 

- Existing tests should be changed so that RndState is tested as well as SeqState. See `SqliteSpec.hs`.

**Comment by piotr-iohk** [comment]
lgtm.
