### ISSUE TITLE
Track block height

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#640]
# Context

From the [Ouroboros paper](https://eprint.iacr.org/2017/573.pdf), about transaction ledger properties:

> **Persistence, with parameter** _k_ ∈ ℕ. Once a node of the system
> proclaims a certain transaction _tx_ as stable, the remaining nodes,
> if queried, will report _tx_ at the same position of the ledger and
> agree on the entire prefix of the ledger (prior to _tx_).
>
> Stability is defined in terms of the blockchain: a transaction is
> declared stable if and only if it is in a block that is more than
> _k_ blocks deep in the ledger.

So the wallet cannot merely keep checkpoints for the last _k_ slots. It must keep checkpoints for the last _k_ blocks, and therefore, it must know the block height of each block.

* The _block height_ is the number of blocks on the chain since genesis.

* The _block depth_ is the distance of a block from the network tip. That is, how many descendent blocks it currently has.

# Decision

In `Cardano.Wallet.Primitive.Model`, add a field to the `Wallet` data type:

```haskell
blockHeight :: Wallet s t -> Quantity "blocks" Natural
```

Adjust `applyBlock` so that it sets the block height of a checkpoint to be one greater than then block height of the previous checkpoint.

Adjust the DBLayer schemas and functions so that `blockHeight` is saved into the `checkpoints` table.

# Acceptance Criteria

1. The `Wallet` type must have a block height

---

# Development Plan

- (Update, 13 sep) This is basically completed and tested as planned. But there might be a much simpler way (#693). This is a bit lower priority though.

This is a very small and simple change. We have added trivial tests on the Wallet Model level, that `initWallet` yields a wallet with `blockHeight = 0` and that `applyBlock` always increases it by `1`.

There is still a danger that our blockHeight calculation is wrong from calling applyBlock too few or too many times. In particular Epoch Boundary Blocks [seem to](https://input-output-rnd.slack.com/archives/CC0CLNEH1/p1564130776069900?thread_ts=1564125788.068800&cid=CC0CLNEH1) not increase the blockHeight and according to Rodney share the same `slotId` as a normal block. Jörmungandr doesn't have Epoch Boundary Blocks. The new haskell node will have, but we believe it will provide the `blockHeight` for each block such that we don't have to perform the calculation ourselves.

If the blockHeight calculation is wrong, we may keep too many unstable checkpoints, or too few. In the latter case, there will be *rare* chain-rollbacks we can only handle by restoring from genesis.

# PR

| Number   | Base      |
| ---      | ---       |
| #662        | `master`  |
| #666       | `master`  |
| #670       | `master`  |
| #673        | `master`  |
| #693        | `master`  |
| #745        | `master`  |

# QA 

1. Block height is now retrieved from each blockHeader.
1. We test that the block height starts at 0 and increases on each block-application given the test-data  `lib/core/test/unit/Cardano/Wallet/Primitive/ModelSpec.hs`.
   - `prop_initialBlockHeight`
   - `prop_applyBlocksBlockHeight`

**Comment by piotr-iohk** [comment]
@Anviking, @rvl - looking at the comment -> https://github.com/input-output-hk/cardano-wallet/pull/673#pullrequestreview-282740377

Would it be worth then to add an integration test for blockHeight?

**Comment by Anviking** [comment]
🤔 Maybe… This situation made me a bit uncomfortable too.

We *could* expose blockHeight from the API somehow and have a test for that… 

I was partly wondering some time ago whether we could take existing, pure, properties, and "lift" them to the integration-level.

Actually… we can compare our calculation with the truth from `chainHeight` in the block-binaries now. That would be really nice to test. It might turn out to be a bit tricky in practice if `NetworkLayer` doesn't work with Jörmungandr/polymorphic blocks though.

**Comment by KtorZ** [comment]
> We could expose blockHeight from the API somehow and have a test for that…


Like this:

https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/getNetworkInformation

?

**Comment by piotr-iohk** [comment]
>Actually… we can compare our calculation with the truth from chainHeight in the block-binaries now. That would be really nice to test...

So is this doable within this task?

**Comment by KtorZ** [comment]
> So is this doable within this task? 

Would require to extract the block height from binary blobs, as @Anviking started in a PR. Though, we agreed to leave that for later until we know a bit more about the feasibility of this with the new haskell blocks. It's so-to-speak, out-of-scope. 

Note that we already do it _in a way_. The restoration progress are measured by using the node's block height which is extracted from the binary block. So, if there was a discrepancy between our block height and the one from the network, we wouldn't reach 100% or reach it prematurely. 

(to be clear, we only extract the block height for the _tip_, but we don't do it for every block as this is a quite pervasive change).

**Comment by piotr-iohk** [comment]
>So, if there was a discrepancy between our block height and the one from the network, we wouldn't reach 100% or reach it prematurely.

In case this happens what are the effects/implications for a working wallet? and are we able to discover such situation in tests?

**Comment by Anviking** [comment]
@piotr-iohk Now we use the block-height from the network. No calculation that can be wrong anymore.

**Comment by piotr-iohk** [comment]
@Anviking - ok, I have added a simple manual procedure #745.
