### ISSUE TITLE
Unify DBLayer QSM model and DB.MVar

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#641]
# Context

To reduce maintenance burden we could either delete the MVar DBLayer, or have it share pure model code with the state-machine tests. Since the MVar DB is a useful diagnostic tool, let's keep it for now. Also its model datatype works better than the one in `StateMachine.hs`.

# Decision

Create a module `Cardano.Wallet.DB.Model` and move the data types from MVar to there, and modify them for rollback.

```haskell
type Database wid s t k =  Map wid (WalletDatabase s t k)
type TxHistory t = Map (Hash "Tx") (Tx t, TxMeta)
data WalletDatabase s t xprv = WalletDatabase
    { metadata :: !WalletMetadata
    , xprv :: !(Maybe xprv)
    , txHistory :: !(TxHistory t)
    , checkpoints :: ![Wallet s t]
    }
```

# Acceptance Criteria

1. MVar DBLayer and DBLayer QSM tests share a model and its functions.
2. Model functions are pure and don't use MVars, IO, etc.
3. The model supports checkpoints, but only a single checkpoint is used.

---

# Development Plan

- [x] Check that key type can be a parameter of db model.
- [x] Set up module for DB model.
- [x] Change StateMachine.hs to use it.
- [x] Change MVar DB to use it

# PR

| Number   | Base      |
| ---      | ---       |
| #660        | `master`  |

# QA 

This is a refactor so the existing tests will cover it.

**Comment by piotr-iohk** [comment]
:+1:
