### ISSUE TITLE
Save checkpoints in SQLite `DBLayer`

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#643]
# Context

Saving checkpoints to the SQL database involves attaching a slot number to all entities, and using a reversible method of deleting entities that are subject to rollback.

# Decision

1. `putTxHistory` already adds `SlotId` as part of `TxMeta`.

   But as a side-effect of inserting outgoing transactions, it
   must also "soft-delete" `utxo` entries.

   For each `InChain` transaction added, if any `utxo` has
   `input_tx_id` of that transaction, then set `utxo.slot_spent` to
   the transaction slot.

   `InChain` TxMeta entries should not replace `Pending` TxMeta
   entries with the same TxId. Both are needed, so that it's possible
   to roll back a transaction to pending.

2. `readTxHistory` will stay much the same, except it will filter out
   `status=Pending` outgoing transactions where there is also a
   `status=InChain` transaction with the same ID.

3. `putCheckpoint` should be changed so that old checkpoints are not
   deleted.

4. `readCheckpoint` will stay much the same, but ignore `utxo` entries
   with non-NULL `slot_spent`. Only the latest checkpoint information
   is interesting for wallet users.

# Acceptance Criteria

1. The effect of `putCheckpoint` and `putTxHistory` is to add data to the database, in a way that can be mostly undone by removing rows.
2. `readCheckpoint` still returns complete information for the latest checkpoint

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #686        | `master`  |
| #724        | `master`  |
| #731        | `master`  |

# QA 

We've been through quite many changes at the moment that are currently hard to test since they don't have (and shouldn't) have any visible effects until we introduce the ability to rollback in the DB engine (in #645). 

Until then, our best argument here is to have unit, state-machine and integration tests still passing despite having completely reviewed how checkpoints and UTxO are stored in the database. More testing regarding rollbacks coming with #645

**Comment by piotr-iohk** [comment]
> More testing regarding rollbacks coming with #645

and #724

**Comment by KtorZ** [comment]
Indeed!
