### ISSUE TITLE
Purge old checkpoints in `DBLayer`

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#644]
# Context

`putCheckpoint` needs adjustment so that it has enough information to maintain the checkpoint list and prune checkpoint data for stable blocks.

# Decision

The _k_ parameter is supplied as a configuration argument to
`putCheckpoint`.

```haskell
putCheckpoint
        :: DBLayer m s t k
        -> Quantity "blocks" Natural
        -> PrimaryKey WalletId
        -> Wallet s t
        -> ExceptT ErrNoSuchWallet m ()
```

After inserting the checkpoint, this function should now clean up
checkpoints which are greater than _k_ blocks old.

How to clean up:
1. Subtract _k_ from the `blockHeight` of the checkpoint.
2. Find the checkpoint with this `block_height`, and get its slot.
3. Delete all `utxo` rows with `slot_spent` < the slot.
2. Delete all `checkpoint` rows with `block_height` less than this point.

# Acceptance Criteria

1. After calling `putCheckpoint`, there will be at most _k_
   checkpoints for unstable blocks in the database.
2. No important wallet data (e.g. transactions, utxo, addresses) is
   lost due to the pruning process.

---

# Development Plan

- [x] Work on top of `paweljakubas/643/save-dblayer-checkpoints` 
- [x] Carry on with the detailed steps in the decision

# PR

| Number   | Base      |
| ---      | ---       |
| #727       | `master`  |
| #786       | `master`  |

# QA 

- Added a property test for verifying that no checkpoints older than `k` is stored in the database (see comment in #786)

**Comment by piotr-iohk** [comment]
:+1:
