### ISSUE TITLE
Implement rollback in `DBLayer`

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#645]
# Context

Rolling back the database is mostly a matter of deleting all entities
with a slot greater than the rollback point.

# Decision

1. Add the following function to `DBLayer`

```haskell
-- | Drops all checkpoints and transaction data after the given slot.
rollbackToSlot
        :: DBLayer m s t k
        -> PrimaryKey WalletId
        -> SlotId
        -> ExceptT ErrNoSuchWallet m ()
```

2. This function will delete all of these with a `slot` > the rollback_slot:
    * **incoming** tx_meta (and related entites)
    * utxo
    * checkpoint (and related entities)
    * seq_state_address (requires adding a new member to class `PersistState`)
    * rnd_state_address (requires adding a new member to class `PersistState`)

3. This function will update any `utxo` where `slot_spent` >
   `rollback_slot` setting `slot_spent = NULL`.

4. This function will update every Outgoing transaction beyond the point of rollback in such a way that their `slot` becomes the point of rollback, and their status become `pending` again.

# Acceptance Criteria

1. Rolling back to a slot will result in a database state as if the blocks since that slot were never applied in the first place, except for pending transactions, which are not removed after rollback.

---

# Development Plan

- [x] Implement rollbacks considering only checkpoints for now, and implement property tests for it
- [x] Support rolling back the tx history, check with property tests
- [x] Add a 'RollbackTo' action to the state-machine
- [x] Check the consequences of having "invalid" transactions in the database ? (see https://github.com/input-output-hk/cardano-wallet/pull/751#issuecomment-534584591) 

# PR

| Number   | Base      |
| ---      | ---       |
| #734        | `master`  |
| #743        | `master`  |
| #751        | `master`  |
| #752        | `master`  |
| #757        | `master`  |

# QA 

- [x] Added [two properties](https://github.com/input-output-hk/cardano-wallet/blob/1c90955db093a7d6642d5995bf9cb0e86ee280e6/lib/core/test/unit/Cardano/Wallet/DB/Properties.hs#L202-L206) to verify rollback behavior:

    - [x] [prop_rollbackCheckpoint](https://github.com/input-output-hk/cardano-wallet/blob/1c90955db093a7d6642d5995bf9cb0e86ee280e6/lib/core/test/unit/Cardano/Wallet/DB/Properties.hs#L549-L579): Check that given any chain and initial checkpoint, we can rollback to any previous checkpoint (up to `k=epochStability`) made following this chain
    
    - [x] [prop_rollbackTxHistory](https://github.com/input-output-hk/cardano-wallet/blob/1c90955db093a7d6642d5995bf9cb0e86ee280e6/lib/core/test/unit/Cardano/Wallet/DB/Properties.hs#L615-L620) Check that given any transaction history, rolling back to any arbitrary point has the following properties:
        - Outgoing transactions beyond the point of rollback are reschuled 
        - All transactions known before the point of rollback are still known
        - All transactions in the database after the rollback happened refer to a slot before or equal to the point of rollback

- [x] Added a `RollbackTo` command to the [state-machine](https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Cardano/Wallet/DB/StateMachine.hs#L244) making sure to interleave rollback calls with other commands.

**Comment by piotr-iohk** [comment]
lgtm.
