### ISSUE TITLE
Prepare Shelley NetworkLayer for rollback

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#646]
# Context

Adjust the Shelley network layer `nextBlocks` function so that,
instead of returning an error on rollback, it returns `RollBackward`.

This relies on the Shelley version of the network layer being a
stateful process.

# Decision

Adjust nextBlocks to possibly return a RollBackward command.

The return types are modelled loosely on the Chain Synchronisation
Protocol from the Shelley networking spec.

```haskell
data NextBlocksResult
  = AwaitReply
  | RollForward [Block (Tx t)]
  | RollBackward BlockHeader

nextBlocks :: NetworkLayer m -> BlockHeader -> ExceptT ErrGetBlocks m NextBlocksResult
```

# Acceptance Criteria

1. `ErrNextBlocksRollBack` should be removed
2. Receiving the `RollBackward` message from the node results in a `RollBackward` return value from `nextBlocks`.

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #?       | `master`  |

# QA

**Comment by KtorZ** [comment]
Any work regarding the Haskell nodes is now of lower priority until the wallet reaches completeness regarding early Shelley features. So, closing this in order to prioritize the work on Jörmungandr instead.
