### ISSUE TITLE
Global state for rollback in Jormungandr

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#647]
# Context

The wallet must be able to handle receiving a network tip which is on a different chain to what it has. The optimum rollback point will be the latest common ancestor block between the wallet and the node.

To calculate the rollback point, the Jormungandr network layer needs to track information about the unstable blocks.

# Decision

Jormungandr network layer maintains information about the unstable block headers which is updated when `networkTip` is called.

```haskell
import Data.Sequence

-- | A list of block headers and their hashes.
-- The first block in this sequence is the network tip.
-- The last block in this sequence is the block of depth _k_,
-- which is the last unstable block.
newtype UnstableBlocks = UnstableBlocks
  { getUnstableBlocks :: Seq (Hash "BlockHeader", BlockHeader) }
```

When `networkTip` is called, the unstable blocks are fetched and pushed onto the front of this sequence. Older blocks are dropped off the back so that the sequence has at most _k_
elements.

# Acceptance Criteria

1. After calling `networkTip`, the first element of the sequence must match the tip, and contain _k_ block headers.
2. The update of global state must be thread safe.

---

# Development Plan

- The difficult part of this will be testing.
- If the code for updating the state is split out then it will be possible to unit test it.
- Use a MVar for concurrent updating of state
- Hardcode _k_ for this ticket, but the value ought to be gotten from the config parameters.

# PR

| Number   | Base      |
| ---      | ---       |
| #675       | `master`  |

# QA 

The tricky logic for updating the sequence in the event of rollback is tested with property tests in `lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/NetworkSpec.hs`. This includes error cases. The test case generator creates various chains with and without forks, for various k. It compares the result of the actual code to a model function.

**Comment by KtorZ** [comment]
> Hardcode k for this ticket, but the value ought to be gotten from the config parameters.

@rvl, with #684 , the "epochStability" (a.k.a `k`) can now be extracted from the network (more exactly, from the genesis file) so it should be possible to remove the hard-coded constant once this is merged.

**Comment by piotr-iohk** [comment]
lgtm :+1:
