### ISSUE TITLE
`nextBlocks` rollback in Jormungandr

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#648]
# Context

Using the global unstable blocks state (#648), we can do a simple non-optimal rollback in the Jormungandr network layer when an alternate chain is detected.

# Decision

Adjust the `nextBlocks` return type so that rolling back is an option.

```haskell
data NextBlocksResult
  = AwaitReply
  | RollForward [Block (Tx t)]
  | RollBackward BlockHeader

data NetworkLayer t m = NetworkLayer
    { nextBlocks
        :: BlockHeader
        -> ExceptT ErrGetBlock m NextBlocksResult
    , ...
    }
```

`nextBlocks` should be modified to detect a rollback condition:

1. It should first call `networkTip` to update the global state.
2. It compares the `SlotId` of the requested `BlockHeader` to those in
   the unstable block headers.
   * If the SlotId is before the deepest unstable block header, return
     blocks as normal under the `RollForward` constructor.
   * If the SlotId is within the unstable block headers and the parent
     hash matches, return blocks in `RollForward`. If there are no
     blocks, return `AwaitReply`.
   * Otherwise, return `RollBackward` to the block header of depth _k_.

# Acceptance Criteria

1. `nextBlocks` must return `RollBackward` if the requested start point is not on the node's chain.
2. You may be able to develop a more optimal solution than rolling back the full _k_, but don't sweat over it too much. (For this to work, each wallet would need its own UnstableBlocks state, which is intersected with the global UnstableBlocks state.)
3. Because jormungandr is a concurrent process accessed through a stateless API, there should be testing of concurrency issues such as what happens if the network tip rolls back while fetching blocks.

---

# Development Plan

- Need to adjust the nextBlocks type a bit to carry around the state for calculating the intersection.
- Property tests for intersection calculation.
- Unit tests for rollback, probably by mocking JormungandrLayer.
- Integration tests with the actual jormungandr node would be pointless, unless it can fork and roll back.

# PR

| Number   | Base      |
| ---      | ---       |
| #755     | `master`  |
| #800     | `master`  |

# QA 

- As part of #755, we've implemented a rather extensive unit tests to stress a bit the networking layer and see how chain following behave. The test defines a mock Jörmungandr client (which implements the [JormungandrClient](https://input-output-hk.github.io/cardano-wallet/haddock/edge/cardano-wallet-jormungandr-2019.9.13/Cardano-Wallet-Jormungandr-Api-Client.html#t:JormungandrClient) interface that we use for Jörmungandr and produces mock blocks. We plug that mock Jörmungandr client into the actual network layer implementation and we then try to follow the chain produced by this client using the networking layer. The mock has its own internal state where it maintain a valid chain. After each API call to the mock, the mock does one of the following mutation to itself (see https://github.com/input-output-hk/cardano-wallet/blob/master/lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/NetworkSpec.hs#L427-L432):

- Add one or more blocks on its local chain
- Rewind its local chain to a point in the past (but keep old blocks in its "database")
- Garbage collect blocks in its database that are no longer on the chain

This allows for creating all sort of interesting scenario where our network layer will try to follow a chain that is evolving quite arbitrarily and, creating a lot of race conditions and concurrency problems between API calls. The quickcheck  check for 2 things:

- For any generated mock node, for all mutations, it always produce a valid chain (in the sense of blocks following each other in sequence starting from genesis, there can be gaps in the slot numbers).  

- For any generated mock node, for any value of `k > 1`, we can define a consumer that can follow the chain using the network layer and eventually be in sync with the node. 

So, the main spec does follow the node as it's evolving and until the node runs out of mutations to apply. Then, we make sure that the network layer can eventually catch up in a finite and capped number of steps. 

Once the consumer has fully synced, we also label cases of interest and to make sure that we go into some specific scenarios. For example:

```
Follow a chain with forks    
      +++ OK, passed 1000000 tests:
      56.1946% advanced more than k blocks
      53.1837% started with an empty chain
      40.6301% started with more than k blocks
      15.3164% switched to a shorter chain
      10.8648% switched to a longer chain
       9.7370% rewinded without switch
       1.4335% rolled back full k
       0.4092% recovered from genesis
```

Also, in case of failure, we display a full error log of the operation that happened on the consumer, the node and the mutation that happened on the network so that we get a very nice counter example in order to understand what's going on:

```
         Applied blocks:  0001 _ _ _ 0002 0005 _ _ 0006 0007 _ 0008 _ 0009 000a 000b 000c 000d
         Node chain:      0001 _ _ _ 0002 0003 0004 0005 _ _ 0006 0007 _ 0008 _ 0009 000a 000b 000c 000d
         Logs:          
         [CONSUMER] nextBlocks SlotId {epochNumber = 0, slotNumber = 0}
         [PRODUCER] getTipId
             ↳  Hash {getHash = "genesis"}
         [NETWORK ] NodeAddBlocks [MockBlock {mockBlockId = Hash {getHash = "0000"}, mockBlockPrev = Hash {getHash = "genesis"}, mockBlockSlot = SlotId {epochNumber = 0, slotNumber = 0}, mockBlockContent = 0},MockBlock {mockBlockId = Hash {getHash = "0001"}, mockBlockPrev = Hash {getHash = "0000"}, mockBlockSlot = SlotId {epochNumber = 0, slotNumber = 1}, mockBlockContent = 1},MockBlock {mockBlockId = Hash {getHash = "0002"}, mockBlockPrev = Hash {getHash = "0001"}, mockBlockSlot = SlotId {epochNumber = 0, slotNumber = 5}, mockBlockContent = 2}]
         [PRODUCER] getBlock Hash {getHash = "genesis"}
             ↳  Left (ErrGetBlockNotFound (Hash {getHash = "genesis"}))
         [CONSUMER] AwaitReply
         [CONSUMER] nextBlocks SlotId {epochNumber = 0, slotNumber = 0}
```

**Comment by piotr-iohk** [comment]
LGTM :+1:
