### ISSUE TITLE
Perform rollback in wallet `restoreStep` restoration loop

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#650]
# Context

Glue the bits together to finish the rollback feature.

# Decision

1. Adjust `restoreBlocks` so that it adds a checkpoint for every `Wallet` returned by `applyBlocks`.
2. Change `restoreStep` so that it handles `RollBackward` by rolling back the database to the given slot.

# Acceptance Criteria

1. Wallet must roll back the database when `nextBlocks` returns RollBackward.
2. Restoration should begin immediately after rollback.
3. There must be adequate logging to inform the user of this situation.
4. The impact on restore time of maintaining rollback information should be examined.

---

# Development Plan

- [x] I have added an extra callback to the restoration worker to rollback on ... rollbacks.
- [x] Made sure we don't purge the very first checkpoint we create in the wallet. We might roll back up to the genesis block, so this checkpoint is needed (and currently discarded after `k` blocks)
- [x] Added a `listCheckpoints` function to the database layer to return a full list of block headers to use to find an initial intersection. The `greatestCommonBlockHeader` now works fine with sparse lists so no work to do in this area :tada:
- [x] Extended the state-machine to also yield `listCheckpoints` calls

# PR

| Number   | Base      |
| ---      | ---       |
| #812        | `master`  |

# QA 

- Added a read-only function `listCheckpoints` to the database layer, and to the state-machine. So, now tested in all sort of interleaving with other calls. 

- Rolling back in the wallet layer is the direct composition (see [here](https://github.com/input-output-hk/cardano-wallet/blob/1a5b2008e0c9797b24134d40ab275a2bd26902f1/lib/core/src/Cardano/Wallet.hs#L521-L522) and [here](https://github.com/input-output-hk/cardano-wallet/blob/1a5b2008e0c9797b24134d40ab275a2bd26902f1/lib/core/src/Cardano/Wallet/Network.hs#L281-L289)) of:

    1. Detecting chain switches at the network-level (fully tested as part of #648)
    2. Rolling back the database (fully tested as part of #645)

So, under the assumption that the network-level can correctly yield a "RollBackward" when needed, and that the call `rollbackTo` to the database works as we expect, the wallet should have no problem rolling back during the restoration loop. 

- The chain follower will log a line at the `INFO` level in the event of rollback, so this could be controlled during some smoke tests:

```
            logInfo tr $ "Rolling back to " <> pretty point
```

**Comment by piotr-iohk** [comment]
lgtm :+1:
