### ISSUE TITLE
CI tests sometimes fails with `ErrGetBlockchainParamsNetworkUnreachable`

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#658]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Windows & OSX & Linux) | Code  v Configuration v Environment v Human v Unknown |

# Context
 
 

- https://travis-ci.org/input-output-hk/cardano-wallet/builds/574325876?u tm_source=slack&utm_medium=notification

- https://input-output-rnd.slack.com/archives/GBT05825V/p1565880698032500

We've had the failure from
- https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core-integration/src/Test/Integration/Scenario/API/Addresses.hs#L62
- https://github.com/input-output-hk/cardano-wallet/blob/master/lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/API/Transactions.hs#L107

Common denominator is that they are the first tests in their respective module.

We _do_ `waitForConnection` in the test-setup:
https://github.com/input-output-hk/cardano-wallet/blob/master/exe/wallet/jormungandr/Main.hs#L335-L337

# Steps to Reproduce

1. Trigger CI build in PR or on master

## Expected behavior

- Tests are not flaky
## Actual behavior
 
<A clear and concise description of what you observe instead. If applicable add screenshots to help explain your problem.>

- For some time (3 weeks?) they regularly fail because of "unexpected ErrGetBlockchainParamsNetworkUnreachable exceptions".

---

# Resolution Plan

- [ ] Collect statistics on when failures occurred on `master` via Travis API. The travis-build history for PRs are not trustable, as one can restart builds when they fail, biasing the results by hiding failures.
- [ ] It seems like there are two modules affected. Create a PR which forces Travis to run these over and over, such that we can reproduce the failures consistently.

# PR

| Number   | Base      |
| ---      | ---       |
| #?       | `develop` |

# QA

**Comment by Anviking** [comment]
I can estimate the failure rate from the Travis API to 7% from master-builds. Unfortunately it _seems_ like only builds from the last week are available.

```bash
$ curl -H "Travis-API-Version: 3" -H "User-Agent: API Explorer" \
  -H "Authorization: token $TRAVIS_API_TOKEN" \
  https://api.travis-ci.org/repo/23485891/builds\?limit=4000 > ci-builds.json

$ cat ci-builds.json | jq '.builds[] | select (.event_type == "push" and .branch.name == "master") |"\(.started_at) \(."@href"), \(.state)" '

"2019-09-06T13:12:47Z /build/581670695, passed"
"2019-09-06T11:58:17Z /build/581641815, passed"
"2019-09-05T18:04:47Z /build/581334599, passed"
"2019-09-04T20:38:18Z /build/580910299, passed"
"2019-09-04T11:23:10Z /build/580670960, passed"
"2019-09-04T09:23:56Z /build/580631513, passed"
"2019-09-04T02:20:57Z /build/580515202, passed"
"2019-09-03T13:51:48Z /build/580248125, passed"
"2019-09-03T06:38:27Z /build/580092151, failed"
"2019-09-03T01:36:09Z /build/580033707, passed"
"2019-09-02T23:40:33Z /build/580012225, passed"
"2019-08-30T10:42:10Z /build/578757014, passed"
"2019-08-30T05:45:57Z /build/578663829, passed"
"2019-08-29T07:38:34Z /build/578224293, passed"
"2019-08-29T06:47:38Z /build/578180771, canceled"
```

The failing build is https://travis-ci.org/input-output-hk/cardano-wallet/builds/580092151 (note that the relative url doesn't include the `s` in builds)

So for this small sample we get a failure rate of `1/14 ≈ 7%`, excluding the canceled build.

**Comment by KtorZ** [comment]
I believe we can now close that one with fixes done to the integration done and the switch to Buildkite, the problem seems to have finally vanished.
