### ISSUE TITLE
Explore the possibility of running the cardano-http-bridge against a local cluster

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#67]
# Context

In order to test our wallet backend in a "real-life" scenario, we would need to be able to run a few integration tests where a the wallet server connects to a given chain producer backend in order to retrieve blocks. 

For now, our only chain producer is the `cardano-http-bridge` and, it only connects to `mainnet` or `testnet` which is fine for testing a few things, but pretty limited when it comes to submitting transaction and moving test funds from some faucet wallet. 

Having the ability to run a demo test cluster in CI and perform a serie of tests against it can be pretty useful. 

# Decision

First, we want to explore the capabilities of the cardano http bridge and figure out whether we can connect it to a local cluster. If this can be done with reasonable efforts, then we do it.

# Acceptance Criteria

1. We `must` assess how complex it would be to instrument the cardano-http-bridge to run against a local cluster of node
2. If simple-enough, we `may` provide instructions and scripts to setup a local cluster to which the `cardano-http-bridge` could connect.

---

# Development Plan

- [x] Look whether it is possible to specify a custom configuration to the http bridge.
    > Turns out it is with some minor changes, cf: https://github.com/input-output-hk/cardano-http-bridge/pull/19

- [x] Experiment connecting to the bridge to a local cluster
    > I have tried a few things with the bridge and the local cluster and I am running into some issues. So far, here are my findings: 
    >
    > - The bridge do use genesis data coming from the 'previous hash' as specified in the configuration. In order to do that, it seems that the bridge looks up some hard-coded initial data in [exe-common/genesis](https://github.com/input-output-hk/rust-cardano/tree/ce954637284bf2f79fe7cf6fa3386b29b5dcd4d4/exe-common/genesis). So far, only the data for the testnet, mainnet and staging are available.
    > - Therefore, I've tried to spin up a local cluster using the same seed and genesis data. Yet, it seems that the protocol my local cluster uses is slightly different from what the bridge expects (the bridge expects the node to advertise its node id where the node seems to be sending raw data). I have quite figured out the problem here...

- [x] Have a setup where it is possible to easily spawn a cluster and an http bridge connected to it.

# PR

| Number   | Base      |
| ---      | ---       |
| #132       | `master`  |
| #134       | `master` |
| #135       | `master` |

# QA 

- Integration tests can now able to start an integration cluster of cardano-node (using the latest release from `cardano-sl`) on top of which, we use the launcher code to start the wallet backend and the bridge

- I've updated the README with [test instructions and pre-requisites](https://github.com/input-output-hk/cardano-wallet#integration) for running the integration tests. Indeed, the `cardano-node-simple` and the `cardano-http-bridge` needs to be available on the global path. 

- I've updated the dot travis file to make sure they're both available in CI: 
   - https://travis-ci.org/input-output-hk/cardano-wallet/jobs/513019924#L259
   - https://travis-ci.org/input-output-hk/cardano-wallet/jobs/513019924#L266

- We do nothing with cluster at the moment, but I've added the plumbing code in the integration test to make sure the cluster is started (and killed) around the integration tests scenarios (cf: https://github.com/input-output-hk/cardano-wallet/blob/master/test/integration/Main.hs#L46-L73)

**Comment by piotr-iohk** [comment]
lgtm :+1:
