### ISSUE TITLE
Connect the wallet primitive to the chain producer through the wallet layer

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#69]
# Context

We have:

- A set of core primitives and types to represent and keep track of a wallet
- A network layer that retrieves blocks from a chain producer (i.e. the cardano-http-bridge)
- A db layer that define an interface for persisting pieces of information to some db engine / storage
- A wallet layer that connects the dots and make use of the above to provide a simple interface for wallet clients (like the API layer or the CLI)

# Decision

We do need to implement the wallet layer to make sure that we process blocks from the chain producer and apply them as we received them. Also, this should ideally make use of the DB layer to keep track of the checkpoints and, restart from a given position when needed.

# Acceptance Criteria

- [x] The wallet layer `must` process blocks from the `NetworkLayer` using the wallet primitives
- [x] The wallet layer `should` flush its latest state to the database after processing blocks
- [x] The wallet layer `may` quickly catch up with the network tip when started
 
---

# Development Plan

- [x] Draft a first pipeline that tight together the various layers in order to restore a wallet from a given mnemonic.
- [x] Look at the heap and time profiling for restoring a wallet against mainnet
- [x] Write test code for the DBLayer
- [x] Write test code for the WalletLayer

# PR

| Number   | Base      |
| ---      | ---       |
| #73       | `master`  |
| #82       | `master` | 
| #88       | `master` |

# QA 

- We've finalized the first draft implementation of the wallet layer as described by [WalletLayer](https://github.com/input-output-hk/cardano-wallet/blob/master/src/Cardano/WalletLayer.hs#L65-L69). To implement this layer, we had to pull strings from the DBLayer and NetworkLayer, ultimately tightening them together alongside the wallet primitive logic to accomplish basic wallet work. 

- Usage of the `watchWallet` have been manually tested and profiled and the result can be seen in comment of #73 (note that, I have later removed the corresponding code from the CLI executable as it seemed to confuse people).

- @paweljakubas also added extra unit tests to test basic properties on our fake DB engine for now, that are visible in [Cardano/DBLayer/MVarSpec.hs](https://github.com/input-output-hk/cardano-wallet/blob/b6cb0ba5a4e913491005a9e9256bc76f3ecf2c6b/test/unit/Cardano/DBLayer/MVarSpec.hs)

- We do also have similar tests working directly at the WalletLayer level and checking additional invariant (like, conflict between ids), cf: [Cardano/WalletLayerSpec.hs](https://github.com/input-output-hk/cardano-wallet/blob/b6cb0ba5a4e913491005a9e9256bc76f3ecf2c6b/test/unit/Cardano/WalletLayerSpec.hs)

**Comment by piotr-iohk** [comment]
@KtorZ, code coverage on `WalletLayer.hs` is rather low now ~53%. Mostly due to not exercised `watchWallet` (and called within it `applyBlocks` and `printInfo`). 

Perhaps it would be possible to add some integration tests for `watchWallet` similar to [HttpBridgeSpec](https://github.com/input-output-hk/cardano-wallet/blob/master/test/integration/Cardano/NetworkLayer/HttpBridgeSpec.hs)?

**Comment by KtorZ** [comment]
@piotr-iohk 
Yup, I am actually about to cover those as part of the debt ticket we have (those are mentioned points). The watch wallet is a bit tricky to cover since it runs forever; I believe we can just run it for a while in a thread and then, nuke the thread at some point :thinking: 
Will do as part of #94

**Comment by piotr-iohk** [comment]
oh yes, I actually glimpsed at #94 but somehow missed the second table (`Unused code`), where it actually is stated. :)

lgtm :+1:
