### ISSUE TITLE
Test compatibility with Jörmungandr Praos/Genesis self-node in CI

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#698]
# Context

Currently we run integration tests against a Jörmungandr BFT self-node. We have to support Genesis/Praos.

Note that we don't currently support [rollbacks](https://github.com/input-output-hk/cardano-wallet/milestone/25), but it should be possible to configure jörmungandr in a self-node setup using genesis/praos (such that there are no rollbacks.)

# Decision

We will check that the wallet works with a praos/genesis self-node. We will replace BFT-configurations in the CI with Genesis/Praos configs.

# Acceptance Criteria

- [ ] Integration tests pass _must_ using a Jörmungandr node with Praos/Genesis config
- [ ] All jörmungandr integration tests run in CI _should_ be run using a Praos/Genesis config

---

# Development Plan

- [x] Fix a trivial wrong hard-coded value and add a test for it
- [x] "Just" Replace config in CI? 

# PR

| Number   | Base      |
| ---      | ---       |
| #701       | `master`  |
| #720        | `master`  |

# QA 

- The bug in the binary decoder is covered by a golden test
- Existing tests run on Genesis/Praos in CI

**Comment by Anviking** [comment]
> What is a self node setup?
— @rvl 

The meaning I intended was just "be able to run a blockchain despite having just one node". And I think this is close to what it means.

From https://iohk.io/blog/join-the-roll-out-of-the-cardano-shelley-testnet/:

> The first stage is all about setting up and hosting a ‘self node’. You can think of a self node as ‘blockchain in a box’, a minimum viable product (MVP) for testing key capabilities. This is basically a set of tools and documentation to bootstrap your own genesis block and run a multi-node environment on your own machine, where you can see how stake pools actually operate. It’s like a complete network within a single instance.

**Comment by piotr-iohk** [comment]
lgtm
