### ISSUE TITLE
Define a small launcher CLI with a single 'start' command

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#7]
# Context

The wallet requires an underlying node. We should have a single command for starting both correctly. 

# Decision

- Support the following CLI parameters 
    - `--wallet-server-port` (the port we are serving the wallet API on)
    - `--node-port` (the port were communicating with the node on)
    - `--network` (mainnet or testnet)

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #27        | `master`  |

# QA 

Tested manually. See PR description of #27 for examples.

**Comment by Anviking** [comment]
When briefly interacting with the old CLI code, I had a few concerns which I thought I'd mention, in case it is avoidable.

Firstly, I found the amount of needed spread out components a bit annoying:

1. Name of CLI flag https://github.com/input-output-hk/cardano-wallet-legacy/blob/a40258f4b61c7a9dbcb03dac010e8fe201e99e28/src/Cardano/Wallet/Server/CLI.hs#L200
2. Help for the CLI flag https://github.com/input-output-hk/cardano-wallet-legacy/blob/a40258f4b61c7a9dbcb03dac010e8fe201e99e28/src/Cardano/Wallet/Server/CLI.hs#L201
3. name of the parser https://github.com/input-output-hk/cardano-wallet-legacy/blob/a40258f4b61c7a9dbcb03dac010e8fe201e99e28/src/Cardano/Wallet/Server/CLI.hs#L199
4. The field-name of the record https://github.com/input-output-hk/cardano-wallet-legacy/blob/a40258f4b61c7a9dbcb03dac010e8fe201e99e28/src/Cardano/Wallet/Server/CLI.hs#L34
5. Comment for the field name https://github.com/input-output-hk/cardano-wallet-legacy/blob/a40258f4b61c7a9dbcb03dac010e8fe201e99e28/src/Cardano/Wallet/Server/CLI.hs#L35

(1), (4), (somewhat (3)) are (basically) the same, as are (2) and (5). The duplication of the help and doc comments actually bothers me the most, as I fear this makes it more difficult to maintain.

Also, it seemed quite easy to mess up the order here https://github.com/input-output-hk/cardano-wallet-legacy/blob/a40258f4b61c7a9dbcb03dac010e8fe201e99e28/src/Cardano/Wallet/Server/CLI.hs#L91-L101

Or maybe this is unwarranted 🤷‍♂️

**Comment by KtorZ** [comment]
@Anviking , for the CLI, I am going to suggest something which will probably make most Haskeller screams but, I'd like us to consider `http://docopt.org/`. This is a DSL to represent CLI which has implementation in various languages, including Haskell (cf: https://github.com/input-output-hk/cardano-sl/blob/develop/cluster/app/demo/Main.hs#L29-L44) 

It gives us the ability to also have a specification for the CLI, and have a clear overview of what it is. Then, the Haskell code is merely about interpreting the CLI args and calling the right handlers. This is somewhat a bit less flexible, less powerful and less type-safe than the mighty `optparse-applicative` but has the main advantage at being simple and portable. 

This is just a suggestion. Generally speaking however, we could definitely write MUCH simpler code with `optparse-applicative` and make the CLI definition fairly transparent (which isn't the case with the legacy implementation).

**Comment by piotr-iohk** [comment]
lgtm :+1:
