### ISSUE TITLE
 Wallet Backend builds and tests on OSX

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#704]
# Context

`cardano-wallet` ultimately results in two binaries as detailed in the root [.cabal](https://github.com/input-output-hk/cardano-wallet/blob/master/cardano-wallet.cabal):

- cardano-wallet-http-bridge
- cardano-wallet-jormungandr

Both are command-lines and web server doing "wallet backend stuff", but working with different chain producers. 

# Decision

At the moment, our CI only produces binary artifacts for linux machines yet, most are using Windows and OSX machines so we ought to be able to produce executables for these targets too. Ideally, our test suites should also run on both platform to ensure that code produced works as expected on these platforms.

The focus is given on `cardano-wallet-jormungandr` for `cardano-wallet-http-bridge` will be removed soon enough and will not see the lights of production.

# Acceptance Criteria

- [x] `cardano-wallet-jormungandr` _must_ compile to OSX
- [x] `cardano-wallet-core:test:unit` _must_ pass on OSX
- [x] `cardano-wallet-cli:test:unit` _must_ pass on OSX
- [x] `bech32:test:unit` _must_ pass on OSX
- [x] `cardano-wallet-jormungandr:test:unit` _must_ pass on OSX
- [x] `cardano-wallet-jormungandr:test:integration` _must_ pass on OSX
- [ ] `cardano-wallet-core:benchmark:db` _should_ pass on OSX

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #766      | `master`  |
| #964 | `master` |

# QA 

1. MacOS builds for the master branch are shown in the [cardano-wallet jobset](https://hydra.iohk.io/jobset/Cardano/cardano-wallet#tabs-jobs).
2. Ensure that all `x86_64-darwin` jobs are green. In particular, tests for the packages listed in the AC.
3. Check that the [`required`](https://hydra.iohk.io/job/Cardano/cardano-wallet/required) job is green.
4. Check the _Constituents_ of the `required` job. These should include tests for packages listed in the AC.
5. Download the [tarball release](https://hydra.iohk.io/job/Cardano/cardano-wallet/cardano-wallet-jormungandr-macos64/latest) from Hydra and check that the binaries run on macOS.

**Comment by piotr-iohk** [comment]
@rvl Question about: `cardano-wallet-core:benchmark:db should pass on OSX`

Do we run benchmark on OSX?

**Comment by rvl** [comment]
@piotr-iohk The benchmark builds ok, but it is not run in the nightly CI job as it is done for Linux.

I consider this type of benchmark not worth running on two similar platforms because the results will be more or less the same.

However, we really really should bring back the nightly wallet restore acceptance test and benchmark. Because this type of benchmark should be run on multiple platforms.

**Comment by piotr-iohk** [comment]
:+1:
