### ISSUE TITLE
Count how many blocks each pool produced — I. Simple approach

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#711]
# Context

To calculate a pool's performance in the current epoch, we need to count how many blocks it actually produced.

We can count them using the proofs in Jörmungandr block-headers:

> In BFT the header also contains (768 bits = 96 bytes):
>   - BFT Public Key of the leader (32 bytes)
>   - BFT Signature (64 bytes)
>
> In Praos/Genesis the header also contains (616 bytes):
>   - VRF PubKey: 32 bytes (ristretto25519)
>   - VRF Proof: 96 bytes (ristretto25519 DLEQs)
>   - KES Signature: 484 bytes (sumed25519-12)
[chain-libs/format.md at master · input-output-hk/chain-libs · GitHub](https://github.com/input-output-hk/chain-libs/blob/master/chain-impl-mockchain/doc/format.md)

The public keys match the `PoolId`s returned from the Jörmungandrs stake-distribution (#713).

# Decision

1. Introduce a new state, and an update-function that can count the number of produced blocks in the current epoch for each pool.

Conceptually:
```haskell
data s =
 {  blockHeader :: BlockHeader,
 ,  blocksProducedThisEpoch :: Map PoolId Word
 }
applyBlock :: (proof, blockHeader) -> s -> s
```

- We can use the `blockHeader` to track where on the chain we are. Such that we can ask the networkLayer for the next blocks.
- We can use `blockHeader ^. #slotId` to know when we are in the next epoch.
- When we enter a new epoch, **we should clear the map** such that it only contains counts for the *current* epoch.

2. Connect the state to the network layer, similar to the restoration mechanism in `WalletLayer`, such that the state advances along the chain.

3. To not have to involve the DB-layer and save the Sqlite implementation for later, a temporary  `MVar` should be enough.

4. Don't involve the `WalletLayer`. Let's make this its own module. 

# Acceptance Criteria

- [ ] There _must_ be an easy way to retrieve an up-to-date `Map PoolId NumberOfProducedBlocksThisEpoch` from `Api.Server`.
- [ ] The count of "number of produced blocks this epoch" _must_ start from `0` every new epoch.
- [ ] The `DB`-layer _shouldn’t_ be involved in this issue.

# Development Plan

- [x] I will create a simple `State` and `applyBlock` in a new module `StatePool.Metrics` as a prototype
- [ ] I will refactor as required such that we can connect `StatePool.Metrics` with the `NetworkLayer` and `Api.Server`.
- [ ] Some property-test scenarios for the `applyBlock` function probably

# PR

| Number   | Base      |
| ---      | ---       |
| #?       | `master`  |

# QA

**Comment by KtorZ** [comment]
Nice! 

1. What about instead of adapting the wallet layer functionality, what about having a dedicated worker which doesn't interfer with wallets and simply keep track of pools' states?  Conceptually, there's no need to create any wallet to keep track of stake pools

2. In: 

```hs
data s =
 {  blockHeader :: BlockHeader,
 ,  blocksProduced :: Map PoolId [SlotId]
 }
```

Does `blockHeader` refers to the last tip for which we fetched the pool states? Since this cannot change through an epoch, what about only keeping track of the epoch and, trying to find a name that reflects this :thinking: ?

**Comment by KtorZ** [comment]
From @rvl 

- Be more specific about which keys correspond to PoolId.
- Is only the current epock relevant, or all epochs?
- If rollback can be separated from this task, let's make it separate.
- What is the blockHeader field for?
- Keeping a list of SlotIds per pool in order to support rollback seems ok, if this state object is like a special wallet.

**Comment by Anviking** [comment]
> What about instead of adapting the wallet layer functionality, what about having a dedicated worker which doesn't interfer with wallets and simply keep track of pools' states? Conceptually, there's no need to create any wallet to keep track of stake pools

I wanted to at first! But I thought that it would possibly require some more, grander, architectural changes that would be difficult to realise.

So I thought it was easier to plan / start with adding things to the WalletLayer.

But since you suggest it… 🤔

**Comment by KtorZ** [comment]
In this case, it's actually easier and causes less changes to have that completely separated from the wallet layer! Plus, with regards to responsibilities, it feels wrong to overload the wallet restoration with this.

**Comment by KtorZ** [comment]
Closing this ticket. Remaining work and QA will be tracked in #713
