### ISSUE TITLE
Count how many blocks each pool produced — III. Sqlite

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#712]
# Context

We should now have some kind of state `s = (BlockHeader, Map PoolId [SlotId])` and a pure function `applyBlock :: (proof, blockHeader) -> s -> s`.

We need to persist that state.

_with f = applyBlocks, here is our situation:_
```
s ------ f  --- >  s’
|        |         |
|        |         |
V        V         V
DB s —-> f’ —> DB s’ 
```

# Decision

- Add a Sqlite table `pool_performance` with `epoch`, `pool_id`, `produced_block_in_slot`. Note that the `SlotId` is here stored in two separate columns. This way previous epochs can be cleaned easily.
- Make it possible to get a `Map PoolId NumberOfProducedBlocks` (or something equivalent) through the DBLayer
- Insert a new row for each block applied
- The pure functionality implemented in #711 can be moved to the `DB.Model` module which is used as reference for state machine tests.

# Acceptance Criteria

- [ ] It _must_ be possible to know _how many_ blocks each stake pool in the current epoch has produced
- [ ] This information _must_ be persisted
- [ ] We _must_ handle rollbacks
- [ ] ~Any new sqlite table _should not_ grow endlessly. When entering into a new epoch, the old epoch  _should_ be dropped.~

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #798        | `master`  |
| #815         | `master`  |

# QA

**Comment by KtorZ** [comment]
> **Add a Sqlite table `pool_performance` [...] `produced_block_in_slot`**

Perhaps `pool_metrics` here to not be too specific about this table. As features and accessors are added into Jörmungandr, we might collect more metrics upon which we'll build a performance indicator. For now, that indicator only involves the number of blocks produced. Also, `produced_block_in_slot` is really a `slot_id` right :grimacing: ?

> **Insert a new row for each block applied**

And also, clean up as we move to the next epoch.... or not? That could be a valuable piece of information to add to the API (blocks produced in the previous epoch, if any). 

>  **We must handle rollbacks**

This would translate as "delete rows above point of rollback" I believe :thinking:

**Comment by KtorZ** [comment]
From @rvl 

- maybe call the table pool_production with columns (epoch integer, local_slot integer, pool_id char(32))
- add an index on the epoch and pool_id columns
- be explicit about the dblayer function signature(s).

```hs
  putPoolProduction :: SlotId -> PoolId -> m ()
  readPoolProduction :: m (Map PoolId [SlotId])
```
  
- if the old epoch data should be dropped, is the current epoch implicitly determined from the SlotId passed to putPoolProduction?
- For readPoolProduction, does it need to return a list of slots, or just a block count per pool?

**Comment by Anviking** [comment]
> Any new sqlite table should not grow endlessly. When entering into a new epoch, the old epoch should be dropped.

I removed this AC, because it adds complexity and we might not want to do it if we get access to the stake-distributions of all epochs.

> Also, produced_block_in_slot is really a slot_id right

I wrote: "Note that the SlotId is here stored in two separate columns. This way previous epochs can be cleaned easily." So the `slotNumber` component of it, yes.

> For readPoolProduction, does it need to return a list of slots, or just a block count per pool?

Just a block count per pool _should_ be enough, I believe.

**Comment by KtorZ** [comment]
Closing this ticket. Remaining work and QA will be tracked in #713
