### ISSUE TITLE
Cache stake-distribution from Jörmungandr's GET /stake ?

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#716]
# Context

The simplistic implementation of #714 will lead to calling the jörmungandr `GET /stake` once per `listStakePools`-request. This is wasteful as the results are fixed for the entire epoch.

Things are made slightly more complicated by the fact that rollbacks/fork-switches across epoch boundaries could alter the result.

# Decision

We could make efforts to cache the results.

# Acceptance Criteria

- [ ] We _may_ cache/memoize the stake-distribution from jörmungandr
- [ ] If we opt to: the caching _must_ be resilient to changing epochs
- [ ] If we opt to: the caching _must_ be resilient to rollbacks.

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #?       | `master`  |

# QA

**Comment by KtorZ** [comment]
This falls into the category of "optimizations", to be (maybe) done in another story IMO. First: let's make it work. Beside, I don't think it's worth the added complexity here. We are talking about optimizing one HTTP call away, which will happen quite rarely in the first place.

**Comment by KtorZ** [comment]
From @rvl 

- If this task is an optimisation, then it needs some kind of benchmark in the AC. Otherwise, how do we know that it worked?

**Comment by Anviking** [comment]
I also saw this as a place where we could potentially deal with the race-conditions. But since we shouldn't be concerned ( https://github.com/input-output-hk/cardano-wallet/issues/714#issuecomment-532096810)

… sure. This is maybe not worth it.
