### ISSUE TITLE
Count how many blocks each pool produced — II. Rollback support

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#722]
# Context

See #711.

#711 uses a simple approach for counting blocks that is 1) in-memory (not persisted) and 2) doesn't support rollbacks.

# Decision

Adapt the simplistic model to support rollbacks. Do this by storing at *when* (at what slotId?) each stake pool produced blocks instead of just counting *how many*.

E.g instead of `Map PoolId Word`, we would use `Map PoolId [SlotId]` internally.

This way we can:
- Still count how many blocks a pool produced (by taking the length of the list)
- Roll-back to slot `sl` (by removing slots newer than `sl` in the list)

# Acceptance Criteria

- [ ] It _must_ be possible to get an up-to-date `Map PoolId Word` (or equivalent)
- [ ] This _must_ still work when the chain rolls back

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #?       | `master`  |

# QA

**Comment by KtorZ** [comment]
Closing this ticket. Remaining work and QA will be tracked in #713
