### ISSUE TITLE
Add CLI command for listing stake pools

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#725]
# Context

We have the API endpoint. Now let's extend the CLI.

# Decision

Allow users of the CLI to list stake pools.

# Acceptance Criteria

- [ ] Users *must* be able to list stake pools via the CLI 

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #782        | `master`  |

# QA

**Comment by KtorZ** [comment]
Closing this ticket. Remaining work and QA will be tracked in #713
