### ISSUE TITLE
Flaky integration wallet test 

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#726]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| `master`    | Windows & OSX & Linux) | Human |

# Context
 
 

We had an unexpected failure in CI:

https://buildkite.com/input-output-hk/cardano-wallet/builds/1974#d43b7a97-9855-45fd-b3dd-e21ddcb30254/97-1126

The failing scenario is the following:

```hs
        it "A newly created wallet can sync with the chain" $ \(_, wallet) -> do
            bytes <- entropyToBytes <$> genEntropy @(EntropySize 15)
            let xprv = generateKeyFromSeed (Passphrase bytes, mempty) mempty
            wid <- unsafeRunExceptT $ W.createWallet wallet
                (WalletId $ digest $ publicKey xprv)
                (WalletName "My Wallet")
                (mkSeqState @(HttpBridge 'Testnet) (xprv, mempty) minBound)
            unsafeRunExceptT $ W.restoreWallet wallet wid
            threadDelay 2000000
            tip <- slotId . currentTip . fst <$>
                unsafeRunExceptT (W.readWallet wallet wid)
            unless (tip > slotMinBound) $
                expectationFailure ("The wallet tip is still " ++ show tip)
```

# Steps to Reproduce

1. Re-run integration tests often....

## Expected behavior

They always pass

## Actual behavior
 
<A clear and concise description of what you observe instead. If applicable add screenshots to help explain your problem.>

Sometimes, this test fails

---

# Resolution Plan

It seems like we are waiting 2s for a wallet to restore, and then, make some assumption about its tip. This really depends on the machine and network connectivity here and relying on a fixed delay isn't very ... reliable.
Instead: we could poll the network tip and wait until it changes, with a much bigger timeout like 60s. This should solve the "flakyness" of the test.

# PR

| Number   | Base      |
| ---      | ---       |
| #733       | `master` |

# QA 

- I have replaced a hard-coded delay with a retry/timeout approach
- I have removed a hard-coded port and replaced it with a dynamic assignation
- I have used waitForConnection instead of hard-coded delays
- CI passed twice without failures already, but that's a pretty poor argument I know.

**Comment by piotr-iohk** [comment]
lgtm :+1:
