### ISSUE TITLE
CI: Code coverage is uploaded for `bors try`

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#754]
# Context

Buildkite CI. 

# Steps to Reproduce

Run `bors try` on a PR.

## Actual behavior
 
It uploads test coverage to coveralls.

## Expected behavior

It should only upload test coverage for successful `bors r+` builds.

---

# Resolution Plan

* Note: The `bors r+` branch is `bors/staging` and the `bors try` branch is `bors/trying`.

# PR

| Number   | Base      |
| ---      | ---       |
| #?       | `develop` |

# QA

**Comment by KtorZ** [comment]
@piotr-iohk closing in favor of https://jira.iohk.io/projects/WB/issues/WB-30
