### ISSUE TITLE
Wallet restoration issues while the node is syncing

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#760]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Linux | Code  v Configuration v Environment v Human v Unknown |

# Context
  I've observed those 2 cases with restoration performed while the node is syncing:

*1. Wallet prematurely restored.*

Say I create this wallet and it gets _restored_ when the node is on epoch 2:

```
[iohk.cardano-wallet.serve.worker.6e9e51d7:Info:ThreadId 71] [2019-09-25 12:07:48.74 UTC] Piotr Wallet3 (restored), created at 2019-09-25 12:04:49.954745975 UTC, not delegating
[iohk.cardano-wallet.serve.worker.6e9e51d7:Info:ThreadId 71] [2019-09-25 12:07:48.74 UTC] number of pending transactions: 0
[iohk.cardano-wallet.serve.worker.6e9e51d7:Info:ThreadId 71] [2019-09-25 12:07:48.74 UTC] number of new transactions: 0
[iohk.cardano-wallet.serve.worker.6e9e51d7:Info:ThreadId 71] [2019-09-25 12:07:48.74 UTC] new block height: 42169
[iohk.cardano-wallet.serve.worker.6e9e51d7:Info:ThreadId 71] [2019-09-25 12:07:48.86 UTC] Applying blocks [2.0 ... 2.21599]
```

The node is then syncing up to the current epoch = 12, but the restoration worker doesn't seem to catch up and even when the chain is fully synced I still see the wallet with `status=ready` and `balance=0` and I know I have funds on it on subsequent epochs. Only after I restart the node, the wallet catches up.

*2. Wallet restoring with 0% progress infinitely*

Pretty much same as before, i.e. creating a wallet on the node that is still syncing and sometimes such wallet ist just infinitely `restoring`. (Until node restarted)
That seems to be always the case some subsequent wallet, like say 3rd wallet created on the node (while it's syncing), whereas first two wallets are case 1

# Steps to Reproduce

1. Start on fresh state-dir `cardano-wallet-http-bridge launch --state-dir ./your-state-dir`
2. While it `http-bridge` is syncing with testnet restore a wallet:
```
curl  -vX POST http://localhost:8090/v2/wallets \
  -H "Content-Type: application/json; charset=utf-8" \
  -d '{
"name": "Piotr Wallet",
"mnemonic_sentence": ["identify", "screen", "lock", "bargain", "inch", "drop", "canyon", "flock", "dry", "zone", "wash", "argue", "system", "glory", "light"],
"passphrase": "Secure Passphrase",
"address_pool_gap": 20
}' --http1.1  |  jq
```
3. Notice the wallet restores until it's fully `status=ready`.
4. Wait for the `http-bridge` to fully sync with testnet

## Expected behavior

The wallet restores fully and there are funds on wallet.

## Actual behavior
 
The wallet is reported as restored (`status = ready`) but the balance is 0.
Only after you restart the node, the wallet really restores and reports appropriate balance.

---

# Resolution Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #?       | `develop` |

# QA

**Comment by KtorZ** [comment]
@piotr-iohk What's the status of that one :thinking: ?

**Comment by piotr-iohk** [comment]
@KtorZ, this one seems to have disappeared after changes related to fixing #756 and #769. Closing for now.
