### ISSUE TITLE
wallet.db size significantly big

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#769]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Windows & OSX & Linux) | Code  v Configuration v Environment v Human v Unknown |

# Context
`wallet.db` size for the server with transaction between wallets is much bigger comparing to the size of wallet.db with the same wallets that were restored on the fresh node.

I had a script running transactions between 3 wallets back and forth for few hours. in total all 3 wallets had ~6k transactions spanning through 1 epoch (between slots 6k - 20k).
`wallet.db` for that backend server is 2.2GB.

The same wallets restored on fresh node and wallet server make `wallet.db` weight only 213MB.

Both wallets dbs can be accessed [here](https://drive.google.com/drive/folders/1pOVEZ5ePLiVaJEObZ1QvWhXzJoAafbXb).

# Steps to Reproduce

1. Start jormungandr testnet and a wallet server with `--database wallet1.db`

[node_config.yaml.txt](https://github.com/input-output-hk/cardano-wallet/files/3671092/node_config.yaml.txt)

```
jormungandr --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770 --config node_config.yaml

cardano-wallet-jormungandr serve --genesis-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770 --database wallet1.db
```

2. Create two wallets and run a [script](https://github.com/piotr-iohk/big-wallet-creator/blob/master/script.rb) `./script test <wid1> <wid2>` for a few hours. (runs transactions between two wallets)
3. Monitor `wallet1.db` size
4. Restore the same wallets using different wallet server and wallet.db file (`--database wallet2.db`).
## Expected behavior

`wallet1.db` and `wallet2.db` sizes shouldn't be significantly different. (The same?)
## Actual behavior
 
`wallet1.db` ~ 2.2GB
`wallet2.db` ~ 200MB

---

# Resolution Plan

- Review `purgeCheckpoints` in SQLite, something is probably off there
- Analyze the 2GB database looking for something bizarre, likely, one table is not getting cleaned up correctly.

# PR

| Number   | Base      |
| ---      | ---       |
| #791       | `master` |
| #786       | `master` |
| #801       | `master` |

# QA 

- Wallet layer now makes sparse checkpoints instead of contiguous ones
- Address discovery state now cleaned up as part of the checkpoint pruning
- Added property to verify that pruning is happening as expected 
- See full analysis on #791 and #786
- In #801, we've also added some measurement in the benchmark tests to get good estimate of the database size with various size of data:

```
File size /1000 CP x 1000 UTxO   
  bench13668-10.db                          166 MB
  bench13668-10.db-shm                       32 KB
  bench13668-10.db-wal                        4 MB
  bench13668-10.db (closed)                 166 MB

File size /10000 w/ 10i + 20o    
  bench24335-2.db                            57 MB
  bench24335-2.db-shm                       128 KB
  bench24335-2.db-wal                        57 MB
  bench24335-2.db (closed)                   57 MB
                                 
File size /100000 w/ 10i + 20o   
  bench24335-3.db                           580 MB
  bench24335-3.db-shm                         1 MB
  bench24335-3.db-wal                       584 MB
  bench24335-3.db (closed)                  580 MB

File size /10000 w/ 50i + 100o   
  bench24335-6.db                           297 MB
  bench24335-6.db-shm                       608 KB
  bench24335-6.db-wal                       299 MB
  bench24335-6.db (closed)                  297 MB
```

**Comment by KtorZ** [comment]
One idea: could be that the checkpoint pruning is not working well. 

@piotr-iohk There was no data discrepancy between the wallets? Mostly: were all the transactions there in the small one? What about addresses?

**Comment by piotr-iohk** [comment]
@KtorZ, yes there was a discrpancy. Small one did not have the pending transactions. But the pending transactions was only 90 out of ~6k.

Tx in the big one:

```
Wallet1

 Transactions: 1774
  Status:
   Pending: 80
   InLedger: 1694
  Direction:
   Incoming: 1200
   Outgoing: 574

Wallet2

 Transactions: 2452
  Status:
   Pending: 3
   InLedger: 2449
  Direction:
   Incoming: 946
   Outgoing: 1506

Wallet3

 Transactions: 1729
  Status:
   Pending: 7
   InLedger: 1722
  Direction:
   Incoming: 787
   Outgoing: 942
```

**Comment by KtorZ** [comment]
Yeah, this is normal, pending transactions are a local construct and don't live on chain. Okay, so it's probably the UTxO that doesn't get cleared up as iy should... Txs are not duplicated and shared across checkpoints.

**Comment by piotr-iohk** [comment]
That looks good! I've been making some tests also over `http-bridge`  doing restoring / transactions (not quite possible on Jormungandr now due to https://github.com/input-output-hk/jormungandr/issues/860).
 
 - DB size looks reasonable (80MB for ~6k tx across few wallets). 
 - no timeout on endpoints during restoration
