### ISSUE TITLE
Add API endpoint to list all legacy wallets.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#775]
# Context

This task will provide an API endpoint that allows users to list all known Byron wallets.

# Decision

The API will provide an endpoint similar to the following:
```yaml
/byron/wallets:
  get:
    operationId: listByronWallets
    tags: ["Wallets"]   
    summary: List
    description: |
      Return a list of known Byron wallets, ordered from oldest to newest.
    responses: *responsesListByronWallets
```
With schema definitions similar to the following:
```yaml
x-responsesListByronWallets: &responsesListByronWallets 
  <<: *responsesErr405
  <<: *responsesErr406
  200:
    description: Ok   
    schema:   
      type: array 
      items: *ApiByronWallet
```
See [`ApiByronWallet`](https://github.com/input-output-hk/cardano-wallet/issues/781) definition.

# Acceptance Criteria

Within the list of criteria below, a _**ticked**_ criterion indicates that there is _**test coverage**_ in the `master` branch to demonstrate that this criterion is _**satisfied**_.

- [x] The API _must_ support the ability to list all known Byron wallets (the `listByronWallets` operation).
- [x] The `listByronWallets` operation _should_ list wallets in order, from _oldest_ to _newest_.
- [x] The `listByronWallets` operation _must not_ include new-style (Shelley) wallets in the list returned.
- [x] After a successful restore with [`restoreByronWallet`](https://github.com/input-output-hk/cardano-wallet/issues/774), calling `listByronWallets` _must_ include the restored wallet in the list returned.
- [x] After a successful deletion with [`deleteByronWallet`](https://github.com/input-output-hk/cardano-wallet/issues/777), calling `listByronWallets` _must not_ include the restored wallet in the list returned.

# Development Plan
- [x] Implement dummy endpoint that always returns the _empty list_.
    This will unblock tasks that depend on the presence of this endpoint and types relating to it.
- [x] Replace dummy implementation with real implementation.

# PR

| Number   | Base      |
| ---      | ---       |
| #790 | master |
| #817 | master |
| #846 | master |

# QA 

- [x] Build integration tests to check that all acceptance criteria are satisfied.

**Comment by piotr-iohk** [comment]
lgtm!
