### ISSUE TITLE
Add API endpoint to fetch information about a legacy wallet.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#776]
# Context

This task will provide an API endpoint that allows users to fetch information about a Byron wallet.

In order to use this endpoint for a given wallet, the wallet must have been previously restored with the [`postByronWallet`](https://github.com/input-output-hk/cardano-wallet/issues/774) endpoint.

# Decision

The API will provide an endpoint similar to the following:
```yaml
/byron/wallets/{byronWalletId}:
  get:  
    operationId: getByronWallet  
    tags: ["Wallets"]
    summary: Get
    description: Return information about a Byron wallet. 
    parameters:
      - *parametersByronWalletId 
    responses: *responsesGetByronWallet
```
With schema definitions similar to the following:
```yaml
x-responsesGetByronWallet: &responsesGetByronWallet 
  <<: *responsesErr404
  <<: *responsesErr405
  <<: *responsesErr406
  200:
    description: Ok   
    schema: *ApiByronWallet  
```

See [`ApiByronWallet`](https://github.com/input-output-hk/cardano-wallet/issues/781) definition.

# Acceptance Criteria

Within the list of criteria below, a _**ticked**_ criterion indicates that there is _**test coverage**_ in the `master` branch to demonstrate that this criterion is _**satisfied**_.

- [x] The API _must_ provide an endpoint to fetch information about a legacy wallet.
- [x] After a successful restore with [`restoreByronWallet`](https://github.com/input-output-hk/cardano-wallet/issues/774), calling `getByronWallet` _must_ return a valid `ApiByronWallet` object with information about the restored wallet.
- [x] After a successful deletion with [`deleteByronWallet`](https://github.com/input-output-hk/cardano-wallet/issues/777), calling `getByronWallet` _must_ return an error.

# Development Plan

- [x] Implement **dummy endpoint** that always fails with a suitable **wallet not found error**.
    This will unblock tasks that depend on the presence of this endpoint and types relating to it.
- [x] Replace dummy implementation with real implementation.

# PR

| Number   | Base      |
| ---      | ---       |
| #790 | master |
| #817 | master |
| #846 | master |

# QA 

- [x] Build integration tests to verify that all acceptance criteria have been satisfied.

**Comment by piotr-iohk** [comment]
lgtm!
