### ISSUE TITLE
Add API endpoint to delete a legacy wallet.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#777]
# Context

This task will provide an API endpoint that allows users to delete a Byron wallet.

# Decision

The API will provide an endpoint similar to the following:
```yaml
/byron/wallets/{byronWalletId}:  
  delete:
    operationId: deleteByronWallet   
    tags: ["Wallets"]
    summary: Delete 
    description: Delete a Byron wallet.
    parameters: 
      - *parametersByronWalletId 
    responses: *responsesDeleteByronWallet   
```

# Acceptance Criteria

Within the list of criteria below, a _**ticked**_ criterion indicates that there is _**test coverage**_ in the `master` branch to demonstrate that this criterion is _**satisfied**_.

- [x] The API _must_ support the ability to delete a Byron wallet (the `deleteByronWallet` operation).
- [x] Calling `deleteByronWallet` with a new-style (Shelley) wallet ID _must_ result in an error.
- [x] After a successful deletion, any data relating to the wallet _must_ no longer be present in the database.
- [x] After a successful deletion, calling [`getByronWallet`](https://github.com/input-output-hk/cardano-wallet/issues/776) with a deleted wallet ID _must_ return an error.
- [x] After a successful deletion, the [`listByronWallets`](https://github.com/input-output-hk/cardano-wallet/issues/775) operation _must_ not include the deleted wallet in the list it returns.

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #790 | master |
| #817 | master |
| #846 | master |

# QA 

- [x] Build integration tests to verify that all acceptance criteria have been satisfied.

**Comment by piotr-iohk** [comment]
lgtm!
