### ISSUE TITLE
Add API endpoint to calculate the cost of migrating from a legacy wallet.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#778]
# Context

This task will provide an API endpoint that allows users to calculate the **exact** cost of migrating from a Byron wallet to a new wallet.

# Decision

The API will provide an endpoint similar to the following:
```yaml
/byron/wallets/{byronWalletId}/migrate:
  get:
    operationId: getByronWalletMigrationInfo
    tags: ["Wallets"]
    summary: Migrate
    description: |
      Calculate the exact cost of migrating from a Byron wallet to a new wallet.
    parameters: 
      - *parametersByronWalletId
    responses: *responsesGetByronWalletMigrationInfo
```

# Acceptance Criteria

Within the list of criteria below, a _**ticked**_ criterion indicates that there is _**test coverage**_ in the `master` branch to demonstrate that this criterion is _**satisfied**_.

- [x] The API _must_ provide an operation to calculate the **exact** cost of migrating from a Byron wallet to a new wallet.
- [x] The actual cost incurred by the migration (with the [`migrateByronWallet`](https://github.com/input-output-hk/cardano-wallet/issues/779) endpoint) must **exactly** match the cost returned by the `getByronWalletMigrateInfo` endpoint. Therefore, the balance of the new wallet must be equal to `b - c`, where `b` was the original balance of the legacy wallet, and `c` is the cost returned by `getByronWalletMigrateInfo`.

# Development Plan

1. Implement **dummy endpoint** that always returns **zero**.
    This will unblock tasks that depend on the presence of this endpoint and types relating to it.
2. Replace dummy implementation with real implementation.

# PR

| Number | Base |
| -- | -- |
| #795 | master |
| #806 | master |
| #811 | master |
| #841 | master |
| #871 | master |
| #882 | master |
| #915 | master |
| #950 | master |

# QA

**Comment by piotr-iohk** [comment]
Closing this one. Added comment here -> https://github.com/input-output-hk/cardano-wallet/issues/779#issuecomment-550268161
