### ISSUE TITLE
Create `ApiByronWallet` type.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#781]
# Context

The `ApiByronWallet` type will be used to represent a Byron-style wallet in the wallet API.

Values of this type will be returned by the following API functions:

* [`getByronWallet`](https://github.com/input-output-hk/cardano-wallet/issues/776)
* [`listByronWallets`](https://github.com/input-output-hk/cardano-wallet/issues/775)
* [`postByronWallet`](https://github.com/input-output-hk/cardano-wallet/issues/774)

# Decision

The definition of `ApiByronWallet` should be identical to the existing [`ApiWallet`](https://github.com/input-output-hk/cardano-wallet/blob/918ebab28d27ed89c6cd0f0b84a53794180ea121/lib/core/src/Cardano/Wallet/Api/Types.hs#L169) type, but without the following fields:

1. `addressPoolGap`
1. `delegation`

# Acceptance Criteria

1. The `ApiByronWallet` type must exist, and it must be possible to perform round-trip JSON serialization and deserialization for values of this type.
2. The Swagger specification should provide a corresponding `ApiByronWallet` schema definition.

# Development Plan

- [x] Add type.
- [x] Add JSON round trip tests.
- [x] Add appropriate schema definition to Swagger API definition.

# PR

| Number   | Base      |
| ---      | ---       |
| #784        | `master`  |

# QA

**Comment by piotr-iohk** [comment]
lgtm! there are json roundtrip tests for the type.
