### ISSUE TITLE
The wallet won't confirm a few transactions

### ISSUE THREAD

**Issue by JayMaree** [cardano-foundation/cardano-wallet#79]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| 2.0.1    | Ubuntu Bionic) | Code  v Configuration v Environment v Human v Unknown |

# Context
We run both `cardano-wallet` and `cardano-explorer` on one Ubuntu server. We execute API calls against the wallet to generate new transactions. A few transactions (on daily basis) won't end up in the Blockchain.
Transaction has been generated but stays at:
```
"confirmations": 0,
```

We do pay enough fee and we do have enough funds. I used cli-command `curl -X GET http://localhost:8090/api/v1/transactions?id={{txid}} | jq .
` to get the json response which contains the 0 confirmations line.
 

# Steps to Reproduce

1. Executed a new order with the same amount and it'll pass

## Expected behavior

The transaction will end up in the Cardano Blockchain
## Actual behavior
The confirmations stays at zero.
<A clear and concise description of what you observe instead. If applicable add screenshots to help explain your problem.>

---

# Resolution Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #?       | `develop` |

# QA

**Comment by KtorZ** [comment]
@JayMaree, thanks for reporting this though this isn't the best place at the moment.
This repository contains a fresh implementation that shares nothing with the current Byron wallet on cardano-sl. 
I'll therefore suggest you to open this issue on https://github.com/input-output-hk/cardano-sl directly as this is where the corresponding code currently lives.

Regarding the issue itself, I am sure to understand how to reproduce this? You mentioned _"A few transactions  won't end up in the Blockchain."_; does it means that there are some transactions that make it? Are you creating transactions using the wallet backend API or from any other means?

**Comment by JayMaree** [comment]
Hi @KtorZ . Thanks! I will create a ticket in the cardano-sl repo.

Some transactions do make it and end in the blockchain. Yes, we use the API.
