### ISSUE TITLE
Spawn http bridge and a wallet server from specified options

### ISSUE THREAD

**Issue by paweljakubas** [cardano-foundation/cardano-wallet#8]
# Context

We need the launcher that enables us to start the cluster comprised of the wallet and cardano-htttp-bridge that is intermediary between the wallet and mainnet/testnet.

# Decision

We will enable launcher starting the cluster that consists of wallet and http bridge instance. As the http bridge is the gateway for block acquisition we will spawn two instances together as parts of lauhing, but also kill the launcher if any part of the cluster is down.     

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #38       | `master`  |
| #75       | `master`  |
| #77       | `master`  |
| #78       | `master`  |
| #80       | `master` |
| #84       | `master`  |
| #87       | `master`  |

# QA 

- We now have two executables available
    - cardano-wallet-server: which only spawns a wallet server that connects to an http-bridge
    - cardano-wallet-launcher: which spawns a wallet launcher that spawns and supervise both the cardano-http-bridge and the cardano-wallet-server.

- Note that both executables expect the `cardano-http-bridge` to be "in scope", so it should have been installed (`cargo install --git https://github.com/input-output-hk/cardano-http-bridge.git`) and, the `$PATH` env var should at least point to `$HOME/.cargo/bin`. 

- There are also some unit tests to verify that the launcher works correctly, meaning, that it stops both processes if one of them exits. When stopped, the launcher also cleans up behind it and remove allocated resources (see: [Cardano.LauncherSpec](https://github.com/input-output-hk/cardano-wallet/blob/master/test/unit/Cardano/LauncherSpec.hs))

- We have also added an extra signal handler on UNIX system such that, the launcher will exit properly (and kill its child processes) when it receives a `SIGTERM`. The manual procedure for this is described in: [test/manual/Cardano/Launcher/POSIXSpec.md](https://github.com/input-output-hk/cardano-wallet/blob/d3cca01f66f0abe93012343dab093a2551b6cbea/test/manual/Cardano/Launcher/POSIXSpec.md)

**Comment by piotr-iohk** [comment]
lgtm :+1:
