### ISSUE TITLE
Error reported in the log after deleting a wallet

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#807]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Windows & OSX & Linux | Code  v Configuration v Environment v Human v Unknown |

# Context
 
There is an error reported in the log after deleting a wallet. It shouldn't be there.

```
[iohk.cardano-wallet.integration.api.request-42:Info:ThreadId 1284] [2019-10-11 07:52:58.66 UTC] [DELETE] /v2/wallets/b692fc03889aa6626f8cdbb928c9268d835b35b1
[iohk.cardano-wallet.integration.api.request-42:Info:ThreadId 1284] [2019-10-11 07:52:58.66 UTC] 204 No Content in 0.001139859s
[iohk.cardano-wallet.integration.worker.b692fc03:Error:ThreadId 1388] [2019-10-11 07:52:58.66 UTC] Unexpected failure while following the chain: thread killed
```

# Steps to Reproduce

1. Delete existing wallet `cardano-wallet-jormungandr wallet delete <wid>`

## Expected behavior

No error in the log.
## Actual behavior
```
[iohk.cardano-wallet.integration.api.request-42:Info:ThreadId 1284] [2019-10-11 07:52:58.66 UTC] [DELETE] /v2/wallets/b692fc03889aa6626f8cdbb928c9268d835b35b1
[iohk.cardano-wallet.integration.api.request-42:Info:ThreadId 1284] [2019-10-11 07:52:58.66 UTC] 204 No Content in 0.001139859s
[iohk.cardano-wallet.integration.worker.b692fc03:Error:ThreadId 1388] [2019-10-11 07:52:58.66 UTC] Unexpected failure while following the chain: thread killed
```

---

# Resolution Plan

- [x] Fix the error handler in `follow` to properly handle asynchronous exceptions

# PR

| Number   | Base      |
| ---      | ---       |
| #869  | `develop` |

# QA

**Comment by piotr-iohk** [comment]
I have noticed that on recent master (`117186d4f858b5d5685c8fa2247df7c274f59705`) there is also another error logged after deleting a wallet, i.e. there are two errors logged now:

 - `Unexpected failure while following the chain: thread killed` immediately after deletion.
 - `Failed to roll forward: ErrNoSuchWallet (WalletId {getWalletId = <wid>})` - when applying blocks after deletion

e.g.:

```
[iohk.cardano-wallet.serve.api.request-109:Info:ThreadId 3782] [2019-10-14 12:47:49.60 UTC] [DELETE] /v2/wallets/2587c35dc03dbe7738eaa8f096e43dd1a289b186
[iohk.cardano-wallet.serve.api.request-109:Info:ThreadId 3782] [2019-10-14 12:47:49.61 UTC] 204 No Content in 0.011228479s
[iohk.cardano-wallet.serve.worker.2587c35d:Error:ThreadId 2776] [2019-10-14 12:47:49.61 UTC] Unexpected failure while following the chain: thread killed
...
[iohk.cardano-wallet.serve.worker.2587c35d:Info:ThreadId 2776] [2019-10-14 12:47:57.63 UTC] Applying blocks [2971.22 ... 2971.22]
[iohk.cardano-wallet.serve.worker.2587c35d:Error:ThreadId 2776] [2019-10-14 12:47:57.63 UTC] Failed to roll forward: ErrNoSuchWallet (WalletId {getWalletId = 2587c35dc03dbe7738eaa8f096e43dd1a289b186})
```

**Comment by KtorZ** [comment]
Which... makes sense ^^. If there's no more wallet, we can't roll forward. We need to better handle the race conditions here and make sure the worker thread is killed cleanly.

**Comment by piotr-iohk** [comment]
Fixed.
