### ISSUE TITLE
Fork API server context into random and sequential variants.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#808]
# Context

The compatibility API server (which supports operations on Byron-style wallets) will require access to two contexts:

1. a _**random**_ context that corresponds to _**Byron**_ wallets. 
2. a _**sequential**_ context that corresponds to _**modern**_ wallets.

# Decision

Fork the existing API server context into two separate contexts, as described above. The compatibility API server should be given a definition similar to:

```hs
compatibilityApiServer
    :: forall t . 
        ( Buildable (ErrValidateSelection t)  
        , DefineTx t  
        , KeyToAddress t RndKey   
        , KeyToAddress t SeqKey   
        ) 
    => ApiLayer (RndState t) t RndKey 
    -> ApiLayer (SeqState t) t SeqKey 
    -> Server (CompatibilityApi t)
compatibilityApiServer               rndCtx seqCtx
    =    deleteByronWallet           rndCtx  
    :<|> getByronWallet              rndCtx
    :<|> getByronWalletMigrationInfo rndCtx   
    :<|> listByronWallets            rndCtx  
    :<|> migrateByronWallet          rndCtx seqCtx 
    :<|> postByronWallet             rndCtx 
```

Most operations on this API will only require access to the random context, but the [migrateByronWallet](https://github.com/input-output-hk/cardano-wallet/issues/779) operation will require access to both contexts.

# Acceptance Criteria

* The _**random**_ context _must_ only provide access to Byron-style wallets.
* The _**sequential**_ context _must_ only provide access to new-style wallets.
* It _should_ be possible to discriminate at the file-system level between _**random**_ wallet
  databases and _**sequential**_ wallet databases.

# QA

Build integration tests to verify that:
- [x] Calling the `createWallet` API function results in a database file with the **`seq`** prefix.
- [x] Calling the `createByronWallet` API function results in a database file with the **`rnd`** prefix.
- [x] Calling the `listWallets` API function _**only**_ lists wallets whose database filenames have the **`seq`** prefix.
- [x] Calling the `listByronWallets` API function _**only**_ lists wallets whose database filenames have the **`rnd`** prefix.
- [x] Calling the `getWallet` API function with a wallet ID that corresponds to a Byron wallet returns a _**wallet not found**_ error.
- [x] Calling the `getByronWallet` API function with a wallet ID that corresponds to a new-style wallet returns a _**wallet not found**_ error.

# PR

| Number | Base |
| -- | -- |
| #809 | master  |
| #810 | master  |
| #846 | master  |

**Comment by piotr-iohk** [comment]
lgtm!
