### ISSUE TITLE
Review and implement network information endpoint

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#819]
# Context

We are the de-facto proxy to the node and the underlying network for clients. Thus, it's useful for them to know some information about the network.

# Decision

Review the current endpoint specification which was designed almost a year ago. Things have evolved a bit since that day and we now have a clearer picture about how this information might be presented. In brief:

- Local chain heights will be reported as part of the wallet response
- NTP status and update proposals won't be implemented until later

# Acceptance Criteria

---

# Development Plan

- [x] Update swagger specification / documentation 
- [x] Create API types and necessary golden and roundtrip tests
- [x] Implement a network endpoint by using the global network layer
- [x] Review API response for wallets to also include a block height and network tip
- [x] Review API response for transactions to also include a block height

# PR

| Number   | Base      |
| ---      | ---       |
| #816       | `master`  |
| #824       | `master`  |
| #825       | `master`  | 
| #829       | `master`  |

# QA 

- [x] Added integration test scenario for both API and CLI:
    - [x] https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core-integration/src/Test/Integration/Scenario/API/Network.hs
    - [x] https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core-integration/src/Test/Integration/Scenario/CLI/Network.hs

- [x] Extended and adjusted the API JSON roundtrips and golden tests to reflect the actual format.

- [x] Swagger updates visible on our exported documentation: https://input-output-hk.github.io/cardano-wallet/api/

**Comment by piotr-iohk** [comment]
lgtm.
