### ISSUE TITLE
Allow launch of jormungandr in passive node mode

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#832]
# Context

When Daedalus starts `cardano-wallet-jormungandr launch` it needs control over which network the node backend connects to.

# Decision

Allow callers of `cardano-wallet-jormungandr launch` to provide extra command line arguments that are passed through to `jormungandr`.

# Acceptance Criteria

- Daedalus must be able to set which network Jormungandr connects to.
- The API port for the node should still be dynamically selected from the available TCP ports on the host.

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #822        | `master`  |

# QA 

- Integration tests are updated - `Test.Integration.Jormungandr.Scenario.CLI.Launcher`.

**Comment by piotr-iohk** [comment]
lgtm, I added a test in #887 and cleaned up old spec testing generated config.yaml, which is we no longer generate.
