### ISSUE TITLE
Allow setting listen address for API server

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#833]
# Context

Have the wallet be able to listen on interfaces other than localhost. Relevant to these situations:

- Connecting to a wallet server on a remote host.
- Running the wallet server within a docker container.

# Decision

- [x] Add a command-line option `--listen-address` to `serve` and `launch` which accepts an IP address or hostname.
- [x] The special address `0.0.0.0` means listen on all interfaces. [HostPreference specification](http://hackage.haskell.org/package/streaming-commons-0.2.1.0/docs/Data-Streaming-Network.html#t:HostPreference)

# Acceptance Criteria

- It must be possible to connect to the wallet server over the network interface specified by `--listen-address`
- The default listen address must remain as localhost.
- IPv6 may be supported

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #838       | `master`  |

# QA 

- For the server, using various listen addresses are tested with unit tests in `lib/core/test/unit/Cardano/Wallet/Api/ServerSpec.hs`. Error cases are also tested.
- Documentation updated in [Wiki](https://github.com/input-output-hk/cardano-wallet/wiki/Wallet-command-line-interface).

**Comment by rvl** [comment]
I moved the client part of this ticket to #949.

**Comment by KtorZ** [comment]
We should probably move that to JIRA as a U/S for now. Although that something I'd like to see happening, we don't have any room for this at the moment.

**Comment by KtorZ** [comment]
We should probably move that to JIRA as a U/S for now. Although that something I'd like to see happening, we don't have any room for this at the moment.

**Comment by piotr-iohk** [comment]
lgtm.
