### ISSUE TITLE
Restoration progress is non-linear and stops at ~70%

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#835]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Windows & OSX & Linux) | Code  v Configuration v Environment v Human v Unknown |

# Context
 
 

Restoration progress was recently changed to be calculated relative to the slot corresponding to the current time. Previously it was relative to the node's local tip.

#804 

# Steps to Reproduce

1. Create and restore a new wallet
2. Poll the progress using `cardano-wallet-jormungandr wallet create wallet`

## Expected behaviour

1. Restoration starts at 0% and progresses to 100% at a stable speed.

## Actual behavior
 
<A clear and concise description of what you observe instead. If applicable add screenshots to help explain your problem.>

1. Restoration is slow in the beginning, and speeds up later
2. Restoration stops at ~70%
3. Also: The nodes's local tip doesn't appear to change even after ~60 min (`lastBlockDate` from `jcli rest v0 node stats get -h http://127.0.0.1:8080/api`)

---

# Resolution Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #?       | `develop` |

# QA

**Comment by KtorZ** [comment]
This doesn't seem to be a wallet issue, doesn't it? Jörmungandr's node seems stuck, and the sync progress kinda reflect that :thinking: ..
