### ISSUE TITLE
Forgetting pending transactions

### ISSUE THREAD

**Issue by paweljakubas** [cardano-foundation/cardano-wallet#836]
# Context

As an API client, 
I want to be able to properly handle a transaction that has timed out and/or is stuck in a pending state, 
so that I am to spend locked UTxOs for wallet users.

AC:

Given there is a pending transaction
And I can “forget” it via an API call by referring to its id
When a forgotten pending transaction may show up in a block
Then viewed within a wallet

# Decision

We are going to add the following endpoint : 
`DELETE /v2/wallets/wid/transactions/tid`
which removes corresponding row from `TxMeta`. 
As a consequence, total balance (calculated basing on UTXO) will stay the same, but available balance (calculated basing on UTO minus pendings in TxMeta) is expected to increase. Applying blocks remain the same

# Acceptance Criteria

1. The API endpoint is created.
2. DB layer is empowered to forget pending tx, Sqlite and MVar impls are added and tested.
3. The respective integration tests are added that illustrate the case.
4. CLI support is delivered.
5. Swagger needs to be updated accordingly.
6. The same endpoint has to be done for Byron wallets

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #845       | `master`  |
| #853        | `master`  |
| #867        | `master`  |
| #879         | `master`  |
| #890          | `master`  |

# QA

**Comment by piotr-iohk** [comment]
Note so it is not lost:
https://input-output-rnd.slack.com/archives/GBT05825V/p1571834246030700
https://input-output-rnd.slack.com/archives/GBT05825V/p1571834379031200

 - Let's make diagrams and extend the documentation in the swagger spec before we release this.

 - One thing also: we need to remove the "invalidated" status for transactions. This is never used and confusing.

**Comment by KtorZ** [comment]
@paweljakubas are we ready to send this one into QA?

**Comment by piotr-iohk** [comment]
Still cannot fully test forget tx on byron wallets... (until https://github.com/input-output-hk/cardano-wallet/pull/934 is resolved).

**Comment by piotr-iohk** [comment]
Enabled tests for Byron wallets in #978. Closing this one.
