### ISSUE TITLE
Improper shutdown of iohk-monitoring switchboard

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#851]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Windows & OSX & Linux) | Code  v Configuration v Environment v Human v Unknown |

# Context
 
There are currently some calls to `Cardano.BM.Setup.shutdown` (presumably to flush logs on exit). However, if any thread writes logs after `shutdown` has been called, the app deadlocks.

Upstream issue: input-output-hk/iohk-monitoring-framework#415

# Steps to Reproduce/Expected behavior/Actual behavior

- Needs a code change to trigger the situation -- e.g. adding logging in an error handler.

---

# Resolution Plan

Use `bracket` to ensure that switchboard shutdown is the last thing that happens in the app.

# PR

| Number   | Base      |
| ---      | ---       |
| #852        | `master` |
| #944 | `master` |

# QA 

- The last DEBUG log message should be a "logging shutdown" message in all cases except when wallet is killed with `-9`.
- The clean shutdown functionality is mostly provided by the base library `Control.Exception.bracket` function.

**Comment by piotr-iohk** [comment]
That's perhaps a good candidate for automated tests
> The last DEBUG log message should be a "logging shutdown" message in all cases except when wallet is killed with -9


I see also that there is this option introduced:
```
  --logging-config FILE.YAML
                           File to configure the iohk-monitoring framework.
```
Few questions: 
 - What should be there in the `FILE.YAML`?
 - Are there any default values if no file is provided?

 I think it would be nice to have some tests illustrating the above, and also updated https://github.com/input-output-hk/cardano-wallet/wiki/Wallet-command-line-interface

**Comment by rvl** [comment]
@piotr-iohk I have updated the `serve` and `launch` usage on that wiki page.

The logging file format and defaults come from the iohk-monitoring project. I have asked if there is any documentation already available that we can use.

**Comment by piotr-iohk** [comment]
@rvl thanks!

I will close this one then and report an issue to track this

>The logging file format and defaults come from the iohk-monitoring project. I have asked if there is any documentation already available that we can use.
