### ISSUE TITLE
Provide a build for Daedalus installer

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#863]
# Context

Previous wallets had a Nix derivation called `daedalus-bridge` that would be integrated into the installer.

# Decision

The Daedalus installer generator should be able to `import <cardano-wallet/release.nix> {}` and use one of these attributes:

 - daedalus-jormungandr.linux
 - daedalus-jormungandr.macos
 - daedalus-jormungandr.windows

# Acceptance Criteria

- It's possible to generate Daedalus installers for Windows, macOS, Linux,
- Necessary dependencies (jormungandr, DLLs) are included in the derivation.

---

# Development Plan

As above.

# PR

| Number   | Base      |
| ---      | ---       |
| #864       | `master`  |

# QA 

- Get the builds from Hydra and try them on the target platforms.

**Comment by piotr-iohk** [comment]
> Get the builds from Hydra and try them on the target platforms.

@rvl, @KtorZ - Can you pls provide links from where I can download the builds?
https://hydra.iohk.io/jobset/Cardano/cardano-wallet#tabs-jobs has those _jobs_

daedalus-jormungandr.linux
daedalus-jormungandr.macos
daedalus-jormungandr.windows

but I don't see any downloadable binary artifacts there...

**Comment by rvl** [comment]
@piotr-iohk 

That QA text I wrote is slightly vague - sorry.

Those attributes are intended to be imported and referenced from the Daedalus installers build, rather than downloaded from the Hydra web interface.

When you run these commands, it will download the builds from hydra.iohk.io. So that's what I meant to say.
```
nix-build release.nix -A daedalus-jormungandr.linux
nix-build release.nix -A daedalus-jormungandr.macos
nix-build release.nix -A daedalus-jormungandr.windows
```
(if it doesn't simply download the build, then try again from a clean git checkout).

**Comment by piotr-iohk** [comment]
ok
