### ISSUE TITLE
Extend network layer to support transaction creation

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#89]
# Context

This task is part of the `Submit transaction` story. We need to have our [Network Layer](https://github.com/input-output-hk/cardano-wallet/tree/master/src/Cardano/NetworkLayer) extended such that we can post transaction to the blockchain. [`Cardano-http-bridge`](https://github.com/input-output-hk/cardano-http-bridge) has already the endpoint for posting a transaction `POST: /:network/txs/signed` which needs to be handled in our network layer.

# Decision
Extend Network Layer to support posting a transaction via `cadano-http-bridge`.

# Acceptance Criteria

1. The Network Layer _must_ be extended to support `POST: /:network/txs/signed` endpoint from `cardano-http-bridge` in order to be able to post transaction to the blockchain.

---

# Development Plan

- [x] I plan on adding something like
```
type PostSignedTx
    =  Capture "networkName" NetworkName
    :> "txs"
    :> "signed"
    :> ReqBody '[Base64 CBOR] SignedTx
    :> Post '[NoContent] ()
```

- [x] ~I plan on getting a `Base64` content type working~
- [ ] ~I maybe plan on adding a `sign :: Tx -> SignedTx` function or something~
- [ ] ~I plan on getting `encodeSignedTx` working and roundtrip-tested, while mocking witness.~
- [ ] ~I intend to look in `cardano-sl` for how to create a proper witness.~

# PR

| Number   | Base      |
| ---      | ---       |
| #130        | `master`  |
| #141         | `master`  |
| #146         | `master`  |

# QA 

- `CBOR` roundtrip tests were added for `encode/decodeTxWitness` and `encode/decodeSignedTx` https://github.com/input-output-hk/cardano-wallet/blob/028a5effc62d8783232d5fc5b8446e5ab06812e2/test/unit/Cardano/Wallet/BinarySpec.hs#L127-L152
- We submit txs to the http-bridge and check that we see appropriate error messages in two integration test cases https://github.com/input-output-hk/cardano-wallet/blob/028a5effc62d8783232d5fc5b8446e5ab06812e2/test/integration/Cardano/Wallet/Network/HttpBridgeSpec.hs#L106-L123
- Also have Aeson roundtrip property + goldens for checking the JSON fromat of the `SignedTx` wrapper (that `{"signedTx": <base64>}` turns to `SignedTx ByteString`)

**Comment by KtorZ** [comment]
@anviking 

>  I maybe plan on adding a sign :: Tx -> SignedTx function or something

This will be done as part of #95 

>  I intend to look in cardano-sl for how to create a proper witness.

This will also be part of #95 (which is a likely follow-up for this task anyway I suppose :) )

**Comment by piotr-iohk** [comment]
lgtm :+1: 
I have added few more tests in #146. @Anviking - pls review if you have a chance.
