### ISSUE TITLE
Extend Jörmungandr Binary format to support Type 4 messages

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#891]
# Context

Our binary serializer/deserializer for Jörmungandr core types currently have holes. In particular, we do not support `Type 4: Certificate` type of messages (see also https://github.com/input-output-hk/chain-libs/blob/master/chain-impl-mockchain/doc/format.md#type-3-certificate).

In order to implement delegation, we'll need to be able to serialize and deserialize delegation certificates. Delegation certificates' content should be the concatenation of the reward account public key and the pool id as:

```
payload = account_pub_key | pool_id
```

# Decision

- Message needs to support 'Type 4: Certificates' types
    - Able to deserialize a message of type 4
    - Able to serialize a transaction with a certificate payload (very much like [`putSignedTx`])(https://github.com/input-output-hk/cardano-wallet/blob/b3c04e557b840f590c095d8e2d385e406ed1f0b2/lib/jormungandr/src/Cardano/Wallet/Jormungandr/Binary.hs#L387)
- Account public key should be mapped to an 32-byte-length ChimericAccount
- The pool identifier should be mapped to `PoolId` from the primitive types 

# Acceptance Criteria

1. `cardano-wallet-jormungandr` _must_ support deserializing type 4 messages
2. `cardano-wallet-jormungandr` _may_ only support `Staking declaration` certificate type
3. `cardano-wallet-jormungandr` _must_ support serializing a transaction with a certificate attached.

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #932       | `master`  |

# QA 

There were tests added. Also binary with TransactionWithDelegation inside it. Maybe it is worth generating another, more interesting binary, and check added message 4 handling - see added golden tests for inspiration

**Comment by piotr-iohk** [comment]
lgtm.
