### ISSUE TITLE
Extend Fee Policy With Flat Fee For Certificate

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#892]
# Context

The Jörmungandr fee policy actually consists of 3 values:

- A coefficient;
- A constant fee;
- A certificate flat fee.

(see also: https://github.com/input-output-hk/chain-libs/blob/master/chain-impl-mockchain/doc/format.md#type-0-initial-blockchain-configuration)

Our own `FeePolicy` only represents the first two, and discards the certificate flat fee during binary deserialization.

# Decision

- Parse the certificate flat fee from the Jörmungandr binary representation.
- Extend the `FeePolicy` type to include the flat certificate fee.
- Revise the `feeOpts` function from the wallet layer and provide multiple constructors to choose the type of policy to apply (so we can easily select whether we need to take certificate fees into account or not).

# Acceptance Criteria

1. `cardano-wallet-core` `FeePolicy` _must_ account for certificate flat fees.
2. `cardano-wallet-jormungandr` _must_ correctly deserialize fee policy to all three values (constant, coefficient, certificate).
3. The wallet layer _must_ still ignore certificate fees when balancing standard transactions .

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #946        | `master`  |

# QA 

The PR was about extending fee policy. Until now it was `a + bx` like policy where x is byte payload. After extending to `a + bx + cy` where y is the number of delegated certificates it propagated to the following tests : 
1. https://github.com/input-output-hk/cardano-wallet/pull/946/files#diff-ea01d42dc8106d3d2e18f8ec129c9fa3R581
(here just checking the proper format)
2. https://github.com/input-output-hk/cardano-wallet/pull/946/files#diff-243dc78f6db975fd4b83e50a4e045bc1R143
(here reading from binary the last part - previously it was ignored)
The above tests are hinting directions for next testing (if one is eager to)

**Comment by piotr-iohk** [comment]
lgtm
