### ISSUE TITLE
Extend 'TransactionLayer' to allow construction of a certificate registration request

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#893]
# Context

To register a certificate, one needs to create a special kind of transaction (a.k.a token transfer in Jörmungandr's terminology) which contains the certificate registration as a payload.

https://github.com/input-output-hk/chain-libs/blob/master/chain-impl-mockchain/doc/format.md#witnesses

```
TRANSACTION-SIGN-DATA-HASH = H(PAYLOAD | IOs)
Authenticated-Data = H(HEADER-GENESIS) | TRANSACTION-SIGN-DATA-HASH | WITNESS-SPECIFIC-DATA
```

At the moment, we always construct transactions with empty payloads (`TokenTransfer<PAYLOAD = ()> | Witnesses`) however, we know need to also be able to construct transfer carrying a certificate registration (`PAYLOAD=account_public_key|stake_pool_id`). 

# Decision

- Either extend the 'TransactionLayer' with a new function for creating certificate registration:

  ```hs
  mkCertificateTx
    :: (Address -> Maybe (k 'AddressK XPrv, Passphrase "encryption"))
    -> (PoolId, k 'AddressK XPrv)
    -> [(TxIn, TxOut)]
    -> [TxOut]
    -> Either ErrMkStakeDelegationTx (Tx t, [TxWitness])
  ```

- Or, extend the `mkStdTx` to also support having a `Maybe` payload and produce witnesses accordingly. 

# Acceptance Criteria

1. One _must_ be able to produce witnesses for a given transaction that also carry a single delegation certificate registration using the transaction layer.

---

# Development Plan

- I'm going to test this with golden test data produced by `jcli`, as is done for the existing transaction spec.

# PR

| Number   | Base      |
| ---      | ---       |
| #1059        | `master`  |

# QA 

- We compare the `mkDelegationCertTx` binary with that of `jcli` in two golden tests: https://github.com/input-output-hk/cardano-wallet/blob/e8cac3c32825bb9e9e9f9b964c59a8d7fb771a68/lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/TransactionSpec.hs#L217-L281

- There is a `Binary` roundtrip making sure we can decode a delegation tx we have encoded https://github.com/input-output-hk/cardano-wallet/blob/41fca2286bb3f593a9e4f1a214236e18b2174d06/lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/BinarySpec.hs#L167-L185

**Comment by piotr-iohk** [comment]
lgtm.
