### ISSUE TITLE
HD Derivation for reward accounts

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#894]
# Context

We are extending the HD derivation path for sequential wallets to support an extra value for what is currently called the "change chain" path. A value of `2` will now indicates a reward account set of key. 

See also https://github.com/input-output-hk/chain-wallet-libs/blob/master/doc/CRYPTO.md#extension-to-accounting-style

# Decision

  - Review and rename 'ChangeChain' to capture the following idea:

    ```hs
    data AccountingStyle -- previously 'ChangeChain'
      | UTxOExternal     -- previously 'ExternalChain'
      | UTxOInternal     -- previously 'InternalChain'
      | MutableAccount   -- newly introduced
    ```

  - Update comments and doc for 'Depth' and 'ChangeChain' carefully

# Acceptance Criteria

1. It _must_ be possible to perform address key derivation  using `MutableAccount` as a 4th derivation path.
1. Existing derivations _must_ remain unchanged and use `UTxOExternal` and `UTxOInternal` according to their old values. 

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #955        | `master`  |

# QA 

the PR was about extending and renaming `ChangeChain` to `AccountingStyle`. 
1. It is worth checking if added comment is simple enough and conveys message : 
https://github.com/input-output-hk/cardano-wallet/pull/955/files#diff-d14c4b850bb3168e6ef09bf8769d120aR161
2. Or if some more tests could be added in `lib/core/test/unit/Cardano/Wallet/Primitive/AddressDerivation/ShelleySpec.hs` and `lib/core/test/unit/Cardano/Wallet/Primitive/AddressDiscovery/SequentialSpec.hs ` - see files: 
https://github.com/input-output-hk/cardano-wallet/pull/955/files#diff-d14c4b850bb3168e6ef09bf8769d120aR161

**Comment by jonathanknowles** [comment]
@KtorZ This sentence seems a bit mangled:
> A value of 2 will know indicates a reward account set of key.

Are you able to unmangle it? (I would do it, but I'm not sure what the original meaning is.)

**Comment by KtorZ** [comment]
@jonathanknowles It's a typo, `know` --> `now`

**Comment by piotr-iohk** [comment]
lgtm.
