### ISSUE TITLE
Implement API types for delegation endpoints

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#895]
# Context

- https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/joinStakePool
- https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/quitStakePool

# Decision

- Create API types definitions needed to implement these endpoints
- Wire up the endpoint declarations into the Servant server
- Implement handlers as `throwError err501`

# Acceptance Criteria

1. The server _must_ serve the API endpoint corresponding to the `joinStakePool` operation from the swagger spec
2. The server _must_ serve the API endpoint corresponding to the `quitStakePool` operation from the swagger spec
3. Endpoints handlers _should not_ be implemented yet and return a `501 Not Implemented` HTTP error when accessed.

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #920        | `master`  |

# QA 

Two endpoints were added. It is worth if they are present and behave as REST verbs suggest. Moreover, if handled errors as advertised in swagger are as expected

**Comment by piotr-iohk** [comment]
Added some preliminary tests in #962.
