### ISSUE TITLE
Nuke `cardano-wallet-http-bridge`

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#897]
# Context

- `http-bridge` has more holes than any cheese :cheese: 
- `http-bridge` is a development burden that costs us hours of maintenance
- We aren't running integration or unit tests for `http-bridge` in CI anymore
- There's now a TestNet for `jormungandr` which we'll be able to use for restoration benchmarks
- To implement delegation features, we will need to go into some heavy structural changes regarding how we look at addresses and public keys. There's no point in loosing hours in fixing these issues for `http-bridge`

# Decision

- rm -rf `lib/src/http-bridge` && everything related to it

# Acceptance Criteria

1. `cardano-wallet-http-bridge` _must_ not exist anymore
2. nightly builds _shouldn't_ be replaced with anything .. yet.

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #634        | `master`  |

# QA 

- `git grep "bridge"` (just comments https://github.com/input-output-hk/cardano-wallet/pull/634#issuecomment-545925924 and strings)
- `git grep "cardano-sl-node"` (nothing)

**Comment by piotr-iohk** [comment]
lgtm.
