### ISSUE TITLE
Extend 'Block' to also contain delegation certificates registrations

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#898]
# Context

Delegation certificate registration (a pair of a pool id and an account public key) can be present in blocks. We'll have to be able to process them and adjust the wallet delegation settings accordingly. 

# Decision

- Extend primitive 'Block' type to also contain delegation certificates registrations. e.g.

  ```hs
  data Block tx = Block
      { header
          :: !BlockHeader
      , transactions
          :: ![tx]
      , delegations
          :: ![(XPub, PoolId)]
      } 
  ```

- Extend Jörmungandr Binary decoder to decode certificate messages & adjust conversion functions from Jörmungandr 'Block' to our new primitive 'Block'.

# Acceptance Criteria

1. `Cardano.Wallet.Primitive.Types#Block` _must_ contain delegation registrations requests
1. `Cardano.Wallet.Jormungandr.Binary#Block` _must_ contain delegation registrations requests
2. `cardano-wallet-jormungandr` _must_ support correctly map Type 3 messages and Type 1 messages to primitive `Block`

---

# Development Plan

- [x] Extend the Jörmungandr `Block` type to contain stake delegations.
- [x] Adjust the `convertBlock` function to populate the `delegations` field when converting from a Jörmungandr block to Wallet-layer block.
- [x] ~~Write golden tests for `convertBlock` with golden blocks with delegations.~~

# PR

| Number   | Base      |
| ---      | ---       |
| #1043        | `master`  |

# QA 

Covered by QA tasks in issue #899.

**Comment by jonathanknowles** [comment]
Hi @KtorZ, are you able to say what "Type 3" and "Type 1" refer to in the acceptance criterion below:
> 3. cardano-wallet-jormungandr must support correctly map Type 3 messages and Type 1 messages to primitive Block

I had a look through and couldn't see anything obvious. Thanks in advance!

**Comment by KtorZ** [comment]
@jonathanknowles this refers to the fragment type (a.k.a fragment spec in Jormungandr).
Yet, since I wrote this ticket, type 3 became type 4 :)

What's important to capture here is that delegation certificates should now be part of our primitive blocks, as the title suggests.

**Comment by KtorZ** [comment]
*Putting this back to `In progress` because:

- We're missing the PRs links into to PR section
- The `QA` section is empty.

**Comment by jonathanknowles** [comment]
@KtorZ in your opinion, are additional tests required over and above the tests already provided by #899? (PR #1050).

We could of course provide additional unit or property tests for the `convertBlock` function.

**Comment by KtorZ** [comment]
I don't think so no. With all the integration tests for this one and the binary unit tests, it seems to me that it's already well tested. 1

**Comment by jonathanknowles** [comment]
@KtorZ wrote:
> I don't think so no. With all the integration tests for this one and the binary unit tests, it seems to me that it's already well tested. 1

Okay in that case, I'll adjust the QA section to refer to the tests produced as part of fixing issue #899.

Thanks for confirming!

**Comment by piotr-iohk** [comment]
lgtm.
