### ISSUE TITLE
Allow address introspection within the wallet engine.

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#900]
# Context

We currently represent addresses as raw `ByteString` which has the nice advantage of being opaque to the wallet engine. As a consequence, we are capable of having a wallet engine which is fairly agnostic to the underlying address format.  

Yet, in order to implement delegation, we're going to need being able to extract a spending public key from an address (the address pool only keeps track of the spending public key indexes, regardless of whether they are grouped with a delegation key or not). 

# Decision

We can take multiple approaches here but, a few ideas:

1. Define an interface to allow introspecting an address to extract either its payment key or, if any, its delegation key instance of this interface for 'SeqKey'.  Something along the lines:

  ```hs
  class IntrospectAddress where
      getSpendingKey :: Address -> SeqKey 'AddressK XPub
      getDelegationKey :: Address -> Maybe (SeqKey 'AddressK XPub)
  ```

Such interface will be impossible to implement for Byron addresses, but they don't support delegation anyway.

2. Make `Address` a type parameter of the wallet engine and define address capabilities in the target themselves. The `Address` is only present in the `TxOut` and we already have an abstract type for transactions. This would effectively mean having different concrete address types which we'd still have to be able to serialize and deserialize for the database. 

Likely, option 2 would lead to a more elegant and less clunky engine by properly abstracting types for it. Yet, that's also probably much more work. 

# Acceptance Criteria

1. The wallet engine _must_ be able to extract the spending public key or a fingerprint that uniquely identifies it from an address when instantiated with a `SeqState`.
2. The wallet engine _may_ still treat addresses as opaque blobs when instantiated with a `RndState`

---

# Development Plan

- [x] Make the wallet engine agnostic to the Key format and leave it to targets to define what their Key format is.

- [x] Add a simple property test the relationship between the address length and the existence of a staking key.

- [x] Fix nightly tests

# PR

| Number   | Base      |
| ---      | ---       |
| #926      | `master`  |
| #969      | `master` |
| #1023    | `master` |

# QA 

- The code has been re-organized to properly allow this to be implemented.

- A new abstraction has been introduced called the `KeyFingerprint` which allow to capture a fingerprint uniquely identifying a given address. That fingerprint can also then be used to reconstruct an address: https://input-output-hk.github.io/cardano-wallet/haddock/edge/cardano-wallet-core-2019.11.6/Cardano-Wallet-Primitive-AddressDerivation.html#t:MkKeyFingerprint 

- A few property tests have been added to show that the fingerprint can be extracted out of addresses or fails for invalid addresses: https://github.com/input-output-hk/cardano-wallet/blob/93978c8497604ff60c5d8b3aa09fdf248dc53573/lib/core/test/unit/Cardano/Wallet/Primitive/AddressDerivation/ShelleySpec.hs#L99-L105

**Comment by piotr-iohk** [comment]
Is it possible/Would it make sense to add some roundtrip tests? Something like _address -> fingerprint -> address_ ?

**Comment by KtorZ** [comment]
Yes!

**Comment by piotr-iohk** [comment]
lgtm.
