### ISSUE TITLE
Revise 'AddressPool' to work with address public keys

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#901]
# Context

Our 'AddressPool' currently keeps track of a pool of 'Addresses' which has a major drawback:

- A spending address public key can be associated with infinitely many delegation key (which may result in an infinite number of addresses corresponding to same spending key).

- When discovering addresses, the wallet should only look at whether the spending key belongs to it. It is possible to create addresses that use a delegation key that belongs to another wallet.

# Decision

- Review 'AddressPool' to work with address public keys instead of addresses. 

- Review address discovery capabilities to also use keys instead of addresses when relevant.

# Acceptance Criteria

1. The sequential discovery _must_ use a single address pool per accounting style to keep track of all transactions made using address public keys derived from the pool's account.
1. The sequential discovery _must not_ keep track of addresses using a `MutableAccount` accounting style
1. The address underlying binary structure _must_ remain unknown to the sequential discovery 

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #942       | `master`  |

# QA 

- The module was already heavily tested (see https://github.com/input-output-hk/cardano-wallet/blob/93978c8497604ff60c5d8b3aa09fdf248dc53573/lib/core/test/unit/Cardano/Wallet/Primitive/AddressDiscovery/SequentialSpec.hs#L111-L199) 

- The type has been adjusted to work with fingerprint instead of addresses, although the outer API has been kept the same for now. 

- The tests still pass despite an heavy internal change

**Comment by piotr-iohk** [comment]
lgtm.
