### ISSUE TITLE
Extend Jörmungandr Client to support fetching an account state

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#902]
# Context

https://input-output-hk.github.io/jormungandr/jcli/rest.html#get-account-state

# Decision

- Extend `JormungandrClient` with a function to get an account's state

# Acceptance Criteria

1. `JormungandrClient` _must_ support fetching an account's state.

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #995       | `master`  |
| #1053      | `master`  |

# QA

**Comment by jonathanknowles** [comment]
@KtorZ In our codebase, do we already have a suitable type that we can reuse for `AccountId`? Looking at the Jormungandr source code, it seems to just be:

> either an address with the account kind or a ed25519 publickey.

source: https://github.com/input-output-hk/jormungandr/blob/650a005c6b3577921c1f754c2d91c0e038e31d11/jcli/src/jcli_app/utils/account_id.rs#L17

**Comment by jonathanknowles** [comment]
@KtorZ I note that we also have this:

https://github.com/input-output-hk/cardano-wallet/blob/master/lib/jormungandr/src/Cardano/Wallet/Jormungandr/Binary.hs#L643

**Comment by KtorZ** [comment]
@jonathanknowles we currently have `ChimericAccount` in the primitive types :+1:

**Comment by jonathanknowles** [comment]
> @jonathanknowles we currently have `ChimericAccount` in the primitive types +1

Great, thanks for confirming @KtorZ.

**Comment by jonathanknowles** [comment]
@KtorZ experimenting with `jcli`:
```
jcli rest v0 account get ca1skzn99jx8a2rw80gp9uea47tmcndv7gm28vy9as6akevy32204aqwzpsctx --host http://127.0.0.1:43665/api --output-format json
```
Gives the following result:
```json
{ "counter": 0
, "delegation":
  { "pools":
    [ [ "5cfbb7f7ec0050499fbd1c79515216c5ad636b97d1944bde8a7db98e7d126803"
      , 1
      ]
    ]
  },
  "value": 1
}
```

Within the list of stake pools, what is the value of `1` supposed to represent? 
Within the Jormungandr source code, we have this definition:

```rust
pub struct AccountState { 
    delegation: DelegationType,   
    value: Value, 
    counter: u32, 
}
```

source: https://github.com/input-output-hk/jormungandr/blob/master/jormungandr-lib/src/interfaces/account_state.rs#L69-L73

Which is defined in terms of this:
```rust
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)] 
pub struct DelegationType {   
    pools: Vec<(Hash, u8)>,   
}
```
Looking a bit further, the `u8` value seems like it's some kind of ratio:
https://github.com/input-output-hk/jormungandr/blob/master/jormungandr-lib/src/interfaces/account_state.rs#L35

This would make sense if the user wanted to delegate their stake to more than one pool, and assign a ratio to each.

**Question:** are we going to make use of this value? If not, how should we process it during deserializing?

**Comment by KtorZ** [comment]
@jonathanknowles 
I believe this refers to the `delegation ratio`. Jörmungandr allows for delegating to multiple stake pools at once by providing a particular delegation ratio. The case we support in the wallet backend is a particular case of this where the delegation is fully done to one particular stake pool (ratio is then `1`). But in practice, you could have two stake pools in this list, with let's say 0.4 and 0.6

**Comment by piotr-iohk** [comment]
I've added few additional tests -> #1053. And have a doubt/question about returned error in one case.

**Comment by piotr-iohk** [comment]
lgtm
