### ISSUE TITLE
Extend wallet's API responses with a reward

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#903]
# Context

As an API client, when fetching a wallet, I want to know how much ADA is available on my reward account.
We know there's only a single reward account which can be derived from the root key so this value should always be available.

https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/getWallet

# Decision

- Extend the swagger definition for the wallet resource to also return a `reward` balance in the balance field.
- Make the corresponding change in the API types and server
- For now, always return a value of 0

# Acceptance Criteria

1. The API response for `getWallet` _must_ contain a 'reward' field 
1. The API responses for `listWallet` _must_ all contain a 'reward' field
1. Reward _should_ always be set to 0 for now

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #948       | `master`  |

# QA

**Comment by piotr-iohk** [comment]
lgtm.
