### ISSUE TITLE
Properly fetch and assign reward account value when fetching wallets

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#904]
# Context

Glue code between #903 and #902 

# Decision

- Effectively implement the reward account reporting by fetching the value from the network layer when fetching or listing a wallet.

# Acceptance Criteria

1. The 'balance.reward' of the wallet resource _must_ reflect the actual value for that reward account as known by the node.

---

# Development Plan

1. Forward `getAccountState` of `JormungandrClient` to `NetworkLayer` (easiest option for now)
2. ~use `getAccountState` and `deriveRewardAccount` from `Api.Server`. Maybe add a `getRewards`-helper  in `Cardano.Wallet`.~ The derivation requires the passphrase. We need to store the reward account in the DB.
3. Re-generate faucet addresses be grouped addresses instead of single
4. Test that rewards accumulate after joining the top stake pool in the integration tests

# PR

| Number   | Base      |
| ---      | ---       |
| #1082 |  `master`  |

# QA 

- Quite extensive integration scenario added here testing that rewards are indeed accumulated in the reward account after a certificate is submitted: https://github.com/input-output-hk/cardano-wallet/blob/master/lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/API/StakePools.hs#L213-L264

- Good to know: when a certificate is submitted at epoch `e`, the delegation is only active at epoch `e+2` and, rewards only starts at epoch `e+3` (for the delegator needs to have "helped" the pool with his stake for at least one epoch to get a reward).

**Comment by Anviking** [comment]
I don't see why this would be completely blocked by #899 so I'm starting it.

**Comment by piotr-iohk** [comment]
lgtm.
