### ISSUE TITLE
Automatically generate golden tests for ToJSON instances of API types

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#91]
# Context

Golden tests can help us verify that our API json format doesn't change accidentally.

There were some talk about golden-tests on the legacy-wallet (and there was one ticket created  https://github.com/input-output-hk/cardano-wallet-legacy/issues/124)

> API breaking changes are bad and also tricky to identify somehow. Right now, there's nothing really helping us not breaking the API apart from our own discipline. Despite being disciplined, something can also slip through our attention and get merged, unnoticed. A simple step towards this would be to add a few golden tests to make sure that API types aren't actually changing in a non backward-compatible ways.
>
> If a given API type has one or a few associated golden test, hopefully, upon making a change, the underlying change would fail. Then, we can assess whether this change is a breaking change or just a soft extension.

We have / will have API-level types with `Aeson` `ToJSON`/`FromJSON` - instances. The API types can be composed of smaller types as product (record) or sum types. It seems like we could generate golden tests automatically.

# Decision

Find a way to generate golden-tests automatically, to ensure that the JSON-format stays consistent. We want to test all interesting cases of our types (e.g make sure we test the format of all the error-cases in an error sum-type)

# Acceptance Criteria

1. There _must_ exist a way to trigger re-generation of golden-tests
2. Generated golden-tests _should_ test the format of _all_ API types, in _all_ interesting cases. (May be weakened if infeasible)
3. We _may_ utilise https://hackage.haskell.org/package/hspec-golden-aeson

---

# Development Plan

- [x] Play around with it, make pr
- [x] Check how it handles large types (whether or not it adapts the number of samples to cover all cases) for second acceptance criteria

# PR

| Number   | Base      |
| ---      | ---       |
| #102        | `master`  |
| #116 (closed)        | `master`  |

# QA 

- See https://github.com/input-output-hk/cardano-wallet/blob/3c56a9ced1ffa122be37aacad96e983f1dc9b17b/test/unit/Cardano/Wallet/Api/TypesSpec.hs#L149-L161 for how it functions
- We need to be careful about missing cases of complex types. (cf https://github.com/input-output-hk/cardano-wallet/pull/102#issuecomment-475262503) Making sure to add tests for "sub-types" is also strategy to deal with this.

**Comment by KtorZ** [comment]
(ready for QA?)

**Comment by piotr-iohk** [comment]
lgtm :+1:
