### ISSUE TITLE
Extend SQLite to allow storing pool registration certificates

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#913]
# Context

With #898, certificate registrations will now be part of blocks normally processed by the wallet layer.

During restoration, we want to be able to also restore registration certificates that are ours and that have been submitted to the chain. We need to keep track of the full history to also be able to cope with rollbacks.

# Decision

- Extend the SQLite `Checkpoint` table to carry a `Maybe Certificate` where `Certificate` refers to a stake pool registration certificate.

- Remove the `walDelegation` from the `Wallet` table which only contains static data unaffected by rollbacks

- Extend the SQLite `Wallet` table to store a pre-generated reward account key (there's only one per wallet, see also #894).

- Review `readWalletMeta` to lookup for certificate in the most recent checkpoint

# Acceptance Criteria

1. The DBLayer _must_ support storing a certificate with a `Checkpoint`
2. The DBLayer _must_ correctly yield the delegation status when returning `WalletMetadata` 

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #980        | `master`  |
| #996        | `master`  |

# QA 

- New table created in the database a set of new command "putDelegationCertificate" in the database layer. 

- State-machine extended with the corresponding command: https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Cardano/Wallet/DB/StateMachine.hs#L514 

- Controlled state-machine coverage with a new tag checking that we cover the case where the wallet metadata are read (and compared with the model) after a certificate has been inserted (to observe the correct handling of the delegation settings in the metadata!): https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Cardano/Wallet/DB/StateMachine.hs#L743

- State-machine actually even caught a bug after many runs that was fixed in https://github.com/input-output-hk/cardano-wallet/pull/997

**Comment by piotr-iohk** [comment]
lgtm.
