### ISSUE TITLE
Port coin selection and fee calculation from legacy

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#92]
# Context

Coin selection happens in order to choose UTxO from the available ones in a wallet to cover (when possible) for the cost of a transaction. More details in [About Coin Selection](https://github.com/input-output-hk/cardano-wallet/wiki/About-Coin-Selection)

In the context of this new wallet backend, we will need a subset of the coin selection previously developed in the legacy code base: see [Kernel/CoinSelection](https://github.com/input-output-hk/cardano-wallet-legacy/tree/develop/src/Cardano/Wallet/Kernel/CoinSelection).

The first module:

- [Kernel/CoinSelection/Generic](https://github.com/input-output-hk/cardano-wallet-legacy/blob/develop/src/Cardano/Wallet/Kernel/CoinSelection/Generic.hs) provides a generic DSL to perform CoinSelection on a ledger relying on UTxO accounting.

- [Kernel/CoinSelection/FromGeneric](https://github.com/input-output-hk/cardano-wallet-legacy/blob/develop/src/Cardano/Wallet/Kernel/CoinSelection/FromGeneric.hs) provides an implementation of the aforementioned DSL for Cardano.

- [Kernel/CoinSelection/Generic/Fee](https://github.com/input-output-hk/cardano-wallet-legacy/blob/develop/src/Cardano/Wallet/Kernel/CoinSelection/Generic/Fees.hs) contains logic to perform fee adjustment on a selection yield by the above modules.

- [Kernel/CoinSelection/Generic/Grouped](https://github.com/input-output-hk/cardano-wallet-legacy/blob/develop/src/Cardano/Wallet/Kernel/CoinSelection/Generic/Grouped.hs) is now irrelevant as we won't be considering grouping

- [Kernel/CoinSelection/Generic/LargestFirst](https://github.com/input-output-hk/cardano-wallet-legacy/blob/develop/src/Cardano/Wallet/Kernel/CoinSelection/Generic/LargestFirst.hs) provides a simple heuristic from selecting coins from the largest first. This is the fallback heuristic in case where the random selection fails to yield a satisfactory solution. If the largest first doesn't yield any result, we know that there are not enough funds to cover the transaction cost and, a failure should be reported to users.

- [Kernel/CoinSelection/Generic/Random](https://github.com/input-output-hk/cardano-wallet-legacy/blob/develop/src/Cardano/Wallet/Kernel/CoinSelection/Generic/Random.hs) contains logic for performing a random selection while improving the selection to minimize the discrepancy between change outputs and normal outputs.

Our final implementation only truly use a subset of the available features from the coin selection "engine", so, it is a legitimate question to ask whether we should port everything in there and preserve the existing format. The generic abstraction makes it possible to have a code that is fairly agnostic to any specificity of a particular coin or wallet. This code has also gone through several round of testing and QA, and despite having some known limitations, is expected to work fairly okay now. On the other hand, it adds several layers of indirection that are probably not needed since we do not intend to support different coins and policy _now_ (and probably not in a near future). Not mentioning that, most of the property and unit testing happens on a concrete implementation using legacy types. So, there's not much from the testing we can re-use. 

# Decision

We'll port relevant part of the coin selection algorithm, dropping the generic approach and fallback to a specialized implementation using our primitive types. Doing so, we'll also NOT port:

- Generic DSL
- PrivacyModeOff approach from the random selection
- Grouping policy 
- Receiver pay fee

Instead, we'll focus on providing a concrete implementation that cover our current and upcoming needs, testing as we go and preserving the algorithms as they currently exists in the generic coin selection. 

The legacy coin selection implementation is also known to be quite _inaccurate_ in the way it reports error. So, we do want to be extra careful when dealing with errors and make sure we make the implementation very honest and helpful about errors. 

In order to simplify the implementation work for this particular bit, we will also push back on the exact fee calculation for transaction and leave the implementation flexible regarding fees, using hard-coded constant for now (and for this, we may consider an interface closely resembling to [FeeOptions](https://github.com/input-output-hk/cardano-wallet-legacy/blob/develop/src/Cardano/Wallet/Kernel/CoinSelection/Generic/Fees.hs#L31-L40)).

# Acceptance Criteria

- [ ] We _must_ be able to perform coin selection from available UTxOs, and yield a result in the form of: 
    - a list of inputs 
    - a list of outputs
    - a list of change coins (later mapped to change addresses)

- [ ] Coin selection _must_ preserve privacy and generate, as much as possible, outputs and change addresses that are roughly of the same size (this can be achieved by porting the algorithms used in the legacy coin selection).

- [ ] Coin selection _should_ make the sender pay fees, removing fee from its original change

- [ ] We _should_ preserve the separation of concerns between coin selection and fee adjustments.

- [ ] We _may_ port the various integration test scenarios about coin selections that exist on the legacy code base in the form of unit tests, and control that selection are yielded correctly

- [ ] Coin selection _shouldn't_ include any form of grouping at this stage

- [ ] Explicit fee calculation and estimation from a transaction _may_ be mocked with dummy values at this stage

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #121        | `master`  |
| #140        | `master`  |
| #165        | `master`  |
| #174        | `master` |

# QA 

Please refer to all tests added, unit tests and also property tests (see [test/unit/Cardano/Wallet/CoinSelection/Policy](https://github.com/input-output-hk/cardano-wallet/tree/master/test/unit/Cardano/Wallet/CoinSelection/Policy))

**Comment by piotr-iohk** [comment]
@paweljakubas, @KtorZ - the ticket is in QA however there is still open pr #176 related to it ( at least it has #92 in Issue number)...

**Comment by KtorZ** [comment]
Yes, @piotr.stachyra this PR should be attached to another ticket we opened today because the fee calculation was a bit out of scope for #92

**Comment by piotr-iohk** [comment]
@KtorZ (addressing you since @paweljakubas is off) - seems there are few areas here that are not _covered_ by tests: 

- https://coveralls.io/builds/23064602/source?filename=src/Cardano/Wallet/CoinSelection/Policy/Random.hs#L135
- https://coveralls.io/builds/23064602/source?filename=src/Cardano/Wallet/CoinSelection/Policy/Random.hs#L183
- https://coveralls.io/builds/23064602/source?filename=src/Cardano/Wallet/CoinSelection/Policy/Random.hs#L209

**Comment by KtorZ** [comment]
So. @piotr-iohk 

- L135 & L209: This is interesting. It looks like we are not evaluating the resulting change in our tests :thinking: ... I'll have a look into this.

- L183: Looking a bit more into `condC`, it seems that this condition is _redundant_ with `condB`. Indeed, the only way to exceed the maximum amount would be by selecting an input that doesn't get us closer to our ideal (but get us really far from it!). So in the end, either `condB` is true and `condC` is necessarily true. Or `condB` is false and `condC` is necessarily false (`condB => condC`) and, because of lazyness here, `condC` is never evaluated. We can change the order of evaluation, or, totally remove `condC` (I can't see any case where `condB` doesn't imply `condC` :thinking: )

**Comment by KtorZ** [comment]
@piotr-iohk The first previous point has been fixed with #196.
Second point won't be fixed here, the condition is never evaluated in our testing and I do believe we can't encounter it, but I don't want to remove it without proper thinking / analysis and keep it as a guard.

**Comment by piotr-iohk** [comment]
:+1:
