### ISSUE TITLE
Wallets reporting of sync progress is inconsistent

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#921]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Windows & OSX & Linux) | Code  v Configuration v Environment v Human v Unknown |

# Context
 
Observed on 0.7.x Jorm testnet, when my node was, sort of, getting out of sync.

# Steps to Reproduce

1. say that node is synced 95% (i.e. `cardano-wallet-jormungandr network information` reports 95%)
2. I import walletA; it is reporting as syncing 95%
3. then node gets synced 100%
4. walletA becomes 100%
  - all OK to this point, but
5. now node gets unsynced again to 95% ( `cardano-wallet-jormungandr network information` reports 95% cause node does not receive blocks for a while)
6. but walletA still remains at 100% and does not update its state down to 95%
7. I import walletB; it is reporting as syncing with 95% , walletA is still 100%
8. now node gets unsynced again to 85%
9. I import walletC

## Expected behavior

Basically, either the wallet should report 100% from the begining (because it gets synced 100% with the node, only node is not synced with the network) or wallet should update its sync progress when node gets unsynced.

I'm thinking the first option.

## Actual behavior
 
  - walletA is 100% synced
  - walletB is 95% syncing
  - walletC is 85% syncing

---

# Resolution Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #?       | `develop` |

# QA 

```bash
# 1. Launch wallet and jormungandr in separate terminals
$  jormungandr \
     --genesis-block lib/jormungandr/test/data/jormungandr/block0.bin \
     --rest-listen 127.0.0.1:8080 \
     --storage /Users/Johannes/.local/share/cardano-wallet/jormungandr/testnet/chain \
     --secret lib/jormungandr/test/data/jormungandr/secret.yaml \

$ cardano-wallet-jormungandr serve --genesis-block-hash (jcli genesis hash --input lib/jormungandr/test/data/jormungandr/block0.bin) --node-port 8080

# 2. Create a wallet
$ cardano-wallet-jormungandr wallet create wallet

# 3. Ctrl-C jormungandr

# 4. Observe progress dropping when polling
$ cardano-wallet-jormungandr wallet list
```

**Comment by Anviking** [comment]
We store the `SyncProgress` itself in percent in the DB, and update it when we apply blocks.
https://github.com/input-output-hk/cardano-wallet/blob/4b279c2089736bce416fe7bc90b4b574682522b4/lib/core/src/Cardano/Wallet/Primitive/Types.hs#L241

Previously the percentage could only change when we applied blocks. 

Now it is calculated in relation to the current time.

We should seek to remove `syncProgress` from `WalletMeta` and calculate it on the fly when reading a wallet.

*Edit: This is assuming we go with the second option "wallet should update its sync progress when node gets unsynced"*:

**Comment by Anviking** [comment]
> I'm thinking the first option. [either the wallet should report 100% from the begining]

Initially I was sceptical of comparing with the current time too. Now I'm more ambivalent about it. 🤷‍♂

I guess, what makes `syncProgress` useful is knowing that `100%` means the state we're seeing is the state on the network — i.e: 
- another instance of the same wallet hasn't spent our funds
- if we haven't received a tx we expected, it is because it hasn't been included in the ledger yet, not because we are unsynced

which would clearly point towards the second option (keeping progress relative to the network / current time).

cc @KtorZ ?

**Comment by KtorZ** [comment]
Saying that we're synced when we are synced with the node is somewhat misleading. If the node is lagging a lot behind, then the wallet might say that it is restored at 100% whereas it is actually missing many blocks.

That the node isn't able to sync with the network in a timely manner is an issue that the walley shouldn't be trying to solve.

I think @anviking's proposal is sound, we should have only a single source of truth and therefore, compute the progress on the fly from the wallet tip and the current time.

**Comment by KtorZ** [comment]
@Anviking please remember to send this to QA if it's fixed.

**Comment by Anviking** [comment]
This is the sync-progress (y) dropping over time (x) from following the QA section. It seems a bit weird; I wonder if we can do better, but that's another issue:
<img width="660" alt="Skärmavbild 2019-10-30 kl  20 00 23" src="https://user-images.githubusercontent.com/304423/67889939-103e8900-fb50-11e9-98df-ecdb55b250ea.png">

**Comment by KtorZ** [comment]
@Anviking what exactly do you find weird in this graph?

**Comment by Anviking** [comment]
I guess I'd expect it to be linear.

I'd expect that restoring 80%-100% would take twice the time as 90%-100% on a fully synced node.

I could be interested in knowing:
- How far (in time) am I from the network?
- How long will it take me to finish syncing given that I'm at 50%?

With non-linear progress it's much more difficult to build the intuition to answer those questions.

**Comment by KtorZ** [comment]
There's no point trying to build linear progress because it'll never be linear. The main reasons being that:

- All blocks are different, some empty, some not. How long it takes to restore 1,10 or 100 blocks very much depends on what's inside the blocks. 

-  Blocks will not have the same impact on the wallet. A block might contain 10k transaction but takes 100ms to restore because no transactions are of interest. On the contrary, a block might contain 100 txs and take 2s to restore because we have to perform several key derivation to extend our address pool because of discovered txs.

The truth is that we can only really know how long it's gonna take once we have synced 🤷‍♂

**Comment by piotr-iohk** [comment]
@Anviking - I'm wondering. This could be an actual integration test I think... (those steps from QA). Maybe I'd extend it a bit.
- start jormungandr
- start wallet serve
- create wallet and have it 100% synced
- stop jormungandr
- make sure sync is dropping for the wallet
- start jormungandr
- make sure the sync for the wallet is back to 100%

Thoughts?

**Comment by Anviking** [comment]
Hm. Yeah, when you say it, it does sound very plausible.

**Comment by Anviking** [comment]
We'd need a new module with a new setup to control jormungandr. Shouldn't be a problem.

We'd also need to be a able to kill the running jormungandr. This is more of a problem. I _think_ we'd be fine with tweaking existing bracketed launching-functions (to say return a `pid`), but might still be a bit unpleasant if it has cascading effects on other code.

**Comment by Anviking** [comment]
We might also imagine alternative ways of stopping block production without actually killing jormungandr.

Maybe we could move `1 lovelace` from the address that is delegating to the running pool.

**Comment by KtorZ** [comment]
Sounds like something we'd rather do manually for now. May we simply write the steps above as a manual test procedure :)?

**Comment by Anviking** [comment]
--> https://github.com/input-output-hk/cardano-wallet/pull/977

**Comment by piotr-iohk** [comment]
lgtm.
