### ISSUE TITLE
Model API Types for Transactions in Servant

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#93]
# Context

Adding support for transactions. **In a separate issue** (to be created), Transaction-related types will be introduced inside  [WalletLayer](https://github.com/input-output-hk/cardano-wallet/blob/master/src/Cardano/WalletLayer.hs). **This ticket** is about modeling this functionality on the API-level — creating wrapping types, JSON instances, etc.

- Cf https://github.com/input-output-hk/cardano-wallet/wiki/Roadmap#submit-transactions for some additional details

- The API we want to implement is described by our swagger spec https://raw.githubusercontent.com/input-output-hk/cardano-wallet/master/specifications/api/swagger.yaml

- Note: The API layer is under construction in #53 as of currently

# Decision

Add wrapping Transaction-related API types, and extend our Servant API with handlers.

# Acceptance Criteria

1. The API _must_ support creation of transactions according to the API Swagger specification https://raw.githubusercontent.com/input-output-hk/cardano-wallet/master/specifications/api/swagger.yaml
2. The added code _should_ be consistent with existing API Layer code (likely from #53 )

---

# Development Plan

- [x] I plan on adding new transaction endpoint to the Cardano.Wallet.Api module
- [x] I plan on adding missing argument types (Payment, TransactionOutput) to Wallet.Api.Types module
- [x] I plan on adding missing return type (Transaction). This type looks a lot a like transaction meta which will be added by https://github.com/input-output-hk/cardano-wallet/issues/101
- [x] I plan on adding json roundtrip test for arguments and return type
- [x] I plan to remove swagger object renaming rules https://github.com/input-output-hk/cardano-wallet/pull/111#discussion_r273499680
- [x] I plan to increase number of samples for tx status golden test https://github.com/input-output-hk/cardano-wallet/pull/111#discussion_r273472378
- [ ] I plan to document types better https://github.com/input-output-hk/cardano-wallet/pull/111#discussion_r273496483
- [ ] TODO: check whether there are other tests that can increase coverage

# PR

| Number   | Base      |
| ---      | ---       |
| #111        | `master`  |
| #139         | `master`  |
| #184          | `master`  |

# QA 

- API definition is now complete for transaction creation: cf [Cardano.Wallet.Api](https://github.com/input-output-hk/cardano-wallet/blob/master/src/Cardano/Wallet/Api.hs#L97-L111)

- Corresponding API representations have corresponding golden tests roundtrips in [Cardano.Wallet.Api.TypesSpec](https://github.com/input-output-hk/cardano-wallet/blob/master/test/unit/Cardano/Wallet/Api/TypesSpec.hs#L162-L164)

- We do also check that the servant definition matches the API specification (cf: [here](https://github.com/input-output-hk/cardano-wallet/blob/master/test/unit/Cardano/Wallet/Api/TypesSpec.hs#L543-L547))

- The handler's implementation is currently untested but will be as part of #96 or #95

**Comment by KtorZ** [comment]
@akegalj I believe we can put this one in QA now right?

**Comment by akegalj** [comment]
> @akegalj I believe we can put this one in QA now right?

yes - its ready

**Comment by piotr-iohk** [comment]
lgtm :+1:
