### ISSUE TITLE
Unreliable test cases in CI

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#931]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Windows & OSX & Linux) | Code  v Configuration |

# Context
 
 

https://buildkite.com/input-output-hk/cardano-wallet/builds/3377#97b21363-a48b-4a51-9787-eb22ff210771/6-7571

https://buildkite.com/input-output-hk/cardano-wallet/builds/3308#c9de0620-ac75-4a16-95b1-7bf2b37dd666/6-7555

https://buildkite.com/input-output-hk/cardano-wallet/builds/3307#7eb3b6dd-7a93-4989-a033-fcc042bf26d5/6-7564

https://buildkite.com/input-output-hk/cardano-wallet/builds/3283#88ba9e84-0cb0-43ea-98f9-2e8d9cf40953/6-7560

https://buildkite.com/input-output-hk/cardano-wallet/builds/3524

https://buildkite.com/input-output-hk/cardano-wallet/builds/3525
https://buildkite.com/input-output-hk/cardano-wallet/builds/3524

# Steps to Reproduce

Unclear. The test sometimes fail. 

## Expected behavior

The test is not flaky and can be trusted.

## Actual behavior
 
<A clear and concise description of what you observe instead. If applicable add screenshots to help explain your problem.>

:man_shrugging: 

---

# Resolution Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #?       | `develop` |

# QA

**Comment by rvl** [comment]
I noticed this message in the logs of the first buildkite build (3377) listed in this ticket:
```
    thread 'Oct 29 10:23:27.014leadership1 ' panicked at 'CRITnot yet implemented: The system just failed to compute an appropriate instant.
    This could be due to a system suspension or hibernation, in order not to miss out on future
    leader elections please prevent your system from suspending or hibernating.
     ', system recorded a 0s delay. This could be due to a system suspension or hibernation, in order not to miss out on future leader elections please prevent your system from suspending or hibernating.jormungandr/src/leadership/mod.rs, :epoch244:: 175380849
    , note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
    reason: second time provided was later than self, slot_system_time: 2019-10-29T10:23:27+00:00, now: 2019-10-29T10:23:27.014508974+00:00, task: leadership
    not yet implemented: The system just failed to compute an appropriate instant.
    This could be due to a system suspension or hibernation, in order not to miss out on future
    leader elections please prevent your system from suspending or hibernating.
```
That would probably explain the `ExitFailure 66`.

**Comment by rvl** [comment]
input-output-hk/jormungandr#982

**Comment by jonathanknowles** [comment]
https://hydra.iohk.io/build/1330205

**Comment by jonathanknowles** [comment]
Another one:
https://hydra.iohk.io/build/1339268/nixlog/68/tail
https://hydra.iohk.io/build/1339268

**Comment by KtorZ** [comment]
We could try increasing a bit the epoch length. We've set it to 3 seconds and it seems to be causing issues as explained in this comment:

> If the end of epoch/start of new epoch happens between node start time and leadership task start/process time

**Comment by KtorZ** [comment]
I believe this one can be closed in favor of another item "re-enable code coverage calculations in CI". 

@piotr-iohk , thoughts?

**Comment by piotr-iohk** [comment]
Sounds good.

>"re-enable code coverage calculations in CI"

Something to plan for recovery week I suppose?

**Comment by KtorZ** [comment]
Possibly, although I'd just create a JIRA story for that one. This is important enough for us to spend a proper time on this.

**Comment by KtorZ** [comment]
Done: https://jira.iohk.io/projects/WB/issues/WB-30?

**Comment by piotr-iohk** [comment]
Although it is not a product feature, I understand it goes to Jira so we can book relevant amount of time for this, and also let product now about how important it is... :man_shrugging:
