### ISSUE TITLE
Technical Debts from v0.0.1

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#94]
# Context

During the development of [v0.0.1](https://github.com/input-output-hk/cardano-wallet/releases/tag/v0.0.1), we have accumulated some technical debts we may get rid of while getting started with this next release. 

#### Poor README

| Module | Comments | PR |
| --- | --- | --- |
| - | Our README is quite poor in information and it would be worth adding some basics stuff to it. That's a point Johannes already raised on the legacy repository actually. We could add at least: </br> - Basic Overview / Goal<br/>- Build & Tests instructions<br/>- A link to the wiki<br/>- Link to the generated Haddock documentation<br/>- Link to the API documentation | #98 |

#### Areas missing testing:

| Module                                     | Comments             | PR  |
| ---                                        | ---                                                                                                                                                     | --- |
| `Cardano.DBLayer` & `Cardano.DBLayer.MVar` | - Pretty much all function <br/> -`readCheckpoints` in particular _(tested manually during profiling)_                                                  | #88 |
| `Cardano.NetworkLayer`                     | -`listen` _(tested manually during profiling)_                                                                                                          | #115  |
| `Cardano.NetworkLayer.HttpBridge`          | - Error cases from `convertError`                                                                                                                       | Won't Cover - Testing in the http bridge is good enough at the moment, let's not spend too much time either on a component that is temporary. |
| `Cardano.Wallet`                           |  - Wallet metadata manipulation <br/> -`currentTip` _(tested manually during profiling)_                        | N/A anymore (tackled by other tickets) |
| `Cardano.Wallet.AddressDerivation`         | - Overflow on address indexes                                                                                                                           | |
| `Cardano.Wallet.AddressDiscovery`          | - Overflow on address indexes during pool extension <br/> - `IsOurs` & `isOurs`                                                                         | |
| `Cardano.Wallet.Binary`                    | - Decoding EBB _(discarded by network layer)_ <br/> - Invalid constructors in block representations <br/> - Decoding redeem addresses & witnesses _(?)_ | |
| `Cardano.Wallet.Binary.Packfile`           | - Some error paths (`VersionTooOld` & `BlobDecodeError` with unconsumed data)                                                                           | #98 |
| `Cardano.Wallet.Mnemonic`                  | - Error cases in `mkMnemonic` <br/> - Error cases in `genEntropy`                                                                                       | #106 |
| `Cardano.Wallet.Primitive`                 | - Arithmetic overflow on `SlotId`                                                                                                                       | #126 |

#### Unused code 

| Module                            | Comments                                                                     | PR  |
| ---                               | ---                                                                          | --- |
| `Cardano.Wallet.AddressDiscovery` | - Manual semigroup instance on `AddressPool`                                 |   #120  | 
| `Cardano.WalletLayer`             | - Debug `printInfo` function in the implementation of `watchWallet`          |  #115   |
| `Servant.Extra.ContentTypes`      | - `WithHash` & `Hash "Blockheader"` in the `Cardano.NetworkLayer.HttpBridge` | #86 | 

#### Integration framework

| Module                            | Comments                                                                     | PR  |
| ---                               | ---                                                                          | --- |
| `Test.Integration.Framework` | ability to explicitly set request headers in order to verify destructive scenarios  |  #122   | 
| `Test.Integration.Framework` | ability to construct and send non-valid JSON request body in order to test destructive scenarios | #131     | 

# Decision

From the various points stated above, evaluate whether they are relevant and, fix them when they are, or leave an appropriate comment in the code giving details or insight about the decision.

# Acceptance Criteria

1. We _must_ have looked into the various points above, and either tackled them or discarded them with a proper justification.

---

# QA

**Comment by paweljakubas** [comment]
I am taking `Cardano.NetworkLayer.HttpBridge    - Error cases from convertError`

**Comment by KtorZ** [comment]
I'll look into removing unused code from the WalletLayer & testing the `listen` and `watchWallet` functions through integration tests.

**Comment by KtorZ** [comment]
Looking into quickly adding tests for the overflow cases.

**Comment by KtorZ** [comment]
Closing as discussed. We'll open a new ticket for the next iteration with new debts.
