### ISSUE TITLE
Let CLI client connect to remote hosts

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#949]
# Context

The wallet server can listen on interfaces other than localhost (#833).

The wallet CLI client ought to be able to connect to addresses other than localhost. Relevant to these situations:

- Connecting to a wallet server on a remote host.
- Connecting to the wallet server within a docker container.

# Decision

Change the CLI `--port=8090` argument to something like `--server=localhost:8090`.
Use the given hostname when forming the API client base URL.

# Acceptance Criteria

- [ ] It's possible to use the CLI client to connect to a wallet server listening on a remote host.
- [ ] The default host and port must remain localhost:8090.

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #?       | `master`  |

# QA

**Comment by KtorZ** [comment]
Moved to `cardano-wallet-laboratory` -> https://github.com/input-output-hk/cardano-wallet-laboratory/issues/14

**Comment by runeksvendsen** [comment]
I would really appreciate this feature. Would you accept a PR? The https://github.com/input-output-hk/cardano-wallet-laboratory/issues/14 gives me a 404.
