### ISSUE TITLE
Invalid Address first byte - error message could be more user-friendly.

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#953]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Windows & OSX & Linux) | Code  v Configuration v Environment v Human v Unknown |

# Context
 
Sending tx for account address e.g.:
```
$ jcli address account $(jcli key generate --type=Ed25519 | jcli key to-public) --testing
ca1s4z7nlvu700ltv0ak2xnpf25a33tzkdu34gl34cvrwtde0jda2al7t2fwgx
```
```
$ jcli address account --prefix patate $(jcli key generate --type=Ed25519 | jcli key to-public) --testing
patate1shtgjpqxkppa57k4v027upv06m46uaxve0l8s84mr6e0u2j9esjtwwsl30y
```

produces error message:

```
"Error in $.payments[0].address: Invalid Address first byte."
```

The message could be made more friendly and informative.

Tests are here -> https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Cardano/Wallet/Primitive/AddressDiscoverySpec.hs

# Steps to Reproduce

```
curl  -vX POST http://localhost:8090/v2/wallets/617963656a409b8a6828dc3a09001de22af90400/transactions \
  -H "Content-Type: application/json; charset=utf-8" \
  -d '{
"payments": [
{
	"address": "ca1s4z7nlvu700ltv0ak2xnpf25a33tzkdu34gl34cvrwtde0jda2al7t2fwgx",
	"amount": {
								"quantity": 100,
								"unit": "lovelace"
				}
} ], 
 "passphrase": "Secure Passphrase"
}' | jq
```

## Expected behavior

```
{
  "code": "bad_request",
  "message": "Error in $.payments[0].address: This type of address (account) is not supported."
}
```

## Actual behavior
 
```
{
  "code": "bad_request",
  "message": "Error in $.payments[0].address: Invalid Address first byte."
}
```

---

# Resolution Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #985       | `master` |
| #987      | `master` |

# QA 

Messages have been polished, Appropriate tests have been updated to assert for new messages.

**Comment by piotr-iohk** [comment]
There is also another unpleasant case found by @jonathanknowles.
When the payload does not parse correctly there is this error: `"34: Failed reading: satisfy"`. Could be made more friendly and informative too.

e.g.:

```
curl  -vX POST http://localhost:8090/v2/wallets/617963656a409b8a6828dc3a09001de22af90400/transactions \
  -H "Content-Type: application/json; charset=utf-8" \
  -d '{
"payments": [
{
	"address": "ca1s4z7nlvu700ltv0ak2xnpf25a33tzkdu34gl34cvrwtde0jda2al7t2fwgx",
	"amount": {
		     "quantity": 100,
		     "unit": "lovelace",
				}
} ], 
 "passphrase": "Secure Passphrase"
}' | jq
```
(note: the payload is invalid, notice additional `,` after `"lovelace"`)
:point_down: 
```
{
  "code": "bad_request",
  "message": "34: Failed reading: satisfy"
}
```

**Comment by piotr-iohk** [comment]
We do have several cases for invalid payload but never verified the error message somehow -> e.g. https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core-integration/src/Test/Integration/Scenario/API/Wallets.hs#L791-L808

(there are few others, to find search for `NonJson`)

**Comment by KtorZ** [comment]
> Could be made more friendly and informative too.

This could be difficult. This error is from `aeson` (the library we use to parse JSON) and we don't have much control over it as the error occurs before it reaches our application layer (the `wai/servant` application is catching that for us).

Maybe we can "adjust" the error afterwards in the middleware we already use to rewrap servant errors: 

https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/src/Cardano/Wallet/Api/Server.hs#L1562-L1608

**Comment by KtorZ** [comment]
More specifically: this line https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/src/Cardano/Wallet/Api/Server.hs#L1562-L1608 could instead do some extra inspection of the underlying error and adjust the error message with something more user friendly.

**Comment by jonathanknowles** [comment]
@KtorZ @piotr-iohk

It seems as though both problems described in this issue have been addressed. Should we close the issue?

**Comment by piotr-iohk** [comment]
:ok_hand:
