### ISSUE TITLE
--logging-config FILE.YAML more info and tests required

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#961]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Windows & OSX & Linux) | Code  v Configuration v Environment v Human v Unknown |

# Context
 
As part of #851 there was this option provided for `launch` and `serve` commands:

```
  --logging-config FILE.YAML
                           File to configure the iohk-monitoring framework.
```

The format of the file is somewhat unknown and it should be provided by iohk-monitoring team.
We need to have it documented https://github.com/input-output-hk/cardano-wallet/wiki/Wallet-command-line-interface and/or link to appropriate resource added. Also information about default values needs to be provided.

We should also have some tests illustrating the behavior of `--logging-config`.
 

# Steps to Reproduce

## Actual behavior
 
<A clear and concise description of what you observe instead. If applicable add screenshots to help explain your problem.>

---

# Resolution Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #1253        | `master` |

# QA

**Comment by paweljakubas** [comment]
In the end, we removed logging-config in #1253. wiki was also updated accordingly
