### ISSUE TITLE
wallet should accept a --node-bin arg

### ISSUE THREAD

**Issue by cleverca22** [cardano-foundation/cardano-wallet#963]
wallet should accept a `--node-bin /path/to/jormungandr` flag
it should route the result to here: https://github.com/input-output-hk/cardano-wallet/blob/dcc30d4d077126beed47cdbebc3008885653a2ea/lib/jormungandr/src/Cardano/Wallet/Jormungandr/Network.hs#L497

| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Windows & OSX & Linux) | Code  v Configuration v Environment v Human v Unknown |

# Context
 
 

# Steps to Reproduce

1. ...

## Actual behavior
 
<A clear and concise description of what you observe instead. If applicable add screenshots to help explain your problem.>

---

# Resolution Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #?       | `develop` |

# QA

**Comment by rvl** [comment]
There's no need for a CLI option.

On Linux and macOS just set the `PATH` variable before spawning the `cardano-wallet-jormungandr` child process.

On Windows, ensure the two exes are installed in the same directory.
