### ISSUE TITLE
SQLite DB state machine test failure.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#996]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next | Linux | Code |

# Context

First seen here: 

https://hydra.iohk.io/build/1338908
https://hydra.iohk.io/build/1338908/nixlog/23
 
# Steps to Reproduce

Run the following command:
```
stack build \
    --test cardano-wallet-core:test:unit \
    --ta '--seed 1736278700' \
    --ta '--match "Sequential state machine tests"'
```
## Expected behaviour

The tests pass.

## Actual behaviour
 
The tests do not pass:
```hs
PostconditionFailed "PredicateC (Resp (Right (Metadata (Just (WalletMetadata {name = WalletName {getWalletName = \"charmander\"}, creationTime = 2096-07-20 08:00:00 UTC, passphraseInfo = Just (WalletPassphraseInfo {lastUpdatedAt = 2769-03-31 20:10:53 UTC}), delegation = Delegating (PoolId {getPoolId = \"de93c1d4404bded49254700a42172901\"})})))) :/= Resp (Right (Metadata (Just (WalletMetadata {name = WalletName {getWalletName = \"charmander\"}, creationTime = 2096-07-20 08:00:00 UTC, passphraseInfo = Just (WalletPassphraseInfo {lastUpdatedAt = 2769-03-31 20:10:53 UTC}), delegation = Delegating (PoolId {getPoolId = \"447f333b6d629daccfc965226e51b766\"})})))))" /= Ok
```

---

# Resolution Plan

- Revise the primary key on `DelegationCertificate` table
- Use `repsert` instead of `insert_`, or make sure that the database fails if trying to insert at the same slot twice :thinking: ?

# PR

| Number   | Base      |
| ---      | ---       |
| #997        | `master` |

# QA 

- Test was re-run 10k times after fix to control that everything was okay.

**Comment by piotr-iohk** [comment]
lgtm.
